### ISSUE TITLE
Consume core updates: inline edit (Table) ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#10003]
Follow up to core issue https://github.com/patternfly/patternfly/issues/5736

**Comment by thatblindgeye** [comment]
Comparing the [deprecated editable rows table example in v6](https://patternfly-react-v6.surge.sh/components/table/react-deprecated#editable-rows) to the [core v6 inline editable table example](https://pf6.patternfly.org/components/inline-edit#inline-edit-table-row), there may not really be any updates needed in React. Core is still using the deprecated Dropdown for the kebab toggle, and React is using the deprecated Select, which should be the only differences (aside maybe from icons).

**Comment by thatblindgeye** [comment]
cc @mcoker @andrew-ronaldson for above comment

**Comment by mcoker** [comment]
@thatblindgeye LGTM!

**Comment by thatblindgeye** [comment]
Closing per agreements above (Andrew left thumbs up emoji on my comment)
