### ISSUE TITLE
Consume core Penta updates: Timestamp

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#10006]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6196

**Comment by andrew-ronaldson** [comment]
This looks good. I don't think this needs react follow up.

**Comment by srambach** [comment]
Looks good from the core standpoint. 🕙 📆

**Comment by andrew-ronaldson** [comment]
Closing. No react follow up needed
