### ISSUE TITLE
Consume core updates: Wizard ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#10009]
follow up to core issue https://github.com/patternfly/patternfly/issues/5742

**Comment by kmcfaul** [comment]
Doesn't appear to need any react updates. Can core/design confirm the react side still appears correct?

@patternfly/design-reviewers
@patternfly/core-in-react-reviewers

**Comment by kmcfaul** [comment]
Wizard will need a followup to address direct token usage in `WizardNavItem` after https://github.com/patternfly/patternfly/issues/5142 is resolved and merged.

**Comment by mcoker** [comment]
Other than [this comment](https://github.com/patternfly/patternfly-react/issues/10009#issuecomment-1957174546), LGTM!

**Comment by kmcfaul** [comment]
Just need design once-over @patternfly/design-reviewers
