### ISSUE TITLE
Consume tokens: Overflow menu

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#10012]
Depends on https://github.com/patternfly/patternfly-react/issues/9985 and https://github.com/patternfly/patternfly-react/issues/9986 https://github.com/patternfly/patternfly/issues/6166

**Comment by wise-king-sullyman** [comment]
It doesn't look like any classname related changes are needed in React, and per design it already looks good on staging, so this issue can be closed.
