### ISSUE TITLE
PF4 DropdownToggle needs optional aria-label prop

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#1003]
If a `<DropdownToggle>`'s content (label) is an icon, there needs to be a way to make the icon accessible.  It seems an optional `aria-label` is the way to solve this (which is what `<Button>`s do).  See screenshot below including a `<Button>` and `<DropdownToggle>`.

cc: @matthewcarleton 

![screen shot 2018-12-03 at 2 01 14 pm](https://user-images.githubusercontent.com/895728/49397644-2eb2bf00-f70a-11e8-8961-b6d8420a1e6d.png)

**Comment by jgiardino** [comment]
@rhamilto, I _think_ this is currently supported with the [KebabToggle Props](https://patternfly-react.surge.sh/patternfly-4/components/dropdown#KebabToggle) but please take a look and confirm if this supports what you're expecting, or if not, please describe what you would expect instead. Currently, it looks like the `aria-label` props will default to a value of "Actions" if not specified.

**Comment by rhamilto** [comment]
The problem is `<KebabToggle>` will always output [`<EllipsisVIcon />`](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Dropdown/KebabToggle.js#L10).  We need the ability to use any icon with `<DropdownToggle>` and provide an `aria-label`.

**Comment by jgiardino** [comment]
Ah, ok. Thanks for the clarification!

**Comment by jgiardino** [comment]
Just wanted to follow up on this one with another question. 😄 

Looking at what we have in core, I would expect the following example of a dropdown is possible in the context of the page banner (i.e. the cog icon with the dropdown arrow). And that this issue should make sure that this variation of a dropdown with aria-label defined is possible in the pf-react implementation.

![image](https://user-images.githubusercontent.com/21063328/49450383-dc75aa80-f7aa-11e8-8033-8afb8b7b5fa8.png)

@rhamilto It looks like in your example that there isn't a dropdown arrow with the icon that you're using as a dropdown toggle. Is your expectation that you should be able to display an icon other than kebab without an arrow? If so, then we might need to bring up this issue in the context of the core repo.

**Comment by jschuler** [comment]
I believe all of this is already possible
```
<Dropdown
        **isPlain**
        toggle={<DropdownToggle **aria-label="Help"** **iconComponent={null}** onToggle={this.onToggle}>**<HelpIcon />**</DropdownToggle>}
        isOpen={isOpen}
        dropdownItems={dropdownItems}
      />
```
isPlain: Removes the border
iconComponent to null: Removes the caret down icon
HelpIcon: The icon to show
aria-label: Gets applied to the Button
<img width="351" alt="screen shot 2018-12-04 at 10 16 10 am" src="https://user-images.githubusercontent.com/869106/49451672-b30a4e00-f7ad-11e8-8445-5a6c25b044f3.png">
<img width="168" alt="screen shot 2018-12-04 at 10 16 25 am" src="https://user-images.githubusercontent.com/869106/49451675-b6053e80-f7ad-11e8-8b2a-346e2fd88e55.png">

**Comment by jgiardino** [comment]
Oh, nice! Thanks for providing the example, @jschuler!

@rhamilto Will you confirm whether this solution provides what you're looking for, and if we can close this issue?

**Comment by rhamilto** [comment]
> @rhamilto It looks like in your example that there isn't a dropdown arrow with the icon that you're using as a dropdown toggle. Is your expectation that you should be able to display an icon other than kebab without an arrow? If so, then we might need to bring up this issue in the context of the core repo.

@priley86 did the implementation of the dropdown and explicitly excluded the arrow.  I'm not sure why.

@jschuler is correct.  `<DropdownToggle>` accepts an `aria-label` prop, but the docs do not indicate it.  So the bug is one of documentation?

![screen shot 2018-12-04 at 11 45 18 am](https://user-images.githubusercontent.com/895728/49458092-1e5a1d00-f7ba-11e8-9c3d-c86a72600d92.png)

**Comment by jgiardino** [comment]
Good call on updating the documentation. @jschuler is this issue sufficient for that, or should we create a new issue?

For the dropdown arrow, it sounds like we aren't blocking you (?) so I would just defer to whatever your designers are recommending, or reach out to one of the pf designers if you want a second opinion.

**Comment by jschuler** [comment]
Closing this issue, and handling the documentation issue in #1018
