### ISSUE TITLE
Multiple consecutive h1's and duplicate ID's for Page Layout examples

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#1004]
In general, headings should always be followed by a body of text and increase one size at a time on a page. While browser around the docs, I found this isn't always the case, take for example http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout

<img width="790" alt="screen shot 2018-12-03 at 3 14 36 pm" src="https://user-images.githubusercontent.com/5942899/49399321-fbbefa00-f70e-11e8-92db-709f4c647dda.png">

It's strange that there are three h1's in a row. To make this better, the `Title` component needs to be extended to allow for the range of possible heading levels.

There are also duplicate ID's "#nav-toggle" in the demos, so users copy/pasting from our code examples inherit those bugs automatically. It would be good to clean this up a little, so the initial getting started experience is smoother.

**Comment by rachael-phillips** [comment]
Are we ready to close this issue?

**Comment by seanforyou23** [comment]
@rachael-phillips yep!
