### ISSUE TITLE
Bug - HelperText - props table not rendering in 

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#10058]
**Describe the problem**
Mentioned in comment https://github.com/patternfly/patternfly-react/pull/10029#pullrequestreview-1856625656 , the props table for HelperText isn't rendering in the v6 branch.

**How do you reproduce the problem?**
Go to the [Helper Text props in v6 staging](https://patternfly-react-v6.surge.sh/components/helper-text#props)

**Expected behavior**
A clear and concise description of the expected behavior.

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by tlabaj** [comment]
closed by org PR #https://github.com/patternfly/patternfly-org/pull/3981
