### ISSUE TITLE
Bug - Truncate - tooltip also shows when there is no actual truncation

### ISSUE THREAD

**Issue by mvollmer** [patternfly/patternfly-react#10053]
The [Truncate](https://www.patternfly.org/components/truncate) component always has a active tooltip for its content, even when there is no actual need for truncation:

![image](https://github.com/patternfly/patternfly/assets/3228183/c4a932a3-95d8-4047-a60b-94ecd2364c86)

Such a tooltip doesn't contribute anything to the user experience, but is an annoyance especially if there are many of them.

It would be great if `Truncate` would only have a tooltip when truncation does actually take place.

Alternatively, as a lesser alternative, a property would be welcome that allows the programmer to disable the tooltip completely.

**Comment by tlabaj** [comment]
cc @andrew-ronaldson @mmenestr

**Comment by andrew-ronaldson** [comment]
If the full text is visible then it can be an unnecessary distraction to have tooltip flashing up so I think we can address this.
