### ISSUE TITLE
Bug - [react-charts] - [TypeError: Cannot read property 'primitiveProps' of undefined]

### ISSUE THREAD

**Issue by sjha4** [patternfly/patternfly-react#10064]
**Describe the problem**
`import { ChartPie } from '@patternfly/react-charts';`
fails with
```
TypeError: Cannot read property 'primitiveProps' of undefined
at Object.<anonymous> (../foreman/node_modules/@patternfly/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx:111:18)
      at Object.<anonymous> (../foreman/node_modules/@patternfly/react-charts/src/components/ChartCursorTooltip/index.ts:1:1)
```

This is probably because the package victory-core had a new release 36.9.0 which includes this change:
https://github.com/FormidableLabs/victory/pull/2758
which seems to break the following use of `CommonProps`
https://github.com/patternfly/patternfly-react/blob/36c91439e10543ffcab706630d035a9a5f8da161/packages/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx#L3

**How do you reproduce the problem?**
importing from ` '@patternfly/react-charts';` for version 6.94.15 throws this error. Likely reproducible in other 6.94.z versions. 

**Is this issue blocking you?**
We'll probably pin victory-core package at an older version locally.

**Comment by boldchains** [comment]
I have same issue, is this resolved?

**Comment by tlabaj** [comment]
cc @dlabrecq

**Comment by dlabrecq** [comment]
PatternFly charts currently uses "^36.8.1". In fact we just updated it for the latest PatternFly milestone.
Unfortunately, Victory 3.9 (released a couple days ago) has not been tested.

**Comment by tadayosi** [comment]
It appears we have the same issue [^1]. For us, upgrading `@patternfly/react-charts` from 7.1.2 to 7.2.0 leads:
```
Attempted import error: 'CommonProps' is not exported from 'victory-core' (imported as 'CommonProps').
```
[^1]: https://github.com/hawtio/hawtio-next/pull/771

**Comment by sjd78** [comment]
> PatternFly charts currently use "^36.8.1". In fact, we just updated it for the latest PatternFly release. Victory 3.9.0 (released days ago) has not been tested, but appears to introduce some type changes.

Version `36.9.1` satisfies the semver `^36.8.1`.

When I updated my project's dependency to `"@patternfly/react-charts": "^7.1.0"` today, the new version of victory-core got picked up and causes this super awesome dev server overlay:
![image](https://github.com/patternfly/patternfly-react/assets/3985964/916d74b0-0fb3-4cf1-9f59-21a5305d31e1)

Once this issue gets resolved (maybe pin the exact version of victory to `36.8.1`, or at least use tilda instead of `~36.8.1` to only pickup new z-stream releases) I can update my app to PF5.2.

**Comment by matborowczyk** [comment]
issue occured to us when upgrading to version 7.2.0

`   1 | import React from "react";
    > 2 | import { ChartDonut } from "@patternfly/react-charts";
        | ^
      3 | import {
      4 |   global_danger_color_100,
      5 |   global_info_color_100,

      at Object.<anonymous> (node_modules/@patternfly/react-charts/src/components/ChartCursorTooltip/ChartCursorFlyout.tsx:111:18)
      at Object.<anonymous> (node_modules/@patternfly/react-charts/src/components/ChartCursorTooltip/ChartCursorTooltip.tsx:16:1)
      at Object.<anonymous> (node_modules/@patternfly/react-charts/src/components/index.ts:16:1)
      at Object.<anonymous> (node_modules/@patternfly/react-charts/src/index.ts:1:1)`
