### ISSUE TITLE
Update popover in Password Strength demo

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#10071]
**Describe the enhancement or change**
Currently the popover in the Password Strength has content related to mentioning password requirements. In general that sort of content shouldn't be hidden in a popover and instead displayed below the input, which the demo is already doing.

We should either remove the help popover or update its content to something more along the lines of "why does a strong password matter" or something along those lines.

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

**Comment by tlabaj** [comment]
Let's remove the help icon and popover.
