### ISSUE TITLE
SPIKE - charts - investigate echarts charting package

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#10074]
How does echarts compare to Victory charts?

Would it be relatively straight forward to apply PF look/feel to echarts (colors, tooltips, legends, etc)?
Would it be relatively straight forward to apply dark theme? enable right to left language support? enable accessibility features like patterned charts?

How do their APIs and level of active maintenance compare?
Does echarts offer unique charts not already offered in Victory charts?

**Comment by tlabaj** [comment]
@dlabrecq Thank you for the investigation and presentation.  We will be closing this issue.  Feel free open any follow up issues.
