### ISSUE TITLE
Bug - Charts - 'CommonProps' not found

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#10078]
Ansible cannot upgrade to latest PF because of `CommonProps` no longer being exported from `victory-core`.

Can we provide a workaround or figure out the source of this update?

```
 @patternfly/patternfly      5.1.0  →  5.2.0
 @patternfly/react-charts    7.1.2  →  7.2.0
 @patternfly/react-core      5.1.2  →  5.2.0
 @patternfly/react-icons     5.1.2  →  5.2.0
 @patternfly/react-table     5.1.2  →  5.2.0
 @patternfly/react-topology  5.1.0  →  5.2.0
```
```
WARNING in ./node_modules/@patternfly/react-charts/dist/esm/components/ChartCursorTooltip/ChartCursorFlyout.js 87:62-88
export 'CommonProps' (imported as 'CommonProps') was not found in 'victory-core' (possible exports: Arc, Axis, Background, Border, Box, Circle, ClipPath, Collection, Data, DefaultTransitions, Domain, Events, Helpers, Hooks, Immutable, LabelHelpers, Line, LineHelpers, LineSegment, Log, Path, Point, PointPathHelpers, Portal, PortalContext, Rect, Scale, Selection, Style, TSpan, Text, TextSize, Timer, TimerContext, Transitions, UserProps, VictoryAccessibleGroup, VictoryAnimation, VictoryClipContainer, VictoryContainer, VictoryLabel, VictoryPortal, VictoryTheme, VictoryTransition, Whisker, Wrapper, addEvents)
```

**Comment by dlabrecq** [comment]
Closing as a dup of https://github.com/patternfly/patternfly-react/issues/10064.

**Comment by Srashti-jain58** [comment]
> Ansible cannot upgrade to latest PF because of `CommonProps` no longer being exported from `victory-core`.
> 
> Can we provide a workaround or figure out the source of this update?
> 
> ```
>  @patternfly/patternfly      5.1.0  →  5.2.0
>  @patternfly/react-charts    7.1.2  →  7.2.0
>  @patternfly/react-core      5.1.2  →  5.2.0
>  @patternfly/react-icons     5.1.2  →  5.2.0
>  @patternfly/react-table     5.1.2  →  5.2.0
>  @patternfly/react-topology  5.1.0  →  5.2.0
> ```
> 
> ```
> WARNING in ./node_modules/@patternfly/react-charts/dist/esm/components/ChartCursorTooltip/ChartCursorFlyout.js 87:62-88
> export 'CommonProps' (imported as 'CommonProps') was not found in 'victory-core' (possible exports: Arc, Axis, Background, Border, Box, Circle, ClipPath, Collection, Data, DefaultTransitions, Domain, Events, Helpers, Hooks, Immutable, LabelHelpers, Line, LineHelpers, LineSegment, Log, Path, Point, PointPathHelpers, Portal, PortalContext, Rect, Scale, Selection, Style, TSpan, Text, TextSize, Timer, TimerContext, Transitions, UserProps, VictoryAccessibleGroup, VictoryAnimation, VictoryClipContainer, VictoryContainer, VictoryLabel, VictoryPortal, VictoryTheme, VictoryTransition, Whisker, Wrapper, addEvents)
> ```

same issue persisting but I am having an error of this.
