### ISSUE TITLE
Calendar month - broken link in docs

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#10076]
This link is hard coded to `/v4` - should probably be a relative link instead?

https://github.com/patternfly/patternfly-react/blob/8152e851ddfb649ab2ae4b4405d848e74416f771/packages/react-core/src/components/CalendarMonth/examples/CalendarMonth.md?plain=1#L20

Can be updated with https://github.com/patternfly/patternfly-react/issues/9998

**Comment by thatblindgeye** [comment]
Closed by #10089
