### ISSUE TITLE
Radio Component Audit

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#1007]
1. What is the interaction difference between the Controlled and Uncontrolled Radio. I'm assuming that the Uncontrolled Checkbox would be like the Uncontrolled Switch, where the user cannot manipulate its state? Right now I can check it.

2. Custom Label Radio should be removed from the React example as there is no example in Core or in Wireframes. @mcarrano do we want to create an issue for this Custom label radio with the badge?

3. Radio buttons are meant to be mutually exclusive (you can only select one radio button from the group -- see in Core). The Controlled Radio example currently works so that once you select an unchecked radio button, the previous radio button does not uncheck, meaning every item in the group gets selected. Can we fix this functionality so that only one radio button can be selected at a time.

**Comment by mcarrano** [comment]
I cannot think of a use case for the Custom label radio button and would be fine to see this removed. Also agree with @christiemolloy that we should be demonstrating hwo the radio buttons work as a group.

**Comment by jgiardino** [comment]
Additionally, in core, we explicitly define a label using the `<label>` `for` attribute. But react examples do this in addition to defining `aria-label`. For radio inputs, this results in the input being announced twice (i.e. two separate key presses), once for the `aria-label` and once for the `<label>`.

**Comment by rebeccaalpert** [comment]
[Controlled components](https://reactjs.org/docs/forms.html#controlled-components) manage data within the component (through state and event handlers), while [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html) just handle data via the DOM. The behavior should be the same for both.

I'm addressing all the comments in https://github.com/patternfly/patternfly-react/pull/1269.
