### ISSUE TITLE
Expandable card/Expandable section consistency

### ISSUE THREAD

**Issue by fhlavac** [patternfly/patternfly-react#10088]
When comparing the Expandable card component to the Expandable section I noticed that the expand toggle icon changes color (black/grey) on focus for the card and not for the expandable section
https://www.patternfly.org/components/card#expandable-cards
https://www.patternfly.org/components/expandable-section
Not sure if that's intentional. It might be worth making the experience consistent.

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**
PatternFly React component groups extension - no deadline

**Comment by tlabaj** [comment]
cc @mcoker
