### ISSUE TITLE
DualListSelector - apply penta updates to next component

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#10091]
Ensure penta styling updates also gets applied to the next version of DLS.

**Comment by kmcfaul** [comment]
DualListSelector next looks good to me for penta, no changes needed like the current DLS. Checked latest on v6 locally (@nicolethoen I'm not seeing DLS-next on the v6 staging surge though?)

cc @patternfly/core-in-react-reviewers @patternfly/design-reviewers to verify.

**Comment by mcoker** [comment]
LGTM 👍👍

**Comment by andrew-ronaldson** [comment]
Winner winner chicken dinner.
LGTM
