### ISSUE TITLE
Bug - [UploadFile] - [Can't upload system files]

### ISSUE THREAD

**Issue by avivtur** [patternfly/patternfly-react#10092]
**Describe the problem**
Trying to upload a system file (like ssh pub key) is not allowed anymore.
This is a regression as PF4 did allow this.

**How do you reproduce the problem?**
Go to [PF docs > FileUpload](https://www.patternfly.org/components/file-upload/simple-file-upload/) and try to upload an SSH public key, A window alert will pop from the browser and prevant this action

**Expected behavior**
The upload should occur regularly

**Is this issue blocking you?**
I couldn't find any workaround

**Screenshots**

https://github.com/patternfly/patternfly-react/assets/67270715/b160a910-7bb7-4303-adf0-9c391c3f202d

**What is your environment?**
 - Browser Chrome (on firefox it works fine)
 - Version 5.1.1

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by avivtur** [comment]
workaround: I've managed to upload a public key, as long as it's not coming from the `.ssh` directory.

**Comment by sunsetZaza** [comment]
It could be the folder permissions on the .ssh folder are set in a way that is preventing read/upload of the public key.

**Comment by avivtur** [comment]
Hi @sunsetZaaZa

> It could be the folder permissions on the .ssh folder are set in a way that is preventing read/upload of the public key.

Well it worked just fine in v4, I assume that an extra layer of security added to the component, maybe by 3rd party package?
I'm hoping there's a way to override this and allow uploading from any directory, without having to change directory permissions for this

**Comment by avivtur** [comment]
@sunsetZaaZa Hi :) 
Do you know if there's any update on this issue?

**Comment by sunsetZaaZa** [comment]
because it's not a legitimate bug
