### ISSUE TITLE
Bug - ClipboardCopy - preview for expansion variant does not stringify properly for all allowed types

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-react#10106]
**Describe the problem**
Follow up to #9711 as the previous fix had to be reverted because it was an unintentional breaking change.

The new approach should solve the issue **without** limiting the allowed types of ClipboardCopy to only a string.

A potential solution is that:

- the expansion preview (or maybe expansion variant?) should not allow react node child
- documentation is improved to let users know that if they do indeed pass something other than string as the child, they will need to override onCopy

**Expected behavior**
Expansion variants do not provide an improperly stringified preview

**Screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/7115053/75492ec7-9104-42fc-95c4-aa9e9652e693)

CC @gitdallas

**Comment by gitdallas** [comment]
Although I'm unsure what people may want to add to the expansion variant other than a string, I don't want to assume people won't have some requirement to do so. I think it may be suitable to use the outcome of `onCopy` as the value to put in the expansion preview.
