### ISSUE TITLE
Bug - [Card] - `isSelectable` not working in webkit 122

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#10104]
**Describe the problem**
`Card` component are no longer clickable / selectable in chrome / webkit 122.

**How do you reproduce the problem?**
Use the [Card Single Selectable](https://www.patternfly.org/components/card#single-selectable) example (or any other example with clickable cards) on the patternfly website. With the latest chrome or edge (v 122), the card is no longer selectable. You must use the radio button in the top right corner. 

Visit the same page with Firefox and it works.

**Expected behavior**
Expected card to be selectable.

**Is this issue blocking you?**
Yes.

**What is your environment?**
 - OS: mac intel
 - Browser: Chrome, edge
 - Version: 122

**What is your product and what release date are you targeting?**
RHOAI

**Any other information?**

**Comment by gitdallas** [comment]
styling is also affected, this can be seen in the [HTML examples](https://www.patternfly.org/components/card/html#clickable) as well. Styling is strange (as seen below) and there are no hover or cursor changes.
![image](https://github.com/patternfly/patternfly-react/assets/5322142/8aad66ed-4908-45e9-aa1f-53a87bcf9581)

**Comment by christianvogt** [comment]
The problem occurs with the styling on this label:
<img width="515" alt="image" src="https://github.com/patternfly/patternfly-react/assets/14068621/7c778c90-8136-469d-ad66-e99e5d93125f">

while it has `position: absolute; inset: 0;` it does not occupy the available space of the parent tile anymore which has `position: relative`.

**Comment by gitdallas** [comment]
ah, that makes sense for why the click would also be affected. looks like an issue for core.

**Comment by mattnolting** [comment]
@gitdallas @christianvogt Looks like the issue is that the `background-color` of label and `z-index` are causing the issue. 

<img width="1418" alt="Screenshot 2024-02-26 at 2 37 05 PM" src="https://github.com/patternfly/patternfly-react/assets/5385435/880d593e-fe12-4f0a-b6ac-7ff39ac6beda">

**Comment by christianvogt** [comment]
If a card also contains body content, such as a link, should that link also be clickable even when the card itself is selectable?

**Comment by gitdallas** [comment]
This may require some `stopPropagation` but should be possible. I think there may be some design guidelines against it though

**Comment by christianvogt** [comment]
We can work around this issue by adding the following css. It seems that `inset: 0` is no longer enough to make the label occupy the parent content box.
```
.pf-v5-c-card__selectable-actions .pf-v5-c-radio__label {
  width: 100%;
  height: 100%;
}
```

**Comment by evwilkin** [comment]
Summary of findings & resolution:  https://github.com/orgs/patternfly/discussions/6381
