### ISSUE TITLE
Data list - remove custom styles for width modifiers examples

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#10119]
With penta, the global vars that create these react-tokens that are used for custom styles will be removed, so we'll want to address that before penta is released (or whenever core removes the global vars and the react-tokens break).

The custom styles are used in the [width modifiers example](https://staging-v6.patternfly.org/components/data-list/#width-modifiers), but core has [an equivalent example](https://www.patternfly.org/components/data-list/html#modifiers) without custom styles, so I think we can just remove the custom stuff on the react side.

https://github.com/patternfly/patternfly-react/blob/3a88c11a91941fd01688e978a5c07b947f3a078a/packages/react-core/src/components/DataList/examples/DataList.md?plain=1#L26-L29

https://github.com/patternfly/patternfly-react/blob/3a88c11a91941fd01688e978a5c07b947f3a078a/packages/react-core/src/components/DataList/examples/DataListWidthModifiers.tsx#L23-L26

https://github.com/patternfly/patternfly-react/blob/3a88c11a91941fd01688e978a5c07b947f3a078a/packages/react-core/src/components/DataList/examples/DataListWidthModifiers.tsx#L49-L56

And anywhere `previewPlaceholder` is referenced

**Comment by tlabaj** [comment]
closed by #10117
