### ISSUE TITLE
PF4 component styling does not work with imported base.css in JS

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#1012]
I've noticed that the styling you PF4 components is broken if you include the base.css file in your JS, scss or whatever file that is compiled via webpack. As it is stated in your documentation.
```javascript
import "@patternfly/react-core/dist/styles/base.css";
```

It does work, when you enter the demo, but after **any** code change (component re-render), the styling suddenly disappears.

![screenshot from 2018-12-05 09-28-33](https://user-images.githubusercontent.com/22619452/49500227-73f10100-f870-11e8-8afd-833b6d17b33f.png)

![screenshot from 2018-12-05 09-27-40](https://user-images.githubusercontent.com/22619452/49500233-76535b00-f870-11e8-838d-3853168fcf64.png)

This is reproducible locally in dev environment and also after build in production environment.

You can try it out in the online example here: https://codesandbox.io/s/2vy5yvjk5p

However when you include the same file, into your html template it suddenly starts working. But this is not viable solution since in same cases you need your styles to be compiled via webpack or some other bundler.

**Comment by dgutride** [comment]
@Hyperkid123  - the base needs to always be included before any component is included in the react examples - please re-open if this is still an issue for you
