### ISSUE TITLE
Bug - [V6 Empty state] - We should not export the EmptyStateHeader and EmptyStateIcon

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#10130]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

The componet is building the Header internally with the required `titleText` prop, so we no longer need to export `EmptyStateHeader`.  To add an icon to the header, you would pass the icon prop directly to the  `EmptyState` component.

**Comment by thatblindgeye** [comment]
Closed by #10364
