### ISSUE TITLE
Bug - DatePicker - Datepicker crashes when manually entering an invalid year

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-react#10135]
DatePicker component does not allow manual entry of year:

https://github.com/patternfly/patternfly-react/assets/11218376/9cbbfd9c-16b1-490f-bd70-c38e9c622fe6

**Comment by tlabaj** [comment]
@ibolton336 is this blocking you?

**Comment by ibolton336** [comment]
@tlabaj It is breaking a unit test on QE side. Not a direct blocker.
