### ISSUE TITLE
Bug - Wizard - cannot customize height in modal

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#10144]
The wizard's `height` property appears to be ignored. For example, setting `height=1000` had no effect; although, I could see the property output in the browser console.

![Screenshot 2024-03-08 at 11 42 33 AM](https://github.com/patternfly/patternfly-react/assets/17481322/a9e13119-6505-4e8a-9e72-e9d3d7b0e993)

See https://www.patternfly.org/components/wizard#within-modal

**Comment by mcoker** [comment]
Hey @dlabrecq! Thanks for the issue, that's a bug we need to fix. I created an issue in core for that work (https://github.com/patternfly/patternfly/issues/6457), but I think it will be breaking so I've slated it for work in our upcoming penta release.

For the time being, would you be able to add a custom style for that wizard in a modal? Adding `--pf-v5-c-modal-box--c-wizard--FlexBasis: 1234px;` either as an inline style on `<Wizard>` or in a stylesheet like `.pf-v5-c-wizard.some-custom-class { --pf-v5-c-modal-box--c-wizard--FlexBasis: 1234px; }` would work.

**Comment by tlabaj** [comment]
cosed by #10332
