### ISSUE TITLE
FormGroupLabelHelp: use component="span" and isInline to match core

### ISSUE THREAD

**Issue by adamviktora** [patternfly/patternfly-react#10158]
Followup to this comment:
https://github.com/patternfly/patternfly-react/pull/10016#discussion_r1515136288

Currently the underlying markup does not match core implementation, we use `<button>` so Popover can be opened on pressing **enter** key. We should use `component="span"` and `isInline` props to match, but first we have to figure out why `Popover` is not accessible with _enter_ when using `span`.

**Comment by thatblindgeye** [comment]
Closed by #10248
