### ISSUE TITLE
NavExpandable does not expand or collapse programmatically 

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-react#1016]
If the NavExpandable component prop `isActive` is set to true, it would be great to have an option to expand it automatically. 

Setting the value of `isExpanded` to true or false does not expand or collapse the nav list items. When NavToggle is manually selected, it calls `this.setState({ value: !value });` from within `handleToggle`. This successfully toggles the NavExpandable open and close. We would like to be able to set the value of `isExpanded` programmatically by passing/setting props. Currently, this option isn't available.

![nav bug](https://user-images.githubusercontent.com/15881645/49534491-a52cf980-f88f-11e8-9f60-a4d669cadf5a.gif)

**Comment by ibolton336** [comment]
Hi - The isExpanded prop is designed to set the components initial expanded property. if you want to toggle the value, you can use the exposed on toggle method inside of the nav component. Would this solve your issue?

**Comment by rhamilto** [comment]
@ibolton336, the problem we have in OpenShift console is there is no way to expand sections of the nav when changing routes using links in the content (not the nav).  For example, if I click the name of a deployment, I am routed to the deployment details page and the workloads nav section is set to active, but the workloads nav section is not expanded to show me the type of workload I am viewing.  I have to click workloads to expand it.  Seems far from ideal to only allow expansion onToggle of a nav item.

![zuq7snrd4r](https://user-images.githubusercontent.com/895728/52229583-4847c280-2883-11e9-993b-4d95a99ec5d5.gif)

cc: @janwright73, @spadgett

**Comment by ibolton336** [comment]
@rhamilto - Just reopened. Thanks for the additional detail. Working on a fix now.

**Comment by ibolton336** [comment]
![navexpandfix](https://user-images.githubusercontent.com/11218376/53757357-7243d300-3e89-11e9-8b51-a0f8b2ee8606.gif)
<img width="1041" alt="screen shot 2019-03-04 at 2 23 43 pm" src="https://user-images.githubusercontent.com/11218376/53757360-753ec380-3e89-11e9-889a-d394973a4861.png">
