### ISSUE TITLE
Bug - [MenuItem] - [Documentation is missing]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly-react#10201]
**Describe the problem**

The MenuItem component property documentation is missing, as for Menu and MenuList. 

https://www.patternfly.org/components/menus/menu#menuitem

**Comment by adamviktora** [comment]
Noticing the same for Button props (https://www.patternfly.org/components/button#button)

**Comment by tlabaj** [comment]
This is a duplicate of an issue in Org.  This needs to be fixed in the documentation-framework.  We have prioritizws it for the coming sprint
https://github.com/patternfly/patternfly-org/issues/3894
