### ISSUE TITLE
v6 Button - prevent aria-disabled from being set by isDisabled prop

### ISSUE THREAD

**Issue by adamviktora** [patternfly/patternfly-react#10210]
Followup to: https://github.com/patternfly/patternfly-react/pull/10199#pullrequestreview-1961549740

**Comment by tlabaj** [comment]
We should also clean up `pf-m-disabled` as mentioned here https://github.com/patternfly/patternfly-react/pull/10199#issuecomment-2021696176

**Comment by thatblindgeye** [comment]
Closed by #10255
