### ISSUE TITLE
V6 - audit onBlur/onFocus and other handlers

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#10215]
onBlur and onFocus should be added back to TextArea with the required event parameter.
Other handlers should be checked at this point in case any params need to be required as well.

**Comment by jonkoops** [comment]
> onBlur and onFocus should be added back to TextArea with the required event parameter.

Why should they be added back? These are already provided by [React's types](https://github.com/jonkoops/patternfly-react/blob/8e22d6507d814eeabb443def328b084abfcfd7a3/packages/react-core/src/components/TextArea/TextArea.tsx#L19C39-L19C77) (`HTMLProps<HTMLTextAreaElement>`).
