### ISSUE TITLE
CodeEditor - Constrained editing

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#10233]
**Is this a new component or an extension of an existing one?**
This is a feature request for the existing CodeEditor

**Describe the feature**
We would like to use the CodeEditor with text that can only partially be modified. Something this package already does https://github.com/Pranomvignesh/constrained-editor-plugin 

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by tlabaj** [comment]
Labeled spike to Investigate using the plugin with our code editor.
