### ISSUE TITLE
Clean up demos from latest core alpha bump

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#10238]
- Ensure correct date props are being passed to the Timestamp components (so that the datetime attribute matches the visible text string that is rendered; this may require rendering 2 Timestamps such as the custom menu data select example where a date range is displayed)

- Ensure icons in the Card examples are using the color associated with the status

https://github.com/patternfly/patternfly-react/pull/10230#pullrequestreview-1974471415

**Comment by adamviktora** [comment]
Closing as this is a duplicate of #10239.
