### ISSUE TITLE
Bug - Modal - error on paste with bitwarden enabled

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#10234]
**Describe the problem**
This is a bit of an edge case but when you have a modal with a password input on it on firefox with bitwarden enabled you get an error when you paste a password.

**How do you reproduce the problem?**
1. Open https://codesandbox.io/p/sandbox/dreamy-dream-7983p4 with firefox and the bitwarden plugin installed
1. Paste something into the password field
1. See the error

**Expected behavior**
It should not give an error

The error is in https://github.com/patternfly/patternfly-react/blob/24c732ea445cd4678cc8901aa22b0d2f80d648cb/packages/react-core/src/components/Modal/Modal.tsx#L155
as it tries to call `setAttribute` on the injected bitwarden component that is rendered on the password input.
and firefox is not allowing this giving a: "Permission denied to access property "setAttribute""

**Is this issue blocking you?**
No, you can disable the bitwarden plugin and then it works

**Screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/51133/d6b1e202-2b05-4b47-8393-caac10244a8a)

**What is your environment?**
 - OS: fedora
 - Browser firefox
 - Version 124.0.1

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by marcoleong** [comment]
It only happens with Bitwarden Auto fill enabled. Can turn off under "Settings" > "Auto-fill" > "Show auto-fill menu on form fields" > "Off"
