### ISSUE TITLE
Form Component Audit

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#1026]
- Remove "Various labels and helper text" example. In Core we do not support the badge underneath, and above this are examples that demonstrate helper text.

- Include "disabled" example (https://pf-next.com/components/FormControl/examples/) as we dont currently have that in React

- For the invalid form I don't seem to be able to type in the input? Is this intended? It would be great to make it work so that as I type it shows an invalid message as soon as I type in an invalid character.

**Comment by tlabaj** [comment]
closed by PR #1185

**Comment by tlabaj** [comment]
closed by #1185
