### ISSUE TITLE
Demo - Table - Update managed column modal demos 

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#10288]
**Describe the problem**
The Managed column demos are currently using the secondary button styling for the Cancel button. There was a decision to use the plain text button for the Cancel action. If more actions are required in the modal the secondary button is available.

**React demos** 
<img width="783" alt="Screenshot 2024-04-18 at 12 05 53 PM" src="https://github.com/patternfly/patternfly-react/assets/28658548/c7eed5b2-4dfb-45ac-a5e4-11da8610124f">

**Core demo**
<img width="732" alt="Screenshot 2024-04-18 at 12 22 51 PM" src="https://github.com/patternfly/patternfly-react/assets/28658548/e7318a34-0a3f-4ab9-8c98-df646c020ea0">

**Comment by tlabaj** [comment]
We should do this in v5 as well.
