### ISSUE TITLE
Drag and drop cursor inconsistencies

### ISSUE THREAD

**Issue by Venefilyn** [patternfly/patternfly-react#10290]
**Please describe the issue**
Looking at the drag and drop I see several different cursors I don't associate with a drag and drop

**Are there visuals for this issue? Please provide screenshots**
Include screenshots or links to Marvel or other mockups.

When hovering over the grab button there's a click rather than grab
![image](https://github.com/patternfly/patternfly-react/assets/6598829/9afc5c06-694c-4817-853c-8f7597dadc93)

Picking up looks correct here 
![image](https://github.com/patternfly/patternfly-react/assets/6598829/db28a4c3-71be-40f8-9048-a55d852db2cf)

But not when you select something else
![image](https://github.com/patternfly/patternfly-react/assets/6598829/2e7cb6e2-7005-4e73-a04b-44cccfc55af2)

Same if you select outside the text
![image](https://github.com/patternfly/patternfly-react/assets/6598829/60be04b1-7703-471b-b87e-dd22091b9a59)

When releasing the drag and drop here, it changes to grab hand which is correct, but given the other cursors being incorrect it doesn't fit
![image](https://github.com/patternfly/patternfly-react/assets/6598829/065ff80c-7316-4a18-8f43-179372de4865)

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**
https://staging-v6.patternfly.org/components/drag-and-drop

**Any other information?**

**Comment by tlabaj** [comment]
We will remove the basic example without the drag button since that is not recommended. We will update the componet so the drag button variant is the default (prevent no drag button variant)
WE will need 2 PRs.  one for v5 one for v6.
