### ISSUE TITLE
BulletChart tooltip generates "unable to find node" error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1030]
I'm attempting to use the bullet chart in the Koku UI. When hovering over the bullet chart, I encounter this error instead of seeing a tooltip. 

`Error: Unable to find node on an unmounted component`

![screen shot 2018-12-08 at 8 25 39 am](https://user-images.githubusercontent.com/17481322/49693132-97e66800-fb38-11e8-822f-13b506da0715.png)

It was suggested this may be related to a recent change regarding imports?

Note: I'm using patternfly-react v2.25.4, react-bootstrap v0.32.1, & react-dom v16.4.1.

My Test Example:
```
const values = [{
  title: 'Core-Hours',
  value: 35
}, {
  title: 'Requests',
  value: 55
}];
return (
  <BulletChart values={values}/>
  ...
```

**Comment by jeff-phillips-18** [comment]
Now that I see the error message better, this is not an import issue. Sorry for that false info.

**Comment by dlabrecq** [comment]
Seems to be a mismatch between react-dom and react-bootstrap. 

I updated react-dom to 16.6.3 and react-bootstrap to 0.32.4. I thought it was react-dom, but it wouldn't work without also updating react-bootstrap.
