### ISSUE TITLE
Charts - Skeleton

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#10310]
The UX design team wants to show a skeleton in place of an empty state (e.g., when there is no data to graph). A "graph empty state gives more context on what the user can expect" Vs showing a generic empty state.

**Notes**
- This is not animated like the existing PatternFly skeletons, just filling label backgrounds grey. 
- Charts shall not provide fake data. Developers can provide their own data to represent their graph if desired.

**Design issue**
https://github.com/patternfly/patternfly-design/issues/1278

**Mocks**
https://www.figma.com/proto/N7hImgEN8rnyKmkz34wcuP/PF---Skeleton-charts?page-id=0%3A1&type=design&node-id=2-1397&viewport=328%2C398%2C0.07&t=iYlJZWG8k9Di231C-1&scaling=scale-down

**Comment by tlabaj** [comment]
closed by #10311
