### ISSUE TITLE
Bug - Table - compound expansion table row missing styles

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#10321]
**Describe the problem**
The react component for the compound expansion table is missing the gray border that displays below the expanded row.

**How do you reproduce the problem?**
Compare the [react example](https://www.patternfly.org/components/table#compound-expandable) against the [html example](https://www.patternfly.org/components/table/html#compound-expansion-example).

The react example is missing a gray bottom-border on the expanded row, as shown in this example:
![image](https://github.com/patternfly/patternfly-react/assets/21063328/a5cd641e-0bcf-4af4-b144-920f73e965f1)

**Expected behavior**
A gray bottom-border should display for the expanded row, as shown in this example:
![image](https://github.com/patternfly/patternfly-react/assets/21063328/aaf5392d-af34-4543-bbd6-e6eeff4d4b5e)

**Is this issue blocking you?**
This is a cosmetic issue, so it's not blocking functionality. 

**Screenshots**
See examples above.

**What is your product and what release date are you targeting?**
This is related to an upcoming release for RHOAI.

**Any other information?**

**Comment by mcoker** [comment]
Looks like the parent row (`tr.pf-[v]-c-table__tr`) with the compound expandable buttons is missing the class `.pf-[v]-c-table__control-row`
