### ISSUE TITLE
Bug - Select - The first time you click on a filter input field, it does not have focus

### ISSUE THREAD

**Issue by AlexandrUSA** [patternfly/patternfly-react#10333]
**Describe the problem**
The first time you click on a filter input field of the Select component with typeahead functionality, it does not have focus. Only after second click we get a focus and we can insert some text into it. This issue is reproducible in official documentation as well: https://www.patternfly.org/components/menus/select/#typeahead

**How do you reproduce the problem?**

1. Add Select component on your page with typeahead functionality
2. Click on it and try to insert some text in filter

**Expected behavior**
Focus is set on the input field and we can enter values there for filtering

**Actual behavior**
The input field does not have focus and we cannot enter filtering values there. Only after second click we get a focus and can insert some text for filtering

**Screenshots**
First click on the filter field (no focus on the input field):
![image](https://github.com/patternfly/patternfly-react/assets/32391610/6228f245-cc0e-48d7-91dc-ac48725cb2db)
Second click (filter gets focus but options are not visible):
![image](https://github.com/patternfly/patternfly-react/assets/32391610/e1d3ce1c-d71d-487f-9be5-331a8ab66a24)

**What is your environment?**
 - OS: iOS, Windows 10, 11
 - Browser: chrome, safari
 - Version: any version

**Comment by adamviktora** [comment]
This behavior was fixed in one of the latest PRs: https://github.com/patternfly/patternfly-react/pull/10207/files by adding the `shouldFocusFirstItemOnOpen` prop and setting it to false in all typeahead select examples.

I believe it was just not released yet (or at least not in the 5.3.0 release which is on the website)

**Comment by tlabaj** [comment]
closed by #10207

**Comment by steverhoades** [comment]
Is there a plan to include this in a release soon?

**Comment by tlabaj** [comment]
We are in the last sprint of development for our Q2 release.  This fix will
be included.

**Comment by rbertucat** [comment]
@tlabaj is that fix in 5.3.4? (https://www.npmjs.com/package/@patternfly/react-core/v/5.3.4) Or is it going to be in 5.4.0? Thanks!
