### ISSUE TITLE
Aligning items in PF Toolbar does not seem to work

### ISSUE THREAD

**Issue by fhlavac** [patternfly/patternfly-react#10343]
**Please describe the issue**
When trying to align the pagination ToolbarItem  in a Toolbar using `align={{ default: 'alignRight' }}`,  it keeps aligned left. I switched to use of `variant="pagination"` which solves the issue for my use case. Just opening the issue because the align prop seems to be still present in the docs and does not seem to work properly.

**Are there visuals for this issue? Please provide screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/50696716/2caffc6e-87fb-4e05-b2a8-53a4b501ac96)

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**
https://github.com/patternfly/react-data-view/pull/5/files#diff-e9838074b64c3100dd94f35063772cdb7d5b026fa3835aa334be458a3ea406d7

**Comment by nicolethoen** [comment]
closed by #10366
