### ISSUE TITLE
Extra space after the Toolbar component

### ISSUE THREAD

**Issue by fhlavac** [patternfly/patternfly-react#10342]
Currently, there is an extra space displayed under the Toolbar component.
The div with `pf-v6-c-toolbar__content pf-m-hidden` should probably not be visible (it is not in PF5, but it is in PF6) - screenshot attached.

**Are there visuals for this issue? Please provide screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/50696716/d3bc1acb-accd-4db1-a8ea-796b84f89386)

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**
https://github.com/patternfly/react-data-view/pull/5/files#diff-e9838074b64c3100dd94f35063772cdb7d5b026fa3835aa334be458a3ea406d7

**Comment by mcoker** [comment]
Looks like this should be resolved with a style update. Opened an issue in the core repo (https://github.com/patternfly/patternfly/issues/6627) and we can use this issue to verify it's working on the react side

**Comment by mcoker** [comment]
This should be fixed in https://github.com/patternfly/patternfly/releases/tag/prerelease-v6.0.0-alpha.137
