### ISSUE TITLE
Change Text component name to Content to better align with core

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-react#10395]
**Describe the enhancement or change**
Currently the component which is named Text in React uses `content` as its class name in core, which can cause confusion.

Additionally in #10390 we will be moving the component in a direction where Text as a component name isn't ideal.

For those reasons I believe we should change the name to Content. If this work is picked up a codemod issue should be made to address this change automatically for consumers.

**Comment by tlabaj** [comment]
closed by #10643
