### ISSUE TITLE
Text - support for hr element

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#10390]
Core supports `<hr>` in the content/text component, it would be super duper to have support for it in the react text/textcontent component. Here is a use case in the docs framework package https://github.com/patternfly/patternfly-org/pull/4011#discussion_r1605141970

https://github.com/patternfly/patternfly/blob/ce84441970fd1a48ad391659a4452bff0ae47139/src/patternfly/components/Content/content.scss#L300-L307

cc @wise-king-sullyman

**Comment by tlabaj** [comment]
closed by #10611
