### ISSUE TITLE
Bug - charts - victory version bump causing build errors in OCP

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#10403]
As soon as we bumped the version of victory in the current PF prerelease, OCP started getting the following errors in multiple places

I’m seeing the following error from a number of files/locations:

```
ERROR in ./node_modules/victory-cursor-container/es/victory-cursor-container.js 9:23
Module parse failed: Unexpected token (9:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // @ts-expect-error "TS2545: A mixin class must have a constructor with a single rest parameter of type 'any[]'."
|   return class VictoryCursorContainer extends Base {
>     static displayName = "VictoryCursorContainer";
|     static defaultProps = {
|       ...VictoryContainer.defaultProps,
 @ ./node_modules/victory-cursor-container/es/index.js 2:0-43 2:0-43
 @ ./node_modules/@patternfly/react-charts/dist/esm/components/ChartCursorContainer/ChartCursorContainer.js
 @ ./node_modules/@patternfly/react-charts/dist/esm/components/index.js
 @ ./node_modules/@patternfly/react-charts/dist/esm/index.js
 @ ./public/components/graphs/index.tsx
 @ ./public/components/graphs/helpers.ts
 @ ./public/actions/dashboards.ts
 @ ./public/reducers/dashboards.ts
 @ ./public/redux.ts
 @ ./public/components/app.jsx
 @ multi ./public/components/app.jsx monaco-editor-core/esm/vs/editor/editor.worker.js
```

**Comment by thatblindgeye** [comment]
Findings from various updates locally:

- Updating all applicable PatternFly versions to prerelease numbers **except for Charts** (remaining at version 7.2.2) results in several TypeScript warnings, as well as a few errors being thrown as a result of `./node_modules/@dagrejs`, but no errors from Victory.
- Updating all PatternFly versions to prerelease numbers **including Charts** (using 7.4.0-prerelease.12) results in several TypeScript warnings, as well as several errors being thrown from the Victory package(s).
- Updating all PatternFly versions to prerelease numbers (same as the second bullet item) and updating the `resolutions` array in package json to include Victory deps results in the same output as the first bullet point (several TS warnings + only a few warnings from dagrejs)
- Updating all PatternFly versions to prerelease numbers (same as the second bullet item) and updating the TypeScript dep version to version `^5.4.5` similar to what PF is using results in an error being thrown from the Console code itself (`Union type SupportedExtension has no members` from `type-resolver.ts` file), no other errors are able to arise
