### ISSUE TITLE
Badge - add disabled variation

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#10417]
Follow up to a [core PR](https://github.com/patternfly/patternfly/pull/6616) that
* Adds `.pf-m-disabled` as a variation of `<Badge>`
* Removes disabled styling for badges when used in `<Button>`, so we'll want to make sure our buttons w/ count are using the disabled badge variation https://github.com/patternfly/patternfly-react/blob/6101cfe558acec0474dd1c0649e44c38bf01383f/packages/react-core/src/components/Button/Button.tsx#L209-L213

**Comment by evwilkin** [comment]
Closed by #10445
