### ISSUE TITLE
Bug - Toolbar - typo in rowGap prop in v6

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#10441]
**Describe the problem**
https://github.com/patternfly/patternfly-react/pull/10418#issuecomment-2127969730

**How do you reproduce the problem?**
Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.

**Expected behavior**
A clear and concise description of the expected behavior.

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by tlabaj** [comment]
closed by #10439
