### ISSUE TITLE
React-icons - update README reference of v5 to v6

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#10480]
Small thing I noticed in the README, the reference to `.pf-v5-svg` should update to `.pf-v6-svg` https://github.com/patternfly/patternfly-react/blob/2b5a598e9b49f052d36b675a0929d5f679af6cca/packages/react-icons/README.md?plain=1#L17

**Comment by evwilkin** [comment]
Closed by https://github.com/patternfly/patternfly-react/pull/10575
