### ISSUE TITLE
Review Components for consistent handling of required aria-labels

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1048]
Verify that all components treat required aria labels the same.  Some components generate an error on the JS side but have the prop optional on the TS side.  If we use isRequired on the JS side the prop should also be required in the TS file.

**Comment by rebeccaalpert** [comment]
There are a ton of components that throw an error if there's no aria-label and some other condition applies:

```
if (!props.id && !props['aria-label']) {
    return new Error('TextArea requires either an id or aria-label to be specified');
}
```

Is it okay to leave those optional in the TS files?

**Comment by tlabaj** [comment]
@rebeccaalpert , yes . I would leave both props as optional in this case.
@dlabaj an you weigh in on this please.

**Comment by jschuler** [comment]
Can we implement something similar to what is shown in the examples here?
https://stackoverflow.com/questions/40510611/typescript-interface-require-one-of-two-properties-to-exist
```
type RequireAtLeastOne<T, Keys extends keyof T = keyof T> =
    Pick<T, Exclude<keyof T, Keys>>
    & {
        [K in Keys]-?: Required<Pick<T, K>>
    }[Keys]

interface MenuItem {
  title: string;
  component?: any;
  click?: any;
  icon: string;
}

type ClickOrComponent = RequireAtLeastOne<MenuItem, 'click' | 'component'>
```
