### ISSUE TITLE
Bug - Pagination - page select toggle wraps

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#10506]
Discovered a couple issues with the latest PatternFly milestone packages in Cost Management.

1. When including an aria label for pagination, an "items" label is output by default. 
2. The page select toggle is wrapping to the next line.

I noticed that the toggle button uses `display=block`, while the [pagination example](https://www.patternfly.org/components/pagination#bottom) on patternfly.org uses `display=inline-flex`.

![Screenshot 2024-06-03 at 11 13 14 AM](https://github.com/patternfly/patternfly-react/assets/17481322/94761d41-109a-4b4b-bd4d-9a8beefaff08)

**Wrapped pagination controls**

![Screenshot 2024-06-03 at 10 31 46 AM](https://github.com/patternfly/patternfly-react/assets/17481322/6aa2872f-ee09-44a8-925b-55ce28f23d5d)

**Example**
```
<Pagination
      itemCount={333}
      widgetId="bottom-example"
      perPage={perPage}
      page={page}
      variant={PaginationVariant.bottom}
      onSetPage={onSetPage}
      onPerPageSelect={onPerPageSelect}
      titles={
          {
            paginationAriaLabel: 'test' <<<
          }
        }
    />
```

**Comment by tlabaj** [comment]
Hello Dan.  I was unable to reproduce either issue.  The wrapping issue was resolve in core PR https://github.com/patternfly/patternfly/pull/6586

When I add the aria label as you demonstrate above, it gets applied correctly.

**Comment by dlabrecq** [comment]
Regarding the aria-label, we're expecting to see "1-31 of 31", but "1-31 of 31 items" is output whenever `paginationAriaLabel` is in use.

Note that we do not add the "items" label ourselves. The only workaround is to provide an empty string to as shown below.

titles={
  {
    items="" <<<
    paginationAriaLabel: 'test'
  }
}

**Comment by tlabaj** [comment]
@dlabrecq Thanks for the info.  I will take another look.
