### ISSUE TITLE
PF4: react-styles - create requirements for distributing embedded CSS and evaluate emotion

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#1057]
Need to ensure emotion is working the way we think it is and we have a full grasp of overall goals with regard to distributing pf4 css embedded in components.

**Comment by janwright73** [comment]
Related questions from the Kiali team, newly leveraging PF4 React.

In the storybook example PF team use:
import accessibleStyles from '@patternfly/patternfly-next/utilities/Accessibility/accessibility.css';
e.g. 'http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout'

Patternfly-next it’s not installed with patternfly-core, after install it we can’t use use this file,
Are this css classes recommended by UX team ?

UXD Team discussion:

- Consumers should not be required to install @patternfly/patternfly-next
- Anything they need should be available or included in the react-core package (and maybe react-tokens?)
- Patternfly-base - how would consumers include that?
- How should we recommend they deliver bundled CSS - would an extract plugin be an option if they don't want css embedded
- Embedded CSS is probably a non-starter for some teams - so coming up with an extraction mechanism and example is going to be critical.  We also need real clarity on whether or not ever importing css as we did in that page demo is allowed for our team.
- react-core dist/styles/base.css is the PF base stylesheet they can import
so we do it already for the base styles
e.g. `import '@patternfly/react-core/dist/styles/base.css'`
maybe we can add some utility classes here as well if this is the approach we’re going with

**Comment by dgutride** [comment]
Removed emotion style injection as part of 3.x react-core release.  Users can now use standard css loader libraries for patternfly.
