### ISSUE TITLE
Inverse PF Logo showing on multiple react demo examples

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-react#10576]
There are multiple full page demos where the PF logo is showing in inverse on light theme 

so far we've seen this on
- banner react demos
- wizard demos
- jumplinks demos
- data list demos
- nav demos

**Comment by tlabaj** [comment]
Let's make sure all demos have the correct logo.

**Comment by rebeccaalpert** [comment]
This should be all set on https://staging-v6.patternfly.org now!
