### ISSUE TITLE
Move lerna root packages into sibling folders instead of roots to prevent releasing

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#1058]
We show extra lerna root releases each time a child package is updated.  These should be moved into sibling packages (named something like patternfly3-lerna-root to prevent releasing).

**Comment by priley86** [comment]
I think we may be able to resolve this by referencing `patternfly3-lerna-root` and `patternfly4-lerna-root` as "file" references. Will try this out in my sandbox sometime soonish...

https://github.com/lerna/lerna/issues/1725

**Comment by redallen** [comment]
Fixed in #1348
