### ISSUE TITLE
Upgrade and align `@dnd-kit/` dependencies 

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#10600]
The the `@dnd-kit/` dependencies should be upgraded to the latest version and any breaking changes should be handled. The `@dnd-kit/utilities` dependency is missing and should be added to `@patternfly/react-drag-drop`, the unused `@dnd-kit/modifiers` should be removed.

A previous attempt at this was done, but some issues were found (https://github.com/patternfly/patternfly-react/pull/10590#pullrequestreview-2110352246) that require a deeper look.

**Comment by jonkoops** [comment]
This is still relevant

**Comment by tlabaj** [comment]
closed by #11129
