### ISSUE TITLE
BulletChart: Each child should have a unique "key" prop

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1060]
I'm seeing warnings about children with the same key props. 

`Warning: Each child in an array or iterator should have a unique "key" prop`

The error appears to be related to ranges. That is, if I omit the ranges, I no longer see the error.

![screen shot 2018-12-14 at 4 26 27 pm](https://user-images.githubusercontent.com/17481322/50028771-bfb55000-ffbe-11e8-8a9a-9065f079bf04.png)

**Comment by jeff-phillips-18** [comment]
@dlabrecq Can you post your usage of the Bullet Chart?

**Comment by jeff-phillips-18** [comment]
Ah, if less than 2 ranges are present this problem occurs. Will fix.

**Comment by dlabrecq** [comment]
Right. I only have one range defined
