### ISSUE TITLE
Bug - DragDropSort - drag overlay styles are missing

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#10612]
The drag overlay (copy of the element that is attached to cursor position) is no longer finding the PF component styles. All variables are "undefined" when inspecting the element.

This is unrelated to the dnd-kit update https://github.com/patternfly/patternfly-react/pull/10590#pullrequestreview-2110352246 as it's happening locally after rebasing from main.

**Comment by tlabaj** [comment]
closed by #10614
