### ISSUE TITLE
Bug - [MenuToggle ] -Flashes the screen when used in the <MastHead>

### ISSUE THREAD

**Issue by ChrisLee5000** [patternfly/patternfly-react#10648]
**Describe the problem**
When clicking the right half of a <MenuToggle> dropdown, the screen flashes and jiggles a bit.

**How do you reproduce the problem?**
This is visible on the PatternFly website as well as our project that has a MenuToggle in the same location in the MastHead.
On Patternfly.org, click "Release 5.3.0" to trigger the bug. It happens about 50-70% of the time when clicking it, usually on the right half of the control.

**Expected behavior**
No flashing or jiggling occurs. 

**Is this issue blocking you?**
Yes

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 126.0.6478.57

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by tlabaj** [comment]
Can you please supply a video of the issue.  We are unable to reproduce this.
