### ISSUE TITLE
menu toggle: Split button checkbox has no padding

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#10641]
In this [example](https://staging-v6.patternfly.org/components/menus/menu-toggle/#split-button-toggle-with-checkbox-and-toggle-button-text) on the React tab of staging there is an inline style that uses a broken spacer variable. 

Short-term we could just update from `padding-left:var(--pf-v5-global--spacer--sm)` to `padding-inline-start: var(--pf-t--global--spacer--gap--action-to-action--plain)`

Long-term this doesn't exist on the Core examples. This should be updated so we don't need custom inline styling

<img width="824" alt="Screenshot 2024-06-23 at 8 53 43 PM" src="https://github.com/patternfly/patternfly-react/assets/28658548/90c8d6fd-5280-45e4-a33a-d040ccbdc684">

**Comment by kmcfaul** [comment]
Closed by https://github.com/patternfly/patternfly/pull/6886
