### ISSUE TITLE
Bug - Wizard - users must to revisit steps in order

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#10640]
Trying to update Cost Management to use the PF v5 wizard, but having trouble forcing users to revisit all steps. In our scenario, users can revisit a previous step, but they cannot skip the following (next) step. 

Properties may be reset, based on choices from a previous step, so steps are expected to be visited in order. The new `isVisitRequired` prop lets users jump to any step, but it also allows steps to be visited out of order.

For v4, we used the step's `isDisabled` prop to achieve the desired behavior below. For example, while the step is greater than the current step index, it remains disabled. After clicking the next button, we were able to update the `isDisabled` prop based on the new step.

The v5 wizard jumps immediately to the next step, after clicking the next button. We're not able to update the `isDisabled` prop, unlike with the v4 wizard.

**Desired behavior**
![chrome-capture-2024-5-21](https://github.com/patternfly/patternfly-react/assets/17481322/02b6f425-e052-4760-8dd4-e776634fbd27)

**Sandbox**
https://codesandbox.io/p/sandbox/wizard-5zt7tj

**Comment by tlabaj** [comment]
Is this blocking you?

**Comment by dlabrecq** [comment]
It's not blocking, but not expected behavior.
