### ISSUE TITLE
Bug - [Select] - Select matches non-ascii characters exactly

### ISSUE THREAD

**Issue by PanSpagetka** [patternfly/patternfly-react#10688]
**Describe the problem**

Search in  `Select` components matches non-ascii characters exactly.  E.g. when you type `i` in codesandbox example you get two results `Knedlik` and `Florida`.  You don't get `Knedlík` and `Rohlík`.  To find those options you need to type `í`.

**How do you reproduce the problem?**
A [codesandbox](https://codesandbox.io/s/proud-sun-ns747q ) 

**Expected behavior**
 We should find a way how to match non-ascii to ascii, for example á -> a, š -> s, í -> i, é -> e, etc.
Typing `i` should filter `Knedlik`, `Florida`, `Knedlík` and  `Rohlík`. 
Typing `í` should filter `Knedlík` and  `Rohlík`. 

**Is this issue blocking you?**
No.

**What is your environment?**
 Not browser or OS specific. Tested on multiple browsers and Fedora versions.

**What is your product and what release date are you targeting?**
web-rca.devshift.net No specific release date.

**Any other information?**
Some people have characters with diacritics in their name. Many are using ASCII version when typing their name, but not all. It might be hard to find people with diacritics in selects with long list of names. Especially if they don't use diacritics everywhere, so you might even not know that their names actually contains non-ASCII characters.

**Comment by tlabaj** [comment]
Hi.  The filtering logic is consumer provided. It is not internal to the component.  Typically our demo code does not cover every use case. We usually demo basic use cases.

**Comment by PanSpagetka** [comment]
Thanks, you are correct, I didn't realize that. Sorry.
