### ISSUE TITLE
Component - Data Table

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#107]
Provide implementation for the Data Table as documented here:
http://www.patternfly.org/pattern-library/content-views/table-view/#/design

The following features of data table were captured in #143 for the `Table` component:
   * ~~Customizable table header (and PF styles applied to the table header)~~
   * ~~Customizable table cells (and PF styles applied to table cells)~~
   * ~~Customizable table footer (and PF styles applied to pagination *after* pagination is done)~~
   * ~~Column visibility (ability to hide columns)~~ (this is done by simply [setting `visible` attribute](https://reactabular.js.org/#/features/toggling-column-visibility) on the column)
   * ~~Row selection and hover for rows~~
   * ~~Inline actions (actions column w/ kebab)~~
   * ~~Sortable columns (and callbacks for sorting)~~
   * ~~Server Side and Client Side Paging~~

Additional features will include:
   * Simplified consumption via `controlled` HOC and `DataTable` component
   * Export to CSV
   * Empty State and filter/toolbar integration (also demonstrating column visibility)
   * Story examples demonstrating these features in a mock application scenario
   * column reordering

Link to JIRA story:
https://patternfly.atlassian.net/browse/OSUX-332
https://patternfly.atlassian.net/browse/OSUX-333 (Export to CSV)

**Comment by priley86** [comment]
cc: @jeff-phillips-18 @ohadlevy 

have we explored the following React data table? or settled on another?
https://allenfang.github.io/react-bootstrap-table/

It seems quite flexible as well (with the ability to customize header/footer):
http://allenfang.github.io/react-bootstrap-table/custom.html#pagination

Initially I believe we also looked at React-Table, but not sure where things have landed.
https://github.com/react-tools/react-table

**Comment by dabeng** [comment]
I think solution4 is to encapsulate jquery DataTables as a reactjs component. In this way, we can make maximum use of the whole APIs of DataTables at little cost.
By the way, we should't focus merely on features design doc described. We know that end users always have all kinds of strange demands for DataTables.

**Comment by ohadlevy** [comment]
@amirfefer started to evaluate react-bootstrap-table current wip in https://github.com/theforeman/foreman/pull/5024

**Comment by priley86** [comment]
@ohadlevy 👍  - will start there and follow this PR as it goes...

**Comment by priley86** [comment]
moving this to backlog - additional features can be added in future pr's.

**Comment by jeff-phillips-18** [comment]
@priley86 Would it make more sense to close this issue and open another to add the additional features? Seeing this in the backlog makes me believe there is no Data Table support.

**Comment by priley86** [comment]
@jeff-phillips-18 sure - closing this issue and opened an additional issue in #204 to capture additional data table work.
