### ISSUE TITLE
Bug - [Select] - for mutliple typeahead, need to click in the input area twice in order to type

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#10702]
**Describe the problem**
When I first click into the input field, my focus is lost and I need to click again before I can type. On the doc page it retains focus from the first click (even after the menu is shown), but in the application and in the code sandbox for the page it does not.

Also, when I tab the toggle button for the drop down gets focus. I'm not sure that it should and the doc page it doesn't but it does for the code sandbox.

It would also be very helpful if all the code in the example were part of the component rather than requiring all applications to copy the example source code. It is quite a lot and needs to be done for every use of the component.

**How do you reproduce the problem?**
Run the code sandbox from the [docs page](https://www.patternfly.org/components/menus/select/) 

**Expected behavior**
I can click on the text input and begin typing

**Is this issue blocking you?**
No. I can add a timeout to give focus to the input ref but that is hacky.

**What is your product and what release date are you targeting?**
RHOAI 2.13

**Comment by tlabaj** [comment]
please verify that this is still an issue.  We are unable to reproduce.

**Comment by jeff-phillips-18** [comment]
Go to https://www.patternfly.org/components/menus/select#typeahead
Open in `codesandbox`
Click in the typeahead
Notice that you cannot type what you are searching for until you click again (which also closes the menu)

**Comment by kmcfaul** [comment]
It looks like codesandbox is running one version behind the latest PF release (it is on `5.3.3` when you pull it up and `5.3.4` does not have this issue).

**Comment by jeff-phillips-18** [comment]
The docs still show running `5.3.3` for me.
