### ISSUE TITLE
Remove third-party configurations for `eslint-plugin-patternfly-react`

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#10740]
The `eslint-plugin-patternfly-react` package contains linting presets for [various ESLint plugins](https://github.com/patternfly/patternfly-react/blob/1f81cd766361955fc6776b8e67c5fe60ecc8a372/packages/eslint-plugin-patternfly-react/package.json#L25-L38), these are all listed as explicit dependencies. This is an issue, as anyone who installs the ESLint plugin will now also get all these other ESLint plugins installed that they likely do not need, and if they do are quite possibly a version that conflicts.

Instead of having a preset for all these third-party plugins the ESLint plugin should be stripped so that it only contains it's own rules and presets, and remove the dependency on any third-party ESLint plugin. This will reduce complexity and maintenance burden, and pull it more in-line with how users expect ESLint plugins to work.

**Comment by tlabaj** [comment]
Closed by #10752
