### ISSUE TITLE
PF4: Failed to compile with no export member 'xxx' message starting patternfly-react 1.39.1

### ISSUE THREAD

**Issue by tadayosi** [patternfly/patternfly-react#1077]
Starting from patternfly-react 1.39.1, this simple `App.tsx` (below) fails to compile with browser saying:

<img width="1303" alt="screen shot 2018-12-18 at 16 49 55" src="https://user-images.githubusercontent.com/156692/50139413-023f9b00-02e5-11e9-8670-fdd541809a40.png">

```
import { Button, Page, PageSection } from '@patternfly/react-core';
import * as React from 'react';

class App extends React.Component {
  public render() {
    return (
      <React.Fragment>
        <Page>
          <PageSection>
            <Button variant="primary">Hello</Button>
          </PageSection>
        </Page>
      </React.Fragment>
    );
  }
}

export default App;
```

It works just ok until patternfly-react 1.39.0.

**Comment by dlabaj** [comment]
Fixed by https://github.com/patternfly/patternfly-react/pull/1093
