### ISSUE TITLE
Bug - Table - Page/table gets auto scrolled while clicking on some row actions

### ISSUE THREAD

**Issue by burhanQuartic** [patternfly/patternfly-react#10790]
**Describe the problem**
This is an issue with 
- Patternfly 5  

when the user clicks on the some row actions, the page/table gets scrolled automatically

**How do you reproduce the problem?**
This issue can be reproduced on the patternfly table demo component as well. https://www.patternfly.org/components/table/#modifiers-with-table-text

**Expected behavior**
The page/table should not get randomly scrolled on clicking the row action.

**What is your environment?**
 - OS: Ubuntu 20.04.6 LTS
 - Browser chrome
 - Version 125.0.6422.60

**What is your product and what release date are you targeting?**
August 2024

**Comment by thatblindgeye** [comment]
@burhanQuartic I moved this over to our React repo. Updating where the action menu gets appended may help resolve this by passing something along the lines of `popperProps={{appendTo: () => document.body}}` (it'd be worth trying to append to an element closer to the trigger than the document body is possible).

Depending on the implementation, if you're using our Dropdown or Select components you could pass that to the outermost element, `<Dropdown>` or `<Select>`. or you can pass that to the table's `<ActionsColumn>`

**Comment by burhanQuartic** [comment]
@thatblindgeye I tried appending it to an element closer to the trigger but that also didn't worked.

**Comment by thatblindgeye** [comment]
@burhanQuartic we merged a PR that should be included in our next version 5 release that should help alleviate the issue. An alternative workaround for now would be to update the appendTo to the document body (rather than as close to the trigger as possible).

**Comment by burhanQuartic** [comment]
@thatblindgeye we have updated the patternfly version to the latest, but still the issue is there.

**Comment by thatblindgeye** [comment]
@burhanQuartic can you confirm the version number of `@patternfly/react-core` that you tested?

**Comment by burhanQuartic** [comment]
@thatblindgeye we tested on @patternfly/react-core version 5.4.0

**Comment by thatblindgeye** [comment]
Gotcha, was just wondering because we merged a PR that might actually help resolve this issue ([tweaking the timeout of our auto-focus logic](https://github.com/patternfly/patternfly-react/pull/11018)), and that is part of version 5.4.1
