### ISSUE TITLE
Remove console styles from PatternFly

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#10791]
Currently console styles in react styles only apply to PatternFly React Console extensions.  These should be removed once the styles have been migrated to [React Console (Issue # 36)](https://github.com/patternfly/react-console/issues/36).

**Comment by dlabaj** [comment]
@tlabaj Build is failing because we need an org update to remove the styles being pulled in from react-console.  Once the react-console PR goes in we need to update org with the new v6 react-console release.  This build should then pass once those 2 updates are in.

**Comment by tlabaj** [comment]
closed by #10780
