### ISSUE TITLE
Bug - [Label Group] - [Show more button submits forms]

### ISSUE THREAD

**Issue by AlexSCorey** [patternfly/patternfly-react#10800]
**Describe the problem**
When using the label group component with labels on a form the form submits when I click on the Show More, the form get submitted.

**Expected behavior**
The Show More button should only expand to show the rest of the labels.  It should not submit the form.

**Is this issue blocking you?**
No- I switched to using Chip Group and the problem is resolved.
![labels](https://github.com/user-attachments/assets/64fca56f-cfef-4635-a0d6-6cea8022e984)

**Comment by himdel** [comment]
More info - the issue boils down to `<form><button></button></form>` - that button submits the form, while `<form><button type="button"></button></form>` doesn't.

`LabelGroup` is rendering a `<Label isOverflowLabel />`, which renders a `<button>`, but not `<button type=button>`, breaking forms.
