### ISSUE TITLE
PF4 AboutModal: make trademark, logoImageSrc, and logoImageAlt to become optional props.

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1080]
This issues is to address changes in react  as a result of core issue[ #1100](https://github.com/patternfly/patternfly-next/issues/1110).

The following changes should be implemented

1. trademark, logoImageSrc, and logoImageAlt props should be optional
2. productName should allow for JSX and not require a string. (**This will be covered in another issue after more investigation**)

**Comment by dtaylor113** [comment]
https://github.com/patternfly/patternfly-next/issues/1131

**Comment by tlabaj** [comment]
closed by #1082

**Comment by tlabaj** [comment]
Closed by #1082
