### ISSUE TITLE
Bug - Select - keyboard navigation for selecting checkbox options is not working

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly-react#10813]
The PF doc example using the Select component with checkbox select options does not "select" the item when pressing the "enter" key. 
[SelectOption](https://www.patternfly.org/components/menus/select#checkbox-select)

https://codesandbox.io/s/qdnv7w

**Comment by tlabaj** [comment]
This is the intended interaction with the new select components.  Space is what triggers selection and this matches native checkbox element inputs.
