### ISSUE TITLE
Bug - DualListSelector next - isTree variant moves all items even with applied filter

### ISSUE THREAD

**Issue by adamviktora** [patternfly/patternfly-react#10862]
**Describe the problem**
DualListSelector next (new version in V6) - when `isTree` prop is true and we apply a search filter to only show few items, then click the "add all" button, it moves all items, including those which are not shown because of the filter.
This is an issue only with the `isTree` variant.

**How do you reproduce the problem?**
1. open this example https://staging-v6.patternfly.org/components/dual-list-selector#with-tree
2. type in "Fruits" to the left search bar
3. click the "Add all" button (`>>`) to move the items to the right - all items will be moved, including Bread and Vegetables, which were invisible due to the filter.

**Expected behavior**
Only Fruits is moved, Bread and Vegetable will stay on the left side - it will not be shown because of the filter, but once the filter is removed, it shows in the list again.
It should behave like this example: https://staging-v6.patternfly.org/components/dual-list-selector/#using-more-complex-options-with-actions

**Screenshots**

https://github.com/user-attachments/assets/391a9211-50b4-4bdb-8f7f-f7e3e142eaf2

**What is your environment?**
 - OS: macOS 14.6.1 
 - Browser: Firefox
 - Version 128.0.3

**Comment by tlabaj** [comment]
WE need to look into this. If this is a componet issue we may need to fix it in PF5.  If it is example code we can just fix it in v6.

**Comment by adamviktora** [comment]
It is just in the example code. I am working on a fix now.
