### ISSUE TITLE
Latest @pattenflu/react-core package broke TypeScript

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1088]
The latest @patternflybot/react-core package appears to be broken. Getting a ton of TypeScript errors with v1.40.1. I don't see an index.d.ts file in the dist/js/components directory.

![screen shot 2018-12-18 at 2 37 31 pm](https://user-images.githubusercontent.com/17481322/50178607-ffd44580-02d2-11e9-9f10-6387056944c4.png)

**Comment by dlabaj** [comment]
@dlabrecq Looking at this now.

**Comment by dlabrecq** [comment]
v1.39.0 (from Dec 7th) and 1.39.1 are broken as well -- v1.38.6 works.

**Comment by dlabaj** [comment]
@dlabrecq Adding back d.ts files for now to resolve this issue.  I'll include you on the PR so you can verify that it works for you.

**Comment by dlabaj** [comment]
Created issue #1094 to fix this to support tsx files.

**Comment by jschuler** [comment]
Addressed via #1093
