### ISSUE TITLE
Bug - [NavList] - [Scroll buttons no longer show up when resizing]

### ISSUE THREAD

**Issue by jelly** [patternfly/patternfly-react#10897]
**Describe the problem**

In our automated pixel test we no longer see the left/right scroll buttons to browse through a navlist when the display is too small to see all nav items. When we refresh the page the buttons show up again.

This problem started in an upgrade to 5.4.0 for us.

**How do you reproduce the problem?**

I can reproduce this with the [NavList Tertiary Demo](https://www.patternfly.org/components/navigation/react-demos#tertiary-nav-deprecated)

**Expected behavior**

Buttons show up.

**Is this issue blocking you?**

For now we work around it in the test.

**Screenshots**

Demo screencast:
[Screencast from 2024-09-03 14-20-53.webm](https://github.com/user-attachments/assets/9fa338bb-7419-46d7-894b-708f02159f00)

**What is your environment?**
 - OS: Red Hat Linux
 - Browser Firefox
 - Version latest

**What is your product and what release date are you targeting?**

Cockpit, none.

**Any other information?**

**Comment by mvollmer** [comment]
This bug is back with Patternfly 6. The fix #11099 seems to be missing from it.

**Comment by tlabaj** [comment]
cc @nicolethoen
