### ISSUE TITLE
Bug - Select - Opening a select that is in a scrollable which is not the body causes screen to jump

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#10896]
**Describe the problem**
Opening a select that is in a scrollable which is not the body causes screen to jump if the menu would go off the screen.

**How do you reproduce the problem?**
https://codesandbox.io/p/sandbox/festive-fire-9dhpjs?workspaceId=eea9ed0c-da74-4627-b8e0-631826ffcb34
Scroll down to value 22 and open the select.

**Expected behavior**
The menu should open leaving the scrollable in the same position.

**Is this issue blocking you?**
Yes

**What is your product and what release date are you targeting?**
RHOAI - already released

**Any other information?**

**Comment by andrewballantyne** [comment]
Can I get an update on this ticket for where we are with the status?

**Comment by jeff-phillips-18** [comment]
@andrewballantyne This is fixed by #11018 , I'll be updating to the new release shortly.
