### ISSUE TITLE
Bug - Modal - self referrential aria-labelledby causing accessible name issues

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-react#11068]
**Describe the problem**
PF5 version of https://github.com/patternfly/patternfly-react/pull/11011

The new Modal has an aria-labelledby that points to itself when an aria-label is passed, which causes a11y issues.

Approach can likely be the same as https://github.com/patternfly/patternfly-react/issues/11012, just placed on v5

**Comment by tlabaj** [comment]
close by #11088
