### ISSUE TITLE
Search missing left-side border

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#11120]
Updated Cost Management to use PatternFly's Search component. The search icon looks fine on the left-side, but the border is partially missing for the right-side icon / button

![Image](https://github.com/user-attachments/assets/c07dca3b-f87f-4113-9a9b-517487a87ee2)

![Image](https://github.com/user-attachments/assets/774f6680-040a-42de-86f3-bcd0f6c23f9f)

**Comment by mcoker** [comment]
Looked at this with @dlabrecq - looks like it's coming from [this CSS override in cost](https://github.com/dlabrecq/koku-ui/blob/482338e66dc024a706508c0259eb4fa1656c5f3f/src/routes/components/dataToolbar/dataToolbar.scss#L11-L14) that is likely a remnant from v5 and can be removed.
