### ISSUE TITLE
Bug - Text, TextComponent - not exported by @patternfly/react-core v6.0.0

### ISSUE THREAD

**Issue by riccardo-forina** [patternfly/patternfly-react#11161]
**Describe the problem**

`Text` and `TextContent` are not exported by `@patternfly/react-core` v6.0.0

**How do you reproduce the problem?**
The CodeSandbox [suggested by this template](https://codesandbox.io/p/sandbox/serverless-cherry-q9t3f) already shows the problem.

**Comment by kmcfaul** [comment]
The `Text` and `TextContent` components have been combined into the `Content` component in v6. We have a [codemod](https://github.com/patternfly/pf-codemods?tab=readme-ov-file#text-replace-with-content-10643) that will run as part of the v5 to v6 migration that will automatically update all references, or both `Text` or `TextContent` may be manually replaced with `Content` as the API is largely the same (the major difference is `TextContent`'s `isVisited` prop becomes `isVisitedLink`).
