### ISSUE TITLE
Menu with favorite icon no longer needs pf-m-favorite class added

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly-react#11176]
The react Menu component applies a `pf-m-favorite` class that is no longer needed to style the star icon.
https://github.com/patternfly/patternfly-react/blob/a382cd6024f91644fb52e77090e62f743cee7eac/packages/react-core/src/components/Menu/MenuItemAction.tsx#L51

Core pr that sets star icon gold color 
https://github.com/patternfly/patternfly/pull/7184

**Comment by tlabaj** [comment]
Let's leave it for now so we do not break an consumers.
