### ISSUE TITLE
PF4 dropdowns cannot be closed on iOS/Mobile Safari

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#1125]
Following on to https://github.com/patternfly/patternfly-react/issues/1113, dropdowns cannot be closed by clicking the dropdown toggle **or the non-clickable negative space elsewhere on the page in iOS/Mobile Safari** .  The only way to close a dropdown in iOS/Mobile Safari is to click one of the dropdown menu items or another clickable item elsewhere on the page.

**Comment by jgiardino** [comment]
I think this issue is a duplicate of https://github.com/patternfly/patternfly-react/issues/984, but let me know if not.
