### ISSUE TITLE
Bug - TableText - regression - PF6 TableText wrapModifier="truncate" is broken

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#11314]
**Describe the problem**
Regression in PF6 `TableText wrapModifier="truncate"` not working as expected and truncating text when sufficient space exists.

**How do you reproduce the problem?**
Go to https://www.patternfly.org/components/table
Modify the first example to render the name with truncation using `TableText`:
`<Td dataLabel={columnNames.name}><TableText wrapModifier="truncate">{repo.name}</TableText></Td>`
Observe all values are truncated when sufficient space exists.

**Expected behavior**
Truncations with `TableText wrapModifier="truncate"` should work the same in PF6 as PF6

**Is this issue blocking you?**
Yes

Workaround? Possibly with `Truncate` or otherwise to not truncate with `TableText`

**Screenshots**
If applicable, add screenshots to help explain the issue.
PF6
![Image](https://github.com/user-attachments/assets/d1d361b0-3915-4df0-baf2-73191c07fcd7)

PF5
![Image](https://github.com/user-attachments/assets/5e771216-a1f5-456b-a780-3234b3aba7d2)

**What is your environment?**
 - OS: macos
 - Browser chrome
 - Version 131.0.6778.86

**What is your product and what release date are you targeting?**
RHOAI 2.17

**Any other information?**

**Comment by tlabaj** [comment]
This should be fixed in 6.1.  closed by https://github.com/patternfly/patternfly/pull/7175
