### ISSUE TITLE
Dropdown component does not close on touch event outside of the focused area

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-react#1131]
When touching outside of the dropdown area on a mobile device, the dropdown does not close. The click event needs to support touch events & behave the same way it does on the desktop version.

**Comment by mturley** [comment]
@kmcfaul, I asked @dgutride if there was anything that needed attention and he gave me this one, but I noticed you're working on relevant changes in #1014. I'm planning to take a crack at this tonight or tomorrow morning, but feel free to stop me if I'm stepping on your toes.

**Comment by mturley** [comment]
Interesting note, this issue appears to be iOS-specific, I can't reproduce it on my Android device but I can on my iPad.

**Comment by mturley** [comment]
This appears to be happening due to a bug in `focus-trap-react`. I opened an issue there, I can reproduce it by using their demo page on an iPad: https://github.com/davidtheclark/focus-trap-react/issues/37
