### ISSUE TITLE
Modal `isLarge` is confussing

### ISSUE THREAD

**Issue by boaz0** [patternfly/patternfly-react#1138]
Since there is no Wizard in PF next yet, it was decided to use Modal for that.
The problem we have right now is that `isLarge` set the `max-width` attribute of the Modal window while I was expecting it sets the `width` attribute to max.

I need this because in each step in the wizard a form is rendered. Some steps have only two fields and others have description text too. This makes different steps change the size of the Modal window which hurts UX. See [here](https://access.redhat.com/insights/platform/storybook/?selectedKind=Components&selectedStory=Wizard) what I mean

Can we do something about it?

**Comment by tlabaj** [comment]
@boaz0   The link you provided is not working.

**Comment by mcoker** [comment]
Created https://github.com/patternfly/patternfly-next/issues/1202 to allow for this

**Comment by boaz0** [comment]
@tlabaj -- I updated the link. Can you try it again [here](https://access.redhat.com/insights/platform/storybook/?selectedKind=Components&selectedStory=Wizard)

**Comment by tlabaj** [comment]
Closed by PR #1372
