### ISSUE TITLE
Need support for UMD and es2015 bundles

### ISSUE THREAD

**Issue by ssilvert** [patternfly/patternfly-react#1142]
Now that Keycloak's account management console has switched from Angular 2+ to React, we want to use the PatternFly React components.  However, our application must use SystemJs as a module loader instead of a pre-bundling solution like WebPack.  SystemJs requires UMD files, which most major libraries provide.

Dan Labrecque modified the PatternFly Angular build to create these files and it worked beautifully.  The issue is here:
https://github.com/patternfly/patternfly-ng/pull/373

Can you guys do the same for React?

**Comment by dlabrecq** [comment]
Patternfly-NG is using Rollup to build ES and UMD bundles, while react-core uses Babel to generate ES.

That said, I was able to generate UMD by adding the following to the react-core package.json file.

```
"build:babel": "concurrently \"yarn build:babel:cjs\" \"yarn build:babel:esm\" \"yarn build:babel:umd\"",
"build:babel:umd": "cross-env BABEL_ENV=production:umd babel src --out-dir dist/umd --extensions \".css,.js,jsx,.ts,.tsx\"",
```

And in .babelrc.js, I added this:

```
'production:umd': {
      plugins: [
        'babel-plugin-typescript-to-proptypes',
        '@babel/plugin-proposal-export-default-from',
        '@babel/proposal-class-properties',
        '@babel/proposal-object-rest-spread',
        [
          '@patternfly/react-styles/babel',
          {
            srcDir: './src',
            outDir: './dist/umd',
            useModules: true
          }
        ]
      ]
    }
```

The package.json of react-core currently uses these properties. I don't have a SystemJS environment to test, so I cannot confirm if that will be an issue?

"main": "dist/js/index.js",
"module": "dist/esm/index.js",

Note that the react-charts and react-table packages would need to be updated as well.

**Comment by ssilvert** [comment]
A single file would be quick and easy for getting started with development, but it would be wasteful in production.

If it's easy to do, can we publish both?  I see advantages to both approaches.

Would you like me to create a simple SystemJs app for testing?  Alternatively, I could just take what you produce in your branch and verify that it works on my current project.

**Comment by priley86** [comment]
I ran into other issues w/ `rollup-plugin-babel` and importing react-styles. If anyone wants to experiment with this, my branch is [here](https://github.com/priley86/patternfly-react/tree/umd-support). 

[babel-plugin-transform-es2015-modules-umd](https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-umd) seems like the safest path for now. 

@ssilvert can you possibly clone #1150 and see if the `dist/umd` directory checks out OK on your end?

**Comment by ssilvert** [comment]
@priley86 I can try this tomorrow.  Any tips on how to build it?

Also, I did create a demo app for you.   If you look at system.js.config, you will see how I declare react's umd files.  Then I use them in Main.tsx.  

You'll just need to do the same for your umd files and add a patternfly-react component to Main.tsx.  Then "npm run build" and "npm run server".

https://github.com/ssilvert/systemjs-react

**Comment by priley86** [comment]
```
git clone https://github.com/priley86/patternfly-react.git  (or add my remote...whichever)
cd patternfly-react
git fetch origin babel-plugin-transform-umd:babel-plugin-transform-umd
git checkout babel-plugin-transform-umd
yarn install
yarn build
cd packages/patternfly-4/react-core
yarn build:umd
```
You can then copy over the `dist/umd` build in react-core over to your project's `node_modules\@patternfly\react-core\dist\umd` folder and try to load the modules from there.

**Comment by ssilvert** [comment]
I'm running Windows.  Your build scripts fail on my box.  I played around with it to try to do some stuff manually, but I think it's not worth the effort to get your build to run.

Can you just zip up the dist and email it to me?

**Comment by priley86** [comment]
@ssilvert email sent 😸

**Comment by ssilvert** [comment]
@priley86 Did your build create a /bundles directory?  I think that's what I actually need.
