### ISSUE TITLE
Catalog Tile titles over-run boundary for long names w/o breaks

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#1146]
![image](https://user-images.githubusercontent.com/11633780/50833100-33c4e880-131e-11e9-99fd-3ab55839be9e.png)

**Comment by dgutride** [comment]
Would be nice to fix this in the extension package if we can get that in.

**Comment by mcarrano** [comment]
@jeff-phillips-18 what is the fix you are looking for here? My opinion is that these very long names should be truncated per the guidelines given here: https://www.patternfly.org/v3/styles/terminology-and-wording/ Is there another solution you are looking for?

**Comment by jeff-phillips-18** [comment]
The fix can be found in the override in openshift console PR above:
https://github.com/openshift/console/pull/1025
