### ISSUE TITLE
import of uuid module failing in DualListSelector

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#1174]
With last update of patternfly-react, importing the module started failing, with the following error.
```
ERROR in ../node_modules/patternfly-react/dist/esm/components/DualListSelector/components/DualListHeading.js
Module not found: Error: Can't resolve 'uuid/v1' in '/build/cockpit/node_modules/patternfly-react/dist/esm/components/DualListSelector/components'
 @ ../node_modules/patternfly-react/dist/esm/components/DualListSelector/components/DualListHeading.js 3:0-27 65:35-39
 @ ../node_modules/patternfly-react/dist/esm/components/DualListSelector/index.js
 @ ../node_modules/patternfly-react/dist/esm/index.js
```

It's complaining about the import here,
https://github.com/patternfly/patternfly-react/blob/1fce402533adce30a9f498305e2d23e26a6a8814/packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHeading.js#L3
This file was introduced with 8c3447 first time in patternfly-react@2.26.2

**Comment by KKoukiou** [comment]
@mturley the uuid module exists locally (correctly brought by patternly-react dependencies) it's just that I see you 're trying to import from subfolder v1, when you do `import 'uuid/v1'`
This subfolder does not exist though. There is uuid.js file which exports v1 function. Is this syntax correct to import function from inside a file?

For me it works if I do,
```diff
diff --git a/packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHeading.js b/packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHeading.js
index a52b942a..9973650b 100644
--- a/packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHeading.js
+++ b/packages/patternfly-3/patternfly-react/src/components/DualListSelector/components/DualListHeading.js
@@ -1,6 +1,6 @@
 import React from 'react';
 import PropTypes from 'prop-types';
-import UUID from 'uuid/v1';
+import uuid from 'uuid';
 import { DropdownKebab } from '../../../index';
 import DualListFilter from './DualListFilter';
 import DualListSort from './DualListSort';
@@ -8,6 +8,8 @@ import DualListMainCheckbox from './DualListMainCheckbox';
 import { noop } from '../../../common/helpers';
 import { SORT_ARIA_LABEL } from '../constants';
 
+var UUID = uuid.v1;
+
 const DualListHeading = ({
   isSortAsc,
   onSortClick,
```

**Comment by mturley** [comment]
According to uuid's docs at https://www.npmjs.com/package/uuid, this syntax is expected, but only since uuid version 3.x (after which the `uuid` import is deprecated). I think something is causing cockpit to resolve an older version of uuid, judging by your `ls` output there. When I build another project I'm seeing the `v1.js` file appear in there:

```
mikebookpro:pf3-integration mturley$ ls node_modules/uuid/
AUTHORS		README.md	index.js	v1.js		v5.js
CHANGELOG.md	README_js.md	lib		v3.js
LICENSE.md	bin		package.json	v4.js
```
