### ISSUE TITLE
Checkbox Support

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#119]
Create support for checkboxes:

Include story examples demonstrating these features in a mock application scenario

Link to JIRA story:
https://patternfly.atlassian.net/browse/OSUX-348

**Comment by priley86** [comment]
I am running into issues with inline styles and additional div's being rendered with the React Bootstrap checkbox. I will update this issue shortly with details.

**Comment by serenamarie125** [comment]
@priley86 It looks checkboxes are already in the [Supported Form Controls](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Show%20Help=true&knob-Disabled=false&selectedKind=Forms&selectedStory=Supported%20Controls&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) in the storybook, can you confirm?

**Comment by priley86** [comment]
So... the React Bootstrap Checkbox implementation seems to do the following:

If I just use the default `<Checkbox>`, I get the following markup:
```
<div class="checkbox"><label title=""><input type="checkbox" value="on"></label></div>
```
I use the inline option,`<Checkbox inline>`  I get:
```
<label class="checkbox-inline" title=""><input type="checkbox" value="on">1</label>
```

These both work fine in forms typically, but for the DataTable selection checkboxes, these classes applied on the outer elements break the design. To match our existing design most closely, I can do something like this:
```
          <ControlLabel srOnly htmlFor={id}>
            {label}
          </ControlLabel>
          <FormControl type="checkbox" id={id} checked={rowData.selected} bsClass=" "
            onChange={e => {this.onSelectRow(e, rowData);}}
          />
``` 
OR just:
```
<ControlLabel srOnly htmlFor={id}> {label}</ControlLabel>
<input type="checkbox" id={id} checked={rowData.selected}
            onChange={e => {this.onSelectRow(e, rowData);}}/>
```
And I get the rendered output that most closely mimics the existing html/design:
```
<label for="select0" class="control-label sr-only">Select row 0</label>
<input type="checkbox" id="select0" value="on">
```

I guess what's bothering me about this is I prefer to just use `<Checkbox>`. I think it might be nice to write a wrapper on top of React Bootstrap Checkbox which just renders an `input type="checkbox"`. Maybe `<Checkbox type="form">` renders to the ReactBootstrap default, and `<Checkbox type="input"` renders just an `<input>`?

Thoughts @jeff-phillips-18 @sharvit @cdcabrera ?

We have the same exact issue w/ <Radio> it appears 😄 ...

**Comment by sharvit** [comment]
@priley86 - I think I prefer to create another new component called `DataTableCheckbox, DataTable.Checkbox`.
This component can handle it inside and should be used only inside the DataTable.

**Comment by jeff-phillips-18** [comment]
I'm OK with this proposal @sharvit though for option 3 it seems we lose bootstrap's additional capabilities and could cause some inconsistencies.

**Comment by jeff-phillips-18** [comment]
Should we update this issue to reflect current status? Currently we do have checkbox support. If there are issues with the current implementation then those should be separate issues.

**Comment by priley86** [comment]
i guess this is just really a case where I disagree with React Bootstrap's api (and would have just had `Checkbox` render an `input`), however to keep it consistent with the React Bootstrap docs, I'm fine with @sharvit 's proposal. I think this should be something that gets re-evaluated when we look at Reacstrap / PF Next...

Also fine w/ closing this issue @jeff-phillips-18.
