### ISSUE TITLE
PF4 [DOCS]:  Dropdown documentation regarding React Router Link needs review

### ISSUE THREAD

**Issue by michaelkro** [patternfly/patternfly-react#1196]
In the Dropdown documentation, we currently recommend adding `<Link />` components as children directly under `<Dropdown />`.

> A react-router Link may be wrapped by DropdownItem or used directly within Dropdown.

Unfortunately, in this case, keyboard interactivity is lost, and if more than one `<Link />` is added, the consumer will be required to provide custom styles (not sure if this is expected or not)

***Screenshot***
![patternfly_seed](https://user-images.githubusercontent.com/15141412/51261568-7f127300-197e-11e9-8ae7-f59289e66ffa.png)

***Code***
```js
export default class App extends Component {
  state = {
    isOpen: false
  };
  onToggle = () => {
    this.setState(prevState => ({
      isOpen: !prevState.isOpen
    }));
  };
  render() {
    const { isOpen } = this.state;
    return (
      <div>
        <Dropdown
          toggle={
            <DropdownToggle isOpen={isOpen} onToggle={this.onToggle}>
              dude
            </DropdownToggle>
          }
          isOpen={isOpen}
        >
          <Link to="#">First Link</Link>
          <Link to="/">Second Link</Link>
        </Dropdown>
      </div>
    );
  }
}
```
***NOTE***:  Tested by spinning up a starter app with `patternfly-react-seed` and adding `react-router-dom`

***EDIT***:  Removed the wrapping `React.Fragment` after testing.  Results still seem to be the same.

**Comment by kmcfaul** [comment]
Is the behavior the same without wrapping the Links in a React.Fragment? I remember mapping the dropdown item styling and keyboard events to custom child items so it might be that a wrapped block of Links isn't handled right now.

**Comment by michaelkro** [comment]
whoops, good call.  Let me remove the fragment from my sample app and see.

**Comment by michaelkro** [comment]
hmm, it doesn't seem to make a difference.  If you want, I can create a repo with my sample app for you to take a look at

**Comment by kmcfaul** [comment]
I will try testing locally first. How about if you wrap the Link in a DropdownItem?

**Comment by michaelkro** [comment]
If I wrap the Links in DropdownItems, I am seeing some console errors.  I believe that #1193 resolves the second

```
app.bundle.js:65294 Warning: Function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Context.Consumer`.
    in Item (created by Context.Consumer)
    in div (created by Context.Consumer)
    in DropdownMenu (created by Dropdown)
    in div (created by Dropdown)
    in Dropdown (created by App)
    in div (created by App)
    in App (created by Route)
    in Route (created by AppRouter)
    in Switch (created by AppRouter)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by AppRouter)
    in AppRouter
```

```
app.bundle.js:7724 Uncaught TypeError: this.props.context.sendRef is not a function
    at DropdownItem.componentDidMount (app.bundle.js:7724)
    at commitLifeCycles (app.bundle.js:68195)
    at commitAllLifeCycles (app.bundle.js:68386)
    at HTMLUnknownElement.callCallback (app.bundle.js:65180)
    at Object.invokeGuardedCallbackDev (app.bundle.js:65200)
    at invokeGuardedCallback (app.bundle.js:65216)
    at commitRoot (app.bundle.js:68417)
    at completeRoot (app.bundle.js:68738)
    at performWorkOnRoot (app.bundle.js:68719)
    at performWork (app.bundle.js:68700)
```

**Comment by kmcfaul** [comment]
I determined that when custom items are directly under Dropdown they are not being assigned the DropdownItem styling. I am still looking into fixing the keyboard events which are throwing errors because the refs of the Links aren't giving the DOM node.

**Comment by rachael-phillips** [comment]
Completed and closing this issue :)
