### ISSUE TITLE
Chip tooltip overflow conditional render fix

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-react#1197]
Currently we are hard coding a check for the length of the chip text to determine if a tooltip is required. This should be replaced with a more elegant solution (e.g. using refs to check the css overflow values). Also, there is a bug with the current implementation causing an error to be thrown if the chip is empty.

**Comment by rebeccaalpert** [comment]
@ibolton336 are empty Chips a common use case?

Using refs gets rid of the main error, but the Chip component currently requires children as a prop. Should I open that up so it's optional or leave it as-is?

**Comment by ibolton336** [comment]
@rebeccaalpert Hey I would open it up to be optional. I think eventually we should add an input to the chip so that the user can start with a blank chip and add their dynamic text.
