### ISSUE TITLE
PF4: Custom Select Component: Single Select variation

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1214]
**This issue covers the Single Select variation of the Custom Select only:**   
(This issue is a child of issue #1206)

Related issue in Core: https://github.com/patternfly/patternfly-next/issues/651  

Info provided on the component: https://docs.google.com/document/d/1rrCdARutABI-Vpa_mdMWGl2xJJTtt2dPQ2bjFx2zwCM/edit?usp=sharing

see: https://pf-next.com/components/Select/examples/

In addition to a React review, this issue should be reviewed by the core contributors:
CSS: @srambach (CSS) @mcarrano (interaction design) @christiemolloy (visual design)

**Comment by rachael-phillips** [comment]
Closing this issue because it was completed in PR #1277
