### ISSUE TITLE
PF4: Custom Select Component: Type-ahead select (multi item) variation

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1216]
This issue covers the Type-ahead select (multi item) variation of the Custom Select only:
(This issue is a child of issue #1206 )

On hold until Type-ahead select (single item) complete (issue #1215 )

Related issue in Core: patternfly/patternfly-next#651

Info provided on the component: https://docs.google.com/document/d/1rrCdARutABI-Vpa_mdMWGl2xJJTtt2dPQ2bjFx2zwCM/edit?usp=sharing

see: https://pf-next.com/components/Select/examples/

In addition to a React review, this issue should be reviewed by the core contributors:
CSS: @srambach (CSS) @mcarrano (interaction design) @christiemolloy (visual design)

**Comment by dgutride** [comment]
Closed via https://github.com/patternfly/patternfly-react/pull/1839
