### ISSUE TITLE
Update Alert component to match core updates

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-react#1220]
The markup has changed for core so we'll have to update in React.
## Core component/PR/issue/version
https://pf-next.com/components/Alert/examples/
This relates to [this issue](https://github.com/patternfly/patternfly-next/issues/1226) and [this PR](https://github.com/patternfly/patternfly-next/pull/1257).
Core v1.0.132

The most significant change is the removal of `.pf-c-alert__body` the wrapper that use to contain all the text of the alert. 

We now just have the `.pf-c-alert__title` and we've added `.pf-c-alert__content` to wrap any additional content. This would likely only be `<p>` with `<a>` contained inside of them.

In terms of accessibility we no longer have `role="alert"` which was on the `.pf-c-alert__body`. We also now require the `.pf-c-alert__action` to always be the last element in the DOM contained inside `.pf-c-alert`.

Please let me know if you have any questions :)

**Comment by jgiardino** [comment]
We've also updated the screen-reader-only text to include "alert"—e.g. "Success alert:" instead of just "Success:" in front of the alert heading.

As always, this text should be defined as default values, but the consumer should be able to update this text with translated values.

**Comment by tlabaj** [comment]
closed by #1259

**Comment by tlabaj** [comment]
closed by #1259

**Comment by tlabaj** [comment]
closed by #1259
