### ISSUE TITLE
PF4: Inline-Editable Table 

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#1228]
This issues builds on to #402 for adding the inline edit feature to PF4 React tables.

Relevant design/core issues:
https://github.com/patternfly/patternfly-next/issues/404
https://github.com/patternfly/patternfly-next/issues/199

Since this is a highly requested feature for some product teams and we'd like to further the design discussion independently right now, we would like to release this feature as a "pf4 extensions" package right now. This functionality could be distributed and labeled as `@patternfly/inline-edit-extension` for the time being so that product teams can consume now and revisit later when design review is completed.

**Comment by dgutride** [comment]
Closing this since the referenced PR was merged
