### ISSUE TITLE
Paging Support

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#123]
Create support for Paging component:
PatternFly design documentation: https://www.patternfly.org/pattern-library/navigation/pagination/

Include story examples demonstrating paging into a mock application scenario

* ~~Add pagination row component (for use in list view, table view, card view)~~ (finished in #143)
* Add simple previous/next pagers [here](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/pagination.html) and pagination default/mini size. 

Links to JIRA story:
https://patternfly.atlassian.net/browse/OSUX-371 (paging)
https://patternfly.atlassian.net/browse/OSUX-340 (List View using paging)
https://patternfly.atlassian.net/browse/OSUX-339 (Table using paging)

**Comment by tstrachota** [comment]
FYI I'm currently working on a pagination component. It seems that I lack permissions to assign this issue to myself. I'll provide a PR soon.

**Comment by jeff-phillips-18** [comment]
Thanks @tstrachota, I have added you to the contributors team. You should now have assign permissions.

**Comment by priley86** [comment]
@tstrachota apologies for the confusion on this and thanks for the contribution. I will compare/contrast today. Hopefully we can get this one in soon ;)

**Comment by tstrachota** [comment]
@priley86 I was looking into open PRs if somebody already started implementing it but apparently I missed yours :-/
That happens. Anyway, I'm ready to incorporate your ideas or collaborate towards a single solution.

**Comment by priley86** [comment]
@tstrachota thanks! feel free to chime in with any issues...

**Comment by priley86** [comment]
@tstrachota also... i am likely not going to get around to implementing the 

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/pagination.html

**Comment by priley86** [comment]
Opened #217 to add the simple previous/next paging buttons. Closing this one and putting back to the backlog.
