### ISSUE TITLE
Dropdown cut off if rendered inside element with `overflow: hidden`

### ISSUE THREAD

**Issue by TimoSta** [patternfly/patternfly-react#1230]
**Problem:**
If a PF4 dropdown is rendered inside a an element that is set to `overflow: hidden`, any part of the dropdown that that is larger than the container is clipped:

![image](https://user-images.githubusercontent.com/5621996/51552845-8256a480-1e3f-11e9-9e7a-4065817c7136.png)

See [this example for a minimal reproduction](https://codesandbox.io/s/j35x1my5).

---

 **Background:**
We are trying to render a dropdown menu on a tab component, to offer options like _duplicate tab_ or _delete tab_.

To make the tabs render properly, we need to set the CSS overflow property of the container to `hidden`. As a result, the dropdown menu on the tab becomes unusable, as it is confined to the space of the tabbar.

---

**Potential Solution:**
A possible solution to this would be to render the dropdown menu not as a child of the toggle in the DOM tree, but rather at the root of the tree, and position it correctly using absolute values. This way, the dropdown is still rendered in the correct place on the UI, but is no longer affected by styles of the parent elements in the tree.

This approach has been taken for example by  Tippy.js, and as a result is in use by PF4 for the tooltip/popover components, and also by Material-UI for [their implementation of dropdown menus](https://material-ui.com/demos/menus/).

---

If you are generally in favor of this approach, I'm more than happy to give the implementation a shot and see how it turns out!

**Comment by jschuler** [comment]
Great suggestion, we should provide users the option to attach the menu to the document body or wherever they choose. We already do this for some other components, like Tooltip and Popover, I think this is another good use-case.

**Comment by rachael-phillips** [comment]
Hi @TimoSta ! Is this something you would be interested in working on?

**Comment by rachael-phillips** [comment]
Hi @TimoSta how is it going on this issue?

**Comment by rachael-phillips** [comment]
Closing because this has been inactive for a long period of time
