### ISSUE TITLE
Pagination should show word page

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#1233]
When using PF3 pagination user might be confused what are numbers and buttons on right side we should include word page and items/records/`${customLabel}` somewhere in there 
![selection_020](https://user-images.githubusercontent.com/3439771/51596280-e1c4bb00-1ef8-11e9-8156-d837ccb70dba.png)

**Comment by dgutride** [comment]
This matches the patternfly design here:  https://www.patternfly.org/pattern-library/navigation/pagination/#design - moving to closed since the implementation is correct.  If you'd like to have the design re-evaluted for PF3, please open an issue in patternfly design.
