### ISSUE TITLE
Component - File Select

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#125]
Create support for file select:

Include story examples demonstrating these features in a mock application scenario

Associated JIRA Issue: https://patternfly.atlassian.net/browse/OSUX-334

**Comment by cdcabrera** [comment]
[Appears some of the baseline work for this is being accomplished with this example](http://rawgit.com/sharvit/patternfly-react/storybook/forms/index.html?knob-Label=Danger%20Will%20Robinson%21&knob-Disabled=false&knob-Show%20Labels=false&knob-Show%20Help=true&knob-Show%20Modal=true&knob-Show%20Loading=false&selectedKind=Forms&selectedStory=Input%20Groups&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) going with PR #131
