### ISSUE TITLE
Wizard - Support for Embedded Wizard

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#126]
Follow on to https://github.com/patternfly/patternfly-react/issues/64
Requires https://github.com/patternfly/patternfly/issues/841

**Comment by priley86** [comment]
@jeff-phillips-18 @jgiardino can this issue be updated to "remove embedded wizard" references?

**Comment by jeff-phillips-18** [comment]
But we already have support for non-embedded wizard. We can close the issue if we feel we never want to support embedded.
