### ISSUE TITLE
Update Toggle button with Core changes

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-react#1266]
Another easy one. 
The menu toggle needs `aria-expanded="true/false" applied.
[PR](https://github.com/patternfly/patternfly-next/pull/1294)

**Comment by rebeccaalpert** [comment]
.pf-c-page__header-brand-toggle > .pf-c-button in the [Page component](http://patternfly-react.surge.sh/patternfly-4/components/page) already seems to have this.

**Comment by rebeccaalpert** [comment]
Per @matthewcarleton, this is all set!
