### ISSUE TITLE
html, body, and .pf-c-page changed to "height: 100%;"

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1294]
As result of some iOS scrolling issues, we changed the height of `.pf-c-page` from `height: 100vh;` to `height: 100%;` requiring the ancestors of `.pf-c-page` to also have `height: 100%`. This was only a CSS change, but we just need to ensure it works in react. It may require adding `height: 100%` to any ancestors of `.pf-c-page`. 

https://github.com/patternfly/patternfly-next/pull/1290/

@tlabaj for PR review

**Comment by jschuler** [comment]
Should probably add a description on the page component that this may be required by the consumer to ensure the ancestors have height 100%
