### ISSUE TITLE
ListView: "React does not recognize the InitExpand prop" warning

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1299]
The `React does not recognize the "InitExpand" prop` warning shows up in the browser console for the Koku UI, whenever the ListView is rendered. 

<img width="1144" alt="screen shot 2019-01-31 at 10 14 29 pm" src="https://user-images.githubusercontent.com/17481322/52100492-bbacb400-25a5-11e9-9e02-94bbfe74aff5.png">

Running the patternfly-react tests also generate the similar warning below.

<img width="951" alt="screen shot 2019-01-31 at 9 57 10 pm" src="https://user-images.githubusercontent.com/17481322/52100329-14c81800-25a5-11e9-999c-1af1d571ae51.png">

**Comment by martinpitt** [comment]
Do you mind fixing the issue title to `initExpanded`, to make this appear in searches? I've stumbled over the same problem when using  `ListView` in Cockpit. Thanks!

**Comment by jeff-phillips-18** [comment]
This was fixed by https://github.com/patternfly/patternfly-react/pull/1331
