### ISSUE TITLE
Multiple test warnings

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1301]
Seeing quite a few warnings while running the patternfly-react tests. Some of these warnings (e.g https://github.com/patternfly/patternfly-react/issues/1299) are showing up in the browser console for Koku UI.

<img width="861" alt="screen shot 2019-01-31 at 9 56 53 pm" src="https://user-images.githubusercontent.com/17481322/52100646-4beaf900-25a6-11e9-9420-fa608b31d352.png">

**Comment by tlabaj** [comment]
@dlabrecq I think some of those are valid warnings when the test case is testing that the warnings are generated as expected.  Ar you seeing these warning outside of running the tests?

**Comment by tlabaj** [comment]
@dlabrecq this is being closed because the behaviour above is expected in the context of the Test.  If you are seeing unexpected console warnings at runtime, please open an issue.
