### ISSUE TITLE
(Table): allow passing custom row, header and cell wrappers

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#1310]
Currently we are using our own row, header and cell wrappers. But there might be consumers that would like to use custom wrappers to change some values in tables.

**Comment by priley86** [comment]
Started to prototype this in OpenShift today - we will need the ability to extend Rows, Headers, and Cells for each view, as well as the ability to apply a "sortField" that is a nested object..i.e.:
```
const columns = [
    { title: 'Name', sortField: 'metadata.name', transforms: [sortable], props },
    { title: 'Status', sortField: 'status.phase', transforms: [sortable], props },
    { title: 'Requester', sortField: 'metadata.annotations.[\'openshift.io/requester\']', transforms: [sortable], props },
    { title: 'Labels', sortField: 'metadata.labels', transforms: [sortable], props },
    { title: '' },
  ];
```

Still a very rough W.I.P. right now (missing sort/pagination, custom `ResourceKebab` etc, but starting to formulate how this _could work_:
https://github.com/priley86/web-ui/commit/b4c390c4bcb11c3d7318ce6d4b1b3a9642496aa2#diff-b2d4cf524cc534d555f71cccff72c6ec

**Comment by priley86** [comment]
i think this issue can be closed - `bodyWrapper` and `rowWrapper` were added a while back in #1227.  I don't think we have cellWrapper, but this can be achieved using `cellTransforms`. Are you OK w/ closing this @karelhala ?

**Comment by karelhala** [comment]
Yeah, we can close this issue, it has been partially resolved or not needed anymore. Closing it and if someone feels like it is still missing they will open a new issue.
