### ISSUE TITLE
Browser tests

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#1315]
QE use library https://github.com/quarckster/widgetastic.patternfly4 to run UI tests in Selenium. In order to keep up the changes in this repo it would be nice to trigger a travis job with browser tests that are described here https://github.com/quarckster/widgetastic.patternfly4/tree/master/testing.
PR #1312

**Comment by quarckster** [comment]
These tests mostly for interactive components such as Dropdown and Navigation. For example it tests if Dropdown can be opened and closed. Sometimes it stops to works due to the changed html of a component, so we need to update the code of the component abstraction. Potentially it can be used as some kind of integration tests for Patternfly.

**Comment by quarckster** [comment]
@dgutride any update on this?

**Comment by redallen** [comment]
Closed in #1312
