### ISSUE TITLE
fix(Alert): Alert component typings

### ISSUE THREAD

**Issue by danielefiungo** [patternfly/patternfly-react#1318]
**Affected**
"@patternfly/react-core": "1.51.6",

**What:**

> /Users/dfiungo/_prjs/redhat/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-core/dist/js/components/Alert/index.d.ts
> ERROR in /Users/dfiungo/_prjs/redhat/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-core/dist/js/components/Alert/index.d.ts(3,3):
> TS2305: Module '"../../../../../../../../../../../../../Users/dfiungo/_prjs/redhat/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/@patternfly/react-core/dist/js/components/Alert/Alert"' has no exported member 'AlertActionCloseButton'.

**How can be reproduced:**

https://github.com/danielefiungo/optaweb-traveling-salesman/tree/update-patternfly-react-deps

Clone the project then:

```bash

$ cd optaweb-vehicle-routing-frontend
$ npm i
$ npm run start

```

**Comment by boaz0** [comment]
@tlabaj it looks like this issue was resolved. Can you close it?
Thanks.

**Comment by danielefiungo** [comment]
Closing issue.
Thanks to @tlabaj
