### ISSUE TITLE
PF4: Popover size attribute has no affect

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1327]
I'm not able to set the width of the PF4 popover component. Using values of 'small', 'regular', and 'large' has no affect. PatternFly appears to override the max width to 300px (converted to 18.75rem).

Note that the popover component also sets 'regular' as a default size. Since there is a default, size should not be required.

My workaround is to override the max width, like so:

```
export const popoverOverride = css`
  &.pf-c-popover {
    --pf-c-popover--MaxWidth: 600px;
  }
`;
```

**Comment by dlabaj** [comment]
@dlabrecq You can set the value with maxWidth property, do you also want support for small, regular, and large?

**Comment by dlabrecq** [comment]
At the time I created the issue, there was a size property. My complaint was that setting the `size` property to 'small', 'regular', or 'large' did not function at all.

Here is the code from the git history.
`size: PropTypes.oneOf(['small', 'regular', 'large']),`

It appears that `size` may been replaced with `maxWidth`. That wasn't available at the time. If `size` is no longer available, then there is no longer an issue.

**Comment by dlabaj** [comment]
Thanks @dlabrecq I'll close this issue now that's it been replaced with maxWidth.
