### ISSUE TITLE
Update classes in page header for header tool icons/menus

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1333]
We've removed the `.pf-u-*` classes in the page header and have baked all of that functionality into the page header classes. You can see those classes here - `.pf-m-user/mobile/icons`

https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/demos/Page/page-template-header-tools-elements.hbs

**Comment by priley86** [comment]
I noted today that many of the page layout demos in PF-R are still using the `.pf-u-*` classes. 

<img width="500" alt="screen shot 2019-02-06 at 12 21 50 pm" src="https://user-images.githubusercontent.com/4237045/52360357-ce8e1100-2a09-11e9-8463-01db7f85c1dd.png">

Only looked at the demos here:
http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout

**Comment by dtaylor113** [comment]
Is this related? #1336

**Comment by dlabaj** [comment]
Will be fixed with #919
