### ISSUE TITLE
PF4 Modal hides body content

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1334]
Installed the prerelease (v1.52.0) of @patternfly/react-core, but the modal no longer displays properly. In the screenshots below, the body is cut off. Cost Management historical charts are not visible and our provider modal now scrolls. 

It appears there is a new max-height property from pf-next. The modal only displays correctly when I disable max-height. This may be a pf-next issue, but may hold up the prerelease?

Cost Management historical charts:
![screen shot 2019-02-06 at 1 08 05 pm](https://user-images.githubusercontent.com/17481322/52364282-d7cfab80-2a12-11e9-94bd-2565597a64e9.png)

Cost Management providers modal:
![screen shot 2019-02-06 at 1 18 18 pm](https://user-images.githubusercontent.com/17481322/52364276-d605e800-2a12-11e9-94c9-614e39a161e1.png)

**Comment by dgutride** [comment]
@rachael-phillips  - this is going to block promotion of the react-core release, can we prioritize and have somebody look into by any chance?

**Comment by rachael-phillips** [comment]
@mcoker will take a look. Thanks for bringing this to my attention!

**Comment by mcoker** [comment]
@christiemolloy we added `--pf-c-modal-box--body--MaxHeight: #{pf-size-prem(360px)};` in https://github.com/patternfly/patternfly-next/pull/1041/commits/87252b29217853ad16c07712b6f62d68d6927b74. That's my commit to your branch, but I was rebasing your original commit while you were out and I don't remember adding a `max-height`. Do you know anything about that line?

**Comment by christiemolloy** [comment]
@mcoker pretty sure it was added to handle the example - "Modal Demo - Long enough to scroll" - where the body is set to 360px max-height and the content scrolls. https://pf4.patternfly.org/demos/Modal/examples-full/?component=Modal%20Demo%20-%20Content%20long%20enough%20to%20scroll

**Comment by tlabaj** [comment]
Closed by PR #1354
