### ISSUE TITLE
PageHeader component: Warning: Invalid attribute name: ``

### ISSUE THREAD

**Issue by rebecabkerr** [patternfly/patternfly-react#1336]
This warning appears in both Firefox and chrome browser consoles, when using the PageHeader component. 
 
**Details:** 
- Using PF4, @patternfly/react-core@1.51.6,
- App built with latest create-react-app, typescript (@3.3.1).
- Tested several code samples from PatternFly React Docs website and all produce this warning
- React Dev tools shows an empty attr name and value in the header tag <header ""="">. There is an unresolved key value pair in the PageHeader.defaultProps ( ...props,  "" : ""}
- Got around it by overriding the PageHeader.defaultProps in the component 

![pageheader_warning](https://user-images.githubusercontent.com/2103774/52378660-48d48a80-2a36-11e9-9028-94f453b6e58b.png)
![pageheader_warning_details](https://user-images.githubusercontent.com/2103774/52379009-3eff5700-2a37-11e9-9da9-9c350e8a777a.png)

**Comment by dlabaj** [comment]
Not seeing this with the latest code base.  I will check with an older version of react-core.

**Comment by redallen** [comment]
This got solved somewhere in the past month, closing.
