### ISSUE TITLE
PF4 Data List: How to put icon into DataListItem?

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#1338]
I tried to put an icon into the left side of DataListItem as it is shown in [pattern library](https://www.patternfly.org/pattern-library/content-views/list-view/#row-variation-examples).

The component DataListCell is not suitable for it because it is too wide. I managed to workaround it. Instead of DataListCell I used `<div className="pf-c-data-list__check">`.

But how to do it right?

**Comment by dgutride** [comment]
This was fixed in core - closing as it shouldn't be an open issue any longer.
