### ISSUE TITLE
PF4 How to correctly highlight text

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#1339]
Is there a standard way for text highlighting? For example, I have list of warnings (e.g. No fencing configured in the cluster) for particular cluster and I want to display this warning in DataListItem for the cluster. Is there standard way (component or using particular styles) to do it?

If this is not the right place for such kind of questions where is possible to ask questions about patternfly4 (react)? 
Thanks.

**Comment by mcarrano** [comment]
@idevat do you have a design mockup of what you are trying to do? I'm wondering is this can be satisfied by just using as Alert Group as shown here: https://pf4.patternfly.org/components/AlertGroup/examples/

**Comment by idevat** [comment]
@tlabaj, @mcarrano thank you for your quick response.

My use case is a dashboard with a list of HA Clusters. For each cluster I have to display basic information about the particular cluster. There may be cluster issues and I need to display it. In the picture below is the first milestone of what should be displayed. (It will become more complex in the future, probably with more details in expanded area.)

![clusters_dashboard](https://user-images.githubusercontent.com/16188254/52466622-3156e800-2b83-11e9-8a46-533dfc7b9474.png)

I'm able to make own components with own styling but I would like to use it as it was intended.

I'm not sure if Alert Group is suitable for this use case. I use it as toast notifications. In fact, I haven't think of using this component in this context. I've never seen it to use it this way. But my concern here is that it would suppress all other information. I think it should stay more compact.

I was told that I have to use patternfly, I'm newbie in using patternfly and I cannot find clues for some tasks. I appreciate all the help.

Btw the picture shows what I meant in issue #1338.

**Comment by mcarrano** [comment]
@idevat Now that I see what you are trying to do, agree that an Alert Group is not the correct approach. Sorry if that confused the issue.  It should be possible to build this using a data list. It's a matter of applying the appropriate layout inside of the list row. @mcoker can you advise here?

**Comment by mcoker** [comment]
@mcarrano @idevat looking at the example above, I would probably use [compound expansion](https://pf4.patternfly.org/components/Table/examples/#) (look for the example under "Table with Compound Expansion") to give more information about each of the cells in your table rows (cluster name, nodes, resources, agents). And for cells that have a warning or alert, use an icon (warning, danger, etc) next to the main row cells that have warnings in them. 

We don't currently have the ability to specify a different color for warning, error, etc text in the table component. So for the moment, you could add your own (though I would question the current choice of color, as it's really difficult to read against a white background). @matthewcarleton also had the idea to add color utility classes for this kind of use. I like the idea of what bootstrap offers - https://getbootstrap.com/docs/4.0/utilities/colors/

**Comment by idevat** [comment]
@mcoker we plan to add expanded area with more details. We would like to have some important aggregate information accessible without row expanding. But even if I moved warning/error list into expanded area, I would have to display it somehow.

I have no problem adding my own parts. But I would like to do it the standard way if possible.

So I have something like this:
```jsx
import React from "react";
import { StyleSheet, css } from "@patternfly/react-styles";
import {
  global_warning_color_200 as warningColor,
} from "@patternfly/react-tokens";

const styles = StyleSheet.create({
  warningList: {
    "margin-left": "1.2em",
  },
  warningItem: {
    color: warningColor.var,
    "list-style-type": "disc",
  },
});

const DashboardClusterWarning = ({ warningList }) => (
  <ul className={css(styles.warningList)}>
    {
      warningList.map((warning, i) => (
        <li key={i} className={css(styles.warningItem)}>
          {warning}
        </li>
      ))
    }
  </ul>
);

export default DashboardClusterWarning;
```

- I eventually found `global_warning_color_100` token. But I'm not sure if it is the correct color. On the picture above is used "orange" which is not much different (`ffa500` vs `f0ab00`). There is also `global_warning_color_200` which is better readable but whilst in context of Alerts it looks well (http://patternfly-react.surge.sh/patternfly-4/components/alert) in my context it does not seem so good to me.

- I used `<ul>` and `<li>` instead of `<List>` and `<ListItem>` because `<List>` already contains class `pf-c-list` which already defines margins and additional classes cannot overwrite it. I used discs because when a message takes more lines it could be harder to recognize which lines belong together.

I don't want to be dogmatic but I expect that as beginner I can miss something that is already solved.

**Comment by matthewcarleton** [comment]
hey @idevat thanks for bringing this up, it has brought attention to something that I think Patternfly would benefit from. In terms of what you show above, I agree with @mcoker this would be a good thing to add to the expanded view. I see your point about showing info at the top level, you could have a status column or something similar with an icon and message that would alert the user to expand and see the info. For warning text we use `#795600` because it provides enough contrast on a white background to pass accessibility requirements. If I can help any further feel free to reach out.

**Comment by idevat** [comment]
@mcoker, @matthewcarleton the color  `#795600` (which corresponds to token `global_warning_color_200`)  provides enough contrast but it suffers from other issues.

1) Color is not a warning too much.
2) I tried to use `global_success_color_200` (`#486b00`) for ok state and it is difficult to distinguish it:

![difficult_to_distinguish_colors](https://user-images.githubusercontent.com/16188254/52954104-8b2c8e80-3389-11e9-9db9-b7785c3d9b74.png)

The use case here is to easily distinguish problematic elements.

**Comment by mcoker** [comment]
I wonder if the text should remain the default black color, and the global warning and success colors could be applied to icons used beside the text it applies to, as shown in your original screenshot? So here you would have a green check and a `#795600` warning triangle? I also wonder if we should add variations to the `label` component that indicate state (matching the states/colors used in the alert component)? @mcarrano

**Comment by mcarrano** [comment]
I think that would work. Agree that the text colors used in the screen shot above does not the intended meaning.

**Comment by dgutride** [comment]
Moving to closed since this question seems to be answered and a follow on issue was creawted.
