### ISSUE TITLE
Table wrong import 

### ISSUE THREAD

**Issue by danielefiungo** [patternfly/patternfly-react#1342]
**What?**
With:
   "@patternfly/patternfly-next": "^1.0.175",
    "@patternfly/react-core": "^1.51.6",
    "@patternfly/react-table": "^0.4.17",

Using react-table, produce "Failed to compile":

> ./node_modules/@patternfly/react-table/dist/esm/components/Table/utils/decorators/sortable.js
Attempted import error: 'modifiers' is not exported from '../../../../@patternfly/patternfly-next/components/Table/table.css.js'.

The bug can be reproduced : 
https://github.com/danielefiungo/react-patternfly-example/tree/%40patternfly/react-table

Component using table: src/components/VehiclesTable.js

```
$ npm i 
$ npm run start
```

![image](https://user-images.githubusercontent.com/1758569/52428679-c665cc80-2b02-11e9-950b-1718a84df847.png)

**Comment by karelhala** [comment]
Hello, sorry this bug was resolved, but reintroduced by wrong rebase. You can fix this by using prerelease version of table `0.4.18`

**Comment by danielefiungo** [comment]
> Hello, sorry this bug was resolved, but reintroduced by wrong rebase. You can fix this by using prerelease version of table `0.4.18`

**Comment by danielefiungo** [comment]
Sorry closed by mistake.

BTW the pre-release version works

**Comment by dlabaj** [comment]
@danielefiungo Is this still an issue I built the code above from the repo and it ran.  Do I need to change something?

**Comment by dlabaj** [comment]
@danielefiungo I updated the code above too the latest versions of the table and patternfly-next and the build failure went away:

    "@patternfly/patternfly-next": "^1.0.175",
    "@patternfly/react-core": "^1.49.6",
    "@patternfly/react-table": "^1.0.33",

I'm going to close this issue but if it's still a problem then let me know and we can reopen this.
