### ISSUE TITLE
PF4 Table: Expanded row max hight forces scrolling

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1346]
The PF4 table appears to have a max height for the expanded row, which forces a scroll bar. This is undesired because there is already a scroll bar for the entire page. We prefer users to not deal with double scroll bars.

Example:
<img width="1340" alt="screen shot 2019-02-07 at 3 06 09 pm" src="https://user-images.githubusercontent.com/17481322/52439785-67945900-2aea-11e9-8b24-b443b0cb24f2.png">

**Comment by karelhala** [comment]
I think this should be brought in core repository https://github.com/patternfly/patternfly-next we don't and should not add custom stylings to components.

**Comment by dlabrecq** [comment]
I agree the styles likely needs to be fixed in core. I'll leave that to the PatternFly folks to decide where the fix is applied.

That said, I installed the prerelease version of the patternfly/react-* packages. I'm not seeing the issue, so it may have been fixed already? I will confirm again when beta is released shortly.

**Comment by tlabaj** [comment]
@mcoker Can you please take a look at this.  Looks like we need a change in core.

**Comment by dlabaj** [comment]
Fixed by core no changes needed in React.
