### ISSUE TITLE
PF4 Table: Component cannot be a direct child

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1351]
I also encountered an issue when adding components inside a child row. For example, I see this warning in the browser console.

<img width="1182" alt="screen shot 2019-02-07 at 8 39 59 pm" src="https://user-images.githubusercontent.com/17481322/52454266-29625e00-2b19-11e9-8f80-4c365d79ea92.png">

Which is generated by this code:

<img width="900" alt="screen shot 2019-02-07 at 8 42 51 pm" src="https://user-images.githubusercontent.com/17481322/52454292-3d0dc480-2b19-11e9-8865-b7cbe6c55f7b.png">

However, if I wrap the component with `<></>`, the warning is no longer generated. Raw HTML tags also work fine. Are there restrictions as to what a child can be?

<img width="791" alt="screen shot 2019-02-07 at 8 46 25 pm" src="https://user-images.githubusercontent.com/17481322/52454354-780ff800-2b19-11e9-92cd-a3df4869179a.png">

**Comment by karelhala** [comment]
If you want to use components in cells you have to either wrap them in some `Fragement` or pass them as `title` prop in cells definition.
```JSX
cells: [
  { title: <div>Some component</div> }
]
```

**Comment by dlabrecq** [comment]
Ok. Is the title prop preferred over wrapping with `<></>`? 

Didn't realize `title` was used for that. There are no `arrayOf` props documented for table cells here: http://patternfly-react.surge.sh/patternfly-4/components/table

**Comment by rachael-phillips** [comment]
Hi @dlabrecq , with the requirement in mind that Insights only needs one expandable row does this block implementation?

**Comment by dlabrecq** [comment]
No, it's not blocking. It's more of a question about how to use the component now. Thinking more documentation would help?

**Comment by karelhala** [comment]
@dlabrecq sadly the prop docs does not support nesting attributes. Either way is fine, object with `title` allows you to add `props` for table cells as well. So I would say title is prefered way, but if you are already using Frgment that is fine as well.

**Comment by dlabrecq** [comment]
I understand, thanks for the explanation. 

We used an empty property for charts in order to link to Victory docs. Gatsby won't render the link, and it's an ugly workaround, but it's something. Will need to fix in order to import the TypeScript props.

![screen shot 2019-02-12 at 2 46 33 pm](https://user-images.githubusercontent.com/17481322/52663626-0c40dd00-2ed5-11e9-8266-fc4950779f4e.png)

**Comment by dlabrecq** [comment]
FYI, I attempted to use the title property. It renders fine, but encountering a type error in the browser console.

```
rows.push({
  cells: [
    {title: <div>{label}</div>},
    {title: <div>{monthOverMonth}</div>},
    {title: <div>{cost}</div>},
  ],
```

<img width="934" alt="screen shot 2019-02-12 at 10 25 05 pm" src="https://user-images.githubusercontent.com/17481322/52685004-264edf80-2f16-11e9-8096-c584c045152f.png">

**Comment by karelhala** [comment]
Which version are you using? Because there was a bug when mixing titles and strings but that was fixed in [@patternfly/react-table/v/1.0.1](https://www.npmjs.com/package/@patternfly/react-table/v/1.0.1)

**Comment by dlabrecq** [comment]
We're on v0.4.18. 

I just installed v1.0.7 and encountered this error.

![screen shot 2019-02-13 at 10 14 07 am](https://user-images.githubusercontent.com/17481322/52721719-46af8600-2f78-11e9-99a5-31f0f96e884d.png)

It works only if I remove the key from the div below. Is this expected?

```
cells: [
  {title: <div>{label}</div>}, // <<< no key
  <div key={`month-over-month-${index}`}>{monthOverMonth}</div>,
  <div key={`cost-${index}`}>{cost}</div>,
],
```

**Comment by karelhala** [comment]
I don't think that error is related to this. I can see in the error message `Object with keys {tiitle} was found` (notice double **i**). I tried it in live demo on http://patternfly-react.surge.sh/patternfly-4/components/table
```
cells: [{title: 'parenrt - 2', key: 'fgff' }, <div key="ff">'two'</div>, <div key="ff">'three'</div>, <div key="ff">'four'</div>, <div key="ff">'fivne'</div>],
```
And no error was present.

**Comment by dlabrecq** [comment]
I'll just omit the key attribute, then.

**Comment by iphands** [comment]
> I'll just omit the key attribute, then.

Wait if you misspelled the key name "title" as "tiitle" can you just fix that as Karel suggests instead of omitting things?

**Comment by tlabaj** [comment]
Closing this issue. I have opened issue #1473 to capture updating docs to make this use of the title prop more clear.

**Comment by tlabaj** [comment]
Closing this issue. I have opened issue #1473 to capture updating docs to make this use of the title prop more clear.
