### ISSUE TITLE
PF4 Dropdown: Missing borders

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1361]
Upgraded @patternfly/patternfly-core from v1.48.0 to v1.51.6 and the DropDown component no longer has borders.

Before (v1.48.0):
<img width="373" alt="screen shot 2019-02-08 at 11 16 32 pm" src="https://user-images.githubusercontent.com/17481322/52516384-14103100-2bf8-11e9-8493-b5e25803e4c3.png">

After (v1.51.6):
<img width="302" alt="screen shot 2019-02-08 at 11 20 43 pm" src="https://user-images.githubusercontent.com/17481322/52516392-491c8380-2bf8-11e9-884f-11a1d8812fae.png">

**Comment by ibolton336** [comment]
Looks like this only occurs when the dropdown is nested within another patternfly component. Looking into it...

**Comment by ibolton336** [comment]
![weirdbehaviorborder](https://user-images.githubusercontent.com/11218376/52969361-17d14f80-337e-11e9-81a2-37339fa96402.gif)

**Comment by ibolton336** [comment]
This issue is resolved by updating to the latest r[eact-core](https://www.npmjs.com/package/@patternfly/react-core) version
