### ISSUE TITLE
PF4 Tabs: Lacks support for tabs in header

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1364]
Per Kyle's high fidelity Insights mocks, we need to place the PF4 tabs inside the `header` tag of Cost Management for accessibility, while the main body is in another tag -- see image below.

At least one Insights app has implemented their own tabs in the header using HTML anchors. This isn't desirable because it doesn't have the same styling and behavior as the PF4 component.

The PatternFly core examples show the tab and tab children in different sections, which could be split into a `header` tag and main body because it's raw HTML. However, the PF4 tabs component won't allow me to do that because a Tab must be a child of the Tabs component.
https://pf4.patternfly.org/components/Tabs/examples/

We could probably style it to look like Kyle's mock, but child elements would also be contained within my `header` tag and/or PF4 header styles, which is not desirable.

That said, I want to do something more like the code below, where children can be defined separately (either by reference or by ID):

```
<section className="pf-l-page-header pf-c-page-header ...">
  <header className="pf-u-display-flex ...">
    <Title size={TitleSize.lg}>{t('overview.title')}</Title>
    <Tabs activeKey={this.state.activeTabKey} onSelect={this.handleTabClick}>
      <Tab eventKey={0} title="Tab item 1" tabChild={tabChild1}/>
      <Tab eventKey={1} title="Tab item 2" tabChild={tabChild2}/>
    </Tabs>
  </header>
</section>
<section className="pf-l-page__main-section pf-c-page__main-section">
  <TabChild id='tabChild1'><div>...</div></Tab>
  <TabChild id='tabChild2'><div>...</div></Tab>
</>
```

Kyle's mock: https://redhat.invisionapp.com/share/ENPJQTBXTAC#/screens/336412758
![screen shot 2019-02-11 at 11 13 34 am](https://user-images.githubusercontent.com/17481322/52576455-1805a400-2dee-11e9-814a-9d9bc43c005c.png)

**Comment by dgutride** [comment]
@rachael-phillips  - let's prioritize getting this adjustment made as product needs are impacted
