### ISSUE TITLE
Update PF4 Component Generator to use new  ccs files naming convention

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1365]
The generator still uses theold nameing convention '@patternfly/patternfly/components/<component_name>/styles.css'
It should use:
'@patternfly/patternfly/components/<ComponentName>/<componentName>.css'

The css file name starts with a lowercase letter.  Components with two words are separated by '-'  (e.g. Context Selector would be context-selector.css)

**Comment by dgutride** [comment]
@tlabaj  - is the react component generator still being used?
