### ISSUE TITLE
PF4 Table: Cannot read property 'title' of null

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1371]
It appears that the table generates a `Cannot read property 'title' of null` error if any cells are null or undefined.

Appears to be generated from this line of Body.js?
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-table/src/components/Table/Body.js#L51

@karelhala This may interest you? My work around was to ensure `item.label` is not null. Not sure how this is related to the property 'title', but was quite difficult to debug.

```
rows.push({
  cells: [
    item.label ? item.label : '', <<<<
    this.getMonthOverMonthCost(item, index),
    this.getTotalCost(item, index),
  ],
...
```

<img width="1144" alt="screen shot 2019-02-11 at 10 07 06 pm" src="https://user-images.githubusercontent.com/17481322/52609127-34cfc500-2e4a-11e9-9a42-3f056c46bd59.png">

**Comment by karelhala** [comment]
Thanks for bringing this is up yes, it is the same as trying to render null or undefined in React. However we should add warning message or something to notify consumer that they shouldn't send null/undefined to cell.

**Comment by dlabrecq** [comment]
Sounds good. Perhaps we could add a check to the `title: curr.title || curr,` line in Body.js?

**Comment by rachael-phillips** [comment]
Can we go ahead and close this one out?

**Comment by tlabaj** [comment]
Closing this issue.  I have opened issue #1473 to capture updating docs to make this use of the title prop more clear.

**Comment by dlabrecq** [comment]
I believe @karelhala suggested adding a warning message?
