### ISSUE TITLE
PF4 Table: Large expandable row margin

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1376]
I added expandable rows to my table. It appears that the expandable row reserves space on the left side, presumably for additional td tags containing toggles, check boxes, etc? As a result, it looks like there is a large margin on the left. 

In order to implement the designs created for Insights/Cost Management, I want to make use of that additional space in the expandable row. Currently, everything is shifted to the right.

![screen shot 2019-02-12 at 1 59 47 pm](https://user-images.githubusercontent.com/17481322/52660800-7a35d600-2ece-11e9-9d04-382222f03d68.png)

**Comment by karelhala** [comment]
This is deliberate and introduced in PF-core https://pf4.patternfly.org/components/Table/examples/

**Comment by dlabrecq** [comment]
I don't agree that this should be closed. The margins don't appear to match the core implementation. For example, the empty space on the left still appears to be larger than core, while right is minimal.

That said, I've opened an issue with core -- https://github.com/patternfly/patternfly-next/issues/1424. IMO, the `td` tag could span the entire row. We really could use the extra room for more items.

**Comment by dlabrecq** [comment]
The patternfly core team stated that the tds are optional and can be removed. 

Please do not close this issue and discuss with the core team.

**Comment by dlabrecq** [comment]
@dgutride Please keep this issue open until resolved.

**Comment by rachael-phillips** [comment]
@mcoker do you mind taking a look at this one?

**Comment by mcoker** [comment]
It looks like this was done in core.

<img width="909" alt="Screen Shot 2019-03-13 at 4 32 15 PM" src="https://user-images.githubusercontent.com/35148959/54316141-027ec800-45ae-11e9-96b7-e2fd44d7dd79.png">

 I was also able to modify the `colspan` on the [react table example](http://patternfly-react.surge.sh/patternfly-4/components/table) to replicate what's shown in the example in core.

<img width="1781" alt="Screen Shot 2019-03-13 at 4 36 04 PM" src="https://user-images.githubusercontent.com/35148959/54316220-30fca300-45ae-11e9-933c-54d404836696.png">
