### ISSUE TITLE
Table dropdown menu bug

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1390]
In the table examples, one of the dropdown options is rendering improperly.

<img width="810" alt="screen shot 2019-02-14 at 12 56 44 pm" src="https://user-images.githubusercontent.com/35148959/52811205-25bf6180-305a-11e9-896a-b88cb0672cf0.png">

**Comment by karelhala** [comment]
That was actually on purpose to show that anything can be part of this dropdown. Here it is `div` so consumers would have to write styles on their own.

**Comment by mcoker** [comment]
ah gotcha! The spacing and `class=" undefined"` made it look like a bug. feel free to close :)
