### ISSUE TITLE
ListView is misaligned if only some items have expander

### ISSUE THREAD

**Issue by martinpitt** [patternfly/patternfly-react#1392]
I have a case where some of my ListView items don't have expandable details:
```html
<ListView>
    <ListView.Item heading="no-details" description="desc 1" />
    <ListView.Item heading="with-details" description="desc 2">
        <ul>
            <li>Detail 1</li>
            <li>Detail 2</li>
        </ul>
    </ListView.Item>
</ListView>
```

This results in the list to be mis-aligned, both in wide and narrow modes:

![wide](https://user-images.githubusercontent.com/200109/52852638-7a75e180-3119-11e9-9df4-70ff7f188db9.png)
![narrow](https://user-images.githubusercontent.com/200109/52852641-7c3fa500-3119-11e9-8663-a90b85a671d1.png)

If at least one item has details, then the others should add some space (like an "invisible expander") at the start.

This is with PatternFly React 2.29.0, confirmed with latest 2.29.12.

@tlabaj for PR review

**Comment by martinpitt** [comment]
well, :man_shrugging: *bump* . Automatically adding "wontfix" feels a bit rude, TBH..

**Comment by kmcfaul** [comment]
@mcoker I am planning on adding a flag parameter to insert span to account for the difference in padding but `list-view-pf-expand` doesn't have the correct padding, and the angle-right and angle-down classes contain the icon. Is there a spacer css class in PF3 that can be used for this case?

**Comment by mcoker** [comment]
@kybaker is this a variation we want to support?

**Comment by kybaker** [comment]
@mcoker I like the flexibility this adds. Can we make sure the content is left aligned whether there is an arrow present or not?

**Comment by mcoker** [comment]
@kmcfaul @martinpitt I created an issue to add support (with examples) for this in core in our upcoming sprint - https://github.com/patternfly/patternfly-next/issues/2084

**Comment by mcoker** [comment]
@kmcfaul @martinpitt I apologize, I missed the PF3 label on this issue. The issue I created in the patternfly-next repo is for PF4.

@rachael-phillips can you comment on whether this is something we want to add to PF3 core?

**Comment by kmcfaul** [comment]
Hi @martinpitt. We are not taking on these couple PF3 ListView issues at this time, please contact @mcoker or @mcarrano if you have further questions.
