### ISSUE TITLE
ListInfo.InfoItems are not aligned if there are different actions

### ISSUE THREAD

**Issue by martinpitt** [patternfly/patternfly-react#1394]
`InfoItem` colums are misaligned if `ListView.Item`s have different actions:

```html
<ListView>
    <ListView.Item heading="one" additionalInfo={[
        <ListView.InfoItem key="snap">
            <span className="pficon pficon-restart" />
            1 GiB snapshot   
        </ListView.InfoItem>
    ]} />
    <ListView.Item heading="and another item" additionalInfo={[
        <ListView.InfoItem key="snap">
            <span className="pficon pficon-restart" />
            20 GiB snapshot  
        </ListView.InfoItem>
    ]} actions={[ <Button key="rollback">Roll Back</Button> ]} />
</ListView>
```

In narrow mode it looks ok, but in wide mode it's broken:

![info-action](https://user-images.githubusercontent.com/200109/52856615-34267f80-3125-11e9-860d-45c3f7acf617.png)

This is with PatternFly React 2.29.0, also tested with latest 2.29.12.

@tlabaj for PR review

**Comment by martinpitt** [comment]
Sorry, accidentally pressed enter. I added a proper description.

**Comment by martinpitt** [comment]
FYI, issues #1392, #1393, and this one  combined make a list with varying elements look really untidy:

![snapshots-wide](https://user-images.githubusercontent.com/200109/52856742-81a2ec80-3125-11e9-90de-382e482fe31a.png)

**Comment by martinpitt** [comment]
*bump*

**Comment by mcoker** [comment]
Hey @martinpitt, I noticed the same behavior in my product and wrote a local override to make it work with my product's UI. Maybe @kybaker or @mcarrano can speak to the original intent of this component more - is it expected that a list view with actions should have the same actions in each row to maintain proper alignment?

**Comment by rachael-phillips** [comment]
What are your thoughts here @kybaker and @mcarrano ?

**Comment by mcarrano** [comment]
List views are intended to allow for flexible presentation of data and actions unlike a table where it's expected that every row will contain a consistent set of items. So in looking at the screen shot above, I see nothing wrong with this except that as pointed out, the alignment is untidy because of the inconsistent content in rows.

@mcoker Is this just a matter of applying the right layout for row content? If the content placed in the center of the row were to left align, it would seem to fix this problem.

**Comment by kybaker** [comment]
@mcoker @mcarrano In the context of PF3 a 'data list' is really serving as a data table. In this case it makes sense that the content would be aligned properly like we would treat a data table in PF4.

**Comment by kmcfaul** [comment]
Hi @martinpitt. We are not taking on these couple PF3 ListView issues at this time, please contact @mcoker to discuss the workaround he has implemented.
