### ISSUE TITLE
PF4 React docs site nav scrolls to top when component is selected

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly-react#1395]
Example:
You're trying to compare `<Level>` and `<Split>` layouts
If you select the Level component, the navigation scrolls back to the top of the page. If you scroll down to the Split and click it, the navigation will go back to the top again.

It's a nitpick, but it would be great for the navigation to not scroll when a new component is selected.

**Comment by rachael-phillips** [comment]
To clarify this is in the PF4 React workspace: http://patternfly-react.surge.sh/patternfly-4/layouts/split

**Comment by dtaylor113** [comment]
Also further clarification that you would like the left-side panel which lists all the components not to scroll to the top after clicking on a component.

**Comment by ryelo** [comment]
@dtaylor113 Yes. That is correct. It's just a bit disorienting when scrolling to the bottom to flip between layouts and having to scroll down every time you switch.
