### ISSUE TITLE
PF4 Table - it's not possible to select a row when TableBody has onRowClick property

### ISSUE THREAD

**Issue by jiridostal** [patternfly/patternfly-react#1401]
It's not possible to tick a checkbox in PF4 Table when TableBody has onRowClick property. I'm enclosing a working example. https://codesandbox.io/s/pmvl2y2y70

**Comment by rachael-phillips** [comment]
@karelhala do you happen to know about this bug already?

**Comment by karelhala** [comment]
@rachael-phillips not yet, I can look into it and find why is this happening.

**Comment by jiridostal** [comment]
I've just bumped at the same issue when I was trying to include dropdown in the table row - same behavior

**Comment by karelhala** [comment]
I finally got time to fix this issue https://github.com/patternfly/patternfly-react/pull/1419

I wanted to prevent events on cells that include any selects or buttons, but then realised that some users might to have these events fired for these places. However if you want to prevent these events as well, you can check in your onRowClick method `event.target.querySelector('input').length === 0` and do not fire if any input is foudn.

**Comment by tlabaj** [comment]
@karelhala can I close this issue?

**Comment by karelhala** [comment]
@tlabaj yes, this issue can be closed. It's paritally resolved by linked PR and partially by usage. So no longer an issue.
