### ISSUE TITLE
Navs missing id

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#1427]
On http://patternfly-react.surge.sh/patternfly-4/components/nav only first nav has `id` attribute which is `nav-primary-simple`. Other navs don't have this attribute that makes hard to find them in the DOM for browser automation tests in https://github.com/quarckster/widgetastic.patternfly4/blob/master/testing/test_nav.py

**Comment by dtaylor113** [comment]
Hi @quarckster, happy to do this but just wanted to verify that you are running browser automation tests using the patternfly-react 4 Doc examples?

**Comment by quarckster** [comment]
@dtaylor113 Exactly https://github.com/quarckster/widgetastic.patternfly4/blob/master/testing/conftest.py#L37

**Comment by quarckster** [comment]
@dtaylor113 #1660 doesn't fix this issue. #1660 added ids to nav items of the first nav. Other navs still don't have id attribute. Only first one has it `<nav class="pf-c-nav" aria-label="Global" id="nav-primary-simple">`, I would like to see id attribute in other `nav` tags. This issue should be reopened.
