### ISSUE TITLE
Loading issues - dark "flash"

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-react#1429]
On initial load of an application, the components of the page load in slower than the background. This causes a dark "flash" on load. This is especially problematic for the Cloud Services Platform where the user switches from application to application, potentially getting the dark flash each time. 

If your page content is all React and you do a brand new Document load
(i.e. not a single page app view state change) then you will see the
HTML render before the React app is build. Hence a flash of the
background image then a quick transition to the React built dom.

We worked around it by laying down fake/placeholder HTML (no js) that
goes away or is replaced by the React dom elements.

cc @iphands and @ryelo [couldn't find Asa]

EDIT: also see this doc about how it was fixed in Cloud Services: https://docs.google.com/document/d/1jKH_3JuZqK4rUqv2FGx1-eMBYkoOdvqnPQGxZJJjkyQ/edit?usp=sharing

**Comment by ryelo** [comment]
cc: @kruai

**Comment by dgutride** [comment]
I would say this is an application issue and not a component issue since the application manages initial dom load - moving to closed unless somebody has an indicator that this can be fixed per component.
