### ISSUE TITLE
PF4 Table: Disable header controls when no rows are available

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1431]
The Cost Management UI needs to provide an empty state in a table, per Kyle's high fidelity mock below. For example, if the applied filter results in no data. However, when there are no rows available, the select all checkbox is selected and sorting is still enabled. 

Clicking on these controls has no effect, but it's confusing to users.

<img width="1254" alt="screen shot 2019-02-22 at 3 11 12 pm" src="https://user-images.githubusercontent.com/17481322/53269148-1f626280-36b6-11e9-82c2-ecf0b8cbcd7f.png">

Can the select all and sorting be disabled by default?

Kyle's Mock:
<img width="1501" alt="screen shot 2019-02-22 at 2 58 34 pm" src="https://user-images.githubusercontent.com/17481322/53267880-867e1800-36b2-11e9-9ede-49b254a61358.png">

**Comment by rachael-phillips** [comment]
@dlabrecq thanks for bringing this to our attention. how high priority is this issue for the team? Can you provide any timeline information about when you will need this? Is this blocking implementation?

**Comment by dlabrecq** [comment]
It's not blocking us. However, it is a usability issue.

**Comment by rachael-phillips** [comment]
Keeping the above conversation in mind, @tlabaj would you mind setting a priority that seems feasible for the team on this issue?

**Comment by dlabrecq** [comment]
This is still a usability issue for Cost Management

**Comment by dlabrecq** [comment]
This is still a usability issue for Cost Management
