### ISSUE TITLE
Broken PF4 chart examples

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1435]
With the exception of the donut and pie chart, all other PF4 chart examples are broken. 

It appears that the examples were reformatted recently. Doesn't seem to match the example / linter formatting for core, so I have to question if all those changes were necessarily? 

The repo appears to run locally, but it might be a good idea to manually view the live examples after making such large, sweeping changes to the entire chart package? Something is obviously broken here.

Stack Chart:
http://patternfly-react.surge.sh/patternfly-4/components/stackchart

<img width="1691" alt="screen shot 2019-02-24 at 1 47 04 pm" src="https://user-images.githubusercontent.com/17481322/53303649-177ffb00-383b-11e9-9f51-8d8eb0f93221.png">

Line Chart:
http://patternfly-react.surge.sh/patternfly-4/components/linechart

<img width="1300" alt="screen shot 2019-02-24 at 1 48 20 pm" src="https://user-images.githubusercontent.com/17481322/53303646-0df69300-383b-11e9-9d54-847ebc85fbfe.png">

Bar Chart:
http://patternfly-react.surge.sh/patternfly-4/components/barchart

<img width="1183" alt="screen shot 2019-02-24 at 1 51 34 pm" src="https://user-images.githubusercontent.com/17481322/53303665-5b730000-383b-11e9-8fd1-9422e214fd13.png">

Area Chart:
http://patternfly-react.surge.sh/patternfly-4/components/areachart

<img width="854" alt="screen shot 2019-02-24 at 1 51 28 pm" src="https://user-images.githubusercontent.com/17481322/53303667-662d9500-383b-11e9-8576-0b7f57a42cac.png">

**Comment by redallen** [comment]
It's unlikely a linting issue from #1409 because it isn't reproducible running a local webserver (or even after building and manually uploading to Surge). It may be a Travis caching issue, which I'm investigating [now.](https://travis-ci.org/patternfly/patternfly-react/builds/498204784)

**Comment by redallen** [comment]
It's confirmed a [Travis issue](http://patternfly-react-chart-test.surge.sh/patternfly-4/components/stackchart). I'm manually uploading a good http://patternfly-react.surge.sh until I get a fix in.
