### ISSUE TITLE
PF4 Table alignment issue

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1438]
The Cost Managementtable has columns with multiple lines. I believe the table is vertically centering text. As a result, lines appear to be misaligned. Ideally, everything would be aligned at the top by default.

If this is a PF4 next issue, please leave this issue for tracking purposes.

![screen shot 2019-02-25 at 9 22 54 am](https://user-images.githubusercontent.com/17481322/53343851-510a4200-38df-11e9-9f97-4aac3ec722cd.png)

**Comment by dlabrecq** [comment]
My workaround is to override table styles like so:

export const tableOverride = css`
  &.pf-c-table {
    thead th + th {
      .pf-c-button {
        text-align: right;
      }
      text-align: right;
    }
    tbody td + td + td + td {
      text-align: right;
    }
    td {
      vertical-align: top; <<< Aligns text at top
    }
  }
`;

**Comment by tlabaj** [comment]
@mcoker Can you please take a look at this and determine in a change is needed in core.

**Comment by mcoker** [comment]
Yep this will need a change in core. Looks like @christiemolloy is working on a related issue, so we can bundle this fix in that PR - https://github.com/patternfly/patternfly-next/pull/1472

**Comment by mcoker** [comment]
#1472 was merged, so this should be fixed in 1.0.225

**Comment by rachael-phillips** [comment]
Hi @mcoker is this a free change by just upgrading or is there anything else we need to do on the React side?

**Comment by mcoker** [comment]
@rachael-phillips totally free, should be fixed when upgrading the version of core.

**Comment by rachael-phillips** [comment]
That's awesome - thanks!

**Comment by rachael-phillips** [comment]
Closing as this is resolved #1587
