### ISSUE TITLE
Alert - confusing alert types

### ISSUE THREAD

**Issue by sharvit** [patternfly/patternfly-react#144]
The `Alert` component should receive a `type` prop with one of the values `['danger', 'error', 'warning', 'success',  'info']`

`danger` and `error` giving the same result and they are identical.

https://github.com/patternfly/patternfly-react/blob/master/src/components/Alert/constants.js#L1-L2
https://github.com/patternfly/patternfly-react/blob/master/src/components/Alert/Alert.js#L41
https://github.com/patternfly/patternfly-react/blob/master/src/components/Alert/helpers.js

* Does it exist for backward compatibility?
* Is one of them deprecated?
* In the storybook I can find only the `danger` type.
  Does it mean I should only use the `danger` type?
  * https://github.com/patternfly/patternfly-react/blob/master/src/components/Alert/Alert.stories.js

Thanks!

**Comment by sharvit** [comment]
Same for `ToastNotification`
https://github.com/patternfly/patternfly-react/blob/master/src/components/ToastNotification/constants.js#L2-L3

**Comment by priley86** [comment]
I believe this was just a conveniency established back in the commit here:
https://github.com/patternfly/patternfly-react/commit/ce337fdf7a7b077d45924938844e49fc1d45eba5#diff-70839dc751b9f23f82319d0fbbd0aca4

I'm fine with either/or (as i agree that having both is causing confusion). It looks like angular-pf uses `danger` type though.

**Comment by sharvit** [comment]
@priley86 my main concern is to end up using both of them in my source code.
This is why I thought about blocking `danger` type in my source code.
Or would you prefer to remove one of them from `patternfly-react` itslef?

I would be fine with both options and can make the pr soon to speed it up.

**Comment by jeff-phillips-18** [comment]
This goes back to patternfly having both. Two different names that resolve to the same look.

I think the thought was at some point there may be a need to distinguish the two, but its never happened.  There is a PF class `alert-danger` which is used which I believe causes the confusion, there is no `alert-error` though `error` is more commonly used for status.

So, yes this is a backward compatibility thing.  I'm not sure if I feel that it should be removed or not.

**Comment by sharvit** [comment]
@jeff-phillips-18 since we deliver features in react as props and not as classes I feel good about delivering danger class with prop `type=error`.

I don't see a reason to support both of them and i think better to deprecate on of them now before we will start to see mixed usage everywhere.
