### ISSUE TITLE
TS errors when importing latest @patternfly/react-core

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#1443]
When importing latest `@patternfly/react-core` I get the following errors out of the box. I'm using typescript `3.1.6`. 

```sh
ERROR in [at-loader] ../../node_modules/@patternfly/react-core/dist/js/components/Select/Select.d.ts:3:30 
    TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.

ERROR in [at-loader] ../../node_modules/@patternfly/react-core/dist/js/components/Select/SelectOption.d.ts:4:18 
    TS2430: Interface 'SelectOptionProps' incorrectly extends interface 'Pick<HTMLProps<HTMLOptionElement>, "start" | "hidden" | "color" | "content" | "size" | "style" | "default" | "wrap" | "open" | "multiple" | "ref" | "children" | "list" | "step" | ... 342 more ... | undefined>'.
  Types of property 'onClick' are incompatible.
    Type 'Function | undefined' is not assignable to type '((event: MouseEvent<HTMLOptionElement>) => void) | undefined'.
      Type 'Function' is not assignable to type '(event: MouseEvent<HTMLOptionElement>) => void'.
        Type 'Function' provides no match for the signature '(event: MouseEvent<HTMLOptionElement>): void'.
```

<img width="1138" alt="screen shot 2019-02-25 at 7 26 54 pm" src="https://user-images.githubusercontent.com/5942899/53378612-344c2980-3934-11e9-92de-328393dcfcb5.png">

**Comment by seanforyou23** [comment]
Looks like I had some weird caching issues going on, after rebuilding the world this seems to have gone away. I think it's safe to close, will reopen if it comes back up.

**Comment by priley86** [comment]
I'm seeing the same issue. Typescript `2.9.2`. Tsconfig:
https://github.com/openshift/console/blob/master/frontend/tsconfig.json

This could be typescript version or tsconfig, but would like to revisit and check this again.
