### ISSUE TITLE
PF4 Tabs: allow eventKey to accept a string

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1446]
As a user, I want to use a string as my tab `eventKey`. Would it be possible to change the `eventKey` type to accept a number or string?

In the Cost Management UI, we iterate over a map of available tabs. We dynamically show/hide tabs, so we identify child components using an ID string; 'aws', 'openshift', etc. 

As a workaround, I've added code to look up IDs based on the `activeTabKey`. However, it would be ideal if we could just provide the tab eventKey with a string instead. This was how our custom tabs component worked.

Below is an example of how we add tabs dynamically.

![screen shot 2019-02-26 at 9 14 09 am](https://user-images.githubusercontent.com/17481322/53418967-e8869800-39a6-11e9-9345-ca57950c28b1.png)

**Comment by dlabrecq** [comment]
It would still be ideal to accept a string or number. I believe this is just a matter of changing the prop type

**Comment by tlabaj** [comment]
closed by #2493
