### ISSUE TITLE
circleci fails intermittently

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#1449]
I noticed circleci failed 2 of 3 times for me in https://github.com/patternfly/patternfly-react/pull/1445

Building PF4 Docs seems to be the problematic step. It produces an error like the following:

<img width="1009" alt="screen shot 2019-02-25 at 10 14 29 pm" src="https://user-images.githubusercontent.com/5942899/53421520-c8a5a300-39ab-11e9-9c64-b1ee2170e2dc.png">

@redallen FYI

**Comment by redallen** [comment]
Yep, CircleCI fails a good deal of the time on building PF4 docs with Terser errors or 10-minute timeouts. It doesn't matter for merging PRs since it only deploys the previews. It should be replaced (Netlify, or other CI provider, and we need to remove the Github checks on PRs at the very least.

**Comment by redallen** [comment]
Closed by #1517 and #1527
