### ISSUE TITLE
ToastNotificationList - supplying a className will override pf className

### ISSUE THREAD

**Issue by sharvit** [patternfly/patternfly-react#145]
Hi,

* In the `ToastNotificationList`, one of the prop i can pass is `className`.
* `ToastNotificationList` should use the patternfly className `toast-notifications-list-pf`.
* If i pass my own `className` it will override the default className `toast-notifications-list-pf`.

https://github.com/patternfly/patternfly-react/blob/master/src/components/ToastNotification/ToastNotificationList.js#L67

* Is this the behavior we want?
* Shouldn't it use `toast-notifications-list-pf` as `className` together with the `className` i am passing as a prop?
  * I guess so, because the description of this field is `additional alert classes`.

**Comment by jeff-phillips-18** [comment]
Agreed, the 'toast-notifications-list-pf' class should always be added and any additional classes added to it.

**Comment by priley86** [comment]
I'm fine with this modification @sharvit. No issue making `toast-notifications-list-pf` the default.

**Comment by sharvit** [comment]
Closed, this issue fixed thanks to @jeff-phillips-18 https://github.com/patternfly/patternfly-react/pull/163
