### ISSUE TITLE
PF4 Tabs: scroll button

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1451]
Why is there a scroll button associated with the PF4 tabs? Odly, this does not appear on Chrome, only with Firefox. How do we get rid of it?

![screen shot 2019-02-26 at 11 25 42 am](https://user-images.githubusercontent.com/17481322/53428794-6eabda00-39b9-11e9-85c9-b8b3792321a7.png)

**Comment by rachael-phillips** [comment]
Hi @dlabrecq we don't see this issue on our side. Do you mind telling us how to reproduce it?

**Comment by dlabrecq** [comment]
All I can say is that it shows up on Firefox, not Chrome. And it's still present with the latest prerelease packages.

**Comment by dlabaj** [comment]
@dlabrecq Do you have a link to the file that has this issue?

**Comment by dlabrecq** [comment]
Tested with Firefox v65.0.1 (64-bit) and 66.0 (64-bit).

Note that this is now happening in multiple places:
![Screen Shot 2019-03-19 at 12 59 55 PM](https://user-images.githubusercontent.com/17481322/54626619-e6fd3c80-4a47-11e9-8d60-179328216907.png)

We're using tabs in a few places; for example:

Overview tabs:
https://github.com/project-koku/koku-ui/blob/master/src/pages/overview/overview.tsx#L120

Card tabs:
https://github.com/project-koku/koku-ui/blob/master/src/pages/ocpOnAwsDashboard/ocpOnAwsDashboardWidget.tsx#L295

**Comment by TheRealJon** [comment]
The `Tabs` component uses the `isElementInView` util function to establish whether the first and last `Tab` element in the `TabList` are fully visible. Firefox (and Safari) calculated these `Tab` elements' `clientWidth` to be slightly larger than Chrome did, causing this function to return `false` for the last tab (i.e. the last tab was incorrectly considered partially out of view on the right side). The `showRightScrollButton` state of the `Tabs` component is set to the inverse of that function's return value, thus causing the right scroll button to appear in those browsers.
