### ISSUE TITLE
Support for UMD followup issue

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#1452]
In #1142 - we added UMD modules for `@patternfly/react-core`, but it appears that to fully support UMD, we may also need to compile UMD modules for `@patternfly/react-styles`, `@patternfly/react-icons`, and `@patternfly/react-tokens`. We should be able to take a similar approach there if desired. Just opening this issue to confirm first...

cc: @ssilvert

**Comment by rachael-phillips** [comment]
Hi @dgutride do we need to get this done before the release?
