### ISSUE TITLE
QE - add root identifier to the page component to help with automated tests

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#1459]
@quarckster can add more info - but the page component is generally a root component for many pages in PF4.  We'd like to have a root attribute added so automated tests can easily pick up where they are.

**Comment by rachael-phillips** [comment]
Hi @dgutride! How high priority is this issue?

**Comment by dtaylor113** [comment]
@dgutride, can you please elaborate on what needs to be done?  -thanks

**Comment by redallen** [comment]
Closing in favor of #2303.
