### ISSUE TITLE
`.pf-c-dropdown__menu-item:hover` `color` within `.pf-c-page__headercolor` is white, which has very low contrast/readability

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#1461]
![screen shot 2019-02-27 at 1 56 50 pm](https://user-images.githubusercontent.com/895728/53515627-755d4e80-3a98-11e9-8ff3-04cd8aa36c9c.png)

Screenshot taken from http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-expandable-nav

cc:  @spadgett, @janwright73

**Comment by rachael-phillips** [comment]
Hi @rhamilto this was fixed in core, and we're no longer seeing the issue here: http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-default-nav
