### ISSUE TITLE
Table - column configs should have optional typescript types

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#1463]
I noted while reviewing [Facet](https://github.com/metalkube/facet) that column configs should be optionally defined when passing transforms, cellTransforms, formatters, and cellFormatters.

https://github.com/metalkube/facet/blob/master/src/components/HostsTable.tsx#L25

**Comment by janwright73** [comment]
@jtomasek - making sure that you are notified that we opened this issue from your findings.

**Comment by jcaianirh** [comment]
@jtomasek opened: https://github.com/patternfly/patternfly-react/issues/1662 so you can get a fix for the transrom type-o as well.
