### ISSUE TITLE
Update Documentation for for using 'title' prop in table cells.

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1473]
The documentation is not clear on how to use the title prop in a cell.  Please see issue #1351 for more details.

**Comment by dtaylor113** [comment]
Hi @tlabaj, so should I update the `row` documentation to something like:

Table Props
The Table component accepts the following props.

Name | Type | Required | Default | Description
-- | -- | -- | -- | --
rows | arrayOf |  !  |   | Actual rows to display in table. Either array of strings or row ojects. (new -->) If you want to use components in row cells you can pass them as `title` prop in cells definition. Ex: rows: [{cells: [{title: `<div>Some component</div>`}]...]

Thanks,
- Dave

**Comment by tlabaj** [comment]
@dtaylor113 That looks good to me.  @dlabrecq what do you think?

**Comment by dtaylor113** [comment]
I'll try to add some better formatting, but just wanted to make sure the text was correct.
