### ISSUE TITLE
Add support for groups in dropdowns

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1485]
https://github.com/patternfly/patternfly-next/pull/1444

https://pf4.patternfly.org/components/Dropdown/examples/

> .pf-c-dropdown__group | `<section>` | Defines a group of items in a dropdown. Required when there is more than one group in a dropdown

> .pf-c-dropdown__group-title | `<h1>` | Defines the title for a group of items in the dropdown menu

`section.pf-c-dropdown__group` should wrap all groups of items if there is at least 2 groups in the dropdown menu.

A person can change the `<h1>` to another level heading, but it's worth noting it's OK to use an `<h1>` there anywhere in the page since it's in a `<section>`, which allows for it's own heading hierarchy.

**Comment by rachael-phillips** [comment]
Hi @mcoker is this needed for Summit? If not, we may make this lower priority.

**Comment by mcoker** [comment]
@rachael-phillips I don't believe anyone asked for it. It was a result of talking to @mcarrano as to how to add groups of items to a dropdown when other dropdowns collapse into a single dropdown. AFAIK it can wait.

**Comment by rachael-phillips** [comment]
Thank you so much for the update :)

**Comment by mcarrano** [comment]
What I will say about this is that if we don't do it, this leaves us exposed as to how we collapse utility items into the kabob when the viewport shrinks to Mobile. Do you agree @mcoker ?  So I feel like this is less of a new feature request and more like correcting for a design oversight/bug.

**Comment by mcoker** [comment]
Yep, agree with that statement completely.

**Comment by rachael-phillips** [comment]
Hi @kmcfaul can we close this issue?
