### ISSUE TITLE
Typeahead warnings after version update

### ISSUE THREAD

**Issue by Laviro** [patternfly/patternfly-react#1491]
Getting unexpected console warnings after the library has been updated.
opened an issue to `react-bootstrap-typeahead`: [issue](https://github.com/ericgio/react-bootstrap-typeahead/issues/428)

**Comment by Laviro** [comment]
cc @mturley

**Comment by mturley** [comment]
Nice, good catch! Looks like they did a `v3.4.1` release just for you :)
