### ISSUE TITLE
Chip - default attributes are unset

### ISSUE THREAD

**Issue by gastaldi** [patternfly/patternfly-react#1506]
In order to use the Chip component, I am required to set all the properties below, otherwise I get a compilation error. I am using TypeScript. 

```xml
<Chip key={c.id} closeBtnAriaLabel="none" isOverflowChip={false} isBadge={false} tooltipPosition="top">
```

**Comment by rachael-phillips** [comment]
We can go ahead and close this issue: referencing #1560
