### ISSUE TITLE
Chip - allow chip to be read-only

### ISSUE THREAD

**Issue by gastaldi** [patternfly/patternfly-react#1507]
When setting the Chip as `readOnly`, that would remove the `X` next to it but keeping the same height

**Comment by rachael-phillips** [comment]
@gastaldi do you mind providing us a little more context on what you'd like to achieve? @mcoker making you aware.

**Comment by gastaldi** [comment]
@rachael-phillips sure, for example, in the first Chip Group Toolbar
example in  http://patternfly-react.surge.sh/patternfly-4/components/chipgroup,  I'd like to avoid `Chip 1` to be removed, but others may be removed (as if Chip 1 were a required chip). 

Therefore having the ability to mark a specific chip as `readOnly` would be really helpful

**Comment by mcoker** [comment]
@rachael-phillips we should ask design if there should be any other visual indicators that the chip is read-only/non-removable, or if it's simply removing the button but keeping the existing overall layout, and then add an issue in core to add this variation.

**Comment by mceledonia** [comment]
I think simply removing the icon button should be fine for this. If we start getting a lot of feedback that people aren't understanding why they can't remove the chip, we can reconsider.

**Comment by rachael-phillips** [comment]
Ok great! Thanks everyone!

**Comment by rachael-phillips** [comment]
I added the on hold label so that we can resolve this in our Core repo first (1533 Create read-only variation of chip). Then we will move it onto React. Thanks everyone!

**Comment by mcoker** [comment]
@rachael-phillips this is in core now and ready to be added to react - https://github.com/patternfly/patternfly-next/pull/1555

**Comment by tlabaj** [comment]
Closed by #1639
