### ISSUE TITLE
PF4 Table: Table checkboxes not vertically centered

### ISSUE THREAD

**Issue by jiridostal** [patternfly/patternfly-react#1509]
Example is worth a thousand words - https://codesandbox.io/s/p1np02j4q

**Comment by rachael-phillips** [comment]
Hi @jiridostal do you mind adding an example with the table checkboxes? We just see the buttons right now.

**Comment by jiridostal** [comment]
I have no idea what happened to my example. I've updated the link.

**Comment by mcoker** [comment]
@jiridostal this should be fixed in https://github.com/patternfly/patternfly-next/pull/1472/

**Comment by rachael-phillips** [comment]
@mcoker are there any further changes we should make in React for this?

**Comment by mcoker** [comment]
@rachael-phillips nope, it's just a CSS change. Pulling in that version of core will fix it.

**Comment by rachael-phillips** [comment]
Thank you so much @mcoker! Closing as this should be fixed now
