### ISSUE TITLE
Unable to reach patterns demo page

### ISSUE THREAD

**Issue by mrMaize** [patternfly/patternfly-react#1516]
My project development has got stuck because I cannot open patterns demo page. Please fix it asap.
Cannot reach - http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/

**Comment by jeff-phillips-18** [comment]
I am able to reach the above with no problems

**Comment by boaz0** [comment]
Hi @mrMaize,

I am too able to reach the above.

Can you describe the steps you did?
Maybe there was a small outage and now the demo page is available.

At any rate, let us know.

**Comment by mrMaize** [comment]
Hi @boaz0 @jeff-phillips-18,

I figured out why I couldn't reach it and the answer is a little insane. 
I managed to get access to demo page via a VPN only. I am from Russia by the way. Now it works just fine. 

Thanks for quick responses.
