### ISSUE TITLE
Turn off close icon on expanded ListViewItem

### ISSUE THREAD

**Issue by danseethaler** [patternfly/patternfly-react#153]
I'd like to be able to disable the close icon when a `ListViewItem` is expanded to show it's `children`.

In our use case the close icon pushes the first child out of alignment. See below
![image](https://user-images.githubusercontent.com/11202705/34619707-0ca7e858-f211-11e7-8dd6-1f35c7a236cb.png)

I would also assume that most people would collapse the children by clicking on the dropdown header instead of looking for the x in the corner. Are there use cases when the `ListViewGroupItemContainer` does not have a parent dropdown capable of collapsing it? If not maybe we could remove the close x entirely.

At a minimum I'd like to be able to pass a prop to the `ListViewItem` [here](https://github.com/patternfly/patternfly-react/blob/master/src/components/ListView/ListViewItem.js#L64) that would essentially turn off the `onClose` prop passed to `ListViewGroupItemContainer`.

**Comment by jeff-phillips-18** [comment]
Ideally, the close button should have no impact on the contents.

**Comment by danseethaler** [comment]
Anyone know if this issue is evident in patternfly itself?

**Comment by jeff-phillips-18** [comment]
I believe it is. Looking at http://www.patternfly.org/pattern-library/content-views/list-view/#/code you can see the close button is overlaid on top of the expanded content.

**Comment by jtomasek** [comment]
The close button is floated right, so any block content will stack under it (as visible at [1]), any floated content will get pushed by it. We can allow to not include it in react component unless it is always required from the UX point of view / patternfly guidelines.

[1] http://www.patternfly.org/pattern-library/content-views/list-view/#/code

**Comment by jgiardino** [comment]
@mcarrano Can you weigh in on this issue?

These are the only possible options I can think of for addressing the use case where the expanded contents occupy the full width:
1. Make the X optional
2. Include extra margin/padding on the right to prevent overlap or pushing of contents
3. Include extra margin/padding on the top to prevent overlap or pushing of contents

And for options 2 and 3, would this margin be optional based on the contents? I would think some contents are totally fine wrapping.

**Comment by mcarrano** [comment]
Yes, I do see the problem. In our earlier mockups, the expansion was more intended as a way to show details of an object in the list, but agree that the Close button does not really work if we are embedding something like a list that takes up the full width of the container.

My recommendation is that we consider the Close (X) button optional.  I can send a PR to update the design documentation to this effect with a note that this not be used if content will span the full width of the expansion panel. What do you think @jgiardino ?

**Comment by jgiardino** [comment]
Thanks, @mcarrano! I agree with making the Close button optional.

**Comment by danseethaler** [comment]
Great thanks everyone! I'll submit a PR to make this happen.
