### ISSUE TITLE
pf-c-backdrop__open class stays on <body> even after 'Modal' removal

### ISSUE THREAD

**Issue by ia3andy** [patternfly/patternfly-react#1531]
This prevent user from scrolling after the `<Modal ..>` has been removed from the screen.

![image](https://user-images.githubusercontent.com/2223984/54043461-ebfef800-41cc-11e9-9edb-019ac1eef798.png)

It seems the class need to be removed: `document.body.classList.remove(css(styles.backdropOpen));`
- when the `isOpen` switch to `false`  
- **and also** when the `componentWillUnmount`

https://github.com/patternfly/patternfly-react/blob/4778a2827ea115b9e1b05683d03a26a26cdb63da/packages/patternfly-4/react-core/src/components/Modal/Modal.js#L92

**Comment by ia3andy** [comment]
Up..

This is really a big bug! Scrolling is not working anymore after opening a Modal..

**Comment by rachael-phillips** [comment]
Hi @ia3andy a few quick questions:
* What product/project does this impact?
* Is this blocking implementation?

**Comment by ia3andy** [comment]
Hi @rachael-phillips.

> What product/project does this impact?

The Launcher for OpenShift https://github.com/fabric8-launcher/launcher-frontend

> Is this blocking implementation?

It's a really serious bug for our application.

I could provide a PR if you wish.

**Comment by rachael-phillips** [comment]
Hi @ia3andy thank you for the information and for offering to put up the PR. I'll take you up on the offer to provide a PR! Thank you so much - greatly appreciated!

**Comment by ia3andy** [comment]
Hi @rachael-phillips, I just provided a PR https://github.com/patternfly/patternfly-react/pull/1563 ;-)
