### ISSUE TITLE
PF4 Switch adds an unwanted prefix "on|off" to the label

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#1546]
When I use the following Switch component:
```javascript
const Test = () => {
  const [isChecked, setIsChecked] = React.useState(false);
  return (
    <Switch
      id="id"
      label="Use custom address"
      isChecked={isChecked}
      onChange={() => setIsChecked(!isChecked)}
      aria-label="aria-label"
    />
  );
};
```
I get the label `OffUse custom address` or `OnUse custom address`.

**Comment by rachael-phillips** [comment]
We are aware of this issue and are working on this on the Core side before moving into React.

**Comment by rebeccaalpert** [comment]
This should be fixed by https://github.com/patternfly/patternfly-react/pull/1591.
