### ISSUE TITLE
PF4 interface NavItemProps lacks a property preventDefault

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#1547]
In the component NavItem there is a property `preventDefault` whilst in `preventDefault` (file `./NavItem.d.ts`) it isn't. 

So a checker reports `Property 'preventDefault' does not exist on type 'IntrinsicAttributes & NavItemProps & { children?: ReactNode; }'.`

**Comment by idevat** [comment]
...whilst in `NavItemProps` (file `./NavItem.d.ts`) it isn't... Sorry for the wrong name.

**Comment by priley86** [comment]
`@types/react` currently defines `onClick for `DOMAttributes` as 
```
onClick?: MouseEventHandler<T>;
```
MouseEventHandler is of type `EventHandler`:
```
type MouseEventHandler<T = Element> = EventHandler<MouseEvent<T>>;
```
which extends `SyntheticEvent`:
```
type EventHandler<E extends SyntheticEvent<any>> = { bivarianceHack(event: E): void }["bivarianceHack"];
```

SyntheticEvent already defines `preventDefault`:
```
    interface SyntheticEvent<T = Element> {
        bubbles: boolean;
        /**
         * A reference to the element on which the event listener is registered.
         */
        currentTarget: EventTarget & T;
        cancelable: boolean;
        defaultPrevented: boolean;
        eventPhase: number;
        isTrusted: boolean;
        nativeEvent: Event;
        preventDefault(): void;
```

Thus I do not think we need to redefine it. Please ensure you are loading a recent version of `@types/react` in your project.
