### ISSUE TITLE
Charts - provide a way to extract data

### ISSUE THREAD

**Issue by dchorvat1** [patternfly/patternfly-react#1549]
In current state, we can't extract data from chart elements since they're not stored in them, we'd need some way to reach the data that gets displayed on mouseover in the charts for test automation purposes.

//cc @karelhala

**Comment by rachael-phillips** [comment]
Hi @dchorvat1 a couple of quick questions:

What product/project does this impact?
Is this blocking implementation?

**Comment by dchorvat1** [comment]
Hi @rachael-phillips, it impacts quality engineering for Insights. It is not blocking implementation itself, but it would be a good feature to have for automated UI tests.

**Comment by rachael-phillips** [comment]
Ok thank you for letting me know. @dlabrecq is this something we have discussed with charts at all?

**Comment by dlabrecq** [comment]
The charts generate SVG images, so there really isn't anything to extract like a data table. PatternFly simply wraps the Victory chart library.

The tooltips displayed on 'mouseover' are generated by a function provided by the UI. The chart simply calls that function to display the data on hover. The chart provides the x/y data point, but the UI function formats the string displayed in the tooltip.

Considering the UI has the data used to generate the SVG, the UI could make the tooltip function available for testing?

FYI, the Cost Management UI uses snapshots in its unit testing. We're able to interact with Victory objects directly via the PatternFly wrappers (e.g., Chart = VictoryChart, ChartTooltip = VictoryTooltip, etc.).

You can find the API docs here: https://formidable.com/open-source/victory/docs/

**Comment by rachael-phillips** [comment]
Thanks so much for all of the information, @dlabrecq!

**Comment by rachael-phillips** [comment]
@dchorvat1 did @dlabrecq give you enough information for what you're trying to accomplish?

**Comment by dchorvat1** [comment]
@rachael-phillips yes, it seems more clear now

**Comment by karelhala** [comment]
Btw it would be realy good if we provide data that were used to generate charts trough `data-raw=JSON`. QE could then check if data used to generate the chart were correct or not. This is especially usefull if consumers are changing data in their component.

**Comment by dlabrecq** [comment]
Similar to the argument of not supporting `offset` for pagination, that would add a great deal of complexity.

**Comment by rachael-phillips** [comment]
If there's any outstanding issue please let me know, and we can reopen this
