### ISSUE TITLE
PF4 expandable compact table missing styling

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly-react#1552]
Example: https://react-pf-playground.stackblitz.io/

Screenshot:

![Screen Shot 2019-03-12 at 9 22 52 AM](https://user-images.githubusercontent.com/12520842/54203308-6f0f9f00-44a8-11e9-81ca-b6be11402408.png)

If you use the compact table with the expandable rows, the blue line is missing from the left side.

Not sure if this is intentional or not, but our mockups have the blue line

**Comment by rachael-phillips** [comment]
Hi @ryelo can you list any product/project release(s) and timelines your trying to align with, and is this currently blocking documentation?

**Comment by AllenBW** [comment]
Timeline, as soon as possible? (before summit?) Would make our table a lil prettier (insights rule table)
<img width="1296" alt="Screen Shot 2019-03-12 at 9 36 52 AM" src="https://user-images.githubusercontent.com/6640236/54204346-70da6200-44aa-11e9-9a45-74aebe70a1f3.png">

**Comment by rachael-phillips** [comment]
Ok, thank you for letting me know!

**Comment by ryelo** [comment]
@rachael-phillips This is affecting nearly all of the apps inside of Cloud Services, preferable asap. We're trying to harden and get as close to mockups as possible, but this is creating readability issues for larger expandable items.

**Comment by rachael-phillips** [comment]
Thank you for the explanation. I've placed the highest priority label on this issue.

**Comment by rachael-phillips** [comment]
@mcoker can you advise on this one? Is this an implementation bug or something we would need to update in Core?

**Comment by mcoker** [comment]
@rachael-phillips I chatted with @mceledonia and will make an update in core.

**Comment by mcoker** [comment]
@ryelo here's the PR in core - https://github.com/patternfly/patternfly-next/pull/1563

Once it's merged, we'll just need to bump the version of core in patternfly-react.

**Comment by dlabaj** [comment]
Added breaking change label due to it being a breaking change in core.

**Comment by LHinson** [comment]
Removing the "on hold" tag since the core PR has been merged

**Comment by dlabaj** [comment]
Fixed in 3.x release.
