### ISSUE TITLE
Need dev/build environment support for Windows

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#1557]
Need to be able to continuously build the project in a Windows environment to ensure contributors on Windows can work on PatternFly.
Closing #478 in favor of this issue.

Previous work that had gone into Windows support:
#1248
#1251
#1255

**Comment by dgutride** [comment]
@redallen  - is this still an issue after all the changes you made?

**Comment by redallen** [comment]
Closed from #2471.
