### ISSUE TITLE
PF4 ModalBoxHeader: prop type `hideTitle` is invalid

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1561]
Discovered this Type error with @patternfly/react-core v2.5.2.

![Screen Shot 2019-03-12 at 4 25 30 PM](https://user-images.githubusercontent.com/17481322/54233557-8fa91a80-44e3-11e9-87d8-ee0b3e6f0de2.png)

**Comment by boaz0** [comment]
seems like fixed in 2.5.5

**Comment by rachael-phillips** [comment]
Closing and if not resolved feel free to reopen
