### ISSUE TITLE
PF4 Tooltip - clicking prevents tooltip from opening

### ISSUE THREAD

**Issue by keithjgrant** [patternfly/patternfly-react#1564]
If I click a tooltip, the tooltip box does not open, even if I continue to hover the mouse over it. I would expect a click to open the tooltip the same way a mouse-over or keyboard focus does.

**Comment by rachael-phillips** [comment]
Hi @keithjgrant I have a quick question for clarification. Are you saying it would be preferable to be able to click to open the tooltip? Right now the tooltip appears on hover in the React workspace.

**Comment by keithjgrant** [comment]
Yes, we would prefer the tooltip to open on click. This would allow us to match the existing behavior in our current version of Ansible.

**Comment by dtaylor113** [comment]
Hi, what is the expected behavior if you put a tooltip on a button or menu item?  Would clicking on a menu/dropdown item select the item and also open the tool tip?

**Comment by dtaylor113** [comment]
Hi, any explanation on why this was suddenly closed?  -thanks
