### ISSUE TITLE
PF4 pagination: add offset

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1567]
The pagination component provides one event regardless if the first, last, next, or previous buttons are pressed. 

It would be ideal to have separate (additional) events so we can fetch data using Customer-Facing REST API guidelines. That is, using generated pagination links to fetch first, next, previous, and last paginated data. As an example, please consider the response from this REST API.

![Screen Shot 2019-03-13 at 2 15 54 PM](https://user-images.githubusercontent.com/17481322/54303964-8a5ad700-459a-11e9-8ab5-352a5dab6d76.png)

Note that we cannot call these pagination links directly because we don't know what the user selected from the pagination controls. Unfortunately, the pagination component only provides a page number via the onSetPage event. 

This means we must calculate a data `offset` property used by the REST API, instead. Along with a `limit` property (i.e., perPage), an `offset` provides an index to items for a given page.

FYI, calculating an `offset` is somewhat painful because table pagination is used in multiple places in the UI. Whenever we fetch new data from the API; for example, the `offset` must be calculated like so:

`const offset = (pageNumber * limit) - limit;`

Upon updating the UI with an API response, we then need to calculate the `page` property for the PatternFly pagination component, like this:

`const page = (report.meta.filter.offset / report.meta.filter.limit) + 1;`

Ideally, we would like to call the REST API's first, next, previous, and last links, instead of performing extra calculations.

**Comment by dlabrecq** [comment]
It would also be a nice feature if the pagination component accepted an optional, offset property. Then, it could calculate the page number itself instead of the UI performing that calculation.

**Comment by karelhala** [comment]
Hello Dan, thanks for pointing this out. We are currently providing functions `onFirstClick`, `onPreviousClick`, `onNextClick`, `onLastClick` and `onPageInput` all of them has attributes: `event, pageNumber` [1]. I think that is enough to satisfy any variation of pagination usage. Function `onSetPage` combines all these functions together, so if you are not interested in them you don't have to list 5 functions to accomodate one behavior but use one and you are good to go.

> It would also be a nice feature if the pagination component accepted an optional, offset property. 

I am strongly against this. We have to support wide variety of different usage and it would make this component really hard to use. There are reasons why some apps want to paginate on frontend, oher apps receive calculated page number. Some application might be using offset in different way. If we'd were to add `offset` property to pagination that would cause additional branching and component complexity would be higher.

I hope that answers all your questions.

[1] http://localhost:9999/components/pagination#Pagination

**Comment by dlabrecq** [comment]
Sorry, I missed the additional events. I was working with an early, prerelease.

Regarding the offset, if an optional property is too complex for the pagination component to handle, that complexity falls on the consumers using it. I suppose we will continue to use the workaround we have in place.

**Comment by karelhala** [comment]
Soooo, can we close this one?

**Comment by dlabrecq** [comment]
IF the PatternFly team is refusing to support it...

**Comment by dlabaj** [comment]
If we have a high number of consumers using offset I'm not against having this calculation done for the component.  I don't see this adding that much additional complexity. @tlabaj @jschuler what are your thoughts?  If we do add this I would recommend that page number take precedent over the offset if both are provided.

**Comment by dlabrecq** [comment]
I'd still like an optional `offset` property to help simplify calculations, but will defer to the PF4 team.

**Comment by rachael-phillips** [comment]
HI @dlabrecq is this still a relevant issue that we should address?

**Comment by dlabrecq** [comment]
IMO, it would still be helpful not to calculate the page number ourselves. Considering the pagination component already has `itemCount` and `perPage` properties, it could calculate the page number itself, instead of the UI performing that calculation.
