### ISSUE TITLE
Update form example

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1577]
In the [horizontal form example](http://patternfly-react.surge.sh/patternfly-4/components/form) in the workpsace, we should replace the "can we follow up via email" and "remember my password" rows with these recent updates made in the core version - https://pf4.patternfly.org/demos/BasicForms/examples/

@mcarrano do you agree?

**Comment by mcarrano** [comment]
Yep. Makes sense.

**Comment by boaz0** [comment]
Mind if I take it?

**Comment by mcoker** [comment]
@boaz0 please do! thanks!
