### ISSUE TITLE
ListView storybook does not have an example or documentation for using subcomponents

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#158]
There is no usage nor documentation for the following:

- ListViewActions
- ListViewAdditionalInfo
- ListViewBody
- ListViewCheckbox
- ListViewDescription
- ListViewDescriptonHeading
- ListViewDescriptionText
- ListViewExpand
- ListViewGroupItem
- ListViewGroupItemContainer
- ListViewGroupItemHeader
- ListVIewIcon
- ListViewInfoItem
- ListViewLeft
- ListViewMainInfo
- ListViewRow

**Comment by chalettu** [comment]
@jeff-phillips-18 , I was starting to look at this.  I am wanting to get some input on how you think we should organize this.   Do you want a story per sub component or how do you envision you would like this to be structured?

**Comment by jeff-phillips-18** [comment]
@chalettu Typically we do one story but include the doc for each subcomponent in that story.

**Comment by chalettu** [comment]
@jeff-phillips-18 , here is a sample I am working on.  Is this the structure you think is what you would like.  
![story examples](https://user-images.githubusercontent.com/230549/38695147-a3a92a04-3e48-11e8-9529-aa7bc8ab9576.gif)

**Comment by jeff-phillips-18** [comment]
Yes. However, I am currently working on https://github.com/patternfly/patternfly-react/issues/304 which will change this a bit. Trying to get to one story per component.

I'm ok with you continuing here and I'll update what I do to what you do if you get there first for the list view component.

**Comment by priley86** [comment]
Would like to piggyback on this. Showing the variations of the detail expansions would be extra helpful for us. 

Relevant PR in V2V/MIQ:
https://github.com/priley86/miq_v2v_ui_plugin/pull/193
