### ISSUE TITLE
support responsive layouts

### ISSUE THREAD

**Issue by atiratree** [patternfly/patternfly-react#1595]
Support different layouts of components per each responsive class. 

Example usage: https://github.com/kubevirt/web-ui-components/pull/268/files#diff-ffa82c1dddf025e859b0be2009b746deR43. We used  [react-responsive](https://github.com/contra/react-responsive) (media queries) in our solution. 

Pf-react could wrap `react-responsive` behavior and add support for different layout composition only for predefined classes (`sm, md, lg, ...`). Or make a custom solution which behaves somewhat similar to  `react-responsive`.

First step of this RFE could be, to export `sm, md, lg, ...` breakpoint variables

Just a quick draft how the full implementation might look like:

```jsx
    <div>
      <Show from={0} to={MD}>
        <MySmallComponent/>
      </Show>
      <Show from={MD} to={MAX}>
        <MyBigComponent/>
      </Show>
      <Show lg xl>
        <LargeScreenNotification/>
      </Show>
    </div>
```

**Comment by redallen** [comment]
We have breakpoints for components that need them and I think implementing breakpoints for entire sections of JSX is best left to the consumer.
