### ISSUE TITLE
TS errors in chart component(s)

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#1603]
When attempting to test drive our charts in a TypeScript based application I ran into several issues. In short, the examples don't really work out of the box. 

AreaChart - errors around `containerRef` property, was able to get the component to render by removing this section of the code. Also had to specify a literal value for width when setting state.

BarChart - Was not able to get this component to render. I was able to silence a few of the errors that came up, but below is an example of the error I received that stopped me in my tracks.

<img width="964" alt="Screen Shot 2019-03-18 at 3 54 17 PM" src="https://user-images.githubusercontent.com/5942899/54559768-29b30c00-4997-11e9-9b8c-6a644a2781ac.png">

DonutChart - Needed to add a class property for size. Was able to get this working by using static values, but I have no idea if the values I've used will cause problems. Seems like "200px" works, but I'm just shooting in the dark.

LineChart - type errors, most of which I was able to silence, but the following is an example of one I couldn't figure out;

<img width="987" alt="Screen Shot 2019-03-18 at 3 54 53 PM" src="https://user-images.githubusercontent.com/5942899/54560039-cfff1180-4997-11e9-9fa1-f7aca408a789.png">

PieChart and StackChart errors were pretty straight forward to silence, mostly just a matter of specifying a type for "theme" param. I used `any`, which is not recommended.

All in all, aside from the immediate errors I was met with, the main thing I walked away feeling was that it was a bummer not to have had any description in the form of English that explains what these chart components were best suited for (all of our components are like this btw). We basically just offer up the code and expect users to find and figure it all out for their selves. Would have been nice to see some elaboration on what each chart was intended to relay (information-wise) and what some of the input values are supposed to represent. This small change would improve the DX in a big way.

**Comment by dlabrecq** [comment]
FYI, the charts are simple wrappers around Victory charts. I consider this an initial implementation with some styling, but there is more styling work to be done (e.g., styles, default color pallets, etc.). 

Note that the components are all (with the exception of stack chart) currently used in the Cost Management UI, which is also a TypeScript application and without TS errors.

If you're having trouble using charts, I suggest looking at the Victory documentation. You should be able to use Victory in the same manor (e.g., Chart is VictoryChart, ChartGroup is VictoryGroup, etc.)

https://formidable.com/open-source/victory/docs/

**Comment by dlabrecq** [comment]
@types/victory may be helpful? It's used in @patternfly/react-charts, but wasn't necessary for the Cost Management UI.

**Comment by seanforyou23** [comment]
`@types/victory` - good call @dlabrecq, that fixed BarChart for me. Still unable to get LineChart going, but feel like it's a good step in the right direction. Might be able to configure typeRoots in the seed project to get victory chart types out of the box (we don't configure typeRoots currently). Realizing now that the `noImplicitAny` setting in patternfly-react-seed further complicates the situation.

I'll see if I get similar errors when using VictoryCharts directly and keep you posted with findings. Thx for the tips!

**Comment by dtaylor113** [comment]
> Cost Management UI, which is also a TypeScript application and without TS errors.

Hi, so can we close this issue?  -thanks
