### ISSUE TITLE
Select enhancement to set toggle width based on menu width

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#1617]
Currently, the toggle for the Select component must have the width set to an arbitrary value in order for the toggle width to not change when selecting a menu item.  

This issue is to investigate whether it would be possible to set the width of the toggle based on the width of the menu.

**Comment by mcoker** [comment]
[mailchimp](https://ux.mailchimp.com/patterns/forms) sets the toggle to the selected item size, so the toggle and menu are different sizes.

**Comment by dgutride** [comment]
Need to test to see if this is still an issue
