### ISSUE TITLE
Refinements for Wizard Component and Demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#1618]
Just doing a design review of the [wizard component](http://patternfly-react.surge.sh/patternfly-4/components/wizard) as recently merged and have some issues that we would like to see addressed:

* Sidebar styling does not seem right. Background fills for disabled states are too light and difficult to tell visually what steps are disabled. 

* Buttons should always be left aligned per designs. "Validation Wizard" has incorrect button placement.

See core implementation for correct button placement and sidebar styling: https://pf4.patternfly.org/components/Wizard/examples-full/?component=Wizard

For the React demo, it would be good to show how this wizard can be used to progressively disclose steps and have sample screens to indicate progress and completion. This flow is illustrated in the design storyboard here: https://redhat.invisionapp.com/share/SZPQWBQY2KH

**Comment by mcarrano** [comment]
@rachael-phillips I entered a new issue for the React wizard as this got merged before we had an opportunity to do a UX Review. There are some visual issues and also a request for a more robust demo. I think we can prioritize if needed. @kybaker please feel free to add further details about visual issues that you see.

**Comment by jschuler** [comment]
Hi @mcarrano , the first issue needs to be addressed in core @mcoker , the second issue is a simple configuration option that can be passed into the wizard. I can update it to default to left alignment.
I agree it would be great to have a more complex demo. Let's add one this sprint.

**Comment by mcarrano** [comment]
Thanks @jschuler . I will try to pull together a meeting with you, me, @mcoker , and @kybaker to review the sidebar styling and decide what needs to be fixed for release. I think that the demo is less critical and can be added later. We should discuss how to proceed with that, however, and what is needed (if anything) from a CSS perspective or if we only need a demo in React.

**Comment by mcoker** [comment]
> the second issue is a simple configuration option that can be passed into the wizard

@mcarrano per our discussions about button placement, should we remove the option of right-aligning the wizard action buttons? Currently they're left aligned by default, but you can right align them with `.pf-m-align-right`.

**Comment by mcarrano** [comment]
@jschuler @mcoker @kybaker and I met today to review the current implementation. A separate issue has been opened here to track styling changes that are needed in the CSS: https://github.com/patternfly/patternfly-next/issues/1616.

There is an updated InVision project that includes high-fidelity mockups and interaction notes. https://redhat.invisionapp.com/share/W3QA5O64XNQ To see these go to Comments mode and look for the yellow call-outs. @jschuler please update the React examples to be consistent with this prototype (excepting places where the visuals need to be updated, as noted). There should be 3 variants:

* Simple wizard -all steps known and no substeps.
* Wizard with substeps
* Progressive wizard - all steps not know but are added/modified as user progresses through the flow.

Let me know if you have questions.

**Comment by terezanovotna** [comment]
Hi there!

After watching the PF4 Designer training yesterday, I hope I am following the right process. 
Browsing through React implementation of the wizard and I want to address two issues I found:

http://patternfly-react.surge.sh/patternfly-4/components/wizard

1)Button alignment `I see it's already addressed above`
in Simple Wizard and in Validation Wizard, buttons placement is not consistent. once they are on the left and once they are on the right. according to pf4, they should be all aligned left?

2)Usability problem
in the Validation Wizard, try clicking on next button (stay on the same area with your mouse click), and then go to step two. you'll experience looping between step 1 and 2 and not getting further. this is a confusing behavior

**Comment by dgutride** [comment]
Closing via #1754
