### ISSUE TITLE
Unit tests for `util.ts` are broken.

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#1624]
The unit tests for `keyHandler` in `util.test.js` are not making any assertions. The `expect` lines should look like this:

```js
    expect(firstDropdownItem).toEqual(document.activeElement);
```

instead of this:

```js
    expect(secondDropdownItem === document.activeElement);
```

As they are, these tests are not actually accomplishing anything and currently fail if the assertions are corrected. These should be revised and updated.

**Comment by dgutride** [comment]
Need to review to see if this is still an issue - pinning open

**Comment by rachael-phillips** [comment]
@dana did we find out if this is still an issue?
