### ISSUE TITLE
PF4 documenation page returns http status 404

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#1626]
Url http://patternfly-react.surge.sh/patternfly-4/index.html (referenced from http://patternfly-react.surge.sh/) returns http status 404.

**Comment by craicoverflow** [comment]
**Workaround**

Use the preview site:

https://1623-pr-patternfly-react-patternfly.surge.sh/patternfly-4/

**Comment by dtaylor113** [comment]
Those links appear to be working now.  Ok to close this issue?

**Comment by idevat** [comment]
It works now. Thanks.
