### ISSUE TITLE
PF4 Bring Reactabular in-house

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#1628]
Reactabular is no longer as active as the project here and I believe thru discussions and recent PRs it would be better to bring this minimal library in-house. Reactabular's current source is a good starting point for writing minimal table extensions, but I believe we can customize and improve it much faster here. The upstream maintainer is no longer able to actively maintain it as noted in [#313](https://github.com/reactabular/reactabular/issues/313) [#338](https://github.com/reactabular/reactabular/issues/338#issuecomment-460069536). 

Noted issues causing a poor developer experience:
- `onChange` \ `onBlur` callbacks for rows are not handled correctly upstream and our current [workarounds](https://github.com/patternfly/patternfly-react/pull/1227/files#r263421663) are not great.
- passing `refs` thru [callback methods](https://github.com/reactabular/reactabular/blob/bd94bbc30e22ba5e0ec5871b2bbf38112391972d/packages/reactabular-table/src/header.js#L35) is no longer a good way to pass React refs, and `React.createRef()` should be used instead.
- `getChildContext` is the old way of using React context. We can update [this](https://github.com/reactabular/reactabular/blob/bd94bbc30e22ba5e0ec5871b2bbf38112391972d/packages/reactabular-table/src/provider.js#L8) to use the new stable [Context API](https://reactjs.org/docs/context.html).

Proposed solution:
- We only currently consume `reactabular-table` (which is luckily only [12 js files](https://github.com/reactabular/reactabular/tree/bd94bbc30e22ba5e0ec5871b2bbf38112391972d/packages/reactabular-table/src) 😎). Bring them in-house and expose as a new package `@patternfly/reactabular-table` and consume them from `@patternfly/react-table`. I think this would be a great first step. Another alternative (which may be better and help us avoid another internal package) would be to bring the source directly into `react-table` and just rename the components to avoid conflict, i.e. `BaseProvider`, `BaseBody`, `BaseBodyRow`, `BaseHeader`, `BaseHeader`, `BaseHeaderRow` or attempt to integrate them inside our current wrappers there. 
- Continue writing our own extensions here in patternfly-react

Additional nice-to-haves:
- convert to TSX
- incrementally fix the issues above
- revisit the API of `Provider`, `Body`, `BodyRow`, `Header`, `HeaderRow` and see if we can improve them.

thoughts?

**Comment by suomiy** [comment]
> Noted issues causing a poor developer experience:

Agree. I would also note that this is about the user experience as well. It is impossible to implement real-time validation (key by key) with current `reactabular-table` .

> We only currently consume reactabular-table (which is luckily only 12 js files). Bring them in-house and expose as a new package @patternfly/reactabular-table and consume them from @patternfly/react-table. I think this would be a great first step.

This approach makes sense and is a good way forward.

**Comment by redallen** [comment]
If we're going to go through that much effort, it would be nice to compare other 3rd party table dependencies too.

**Comment by suomiy** [comment]
> If we're going to go through that much effort, it would be nice to compare other 3rd party table dependencies too.

+1 it is good to look at other options. Anyway I think other solutions might be hard to customize for our API and take much longer to adapt compared to just modifying reactabular. Also the consumers are quite used to how reactabular handles things

**Comment by priley86** [comment]
@redallen - this was discussed originally in [402](https://github.com/patternfly/patternfly-react/issues/402#issuecomment-428975243). I think we used Reactabular initially as a "how-to" for building minimal React tables, but now we have outgrown it in a sense. Many other 3rd libraries impose assumptions that I don't think PF quite warrants (i.e. take Bootstrap as an example, we no longer subscribe to that ecosystem for various reasons). In many cases, it makes more sense to take these implementations in-house and customize them in PF (and treat JS similar to the way we now treat CSS in PF Next). This should be a minimal effort (what I am describing above), but always happy to hear about alternatives 😸

**Comment by priley86** [comment]
resolved in #1250 - the hope is to update the base components and convert them to TSX in the future. This was necessary to resolve some React warnings being thrown in the base library. I have also gone ahead and converted `lodash` usages to `lodash-es`.

**Comment by priley86** [comment]
closed by #2011
