### ISSUE TITLE
PF4 Wizard doesn't allow to control the steps from outside

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#1630]
The wizard component encapsulates the workflow of steps. Consider the following (simplified) scenario:

A user wants to add a cluster to cluster management.
1. The user opens a wizard (at step 1).
2. The user enter name of one cluster node and click on button "Next".
3. A check request (whether the back-end is authenticated against chosen node) is sent. (Suppose the answer is not authenticated.)
4. Wizard goes to step 2. It shows form with password (only this field to keep it simple for now).
5. An authentication request is sent. (Suppose password is wrong).
6. At this point, I would expect the wizard to stay at step 2 and the password field is shown again (with an explanation). But I was not able to achieve this behavior.

So, in code it looks like this (in principle, simplified):
```javascript
const Test = () => {
  const [password, setPassword] = React.useState("");
  const [step, setStep] = React.useState(1);
  const [wrongPasswordUsed, setWrongPasswordUsed] = React.useState(false);

  const onNext = () => {
    if (step !== 2 || password === "pw") {
      setStep(step + 1);
      return;
    }
    console.log("I really need to keep step 2. But how?");
    setWrongPasswordUsed(true);
  };

  const steps = [
    {
      name: "Enter node",
      component: "User enter node here...",
    },
    {
      name: "Node authentication",
      component: (
        <React.Fragment>
          Password:
          <input
            value={password}
            onChange={e => setPassword(e.target.value)}
          />
          {wrongPasswordUsed && <p>Wrong password, try again</p>}
        </React.Fragment>
      ),
    },
    {
      name: "Add cluster",
    },
  ];
  return (
    <Wizard
      data-role="add-cluster-wizard"
      isOpen
      startAtStep={step}
      title="Test"
      steps={steps}
      onNext={onNext}
    />
  );
};

```
- The main question here is how to keep step 2 in the case of wrong password.
- I tried to set step with `startAtStep` attribute, but it is really only for start.
- I used my own state `step` to identify my situation. I'm aware that using `onNext` is not sufficient. It is also needed to use at least `onBack` and `onGoToStep` to track current step. It is really uncomfortable.
- If I need to change the button `Next` label (e.g. `Check authentication` in step 1, `Authenticate node` in step 2) I would have to track current step as well. 

Maybe I'm wrong and I misunderstand the patternfly wizard intention. Are there any guidelines for wizard mechanisms  somewhere? I mean something explaining how to implement various scenarios?

I also thought of another solution: 

In step 1:
1. disable the `Next` button
2. add an extra button (`Check node authentication`) next to field with node name.
3. the user clicks on `Check node authentication` button.
3.1. the `Next` button is enabled and the button `Check node authentication` disappear - when node is already authenticated.
3.2. the form with the password field + button `Authenticate node` appear - when node is not authenticated. Let's continue from this point to 4.
3.3. leave other cases aside...
4. user enters a password and clicks on the `Authenticate node` button.
4.1. more or less the same as in 3.1 - when authentication succeeds.
4.2. the same as in 3.2 (+ explanatory message) - when authentication fails.
5. the user clicks on the `Next` button when node is authenticated.

So, all points above are part of step 1. Is this the way the wizard was intended? Is it correct to use extra button inside the step component? Is it correct to have single step so complex (previous points are a bit simplified as a matter of fact)?

I have another scenario:
There is a cluster setup (let's say) wizard in (too) old version of our web ui. User enters cluster name and names of nodes. At this point he can do 3 actions (buttons): `Create cluster` (the simplest case), `Add advanced options` and `Cancel`. Current implementation of wizard allows only the `Next` button and the `Cancel` button (and `Go back` but here it does not matter). 

So again: is it correct to put the `Create cluster` button inside step component and use the `Next` button as `Add advanced options` (it leads to relatively complex form - it should be maybe split to more steps)?

Is somewhere more appropriate place to ask such type of questions than this github issues page?
Thanks.

**Comment by idevat** [comment]
I've tried to implement my "another solution" (with extra buttons inside the step component) and it works. (But the question if it is a right way still remains.)

However, I noticed another problem. (For now, this is a theoretical problem, because in my current case I don't have to bind more functions to `onNext` attribute.)

1. The user clicks on the `Next` button at step 1.
2. The wizard goes to step 2 and a request to back-end is sent. (via function bound to `onNext` attribute).

How can I bind another function in step 2? I need to decide which of two functions should be bound. And for that decision I need to know the current step.

To call the function via `componentDidMount`/`useEffect` of the step component is not a solution because I need to call the function only when the user clicks on the `Next` button and I don't want it when they clicks on left step navigation.

**Comment by jschuler** [comment]
Hi @idevat , the onNext callback is called with arguments 
`newStep: { id?: string | number; name: string; }, prevStep: { prevId?: string | number; prevName: string; }`
An example is here:
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Wizard/examples/ValidationWizard.js#L48
id and name are additional fields that are part of your step. 
I think this example has some of the behaviors that you are looking for. You can see a live example here:
http://patternfly-react.surge.sh/patternfly-4/components/wizard
There is also an additional field you can add in your steps configuration, `enableNext`.
This enables the Next button conditionally. This way you can configure so users cannot continue until the form is valid.

**Comment by idevat** [comment]
Hi @jschuler, thanks for the response.

Arguments of `newSteps` are definitely answer to the question about binding multiple functions to `newStep` attribute.

I have used the attribute `enableNext` in my attempt with adding extra button inside the step component. However, I was looking for a little bit different behavior:

1. A user clicks on the `Next` button.
2. A request to the back-end is sent. (The wizard stays on the same step waiting for response. The spinner can be shown, for example).
3. The wizard goes to the next step in the case of success response. It stays on the same step in the case of failed response.

The next question was about using more `Next` buttons. One button to go to the next step, the other to skip the next few steps. (i.e. `Advanced settings` vs `Create cluster` without advanced settings).

Maybe these scenarios miss the intention of patternfly wizard. Can you direct me to some guidelines in such case?
Is it ok to use another buttons beside `Next`, `Back` and `Cancel`?
Is it ok to have another extra buttons in step component?
How to deal with asynchronous actions (and they results) in the context of wizard?

**Comment by jschuler** [comment]
@idevat You can define your own footer buttons now, this should give you the flexibility you're looking for. Closing this issue as I think this is addressed, thanks!
