### ISSUE TITLE
PF4: Empty state button w/ vs w/o link - Add support for React Router to Button

### ISSUE THREAD

**Issue by martinpovolny** [patternfly/patternfly-react#1653]
If I place a link around the button in empty state the space between the EmtyStateBody and the Button is missing:

![empty-state-no-link](https://user-images.githubusercontent.com/51095/55162669-95039780-5168-11e9-9e9a-0976efc97dce.png)

![empty-state-link](https://user-images.githubusercontent.com/51095/55162670-959c2e00-5168-11e9-926d-7b256320737e.png)

```
                <EmptyState>                                                                             
                    <EmptyStateIcon icon={CubesIcon} />                                                  
                    <Title headingLevel="h5" size="lg">No Sources</Title>                                
                    <EmptyStateBody>                                                                     
                        No Sources have been defined. To start define a Source.                          
                    </EmptyStateBody>                                                                    
                    <Link to='/new'>                                                                     
                        <Button variant="primary">Add a Source</Button>                                  
                    </Link>                                                                              
                </EmptyState>   
```

**Comment by rachael-phillips** [comment]
@martinpovolny thanks for posting! @mcarrano @mcoker in this issue @martinpovolny has used a link around the button. Is this the intended use for the button and/or something we can support?

**Comment by mcoker** [comment]
@martinpovolny I think in this case you would want to use a [link button](http://patternfly-react.surge.sh/patternfly-4/components/button) instead of `<Link>`

```
<Button component="a" href="/new" target="_blank" variant="primary">
   Link to Core Docs
</Button>
```

**Comment by martinpovolny** [comment]
@mcoker : Thanks, that works as needed!

**Comment by martinpovolny** [comment]
@mcoker : The styling is ok. But the functionality is not the same.

How do I do a proper react router link with that? The `href` that you are suggesting here works as a normal HTML href not a React router `<Link />`

**Comment by mcoker** [comment]
@tlabaj @jschuler ^

**Comment by martinpovolny** [comment]
My temporary hack solution:

```
                    <Link to={paths.sourcesNew}>                                                     
                        <Button style={{ marginTop: 'var(--pf-c-empty-state--c-button--MarginTop)' }}
                            variant="primary">Add a Source</Button>                                  
                    </Link> 
```

**Comment by martinpovolny** [comment]
Any news on this? Or are we supposed to create `<Button />` w/o the wrapping `<Link />` but with an `onClick` handler?

What is the correct solution here?

Thx!

**Comment by dlabaj** [comment]
We should update our button to have support for React router similar to what we do with NavItem.  For now you can use what you have above if it's working but we should make the update on the PF4 end so you can add the Link component by doing

<Button> <Link /> </Button>  instead of  <Link> <Button /> </Link>

**Comment by dlabaj** [comment]
@rachael-phillips and @tlabaj Can we pull this into the upcoming sprint so we can get a fix for this.

**Comment by rachael-phillips** [comment]
Hi @dlabaj yes, let's find someone to work on this in Slack.

**Comment by martinpovolny** [comment]
Hallo. I have noticed that the issue is marked as solved but I see no link to a solution or to a PR or something.

What is the status?

Thx!

**Comment by rachael-phillips** [comment]
Hi @martinpovolny apologies, I accidentally closed it and reopened it. We hope to have this done for our next release candidate at the end of May.

**Comment by martinpovolny** [comment]
Thanks for the explanation.

**Comment by jessiehuff** [comment]
@martinpovolny Would this work? You can tell Button to use the React Router component. `<Button component={Link} to="/new">Button Link</Button>`

**Comment by martinpovolny** [comment]
Thanks, yes, this works for us.

**Comment by jessiehuff** [comment]
Awesome, thanks so much for checking! :) Feel free to reopen if you'd like.
