### ISSUE TITLE
Alerts should have an optional timeout when used as a toast

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#1654]
Per the PF4 design guidelines, toast alerts should time out after a certain period of time. 

"Transient toast alerts automatically dismiss after a period of time. Eight (8) seconds is a recommended timeout, but alerts should remain visible if the user is hovering over them."

Looks like this behavior is not built into the component but it should be.

**Comment by rachael-phillips** [comment]
Hi Matt, what priority do you think this is?

**Comment by mcarrano** [comment]
I would check with developers on the React side. It could possibly be handled outside of the component, but it was a feature that was there in PF3 so we lost functionality. @seanforyou23 wrote on Slack:

> in PF3 we had a `TimedToastNotification` with `persistent` and `timerdelay` properties which make flexible how and when a notification can be dismissed. In PF4 React we currently only have Alert, which does have the timer functionality.

I think it's high priority and we should assess how much work it is to add this. I think it will be expected functionality.

**Comment by seanforyou23** [comment]
We will soon have a need for it over in Fuse, and while possible to handle outside of the core react component, it won't desirable on the consuming side. I don't think adding the timeout feature will involve a ton of extra work.

I tried using `TimedToastNotification` inside of the new PF4 AlertGroup and it seems to work just fine (win!) so that buys us some time in case we need it.

**Comment by rachael-phillips** [comment]
@dlabaj how much work will this require over on the React side?

**Comment by dlabaj** [comment]
There isn't much work to add this ability. @rachael-phillips @tlabaj

**Comment by mcarrano** [comment]
We should definitely have this capability. Here's what our design documentation currently says about this:

> Transient toast alerts automatically dismiss after a period of time. Eight (8) seconds is a recommended timeout, but alerts should remain visible if the user is hovering over them.

**Comment by dlabaj** [comment]
@mcoker @seanforyou23 Are we thinking it will be hidden or removed from the DOM?  If it's hidden do we need a modifier for it?

**Comment by mcarrano** [comment]
That's fine to keep the current default behavior @dlabaj . As for whether to hide or remove, seems like you would want to remove. Otherwise if you hide, how does the user get rid of them?

**Comment by seanforyou23** [comment]
@dlabaj  I think removing it from the DOM is the way to go, can't think of any reason to keep it around at the moment.

**Comment by dlabaj** [comment]
Thanks @mcarrano and @seanforyou23 for the feedback.  If it was hidden the developer would have to remove them.  Wasn't sure if there was a use case where the notification would want to be seen by the user after it disappears.  We will go with removing them from the DOM.

**Comment by jenny-s51** [comment]
@dlabaj @seanforyou23 What would be the preferred way to approach this? I’m looking at the `TimedToastNotification.js` file in PF3, but that class belongs to its own component ToastNotification. Should I try to reproduce the same class in TSX, add this new file to the Alert component, and call it within `Alert.tsx`? Or should I just add that timer functionality somewhere in `Alert.tsx` directly?

**Comment by Deurnieur** [comment]
Any news on this feature ?

Thanks
