### ISSUE TITLE
No exported member 'compoundExpand' for react-table

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-react#1657]
![Screen Shot 2019-05-22 at 3 28 22 PM](https://user-images.githubusercontent.com/11218376/58202964-fba7bc00-7ca6-11e9-8a9b-4619301af8ec.png)

**Comment by ibolton336** [comment]
FIxed as of 4-17

**Comment by ibolton336** [comment]
![Screen Shot 2019-05-22 at 3 28 22 PM](https://user-images.githubusercontent.com/11218376/58202908-cdc27780-7ca6-11e9-8af8-295099958698.png)

**Comment by ibolton336** [comment]
My original issue was resolved, but now I am having an issue importing the compountExpand module.

**Comment by rachael-phillips** [comment]
Hi @jcaianirh are we ready to close this issue?

**Comment by jcaianirh** [comment]
yes! thanks this is closed with the mentioned merged pr.
