### ISSUE TITLE
Make github and google drive icons available

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-react#1666]
Please add the github and google drive icons for use. 
https://fontawesome.com/icons/github?style=brands
https://fontawesome.com/icons/google-drive?style=brands

Also, there's a typo "fortawesome" in this file :-)  https://github.com/patternfly/patternfly-react/blob/master/packages/react-icons/README.md

**Comment by karelhala** [comment]
We should include all brand icons, last time I tried it failed with `500px` icon (this requires change after import), but other should be fine.
