### ISSUE TITLE
React-charts Axes Hidden

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#1673]
The axes are hidden on [a few charts](https://1656-pr-patternfly-react-patternfly.surge.sh/patternfly-4/charts/chartbar/) that need the following styles applied:
```
svg {
  overflow: 'visible'; }
```

We should apply these styles for the consumer instead of making them define their own CSS.

**Comment by rachael-phillips** [comment]
HI @redallen would you consider this a bug or an enhancement?

**Comment by redallen** [comment]
Considering it's also an [upstream issue](https://github.com/FormidableLabs/victory/issues/991) if you structure the <Victory> components the way we do, I'd say so. We should be applying all styling for the consumer so they don't have to worry about this.

**Comment by dlabrecq** [comment]
This has been fixed by adjusting the default padding
