### ISSUE TITLE
Add no border rows option to compact table

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1674]
We added borders to the compact table, and a modifier to disable them

https://github.com/patternfly/patternfly-next/pull/1541

This is also related to https://github.com/patternfly/patternfly-next/pull/1563/ (react issue for that is https://github.com/patternfly/patternfly-react/issues/1679), which says the "no border rows" modifier can't be used with an expandable compact table.

**Comment by tlabaj** [comment]
Closed by #1745
