### ISSUE TITLE
Add small/large props to empty state

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1677]
https://github.com/patternfly/patternfly-next/pull/1475

not sure if you would want someone to be able to set a custom `width` or `max-width`, too?

**Comment by boaz0** [comment]
@mcoker @rachael-phillips can you assign me to this please. :pray: 
Thanks.

**Comment by mcoker** [comment]
The component should use the `pf-m-lg` variation by default, with the option to change that and be either full width or small.
