### ISSUE TITLE
Add wrapper to accordion, datalist, page (sidebar)

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1682]
Need to add these elements. They should be a direct child of the parent BEM element

* `.pf-c-data-list__expandable-content-body` (child of `.pf-c-data-list__expandable-content`)
* `.pf-c-page__sidebar-body`(child of `.pf-c-page__sidebar`)
* `.pf-c-accordion__expanded-content-body` (child of `.pf-c-accordion__expanded-content`)

**Comment by tlabaj** [comment]
Accordion has not been merged in react yet. @ibolton336  can you add the accordion wrapper to your PR please?
.pf-c-accordion__expanded-content-body (child of .pf-c-accordion__expanded-content)

**Comment by tlabaj** [comment]
Closed by #1703
