### ISSUE TITLE
Add Less -> Sass Converter

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#169]
Since we need to support both Less and Sass, we should use a converted to that contributors need only create the less files rather than both.

See https://github.com/patternfly/angular-patternfly/pull/692

**Comment by cdcabrera** [comment]
This is minor, but if anyone is curious. @jeff-phillips-18  @priley86 Looks like a side piece to this issue/task could be addressing some of the Sass NPM install issues vs the Yarn install.

The `optional dependency` install `"bootstrap-sass": "^3.3.7"` from Patternfly core is where it's at... adding `bootstrap-sass` into PF-React as a some form of dependency resolves NPMs issues.

**Comment by jeff-phillips-18** [comment]
Given the status of pf3 react and the difficulty of this request, closing.
