### ISSUE TITLE
Charts updates

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-react#1692]
@rachael-phillips @dlabrecq After reviewing our current implementation of charts compared to the original proposed design, I've found the following items that need to be addressed:

- All charts that use multiple colors and do not have descriptive variable names on either axes need to have legends listing those variables
- Legends are always left-aligned and can either be placed centered underneath the chart or to the right of the chart
- Area, bar, line and stack charts need tick marks at all values on x and y axes → these tick marks should ultimately be optional for use, but we want to recommend using them
- Area and line charts need dots at each discrete value shown
- Area and line charts need the dot at a discrete value to expand from 8x8 to 12x12 upon hover (tooltip appears at this time too)
- Area, donut and pie charts tooltips on hover should be using the PF4 styled tooltip
- Donut charts need a grey fill for unused chart area
- Donut charts need another design example that represents thresholds - grey #D8D8D8 fill for unused chart area, blue-300 #73bcf7 fill for 1st level of threshold (no threshold has been reached), gold-400 #F0AB00 fill for 2nd level of threshold (warning threshold has been reached), red-100 #c9190b fill for 3rd level of threshold (danger threshold has been reached) --> this has been addressed and design documentation differs from what is listed here -- has been merged

Referenced here: https://github.com/patternfly/patternfly-org/issues/720 (Charting documentation)

**Comment by cben** [comment]
I'll take this opportunity to ask some questions :)

- I'd love to see examples / guidance for DonutChart and its tooltips with units, e.g. "876.5 MiB used out of 2.34 GiB capacity".  Should each number be humanized & rounded separately?  Should all be forced to use same unit?
  I've had some bugs implementing this in a project, and I think I now know how to do it right, but would like guidance how it *should* behave...

- How should Donut charts look when numbers are 0?
  - "0 out of 5 nodes" — without legend, the 0 portion would be invisible (and impossible to hover on), which is sometimes fine sometimes not.
  - "0 out of 0 nodes" — not sure whether this has legit use cases, in our case this was missing data.  OK, how should chart look when data is missing?

**Comment by gdoyle1** [comment]
Hi @cben ! If you'd like to take a look at these guidelines https://docs.google.com/document/d/1-R9JGlkTeU8-xa0lkfox4kn5HxFN6vJjQ1i9NN1-z6M/edit?usp=sharing I think they'd be helpful in answering your questions. I'm working on designing donut charts with thresholds now. But you'll find the simple design for a donut chart in that document.

**Comment by dlabrecq** [comment]
The tooltips and donut charts have been addressed.

Victory doesn't support "Area and line charts need dots at each discrete value shown"

**Comment by gdoyle1** [comment]
@dlabrecq Seems like we covered as much as we possibly could here then. If it hasn't already been done then it is in progress. Seem right?

**Comment by dlabrecq** [comment]
We can still update the examples to add legends, axis tics, etc.

**Comment by dlabrecq** [comment]
Updated the legends, grids, axis ticks, etc. via this PR:
https://github.com/patternfly/patternfly-react/pull/2324
