### ISSUE TITLE
In the Wizard, add the ability to hide the nav.

### ISSUE THREAD

**Issue by vbusch** [patternfly/patternfly-react#1695]
We have a use case where we want to hide the left side nav for a step.  And when the nav is shown, that step shouldn't appear in it.

Here is the use case:
- Step 1 and Step 2 are entering data into forms.
- The third step is for reviewing and has the finish button.
- The fourth step is an 'in progress... status screen'.  It shouldn't show the navigation items.
- The fifth step is the final status.  .  It shouldn't show the navigation items.

When the left nav is shown (Steps 1-3), the navigation items would only contain:
- Step 1
- Step 2
- Step 3
When on the last 2 steps (step 4 & step 5), the left side nav would be hidden.

**Comment by amysueg** [comment]
@mcarrano For the Wizard design guidelines to take into consideration.

**Comment by mcarrano** [comment]
Yes, this is in fact the way it is intended to work. There is an open issue here for cleaning up the current React implementation: https://github.com/patternfly/patternfly-react/issues/1618. @jschuler please take note. There is an InVision deck here that shows the intended flow: https://redhat.invisionapp.com/share/W3QA5O64XNQ

**Comment by dlabaj** [comment]
@tlabaj Do you think we can get this into the next sprint?

**Comment by dgutride** [comment]
Closing via #1754
