### ISSUE TITLE
PF4 about modal  is not closed when clicking somewhere else on page outside of About box

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#1699]
In PF4 component about modal  is not closed when clicking somewhere else on page outside of About box. But it used to be in PF3

PF4: [Storybook aboutmodal PF4](http://patternfly-react.surge.sh/patternfly-4/components/aboutmodal)
PF3: [Storybook aboutmodal PF3](http://patternfly-react.surge.sh/patternfly-3/?selectedKind=patternfly-react%2FCommunication%2FAbout%20Modal&selectedStory=AboutModal&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by priley86** [comment]
cc: @patternfly/patternfly-react-ux ^^ - is this behavior expected to be different in PF4?

**Comment by jgiardino** [comment]
Yes, I think the expectation was that modals cannot be dismissed by clicking outside the modal, but @mcarrano would need to confirm this.

**Comment by mcarrano** [comment]
Yes that's correct.

**Comment by priley86** [comment]
ok to close this one @aljesusg? Hopefully, this answers the question.

**Comment by aljesusg** [comment]
Yes, thanks !!!
