### ISSUE TITLE
Make card header a large title 

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1708]
https://github.com/patternfly/patternfly-next/pull/1696

**Comment by rachael-phillips** [comment]
this one may be considered a breaking change in react, because it will make our card header font bigger/bolder by default. doesn’t break the API or anything, but folks will notice a font size/weight change after it’s added

**Comment by tlabaj** [comment]
@mcoker @rachael-phillips Should the consumer be able to remove the large modifier for the header?  Or should it always be large?

**Comment by mcoker** [comment]
@mceledonia what do you think? FWIW, I think if a person wanted to use a different title type, they should be able to just use their own `<Title>` component in the header with the modifier for whatever title size they want. But should they be able to undo the new default styling of the header and put normal text in there without having to overwrite CSS to do so?

**Comment by mceledonia** [comment]
@mcoker Yes, and we should probably apply this approach to other components where applicable, such as the modal.

**Comment by mcoker** [comment]
Chatted with @mceledonia about this. We should try to be consistent with how other components behave and encourage the default to be used, and make the user deviate from the component's defaults purposefully if they want something different.

In the case of empty state, modal, popover, and card, the header element should be a `<Title>` with the size modifier (ie, lg, xl, 2xl, etc) used in core by default. And if a user wants to change the heading level and/or the size modifier, they can.

**Comment by tlabaj** [comment]
Closed by #1703
