### ISSUE TITLE
ToastNotificationList: Removing last toast notification removes auto-dismiss feature

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#172]
If I close the last toast notification in the list via the close button, the other notifications do not auto-dismiss after the timer delay period expires.

**Comment by AllenBW** [comment]
confirmed, looks like the timer is getting jacked 🆙 ... if ya close last notification, hover over others, **then** they close... otherwise, they persist FOR ALL ⌛️ 

working this presently 🌮 💃
