### ISSUE TITLE
PF4 Modal uses an unnecessary extra Bullseye

### ISSUE THREAD

**Issue by msglifeIberia** [patternfly/patternfly-react#1722]
The `Modal` component is rendered inside 2 `pf-l-bullseye` `div`s. One `Bullseye` is enough to center the modal.
Noticed this in my snapshot testing after upgrading from `v2.1.4` to `v2.10.9`, so the 2nd `Bullseye` was introduced somewhere in that version range.
To reproduce please see https://patternfly-react.surge.sh/patternfly-4/components/modal and inspect the DOM after opening one of the modals.

**Comment by tlabaj** [comment]
Closed by #1799
