### ISSUE TITLE
PF4 docs

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#1724]
- [ ] Fix font size (html should be set to 16px so that rem units can pick it up)
- [ ] Font family should be Overpass everywhere
- [x] Some components are not rendering (LoginPage ((fixed via https://github.com/patternfly/patternfly-react/pull/1696)), Background)
- [x] Layouts should be in their own nav category (#1753)
- [ ] Layouts don't have visual borders anymore
- [ ] Dark theme toggle button is missing
- [x] Fix hot reloading on code changes
- [ ] Fix color scheme.  It is hard to read the grey on grey. (Background should be white)

Additional:
- [x] Fix per-example styles
- [x] Fix empty state centering (#1753)
- [ ] Simple context selector text too large
- [ ] Make react-live code block readable

**Comment by mcoker** [comment]
Wrapping the examples in `<pre>` tags seems to be problematic. `<pre>` applies a lot of font and white-space changes we don't want in the examples. That should also help address some of the font size issues.

**Comment by jgiardino** [comment]
This may or may not be related to this issue. When this issue is fixed, can we check the following, and capture this as an issue if it's unrelated?

I'm seeing a difference in font size for the Alert description:
![image](https://user-images.githubusercontent.com/21063328/55826807-ccfacb00-5ad6-11e9-95f3-476514408c81.png)

I only see this issue in Chrome, and it looks like Chrome is pulling the styles in twice.

**Comment by dlabaj** [comment]
Can this be broken out into separate smaller issues.  This seems like a lot for one PR.  Seems like each of the boxes should be their own issue.

**Comment by redallen** [comment]
My plan is to split up the work over multiple PRs and just reference a few checkboxes on this issue each time.

**Comment by redallen** [comment]
CSS mock for example padding
<img width="1642" alt="Screen Shot 2019-04-12 at 1 10 01 PM" src="https://user-images.githubusercontent.com/47335686/56057654-5e637a80-5d2d-11e9-98d2-d8b4ab800bcd.png">

**Comment by redallen** [comment]
Closing in favor of https://github.com/patternfly/patternfly-org/issues/1208 which will unify docs across repos.
