### ISSUE TITLE
Change all documentation to sentence case

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#1730]
In this issue we need to go through our component documentation pages of the website and change every title to sentence case. Here are three examples. 

"About Modal" should be "About modal"
"AboutModalBox" should be "About modal box"
"ApplicationLauncher Props" should be "Application launcher props"

 cc @stacymcauliffe

**Comment by tlabaj** [comment]
I just want to clarify we are not talking about the developer API docs here?  If I am looking for a component's API on a website I would expect to look for it by name of the component.  So I would expect to see AboutModal in the nav and not About Modal.
