### ISSUE TITLE
Popover: arrow not aligned

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1740]
The popover arrow does not align with the info button that launches it. Only when there is enough room will the popover center over a button.

It would be most helpful if the arrow pointed to the item providing the info.

Position left:
![Screen Shot 2019-04-09 at 5 33 59 PM](https://user-images.githubusercontent.com/17481322/55837278-e90a6680-5aee-11e9-9258-f161a62dab1b.png)

Position bottom:
![Screen Shot 2019-04-09 at 5 36 13 PM](https://user-images.githubusercontent.com/17481322/55837237-cd06c500-5aee-11e9-9321-db775a3c8fe9.png)

**Comment by boaz0** [comment]
@dlabrecq what happens when you set `enableFlip` to `true`?

**Comment by dlabrecq** [comment]
This is with enableFlip, which is why it appears on the bottom and not the top.

**Comment by martinpovolny** [comment]
I have similar issues:

![popover-arrow-2019-04-24_15-06](https://user-images.githubusercontent.com/51095/56661784-bf327180-66a2-11e9-9ca6-ce2224668207.png)

I do not see how I can make the popover look the way it's in my designs.

Ping @nlcwong

**Comment by SpyTec** [comment]
There was a fix back in August which would position the popover better, #2711. Did this solve the issues or is there anything still broken?
