### ISSUE TITLE
Tooltip and popover background colors

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1741]
Tooltips and popovers have different background colors. This is most annoying in the Cost Management UI; especially, when there are tooltips and popovers used in close proximity.

We (UI/UX) were expecting the tooltip background color to match the popup? I get the impression that this was intended for the old, dark theme? 

Is there an easy way to change the background without a bunch of overrides?

Tooltip:
![Screen Shot 2019-04-09 at 5 34 55 PM](https://user-images.githubusercontent.com/17481322/55837487-8b2a4e80-5aef-11e9-86c3-928868871fbe.png)

Popover:
![Screen Shot 2019-04-09 at 5 36 13 PM](https://user-images.githubusercontent.com/17481322/55837507-9aa99780-5aef-11e9-9a68-9263c9e3c780.png)

**Comment by jschuler** [comment]
Perhaps we should support this in core with different modifiers, @rachael-phillips

**Comment by rachael-phillips** [comment]
Thanks for tagging me @jschuler. @mceledonia what are your feelings on this? I know the dark tooltip was intentional. Do you mind explaining to us why this is the case?

**Comment by rachael-phillips** [comment]
Hi @mceledonia what are your thoughts on this issue?
