### ISSUE TITLE
Refactor Data List

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#1747]
https://github.com/patternfly/patternfly-next/pull/1695/

Added new classes to the Data List to add support and flexibility as the Data list was breaking:

`pf-c-data-list__item-row` wraps around the next three items/every item in the first row
`.pf-c-data-list__item-control` wrap around the toggle and checkbox
`.pf-c-data-list__item-content` wrap around data-cells
`pf-c-data-list__item-action` wrap around action buttons

`pf-m-no-fill` added to the data-list__cell so that it stretches to fill its parent.
`pf-m-align-right` aligns a data-list__cell to the right of its parent.
`pf-m-icon` added to data-list__cell when an icon is used inside of it

**Comment by tlabaj** [comment]
Closed by #1755
