### ISSUE TITLE
Update patternfly/react-tokens package to include the new color pallete variables from core

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#1756]
The patternfly/react-tokens package needs to be updated to include the new color pallete variables from core. The package doesn't appear to have been updated in a very long time.

cc @dlabrecq

**Comment by dlabrecq** [comment]
I've tested the react-tokens package and it should pull chart vars from patternfly-core, automatically. We just need to update the version of patternfly-core used by react-tokens.

**Comment by dlabrecq** [comment]
This can be closed. Color vars are now available in react-tokens and react-charts have been updated to use them.
