### ISSUE TITLE
PF4 Modal: cannot scroll horizontally

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1765]
When the window is resized smaller than the modal, users can scroll vertically, but not horizontally. This means that Cost Management charts get cut off.

It appears that the modal will resize itself vertically, but not horizontally?

![chrome-capture](https://user-images.githubusercontent.com/17481322/56138876-c7353780-5f65-11e9-8319-2069c3fceaae.gif)

Looking at the modal styles, it appears that overflow-x is hidden. However, even if I override that to auto/scroll, the modal refuses to scroll.

![Screen Shot 2019-04-15 at 10 00 22 AM](https://user-images.githubusercontent.com/17481322/56138868-c2708380-5f65-11e9-990f-68c910bf5d15.png)

**Comment by rachael-phillips** [comment]
@mcoker do you mind taking a look at this from the CSS perspective?

**Comment by mcoker** [comment]
@dlabrecq looks like this is related to https://github.com/patternfly/patternfly-react/pull/1799

**Comment by dlabrecq** [comment]
Ok, I'll give that a try once merged

**Comment by dlabrecq** [comment]
The modal now shrinks to a minimum width of about 490px. No horizontal scroll, but believe this will be fine. Thanks!
