### ISSUE TITLE
RCUE for PF4

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#1770]
There are  background and logos that we want to deliver for product. In the past, we have called this RCUE (Red Hat Common User Experience) as these visual assets are specific to Red Hat products. 

In this issue, we will address adding RCUE for the newest version of PF. First, we should investigate how to achieve this since this isn't a straight lift from pf3 (e.g. separate git?, separate stylesheet?, etc).

**Comment by dlabaj** [comment]
Is this updating RCUE and figuring out the CSS portion as well as consuming it in react?

**Comment by LHinson** [comment]
The latter. @dgutride can provide more background. 

That said, this is second priority to the rc.1 work and can be done after our next release.

**Comment by rachael-phillips** [comment]
Closing this issue to open in Core.
