### ISSUE TITLE
Latest packages: cards

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1774]
Installed the latest Patternfly and patternfly-react packages and the Cost Management UI is looking odd.

In this case, there is a problem with cards not stretching the entire page width.

When the Cost Management overview page loads, cards no longer stretch the width of the page. And when the page has finished loading, the cards don't always stretch fully. Sometimes a page refresh will fix that, but more often not.

While loading, cards do not fill the page:
<img width="1736" alt="SAVE2" src="https://user-images.githubusercontent.com/17481322/56166500-c8855500-5fa3-11e9-8fa1-63ad9ca30794.png">

After page loading, cards still do not fill the entire page:
<img width="1389" alt="SAVE" src="https://user-images.githubusercontent.com/17481322/56166494-c1f6dd80-5fa3-11e9-8f5c-16f314871d04.png">

Package versions:

![Screen Shot 2019-04-16 at 11 33 28 AM](https://user-images.githubusercontent.com/17481322/56224573-d1c30000-603d-11e9-90a3-e22f895dd66b.png)

**Comment by rachael-phillips** [comment]
Hi @dlabrecq would you mind breaking this issue up into three issues? 1 for cards, 1 for progress bar, and 1 for pagination padding. Thank you!

**Comment by rachael-phillips** [comment]
@mcoker are any of these CSS related?

**Comment by mcoker** [comment]
@rachael-phillips it looks like CSS and/or usage related issues. I'd like to spin that up in a local environment if possible so I can look at where the problematic code is. @dlabrecq is there a branch I can build?

**Comment by dlabrecq** [comment]
@mcoker I created a draft PR with the latest PatternFly packages.

Please let me know if you need help running the environment. Note that the URL changed to https://ci.foo.redhat.com:1337/hybrid/cost-management/

**Comment by dlabrecq** [comment]
Split this issue into 4:

@Rachael Phillips Moved other issues here:

https://github.com/patternfly/patternfly-react/issues/1779
https://github.com/patternfly/patternfly-react/issues/1778
https://github.com/patternfly/patternfly-react/issues/1777

**Comment by rachael-phillips** [comment]
Thanks @dlabrecq I see them

**Comment by mcoker** [comment]
@dlabrecq can you link me to the PR or branch name I can pull down?

**Comment by dlabrecq** [comment]
@mcoker It's https://github.com/project-koku/koku-ui/pull/758

**Comment by dlabrecq** [comment]
This is a good video of the issues I've been seeing.

![chrome-capture](https://user-images.githubusercontent.com/17481322/56243144-def4e480-6067-11e9-8fb6-8785ed0ba8f7.gif)

**Comment by dlabrecq** [comment]
This now appears to be due to https://github.com/patternfly/patternfly-react/issues/1779
