### ISSUE TITLE
PF4 Tabs shortens children elements

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#1775]
When using PF4 Tabs, the children elements are **shortened**. It causes issues when using tabs and forms together. (Maybe this is a issue for CSS team, but I do not know.)

_Example from demo_

![image](https://user-images.githubusercontent.com/32869456/56216604-05b01c80-6062-11e9-87b1-f46385b95ad4.png)

_Should be something like this_ (when I add `width: 100%` to `section` element in tabs)

![image](https://user-images.githubusercontent.com/32869456/56216917-98e95200-6062-11e9-944f-0889d3be5e4c.png)

**Code**

```javascript

import React from 'react';
import { Tabs, Tab, TabsVariant, TabContent, Form, FormGroup, TextInput } from '@patternfly/react-core';

class SimpleTabs extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      activeTabKey: 0
    };
    // Toggle currently active tab
    this.handleTabClick = (event, tabIndex) => {
      this.setState({
        activeTabKey: tabIndex
      });
    };
  }

  render() {
    return (
      <Tabs activeKey={this.state.activeTabKey} onSelect={this.handleTabClick}>
        <Tab eventKey={0} title="Tab item 1">
           <Form>
             <FormGroup label='Text'> 
                <TextInput value='saadsdsaaaasdsdsdsdsdsdsdsdsd'/>
            </FormGroup>
           </Form>
        </Tab>
        <Tab eventKey={1} title="Tab item 2">
          Tab 2 section
        </Tab>
        <Tab eventKey={2} title="Tab item 3">
          Tab 3 section
        </Tab>
      </Tabs>
    );
  }
}


```

cc @Hyperkid123

**Comment by rachael-phillips** [comment]
Thanks @rvsia for bringing this to our attention. @mcoker do you know if this is a CSS issue?
