### ISSUE TITLE
Latest PF4 packages: Chart axis font size

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1777]
Installed the latest Patternfly and patternfly-react packages and the Cost Management UI is looking odd.

In this case, the chart axis font size is much larger than before.

Seems to grow larger after the cards stretch, after the page is loaded, so could be related to https://github.com/patternfly/patternfly-react/issues/1774 Looks like that may be messing with the chart rendering?

Before:
![Screen Shot 2019-04-16 at 11 36 45 AM](https://user-images.githubusercontent.com/17481322/56223537-ef8f6580-603b-11e9-8000-6a72db64d847.png)

After:
![Screen Shot 2019-04-16 at 11 29 31 AM](https://user-images.githubusercontent.com/17481322/56223541-f322ec80-603b-11e9-915e-88135b3ad2fe.png)

Package versions:
![Screen Shot 2019-04-16 at 11 33 28 AM](https://user-images.githubusercontent.com/17481322/56223554-fa49fa80-603b-11e9-8077-31913b7fdc75.png)

**Comment by redallen** [comment]
To test this out in the latest docs, we need to readd the old css styles for svg overflow. That can now be done with a simple import at the top of the mdx file. See #1673 . Old styles [here.](https://github.com/patternfly/patternfly-react/tree/14e4cd324ddad696fe0c29825225952273573482/packages/patternfly-4/react-charts/src/components/AreaChart/examples/common)

**Comment by dlabrecq** [comment]
This now appears due to https://github.com/patternfly/patternfly-react/issues/1779.
