### ISSUE TITLE
Latest PF4 packages: tab content

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1779]
Installed the latest Patternfly and patternfly-react packages and the Cost Management UI is looking odd.

In this case, there is a problem with the tab content.

When the page is loaded, progress bars do not expand the entire width of the card body as expected. As a result, our Insights skeletons and PF progress bars no longer stretch the entire width.

It appears there is an issue with the `select` element output by the tabs component? I can override that to 100% and the progress bars fill the card.

Note that this also affects our use of Insights skeleton components. The skeletons look fine in other areas -- seems to be just an issue with the tabs?

Progress bars before:
![Screen Shot 2019-04-16 at 11 42 42 AM](https://user-images.githubusercontent.com/17481322/56223966-c3c0af80-603c-11e9-98f6-b7798ce49cfa.png)

Progress bars after:
<img width="1389" alt="SAVE" src="https://user-images.githubusercontent.com/17481322/56166494-c1f6dd80-5fa3-11e9-8f5c-16f314871d04.png">

Skeletons before:
![Screen Shot 2019-04-16 at 11 46 42 AM](https://user-images.githubusercontent.com/17481322/56224287-5e20f300-603d-11e9-802b-3984c207c474.png)

Skeletons after:
<img width="1165" alt="Screen Shot 2019-04-15 at 5 28 40 PM (2)" src="https://user-images.githubusercontent.com/17481322/56166732-582b0380-5fa4-11e9-8552-9e9b41d26f1c.png">

**Comment by tlabaj** [comment]
@dlabrecq are you using the TabContent Outside of the tabs here?

**Comment by mcoker** [comment]
@tlabaj looks like this is the same issue as https://github.com/patternfly/patternfly-react/issues/1775

**Comment by dlabrecq** [comment]
I'm not using TabContent here, just Tabs and Tab.

**Comment by mcoker** [comment]
@tlabaj looking at the old implementation of tabs, the tab content sections are outside of the tabs component parent. With Dan's latest updates, the tab content sections are now inside of the tabs. Do you know when and why that changed? I'm curious if I need to provide a CSS fix or if this is something we can sort out in the react component.

<img width="1291" alt="Screen Shot 2019-04-16 at 4 38 38 PM" src="https://user-images.githubusercontent.com/35148959/56245959-4ad64d80-6066-11e9-95ea-769100b287db.png">

**Comment by tlabaj** [comment]
@mcoker  It probably changed with the refactoring for the TabContent outside of Tabs. . I can make that change so it is outside of the tabs again.
