### ISSUE TITLE
Component : Tree View

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#178]
Provide implementation for the [PatternFly TreeView](http://www.patternfly.org/pattern-library/widgets/#bootstrap-tree-view) 

Need to clarify the amount of work is in scope for this Issue - it's very basic functionality, for the initial feature.  We should be able to follow up with incremental functionality as needed.

Test page for the PF core implementation can be found here for comparison: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-treeview-2.html

Include story examples demonstrating these features in a mock application scenario

**Comment by ohadlevy** [comment]
wasn't this done via #196? can we close it?

**Comment by priley86** [comment]
yes - we already consumed it and merged it. I will close this and i've opened #321 for anything else remaining...
