### ISSUE TITLE
Latest packages: perPageSuffix not recognized TS error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1784]
Installed the latest Patternfly and patternfly-react packages and the Cost Management UI is now generating the following message.

This appears to be generated by the pagination component.

<img width="1180" alt="Screen Shot 2019-04-16 at 8 35 24 PM" src="https://user-images.githubusercontent.com/17481322/56253445-5c315100-608a-11e9-8490-c08171e0754b.png">

**Comment by karangarg45** [comment]
Facing the same issue in my app.
This line seems to be causing the issue. Need to take perPageSuffix prop out before spreading the restProps on the div.
https://github.com/patternfly/patternfly-react/blob/a0ff240677a3e4cd9989102805c0f45a5a079841/packages/patternfly-4/react-core/src/components/Pagination/OptionsMenu.js#L98

**Comment by boaz0** [comment]
Yes, that's probably my fault. Can I fix this?
