### ISSUE TITLE
PF4. Bug I can't use Checkbox Select Input

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#1785]
Component CheckboxSelectOption Is not exported

Storybook : http://patternfly-react.surge.sh/patternfly-4/components/select/

Version 2.11.0

Select component in node_modules has selectConstants,SelectOption,SelectToggle and SingleSelect but not this component need it to create the example of Checkbox Select Input

cc @priley86

**Comment by kmcfaul** [comment]
I tested versions in a local blank react project, and found that CheckboxSelect is not in the 2.11.0 release. CheckboxSelect is included in the 2.11.1 release, but there is a different import issue with a css class. The following release, 3.1.1, fixes that second import error and is a stable release to use Checkbox Select.

**Comment by dlabaj** [comment]
Updated release notes here: https://github.com/patternfly/patternfly-react/releases/tag/%40patternfly%2Freact-core%403.1.3

Please use 3.1.3 or above.

**Comment by aljesusg** [comment]
Great Thanks

**Comment by aljesusg** [comment]
Hi the version 3.1.1 breaks styles in our actual version, do you know id there is any change there?

## before
![before](https://user-images.githubusercontent.com/3019213/56305707-04095600-6141-11e9-8251-58f356b430c3.png)

## after
![after](https://user-images.githubusercontent.com/3019213/56305705-04095600-6141-11e9-96a4-db1b774eb2ca.png)

**Comment by mcoker** [comment]
@aljesusg we changed which elements in the login page use a dark and light theme (https://github.com/patternfly/patternfly-next/pull/1685/files), but I wouldn't expect it to cause the issue above. In your screenshot, it looks like there is an issue with the entire login container, as it's flush left with the window viewport. Do you have custom CSS overriding any of those sections that might need to be updated? And is there a way I can look at the broken page and try to help debug?

**Comment by aljesusg** [comment]
We have the same override that the openshift console with additional css to fix the styles between pf3 components and pf4 components until we migrate all the app :(, I need to check what happens before upgrade :( Thanks

**Comment by mcoker** [comment]
@aljesusg ok, let me know if I can help out in any way.
