### ISSUE TITLE
PF4: ReactStyles issue with css

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#1795]
Many of the JEST tests are failing in Cost Management with the latest PatternFly packages. We've updated our snapshots, but still have 25 failing tests. For example:

![Screen Shot 2019-04-17 at 11 10 12 AM](https://user-images.githubusercontent.com/17481322/56301613-321d7480-6106-11e9-9c39-40b3202d09b9.png)

Seems to happen for any test that imports:

`import { css } from '@patternfly/react-styles';`

![Screen Shot 2019-04-17 at 11 46 30 AM](https://user-images.githubusercontent.com/17481322/56301770-7a3c9700-6106-11e9-8da9-af662fdfa4a8.png)

Could be an issue for the Cost Management UI to solve, but we haven't made any changes to our tests. Still investigating with the UI to see if there's something we need to do on our end, but want to start tracking the issue.

**Comment by dlabrecq** [comment]
A draft PR with the latest packages can be found here: https://github.com/project-koku/koku-ui/pull/758

**Comment by dlabrecq** [comment]
Added the following to jest.config.ts and all appears to be well now.

```
moduleNameMapper: {
  '\\.(css|less)$': '<rootDir>/test/styleMock.js',
},
```

**Comment by dgutride** [comment]
Need to add this to our release notes, just in case...
