### ISSUE TITLE
Component - Label

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#18]
Implement a component that provides the following UI element:

- [PatternFly Label](http://www.patternfly.org/pattern-library/widgets/#labels)

Acceptance Criteria:

- When rendered, the component matches the examples in the PatternFly Pattern Library (see link above)
- the component supports:
  - color variations as shown in the PatternFly library

**Comment by priley86** [comment]
cc: @dabeng maybe this another easy one to tackle? I am not sure what your current sprint looks like, but if you can slide it in, it would be helpful!

cc: @LHinson

**Comment by priley86** [comment]
Pretty please also update any existing `<label>` JSX to use the new <Label> once done...

**Comment by dabeng** [comment]
Hi @priley86 , you said that you wanna update all existing <label> tags with new Label component. Is the following screenshot your expected result?

<img width="1600" alt="screen shot 2017-12-13 at 1 10 19 pm" src="https://user-images.githubusercontent.com/5689075/33922741-c1bedc36-e007-11e7-9e2e-2906961720a6.png">

<img width="1600" alt="screen shot 2017-12-13 at 1 10 24 pm" src="https://user-images.githubusercontent.com/5689075/33922744-c7ac9354-e007-11e7-8f84-99d45e2f7964.png">

**Comment by priley86** [comment]
thanks @dabeng, this is exactly what I was hoping to find ;)  I think we should ensure the `Label` can be flexible enough to support all labels... React Bootstrap should accept `className` but I have not tested it.

**Comment by jgiardino** [comment]
I think what @priley86 meant was to find any instances of '`<span class="label label-`' and to replace those with the new `<Label>` component. 

These are different elements than the `<label>` elements that are used in the modal and wizard components, which should not be replaced with the `<Label>` component.

**Comment by priley86** [comment]
Ahh good distinction. I would propose we create a new component then as these are fairly common... I guess bigger question I have then is, why do our forms in PF Core use <span>s as opposed to <label>s ?

**Comment by jgiardino** [comment]
Oh, I think I may have misread @priley86's comments.

The `<Label >` component results in the following runtime html:
`<span class="label label-default">Default</span>`

This html is nothing like what we should be using within forms. While they share the same name, I would argue that is just a naming convention provided by Bootstrap, and is not meant to suggest that `<span class="label label-default">Default</span>` should be used as a label for a form field. Additionally, bootstrap doesn't even use their Label component within forms, as shown in [this example](https://getbootstrap.com/docs/3.3/css/#forms):
```
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  ...
```

For forms, I would expect forms us to provide a different set of components, possibly using what [react-bootstrap has implemented for Forms](https://react-bootstrap.github.io/components.html#forms), and that `<Label>` would only be used to implement what [Bootstrap has defined for Labels](https://getbootstrap.com/docs/3.3/components/#labels).

**Comment by jgiardino** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/4a148723-fbbf-4972-8e6e-120148c5a497-a07a3b9e-da41-4f2c-af4f-5c7d9c4da655-v1.png?transparent=1&palette=1&width=123)
Oh, Bootstrap! This is quite confusing given their use of 'label' as a name for text that has a color behind it.

**Comment by priley86** [comment]
thanks @jgiardino 👍  . This clarifies it. We can rebase those examples once we have `ControlLabel` added.
