### ISSUE TITLE
Add padding props to page main section

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1802]
* `.pf-m-no-padding` - removes padding from main section - https://github.com/patternfly/patternfly-next/pull/1733

* `.pf-m-no-padding-mobile` - removes padding when the page layout breaks to the mobile view - https://github.com/patternfly/patternfly-next/pull/1497

**Comment by dlabaj** [comment]
Are these always added together or you can choose to add one and not the other.

**Comment by mcoker** [comment]
You can choose one or the other.

**Comment by dgutride** [comment]
Closed via https://github.com/patternfly/patternfly-react/pull/1818
