### ISSUE TITLE
Kebab menu placement is off 

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#181]
The kebab menu placement in the storybook is a bit off
https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Right%20aligned=false&selectedKind=DropdownKebab&selectedStory=DropdownKebab&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

The arrow should be pointing at the kebab

FYI, the PF core test page works as expected : https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/dropdowns.html

**Comment by jeff-phillips-18** [comment]
This is due to `Dropdown` adding the `btn-group` class to the kebab.

`<div class="dropdown-kebab-pf dropdown open btn-group"`

which adds styling to the kebab button:

`.btn-group > .btn:first-child {
    margin-left: 0;
}`

**Comment by jeff-phillips-18** [comment]
Looks like this would be fixed by https://github.com/patternfly/patternfly/pull/835

**Comment by jgiardino** [comment]
Yes
@jeff-phillips-18 would you have time to review that one so that it can get merged?

**Comment by jeff-phillips-18** [comment]
Fixed by upgrading to Patternfly 3.37.6
