### ISSUE TITLE
PF4: Select is opening when the user keyPress Enter

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#1815]
It seems that onToggle method is returning true when the user keypress the EnterKey, so in Kiali when the user is pressing the Enter key in a form the Select open instead sent the form.

**Comment by aljesusg** [comment]
This is a blocker for us we must fix this or return to pf3 component
## Behaviour
![select](https://user-images.githubusercontent.com/3019213/56565519-dee96d00-65b0-11e9-89d4-34e6b0103843.gif)

The problem is that there is a focus in event.key Enter
```js
_defineProperty(_assertThisInitialized(_this), "onEscPress", function (event) {
      var _this$props2 = _this.props,
          parentRef = _this$props2.parentRef,
          isExpanded = _this$props2.isExpanded,
          onToggle = _this$props2.onToggle,
          onClose = _this$props2.onClose;
      if (!isExpanded && event.key === KeyTypes.Enter) _this.toggle.focus();

      if (isExpanded && (event.key === KeyTypes.Escape || event.key === KeyTypes.Tab) && parentRef && parentRef.contains(event.target)) {
        onToggle && onToggle(false);
        onClose && onClose();

        _this.toggle.focus();
      }
    });
```

cc @priley86

**Comment by kmcfaul** [comment]
`if (!isExpanded && event.key === KeyTypes.Enter) _this.toggle.focus();`

@aljesusg This problematic focus call has been removed in later builds. Please try running version 3.1.3 or above and let me know if the issue persists.
