### ISSUE TITLE
PF4 chart axis ticks and labels overflow parent

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#1819]
Chart axis tick labels are rendered outside of the parent on the left and bottom. This can be seen in the line and bar chart examples. Created similar vanilla victory charts in OpenShift and the labels were rendered correctly inside the parent element. 

## With PF React Charts
```jsx
<Chart>
  <ChartArea data={data} />
</Chart>
```
![image](https://user-images.githubusercontent.com/22625502/56509107-134b2380-64f4-11e9-9665-d9bcfebd47b0.png)

## With Victory
```jsx
<VictoryChart>
  <VictoryArea data={data} />
</VictoryChart>
```
![image](https://user-images.githubusercontent.com/22625502/56509167-47bedf80-64f4-11e9-8c54-c16ff3840f43.png)

**Comment by dlabrecq** [comment]
I believe this can be closed now.
