### ISSUE TITLE
Component : Progress Bars

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#182]
Provide implementation for the PatternFly [Progress Bars](http://www.patternfly.org/pattern-library/widgets/#progress-bars)

Test page for the PF core implementation can be found here for comparison: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/progress-bars.html

Include story examples demonstrating this features in a mock application scenario

**Comment by ZitaNemeckova** [comment]
@serenamarie125 can you please assign it to me? Thanks :)

**Comment by ZitaNemeckova** [comment]
https://github.com/patternfly/patternfly-react/pull/188

**Comment by sharvit** [comment]
Closed since introduced in version [1.4.0](https://github.com/patternfly/patternfly-react/releases/tag/v1.4.0)
thanks @ZitaNemeckova :+1:
