### ISSUE TITLE
Component : Slider

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#183]
Provide implementation for the [PatternFly Slider](http://www.patternfly.org/pattern-library/forms-and-controls/slider/)

Test page for the PF core implementation can be found here for comparison: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-slider.html?

Include story examples demonstrating this features in a mock application scenario

**Comment by dabeng** [comment]
Hi @serenamarie125 . I made a **[Demo](https://rawgit.com/dabeng/patternfly/slider-dist/dist/tests/bootstrap-slider.html)** to implement the expected behavior described on design doc of patternfy.org.

**Comment by laviro** [comment]
Working on this issue
