### ISSUE TITLE
Add support for dropping columns in the Table

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1832]
https://github.com/patternfly/patternfly-next/pull/1748

> | `.pf-m-hidden{-on-[breakpoint]}` | `.pf-c-table tr > *` | Hides a table cell at a given breakpoint, or hides it at all breakpoints with `.pf-m-hidden`. **Note: Needs to apply to all cells in the column you want to hide.** |
> | `.pf-m-visible{-on-[breakpoint]}` | `.pf-c-table tr > *` | Shows a table cell at a given breakpoint. |

This works with any of our global breakpoints. So you can use `.pf-m-hidden, .pf-m-hidden-on-[sm, md, lg, xl]` and the same for `visible`. You can use multiple classes on a single cell, too. For example `.pf-m-hidden` to hide the cell by default, then `.pf-m-visible-on-sm` to show it on `sm`, then `.pf-m-hide-on-md` to hide on `md`, and so on.

I suppose you should be able to add this to any cell in your table, as well as potentially supporting some way to say "hide the 3rd column on md breakpoint" and the react component applies the appropriate class to all the cells in that column?

**Comment by priley86** [comment]
i think this can probably work similarly to our `cellWidth()` transform (which just applies a class to a column and each column cell). In this case, it would be a set of classes, so I propose we add a `visiblility()` transform to make this more explicit. We could also expose these visibility classes as constants from react-styles to make them easier to digest from React/Typescript. So I could see an API like this downstream:
```
class HideShowTable extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      columns: [
        'Branches',
        {
           title: 'Pull requests', 
           transforms: [visiblility(hiddenOnMd, visibleOnLg)] 
        },
        'Workspaces',
        {
          title: 'Last Commit',
          transforms: [visiblility(hidden, visibleOnSm)]
        }
      ],
      rows: [['10', 'Hidden only on md breakpoint', '5', 'Hidden on xs breakpoint']]
    };
  }

**Comment by priley86** [comment]
fwiw...this is possible today, just more effort on the consumer...

```
class HideShowTable extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      columns: [
        'Branches',
        {
           title: 'Pull requests', 
           props: { className: 'pf-m-hidden-on-md pf-m-visible-on-lg'}
        },
        'Workspaces',
        {
          title: 'Last Commit',
          props: { className: 'pf-m-hidden pf-m-visible-on-sm'}
        }
      ],
      rows: [[
        '10', 
        {title: 'Hidden only on md breakpoint', props: {  className: 'pf-m-hidden-on-md pf-m-visible-on-lg'}},
        '5', 
        {title: 'Hidden on xs breakpoint', props: { className: 'pf-m-hidden pf-m-visible-on-sm'}}
     ]]
    };
  }
```
