### ISSUE TITLE
TS errors in ClipboardCopy

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#1834]
When importing latest `@patternfly/react-core` I'm met with errors for ClipboardCopy component. 

<img width="1353" alt="Screen Shot 2019-04-23 at 1 09 36 PM" src="https://user-images.githubusercontent.com/5942899/56602653-fa15a600-65cb-11e9-84b9-e34f305eeab5.png">

**Comment by boaz0** [comment]
@dgutride I think this will fix it:

replacing:
```js
import { FunctionComponent, HTMLProps, MouseEvent, ReactNode, HTMLDivElement } from 'react';
```
with 
```js
import { FunctionComponent, HTMLProps, MouseEvent, ReactNode } from 'react';
```

and
```js
import { OneOf } from '../../typeUtils';
```
with
```js
import { OneOf } from '../../helpers/typeUtils';
```
 
and
```js
export const ClipboardCopyVariant = {
```
with
```js
export const ClipboardCopyVariant: {
```

**Comment by dgutride** [comment]
Should be fixed now.
