### ISSUE TITLE
Component : Application Launcher

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#184]
Provide implementation for the [PatternFly Application Launder](http://www.patternfly.org/pattern-library/application-framework/launcher/)

Test page for the PF core implementation can be found here for comparison: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/application-launcher.html

Include story examples demonstrating this features in a mock application scenario

**Comment by samvarankashyap** [comment]
@dgutride @serenamarie125 I was wondering if i can get a status of the launcher component. I am currently working on a User interface project and would like to add this component. Thank you.

**Comment by gilad215** [comment]
Talked to @dgutride, i'll take it from here.

**Comment by serenamarie125** [comment]
@gilad215 this is great that you are continuing with all these contributions!  Thank you
Our design documentation is here: http://www.patternfly.org/pattern-library/application-framework/launcher/#overview and there already is Core code that exists.
