### ISSUE TITLE
Wizard state not resetting on close

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-react#1845]
Can we add a function to reset the wizard state? When closing the wizard & reopening, the same step I am on when I initially closed the wizard is shown.

**Comment by boaz0** [comment]
@ibolton336 I believe you can do that using `onNext`, `onBack` and `onSave`.
Please review #1847 to let me know if that's what you meant.
Moreover, feel free to add other use cases that I didn't mention and you need.

**Comment by ibolton336** [comment]
Spoke with @redallen re: this issue yesterday. 
he suggested that instead of:
```
 /** The step to start the wizard at (1 or higher) */
  startAtStep?: number;

```
we should use: 
```
curStep?: number;
```

**Comment by tlabaj** [comment]
@ibolton336 @redallen we are not at a point to introduce a breaking change to the API. For now maybe we can update the comment to be more clear.
@boaz0 can you update the comment for the startAtStep prop in your PR?

**Comment by dlabaj** [comment]
Agree we should just change the comment if it's confusing.  We can't change the api at the moment.  We could put a request in for the next breaking change release to do this if we feel strongly.

**Comment by ibolton336** [comment]
![wizard-bug](https://user-images.githubusercontent.com/11218376/56930738-cb0ba280-6aab-11e9-91a1-2441d457ad0c.gif)

**Comment by redallen** [comment]
I feel strongly we should be able to programmatically control the step beyond just what step it starts at. Outside sources (like API calls) should be able to set the step forwards or backwards more than a single step as well.

**Comment by dlabaj** [comment]
There's still an issue with it not removing the wizard from the DOM when it's closed.  It can be seen in our demo app.

**Comment by dlabaj** [comment]
Change to a P1 for the remaining issue, since there is some time to allow for a fix.

**Comment by ibolton336** [comment]
Any ideas for a temporary fix?

**Comment by ibolton336** [comment]
![wizardBug](https://user-images.githubusercontent.com/11218376/58840696-a9668380-8634-11e9-94bf-310c79af760d.gif)

**Comment by ibolton336** [comment]
Found the issue - I was not wrapping the component in isOpen boolean. Should make it clear in the docs that you need to wrap the component in isOpen in addition to having an isOpen prop on the component itself to avoid this bug.
