### ISSUE TITLE
ApplicationLauncher Toggle defines incorrect ARIA prop

### ISSUE THREAD

**Issue by TimoSta** [patternfly/patternfly-react#1846]
The toggle in the `ApplicationLauncher` component [currently receives a prop `ariaHasPopup`](https://github.com/patternfly/patternfly-react/blob/202490c44ef7a5df4a805a0203386926870512a6/packages/patternfly-4/react-core/src/components/ApplicationLauncher/ApplicationLauncher.js#L81), which does not follow [React's naming conventions for ARIA attributes](https://reactjs.org/docs/accessibility.html#wai-aria). It should instead be set as `aria-haspopup`.

At runtime, this results in the following warning:

![image](https://user-images.githubusercontent.com/5621996/56693284-13911d80-66b2-11e9-90a1-fe8fc04efa24.png)

**Comment by dgutride** [comment]
Fixed via https://github.com/patternfly/patternfly-react/pull/1880
