### ISSUE TITLE
Add support for alerts in About Modal

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-react#1853]
I'm seeing a padding/styling issue when I use Alert inside an AboutModal:
<img width="1214" alt="Screen Shot 2019-04-23 at 4 30 30 PM" src="https://user-images.githubusercontent.com/7014965/56745636-bc8a5780-6748-11e9-9583-a288d18bc802.png">

It's caused by .pf-c-content targeting the h4s. We need to use Alert like this in OpenShift.

I discussed this with patternfly-next in https://github.com/patternfly/patternfly-next/issues/1754. They suggest the easiest way to fix this is let the user specify whether they want their content wrapped in a .pf-c-content component. Right now the React About Modal puts children into a content component automatically.

**Comment by dgutride** [comment]
Seems like a reasonable change to me - let's see if we can get this done in time for RC.1 if @mcarrano is ok with the design.

**Comment by mcarrano** [comment]
I am fine with this. It basically allows for more content flexibility in the About dialog. Could be an alert or anything else we want to put in here.
