### ISSUE TITLE
Add support for nodes in Alert title

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-react#1854]
We want to pass a React.Fragment containing text and a  Link component to an Alert title prop in OpenShift, but we're getting a Typescript warning. Title only accepts strings. I'd like to open the type up to accommodate this.

Example usage (padding issue being addressed separately in #1853):
<img width="1214" alt="Screen Shot 2019-04-23 at 4 30 30 PM" src="https://user-images.githubusercontent.com/7014965/56746402-1f302300-674a-11e9-8098-5b99f377ed9f.png">

**Comment by dgutride** [comment]
Seems like a good bug fix for Rc1
