### ISSUE TITLE
ChipGroup should allow a variable number of chips to be displayed

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#1855]
The ChipGroup component was designed to group a set of chips to be displayed together and handle potential overflow situations. Looks like as currently implemented, the group is implemented to display a fixed number of chips before hiding additional chips by collapsing the group and exposing a "more" button. This became evident when reviewing the type ahead select (ref https://github.com/patternfly/patternfly-react/pull/1839) and seeing that the list of selections is collapsed even when there is plenty of space to display them.

This should be changed to allow the consumer of this component to either pass in a number of chips to display or choose to make that flexible and calculated based on the width of the group's container. The desired behavior is for the ChipGroup to only collapse the group when there would not be enough space to display all elements without wrapping.

**Comment by mcarrano** [comment]
@dgutride @LHinson FYI

**Comment by jlmitch5** [comment]
We could use this on Tower/AWX.

The other thing we could use is a total count of chips prop and a callback prop on when "see more" is clicked.

We have a few lists where our api for the overall list gives us the first 5 labels (which we would display as chips) as a summary field, as well as the total amount of labels.  When "see more" is clicked, we would make an additional additional request to the detail view of that particular item in the list to get the rest of the labels.

**Comment by dlabaj** [comment]
@mcarrano Can you add a link to the core issue?

**Comment by tlabaj** [comment]
Depends on core issue [#1837](https://github.com/patternfly/patternfly-next/issues/1837)

**Comment by mcarrano** [comment]
Based on an Aug 8 meeting with @tlabaj and @mcoker we should move forward with this fix and allow the consumer to pass a threshold value to control the number of chips to display before exposing the overflow. Make the default = 3.

**Comment by rachael-phillips** [comment]
Hi @mcarrano thank you for the update! We will still wait until #1837 is closed before picking up this issue, correct?

**Comment by rachael-phillips** [comment]
Closing this because it was resolved in #2495
