### ISSUE TITLE
Component - Inline edit

### ISSUE THREAD

**Issue by tstrachota** [patternfly/patternfly-react#187]
Implementation of inline editing in forms, tables and list view:
http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/

Patternfly currently contains only design of inline edits so the styles will most likely need to be implemented prior to adding the components.

**Comment by jeff-phillips-18** [comment]
Thank you for using the project board! :1st_place_medal:

**Comment by jgiardino** [comment]
+1 for using the project board!

@tstrachota Another option is to add the css in patternfly-react first since this implementation doesn't exist in core, and then we can create a separate issue to add the css to patternfly core. Just keep in mind that any css we add to patternfly-react should follow the [patternfly coding guide](http://codeguide.patternfly.org/).

**Comment by dabeng** [comment]
@jgiardino Great idea. Recently I focused on "inline edit on form". It involves five types of existing patternfly widgets, so rate of progress is a little slower than developing common widgets.

**Comment by tstrachota** [comment]
https://github.com/patternfly/patternfly-react/pull/240

**Comment by dabeng** [comment]
Additional Information:
1. All the components used in "inline-edit in a form" are existing components listed in patrernfly library section of patternfly.org;

2. Currently, "inline-edit in a form" pattern includes 6 types of input field - enhanced text box, enhanced textarea, simple  single select of bootstrap select, multiple select of bootstrap select, bootstrap combobox, bootstrap datepicker;

3. <img width="18" alt="screen shot 2018-02-26 at 10 37 46 am" src="https://user-images.githubusercontent.com/5689075/36652248-90862612-1ae8-11e8-8b87-9774dcbce8f7.png"> spinner is used to mock async operations in common scenarios, e.g. submitting updated results via ajax after users complete their inline-edit;

4. IMO, "inline-edit in a form" shouldn't be entirely responsible for all sorts of form validation. Moreover, we have ["Errors and Validation"](http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/) design already. Although not comprehensive and detailed, "Errors and Validation" is indispensable part for patternfly;

**Comment by ohadlevy** [comment]
closed via #240
