### ISSUE TITLE
CSS not loading properly after upgrading to latest version 3.2.6

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-react#1878]
<img width="826" alt="Screen Shot 2019-04-29 at 11 39 19 AM" src="https://user-images.githubusercontent.com/11218376/56912114-946a6380-6a7c-11e9-8f5e-31c881d79870.png">

**Comment by aljesusg** [comment]
We found the same issue

change the css load @patternfly/react-core/dist/styles/base.css'; to @patternfly/patternfly/patternfly.css';

**Comment by ibolton336** [comment]
After examining closer with @mcoker , it appears that loading the base.css in the index.tsx portion of my app was causing the issue. Loading the base.css within the index.html file as a standard <link rel="stylesheet" src="../node_modules/patternfly/base.css" ></link> include seemed to fix the majority of the issues.

**Comment by aljesusg** [comment]
Replace that line with 
```html
<link rel="stylesheet" src="../node_modules/patternfly/patternfly.css" ></link>
```

**Comment by ibolton336** [comment]
@aljesusg Thanks! Did end up trying this also but didn't really see a noticeable difference in my case. In any event, there is a bug with the css load order when importing the base.css as it has been done up until 3.x.x

**Comment by dgutride** [comment]
@ibolton336  - closing as the CSS needs to be loaded in the correct order to work.  Please contact me offline if you think this is something PF needs to address differently in documentation, etc.

**Comment by rh-kgarg** [comment]
@ibolton336 i am also facing the same problem with Webpack 4. Were you able to figure out a solution for this?

**Comment by rh-kgarg** [comment]
@ibolton336 NVM. Solved it by just moving the `import '@patternfly/react-core/dist/styles/base.css';` at top of my index.tsx file.
