### ISSUE TITLE
Add auto-complete component

### ISSUE THREAD

**Issue by danseethaler** [patternfly/patternfly-react#189]
I wanted to start a discussion about adding an auto-complete component to patternfly-react. I understand there isn't an official specification for this in the patternfly core but it's a common component that we may want to support. I started building one in Foreman using the downshift library and I thought it would be worth submitting here for discussion. You can check it out on [this storybook](https://rawgit.com/danseethaler/patternfly-react/autocomplete-component-storybook/index.html?selectedKind=AutoComplete&selectedStory=AutoComplete&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).

Here's a quick example:

![autocomplete](https://user-images.githubusercontent.com/11202705/35449032-df1deda4-0289-11e8-9048-3667d562a83a.gif)

The auto-complete component should:
- Allow user to type anything in the input field (doesn't have to match a dropdown item)
- Set the input field to the dropdown item value when selected
- Trigger callbacks to the outer component when the input value changes (so new options can be rendered) and when the search is executed

I'm sure there is a lot more to discuss but I wanted to submit this to get the conversation going. You can see the code for this component at https://github.com/danseethaler/patternfly-react/commit/2e58e140cdcfcd4438e56f75872feab9a0f69906

**Comment by priley86** [comment]
Wonderful! I am a big proponent of this library as it has a very flexible js api surface and exposes primitives capable of any CSS.

Maybe we can do some design/a11y review next?

Great job...

**Comment by danseethaler** [comment]
Thanks @priley86! Yeah downshift is really terrific and handles a lot of the a11y without much effort on our part. I'm happy to submit a PR if it's easier to review the code that way or if we want to have some more design discussions first we could do that here.

There are a couple of features I haven't implemented yet that I think we'll need.

1. we probably want the component to accept an array of objects instead of strings so we can support disabled items, dividers, etc.
2. it would be nice if hitting the `tab` key when an item was highlighted would select the item and update the text input
3. also it would be nice if hitting `enter` would execute the search/submit if no item is highlighted.

cc: @jgiardino

**Comment by jgiardino** [comment]
This looks like a really nice feature to add! I haven't seen anything in patternfly that addresses auto-complete. I'm adding @maryclarke and @mcarrano just to loop them in on this (and point us to any existing documentation, if any).

I'm always in favor of pushing something just to facilitate review and discussion.

As for keyboard interaction, my preference is to follow what bootstrap 3 has as closely as possible. In this case, I think the [button dropdown](https://getbootstrap.com/docs/3.3/components/#btn-dropdowns) provides a pattern that we could follow:
- bot the Tab and Up/Down arrow keys will select a menu item
- Esc will dismiss the menu, and do nothing
- I also agree that Enter will execute the selected item

It's worth noting though that our own [button dropdown](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Style=default&selectedKind=Button&selectedStory=DropdownButton&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) is not consistent with the original bootstrap pattern (and maybe we're limited to how react bootstrap has implemented this?). In pf-react/react-bootstrap implementation, Tab will not navigate to the next menu item—only the arrow keys will work.

**Comment by mcarrano** [comment]
I do like the idea of having an auto-complete component in PatternFly core. Adding @andresgalante and @LHinson to the conversation. Not sure what it would mean to add this from a core CSS standpoint. Thoughts?

**Comment by danseethaler** [comment]
Great feedback @jgiardino. I've created a PR to make the code review easier and added support for headers, dividers, and disabled items.

I've also done some work to enable handling the enter/tab key. I agree with everything you said except I think it may make sense to change the functionality of the tab key. Since this is an autocomplete feature instead of a dropdown button it feels really natural to have the tab key select the currently highlighted item so you can keep typing. Try out the updated storybook (link at top) and see what you think.

**Comment by danseethaler** [comment]
Thanks for pointing out the core CSS implications @mcarrano. The only custom style in this implementation is for the dropdown container [here](https://github.com/patternfly/patternfly-react/pull/190/files#diff-5a2174c8709569017a7fd55ef8c3bcf1R13) so hopefully fairly easy to determine how to handle.

**Comment by jgiardino** [comment]
I checked out the storybook. I agree with you about the key commands, @danseethaler. After playing around with the control, I think what you have works really well.

**Comment by priley86** [comment]
another thing I really <3 about this upstream project is it's being contributed to by one of the lead a11y experts in our field, Marcy Sutton. I know her through a friend of a friend leading a local Girl Develop It chapter - it might be worth reaching out and saying "hi" @jgiardino  😸 

https://marcysutton.com/about/

**Comment by dabeng** [comment]
This recommend was also put forward on patternfly repo before - [typeahead or autocomplete is very popular plugin which should be introduced into patternfly](https://github.com/patternfly/patternfly/issues/332)
