### ISSUE TITLE
Dropdowns are not show fully

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#1910]
http://patternfly-react.surge.sh/patternfly-4/components/contextselector/
![Screenshot_20190502_135555](https://user-images.githubusercontent.com/1011257/57073693-13140a80-6ce2-11e9-9da6-724559a7c899.png)

@patternfly/react-core: 3.16.9

@patternfly/react-table: 2.5.10

@patternfly/react-charts: 3.4.2

@patternfly/react-tokens: 2.5.1

@patternfly/react-styled-system: 3.4.1

@patternfly/react-inline-edit-extension: 2.3.21

**Comment by tlabaj** [comment]
Closing this since it is no longer an issue in the latest version of react-core
