### ISSUE TITLE
DataList examples unclear

### ISSUE THREAD

**Issue by ibolton336** [patternfly/patternfly-react#1913]
When attempting to refactor my DataList component, I am not sure what to remove/ what to add to my component. There are unused imports in the Simple DataList example that should be removed for clarity:
<img width="669" alt="Screen Shot 2019-05-02 at 12 40 23 PM" src="https://user-images.githubusercontent.com/11218376/57091643-a8f66800-6cd7-11e9-94fc-00cb413f6bb4.png">

**Comment by rachael-phillips** [comment]
@ibolton336 is this issue blocking implementation for you?

**Comment by ibolton336** [comment]
@rachael-phillips no not at this time.
