### ISSUE TITLE
Wizard Component Props should extend the correct React HTMLProp

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#1916]
The Wizard Component exported interfaces should extend the correct HTMLProp.

**Comment by dgutride** [comment]
@tlabaj  - is this the reason there are no properties in the wizard documentation?  If so, I'm going to recommend we put this at p0 since missing documentation will block a consumer from effectively using the component.

**Comment by boaz0** [comment]
@tlabaj can you assign it to me? :grinning:
