### ISSUE TITLE
Component - Base Card

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#192]
Create the [base component Card](http://www.patternfly.org/pattern-library/cards/base-card/
) 

This will be the base for the following components:
[Aggregate Status Cards](http://www.patternfly.org/patter

- n-library/cards/aggregate-status-card/) #206 
- [Trend Card](http://www.patternfly.org/pattern-library/cards/trend-card/) #207 
- [Utilization Bar Card](http://www.patternfly.org/pattern-library/cards/utilization-trend-card/) #208 

Dev Notes:
Ideally - we can also provide some simple helpers on top of the core Card components to ensure cards have the same height in a dashboard visualization. I have written an example of this using [React Equalizer](https://github.com/patrickgalbraith/react-equalizer) as opposed to jquery-match-height. Reach out if you'd like any help w/ this.

**Comment by gilad215** [comment]
I would like to work on this issue

**Comment by priley86** [comment]
Hello @gilad215 - i think we should break down these components into their smaller elements as much as is feasible (i.e. these JSX class components typically follow the `class` referenced in the div's). So yes - I would propose breaking down Heading, Title, Body, etc. We will need to ensure the base jsx elements created can be used alongside each of the Card variations where necessary (so feel free to demonstrate what you can with this issue as a starting point). 

We have some other downstream issues hanging on this now so appreciate your work!

**Comment by serenamarie125** [comment]
@priley86 I'd suggest that we change the scope of this issue to be focused solely on the base card : the design elements can be found here: http://www.patternfly.org/pattern-library/cards/base-card/#design

I'd like to create individual issues for each of the following : Aggregate Status Cards, Base Card, Trend Card, Utilization Bar Card

Are you ok with that ?
