### ISSUE TITLE
Build/devserver breaks with node 10.x

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#1927]
Found a bug where editing any component file prevents running a build or starting the dev server. Seems to be an issue on node10 and not node8.

Steps to reproduce;

0) Ensure you're on Active LTS node version `10.15.3` as directed in our docs for [pf3](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/patternfly-react/README.md#node-environment) and [pf4](https://github.com/patternfly/patternfly-react/tree/master/packages/patternfly-4/react-core#node-environment)
1) yarn && yarn bootstrap && yarn build && yarn build:docs
2) edit AboutModal.js (or any component) with a simple line break anywhere
3) yarn build
4) shell crashes, notice the infinite loop of the following error

`(node:21805) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 error listeners added. Use emitter.setMaxListeners() to increase limit`

<img width="1288" alt="Screen Shot 2019-05-02 at 5 12 41 PM" src="https://user-images.githubusercontent.com/5942899/57162432-3c08ce00-6dbc-11e9-9228-451b78a08cc1.png">

Following the same steps when running node `8.16.0` and there's no issue. Running similar exercises in another lerna project and there's no issue. Rebooted and recloned the repo and the problem still exists.

Looks like it was introduced with https://github.com/patternfly/patternfly-react/pull/1835

**Comment by dtaylor113** [comment]
+1  I just ran into this, had to `nvm 8` as workaround.
