### ISSUE TITLE
Component - Utilization Bar

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#193]
Implement the Utilization Bar Chart demonstrated here:
http://www.patternfly.org/pattern-library/data-visualization/utilization-bar-chart/
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/utilization-bar-charts.html

Dev Notes:
It seems like this component can be written as a vanilla js component (as it's quite simple). We had something like [this](https://github.com/patternfly-webcomponents/patternfly-webcomponents/blob/master/src/pf-utilization-bar-chart/pf-utilization-bar-chart.component.js) in the past as a web component. Attributes could easily be converted to props. Also - the Angular JS example: https://github.com/patternfly/angular-patternfly/blob/master/src/charts/utilization-bar/utilization-bar-chart.component.js

**Comment by serenamarie125** [comment]
@ZitaNemeckova is this something you could start on?  It's similar to what you did with Progress Bar

**Comment by ZitaNemeckova** [comment]
This one's tricky but I'm working on it (https://github.com/patternfly/patternfly-react/pull/211)
