### ISSUE TITLE
feat(In-Line Alert) - In-Line Alert Varation 

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#1934]
Need an in-line alert variation for our alert component: 

See:  https://github.com/patternfly/patternfly-next/issues/1390

**Comment by rachael-phillips** [comment]
Placing this on hold until the Core issue is complete.

**Comment by rachael-phillips** [comment]
@tlabaj are we ready to close this issue?

**Comment by tlabaj** [comment]
closed by #2126
