### ISSUE TITLE
feat(Mega menu) - Introduce Mega Menu Component.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#1935]
Introduce new react component for mega menu based on the following design:

https://redhat.invisionapp.com/share/JBRQIWP6UKA#/screens/360241106

See issue: https://github.com/patternfly/patternfly-next/issues/1767

**Comment by rachael-phillips** [comment]
Placing this on hold until the CSS implementation is complete

**Comment by LHinson** [comment]
Will not pursue at this time... only need atm are enhancements to the app launcher
