### ISSUE TITLE
Introduce drawer component for react

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#1938]
Introduce the border component for react.  The drawer component can be seen in notification drawer as well as in other page layouts, where the drawer slide content over, in addition to the capability to lay over content.

This requires updates to:
* Accordion (https://github.com/patternfly/patternfly-next/issues/1787)
* Alert Group (https://github.com/patternfly/patternfly-next/issues/1788), and
* A Notification Icon (https://github.com/patternfly/patternfly-next/issues/1789)

Tasks:
- [ ] Accordion styling updates if applicable outside this component will be fixed with this issue.

See issue: https://github.com/patternfly/patternfly-next/issues/1786

**Comment by rachael-phillips** [comment]
Placing this on hold until the Core implementation is complete.
