### ISSUE TITLE
Notification drawer component

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#1939]
Introduce notification component and notification group.

Introduce the border component for react. The drawer component can be seen in notification drawer as well as in other page layouts, where the drawer slide content over, in addition to the capability to lay over content.

Notification drawer component (patternfly/patternfly-next#1787)
Icon w/ badge (patternfly/patternfly-next#1789)

See issue: patternfly/patternfly-next#1786

Design documentation: Design documentation with expected behavior can be found here: https://drive.google.com/open?id=1kccmdwXgnkLZdH5OY_sr6C91Gsm0gCtF6zp9OBwC-dE

**Comment by rachael-phillips** [comment]
Placing this on hold until the Core implementation is complete

**Comment by mcarrano** [comment]
This issue should remain open.

**Comment by tlabaj** [comment]
Closed by #4137
