### ISSUE TITLE
Grid Layout Not Always Responsive

### ISSUE THREAD

**Issue by misueno** [patternfly/patternfly-react#1947]
We have a Grid that is using sm, md, lg, and xl props in order for it to be responsive when resized.  See code snippet below.

**When the browser window itself is resized, the grid is responsive:**

![BrowserWindowResizedResponsive](https://user-images.githubusercontent.com/20897509/57332591-438be800-70d8-11e9-8978-966be335f2ed.PNG)

**When the grid is resized via a vertical slider component, it is not responsive.  It doesn't seem to know that it is getting smaller in that case:**

![GridResizedViaSliderNotResponsive](https://user-images.githubusercontent.com/20897509/57332766-a7aeac00-70d8-11e9-8155-9c0515fc921a.PNG)

**Code Snippet:**
`<Grid gutter="sm" sm={12} md={6} lg={4} xl={2}>
    {attributes.map(({label, ...attr}) => (
        <GridItem key={attr.id}>
		...
        </GridItem>
    ))}
</Grid>`

**Comment by rachael-phillips** [comment]
@mcoker do you mind taking a quick look to determine if this is core?

**Comment by mcoker** [comment]
@misueno the breakpoints are based off of the window viewport. There is no way currently to have breakpoints defined by container size.
