### ISSUE TITLE
React PF4 Pagination doesn't handle 0 items

### ISSUE THREAD

**Issue by vbusch** [patternfly/patternfly-react#1949]
In firefox (66.0.3), the page number shows as an error when there are no items.  Firefox is highlighting the box in red.  The screenshots have not been edited.

Tried setting the page to 0 & 1.  Set amountOfPages=1, however, it still displays 0.

![0pages](https://user-images.githubusercontent.com/1995405/57341720-8f0aba00-7109-11e9-9de9-891c6a288f64.png)
![Screenshot from 2019-05-07 20-19-57](https://user-images.githubusercontent.com/1995405/57341728-93cf6e00-7109-11e9-95a8-1393af62387d.png)

**Comment by redallen** [comment]
This is because the `<input>` we render has "min=1":
```
      <input
        className={css(styles.formControl)}
        aria-label={currPage}
        type="number"
        min="1"
        max={lastPage}
        value={page}
        onChange={event => {
          let inputPage = Number.parseInt(event.target.value, 10);
          inputPage = Number.isNaN(inputPage) ? page : inputPage;
          inputPage = inputPage > lastPage ? lastPage : inputPage;
          inputPage = inputPage < 1 ? 1 : inputPage;
          onSetPage(event, Number.isNaN(inputPage) ? page : inputPage);
          onPageInput(event, Number.isNaN(inputPage) ? page : inputPage);
        }}
      />
```

We should just have to change that number to 0.

**Comment by rachael-phillips** [comment]
Is this still an issue with the lates in place? https://github.com/patternfly/patternfly-react/pull/2175

**Comment by tlabaj** [comment]
@mcarrano thoughts on this one?

**Comment by mcarrano** [comment]
@vbusch @tlabaj From a design perspective we should never encounter this situation. If there are 0 pages, then there is no data to display and we should be using the empty state pattern as described here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/empty-state

**Comment by vbusch** [comment]
@mcarrano thank you.  This should be marked as invalid then.
I am no longer showing the pagination, when 0 items, in our app.

**Comment by johnsonm325** [comment]
So, then I understand that if there are 0 items, then we remove the pagination bar and show an empty state like this:

![image](https://user-images.githubusercontent.com/15373136/61404329-3a23b680-a8a5-11e9-99d0-e72241c73c3f.png)

**Comment by mcarrano** [comment]
Yes, exactly!

**Comment by tlabaj** [comment]
I am closing this issue since the use case is invalid.
