### ISSUE TITLE
Expose Refs to Input Fields to Allow Focusing

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-react#1954]
Related Issue: https://github.com/patternfly/patternfly-react/issues/816

I would like to autofocus the username input on the Login form, but currently this is not a supported feature. Without access to refs, the only solution around this is to manipulate the actual DOM.

**Comment by redallen** [comment]
We should support focusing all potential form fields.

**Comment by redallen** [comment]
Looks like there's no other `<FormGroup>`s we use inside components, only the login form.
