### ISSUE TITLE
Remove the use of any from typescript code and use the correct types

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#1963]
Update instances where we have types defined as any, since it doesn't follow best practices and results in linter errors.

**Comment by redallen** [comment]
Some places `any` is necessary. How about we pick some specific instances we would like to remove it? We're getting a little ahead of ourselves here when we still have a lot more Javascript (which is implictly always `any`) to convert to Typescript. Also, any changes to the linter or typechecking config are welcome.
