### ISSUE TITLE
[PF4] React-charts issue  ChartLegend and victory types 

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#1976]
With version stable 3.4.2

`
node_modules/@patternfly/react-charts/dist/js/components/ChartLegend/ChartLegend.d.ts
(5,25): Type '[]' does not satisfy the constraint 'number | "toString" | "valueOf" | "charAt" | "charCodeAt" | "concat" | "indexOf" | "lastIndexOf" | "localeCompare" | "match" | "replace" | "search" | "slice" | "split" | "substring" | ... 29 more ... | "trimRight"'.
  Type '[]' is not assignable to type '"trimRight"'.
`
With last version 3.4.6

`node_modules/@types/victory/index.d.ts
(74,43): Generic type 'ReactElement<P>' requires 1 type argument(s).`

**Comment by redallen** [comment]
Closing in favor of #2077
