### ISSUE TITLE
Tabs not working with UMD/SystemJs

### ISSUE THREAD

**Issue by ssilvert** [patternfly/patternfly-react#1981]
Trying the Tabs library for the first time and it crashes.  Simple project to reproduce is here: https://github.com/ssilvert/systemjs-react/tree/patternfly-react

Same problem happens with older version of patternfly-react.

Errors look like this:

react.development.js:276 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `InternalTabs`.
    in InternalTabs (created by TabsWithDiv)
    in div (created by TabsWithDiv)
    in TabsWithDiv (created by Tabs)
    in Tabs (created by Main)
    in Main
warningWithoutStack @ react.development.js:276
warning @ react.development.js:1791
createElementWithValidation @ react.development.js:3023
render @ Tabs.js:503
finishClassComponent @ react-dom.development.js:14830
updateClassComponent @ react-dom.development.js:14785
beginWork @ react-dom.development.js:15733
performUnitOfWork @ react-dom.development.js:19401
workLoop @ react-dom.development.js:19441
renderRoot @ react-dom.development.js:19524
performWorkOnRoot @ react-dom.development.js:20431
performWork @ react-dom.development.js:20343
performSyncWork @ react-dom.development.js:20317
requestWork @ react-dom.development.js:20186
scheduleWork @ react-dom.development.js:20000
scheduleRootUpdate @ react-dom.development.js:20661
updateContainerAtExpirationTime @ react-dom.development.js:20689
updateContainer @ react-dom.development.js:20746
ReactRoot.render @ react-dom.development.js:21042
(anonymous) @ react-dom.development.js:21179
unbatchedUpdates @ react-dom.development.js:20548
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21175
render @ react-dom.development.js:21244
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
evaluate @ evaluate.js:106
(anonymous) @ instantiate.js:355
dynamicExecute @ register-loader.js:665
doEvaluate @ register-loader.js:612
ensureEvaluate @ register-loader.js:520
(anonymous) @ register-loader.js:133
Promise.then (async)
(anonymous) @ register-loader.js:132
Promise.then (async)
RegisterLoader$1.<computed> @ register-loader.js:117
(anonymous) @ loader-polyfill.js:65
Promise.then (async)
Loader.import @ loader-polyfill.js:64
SystemJSLoader$1.import @ systemjs-loader.js:126
(anonymous) @ index.html:21
Show 2 more frames
react.development.js:276 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `InternalTabs`.
    in InternalTabs (created by TabsWithDiv)
    in div (created by TabsWithDiv)
    in TabsWithDiv (created by Tabs)
    in Tabs (created by Main)
    in Main
warningWithoutStack @ react.development.js:276
warning @ react.development.js:1791
createElementWithValidation @ react.development.js:3023
render @ Tabs.js:527
finishClassComponent @ react-dom.development.js:14830
updateClassComponent @ react-dom.development.js:14785
beginWork @ react-dom.development.js:15733
performUnitOfWork @ react-dom.development.js:19401
workLoop @ react-dom.development.js:19441
renderRoot @ react-dom.development.js:19524
performWorkOnRoot @ react-dom.development.js:20431
performWork @ react-dom.development.js:20343
performSyncWork @ react-dom.development.js:20317
requestWork @ react-dom.development.js:20186
scheduleWork @ react-dom.development.js:20000
scheduleRootUpdate @ react-dom.development.js:20661
updateContainerAtExpirationTime @ react-dom.development.js:20689
updateContainer @ react-dom.development.js:20746
ReactRoot.render @ react-dom.development.js:21042
(anonymous) @ react-dom.development.js:21179
unbatchedUpdates @ react-dom.development.js:20548
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21175
render @ react-dom.development.js:21244
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
evaluate @ evaluate.js:106
(anonymous) @ instantiate.js:355
dynamicExecute @ register-loader.js:665
doEvaluate @ register-loader.js:612
ensureEvaluate @ register-loader.js:520
(anonymous) @ register-loader.js:133
Promise.then (async)
(anonymous) @ register-loader.js:132
Promise.then (async)
RegisterLoader$1.<computed> @ register-loader.js:117
(anonymous) @ loader-polyfill.js:65
Promise.then (async)
Loader.import @ loader-polyfill.js:64
SystemJSLoader$1.import @ systemjs-loader.js:126
(anonymous) @ index.html:21
Show 2 more frames
2react-dom.development.js:49 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `InternalTabs`.
    at invariant (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:49:15)
    at createFiberFromTypeAndProps (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:10314:11)
    at createFiberFromElement (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:10335:15)
    at reconcileSingleElement (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:12620:23)
    at reconcileChildFibers (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:12677:35)
    at reconcileChildren (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:14491:28)
    at updateHostComponent (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:14952:3)
    at beginWork (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:15738:14)
    at performUnitOfWork (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:19401:12)
    at workLoop (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:19441:24)
invariant @ react-dom.development.js:49
createFiberFromTypeAndProps @ react-dom.development.js:10314
createFiberFromElement @ react-dom.development.js:10335
reconcileSingleElement @ react-dom.development.js:12620
reconcileChildFibers @ react-dom.development.js:12677
reconcileChildren @ react-dom.development.js:14491
updateHostComponent @ react-dom.development.js:14952
beginWork @ react-dom.development.js:15738
performUnitOfWork @ react-dom.development.js:19401
workLoop @ react-dom.development.js:19441
callCallback @ react-dom.development.js:143
invokeGuardedCallbackDev @ react-dom.development.js:193
invokeGuardedCallback @ react-dom.development.js:250
replayUnitOfWork @ react-dom.development.js:18667
renderRoot @ react-dom.development.js:19557
performWorkOnRoot @ react-dom.development.js:20431
performWork @ react-dom.development.js:20343
performSyncWork @ react-dom.development.js:20317
requestWork @ react-dom.development.js:20186
scheduleWork @ react-dom.development.js:20000
scheduleRootUpdate @ react-dom.development.js:20661
updateContainerAtExpirationTime @ react-dom.development.js:20689
updateContainer @ react-dom.development.js:20746
ReactRoot.render @ react-dom.development.js:21042
(anonymous) @ react-dom.development.js:21179
unbatchedUpdates @ react-dom.development.js:20548
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21175
render @ react-dom.development.js:21244
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
evaluate @ evaluate.js:106
(anonymous) @ instantiate.js:355
dynamicExecute @ register-loader.js:665
doEvaluate @ register-loader.js:612
ensureEvaluate @ register-loader.js:520
(anonymous) @ register-loader.js:133
Promise.then (async)
(anonymous) @ register-loader.js:132
Promise.then (async)
RegisterLoader$1.<computed> @ register-loader.js:117
(anonymous) @ loader-polyfill.js:65
Promise.then (async)
Loader.import @ loader-polyfill.js:64
SystemJSLoader$1.import @ systemjs-loader.js:126
(anonymous) @ index.html:21
Show 7 more frames
2react-dom.development.js:17206 The above error occurred in the <button> component:
    in button (created by InternalTabs)
    in InternalTabs (created by TabsWithDiv)
    in div (created by TabsWithDiv)
    in TabsWithDiv (created by Tabs)
    in Tabs (created by Main)
    in Main

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:17206
logError @ react-dom.development.js:17242
update.callback @ react-dom.development.js:18154
callCallback @ react-dom.development.js:16522
commitUpdateEffects @ react-dom.development.js:16561
commitUpdateQueue @ react-dom.development.js:16552
commitLifeCycles @ react-dom.development.js:17472
commitAllLifeCycles @ react-dom.development.js:18825
callCallback @ react-dom.development.js:143
invokeGuardedCallbackDev @ react-dom.development.js:193
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19037
(anonymous) @ react-dom.development.js:20507
unstable_runWithPriority @ react.development.js:735
completeRoot @ react-dom.development.js:20506
performWorkOnRoot @ react-dom.development.js:20435
performWork @ react-dom.development.js:20343
performSyncWork @ react-dom.development.js:20317
requestWork @ react-dom.development.js:20186
scheduleWork @ react-dom.development.js:20000
scheduleRootUpdate @ react-dom.development.js:20661
updateContainerAtExpirationTime @ react-dom.development.js:20689
updateContainer @ react-dom.development.js:20746
ReactRoot.render @ react-dom.development.js:21042
(anonymous) @ react-dom.development.js:21179
unbatchedUpdates @ react-dom.development.js:20548
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21175
render @ react-dom.development.js:21244
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
(anonymous) @ Main.tsx:54
evaluate @ evaluate.js:106
(anonymous) @ instantiate.js:355
dynamicExecute @ register-loader.js:665
doEvaluate @ register-loader.js:612
ensureEvaluate @ register-loader.js:520
(anonymous) @ register-loader.js:133
Promise.then (async)
(anonymous) @ register-loader.js:132
Promise.then (async)
RegisterLoader$1.<computed> @ register-loader.js:117
(anonymous) @ loader-polyfill.js:65
Promise.then (async)
Loader.import @ loader-polyfill.js:64
SystemJSLoader$1.import @ systemjs-loader.js:126
(anonymous) @ index.html:21
Show 7 more frames
index.html:22 Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `InternalTabs`.
    at invariant (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:49:15)
    at createFiberFromTypeAndProps (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:10314:11)
    at createFiberFromElement (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:10335:15)
    at reconcileSingleElement (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:12620:23)
    at reconcileChildFibers (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:12677:35)
    at reconcileChildren (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:14491:28)
    at updateHostComponent (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:14952:3)
    at beginWork (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:15738:14)
    at performUnitOfWork (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:19401:12)
    at workLoop (http://localhost:8080/node_modules/react-dom/umd/react-dom.development.js:19441:24)
(anonymous) @ index.html:22
Promise.catch (async)
(anonymous) @ index.html:21

**Comment by redallen** [comment]
I checked out your repo, and the stack trace is actually useful here. `InternalTabs` in `Tabs.js` calls `React.createElement(_reactIcons.AngleLeftIcon, null))` and `React.createElement(_reactIcons.AngleRightIcon, null)`, so you just need to include those as well and it works. [Here's the magic commit.](https://github.com/redallen/systemjs-react/commit/e29d8026188728168a387dcb12d9fef28e2c0ca9)

Please reopen if you can't reproduce the fix!
