### ISSUE TITLE
"gutter" prop on stack, split, gallery, grid takes an unnecessary argument

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#1982]
In Stack, Split, Gallery, and Grid, the examples use syntax like `<Gallery gutter="md">`. However we don't currently support changing the gutter size (ie, "sm", "md", "lg", etc) in these components - you either add a gutter (`.pf-m-gutter`) or you don't.

**Comment by rachael-phillips** [comment]
@mcoker does this still apply since the pr was closed not merged?

**Comment by rachael-phillips** [comment]
This is related to @1947

**Comment by mcoker** [comment]
Oh yes, this still applies. Gutter should just be enabled or disabled, not take a size argument.

**Comment by SpyTec** [comment]
If we are not supposed to use differing sizes with these components. How are we supposed to change the sizing without changing it globally or adding custom classes? 

Or for that matter, two of my components right now need to be stacked on top of each other inside a Grid cell, I need a margin for them that's small - is there no component in PatternFly that fits here?

**Comment by mcoker** [comment]
@SpyTec currently these layouts are designed to work within the page component main sections and match the gutter spacing provided by the main sections, navigation, header, etc.

We have a more generic flex layout in core that is a builder layout and allows you to apply any sort of spacing you'd like, however it currently is not available as a react layout and we're trying to get that feature on the react roadmap. You can read more about that layout here - https://www.patternfly.org/v4/documentation/core/layouts/flex
