### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#2]
## Release Process
Today in Patternfly, we have [patternfly-eng-release](https://github.com/patternfly/patternfly-eng-release) to manage releases. We also have some projects gravitating towards [semantic-releases](https://github.com/semantic-release/semantic-release) which automate releases to npm with semantic versioning after every PR merge based on commit message. What type of release process would you like to see used?

**Comment by bleathem** [comment]
The concept of semantic versioning and a release on every PR sounds very appealing.  It definitely reduces the overhead associated with performing a cumulative release.

Is there an automated to aggregate the release notes?  If I'm upgrading from 6.2.13 to 6.5.12 for instance, and I want to know what has changed between those versions, do I have to look at the PR message for each release in between?

**Comment by priley86** [comment]
@bleathem  Other than this [plugin](https://www.npmjs.com/package/semantic-release#generatenotes) which seems poorly documented, I'm not sure how to generate release notes. If we were to go with semantic-releases, I would almost suggest doing this manually or documenting them via Github project milestones & Github project releases. We could always notify the ML as we have before.

The major difference here I suppose would be ensuring every commit is automatically released semantically and our npm package is always up to date (for better or for worse). This also encourages better commit messages with the strict commit syntax.
