### ISSUE TITLE
Component - Popover

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#20]
Implement a component that provides the following UI element:

- [PatternFly Popover](http://www.patternfly.org/pattern-library/widgets/#popover)

Acceptance Criteria:

- When rendered, the component matches the examples in the PatternFly Pattern Library (see link above)
- the component supports:
  - displaying a title
  - displaying a close icon

**Comment by priley86** [comment]
We've added partial support in #86.

**Comment by jgiardino** [comment]
@priley86 Do you remember what work is remaining for this?

**Comment by jgiardino** [comment]
Closing this for now. We can create new issues as further enhancements are needed.
