### ISSUE TITLE
Move controlled.js helper into its own package?

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#200]
Long-term, low-priority, but the controlled state helper that I wrote as part of #88 is a great candidate for a utility repo that would be useful to the React community at large (even those who aren't using patternfly-react). I was quite surprised to see that something like it didn't really exist yet.

It might be cool to document and share it, as a repo at perhaps `patternfly/react-controlled-state`, update patternfly-react to use it as an npm dependency, and spread it around the community. If people end up using it, there will be more visibility on the patternfly github org, and perhaps more React developers will find out about patternfly-react.

Plus, I want to use it in my own side project :)  Hooray for open source.

**Comment by priley86** [comment]
i think this relates to #160 - ideally long term we can get maximum visibility on pf-react related distributions in a "monorepo", however I am not opposed to exposing packages in separate repos if that becomes the consensus (and also not opposed to separate repos when those packages are cross framework/generic es6 modules). Maintaining a separate package is minimal effort if automated release tools are used and I am happy to share notes on this - however I think it may be desirable to keep related packages in a monorepo. Will revisit this in the future and thanks for posing it!

**Comment by mturley** [comment]
Ah, yes! A monorepo with multiple npm packages deployed from it. Hadn't thought of that, that will probably work great. And in fact, if people wanted to look at the source for this helper they'd end up at the source for all of patternfly-react, which is great for visibility.

Relevant: #201

**Comment by mturley** [comment]
This issue didn't age well... the `controlled` helper became obsolete pretty quickly when React added `getDerivedStateFromProps`. It should be removed and the VerticalNav should be refactored to stop using it... but, that's technical debt that might not ever be worth spending time on for pf3, and I already made a note of it in my comment here: https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/patternfly-react/src/common/controlled.js#L9

So I think it's safe to close this one.
