### ISSUE TITLE
Card View

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2004]
Create a card demo based on this PR that was just merged in Core:
https://github.com/patternfly/patternfly-next/pull/1716

Functionality includes the ability to check all cards using their checkboxes and delete them using the toolbar buttons. The kebab in each card should expand.

@mcarrano should be able to answer any other interaction questions.

**Comment by mcarrano** [comment]
This should be pretty straight forward. It's just a grid of cards with a toolbar inside of a full page layout. The cards must be selectable as @rachael-phillips notes. The core demo provides a reasonable default card to use for the demo. But it's important to note that the content of the card itself should not be constrained. The consumer should be able to add any actions or body content within the general card layouts that we support.

Let me know if you have further questions.

**Comment by dlabaj** [comment]
@rachael-phillips @mcarrano We need toolbar implemented to be consistent with core prior to doing this work.  We currently are still using a layout.  If we implement this in react without the toolbar then it will not be the same as what we have in core.

**Comment by rachael-phillips** [comment]
@mcoker @mcarrano should we just wait until toolbar refactor is complete in Core and React to continue with this work?

**Comment by mcarrano** [comment]
Yes, I think so @rachael-phillips . Having a refactored React toolbar will be a dependency for any of these data views (card, list, or table).

**Comment by jenny-s51** [comment]
Hi @mcarrano @dlabaj  -- just wondering if this issue is still on hold ... are there any corresponding issues in core/react for the toolbar refactor? Does anyone know the status of those? I see https://github.com/patternfly/patternfly-react/issues/2009 is related but still open

**Comment by mcarrano** [comment]
I think that the Toolbar is complete now and #2009 should probably be closed. @tlabaj can you confirm that is the case? I am not aware of anything else that should be blocking this. There is design documentation recently  released here that should provide more detail on expected behavior. https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/card-view

**Comment by mcarrano** [comment]
@rachael-phillips @LHinson Should this get on the roadmap? We have a core demo but not a React.

**Comment by jenny-s51** [comment]
@mcarrano happy to take on this issue once it's taken off hold!

**Comment by mcarrano** [comment]
Sounds good to me @jenny-s51 

@rachael-phillips @tlabaj any issue with proceeding forward with this? I think it was on hold waiting for the Toolbar.

**Comment by rachael-phillips** [comment]
@mcarrano @jenny-s51 yes, we can go ahead and start working on this. One thing to keep in mind is because this will be experimental we will want to include the experimental alert as seen across our experimental features:

<img width="1294" alt="Screen Shot 2019-12-03 at 1 57 25 PM" src="https://user-images.githubusercontent.com/40275806/70080698-05569880-15d5-11ea-8c72-a626e293ffe7.png">


cc @tlabaj

**Comment by jenny-s51** [comment]
WIP via #2004. Card View display/functionality is complete -- currently working on a functional toolbar for the demo.

**Comment by tlabaj** [comment]
closed by  #3441
