### ISSUE TITLE
Investigate why the Snapshot test are rendering dynamic tags as <Component>

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#2007]
The Jest test snapshots render dynamic tags as <Component> . We need to determine why this is happening.

**Comment by rachael-phillips** [comment]
Closing

**Comment by elad661** [comment]
@rachael-phillips @tlabaj Hey, I'm seeing this issue now after updating to 3.112.3, breaking all our tests in OCM. I see this was closed without providing additional details. Should I file a new bug? Do you have some tips for me how I can work around this issue?
