### ISSUE TITLE
Refactored Toolbar

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2009]
The related core issue is https://github.com/patternfly/patternfly-next/issues/1528

**Comment by mattnolting** [comment]
I spoke to @mcarrano and @mceledonia about toolbar details. Here are the takeaways.

- Elements need to be moved in the DOM, based on content. 
Example 1: when multiple filters are present, these filters need to be moved to the `expandable-content` element and controlled via filter button toggle.

![Screen Shot 2019-05-14 at 3 38 49 PM](https://user-images.githubusercontent.com/5385435/57727050-86ad0480-765e-11e9-802c-615d1499fc1d.png)

![Screen Shot 2019-05-14 at 3 39 23 PM](https://user-images.githubusercontent.com/5385435/57727033-7d239c80-765e-11e9-983c-248b9a5b80fe.png)


Example 2: `primary` and `secondary` action buttons should move to the actions menu dropdown at specific breakpoint (this may be controlled by JS as well, we'll have to test and work w/design).

![Screen Shot 2019-05-14 at 3 38 13 PM](https://user-images.githubusercontent.com/5385435/57726969-54030c00-765e-11e9-9fb1-eb72273d3853.png)

- Toolbar may include `bulk-select`, `filter/multiple filters`, `overflow menu action button w/primary and secondary buttons`, `chip-group + chips` and `pagination`.

**Comment by karelhala** [comment]
@nicolethoen any update on this? We want to change how our toolbars behave on smaller screens and would like to use these new components.

**Comment by nicolethoen** [comment]
@karelhala it's all I'm doing :) hoping to have a PR up this week.

**Comment by rachael-phillips** [comment]
Closing this issue
