### ISSUE TITLE
Expose several NPM packages

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#201]
Currently, PatternFly React only exposes a single NPM package “patternfly-react” and exposes all modules within a single package in an automated semantic release process. 

In the long term, it would be nice to expose several NPM packages in an automated semantic release process via a single repository, a “monorepo”. This will allow further breakdown of the distributions and reduce the dependency trees when installing patternfly-react packages, and enable us to continue reviewing packages together as a community in a single repository. 

More notes on how Facebook did this here: https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html

**Comment by priley86** [comment]
Referencing our other [discussion](https://github.com/patternfly/patternfly-react/pull/160#issuecomment-361946200) on this here too. Support for this is currently being added to semantic-releases upstream: https://github.com/patternfly/patternfly-react/pull/160#issuecomment-361946200

**Comment by karelhala** [comment]
I really like the idea of monorepo and splitting code into separate bundles which can be included one by one and make it easier to maintain and have much more sophisticated components in this repo. However I would not use multiple packages, that might be the end goal in future, but right now we can use webpack and it's [libraries](https://webpack.js.org/guides/author-libraries/#expose-the-library), where as entries for webpack we'd use function to look for all folders. You can check out this repo [react-ui-components](https://github.com/karelhala/react-ui-components/tree/master/scripts) which basically does the same thing as we intend to do here.

**Comment by priley86** [comment]
Responded in #218 regarding organization. I think using webpack to expose commonJS/AMD definitions here is a separate issue from this one now (as far as moving to automated semantic releases of monorepo is concerned).

Do you mind starting a separate issue on webpack/AMD? I think right now, exposing our babel transpiled es6 modules is working fine, and we leave code splits to Webpack on the application end. However, I'm definitely open to ideas on this in the future... I am hearing good things about Rollup and other packaging libraries as well, but Babel is working great right now!
