### ISSUE TITLE
Date and Time Picker investigation

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#2010]
Follow up to https://github.com/patternfly/patternfly-next/issues/180

**Comment by dgutride** [comment]
Reopening

**Comment by unlikelyzero** [comment]
@dgutride @LHinson

**Comment by LHinson** [comment]
@unlikelyzero yes, I just added the pin tag so that the stalebot won't close it again. We are looking to pick this back up after our major release in May.

**Comment by AllenBW** [comment]
+1 for timezone inclusion

**Comment by tlabaj** [comment]
Initial investigation issue: was #2947
Results of finding can be found in this doc.
https://docs.google.com/document/d/1HCUTWCk3It3pIRYFLD83H-wThA10yUs7KLJM3fU5Q7Y/edit#heading=h.i6wtpaspo49f
