### ISSUE TITLE
Remove AlertActionCloseButtonProps

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#2016]
AlertActionCloseButtonProps just extends ButtonProps and doesn't offer an additional functionality.  We should remove this in a Breaking change release.

**Comment by rachael-phillips** [comment]
We will tackle this one in the future.

**Comment by rachael-phillips** [comment]
We will investigate whether this issue is necessary to take on.

**Comment by jschuler** [comment]
I see that AlertActionCloseButtonProps offers `variantLabel` and `onClose` over ButtonProps so this can be closed.
