### ISSUE TITLE
Enhancement - Data Tables

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#204]
In this issue we will build on the existing Data Table Component implemented in #107.

Link to current PF Design docs:
https://github.com/patternfly/patternfly-design/blob/master/pattern-library/content-views/table-view/design/overview.md

Some remaining features which PatternFly currently has design for and could be implemented now:
* Simplified API consumption via `controlled` HOC and `DataTable` JSX component (API enhancement only)
* Export to CSV (@serenamarie125 @jgiardino @mcarrano is this accounted for in the current data table design via toolbar/table actions?)
* Empty State, empty row (after filter), filter/toolbar integration (also demonstrating column visibility, column reordering)
* Story examples demonstrating these features in a mock application scenario

Some additional design thoughts for future consideration that Reactabular would support (@mcarrano @jgiardino @jeff-phillips-18  @serenamarie125  maybe you can clarify the design docs/PF intentions on these items) :
* Table with tree (and drag and drop table with tree)
   * https://reactabular.js.org/#/drag-and-drop/with-tree
* Infinite scrolling table (this would enable much more performant UI for large data sets):
   * https://reactabular.js.org/#/examples/infinite-scrolling
* Inline editing
   * https://reactabular.js.org/#/data/inline-editing

Any other UX/design we can account for that I am missing here?

**Comment by mcarrano** [comment]
Just to address your questions @priley86 ...

* We don't specifically call our Export to CSV as an action. I guess it's something that is use case dependent. @serenamarie125 do you see a need for this?
* We do currently have a pattern for a Tree List, but not a Tree Table, although these would seem pretty similar. See http://www.patternfly.org/pattern-library/content-views/tree-list-view/
* We also have inline editing specified but not implements, I think. That's documented here: http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/

There is an open design issue here to consider what features/baseline we should have for table functionality. https://github.com/patternfly/patternfly-design/issues/543  So this becomes an ongoing discussion.

**Comment by serenamarie125** [comment]
having an optional export is definitely useful

**Comment by priley86** [comment]
closing this legacy pf3 issue for now.
