### ISSUE TITLE
PF4 modal: align buttons to left

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#2046]
According to design documentation and our UX designer, **modal buttons should be aligned to left**:

![image](https://user-images.githubusercontent.com/32869456/58081015-92478080-7bb4-11e9-969a-d4abb88c8311.png)

However, they are not in current implementation:

![image](https://user-images.githubusercontent.com/32869456/58081087-b3a86c80-7bb4-11e9-92d6-30ba9f1a96f5.png)

**Links:**
[PF4 design](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal)
[PF4 react](http://patternfly-react.surge.sh/patternfly-4/components/modal/)

cc @martinpovolny

**Comment by terezanovotna** [comment]
@rvsia nice catch!

**Comment by doruskova** [comment]
I also had a problem with it this week. Really confusing. Thanks @rvsia for mentioned this.

**Comment by katierik** [comment]
Logged a similar bug in patternfly-org: https://github.com/patternfly/patternfly-org/issues/1290

**Comment by christiemolloy** [comment]
This should be fixed in Core first, I just created an issue to capture it: https://github.com/patternfly/patternfly-next/issues/2056

**Comment by tlabaj** [comment]
On hold while waiting for core fix.

**Comment by terezanovotna** [comment]
Looking forward to seeing this fixed!🥳🥳

**Comment by rvsia** [comment]
@tlabaj So, this issue should be closed now, right? https://github.com/patternfly/patternfly-react/pull/2835

**Comment by tlabaj** [comment]
Closing this issue.  Issue #3672 will address changing the default behaviour.
