### ISSUE TITLE
Stack: Regardless of gutter value passed in "pf-m-gutter" is set on the Stack

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#2050]
It doesn't matter what value I pass in for a gutter to <Stack> the "pf-m-gutter" class is added to the stack.

**Comment by christianvogt** [comment]
Same problem occurs on `Split`

**Comment by jessiehuff** [comment]
I don't think the modifiers exist [in core](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/layouts/Stack/stack.scss) so even though we changed the class name it doesn't do anything.

**Comment by mcoker** [comment]
@jeff-phillips-18 we don't currently support modifying the gutter size on these layouts. @kybaker and I have talked about it and if you need to override the gutter size, you'll need to write a CSS override or use a utility class. The values for the `gutter` prop in the react layouts should be removed so the gutter is either enabled or disabled. I filed an issue for that here - https://github.com/patternfly/patternfly-react/issues/1982

**Comment by dlabaj** [comment]
duplicate of #1982

**Comment by tlabaj** [comment]
Closing this since it is duplicate.
