### ISSUE TITLE
DropdownItem: navigates to # on select

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#2052]
The DropdownItem click navigates to '#' on click. I must handle the click via onClick in order to preventDefault to avoid unwanted navigation.

**Comment by boaz0** [comment]
Maybe `component="button"` will fix that problem?

```js
<DropdownItem key="group 1 action" component="button">item 1</DropdownItem>
```

**Comment by kmcfaul** [comment]
@jeff-phillips-18 Has `component="button"` resolved your issue? DropdownItem defaults to `<a>` so it would be navigating on a click.

**Comment by jeff-phillips-18** [comment]
That should be fine.
