### ISSUE TITLE
Accordion: Focus border renders outside of accordion item

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#2053]
![image](https://user-images.githubusercontent.com/11633780/58108266-814d3e00-7bb9-11e9-8209-f12513d46d08.png)

**Comment by tlabaj** [comment]
@mcoker Can you verify that the react implementation matches core.  I am thinking this may be a core issue.

**Comment by rachael-phillips** [comment]
Hi @mcoker and @tlabaj did we find out where the issue was on this one?

**Comment by mcoker** [comment]
@rachael-phillips commented on the core issue - https://github.com/patternfly/patternfly-next/issues/1850#issuecomment-513943051
