### ISSUE TITLE
Nav: Horizontal Nav focus border renders improperly

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#2054]
![image](https://user-images.githubusercontent.com/11633780/58108366-b5c0fa00-7bb9-11e9-8bc5-e9cf4bf7cc9b.png)

![image](https://user-images.githubusercontent.com/11633780/58108493-f02a9700-7bb9-11e9-8d0d-e1973455ffdc.png)

**Comment by jschuler** [comment]
Looks to be a core issue since I see this here as well
https://pf4.patternfly.org/components/Nav/examples/#

**Comment by dlabaj** [comment]
@tlabaj @mcoker I believe this will not require an updates on the react side once 1849 is fixed.  Just verification.  Let me know if you agree.

**Comment by rachael-phillips** [comment]
@tlabaj @mcoker following up here. Can you confirm @dlabaj 's comment above?

**Comment by mcoker** [comment]
@rachael-phillips that's correct. I think we can close this one in favor of https://github.com/patternfly/patternfly-next/issues/1849. Or do you prefer leave it open @jeff-phillips-18 to verify once 1849 is merged?

**Comment by jeff-phillips-18** [comment]
I'm ok with closing.
