### ISSUE TITLE
Dropdown-like components refactor

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#2065]
We need to use modularity instead of writing same code for dropdown-like components. There are currently 6 components with similiar code
* [ ] Application Launcher - https://github.com/patternfly/patternfly-react/pull/2101
* [ ] Context Selector
* [ ] Dropdown
* [ ] Options Menu
* [ ] Select

These components should share same logic because they are essentialy the same (active item + menu) and we should benefit from sharing common components instead of writing similiar code in multiple places. Now there is issue opened [1] to pass selected item when user selects something in dropdown, this fix will have to be applied to all 5 components. In past there was fix [2] to pass event when clicking on dropdown toggle so consumers can react to it. In future we should try to refactor dropdown in more clean way. All these issues require adding same code to muliple components this is not good and it's against basic coding principles.

This refactor should change component API as minimal as possible so we don't have to release breaking changes, we should olny update component API by adding new attributes to callbacks but it should still be possible to use these components with current usage.

In past I have opened a PR [2] so application launcher was using dropdown, visually and accesible nothing changed (it even fixed one accessible bug that is still present in non dropdown implementation).

[1] https://github.com/patternfly/patternfly-react/issues/2051
[2] https://github.com/patternfly/patternfly-react/pull/1667
[3] https://github.com/patternfly/patternfly-react/pull/1668

**Comment by SpyTec** [comment]
One discrepancy I've noticed is that some components can be disabled whilst others can't. For instance, Context Selector has `disabled` prop but neither Select nor Application Launcher has it.

Related: #2094
