### ISSUE TITLE
Select w. typeahead breaks search on tab

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2066]
If you have a Select component with typeahead and start typing, it displays the options as expected. Clicking tab and then shift-tab to go back however doesn't expand the list

In fact, this issue happens any time you tab to get to the text input rather than clicking

Version: `"@patternfly/react-core": "^3.16.10"`

**Repro steps:**
1. Have a Select component with typeahead variant that's not in focus
1. Tab until you get to text input in the Select component
1. Start typing for a result

**Expected result:**
Options list is expanded

**Actual result:**
Nothing happens

**Comment by redallen** [comment]
Is this still the case in https://2013-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/select/ ?

**Comment by SpyTec** [comment]
@redallen Yes, the examples there have the same bug

**Comment by tlabaj** [comment]
closed by #2572
