### ISSUE TITLE
Improve Dropdown to allow keyboard navigation

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2067]
Right now if you want to select an option in a dropdown you have to click it. There is no way to use keyboard shortcuts to select an option.

Using up/down arrows do not work. Tab brings you to next element rather than down the list.

For Select with typeahead: Pressing enter does not select the top most element or the selected element.

Is this something to consider as an improvement?

**Comment by redallen** [comment]
Select with typeahead keyboard support is in #2013. I agree the dropdown should allow keyboard navigation, so I changed the title to that.

**Comment by tlabaj** [comment]
This issue was closed by PR #2067
