### ISSUE TITLE
Component - Utilization Bar Card

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#208]
Create the [Utilization Bar Card](http://www.patternfly.org/pattern-library/cards/utilization-trend-card/
) , based off of the [PatternFly Base Card](http://www.patternfly.org/pattern-library/cards/base-card/)

Note that the Base Card has an associated [Issue#192](https://github.com/patternfly/patternfly-react/issues/192)

Dev Notes:
Ideally - we can also provide some simple helpers on top of the core Card components to ensure cards have the same height in a dashboard visualization. I have written an example of this using React Equalizer as opposed to jquery-match-height. Reach out if you'd like any help w/ this.

**Comment by ZitaNemeckova** [comment]
@serenamarie125 Do you mean Utilization Bar Card or Utilization Trend Card? First link is pointing to the second card.

**Comment by LHinson** [comment]
Closing this issue as Utilization Bar Card has been introduced. See [here](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Header=Great%20job%21&knob-Message=This%20is%20really%20working%20out.&knob-Type=success&knob-Menu=true&knob-Action=true&knob-Style=default&knob-Match%20Height=true&selectedKind=patternfly-react%2FCards&selectedStory=Utilization%20Bar%20Card&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).
