### ISSUE TITLE
maxWidth prop doesn't work with ClipboardCopy

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#2082]
I noticed that the `maxWidth` prop for this component doesn't have an effect on how the component renders. I believe this is a bug.

**Comment by boaz0** [comment]
Probably `maxWidth` is a bad name for that prop but it  is used in the tooltip component. As mentioned in the docs it sets a maximum width of the tooltip.

Nevertheless, if you want to set a maximum width to the entire component you can do so through the `style` prop:

```js
import React from 'react';
import { ClipboardCopy, ClipboardCopyVariant } from '@patternfly/react-core';

<ClipboardCopy style={{ maxWidth: '200px'}}variant={ClipboardCopyVariant.expansion}>
  Got a lot of text here, need to see all of it? Click that arrow on the left side and check out the resulting
  expansion.
</ClipboardCopy>
```

**Comment by seanforyou23** [comment]
I see, thanks for clarifying @boaz0! The property name does seem like a stumbling block as it's passed directly to the ClipboardCopy component and doesn't indicate that it will be used for something other than the container. I totally missed the word "tooltip" in the doc.
