### ISSUE TITLE
Select does not render children when changed after initialization

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2090]
If you have a Select component that gets its children updated post-construction it will not render the new children until either the select has been closed and re-opened, or selection is cleared.

Can probably be fixed by `getDerivedStateFromProps` (thanks dougmiller) https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

CodeSandbox: https://codesandbox.io/embed/ecstatic-boyd-qprtb

Version: `"@patternfly/react-core": "^3.16.10"`

**Repro steps:**
1. Have a Select component with any type
1. Populate its initial children 
1. Change children value
1. Click dropdown on Select component

**Expected result:**
Options list contains updated children value

**Actual result:**
Options list contains old children value.

**Comment by redallen** [comment]
Someone on Slack had the same issue a few days ago, you have to click the select twice to render children. @kmcfaul thinks Select needs an extra lifecycle method as well.

**Comment by SpyTec** [comment]
Same person :)

**Comment by tlabaj** [comment]
Closed by #2518
