### ISSUE TITLE
Not all dropdown types can be disabled

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2094]
I have a use case for disabling Select component when no children are active, though no `disabled` prop exists on the component. 

Only dropdown-type component that can be disabled is Context Selector. Alas this doesn't support multiple selections.

Having `disabled` prop on Select and Application Launcher in the same manner Context Selector has would be a nice feature

**Comment by shailysangwan** [comment]
Hi @SpyTec , I want to start contributing to the project and I was hoping to work on this issue if it is to be implemented.
Thanks :)

**Comment by SpyTec** [comment]
>Hi @SpyTec , I want to start contributing to the project and I was hoping to work on this issue if it is to be implemented. ...

Hi @shailysangwan!

I’m not part of the core team myself, though I believe you can pick this up right away. 

There’s one caveat in #2065 which might refactor dropdown into its own shared modular component. It doesn’t seem to be marked for next release so that refactor might take a while :)

**Comment by tlabaj** [comment]
Issue #2366 will address disabling the Select Component.

**Comment by tlabaj** [comment]
C
