### ISSUE TITLE
Popover Regression

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#2099]
A recent [change](https://github.com/patternfly/patternfly-react/commit/be3d1c5e1c057245cb571fd9889ba6378fd35037#diff-d5b83b2e57be9a5646fe7d3bad5c38d9R32) broke the ability to use `position={PopoverPosition.right}` as a value for the position property on Popover. We should be able to use strings or enum values here.

**Comment by redallen** [comment]
Closed via #2113
