### ISSUE TITLE
PF3 Form Examples Allow Closing Modal Form

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#2119]
On the PF3 Form Examples page, the Show Info button on the top right is unreachable because the modal doesn't allow it: 

http://patternfly-react.surge.sh/patternfly-3/index.html?knob-Show%20Help=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Modal=true&selectedKind=patternfly-react%2FForms%20and%20Controls%2FForms%2FForm%20Examples&selectedStory=Modal%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by redallen** [comment]
Uncheck the "Show Modal" in the Knobs, and then you click the Show Info button.
![Screenshot from 2019-05-30 15-03-34](https://user-images.githubusercontent.com/47335686/58657478-55823480-82ec-11e9-836e-e62bd3a7bf90.png)

**Comment by jcaianirh** [comment]
This is user reported. If we connect the x/Cancel to the close event the flow is much more evident. The knobs are usually there to tweak the component in question, which in this case is an example form not example modal.

**Comment by jcaianirh** [comment]
thanks @redallen !
