### ISSUE TITLE
Track Package and Component Usage

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2127]
Track packages that use @patternfly/react-core and grep through their imports to find component usage.

**Comment by dgutride** [comment]
Initial goal would be to get a report of the following and to create a reusable process for generating this list on a regular cadence.

Total component use (count by component totaled across repositories that are queried)
Component usage per repository (i.e. for a repo, button: 30, tab: 20, nav: 2)

**Comment by redallen** [comment]
Initial work done in https://github.com/redallen/patternfly-analytics , open new issues there.
