### ISSUE TITLE
PF4 Tabs Invalid prop `forwardRef` supplied to `Tab`

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#2132]
There's an issue with version `3.32.5` (recommended in issue #2100).

Component:
```javascript
import React from "react";
import { Tabs, Tab } from "@patternfly/react-core";

const Test = () => (
  <Tabs activeKey={0}>
    <Tab eventKey={0} title="Tab0">
      Tab0
    </Tab>
    <Tab eventKey={1} title="Tab1">
      Tab1
    </Tab>
  </Tabs>
);

export default Test;
```
produces warning:
![tabs_issue](https://user-images.githubusercontent.com/16188254/58783712-dccbf280-85e1-11e9-8c62-64e6b4b18971.png)

This issue does not occur in a version `3.16.10`

**Comment by redallen** [comment]
This has to do with our incorrect PropTypes. I just opened a PR to fix it!

**Comment by jschuler** [comment]
Thanks @redallen I see your fix covered it as well, I am merged a fix just for tabs that also addresses this
