### ISSUE TITLE
'ChartDonutUtilization' is not exported from '@patternfly/react-charts'

### ISSUE THREAD

**Issue by davebertz** [patternfly/patternfly-react#2135]
'ChartDonutUtilization' is not exported from '@patternfly/react-charts'

**Comment by redallen** [comment]
Which version of `@patternfly/react-charts` are you using?

**Comment by davebertz** [comment]
```
    "@patternfly/patternfly": "^2.8.2",
    "@patternfly/react-charts": "^3.4.2",
    "@patternfly/react-core": "^3.32.5",
    "@patternfly/react-inline-edit-extension": "^2.4.14",
    "@patternfly/react-table": "^2.8.14",
```

**Comment by redallen** [comment]
[In that version](https://unpkg.com/@patternfly/react-charts@3.4.2/dist/esm/components), we don't have a `ChartDonutUtilization`, only a `ChartDonut`. You can upgrade to a prerelease version like `3.6.4` to get `ChartDonutUtilization`.
