### ISSUE TITLE
Chart docs: annotate types

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2139]
The react-charts docs contain some complex object types. For example, the `ChartArea` component shows `AnimatePropTypeInterface` as the `animate` type below.

The Victory docs show the `animate` type as `type: boolean || object`.
See https://formidable.com/open-source/victory/docs/victory-area/#animate

Note: There are far more complex examples, but using `animate` for simplicity.

![Screen Shot 2019-06-03 at 2 38 52 PM](https://user-images.githubusercontent.com/17481322/58825992-a0ae8700-860d-11e9-8b39-1dec90da2f9d.png)

I don't want to override the existing Victory property types, just to add a description for react-docs. I would prefer to document properties using an annotation, if possible? 

That may allow us to simplify the `animate` description / type as a `boolean` instead of `AnimatePropTypeInterface`. It would also isolate us from Victory changing the underlying property type and breaking our component wrappers.

**Comment by redallen** [comment]
What's wrong with overriding the existing Victory props to make `animate?: boolean`? What type of `@` annotation would you like to use, and how would you like it to render?

**Comment by dlabrecq** [comment]
If `animate` were a `boolean`, that would generate an error because the underlying Victory component has a different type. Ideally, we wouldn't override types at all.

Overriding props to be a simple `boolean`, `string`, etc. is not going to work. There are far more complex objects with nested properties.

**Comment by redallen** [comment]
It wouldn't generate an error if we `Omit<VictoryProps, 'animate'>` and then pass to victory something like `animate ? {object Victory expects} : {}`. Still, what type of annotation would you like to use, and how would you like it to render?

**Comment by dlabrecq** [comment]
I simply want to add documentation without having to also re-typing all Victory properties or having to write special code to pass-thru complex objects. Ideally, we should be able to extend a Victory interface and use their existing documentation. I don't have a solution for you, only stating the problem.

**Comment by redallen** [comment]
Oh, I completely understand that issue. That requires extending [react-docgen](https://github.com/reactjs/react-docgen) to follow imports to resolve types. I can open that issue upstream.

**Comment by redallen** [comment]
Looks like [a PR](https://github.com/reactjs/react-docgen/pull/352) is already opened to add support for this. Awaiting its merge and a new package release.

**Comment by redallen** [comment]
Still awaiting its update and merge. Can likely dedicate a day this week to fix it upstream.

**Comment by dlabrecq** [comment]
The unreadable chart docs are still an ongoing issue. 

Inheriting types would be ideal, but if we could somehow provide our own prop types, that would help us clarify the docs.

**Comment by redallen** [comment]
Yeah, this issue has become me adding annotations like `/* @proptype custom string of type */` and `/* @hide */` for internal props. I'd like to follow Javadoc syntax or something of the like.

Are there any more annotations you think might be useful @dlabrecq @dlabaj @tlabaj ?

**Comment by tlabaj** [comment]
@redallen I agree with following Javadoc syntax . `@deprecated` would be very useful to have.

**Comment by dlabrecq** [comment]
That would be fine by me

**Comment by dlabrecq** [comment]
That would be fine by me.

@deprecated, @hide, etc. would be a good start. If we could add them, just when we chose to override, that would be even better.

**Comment by dlabrecq** [comment]
These are the supported annotations: https://github.com/patternfly/patternfly-org/blob/feat/org-redesign/packages

**Comment by dlabrecq** [comment]
I'm going to reopen this to ensure we apply annotations to the chart docs.

These are the supported annotations: https://github.com/patternfly/patternfly-org/blob/feat/org-redesign/packages

**Comment by dlabrecq** [comment]
Tried using @propType, but does not appear to work. Created https://github.com/patternfly/patternfly-react/issues/5304 to track it.
