### ISSUE TITLE
Top level menu item in VerticalNav should close on second click

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/patternfly-react#214]
It's a bit confusing that repeatedly clicking a top-level item does not toggle the menu open/close.

![2018-02-08 14 41 34](https://user-images.githubusercontent.com/280512/35994380-3ceb3686-0cde-11e8-91ea-871d6bbcbe75.gif)

I also noticed that a click outside of the menu occasionally didn't close the menu w/o a second click.

**Comment by jeff-phillips-18** [comment]
Is this in hover disabled mode?

**Comment by Laviro** [comment]
Working on it

**Comment by Laviro** [comment]
@benjaminapetersen you may set the hoverDisabled prop to true.

**Comment by benjaminapetersen** [comment]
I don't believe it was `hover` triggered, I think it was `click` to open, but then `click` again did not close.
