### ISSUE TITLE
Link Button Broken

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2145]
The Link Button variation of the Button is missing the margin between icon and text. Refer to Core for correct spacing. This PR was merged in Core: https://github.com/patternfly/patternfly-next/pull/1890

**Comment by jschuler** [comment]
At the Button is just a container, if it's the Link variant you can place an icon + text or just text or just icon. To add the `pf-c-button__icon` class on the icon for the user which adds the right padding on the icon, we might have to add an additional icon prop for the button that adds it in for the user. otherwise the user could manually insert `<PlusCircleIcon className="pf-c-button__icon" />`

**Comment by christiemolloy** [comment]
@jschuler I was currently fixing this in Core, so that we have a wrapper around the icon with the class that sets the margin. Do you think thats a better way than adding another prop/the user manually setting it? or do you think this can be easily fixed in React?

**Comment by mcoker** [comment]
@jschuler the wrapping element was added to core in https://github.com/patternfly/patternfly-next/pull/1890

**Comment by kmcfaul** [comment]
As @jschuler mentioned, the current React implementation has no knowledge of what the Button contains at the moment, so the icon as well as the text are defined outside. We can either wrap the entirety of the link button's contained content (icon + text), or define an optional icon property that we wrap ourselves.

Is there a preferred way for me to implement this of the options?

**Comment by christiemolloy** [comment]
The idea is that for any button with an icon + text, the icon should have a class wrapped around it and we defined that class in Core. I think the second suggestion about defining an option icon property would work right @mcoker

**Comment by mcoker** [comment]
> define an optional icon property that we wrap ourselves.

Yeah, would you take a prop for the icon to use and the react component generates the icon and wraps it in the new element? FWIW, I was thinking something like this, but maybe a prop would be better?

```
    <Button variant="link">
      <ButtonIcon>
        <PlusCircleIcon />
      </ButtonIcon>
      Link button
    </Button>
```

**Comment by kmcfaul** [comment]
@mcoker 
It would be more along the lines of:
`
<Button variant="link" icon={<PlusCircleIcon />}>
     Link Button
</Button>
`

`<ButtonIcon>` would be another component, but is also doable if we want to add a simple wrapper instead. Users would have to define their link buttons as you have shown in this case.

**Comment by mcoker** [comment]
Your suggestion is much better!

**Comment by mcoker** [comment]
@kmcfaul fwiw, I was looking at the [empty state component](http://patternfly-react.surge.sh/patternfly-4/components/emptystate/) and it has a similar feature where you can add an optional icon and that's defined as...

```
  <EmptyState variant={EmptyStateVariant.full}>
    <EmptyStateIcon icon={CubesIcon} />
    ...
```

If that's similar to this, is there any value in being consistent with the approach?

**Comment by kmcfaul** [comment]
The PR does add a similar optional 'icon' property so it should behave the same as the empty state case from what I see.
