### ISSUE TITLE
Migrate from npm to yarn 

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/patternfly-react#215]
Per [comments on issue 19 in patternfly-react-demo-app](https://github.com/patternfly/patternfly-react-demo-app/issues/19#issuecomment-364618983), since `yarn` is being used in products, consider migrating repos from `npm` to `yarn`.

**Comment by vojtechszocs** [comment]
I was playing with this today and got it working. Will post a PR soon.

**Comment by vojtechszocs** [comment]
PR is ready, let me know what you think.
