### ISSUE TITLE
Alert - provide default value for variant prop

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#2154]
As suggested in #2030, there should be a default value defined for the `variant` prop. After discussing with other PF contributors, the recommendation is to use `'info'` as the default.

**Comment by ssilvert** [comment]
NOOOOOO!!!!!

**variantProp** should not be displayed as part of the title at all.

As a developer, I should be able to just say:
```javascript
<Alert>My message to the user.</Alert>
```

It should all just work.  The message should be displayed to the user with a default severity level.

**Comment by tlabaj** [comment]
Closed by #2218
