### ISSUE TITLE
Grid is broken in workspace and website

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2156]
<img width="1369" alt="Screen Shot 2019-06-04 at 3 40 02 PM" src="https://user-images.githubusercontent.com/40275806/58908645-19c9df00-86df-11e9-840c-6d0e39301fa7.png">

The Grid looks broken and unresponsive on workspace and website.

<img width="993" alt="Screen Shot 2019-06-04 at 3 41 35 PM" src="https://user-images.githubusercontent.com/40275806/58908711-454cc980-86df-11e9-8d1b-16c6b3facd63.png">

**Comment by redallen** [comment]
I last refactored this for react-docs, I'll take a look when I have time!

**Comment by redallen** [comment]
@jschuler and I had a talk where we don't really see this playground's value, nor it being worth it to maintain and style. Grid documentation is sufficient without it.
