### ISSUE TITLE
Popover example looks broken in React workspace and website

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2157]
https://staging.patternfly.org/v4/documentation/react/components/popover/

Popover example looks broken in React workspace and website.

<img width="644" alt="Screen Shot 2019-06-04 at 3 51 17 PM" src="https://user-images.githubusercontent.com/40275806/58909239-a032f080-86e0-11e9-969a-f52b7f2d7e86.png">

**Comment by dgutride** [comment]
@rachael-phillips  - the example seems to work for me, can you provide more details about what you mean - are you talking about the design/look and feel or functionality?

**Comment by redallen** [comment]
Popover was just converted to TypeScript, upgraded to Tippyv2, and its examples review. The Advanced popover example correctly toggles the checkbox and is not closable from clicking away except by clicking the checkbox. Reopen if there's a specific bug.
