### ISSUE TITLE
Remove flow from react-virtualized-extension

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2182]
Convert the following flow files from flow to TypeScript:

- `VirtualGrid.js`
- `VirtualTableBody.js`
- `utils/ScalingCellSizeAndPositionManager.js`
- `utils/maxElementSize.js`
- `utils/calculateSizeAndPositionDataAndUpdateScrollOffset.js`
- `utils/updateScrollIndexHelper.js`
- `utils/CellSizeAndPositionManager.js`
- `accessibilityOverscanIndicesGetter.js`
- `types.js`
- `defaultOverscanIndicesGetter.js`
- `defaultCellRangeRenderer.js`

**Comment by dgutride** [comment]
@redallen  - is this a large effort?

**Comment by redallen** [comment]
Closed in #2190
