### ISSUE TITLE
Test coverage: Charts

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#219]
Coveralls indicates current coverage is 35% for Charts. This would be nice to improve upon as "good first issues" while familiarizing with the repo. Just going to identify a few of these for now...

https://coveralls.io/github/patternfly/patternfly-react?branch=master

**Comment by rebeccaalpert** [comment]
It looks like all the charts except PieChart have at least basic tests in place (for proper rendering), though some (StackedBarChart, etc.) have their tests stored in more general files like BarChart.test.js. I made a rendering test for PieChart following the conventions the other tests are using. Is that all you need for this?

**Comment by priley86** [comment]
hey @rebeccaalpert - thanks for helping out w/ this!

I've been using the Jest test coverage reporter inside this project to inspect the analyzed coverage. You can see this by running `yarn test` on your local, and then after it's done, navigating to the `coverage\lcov-report\index.html` file (and just opening that in Chrome). Right now, it looks like Charts is still one of our biggest offenders (particularly the Donut). As you add tests, you can see those lines get covered and go green ✅ 
![screen shot 2018-06-08 at 11 02 57 am](https://user-images.githubusercontent.com/4237045/41165675-3dcc8870-6b0c-11e8-8da5-88a60a4f824b.png)
![screen shot 2018-06-08 at 11 03 08 am](https://user-images.githubusercontent.com/4237045/41165681-3f5fbfb8-6b0c-11e8-93a0-5534618bb8d4.png)




Additionally - we are using Recompose for these Charts right now, but I would not be opposed to leaving that dependency in the future... it seems redundant now in some areas since we have moved to React 16. If you are interested in this, maybe we could revisit that in a future issue!

**Comment by priley86** [comment]
This PF3 issue is stale and no longer being actively worked. Closing this for now. Will reopen if we determine it is needed later.
