### ISSUE TITLE
Select component updates

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#2211]
We would like to use Select component in cloud services however its API does not quite fit our needs.

* `isExpanded` - all components have isOpen however select has isExpanded is there any reason for it?
* `isDisabled` - unable to set isDisabled on select component
* position - unable to set position of select to right, left
* direction - unable to set position of select to top, down (select on page end is not usable) **Critical**
* checkbox typeahed is missing
* `isPlain` - attribute is missing
* ~~`onSelect` missing whole object - when I select some value I want to receive the entire object, not just it's value. We want to display custom elements and filter trough server IDs **Critical**~~ https://github.com/patternfly/patternfly-react/issues/2045
* unable to search by callback function - select options are seachable only on first char, however we would like to query server to retrieve new options **Critical**
* unable to use custom components in select children - we will be loading options from server so we would like to show spinner instead of select options and show options once we load them **Critical**

I went ahead and tried to fix some of these issue, however because select component has specific implementantation I was unable to do it. I think this is great place to track these issues if you want break it into more specific issues and I'll link them in here as well.

**Comment by karelhala** [comment]
ping @Hyperkid123

**Comment by karelhala** [comment]
Looks like whole object when selecting value is already addressed in https://github.com/patternfly/patternfly-react/issues/2045 so crossing that out.

**Comment by rachael-phillips** [comment]
@tlabaj making you aware. @karelhala is this currently blocking you?

**Comment by Hyperkid123** [comment]
@rachael-phillips select component is blocking multiple insgiths UI projects. I am working on sources, catalog, approval, rbac (data-driven-forms).

All of them needs to use select but because of some issues described in #2045 we can't use pf4 select. We are using custom implementation or component from different library.

**Comment by rachael-phillips** [comment]
@Hyperkid123 and @karelhala can you tell me more about your timeline and when you need these changes by?

**Comment by rachael-phillips** [comment]
@karelhala we are going to create another issue to address the breaking changes here.

**Comment by rachael-phillips** [comment]
@mcarrano we don't have a checkbox typeahed in Core - is this a variation that we planned for in design?

**Comment by mcarrano** [comment]
I'm not sure what you mean by "checkbox typeahead." Can someone give an example?

**Comment by kmcfaul** [comment]
@karelhala beginning to work on these, and need some clarification about a couple.

Is the `isPlain` modifier missing from the select option component or a different part of the select?

What do you mean by searching via a callback function? If the options update with a server call in some other part of the code, then keeping the options structure in state and updating it should update the select menu.

**Comment by karelhala** [comment]
> @karelhala beginning to work on these, and need some clarification about a couple.
> 
> Is the `isPlain` modifier missing from the select option component or a different part of the select?
> 

I would expect that this property would have same behavior as `isPlain` on dropdown component. That means, no borders etc. If there is no example in core I think we can skip it. I would just expect similiar API as what has dropdown.

> What do you mean by searching via a callback function? If the options update with a server call in some other part of the code, then keeping the options structure in state and updating it should update the select menu.

Currently default search function is searching over DOM elements, that is not ideal if I am using translated texts I can't map them to untranslated (present on server) plus I would like to filter by any occurrences not only by starting string. Imagine having options `['One', 'Two', 'Three', 'Four']` if user inputs `O` in filter I would like to show `['One', 'Two', 'Four']`, current implementation would show just `['One]`.

I would imagine that when I use `Select` component and pass `onFilter` function I would handle this filtering instead of predefined. Basicly if this callback is present do not filtere values by default function but use this callback.
```JSX
import React from 'react';
import { Select, SelectOption, SelectVariant, CheckboxSelectGroup, CheckboxSelectOption } from '@patternfly/react-core';

class MyComp extends React.Component {
  state = {
    options: [
       'One', 'Two', 'Three', 'Four'
    ]
  }
  onFilter = (event, value) => {
    this.setState({
      options: this.state.options.filter(item => item.indexOf(value) !== -1)
    })
  }

  render() {
    return (
      <Select
         // other props
        onFilter={this.onFilter}
        >
          {this.options.map((option, index) => (
            <SelectOption
              isDisabled={option.disabled}
              key={index}
              value={option.value}
              isPlaceholder={option.isPlaceholder}
            />
          ))}
        </Select>
    )
  }
}
```

**Comment by tlabaj** [comment]
@karelhala the Select menu is the same width as the toggle.  Position left or right would not make a difference to the appearance.

**Comment by rachael-phillips** [comment]
@karelhala when you have marked something as critical, what are the timeline needs for this fix?

**Comment by tlabaj** [comment]
Issue #2366 has been opened to address the `isDisabled`
Issue #2368 has been added for the direction prop
Issue #2369 has been added for the Search callback
Issue #2370 has ben added for the custom children

**Comment by karelhala** [comment]
@rachael-phillips well, we have started to use different component because select has currently another issue and you can't use typeahed in there. Input does not receive focus.

**Comment by mcarrano** [comment]
@karelhala There is a specific variant called "Typeahead select input" https://www.patternfly.org/v4/documentation/react/components/select/#typeahead-select-input   Does this not do what you need?

**Comment by karelhala** [comment]
@mcarrano not really because I am unable to match the values based on my own filtering function. given the example I would like to filter the values by typing `ba` and see option `Alabama` as it contains the sring.

**Comment by mcarrano** [comment]
I see. That makes sense @karelhala . It should be possible to do that.
