### ISSUE TITLE
React table throws Can't resolve lodash-es in v2.11.1

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2222]
I'm getting the following error after updating to latest react-tables, v2.11.1.

```
Failed to compile.

./node_modules/@patternfly/react-table/dist/esm/components/Table/base/body.js
Module not found: Can't resolve 'lodash-es' in '/home/spytec/Documents/JavaScriptProjects/telltale-ui/node_modules/@patternfly/react-table/dist/esm/components/Table/base'
```

**Comment by AllenBW** [comment]
Ditto this issue, @dgutride ⛑ 🙇 😱 ❤️

**Comment by redallen** [comment]
`lodash-es@4.x` is currently a peer dependency of `@patternfly/react-table`. If you `npm i --save lodash-es@4.x` in your project, the import should resolve. A new release will be out soon that includes it as just a normal dependency.

**Comment by redallen** [comment]
Please repoen if `@patternfly/react-table@2.11.6` still has these issues!
