### ISSUE TITLE
Select sends undefined props to SelectToggle and SingleSelect

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2223]
In version v3.38.0 I'm getting the following error whenever I use the Select component.

> Warning: Failed prop type: SelectToggle: prop type `handleTypeaheadKeys` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

and

> Failed prop type: SingleSelect: prop type `sendRef` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

Reproducible CodeSandbox: https://codesandbox.io/embed/dazzling-maxwell-fuh7i?fontsize=14

**Comment by rachael-phillips** [comment]
Thanks for posting this @SpyTec! Is this currently blocking you?

**Comment by SpyTec** [comment]
Apart from clogging up the console it does not seem to affect functionality

**Comment by rachael-phillips** [comment]
Thanks!

**Comment by redallen** [comment]
Big select refactor coming in #2201.

**Comment by rachael-phillips** [comment]
@redallen will the refactor resolve this?

**Comment by tlabaj** [comment]
Closed by #2201
