### ISSUE TITLE
PF4:  Modal onClose callbacked changed to () => void;  in @patternfly/react-core 3.16.4 and prior it allowed passing an argument  

### ISSUE THREAD

**Issue by jwmatthews** [patternfly/patternfly-react#2233]
We noticed a breaking change in typedef for 'onClose?: () => void;' of Modal.tsx
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Modal/Modal.tsx#L27

We were using "@patternfly/react-core": "3.16.4" , attempted to upgrade to latest and hit error:
ERROR in /git/fusor/mig-ui/src/app/common/components/ConfirmModal.tsx
./src/app/common/components/ConfirmModal.tsx
[tsl] ERROR in /git/fusor/mig-ui/src/app/common/components/ConfirmModal.tsx(20,7)
TS2322: Type '(isConfirmed: any) => void' is not assignable to type '() => void'.

Resolve by pinning to "@patternfly/react-core": "3.16.4"

Our example:
https://github.com/fusor/mig-ui/blob/master/src/app/home/components/DataList/Clusters/ClusterDataListItem.tsx#L42
 https://github.com/fusor/mig-ui/blob/master/src/app/common/components/ConfirmModal.tsx

**Comment by jwmatthews** [comment]
cc @eriknelson @ibolton336

**Comment by redallen** [comment]
The typedef that used to just be `Function` was modified to match the implementation in #1942 , which is `() => void`. Your `isConfirmed: any` was never being used, so just remove it or open an issue for Modal if you want the type to be `(event: MouseEvent) => void`.
