### ISSUE TITLE
Vertical navigation controlled state gets confused when no initial item is active

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#224]
When starting with no active items then setting an active item, the first active item remains considered active and is highlighted.

**Comment by mturley** [comment]
Hmm. I guess maybe `initialActive` should be required, if you are not using `active` somewhere in the tree? hmm that's difficult to enforce. There are custom propTypes functions you can write though so it's doable.

**Comment by mturley** [comment]
Action items for when I get around to this:

- [ ] Add notes to documentation / code comments / storybook descriptions to explain the workaround of always specifying an active item even if you don't have a real one.
- [ ] Maybe introduce some kind of loading state where it is acceptable to not have an active item
- [ ] Maybe introduce more strict propTypes testing or other warnings/failures when you do not specify an active item

**Comment by jeff-phillips-18** [comment]
Still relevant

**Comment by mturley** [comment]
I didn't realize I was still assigned to this, I'll unassign myself for now in case someone else has time to take it on before I do. Sorry I dropped the ball on this one @jeff-phillips-18 , how high priority do you think it is?

**Comment by jeff-phillips-18** [comment]
well, I don't _need_ it any more (we worked around it), but others may run into the same.

**Comment by jeff-phillips-18** [comment]
workaround is to start controlled, meaning set the initial active item for the nav
