### ISSUE TITLE
Bug - ChartDonutThreshold should not have tooltip labels by default.

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#2259]
If no 'labels` prop is passed to `ChartDonutThreshold`, the default labels just show an index value:

![video-convert](https://user-images.githubusercontent.com/22625502/59447835-f800e400-8dd1-11e9-88fd-c88c8bdcdeaf.gif)

**Comment by rachael-phillips** [comment]
@TheRealJon is this blocking you?

**Comment by TheRealJon** [comment]
@rachael-phillips No, not a blocker, just something I noticed. I am manually overriding the label values, but ideally, the default should be handled upstream. I am working on fixes for this and #2258 now

**Comment by TheRealJon** [comment]
Fixed by https://github.com/patternfly/patternfly-react/pull/2270
