### ISSUE TITLE
Epic: Custom Checkbox and Radio Button

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2266]
This epic ties together several issues related to extending our checkbox and radio button component beyond the standard browser support. Some requirements/needs include:

* Supporting tri-state checkbox functionality that includes an intermediate state.
* Making checkboxes and radio buttons more accessible by creating a larger click target. See related issues for more details.

**Comment by mcarrano** [comment]
@jgiardino @mceledonia @mcoker @bkjeffer and I met today to discuss the need for custom checkboxes and radio buttons to address the accessibility issue in https://github.com/patternfly/patternfly-next/issues/865

We concluded that it does make sense to create a custom component that will overlay visual appearance of the standard check HTML component as done by Google Material Design (see https://material-components.github.io/material-components-web-catalog/#/component/checkbox) This would be styled for a slightly larger graphical element and a click/touch target of 40px. The custom component would also implement the tr-state functionality requested in https://github.com/patternfly/patternfly-next/issues/1411. This can be done in a way that will maintain standard HTML check behaviors.

Others feel free to add or elaborate if I missed anything. @rachael-phillips @LHinson FYI

**Comment by jgiardino** [comment]
Thanks for capturing this!

Something to note in addition to creating custom styles for the indeterminate state, is that to support  the semantics of this state for assistive technology, we would also need to create a custom html component that does not use `<input type="checkbox" checked>` but instead `<div role="checkbox" aria-checked="true|false|mixed">`.  The example for this tri-state checkbox is available under the [WAI ARIA authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1/#checkbox). 

I tested their example in VO, and the mixed (i.e. indeterminate) state is announced.
However, using a regular input where the indeterminate state is set with JS, the checkbox is announced as "unchecked".

**Comment by mcarrano** [comment]
Accessibility issue is still pending. Is this something we want to get on our roadmap @rachael-phillips @LHinson ?
