### ISSUE TITLE
Popover doesn't show property docs for sub-components

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-react#2272]
https://patternfly-react.surge.sh/patternfly-4/components/popover/
Only shows Popover properties, should be properties sections for PopoverContent, PopoverBody, PopOverDialog, PoopOver Header & Footer, etc..

**Comment by redallen** [comment]
Add the exported components/classes you wish to `propComponents: ['Popover']` in Popover.md.

**Comment by rachael-phillips** [comment]
Hi @dtaylor113 how is it going on this issue?

**Comment by redallen** [comment]
In `Popover/index.ts` we only `export { Popover, PopoverPosition } from './Popover';`, so we shouldn't include `PopOver{Header,Body,etc}` in the docs for consumers since they are not exposed to them.
