### ISSUE TITLE
Popover close button target area isn't big enough

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#2275]
In the react version of Popover, the size of the target area for the close button is too small. While the button seems to be the correct dimensions, the clickable area is much smaller, seems to be roughly the size of the svg inside it. This presents an accessibility issue for those with motor control limitations, and also just seems buggy in general.

Steps to reproduce:

- Launch the examples at http://patternfly-react.surge.sh/patternfly-4/components/popover/
- Hover over the close "x" button
- Notice the cursor flickers when crossing the bounds of svg/button and the area outside the svg isn't clickable

![2019-06-17 09 07 44](https://user-images.githubusercontent.com/5942899/59606599-909fa880-90df-11e9-951d-b90f258878fd.gif)

Expected result: The entire area within the close button is clickable.

The core implementation seems to be ok https://pf4.patternfly.org/components/Popover/examples/

**Comment by seanforyou23** [comment]
Looks like the problem was introduced with https://github.com/patternfly/patternfly-react/pull/1757

Tippy supports an `interactive` property out of the box, which allows for highlighting and selecting text, so I'm not sure why we needed to apply pointer-events in the first place. Will keep investigating, just wanted to share finding so far.

**Comment by rachael-phillips** [comment]
Thanks for filing this @seanforyou23 !

**Comment by rachael-phillips** [comment]
@seanforyou23 are you working on this one currently?
