### ISSUE TITLE
CircleCI builds are failing

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2277]
The PR builds are failing. I see the same error for the latest two PRs. For example:

CircleCI dist build:
<img width="978" alt="Screen Shot 2019-06-15 at 12 16 43 AM" src="https://user-images.githubusercontent.com/17481322/59546875-f84ccc80-8f02-11e9-98d0-34bec66e3982.png">

See https://circleci.com/gh/patternfly/patternfly-react/2259?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

From Slack:
<img width="407" alt="Screen Shot 2019-06-15 at 12 18 30 AM" src="https://user-images.githubusercontent.com/17481322/59546883-2500e400-8f03-11e9-8702-003a23588d75.png">

**Comment by rachael-phillips** [comment]
@redallen do you have an update here and how high priority is this?

**Comment by redallen** [comment]
This was fixed in #2287 this morning :)
