### ISSUE TITLE
react-charts: Update theme to use pf-core variables

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2280]
PatternFly core is in the process of defining color variables for margins, padding, font sizes, height, width, etc. We need to begin using these variables in the theme for react-charts.

Note: color scales will be done via https://github.com/patternfly/patternfly-react/issues/2076

Depends on the following PR:
https://github.com/patternfly/patternfly-next/pull/1863

**Comment by rachael-phillips** [comment]
Thanks for opening this issue, @dlabrecq !

**Comment by redallen** [comment]
Closed in #2281 .

**Comment by dlabrecq** [comment]
The PR below was used to update color scales only. This work was done first.
https://github.com/patternfly/patternfly-react/issues/2076

This issue is to update the remaining theme props to use the vars created by:
patternfly/patternfly-next#1863

**Comment by dlabrecq** [comment]
This PR is now available https://github.com/patternfly/patternfly-react/issues/2280. However, we need to fix a few pf-core variables.

I created this pf-core issue: https://github.com/patternfly/patternfly-next/issues/2011
