### ISSUE TITLE
PageHeader should be updated to use the Context selector

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#2285]
Currently the PageHeader has div that is hidden because the context selector was not available at the time of implementation.  The Context selector is now available so code should be updated.

` {/* Hide for now until we have the context selector component */}
    {/* <div className={css(styles.pageHeaderSelector)}>
      pf-c-context-selector
    </div> */}`

**Comment by rachael-phillips** [comment]
@tlabaj how high priority do you think this is? Could this be a candidate for the help wanted tag?
