### ISSUE TITLE
Consistency - Use ...props for destructing/spread'ing props

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#229]
Would like to standardize on this if possible and use `...props` globally going forward. We may also need to break out a few nested inlined components into `InnerComponents` directory so that `no-shadow` lint rule doesn't break once airbnb config is merged.

Just opening this issue first though.

**Comment by AllenBW** [comment]
Hmmm also perhaps include the retroactive transition  across the repo as to avoid confusion? 
And as I mentioned in #230... add mention of this consensus convention https://github.com/patternfly/patternfly-react/blob/master/CONTRIBUTING.md#code-consistency
