### ISSUE TITLE
Add Custom Data-Attributes to Components for OUIA Compatibility

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2303]
Custom `data-` attributes on our components can help QE teams with integration tests. One suggestion is [OUIA](https://forum.patternfly.org/t/open-web-ui-design-specification-for-enabling-automation-ouia/154). Investigate how to include such attributes behind a Local Storage flag (for now).

This runtime could be useful for consumers who wish to run their own integration tests that locate PF4 components by `data-` attributes.

On the other hand, this is a violation of KISS in our main `dist` where dead code for these extraneous attributes will exist for a runtime most consumers never use and certainly won't want to ship in production. Webpack will not tree-shake the code because it has no idea what `localStorage` will be at runtime.

We could release a separate `react-core-test` package with these attributes for every major release, or ship a [new module type](https://auth0.com/blog/javascript-module-systems-showdown/) like `amd` and require integration tests use that unpopular module type that doesn't include the `data-` attributes.

Open to discussion.

**Comment by rachael-phillips** [comment]
@redallen do you have an update on this one?

**Comment by rachael-phillips** [comment]
@dgutride can you add a list of components here of what will need to be delivered? We're trying to understand the stopping point of this effort and when it is complete.

**Comment by quarckster** [comment]
@rachael-phillips we would like to have OUIA compatible this list of components:
Alert
Breadcrumb
Button
Context Selector
Donut Chart
Dropdown
FormSelect
Nav
Pagination
Select
Switch
Table
Tabs
`Switch` has already an opend PR.

**Comment by rachael-phillips** [comment]
@quarckster thank you! Would it make the most sense to open separate issues to track this work or do you want to track it all here in this issue?

**Comment by quarckster** [comment]
@rachael-phillips I plan to open separate PRs for each component.
