### ISSUE TITLE
Disabled variation of pagination component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#2315]
Once we complete the work needed in core and add an example in https://github.com/patternfly/patternfly-next/issues/1963, let's offer a variation of the pagination in a disabled state.

This is related to @boaz0's issue https://github.com/patternfly/patternfly-next/issues/1785

**Comment by rachael-phillips** [comment]
@mcoker are we ready to get started on this on the React side?

**Comment by mcoker** [comment]
@rachael-phillips yep!
