### ISSUE TITLE
Component: Date Picker

### ISSUE THREAD

**Issue by sjd78** [patternfly/patternfly-react#232]
Provide an implementation for the Patternfly Date Picker.

See [Patternfly Bootstrap Datepicker widget](http://www.patternfly.org/pattern-library/widgets/#bootstrap-datepicker) and [Patternfly Form and Controls Datepicker](http://www.patternfly.org/pattern-library/forms-and-controls/datepicker/).

See PR #226

**Comment by sjd78** [comment]
My intention is to integrate the [DateTimePicker](http://jquense.github.io/react-widgets/api/DateTimePicker/) from [react-widgets](http://jquense.github.io/react-widgets/) and align with PF style and UX designs.

**Comment by ares** [comment]
hello, was there some progress? this would be very appreciated addition

**Comment by ares** [comment]
The PR is WIP

**Comment by rachael-phillips** [comment]
Hi @sjd78 are you still working on this?

**Comment by sjd78** [comment]
> Hi @sjd78 are you still working on this?

Unfortunately, I am not working on this anymore.

**Comment by ares** [comment]
There's alternative implementation - see https://github.com/patternfly/patternfly-react/pull/1420

**Comment by tlabaj** [comment]
A Date Picker was added via PR #1420
