### ISSUE TITLE
Application Launcher does not honor position "right"

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#2322]
Setting `position={DropdownPosition.right}` has no effect on the ApplicationLauncher

**Comment by rachael-phillips** [comment]
@jschuler making you aware of this one.

**Comment by jschuler** [comment]
@mcoker i think we're missing support for modifiers direction `up`: `.pf-c-app-launcher.pf-m-top` and position `right`: `.pf-c-app-launcher__menu.pf-m-align-right`

**Comment by tlabaj** [comment]
This was fixed in core.
