### ISSUE TITLE
PF4: Popover link not focusable

### ISSUE THREAD

**Issue by jiridostal** [patternfly/patternfly-react#2333]
Link in the Popover body is not focusable so it's not possible to click it.
Steps to reproduce:

1. Go to https://www.patternfly.org/v4/documentation/react/components/popover/
2. Edit source code for Simple popover (or any example on the page) so it contains an "a" element.
3. Click the "Toggle Popover" button and try to click the newly created link.

**Comment by rachael-phillips** [comment]
Hi @jiridostal is this blocking you or is this just a problem with the documentation on the site? @tlabaj making you aware.

**Comment by jiridostal** [comment]
Unfortunately I need this functionality to work, it happens everywhere not only in docs.

**Comment by rachael-phillips** [comment]
@seanforyou23 will the issue you reference totally resolve this issue?

**Comment by seanforyou23** [comment]
@rachael-phillips I do believe so. I added an example with a link in the [Popover demo](https://patternfly-react.surge.sh/patternfly-4/components/popover/), I'll close this issue for now - feel free to reopen if I overlooked anything.
