### ISSUE TITLE
PF4: Shadow DOM breaks selenium tests

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#2335]
Examples in https://www.patternfly.org/v4/documentation/react/components/ use Shadow DOM. Tests in https://github.com/RedHatQE/widgetastic.patternfly4 failed because Selenium doesn't support Shadow DOM yet.

**Comment by rachael-phillips** [comment]
Hey @redallen making you aware of this one

**Comment by jschuler** [comment]
Hi @quarckster, would it be possible to access the element as described in this article?
https://medium.com/rate-engineering/a-guide-to-working-with-shadow-dom-using-selenium-b124992559f

**Comment by jschuler** [comment]
I could also think of passing a URL attribute that turns off shadow dom

**Comment by quarckster** [comment]
@jschuler that could make things much easier!

**Comment by psav** [comment]
@quarckster I was wondering if the OUIA attribute is assigned to the outer container, assuming one shadow dom per component, we could easily access the innards

**Comment by quarckster** [comment]
@psav I don't think so because shadow host != component root.

**Comment by psav** [comment]
That's a shame :)

**Comment by jschuler** [comment]
@quarckster Would you be able to append `?shadow=false` to every link on the page?

**Comment by quarckster** [comment]
Yes, that will work I just need to change that line https://github.com/RedHatQE/widgetastic.patternfly4/blob/master/testing/conftest.py#L38

**Comment by jschuler** [comment]
@quarckster this change is in staging now. 
https://**staging**.patternfly.org/v4/documentation/react/components/alert/**?shadow=false**
Let me know if this doesn't work for you.

**Comment by quarckster** [comment]
@jschuler Thanks. It works!

**Comment by quarckster** [comment]
@redallen @jschuler can you please tell when the changes will go https://patternfly.org?

**Comment by redallen** [comment]
@quarckster It's been promoted now.
