### ISSUE TITLE
Spike: Investigating release automation 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2336]
cc @dgutride feel free to fill in with details

We would like to move towards a more automated release process. In this issue we should investigate the release process automation.

**Comment by redallen** [comment]
There's not much left to automate inside of this repo outside of #2549.

We would like to automate prerelease validation in products. Specific products should be picked and environments setup for them. Once given a list of products by @dgutride , we can look into leveraging infrastructure to do this for the easiest ones.

We would also like a more rigorous integration test suite to verify release promotions. This could be hidden behind a manual CircleCI trigger for now. Additional suites could include:
- Styles snapshot testing
- Aria compliance
- React-seed testing
