### ISSUE TITLE
Working Pagination example missing from docs

### ISSUE THREAD

**Issue by jamesla** [patternfly/patternfly-react#2337]
https://www.patternfly.org/v4/documentation/react/components/pagination/

I am looking at the docs for the Pagination component however it appears to be missing a working example and the props aren't clear enough for me to wire this up to a Table component.

I'm posting this as a bug as I'd probably argue that this documentation needs to be improved.

In the mean time is there a working example or example project (with a Pagination component included) that I could look through?

**Comment by rachael-phillips** [comment]
@jamesla what working example is missing?

**Comment by rachael-phillips** [comment]
@jschuler would you mind jumping in here and advising?

**Comment by jschuler** [comment]
Would be good to have a paginated table demo of this. @priley86 do you happen to have an example of this or have implemented this before?

**Comment by priley86** [comment]
hey @jschuler ! I think the closest I have come across of our PF4 Table integrated w/ Pagination is in Insights-Advisor-Frontend (and their Rules table):

https://github.com/RedHatInsights/insights-advisor-frontend/blob/3921ffabd8b864641b8d4f8a1d6fcdab60251de6/src/PresentationalComponents/RulesTable/RulesTable.js#L9

major kudos to @AllenBW for being an early adopter there! 🍏 

Agree it would be great to have an example of this in PF React...

**Comment by boaz0** [comment]
@priley86 can you assign this to me?
Thanks.

**Comment by jamesla** [comment]
@priley86 Thanks for the example I will have a read through. It would be also good if a really simple example of the most basic table with the most basic pagination component.

**Comment by tlabaj** [comment]
@boaz are you still interested in working on this?

**Comment by boaz0** [comment]
yes please.

**Comment by boaz0** [comment]
@tlabaj - yes please :pray:
