### ISSUE TITLE
PF4: Button type is missing in the Expandable Component

### ISSUE THREAD

**Issue by debsmita1** [patternfly/patternfly-react#2339]
The button type is missing, as a result the component behaves like a submit button on a form when clicked.

![Expandable](https://user-images.githubusercontent.com/22490998/60037062-4d8c9900-96ce-11e9-9a97-f60d749b9459.gif)

**Comment by rachael-phillips** [comment]
@debsmita1 is this blocking you currently or do you have a work around?

**Comment by debsmita1** [comment]
> @debsmita1 is this blocking you currently or do you have a work around?

@rachael-phillips  It isn't blocking me currently. I do have a workaround (I am using preventDefault() )

**Comment by tlabaj** [comment]
@rachael-phillips @christiemolloy I have opened an issue in core for this as well.[#1980](https://github.com/patternfly/patternfly-next/issues/1980)
