### ISSUE TITLE
PF4 Table: Pagination input field weird behavior

### ISSUE THREAD

**Issue by jiridostal** [patternfly/patternfly-react#2344]
It's almost impossible to enter page number in the pagination field.
Steps to reproduce using docs:
1. Go to https://www.patternfly.org/v4/documentation/react/components/pagination/
2. Try to enter different numbers in the page field - the first number stays in the field regardless backspace, overall experience is strange.

**Comment by rachael-phillips** [comment]
Hi @jiridostal would you consider this a bug or do you think this is more of a design flaw?

**Comment by jiridostal** [comment]
It was repeatedly reported on our app as a bug.

**Comment by rachael-phillips** [comment]
@jiridostal so it sounds like a blocker. Is that right or do you have a workaround?

**Comment by jiridostal** [comment]
I was not able to provide a workaround, I believe this needs to be fixed on PF side.

**Comment by jiridostal** [comment]
We got one more report recently - the page number field allows to use only two digits. As we have a lot of pages, it'd be good to have an option to enter at least 4 digits.

**Comment by rebeccaalpert** [comment]
@jiridostal - the width is controlled by patternfly-next; I opened an issue for that at https://github.com/patternfly/patternfly-next/issues/1996.

**Comment by ryelo** [comment]
Just an FYI, there was a bug that we filed for this:

https://github.com/patternfly/patternfly-next/issues/1536

We have a manual override we're doing in some cases that we can share @jiridostal
