### ISSUE TITLE
PF4 Tabs Typscript error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2345]
I installed the very latest pre-release packages and the Cost Management build generates 6 new TS errors with tabs. Looks like variant should be optional because there is a default.

<img width="277" alt="Screen Shot 2019-06-25 at 10 29 04 AM" src="https://user-images.githubusercontent.com/17481322/60106986-1650d300-9734-11e9-868d-9a60c11751f5.png">

<img width="800" alt="Screen Shot 2019-06-25 at 10 27 15 AM" src="https://user-images.githubusercontent.com/17481322/60106933-033e0300-9734-11e9-86b7-c1418b55627c.png">

**Comment by tlabaj** [comment]
Thanks for opening this Dan
