### ISSUE TITLE
Donut chart main label is misleading due to round up

### ISSUE THREAD

**Issue by ares** [patternfly/patternfly-react#2356]
Imagine you draw a donut chart for a fireman operator dashboard. It displays how many building in a city are on fire and how many are ok. Let's say there are 1000 buildings in the city. Now first starts burning, so we have 999 ok (green), 1 on fire (red). The donut chart will show only green color, and only after hovering over it, it says "99.9%", which is one problem, there's no visual indication of fire.

The second and the bigger one is, the main label says "100% ok" because it rounds up, I guess thanks to this line https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/patternfly-react/src/components/Chart/DonutChart.js#L24.

Poor fireman operator won't notice from the dashboard that one building is on fire, until the fire spreads to few more buildings.

**Comment by rachael-phillips** [comment]
@dlabrecq making you aware of this one

**Comment by rachael-phillips** [comment]
@ares is this blocking you at this time?

**Comment by dlabrecq** [comment]
@rachael-phillips FYI, this is an PF3 issue

**Comment by ares** [comment]
It's not blocking but the bug reported by customer has a big priority. @amirfefer will send a PR with the fix today I believe. And sorry for confusion, yes this is PF3 issue.

**Comment by ares** [comment]
The suggested fix - https://github.com/patternfly/patternfly-react/pull/2375

**Comment by rachael-phillips** [comment]
Thanks @ares and @dlabrecq !

**Comment by tlabaj** [comment]
Closed by #2375
