### ISSUE TITLE
PF4 tabs: ForwardRef error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2359]
Installed the latest pre-release packages with Cost Management and encountered a runtime error with tabs.

<img width="1747" alt="Screen Shot 2019-06-28 at 9 33 27 PM" src="https://user-images.githubusercontent.com/17481322/60378159-6659bf00-99ec-11e9-8b44-80a5be1859f2.png">

Package versions:
<img width="295" alt="Screen Shot 2019-06-26 at 8 47 05 AM" src="https://user-images.githubusercontent.com/17481322/60180872-fe8a5500-97ee-11e9-89b4-8582f216981a.png">

**Comment by mturley** [comment]
I'm guessing the TypeError is more serious than the forwardRef error, I'm not sure why forwardRef is even required there

**Comment by mturley** [comment]
@dlabrecq, I found someone with a similar issue: https://github.com/atomiks/tippy.js-react/issues/63
In their case it seems like it was either the wrong version of React, or a webpack issue, or a node_modules cache issue. Have you tried deleting `node_modules` and reinstalling? What version of React are you using in Cost Management?

**Comment by dlabrecq** [comment]
I encountered this issue before with the tab component. It was a result of not checking if children were undefined when tabs and tab content are split. I assume there is a similar issue after refactoring the code for typescript.

Note that this was working prior to converting tabs to typescript.

Yes, I've deleted node_modules.

"react-dom": "^16.6.3"

**Comment by dlabrecq** [comment]
FYI, this does not appear to be related to slightly different React versions. The versions in react-core and Cost Management have not changed for quite a while. The only recent change I see is the tab components were converted to typescript.

That said, my own debugging shows that the `forwardRef` property is required in `ForwardedRefProps` of `Tab.tsx`. Additionally, the `innerRef` property of `TabContext.tsx` has a type `React.Ref<HtmlElement>`, which should be the same type of `React.Ref<any>`.

Testing a fix with Cost Management now...

**Comment by mturley** [comment]
@seanforyou23 is this related to the changes we were discussing the other day about the updated version of Tippy? I wasn't sure if the code you were seeing problems with was merged or not

**Comment by dlabrecq** [comment]
Tippy is a separate issue https://github.com/patternfly/patternfly-react/issues/2400

**Comment by seanforyou23** [comment]
It's possible @mturley - we're using the workaround pattern tippy [recommends](https://github.com/atomiks/tippy.js-react#component-children) (using a `span` as an immediate child) until we come to conclusion on how we want to handle forwardRef across many components. It seems there's been a few approaches used in the codebase so this is probably a good time to align them.

I've got an open PR for some tippy enhancements, will link that to #2400
