### ISSUE TITLE
PF4: Build error when using react-core: 3.53.3 package

### ISSUE THREAD

**Issue by debsmita1** [patternfly/patternfly-react#2365]
I am trying to use the react-core's latest pre-release package 3.53.3 in the openshift/console code, and my build fails with an error

![Screenshot from 2019-06-26 20-10-22](https://user-images.githubusercontent.com/22490998/60203671-c4f72f80-986a-11e9-9fe9-ad6253c138e0.png)

**Comment by tlabaj** [comment]
Closing this issue.  #2400 is a duplicate  that is being worked on.
