### ISSUE TITLE
PF4 Select: Add isDisabled prop to the component

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#2366]
The consumer should be able to disable the Select component similar to the Dropdown.

This issue is dependent on the core issue [#1985](https://github.com/patternfly/patternfly-next/issues/1985)

@jschuler will be in charge on the PR review for this one.

**Comment by mcoker** [comment]
@tlabaj @kmcfaul the work for this is done in core, merged in https://github.com/patternfly/patternfly-next/pull/2028

**Comment by tlabaj** [comment]
Closed by #2678
