### ISSUE TITLE
babel-plugin-typescript-to-proptypes package does not reliably convert all typescript type definitions

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#2372]
Noticed that the dist js for ChartDonut only has about half of the prop types defined that it should. There are 54 props with type definitions in the source typescript file, and only 25 prop types in the resulting dist js.

**Comment by rachael-phillips** [comment]
@TheRealJon how high priority is this? Would you say this will block anyone?

**Comment by TheRealJon** [comment]
@rachael-phillips This shouldn't block anyone, it would just cause javascript console warnings in development mode.
