### ISSUE TITLE
PF4: Pagination - page number converted to three dots

### ISSUE THREAD

**Issue by jiridostal** [patternfly/patternfly-react#2374]
A bug report to our app says "Page number is lost and replaced w/ "..." if I click to the last page. See attached images.". 
It was created on Mac, I was not able to reproduce it on Fedora Firefox nor Chrome.
![image](https://user-images.githubusercontent.com/6286045/60249670-8cd10a80-98c5-11e9-97c8-f7edafea38c8.png)

**Comment by katierik** [comment]
There is some more strange behavior I am seeing with this number selector.
I cannot type a number in it and get the correct result. e.g. I tried to type "20" to go direct to p20 and got some strange responses: http://www.giphy.com/gifs/kdoQOkTSp1gnldR0F9

**Comment by rebeccaalpert** [comment]
This is related to a text-overflow: ellipsis style from React Core. I opened an issue there at https://github.com/patternfly/patternfly-next/issues/2000.

**Comment by rebeccaalpert** [comment]
This is still a bug.
