### ISSUE TITLE
Exclude internal properties from docs

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2380]
Props that look like:
```js
  /** Internal index of the option */
  index?: number;
```
shouldn't show.

**Comment by SpyTec** [comment]
Wouldn't items with `@private` JSDoc property be better?

```js
  /** 
  * Internal index of the option 
  * @private 
  */
  index?: number;
```

Or if docs are built with JSDoc in mind, it would be possible to use `@protected` instead and explicitly tell the docs builder to ignore them

**Comment by redallen** [comment]
I prefer the JSDoc route! I'm going to have to parse the string either way since JSDoc isn't used, but I'm all for a standard.

**Comment by redallen** [comment]
Duplicate of #2139
