### ISSUE TITLE
VerticalNav combined with Link from react-router-dom

### ISSUE THREAD

**Issue by lucasponce** [patternfly/patternfly-react#239]
Perhaps this question is quite simple but I don't see an obvious way to combine something like:
```
import * as React from 'react';
import { VerticalNav } from 'patternfly-react';
import { Link } from 'react-router-dom';

const { Masthead, Item } = VerticalNav;

class Navigation extends React.Component {
  render() {
    return (
      <VerticalNav sessionKey="navigationSessionKey">
        <Masthead title="My App" />
        <Item title="Services" iconClass="fa fa-home">
                <Link to={'/services'}>Service List</Link>
        </Item>
      </VerticalNav>
    );
  }
}

export default Navigation;
```

or this other attempt

```
      <VerticalNav sessionKey="navigationSessionKey">
        <Masthead title="My App" />
        <Link to={'/services'}>
           <Item title="Services" iconClass="fa fa-home" />
        </Link>              
      </VerticalNav>
```
seems to not work properly.

Any advice about how to use this component ? 

I see in https://github.com/patternfly/patternfly-react-demo-app/blob/master/src/components/Nav/VerticalNav.js that the component is completely re-written and I would like to re-use it.

Any idea ?

Thanks,
Lucas

**Comment by jeff-phillips-18** [comment]
@lucasponce Did you see the storybook for Vertical Nav at https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=Vertical%20Navigation&selectedStory=Items%20as%20JSX&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

Have you been able to proceed?

**Comment by lucasponce** [comment]
@jeff-phillips-18 yeah, but unfortunately the Vertical Nav is not very friendly with the Link component, I guess it is not yet supported (or I didn't find a good way to use it without re-implementing the component in plain div+style).

So, we used a workaround invoking the history of the router.

https://github.com/kiali/swsui/blob/master/src/components/Nav/Navigation.tsx#L59

If in future versions of the component, the Link component can be use, I guess we can refactor this.

**Comment by theute** [comment]
@jeff-phillips-18 Looks like it shows as "assigned" in the board but @dtaylor113 unassigned himself.
It's blocking us for https://issues.jboss.org/browse/KIALI-989 could we please make sure this doesn't fall through the cracks ?
Thanks!

**Comment by jeff-phillips-18** [comment]
I have implemented vertical navigation with `react-router` (not using `<Link>`). There is an example of this at https://github.com/quipucords/quipucords/blob/master/client/src/components/app.js

If you need to use `react-router-dom` and `<Link>` then I can try to get something like that to work.
