### ISSUE TITLE
feat(accordion): update examples and html structure.

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2390]
Related to this issue in Core: https://github.com/patternfly/patternfly-next/issues/1913 

In Core we added a new example and updated an old example of the Accordion, so that now there is one example that uses just `<div>` and `<h1 - h6>` in its html markup, and another that uses "definition list" `<dl>`, `<dt>` and `<dd>` in its html markup.

In Core we don't have defaults the same way that React does, but its important to keep the example order the same from Core to React. @jgiardino suggested that the default in React may be the definition list, and then if a user specifies a heading level it will use divs and h1-h6. https://github.com/patternfly/patternfly-next/pull/1990#issuecomment-506466771

**Comment by rachael-phillips** [comment]
@boaz0 will #2422 solve this issue?

**Comment by boaz0** [comment]
@rachael-phillips yes it will.
