### ISSUE TITLE
Add types to buttons

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2391]
Related to https://github.com/patternfly/patternfly-next/issues/1980 and https://github.com/patternfly/patternfly-next/pull/1982

Buttons now have a type of "button" by default. If buttons are used to submit data at the end of a form, then they use the "submit" type, and if they are used to reset data in a form they use the "reset" type.

This also adds a default type of "button" to the expandable button so that it fixes the bug of when it was used in a form and it was defaulting to the type "submit".

@dlabaj for PR review

**Comment by rachael-phillips** [comment]
We won't address this for the Albatross release if the build is fine but plan to pick this up for Bluebird

**Comment by rachael-phillips** [comment]
We are going to investigate this
