### ISSUE TITLE
Size change in Progress Component

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2393]
Related to : https://github.com/patternfly/patternfly-next/pull/1974

Font-size for the `pf-m-sm` variation of the progress size has been changed. Not sure if anything needs to happen in React here. Feel free to close the issue if it doesn't.

**Comment by rachael-phillips** [comment]
Can close once we update

**Comment by tlabaj** [comment]
Closed by PR #2397
