### ISSUE TITLE
toggle rotation

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2394]
Related to: https://github.com/patternfly/patternfly-next/pull/1932

We added variables for the transform() property and the transition() property. This issue should be used to verify that the transitions set on "toggle elements" in components work properly.

**Comment by jessiehuff** [comment]
I tested the following components for the toggle element transitions on the React side, and they all appear to work: 
* accordion
* clipboard copy
* data list
* expandable
* nav
* table
* wizard toggle

Looks great, Christie! :)
