### ISSUE TITLE
Unable to click options menu check on the right hand side.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#2415]
There's an area between the text and the check that does not respond to click events when a user clicks in that area.  See screenshot below.

<img width="184" alt="Screen Shot 2019-07-01 at 11 18 26 AM" src="https://user-images.githubusercontent.com/6126356/60450229-637eea00-9bf7-11e9-91c7-21d8523547a9.png">
@dlabaj for PR review

**Comment by boaz0** [comment]
IMO it's a problem with core. There are sub elements in the button that are clickable which prevents the event to bubble to the button.

To fix this we need to set something like:

```
.pf-c-button > * {
  pointer-events: none;
}
```

**Comment by dlabaj** [comment]
@mcoker Can you take a look to see if this is a core issue.

**Comment by mcoker** [comment]
@dlabaj weird, I can click anywhere in the button and select something in the options menu. However if I have already selected something in the "single option" example, clicking on the check icon or it's padding toggles the selection. But in the plain, right aligned, top aligned and plain with text examples it's the opposite - clicking on the check icon does nothing, but clicking on the text toggles the selection.

The event should be on the button itself, so clicking anywhere in the button should trigger the selection.

**Comment by mcoker** [comment]
@jenny-s51 we have icons in the [link variation of button](https://patternfly-react.surge.sh/patternfly-4/components/button/) and [App launcher w/ sections and icons](https://patternfly-react.surge.sh/patternfly-4/components/applicationlauncher/). Do you know if those components have the same problem?

**Comment by jenny-s51** [comment]
@mcoker Just checked -- I don't think so! Neither of those seem to have this problem.

**Comment by mcoker** [comment]
@jenny-s51 thanks! Do you know why, and what the difference is as to why the options menu needs it?

**Comment by jenny-s51** [comment]
Closing via #2513
