### ISSUE TITLE
Fail build for PRs with a commit that says "Breaking change"

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#2416]
Remove the "breaking change" option from `yarn commit` script.  This way contributors will not inadvertently bump the react-core version

**Comment by redallen** [comment]
Even if we remove it, they can always add it to commit messages using `git commit`. Even if we lint them with Husky, they can still bypass them.

It's on me to do some scripting to detect `\n\nBreaking change:` in commit messages in CircleCI and fail the build. It'd be a good thing to add to the `lint` stage.
