### ISSUE TITLE
Add 2xl breakpoint to [hidden/visible]On[breakpoint] table cell visibility classes

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#2436]
we have a new breakpoint `$pf-global--breakpoint--2xl` that should be supported with both `visibleOn` and `hiddenOn` with the `classNames(Visibility.hidden, Visibility.visibleOnMd, Visibility.hiddenOnLg, ...)` classes.

**Comment by tlabaj** [comment]
@priley86 for review of PR

**Comment by priley86** [comment]
sounds good... should be a simple add here hopefully:

https://github.com/patternfly/patternfly-react/blob/fdbde6d0fa3e6151300f1bbb8322a3308fb606c0/packages/patternfly-4/react-table/src/components/Table/utils/decorators/classNames.js

**Comment by kmcfaul** [comment]
Closed in #2676
