### ISSUE TITLE
PF4: Trigger of widgetastic.patternfly4 tests was deleted

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#2440]
PR #2287 removed a curl command that sends a POST request to Travis that triggers browser tests from https://github.com/RedHatQE/widgetastic.patternfly4/tree/master/testing. This request should be returned back and should be sent when https://www.patternfly.org/v4/documentation/react/components/ is updated. Curl command:
```
curl -s -X POST \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Travis-API-Version: 3" \
    -H "Authorization: token $QUARCKSTER_TOKEN" \
    -d '{"request": {"branch": "master"}}' \
    https://api.travis-ci.org/repo/RedHatQE%2Fwidgetastic.patternfly4/requests
```

@tlabaj for PR review

**Comment by redallen** [comment]
It's much trickier if you're testing against patternfly.org. There is no build that runs to update patternfly.org.

Right now, staging.patternfly.org gets updated by a build in https://github.com/patternfly/patternfly-org and is occasionally copied over to patternfly.org. However, if you're testing against patternfly-react.surge.sh, I can add that to our build here.

Let me know how you'd like to proceed. I can create a script to update patternfly.org and add a `curl` command at the end.

**Comment by quarckster** [comment]
We used to tests against patternfly-react.surge.sh but some components are broken there so we switched to patternfly.org. It's not clear for me when documentation page with components on patternfly.org is updated. What does mean "occasionally"? Someone update it manually? Anyway, if documentation on staging.patternfly.org reflects the latest commit from master it will be enough for us.

**Comment by dgutride** [comment]
@quarckster  - staging.patternfly.org is not directly related to patternfly-react master - those updates happen close to once a month right now - if you want to test against a nightly build of patternfly.org, we'd have to build something different for you

**Comment by redallen** [comment]
To make it clearer, these are your choices for webpages to test against.

1. https://patternfly-react.surge.sh -> updated most frequently on every push to `master` on this https://github.com/patternfly/patternfly-react
2. https://staging.patternfly.org -> updated less frequently on every push to `master` on https://github.com/patternfly/patternfly-org
3. https://patternfly.org -> updated monthly by manually copying staging over

1) and 2) are trivial to implement by adding your `curl` to the end of a CircleCI/Travis build script on one of the two repos (or both, if you wish). 3) would require writing a script to make the process less manual, which we are headed toward anyway.

You also will probably be interested in #2304 which can help with testing.

**Comment by quarckster** [comment]
@redallen @dgutride I checked https://patternfly-react.surge.sh it seems all previous issues were fixed and we can use it to test the components from the master. So let's just return `curl` command to the same place where it was before.
