### ISSUE TITLE
PF4: Typeahead select input does not have isLoading property 

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#2444]
PF3 TypeAheadSelect has an Async variant which allows the users to show a spinner if the 'isLoading' property was passed.

It's really useful for my usecase because there is another dialog field which auto-fill the default value of this component, but this is done asynchronously.
This I need an indicator this the default value is being searched for.

**Comment by tlabaj** [comment]
@mcarrano Is this a feature we plan on supporting.  We do not have a design for this.

**Comment by mcarrano** [comment]
No, we don't have a design for this @tlabaj but I can see how this can be useful. I will open a core issue for this to consider as an enhancement request. @LHinson @rachael-phillips FYI.

**Comment by KKoukiou** [comment]
Commenting so that the bot will not close the issue for start.
Any update on this?

**Comment by mcarrano** [comment]
@tlabaj Would it be easy to implement something like this now that we have a spinner @tlabaj ?

![select-with-spinner](https://user-images.githubusercontent.com/6619860/64879858-e1fafd80-d624-11e9-833d-e8e396162708.png)

Would it require any core implementation?  Let me know if this is what you had in mind @KKoukiou . It will still need to get into our release plan.

**Comment by tlabaj** [comment]
Yes.  Since we have a spinner, the consumer should be able to add it instead of DropDownItems if data is loading.
@KKoukiou can we close this issue now?

**Comment by KKoukiou** [comment]
> @tlabaj Would it be easy to implement something like this now that we have a spinner @tlabaj ?
> 
> ![select-with-spinner](https://user-images.githubusercontent.com/6619860/64879858-e1fafd80-d624-11e9-833d-e8e396162708.png)
> 
> Would it require any core implementation? Let me know if this is what you had in mind @KKoukiou . It will still need to get into our release plan.

Right, I imagined something like this indeed.

**Comment by KKoukiou** [comment]
Commenting for the stale bot to remove the wontfix.

**Comment by tlabaj** [comment]
Hi Katerina.  In our last release we added the ability to add custom content to the Select menu with `customContent` prop.  You would need to set the `selectVariant` to `"panel"` and have the `customContent` prop be the loading spinner e.g.
  ```
<Select
        variant={SelectVariant.panel}
        customContent={
          <EmptyState>
            <EmptyStateIcon variant="container" component={Spinner} />
            <Title size="lg">Loading</Title>
          </EmptyState>
        }
        placeholderText="Filter by birth month"
      />
```
Here is an example of how that might look: 

![image](https://user-images.githubusercontent.com/39532947/70173190-57b0bb80-16a0-11ea-888e-04db9df674d0.png)

Let me know if you have any further questions.
