### ISSUE TITLE
Should the page component sidebar collapse on mobile when you click anywhere outside of the sidebar?

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#2454]
Resulting from a discussion about the [drawer component in core](https://github.com/patternfly/patternfly-next/issues/1786). On mobile, if the sidebar is open, should clicking on anything outside of the sidebar automatically collapse it? 

cc @mcarrano @kybaker

**Comment by dlabaj** [comment]
@mcarrano @kybaker We can do this in react if this is what the interaction is intended to be.

**Comment by mcarrano** [comment]
Yes, this is what we want @dlabaj . The logic is that if I open the nav, but then click on something else, the nav should just close.

**Comment by QasimRRizvi** [comment]
Is there any way to close the drawer by clicking outside?
