### ISSUE TITLE
PF4: tooltips don't work on disabled DropdownItem

### ISSUE THREAD

**Issue by elad661** [patternfly/patternfly-react#2470]
I have a `<Dropdown>`, inside which there are some `<DropdownItem>`s. Some dropdown items are disabled and have tooltips, for example:

```jsx
<DropdownItem component="button" isDisabled tooltip={<span>Explanation about why this is disabled</span>}>item name</DropdownItem>
```

This doesn't work. Looking at the React inspector, I can see that the `<Tooltip>` inside exists, but it doesn't show when I hover with the mouse over the item. If I remove the `isDisabled`, the tooltip works - but my only usecase for tooltips here is to explain why certain menu items are disabled, so this doesn't help much.

Versions (I believe these are the latest as of today, but I'm never sure):
    "@patternfly/patternfly": "2.17.2",
    "@patternfly/react-core": "3.62.1"

**Comment by elad661** [comment]
The root cause of this issue seems to be this CSS rule:

```css
.pf-c-dropdown__menu-item:disabled, .pf-c-dropdown__menu-item.pf-m-disabled {
    pointer-events: none;
```
This disables any pointer event on the dropdown item, including hover / mouseenter, so the event handler to show the tooltip is never called.

Does this mean I need to move this issue to patternfly/patternfly-next? (I don't know where this style comes from exactly)

**Comment by rachael-phillips** [comment]
@mcoker does this need to be fixed in Core first? cc @tlabaj

**Comment by rachael-phillips** [comment]
@elad661 is this currently blocking you?

**Comment by mcoker** [comment]
@rachael-phillips from glancing at it, I don't think so, though it depends on what the ultimate solution is. We may need to make a modification in core, or we may just need to document a technique that allows for the tooltip to display on a disabled element, like @elad661's suggestion of wrapping the disabled element in another element that has the event handler that triggers the tooltip.

**Comment by rachael-phillips** [comment]
@elad661 is this currently blocking you?

**Comment by elad661** [comment]
@rachael-phillips sorry for the delay, missed your initial question -  it's not blocking me, our UX designer said we can just not show the tooltips for now. However, I still think this needs to be fixed.

**Comment by rachael-phillips** [comment]
Thank you for the details @elad661 !

**Comment by cben** [comment]
@elad661 we still want this, right?
cloud.redhat.com/openshift still has dropdowns with disabled items without tooltip explanation.

**Comment by elad661** [comment]
Yes, I still think this is needed and I don't think this should've been marked as stale.
