### ISSUE TITLE
PF4: Chart tooltip is unresponsive

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#2482]
When I use bar chart with title and hover over different values the title is not rendering correctly and jumps over different values.

![Peek 2019-07-09 14-08](https://user-images.githubusercontent.com/3439771/60886865-4da2a200-a253-11e9-9b72-ee8efda1a7f5.gif)

**Comment by karelhala** [comment]
@rachael-phillips ping this is quite urgent because our UX person is currently designing report tool that will show bar chart with titles.

**Comment by dlabrecq** [comment]
This tooltip functionality is provided by Victory; however, tooltips can be applied to charts differently. 

In this particular example, we overrode the chart's containerComponent property. However, you can add a tooltip directly to the bar component itself.

See https://formidable.com/open-source/victory/guides/tooltips#simple-tooltips

**Comment by dlabrecq** [comment]
We may change the examples so that bar chart example does not use VoronoiContainer.

**Comment by dlabrecq** [comment]
FYI, the issue appears to be resolved if you set `voronoiDimension`, like so:

`containerComponent={<ChartVoronoiContainer labels={datum => `${datum.name}: ${datum.y}`} voronoiDimension="x"/>}`

**Comment by dlabrecq** [comment]
Added the `voronoiDimension` prop to fix the tooltip hover for our bar chart examples. Then, modified the stack chart example to show how tooltips are applied without a voronoi container.

https://github.com/patternfly/patternfly-react/pull/2497

**Comment by rachael-phillips** [comment]
Hi @karelhala I'm sorry for the delay - I was away and just got back from pto. @dlabrecque did we resolve @karelhala's issue?

**Comment by dlabrecq** [comment]
I believe so. I was able to correct the bar chart example
