### ISSUE TITLE
Select has no max height

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2483]
Select has no `max-height`, meaning that for long lists it will expand every entry. A height limit should be imposed so it can become scrollable

**Comment by tlabaj** [comment]
@mcoker can you please take a look at this one too

**Comment by mcoker** [comment]
@mcarrano can you weigh in on this one?

**Comment by mcarrano** [comment]
I don't feel strongly about this one @mcoker but I do see @SpyTec 's point. I can see arguments both ways. Maybe we add the ability to set max-height as an option? What do you think?

**Comment by SpyTec** [comment]
Though if max-height was an optional thing, would #2485 be possible? Given hundreds of entries, would there then be a different component more suitable?

**Comment by rachael-phillips** [comment]
@mcoker and @mcarrano what are your thoughts to @SpyTec 's comment above?

**Comment by mcoker** [comment]
I agree setting a `max-height` as an optional variation would be useful, though I don't understand the technical implications of a virtual scroller, so not sure why it wouldn't (maybe?) be possible if the choice to limit the height was a prop?

I'm also not sure if another component would be more suitable. I suppose it depends on the use case - maybe a selectable table or datalist with the option for filtering and/or pagination?

**Comment by SpyTec** [comment]
> I agree setting a `max-height` as an optional variation would be useful, though I don't understand the technical implications of a virtual scroller, so not sure why it wouldn't (maybe?) be possible if the choice to limit the height was a prop?

I've never implemented a virtual scroller myself. Though from my POV it would seem like a lot of work to implement if it will only be used if max-height is active.

> I'm also not sure if another component would be more suitable. I suppose it depends on the use case - maybe a selectable table or datalist with the option for filtering and/or pagination?

All of these require you to have visible data that isn't hidden behind a dropdown, and it would need to occupy space and not be floating like dropdowns do.

**Comment by tlabaj** [comment]
cc @priley86  Can you weigh in here please.

**Comment by mceledonia** [comment]
Chiming in here, I don't think it would hurt to have as an option, but I'd concur that if you had a dropdown with enough items for this to be an issue another design approach would be worth considering. Maybe that's something we suggest in design documentation. How does it currently behave when the dropdown list extends beyond the browser height in say a mobile size viewport?

**Comment by mcoker** [comment]
@mceledonia it overflows the viewport and you have to scroll the window

![Sep-06-2019 10-42-39](https://user-images.githubusercontent.com/35148959/64441295-346f7380-d093-11e9-809e-4ab320a2575a.gif)

**Comment by mcarrano** [comment]
Select lists (unlike dropdowns) could have lots of items if the contents are being loaded from some data set. That's why the type-ahead select is useful because it provides a way to filter the list of choices to something more manageable. For this reason, I think allowing the consumer to set a max height and then scroll makes sense.
