### ISSUE TITLE
Missing .css in import after 5bbc4a25d

### ISSUE THREAD

**Issue by marusak** [patternfly/patternfly-react#2484]
Commit https://github.com/patternfly/patternfly-react/commit/5bbc4a25dba7b351cfd0c174d15eb1b28eda3384 had broken build for us. Now I see following error:
```
@import '~react-bootstrap-typeahead/css/Typeahead';
    ^
    Can't resolve 'react-bootstrap-typeahead/css/Typeahead' in '/home/mmarusak/cockpit/cockpit/node_modules/patternfly-react/dist/less'
```
If I write there `.css` back it works again.

**Comment by redallen** [comment]
Weird, if I add `.css` it breaks. I'll see if there's a way to add it back without breaking.

**Comment by redallen** [comment]
Adding it back to the SASS doesn't work for the importer, but adding it back to the LESS doesn't matter for our build. Let me know if it fixes your build once merged.

**Comment by marusak** [comment]
Thank you for quick fix! For us it was only missing in .less file, so the PR fixes that.

**Comment by redallen** [comment]
Happy to help. Thanks for reporting the bug!
