### ISSUE TITLE
Select has no virtual scroller

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2485]
Related to #2483. Once Select is scrollable I think a virtual scroller would be a good improvement. The performance gains of utilizing a virtual scroller far surpasses native scrolling.

**Comment by jenny-s51** [comment]
Hi @SpyTec, since #2483 is closed, does that mean select is currently scrollable? Just wondering if there's anything blocking this issue, or if I can start working on it

**Comment by SpyTec** [comment]
Hi Jenny, since there's now a max height prop there shouldn't be anything blocking this. I know table has virtual scrolling if that's something we can use
