### ISSUE TITLE
PF4 Datalist: hiddenOn2Xl and visibleOn2Xl breakpoints do not work

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#2490]
This is a follow up  issue for the PR #2251.  The hiddenOn2Xl and visibleOn2Xl breakpoints still not working when merged.

**Comment by redallen** [comment]
@mcoker verified this works in master [in this comment](https://github.com/patternfly/patternfly-react/pull/2251#issuecomment-509763029), likely the PR preview previously tested against didn't get updated. Reopen if there's still an issue.
