### ISSUE TITLE
EmptyStateBody does not allow DOMNesting

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#2494]
EmptyStateBody is wrapper around `<p>` and so we can't use many HTML tags inside the body because of `Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
` etc.

https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateBody.tsx#L17

I propose to change it to `<div>`

**Comment by tlabaj** [comment]
@mcoker thoughts on this one?

**Comment by mcoker** [comment]
@rvsia thanks for the issue! We changed `.pf-c-empty-state__body` from a `<p>` to a `<div>`  in core back in April, and looks like we missed requesting this change to be updated in react. https://github.com/patternfly/patternfly-next/commit/14cc89873991781f26cb2d4f2c916ccbc80d8aae

**Comment by rvsia** [comment]
Thank you for quick response! :+1:

**Comment by tlabaj** [comment]
closed by #2499
