### ISSUE TITLE
Abusing the __mocks__ folder

### ISSUE THREAD

**Issue by sharvit** [patternfly/patternfly-react#250]
**The `__mocks__` folder became a very popular convention in this project.**
It mostly used to wrap components and demonstrate them in a storybook.

But, the jest framework has a totally different story about it:
> Create a manual mock by saving a mock implementation in the __mocks__ folder. This allows you to specify the implementation, and it can be used across test files.

**Those manual mocks can be an amazing tool when writing tests!**
https://facebook.github.io/jest/docs/en/manual-mocks.html

There is any reason why we are abusing the `__mocks__` convention?
Should we take some action and migrate?

So many mocks:
![patternfly-react-mocks](https://user-images.githubusercontent.com/1262502/36630083-5c6f471c-1969-11e8-96b8-4b1d32306b75.png)

**Comment by priley86** [comment]
Yea...+1 Avi. I think mocks folder can really be used for auto mocking like Jest describes (am using that feature downstream now). I think we can move current mocks into “Stories” folder and start to use mocks for auto mocks in our tests?

**Comment by priley86** [comment]
Thanks for raising this!

**Comment by priley86** [comment]
@sharvit do you want to take a stab at addressing this one? Would be nice to resolve it now that you mention it...

**Comment by sharvit** [comment]
@priley86 I want to but not sure it can fit into my work schedule for the next 2-3 weeks.

Let keep tracking it for a while and if no one will take it, i will :+1:

**Comment by priley86** [comment]
@sharvit i'm happy to clean this up. I think after discussing a bit w/ @jeff-phillips-18, we will move them into "Stories" and rename the `[Mock]Component.js`'s existing in `__mocks__` to `Stories/Component[Manager].js`. This should be more consistent but I just wanted to make sure that the example stateful managers are denoted differently from others. I'll take a stab at this over the week and we can continue to iterate...

**Comment by priley86** [comment]
probably need to add some conventions to contributing.md on this too...

**Comment by sharvit** [comment]
@priley86 What about `ComponentPattern.js`?
https://github.com/patternfly/patternfly-react/pull/256
