### ISSUE TITLE
Filter component in PF4

### ISSUE THREAD

**Issue by lucasponce** [patternfly/patternfly-react#2501]
Kiali uses PF3 Filter component [1] to implement one of the main features which requires multi-dimensional + multi-value filtering.

Patternfly 4 has some design guidelines in [2] but there is not an implementation for PF4 + React.

So, that limitation prevents us to run a full migration to PF4, as we should to implement a custom filter to have same features we had in PF3.

Our expectation is if PF4 could also provide a similar component that exists in PF3.

[1] https://github.com/patternfly/patternfly-react/tree/master/packages/patternfly-3/patternfly-react/src/components/Filter

[2] https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters

**Comment by rachael-phillips** [comment]
Hi @lucasponce, do you mind adding this issue to our next repo?

**Comment by lucasponce** [comment]
https://github.com/patternfly/patternfly-next/issues/2077

**Comment by abonas** [comment]
@serenamarie125 fyi
