### ISSUE TITLE
Add aria-role to charts

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2507]
From @mattnolting in #2500 :
> The data presented is not traversable... Some possible approaches are adding `role="group"` to charts, then selectively adding `role="presentation"` to elements we want to hide from SRs. Another is to generate a hidden table that contains the data represented visually.

**Comment by dlabrecq** [comment]
This appears to be a dup of https://github.com/patternfly/patternfly-react/issues/2507
