### ISSUE TITLE
PF4: Accordion renders children twice

### ISSUE THREAD

**Issue by matankb** [patternfly/patternfly-react#2521]
The `<Accordion>` component renders its children twice, as shown by  [the examples in the docs](https://www.patternfly.org/v4/documentation/react/components/accordion/). This seems to be caused by an issue on line 27  in `/dist/esm/Accordion.js`:

```javascript
  return React.createElement("dl", _extends({
    className: css(styles.accordion, className),
    "aria-label": ariaLabel
  }, props), React.createElement(AccordionContext.Provider, {
    value: headingLevel
  }, children), children);
```

The issue doesn't appear in `/dist/js/Accordion.js`.

**Comment by boaz0** [comment]
Hi @matankb 
This was fixed as you can see [here](https://patternfly-react.surge.sh/patternfly-4/components/accordion/) . Make sure you're using the latest of PF-4 (v3.58.1)

**Comment by redallen** [comment]
Closing as this doesn't appear in the latest [@patternfly/react-core](https://www.npmjs.com/package/@patternfly/react-core). Feel free to reopen.
