### ISSUE TITLE
Track @patternfly/patternfly versions in the IncrementalBuild

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2532]
We should add in some logic to the incremental build to also keep track of our `@patternfly/patternfly` versions and which packages change their `dist` depending on it, like `react-tokens` and `react-styles`.

**Comment by rachael-phillips** [comment]
Hi @redallen what priority do you think this is?

**Comment by redallen** [comment]
Low. Easy workaround is just running `yarn clean`.
