### ISSUE TITLE
Tri-State Checkbox Dropdown Example Request

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#2537]
Request for a demo/example for how to incorporate the [tri-state checkbox](https://patternfly-react.surge.sh/patternfly-4/components/checkbox/) with the [split button dropdown](https://patternfly-react.surge.sh/patternfly-4/components/dropdown/).

We've received a UX design that combines these two components, but there's not clear examples on how to make these two things work well together.

![tri-state-cb-dropdown](https://user-images.githubusercontent.com/5942899/61463282-11053380-a942-11e9-9213-a0b0e90d702f.png)

**Comment by mcarrano** [comment]
We have an open issue to introduce a tri-state checkbox here: https://github.com/patternfly/patternfly-next/issues/1411 This is currently in the Core backlog.
