### ISSUE TITLE
Epic: Refactor Wizard

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#2540]
I'm creating this epic to aggregate a number of issues that have come up regarding changes requested to our Wizard approach.

These roughly include:
* Removing the wizard from the modal to allow for "in-page" variants.
* Updating the stepper design.
* Creating an "in-page" wizard demo.

This will include some breaking changes as we'd need to revise the current modal-only approach.

**Comment by mcarrano** [comment]
@rachael-phillips @LHinson is this still something on our roadmap?

**Comment by rachael-phillips** [comment]
@mcarrano, no I do not see it on our roadmap currently.
