### ISSUE TITLE
Donut Chart - SVG tooltip overflow properties

### ISSUE THREAD

**Issue by kialam** [patternfly/patternfly-react#2541]
Existing tooltips for donut charts do not account for their bounding box edges.
![Screen Shot 2019-07-18 at 11 35 43 AM](https://user-images.githubusercontent.com/2293210/61471139-3b5ded80-a950-11e9-8c88-e4e1a4d36b26.png)
![Screen Shot 2019-07-18 at 11 45 02 AM](https://user-images.githubusercontent.com/2293210/61472034-a2c86d00-a951-11e9-9baa-984b570a0923.png)

When a chart is placed either on the left or right side in a page layout, the tooltip overflow properties do not extend beyond their bounding box left or right edges respectively. If either of the left or right edges of the chart is flanked by the edge of the browser window, there is no possibility of tooltip displaying beyond that edge, regardless of what z-index is set. In this use case, the tooltip positioning should be transverse relative to it's bounding edge.

**Comment by dlabrecq** [comment]
Overflowing the chart container isn't always desired. However, there are a couple ways you can address tooltips.

1. Make the container large enough to accommodate the tooltip.
2. Use a style to set overflow.

There are various examples showing how to make the container large enough for legends, for example, 

The Sparkline example shows overflow in action.

<img width="218" alt="Screen Shot 2019-07-19 at 8 31 42 AM" src="https://user-images.githubusercontent.com/17481322/61535370-1de85c80-aa00-11e9-9805-868be0d18b7a.png">

<img width="738" alt="Screen Shot 2019-07-19 at 8 31 29 AM" src="https://user-images.githubusercontent.com/17481322/61535381-22147a00-aa00-11e9-85cd-94fb18f07c2f.png">

**Comment by dlabrecq** [comment]
Overflowing the chart container isn't always desired. However, there are a couple ways you can handle tooltips.

1. Make the container large enough to accommodate the tooltip.
2. Change the SVG scale -- see docs for height & width
3. Use CSS to set SVG overflow
4. Provide a custom tooltip

There are various examples showing how to make the SVG & parent container large enough to accommodate legends and labels. With that approach, the `height` and `width` of the SVG is made larger, while `donutHeight` and `donutWidth` limit the size of the donut itself.

The Sparkline example also shows how to use SVG overflow, allowing tooltips to extend beyond the chart boundary. Although, margins may be necessary if the donut is against the window edge.

<img width="218" alt="Screen Shot 2019-07-19 at 8 31 42 AM" src="https://user-images.githubusercontent.com/17481322/61535370-1de85c80-aa00-11e9-9805-868be0d18b7a.png">

<img width="738" alt="Screen Shot 2019-07-19 at 8 31 29 AM" src="https://user-images.githubusercontent.com/17481322/61535381-22147a00-aa00-11e9-85cd-94fb18f07c2f.png">

There's quite a bit you can do with a custom tooltip. For example, you can set properties like height, width, orientation, etc. You can even provide your own label and flyout components. With a couple tweaks, I was able to change where Victory positions the tooltip:

<img width="528" alt="Screen Shot 2019-07-20 at 12 22 30 AM" src="https://user-images.githubusercontent.com/17481322/61573927-a4468200-aa84-11e9-8246-3143694a1b5c.png">

See: https://formidable.com/open-source/victory/docs/victory-tooltip

**Comment by dlabrecq** [comment]
Overflowing the chart container isn't always desired. However, there are a couple ways you can handle tooltips.

1. Resize the container to accommodate the tooltips
2. Change the SVG scale -- see docs for height & width
3. Use CSS to set SVG overflow
4. Provide a custom tooltip

We have various examples showing how to resize the SVG & parent container to accommodate legends and labels. With that approach, the `height` and `width` of the SVG is made slightly larger than the donut, while `donutHeight` and `donutWidth` limit the size of the donut itself.

The Sparkline example also shows how to use SVG overflow, allowing tooltips to extend beyond the chart boundary. Although, margins may be necessary if the donut is against the window edge.

<img width="218" alt="Screen Shot 2019-07-19 at 8 31 42 AM" src="https://user-images.githubusercontent.com/17481322/61535370-1de85c80-aa00-11e9-9805-868be0d18b7a.png">

<img width="738" alt="Screen Shot 2019-07-19 at 8 31 29 AM" src="https://user-images.githubusercontent.com/17481322/61535381-22147a00-aa00-11e9-85cd-94fb18f07c2f.png">

In addition, there's quite a bit you can do with a custom tooltip. For example, you can set properties like height, width, orientation, etc. You can even provide your own label and flyout components. With a couple tweaks, I was able to change where Victory positions the tooltip:

<img width="528" alt="Screen Shot 2019-07-20 at 12 22 30 AM" src="https://user-images.githubusercontent.com/17481322/61573927-a4468200-aa84-11e9-8246-3143694a1b5c.png">

See: https://formidable.com/open-source/victory/docs/victory-tooltip

FYI, Victory is planning to include improvements for tooltips in their next major release.
`https://github.com/FormidableLabs/victory/issues/1336`

**Comment by dlabrecq** [comment]
Fixed via https://github.com/patternfly/patternfly-react/pull/2883

**Comment by chriszrc** [comment]
@dlabrecq given that most people assume this is how tooltips would work by default, why isn't this automatically the default option?
