### ISSUE TITLE
Modal PF4: cannot render on specified element

### ISSUE THREAD

**Issue by thaorell** [patternfly/patternfly-react#2551]
[Potential enhancements]

I'm trying to write a PF4 Modal, then run ReactDOM.render(modal, target), with target being the container that modal would be rendered in (similar to [link](https://github.com/oVirt/ovirt-engine-ui-extensions/blob/83e676c701ffc7696eae1a7d073facbbeec2a6ba/src/integrations/showClusterUpgrade.js#L95)). However, the modal is rendered in the iframe document body, but not in the specified container. 

In PF3, it was possible because Modal accepted a container props. [link](https://github.com/react-bootstrap/react-overlays/blob/7dc63e8e51b2ede669801ead8453645e9311394b/src/Modal.js#L464-L470)

Would it be possible to implement a new props like in PF3 instead of defaulting to `document.body` as [currently implemented](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Modal/Modal.tsx#L84)?
@sjd78 @mturley

**Comment by rachael-phillips** [comment]
Hi @thaorell thank you for filing this. Is this a blocker for you at this time?

**Comment by sjd78** [comment]
> Hi @thaorell thank you for filing this. Is this a blocker for you at this time?

@rachael-phillips - On ovirt/RHV Admin Portal the UI plugins are setup so they run within an iframe.  We cannot easily change the way the plugin API does things.  Without being able to open a Modal in the iframe parent window, we are blocked from adopting PF4 Modals.

I have a PR nearly ready that we'll test and post in the next day or so.
