### ISSUE TITLE
Select menu has incorrect closing behavior 

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#2561]
This is an extension to issue #2066 , and PR #2560 

See example below. Currently, the select menu is hidden when the input is initally focused, but backspacing to an empty input leaves the menu open.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32821331/61652347-b6dbd980-ac85-11e9-8b33-c28669f84755.gif)

**Comment by rachael-phillips** [comment]
Thanks for filing @jenny-s51 !

**Comment by rachael-phillips** [comment]
@mcarrano is this the expected behavior for Selects? Double checking here before we put up the PR.

**Comment by mcarrano** [comment]
My opinion is that it's fine the way it is. I wouldn't necessarily expect the menu to close as long as focus is still on the input field. It should only close if the user tabs away.

On a related note - when testing this on the website, I found that the type-ahead no longer works for me on Firefox. It used to. Can someone test this?

**Comment by jenny-s51** [comment]
Hi @mcarrano! Per @mcoker, the type-ahead problem should have been resolved in this core PR that was merged yesterday: https://github.com/patternfly/patternfly-next/pull/2075
