### ISSUE TITLE
fix(data-list): fix a11y

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2570]
Based on the audit from patternfly-org, there are several issues in the Data List component:
https://github.com/patternfly/patternfly-org/issues/1311

There are 4 places in the component that this issue is occurring: "ARIA attributes must conform to valid values"

To find these errors / test if your solution works:
1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by redallen** [comment]
The axe errors:
<img width="858" alt="Screen Shot 2019-08-19 at 15 14 28" src="https://user-images.githubusercontent.com/47335686/63292689-3ca67100-c294-11e9-970f-c336e7adc8ba.png">

**Comment by jessiehuff** [comment]
Seems to be resolved, likely closed by #3593
