### ISSUE TITLE
fix(a11y): React documentation tables

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2571]
Related to this issue from patternfly-org: https://github.com/patternfly/patternfly-org/issues/1304

This issue is happening from patternfly-react: "All th elements and elements with role=columnheader/rowheader must have data cells they describe"

If we can update these tables in React that would solve our a11y issues in org.

**Comment by jessiehuff** [comment]
This issue appears to be fixed by one of our updates.
