### ISSUE TITLE
Add wrap prop for <td> and <th> cells in a <thead>

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#2578]
I don't see support for the `.pf-m-wrap` class you can add to cells of the `<thead>` element to allow the content in the cells to wrap. If we don't support that, we should add it, and also add an example. We recently added an example to the core workspace here - https://github.com/patternfly/patternfly-next/pull/2065

**Comment by rachael-phillips** [comment]
Hi @mcoker is this a high priority issue?

**Comment by mcoker** [comment]
I know Patrick has used it on openshift, though I think he's adding the class manually versus using a react prop. So I think it's high enough that products would use it and we should support it since it's available in core, but there are workarounds since you can just add the class manually. FWIW, should be a pretty low level of effort, too.

**Comment by boaz0** [comment]
@tlabaj @rachael-phillips - do you mind if I work on it?

**Comment by rachael-phillips** [comment]
Yes! Thanks @boaz0!
