### ISSUE TITLE
a11y issue in documentation/react/dropdown

### ISSUE THREAD

**Issue by lareplog** [patternfly/patternfly-react#2581]
only need to fix the "buttons must have discernible text" issue. 

https://github.com/patternfly/patternfly-org/issues/1312

To find these errors / test if your solution works:

1. Right click on the page and choose inspect
2. In developer tools, choose "axe" from the top menu 
3. Run the test

**Comment by tlabaj** [comment]
This will be fixed by PR #2690

**Comment by rachael-phillips** [comment]
Closing this issue because it has been addressed
