### ISSUE TITLE
Modal: Cancel button should be a LinkButton

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#2585]

**Comment by boaz0** [comment]
Are you talking about the close button? The Modal doesn't have any cancel button.

**Comment by mcarrano** [comment]
This is still an issue that was noted to me yesterday by one of our designers. Examples in the Modal should be updated to look like this:

![Small](https://user-images.githubusercontent.com/6619860/65279004-3efe2400-dafb-11e9-92d9-1230b3973744.png)
