### ISSUE TITLE
[PF4] There isn't onRowClick  in VirtualTable

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#2594]
React-Virtualized PF4: https://patternfly-react.surge.sh/patternfly-4/virtual%20scroll/virtualized/

React-virtualized table => https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md#prop-types

React-virtualized table PF4 tbody props => https://patternfly-react.surge.sh/patternfly-4/components/table/

This impact to Kiali https://github.com/kiali/kiali-ui/pull/1319

cc @serenamarie125 @abonas

**Comment by abonas** [comment]
@aljesusg I see this is closed  - is this resolved?

**Comment by aljesusg** [comment]
not resolved @abonas but I check the openshift console and the "link" is in the name of the item no in the row so we don't need this.
