### ISSUE TITLE
[PF3] Pagination controls are not exported outside the context of a PaginationRow, so they can't be rendered at both the top and bottom of a list

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#2599]
In IMS, we have a few list views with pagination, and when we implemented them we just added a pagination row at the bottom, as provided by the PaginationRow component here: https://patternfly-react.surge.sh/patternfly-3/index.html?knob-Item%20Count%3A=75&knob-Items%20End=15&knob-Page=1&knob-Page%20Size%20Drop%20Up=true&knob-firstPage=First%20Page&knob-Total%20items=75&knob-of=of&knob-Items%20Start%3A=1&knob-currentPage=Current%20Page&knob-perPage=per%20page&knob-nextPage=Next%20Page&knob-Number%20of%20Pages=5&knob-View%20Type%3A=list&knob-lastPage=Last%20Page&knob-previousPage=Previous%20Page&selectedKind=patternfly-react%2FWidgets%2FPagination&selectedStory=Pagination%20row&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

We recently got a complaint from QE that when there are a lot of list items, the pagination controls can't be seen until the user scrolls down. I thought this was a non-issue but then I noticed that in the original design documentation for Pagination, it also appears as a control at the top-right of the list, aligned with any active filters: https://www.patternfly.org/v3/pattern-library/navigation/pagination/#overview

This is not compatible with how it was implemented in patternfly-react, since the exported PaginationRow is the whole bottom row including that "N per page" selection on the left. In order to match the original design I would need to modify patternfly-react to export a part of that component separately so I can render only the controls on the right side.

Is this something worth fixing at this point? We could take the relevant children from PaginationRow and factor them out into a separate component that is used inside PaginationRow and also exported on its own. Then it could be rendered at the top of the list view as well as the bottom, without also rendering the "N per page" selection.

**Comment by rachael-phillips** [comment]
@mcoker will this have any implication on the Core side?

**Comment by mcoker** [comment]
@mturley are you able to reorder the elements in the existing component as a new component in react without needing any styling updates, or will we need to style the new variation in core?

**Comment by mturley** [comment]
I think we can probably do that in react without any updates to core. I'll give it a try when I can and get back to you. The issue in my product was pushed to another release, so I might not get to it any time soon.

**Comment by mturley** [comment]
Activity!

(I'd still like to fix this when time allows)
