### ISSUE TITLE
PF4 Switch label props breaking change

### ISSUE THREAD

**Issue by boaz0** [patternfly/patternfly-react#2600]
A follow up to #2468 - to match the implementation to PF4 core the current API should be changed to include the label when the toggle is off and a different label when the toggle is on.

To solve this two ways come to mind:

* update the type of `label` from `string` to `string[2]` where the first item is the label on `on` and the second one is on `off`
* create two props `labelOn` and `labelOff` for the `on` and `off` states respectively.

This is going to be breaking change as it changes the API of the switch component.

//cc @jgiardino

**Comment by redallen** [comment]
This could not be a breaking change if we:
- Change the type to `string | string[2]` and check if they pass an array or a string to render the label.
- Add a `labelOff` prop and keep the `label` prop.

Renaming the `label` prop seems a little extreme to me.

**Comment by boaz0** [comment]
Both ideas sound good. Nevertheless, the latter seems easy to implement.

Thanks @jschuler I will be working on it
