### ISSUE TITLE
Pagination and empty state - error

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-react#2602]
On Firefox

A table has no results and is showing an empty state, and the pagination widget shows an error. There are zero results, so there are zero pages. 
The error shows up on page load, and seems to happen only in Firefox 68.0.1

![Xnip2019-07-29_10-18-54](https://user-images.githubusercontent.com/23172038/62056545-e2ae1080-b1eb-11e9-9f13-ee32deff8802.jpg)

cc @AllenBW

**Comment by AllenBW** [comment]
the react-pagination component doesn't appear to handle the edge case of 0 results well
<img width="589" alt="Screen Shot 2019-07-29 at 10 59 42 AM" src="https://user-images.githubusercontent.com/6640236/62058827-0ecb9080-b1f0-11e9-9965-7ee0a57142ca.png">

unsure what the right fix is here 🤔  a few options
* hide the component when there are no results 
* say there is one result (to avoid the red box of doom, but it would be a lie)
* other?

**Comment by rachael-phillips** [comment]
Hi @katierik and @AllenBW thank you for filing this. @tlabaj making you aware

**Comment by katerinapat** [comment]
There is already a bug report filed in our JIRA. Is there any action planned on this?

**Comment by rachael-phillips** [comment]
@katerinapat this issue has not been planned so far. What release version are you targeting for this fix?

**Comment by tlabaj** [comment]
@katierik is this still an issue.  I believe PR #2558 fixed this.

**Comment by tlabaj** [comment]
@katierik please reopen if this is still an issue.
