### ISSUE TITLE
Tabs as nav example doesn't match html equivalent

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#2607]
When I look at the HTML examples for Tabs, the [Tabs using the nav element](https://www.patternfly.org/v4/documentation/core/components/tabs#tabs-using-the-nav-element) shows the tabs as `<a>` instead of `<button>` elements. 

When I look at a similar [example for react](https://www.patternfly.org/v4/documentation/react/components/tabs/#tabs-using-the-nav-element), I don't see `<a>` elements being used for the tabs. And it isn't obvious to me from this example how to use `<a>` elements instead of `<button>` elements.

If I add `href="#someurl"` to a `<Tab>` and inspect the html, I do see that the tab converts to a `<a href="#someurl" ...>` instead of a `<button>`. But I don't see this prop/attribute noted in the props documentation. 

For this issue:
- Should an item be added for `href` in the `<Tab>` props documentation? 
  - actually, are there other props that should be included for `<Tab>`? I don't see a section listing any props for `<Tab>`
- Can we update the react example to have parity with the html example, and use `<a>` instead of `<button>` in the examples that use the `<nav>` element?

**Comment by cmwylie19** [comment]
Hi Guys, just submitted the fix for this. I made the react example identical to the html version.

**Comment by rachael-phillips** [comment]
Hi @cmwylie19 do you mind linking the issue here? @tlabaj I'm going to assign @cmwylie19

**Comment by cmwylie19** [comment]
sure https://github.com/patternfly/patternfly-react/issues/2607 @rachael-phillips thanks! Submitting a PR now

**Comment by tlabaj** [comment]
Closed by #3527
