### ISSUE TITLE
Feature: Tab component misses mountOnEnter, unmountOnExit properties

### ISSUE THREAD

**Issue by xeviknal** [patternfly/patternfly-react#2609]
In PF3 we had something like the following:

```
            <TabContent>
              <TabPane eventKey="info" mountOnEnter={true} unmountOnExit={true}>
                <AppInfo
                  app={this.state.app}
                  namespace={this.props.match.params.namespace}
                  onRefresh={this.doRefresh}
                  activeTab={this.activeTab}
                  onSelectTab={this.tabSelectHandler}
                  health={this.state.health}
                />
              </TabPane>
              <TabPane eventKey="traffic" mountOnEnter={true} unmountOnExit={true}>
              </TabPane>
            <TabContent>
```

In patternfly 4, we want to implement Tabs also using the `mountOnEnter` and `unmountOnExit`

```
      <Tab title="Inbound metrics" eventKey={2}>
        <IstioMetricsContainer
          namespace={this.props.match.params.namespace}
          object={this.props.match.params.app}
          objectType={MetricsObjectTypes.APP}
          direction={'inbound'}
        />
      </Tab>
```

Is there the possibility to implement those properties for PF4 for Tab component?

**Comment by abonas** [comment]
cc @serenamarie125 @aljesusg

**Comment by rachael-phillips** [comment]
@tlabaj making you aware of this one.

**Comment by rachael-phillips** [comment]
@xeviknal is this currently blocking you

**Comment by xeviknal** [comment]
@rachael-phillips I did a workaround that looks like is working, although is not that elegant. So, not blocking.

**Comment by rachael-phillips** [comment]
Thanks so much for letting us know @xeviknal !

**Comment by rachael-phillips** [comment]
@xeviknal what do you expect these properties to do? What functionality would you like to see here? Having a little more information will be helpful for addressing this. Thank you!

**Comment by redallen** [comment]
Docs for PF3 tabs: https://react-bootstrap.github.io/components/tabs/#tabs-props

**Comment by xeviknal** [comment]
I am expecting to have same behavior has in PF3. Mount the DOM when I click into the tab, unmount it when I am leaving the tab.
I guess it is close to what @redallen linked in the comment above :)
Thanks!

**Comment by rachael-phillips** [comment]
@redallen are we ready to close this issue?

**Comment by redallen** [comment]
@rachael-phillips I think we need to better evaluate the value of adding these two props.

What a consumer would have to do themselves as a workaround? What would we have to do as a library to add them? How much does it aid in PF3 -> PF4 conversion? I'm not sure the answers to these yet.
