### ISSUE TITLE
PF3 ExpandCollapse missing onToggle callback

### ISSUE THREAD

**Issue by shaded-enmity** [patternfly/patternfly-react#2610]
The `Expandable` component in PF4 provides `onToggle` callback, however the PF3 `ExpandCollapse` component has no such callback, which makes it impossible to use when the expanded part triggers a re-render of a parent component. 

I can submit a PR for this, let me know if such change is welcomed.

**Comment by rachael-phillips** [comment]
@shaded-enmity thanks for filing! Yes, it would be great if you could put up a PR for this one :)
