### ISSUE TITLE
Replace lodash-es with lodash

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2617]
We have no reason to depend twice on the same library. We should replace *`lodash-es` with `lodash`.

**Comment by dlabrecq** [comment]
"I used lodash-es instead of lodash because it is currently a dependency in OpenShift." -- @priley86 

Victory charts has lodash as a dependency; thus, react-charts inherits this dependency as well. It's not likely that we can change that to use lodash-es.

**Comment by redallen** [comment]
In that case, we should replace `lodash-es` with `lodash`.
