### ISSUE TITLE
PF4 Select checkbox variant cannot expand with empty children

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2618]
If you have no children with `SelectVariant.checkbox` and try to expand you will be met with a "You can't have a focus-trap without at least one focusable element" error

## Expended results
1. Click to expand Select
1. Met with empty window

## Actual results
1. Click to expand select
1. Error crashes the application

Reproducible sandbox:
https://codesandbox.io/s/amazing-dawn-ueed9?fontsize=14

**Comment by rachael-phillips** [comment]
@SpyTec is this currently blocking you?

**Comment by SpyTec** [comment]
Hi @rachael-phillips, I can get around it so it's not currently blocking me
