### ISSUE TITLE
Feature: Support JSX.Element on Tab title property

### ISSUE THREAD

**Issue by xeviknal** [patternfly/patternfly-react#2623]
Right now, Tab title component only supports string values. It would be great that it supported Elements.

Kiali wants to render as a tab title one string and one icon, like the following:
![Screenshot of Kiali Console (4)](https://user-images.githubusercontent.com/613814/62265153-525a1080-b423-11e9-82a4-2d63f41e9479.jpg)
![Screenshot of Kiali Console (5)](https://user-images.githubusercontent.com/613814/62268004-a1597300-b42e-11e9-9e68-5ae86a6f3b93.jpg)

This is blocking our progress into migration to PF4.

**Comment by xeviknal** [comment]
cc @serenamarie125 @aljesusg @pilhuhn @abonas

**Comment by xeviknal** [comment]
In the second example, we needed to have this last tab opening a new tab (other tabs should just run as usual). Is there a way to achieve it with actual implementation of tabs?

**Comment by rachael-phillips** [comment]
Hi @xeviknal what is your timeline like on this request, and what level of urgency would you say this is?

**Comment by xeviknal** [comment]
@rachael-phillips another workaround for both solutions: icons and links.
However, starting to have a lot of workarounds, hehe.

Example that works. Notice the trick of telling title is type any. Tab.title expects a string.
```typescript
const title: any = (
          <>
            Traces <Icon type={'fa'} name={'external-link'} />
          </>
        );
<Tab eventKey={3} title={title} />
```

Non working scenario:
```typescript
      <Tab eventKey={3}
            title={
              <>
              'Traces ' + <Icon type={'fa'} name={'external-link'} />
              </>
            }
          />
```

**Comment by rachael-phillips** [comment]
That's a great point, @xeviknal Thanks for posting the workaround!

**Comment by boaz0** [comment]
@rachael-phillips @tlabaj can you assign this to me?

**Comment by rachael-phillips** [comment]
Done! Thanks for your help @boaz0 !

**Comment by xeviknal** [comment]
I can confirm that this has been fixed and is not a blocked in Kiali's side. Thanks.
