### ISSUE TITLE
icon button size look out of place in topology

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#2627]
The icon buttons used in the topology look out of place as the height of the button is larger than the width:
![image](https://user-images.githubusercontent.com/14068621/62303359-f656b280-b449-11e9-9301-94c0aaa33831.png)

The designs show a wider button than taller button:
![image](https://user-images.githubusercontent.com/14068621/62303519-4897d380-b44a-11e9-975d-689f2c9082d8.png)
![image](https://user-images.githubusercontent.com/14068621/62303541-53526880-b44a-11e9-9ebd-927cb1e00b41.png)

**Comment by serenamarie125** [comment]
@mceledonia i see that the PF topology design shows the graph buttons wider than tall.  I think that having them more square as @jeff-phillips-18 implemented it looks better.  What do you think ?

**Comment by christianvogt** [comment]
@serenamarie125  The current implementation isn't more square. It's a taller rectangle...

**Comment by mceledonia** [comment]
@serenamarie125 @christianvogt I'm thinking either square or wider rectangle would be best. Since they are the same height either way, making them skinnier will make them a smaller click target which could potentially get dicey on mobile.

**Comment by jeff-phillips-18** [comment]
when developing the topology components, I specifically set the left/right margins to `-sm` (top). The PF4 default is `-md` (bottom):

![image](https://user-images.githubusercontent.com/11633780/62372778-59a61a80-b506-11e9-9718-1c11a3a976ca.png)

@mceledonia remove my setting of `-sm`?

**Comment by mceledonia** [comment]
Yeah, I feel like our Goldilocks is somewhere in the middle of those two, but since we're working with the variables I'd go with the wider versus the skinnier due to the reason I mentioned above.
