### ISSUE TITLE
PF3 jest failure due to PF4 settings

### ISSUE THREAD

**Issue by shaded-enmity** [patternfly/patternfly-react#2630]
`jest.config.js` contains `"<rootDir>/packages/patternfly-4/react-core/scripts/snapshot-serializer"` and when trying to run tests for PF3 via `yarn test:pf3` I'm getting:
```
 FAIL  packages/patternfly-3/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.test.js
  ● Test suite failed to run

    Cannot find module './dist/js/build/jest/snapshot-serializer' from 'snapshot-serializer.js'

    > 1 | const { default: serializer, createSerializer } = require('./dist/js/build/jest/snapshot-serializer');
        |                                                   ^
      2 | 
      3 | module.exports = serializer;
      4 | module.exports.createSerializer = createSerializer;

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.require (packages/patternfly-4/react-styles/snapshot-serializer.js:1:51)

```

For all of the PF3 test suites.

**Comment by rachael-phillips** [comment]
Thanks for filing @shaded-enmity . Is this a blocking issue for you at this time?

**Comment by shaded-enmity** [comment]
@rachael-phillips Nope, I removed the PF4 specific line from the config and was able to run the tests ok :)

**Comment by rachael-phillips** [comment]
ok great! Thanks @shaded-enmity !

**Comment by redallen** [comment]
@shaded-enmity Try running `yarn build:pf3` or `yarn build` first.

**Comment by shaded-enmity** [comment]
@redallen Thanks, so:

```
yarn build:pf3 && yarn test:pf3
```

fails with the barrage of errors, while

```
yarn build && yarn test:pf3
```

Works fine!

**Comment by redallen** [comment]
Ah, that makes sense. It's due to a PF4 package building the `snapshot-serializer` that Jest needs. Reopen if you have any other issues, thank for your interest in building PatternFly!
