### ISSUE TITLE
Turning switch on/off does not change anything in DOM

### ISSUE THREAD

**Issue by abalakh** [patternfly/patternfly-react#2669]
I'm looking at examples in docs (both patternfly-react.surge.sh and patternfly.org). Switch's input is loaded with or without "checked" attribute (`<input class="pf-c-switch__input" ... checked>`), but when changing switch state that attr is not added/removed. No classes or anything else are updated as well.
Moreover, both labels (for "on" and "off" states) are present in DOM at the same time, so from test automation perspective i have no idea what state switch is currently in and which label is actually shown.
Making "checked" attr reflect actual switch state (or intoducing some other attr/class/etc) would help a lot.

**Comment by abalakh** [comment]
Optionally, some attr in labels like "hidden=True" would make it easier to determine what label is shown, and i won't have to write some complex xpath like `/span[contains(@class, 'pf-m-on') and preceding-sibling::input[@checked] or contains(@class, 'pf-m-off') and preceding-sibling::input[not(@checked)]]` to figure that out. But even such weird xpath will only work if `checked` actually reflexts switch state.

**Comment by rachael-phillips** [comment]
Hi @abalakh is this bug for PF3 or PF4? Are you currently blocked at this time because of this bug?

**Comment by abalakh** [comment]
@rachael-phillips PF4 ([here](https://patternfly-react.surge.sh/patternfly-4/components/switch/?shadow=False) or [here](https://www.patternfly.org/v4/documentation/react/components/switch/?shadow=False)).
Not currently blocked as i'm just adding support for Switch in our automation, so far it's not yet used in our tests AFAIK, but soon will be for sure, we have switches present on webUI, so if you ask to determine hi/med/low priority, i'd say medium for now.

**Comment by rachael-phillips** [comment]
Thank you! That's super helpful.

**Comment by rachael-phillips** [comment]
@abalakh can I close this issue since #39 has merged?

**Comment by abalakh** [comment]
@rachael-phillips no, that's what i've mentioned in https://github.com/patternfly/patternfly-react/issues/2669#issuecomment-519542617, it works for initial switch state, but if user clicks the switch - framework won't be able to figure out the state has changed as nothing changes in DOM.
