### ISSUE TITLE
Select not taking click events

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#2671]
None of the Select component example exposed in the React documentation section of the website seem to be taking click events to select an item from the dropdown. Looking at this page: https://www.patternfly.org/v4/documentation/react/components/select/  I'm seeing this problem with either Firefox or Chrome.

**Comment by redallen** [comment]
This has since been fixed! https://patternfly-react.surge.sh/patternfly-4/components/select/ works and will show up when we next promote https://patternfly.org !
