### ISSUE TITLE
PF4 React-Table - TypeScript followup

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#2673]
In #2360, I noted a couple of additional nice-to-haves:

- [x] It would be better to expose all formatter/transformer props in `Table.tsx` with our explicitly defined types. Doing so would also require ensuring all formatters and transformers are tested via that interface (as explicit props to `Table`). https://github.com/patternfly/patternfly-react/pull/2360#issuecomment-517371474

- [ ] Ensure that Prettier formatter is applied to React-Table after it is applied in React-Core: #2362 

- [ ] Determine if we'd like to introduce breaking API changes for the `tslint` settings different from React-Core: https://github.com/patternfly/patternfly-react/pull/2360#issuecomment-513822602

- [x] Add Cypress/e2e tests

- [ ] Consider using an interface for static type analysis of aria props/captions/headers. See [comment here](https://github.com/patternfly/patternfly-react/pull/2360#discussion_r312525317).

- [ ] Consider rewriting this logic in `collapsible.tsx` for better type analysis: https://github.com/patternfly/patternfly-react/pull/2360#discussion_r312541336

- [ ] Update event types in `selectable.tsx`: see [comment](https://github.com/patternfly/patternfly-react/pull/2360#discussion_r312542774)

**Comment by mturley** [comment]
Just commenting here so this issue ends up in my "participating" filter. This all sounds like good stuff!

**Comment by mturley** [comment]
We haven't addressed all these things yet, so I'm bumping stalebot -- @seanforyou23 do you want to keep this issue open or track these kinds of things in individual issues?

**Comment by seanforyou23** [comment]
Thanks @mturley - I'm just now coming across this issue and find it very helpful! I'm working on fixing the `selectable` transform today - and I've had my eye on some of the other stuff mentioned in this issue so let's keep it open and I'll work on seeing through the remaining TODO's. Will tag you for review once I get a PR up.

**Comment by mturley** [comment]
Bumping stalebot because https://github.com/patternfly/patternfly-react/pull/3296 is still open
