### ISSUE TITLE
styles doesn't work with UMD

### ISSUE THREAD

**Issue by ssilvert** [patternfly/patternfly-react#2674]
It looks like this commit broke my app:

https://github.com/patternfly/patternfly-react/pull/2085

I'm not sure how this is supposed to be consumed now.  Now it looks like react-styles is looking for files like ...components/Alert/alert.js?

Those don't exist in the react-styles distribution.

**Comment by rachael-phillips** [comment]
@ssilvert this is the bug that's currently blocking you, correct?

**Comment by ssilvert** [comment]
@rachael-phillips Correct.  It's a blocker.

**Comment by rachael-phillips** [comment]
@dgutride I know you were looking at this with @ssilvert . What was the outcome of that and what should our next steps be?

**Comment by ssilvert** [comment]
@rachael-phillips Is anyone looking at this?

**Comment by redallen** [comment]
What do you need to `require()` CSS in the UMD world @ssilvert? Do you have something like [`css-loader`](https://github.com/webpack-contrib/css-loader)? How was importing components working before since they've always had `require('./about-modal-box.css')`?

**Comment by ssilvert** [comment]
@redallen @rachael-phillips  It doesn't look like anything was done about react-styles with UMD.  

I still get the same errors with the latest patternfly-react.

**Comment by dgutride** [comment]
Unfortunately, this is still broken and we need to help prioritize a fix for it.

**Comment by redallen** [comment]
Fixed in https://github.com/ssilvert/systemjs-react/pull/3
