### ISSUE TITLE
DropdownItem HTML elements

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#2675]
This is huge blocker because we want to add translations to our UI with [react-intl](https://github.com/formatjs/react-intl) and you do that by usig [`formattedmessage`](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#formattedmessage) that is regular component and once you add any component to dropdownItem it changes the styles and it's not showing properly in the menu.

Can we add option to null the component used to wrap component, if passed do not wrap children, and when component is passed wrap children with that component (current behavior).

Example:
```JSX
<DropdownItem
  key={'delete-selected'}
  onClick={() => {}}
  component='button'
>
  <FormattedMessage { ...defaultMessages.delete }/>
</DropdownItem>
```
Expected render:
```HTML
<li role="none">
  <button role="menuitem" tabindex="-1" type="button" class="pf-c-dropdown__menu-item"> 
   <span>Delete</span>
  </button>
</li>
```

To allow custom children in li elements we can pass null to component:
```JSX
<DropdownItem
  key="custom-dropdown-item"
  onClick={() => {}}
  component={null}
>
  <div>My custom dropdownItem</div>
</DropdownItem>
```

**Comment by rachael-phillips** [comment]
Hi @karelhala we'll be investigating this one. Thanks for filing!

**Comment by rachael-phillips** [comment]
Hi @karelhala we are investigating this issue this sprint and will report back with next steps on this issue.
