### ISSUE TITLE
PF4 - React Table - Inline Edit Feature

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#2679]
In this issue, I will try to capture additional needs for the upcoming Inline Edit feature 😸 . Please feel free to append...

This issue will include the following:

- Provide an implementation of the new Inline Editable table coming to PF Core. Link to [PF Core issue](https://github.com/patternfly/patternfly-next/issues/404).
- Refactor inline editable row and inline editable table to meet latest design spec and Core HTML/CSS (following). This will involve revisiting and refactoring the existing source in `@patternfly/react-inline-edit-extension`. Special consideration should be taken to ensure this is now consistent w/ our current React-Table implementation.
- Use TypeScript and available React-Table types/interfaces exposed in #2360 where possible. [Link to a relevant comment](https://github.com/patternfly/patternfly-react/pull/2360#discussion_r312588396) and [another comment](https://github.com/patternfly/patternfly-react/pull/2360#discussion_r312494646).
- Expose the new InlineEditable source from `@patternfly/react-table` instead of `@patternfly/react-inline-edit-extension`. We'd like to make this part of the Core distribution of React Table going forward.

This may also include additions to the Toolbar in React-Core for the new design as well as demos integrated w/ the Inline Edit Toolbar options in the Inline Edit examples.

**Comment by mturley** [comment]
Just commenting here so this issue ends up in my "participating" filter. I will definitely want to get involved in this, I wrestled with the PF3 inline edit feature quite a bit.

**Comment by johnsonm325** [comment]
Attaching new issue for future implementation on this issue:

https://github.com/patternfly/patternfly-react/issues/2808

**Comment by mturley** [comment]
Noticed that this issue was marked as stale but there is ongoing work for this in core (https://github.com/patternfly/patternfly-next/issues/2315, https://github.com/patternfly/patternfly-next/issues/2319). @mattnolting @tlabaj @rachael-phillips @LHinson should we keep this issue open or close it until the current core work is ready for a React implementation?

**Comment by rachael-phillips** [comment]
@mturley, yes we should leave it open.
