### ISSUE TITLE
PF4 Possible bug on empty state size class binding

### ISSUE THREAD

**Issue by carlosga** [patternfly/patternfly-react#2680]
Looking at the demo page of the Empty State component ( https://www.patternfly.org/v4/documentation/react/components/emptystate/  ) it looks like the css class for the component size is not being generated correctly, on the demo page, the small size one is being generated as **'styles.modifiers.sm'** and the large one as **'styles.modifiers.lg'**, if i'm not wrong they should be generated as **'pf-m-sm'** and **'pf-m-lg'** ( as in the HTML demo page ).

**Comment by boaz0** [comment]
@carlosga you're right it looks like a bug.

**Comment by rachael-phillips** [comment]
@carlosga is this currently blocking you or do you have a workaround?

**Comment by boaz0** [comment]
A possible workaround is to pass `pf-m-lg` or `pf-m-sm` to the `className` prop of `EmptyState`

//cc @carlosga @rachael-phillips

**Comment by carlosga** [comment]
> @carlosga is this currently blocking you or do you have a workaround?

No, 'it's not blocking.
