### ISSUE TITLE
PF4 Login Page background image doesn't show up in Firefox

### ISSUE THREAD

**Issue by akshygupt** [patternfly/patternfly-react#2693]
System Details:
Operating System: Fedora 29
Browser: Firefox Quantum 68
@patternfly/react-core:

If you visit the login page [example](https://www.patternfly.org/v4/documentation/react/components/loginpage/) provide in the documentation, the background image doesn't show up. 

This seems to be an issue with the filter property, if i were to remove this, the image starts to show up

.pf-c-background-image{
...
~~--pf-c-background-image--Filter: url(#image_overlay);~~
}

Could someone please take a look into this?

**Comment by jschuler** [comment]
@mcoker can you see from the DOM why the filter is not working? (I am not sure how the filter works :) )

**Comment by mcoker** [comment]
@jschuler in https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/BackgroundImage/BackgroundImage.tsx#L82 we should remove the `0` from `width` so that it is just an empty value (`width=""`)
