### ISSUE TITLE
Issues with Accordion styling

### ISSUE THREAD

**Issue by rawagner** [patternfly/patternfly-react#2694]
Im trying to use PF4's Accordion but Im facing a few issues

- every AccordionToggle is wrapped in heading (h1-h6, which can be configured) - I dont want that, I cannot even pass a custom className to the heading. It seems to me that this wrapping inside heading tag is unnecessary. If i'd like to use heading tag I can specify it as

```
<AccordionToggle ... >
  <h3>...</h3>
</AccordionToggle>
```

- adding custom classes to AccordionToggle's button element via passing className such as
```
<AccordionToggle className="my-custom-classname" >
```
 to change the default padding/border but Im not able to do so as applied class `.pf-c-accordion .pf-c-accordion__toggle`  has precedence.

**Comment by rachael-phillips** [comment]
Hi @rawagner is this currently blocking you or do you have a work around?

**Comment by rawagner** [comment]
not blocking, I can style with some ugly css rules for now :)

**Comment by rachael-phillips** [comment]
Thanks for the info!

**Comment by rachael-phillips** [comment]
@mcoker I placed a P2 on this issue because it is not blocking. Feel free to review and correct if needed.

**Comment by mcoker** [comment]
Thanks @rachael-phillips. Related - https://github.com/patternfly/patternfly-next/issues/2116

**Comment by redallen** [comment]
Opened a PR for this.

**Comment by rachael-phillips** [comment]
@rawagner did you see Zack's PR open for this?

**Comment by rawagner** [comment]
@rachael-phillips sorry, I missed that. 

And yes, ability to specify my own container via props will be very nice! It will solve my first issue but the second issue still remains.

Im not able to style `AccordionToggle`'s button element because `.pf-c-accordion .pf-c-accordion__toggle` has precedence over my style which Im passing via `className `prop.  The `.pf-c-accordion .pf-c-accordion__toggle` is coming from `@patternfly/react-styles/css/components/Accordion` - this import https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Accordion/AccordionToggle.tsx#L3

I noticed similar thing for the `Card` component where Im not able to override default padding of `CardBody` because again there is a style imported in a similar fashion.

**Comment by redallen** [comment]
@rawagner It's a total hack, but you can pass `class="abc123"` to set your own class since we add it at the end via `{...props}`:

```jsx
<AccordionToggle class="abc123">
```

**Comment by rawagner** [comment]
that works, but Im not blocked on this so I wont use it for now as it is really ugly :)

**Comment by redallen** [comment]
It's ugly, but without adding an extra prop to our entire library (that effectively does the same thing), it's difficult to provide you a way to not add the default classes. This is outside the scope of this issue.

This isn't just an Accordion issue. For all of our components, we simply append the `className` our consumers pass to the end of the element we add to the DOM, like `<div className={css('pf-c-component', className)}>{children}</div>`. We could provide an extra `noStyle` prop to every component to not add our default classes, but this defeats the purpose of a styled component library.

There are two methods to workaround the default classes we add:
1. Fix the CSS classes to work as they are
- Add your own class that overrides the CSS. If your class is further down in the .css file you ship, it will take precedence.
- Have your class use `!important`
- Ignore imports from `@patternfly/react-styles/css/**/*.css` to not import component styles using [Webpack's null-loader](https://github.com/webpack-contrib/null-loader) or something similar
- [Open an issue in patternfly-next](https://github.com/patternfly/patternfly-next/issues/new) to change the CSS you don't like, or don't believe adheres to PatternFly standards

2. Use the `class` property
- Pass `class="myClass"` and rely on React letting `class=` take precedent over `className=` and the fact for most components PatternFly passes your props through to the styled `<div>`, `<button>`, or other HTMLElement

**Comment by rachael-phillips** [comment]
@rawagner do you have any follow up questions here or did @redallen 's answers help you out?
