### ISSUE TITLE
Problem with @spice-project/spice-html5 in SpiceConsole

### ISSUE THREAD

**Issue by bond95** [patternfly/patternfly-react#2709]
`SpiceConsole` importing `@spice-project/spice-html5` which cause error, because Chrome is not supported `import * as` construction.

**Comment by redallen** [comment]
Can you give steps to reproduce or link a repo/branch?

**Comment by bond95** [comment]
@redallen in this PR https://github.com/oVirt/ovirt-web-ui/pull/1091 we use only `VncConsole`, to make it work I did mock file and set it as alias with name `@spice-project/spice-html5`.

**Comment by redallen** [comment]
That's interesting, [`@spice-project/spice-html5` claims to be Chrome and Firefox compatible](https://www.npmjs.com/package/@spice-project/spice-html5). If you're using tree-shaken ESM modules, it should only be a problem if you `import { SpiceConsole } from '@patternfly/react-console';`, which I don't see in your project. What's the exact error you're seeing?

**Comment by rachael-phillips** [comment]
@bond95 did you see @redallen's comment above? :)

**Comment by rachael-phillips** [comment]
@bond95 did you see @redallen's comment above?

**Comment by bond95** [comment]
> That's interesting, [`@spice-project/spice-html5` claims to be Chrome and Firefox compatible](https://www.npmjs.com/package/@spice-project/spice-html5). If you're using tree-shaken ESM modules, it should only be a problem if you `import { SpiceConsole } from '@patternfly/react-console';`, which I don't see in your project. What's the exact error you're seeing?

I got this error `Uncaught SyntaxError: Unexpected token *`

**Comment by bond95** [comment]
Fixed, thank you.
