### ISSUE TITLE
Pagination number field doesn't trigger on change

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2716]
Clicking the buttons and navigating pagination works, but changing the number field directly does not trigger any changes.

See: https://patternfly-react.surge.sh/patternfly-4/components/pagination/

## Repro steps

1. Navigate up one pagination by clicking next
2. Click on input field
3. Change back to page 1

## Expected behaviour
Page is changed back to 1

## Actual behaviour
Page does not change

**Comment by rachael-phillips** [comment]
@SpyTec thanks for filing! Is this currently blocking you or do you have a work around?

**Comment by SpyTec** [comment]
Currently not blocking me; Found no workaround for the input field

**Comment by jschuler** [comment]
Hi @SpyTec , i tested this on https://patternfly-react.surge.sh/patternfly-4/demos/paginationtable/ and after I change the number I hit the Return key and it changes the page for me. Are you pressing the Return key after changing the number?

**Comment by SpyTec** [comment]
I did not press the return key, but now that I try it does indeed change the page.

**Comment by tlabaj** [comment]
I am closing this issue based on the comments.  Please reopen if you are still having an issue with this.
