### ISSUE TITLE
Update formatting for pf-org

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#2720]
So that we can have consistent font styles in the patternfly-org website, can we update the Table component page: https://patternfly-react.surge.sh/patternfly-4/components/table/ so that the link at the top: "Note: Table lives in its own package at @patternfly/react-table!" doesn't use a `<code>` block anymore? (It should just use an `<a>` tag)

Related to #1237

**Comment by evwilkin** [comment]
Fixed in #2832
