### ISSUE TITLE
Area Chart color themes sometimes cause contrast issues

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#2722]
When using the monochromatic color themes on area charts, it's possible that two overlapping lighter colors will be indistinguishable. As seen here in the examples, the data for Cats and Birds overlap, but you can't distinguish the "Birds" data because it does not contrast against the overlapping "Cats" data.

![image](https://user-images.githubusercontent.com/22625502/63195675-44baa280-c041-11e9-8772-ae1c358bf773.png)

**Comment by mceledonia** [comment]
I'd suggest starting with setting a top border for each area value which is the same color but 100% opacity, 1px border.

If we can, it would be very helpful to set each values blending mode to "multiply." This makes the colors darken as they overlap, I mocked up a super quick example below.

![image](https://user-images.githubusercontent.com/30935938/63375153-375f2a00-c359-11e9-98d7-ecbe938f8e5c.png)

**Comment by dlabrecq** [comment]
The problem with `mix-blend-mode` is that it applies to all children of the svg. There's no way to apply the CSS rule to just the `g` and `path` elements representing each area.

As a test, applying `.VictoryContainer svg * { mix-blend-mode: multiply }` demonstrates that areas are more visible, but it also breaks tooltips.

<img width="719" alt="Screen Shot 2019-09-08 at 7 39 11 PM" src="https://user-images.githubusercontent.com/17481322/64496236-bc5ea480-d270-11e9-8360-f8d0b5e814f8.png">

**Comment by dlabrecq** [comment]
Wanted to note that the design on https://www.patternfly.org/v3/pattern-library/data-visualization/area-chart/#design does not include multiple area charts. Perhaps this type of data is best represented as a line chart? And our chart examples should mimic the "Single Area Chart" as shown on patternfly.org?

**Comment by dlabrecq** [comment]
Experimented a bit and got a little further. I was able to apply CSS to target just the `clip-path` attributes. The grid lines are also slightly more visible, IMO.

`.VictoryContainer svg g[clip-path] { mix-blend-mode: multiply }`

Before:
<img width="697" alt="Screen Shot 2019-09-08 at 8 20 05 PM" src="https://user-images.githubusercontent.com/17481322/64496711-2299f600-d276-11e9-9ac5-9b1f8bf1d4e4.png">

After:
<img width="702" alt="Screen Shot 2019-09-08 at 8 16 21 PM" src="https://user-images.githubusercontent.com/17481322/64496685-c931c700-d275-11e9-95a4-885e4b499bd3.png">

**Comment by dlabrecq** [comment]
Experimented a bit and got a little further. I was able to apply CSS to target just the `g` elements with `clip-path` attributes used for each area. The grid lines are also slightly more visible, IMO.

`.VictoryContainer svg g[clip-path] { mix-blend-mode: multiply }`

Before:
<img width="697" alt="Screen Shot 2019-09-08 at 8 20 05 PM" src="https://user-images.githubusercontent.com/17481322/64496711-2299f600-d276-11e9-9ac5-9b1f8bf1d4e4.png">

After:
<img width="702" alt="Screen Shot 2019-09-08 at 8 16 21 PM" src="https://user-images.githubusercontent.com/17481322/64496685-c931c700-d275-11e9-95a4-885e4b499bd3.png">

After with stroke color:
<img width="710" alt="Screen Shot 2019-09-08 at 9 03 46 PM" src="https://user-images.githubusercontent.com/17481322/64497446-2c265c80-d27c-11e9-8df2-3e7f95616eef.png">

**Comment by dlabrecq** [comment]
The mix-blend-mode will be set via https://github.com/patternfly/patternfly-next/pull/2239

**Comment by dlabrecq** [comment]
Fixed by:

https://github.com/patternfly/patternfly-next/pull/2239
https://github.com/patternfly/patternfly-react/pull/2883
