### ISSUE TITLE
Form - modal not dismissible - makes documentation kinda uselessssssss 😭

### ISSUE THREAD

**Issue by AllenBW** [patternfly/patternfly-react#273]
Maybe instead of launching by default we have it on a button... present state, modal can't be dismissed, makes all the description test and the with info documentation useless

### [its this thing](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Show%20Help=true&knob-Disabled=false&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Modal=true&knob-Show%20Loading=false&selectedKind=Forms&selectedStory=Modal%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
<img width="1089" alt="screen shot 2018-03-16 at 12 08 52 pm" src="https://user-images.githubusercontent.com/6640236/37531529-d804ec70-2912-11e8-8680-d547c06ec2dd.png">

**Comment by priley86** [comment]
+1 from me on this..

**Comment by AllenBW** [comment]
yep, another of my oversights, show modal knob is already present, achieves the goal of this bug 🤦‍♂️ 👍

**Comment by priley86** [comment]
@AllenBW originally it was requested that buttons open modals (that was a design consistency thing with other PF documentation). I'm honestly not hugely worried whether it is driven via Knob or Button, as long as test coverage for these patterns is good. 😸 Maybe it is worth asking for design preference on each pattern (in how you are presenting the stories). I can see the case for presenting the prop as well as a button though...

**Comment by AllenBW** [comment]
@maryclarke !!! ok checking out the modal form... then checking out the modal overlay... which do you prefer ?

**Comment by jgiardino** [comment]
If the question is this: Do we show a modal from clicking a button or by selecting a knob?
I'm inclined to use a button. I do think they should be the same for both examples. And it would be nice to be consistent with test pages in other repos, so if most of those cases are using a button, then that's what I'd suggest doing here.

**Comment by AllenBW** [comment]
Unsure of what other repos, but I'll morph it however desired. 🌮 🎉
