### ISSUE TITLE
withOuia should not be listed with the other components

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#2738]
The withOuia helper component should be moved to a helper section and hidden from the documentation that lists all components.  Let's discuss how to best include the documentation for this instead of listing it as a usable PatternFly component for consumers.

**Comment by redallen** [comment]
Relevant link: https://patternfly-react.surge.sh/patternfly-4/components/withouia/

**Comment by rachael-phillips** [comment]
Hi @redallen what is the urgency of this issue?
