### ISSUE TITLE
Wizard: Required fields don't show required asterisk correctly

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2746]
In Cost Management, we defined a required field within a wizard step. The asterisk is shown, but the color and spacing is off.

![Screen Shot 2019-08-21 at 11 22 08 AM](https://user-images.githubusercontent.com/17481322/63445210-fa04a600-c405-11e9-9c76-06dc07f74434.png)

This is the code for the text input:
<img width="546" alt="Screen Shot 2019-08-20 at 4 51 56 PM" src="https://user-images.githubusercontent.com/17481322/63384022-00deda80-c36c-11e9-9ece-5a259387daea.png">

//cc @boaz0

**Comment by dlabrecq** [comment]
Clearing my local storage helped. I can now see the red asterisk, but the spacing is still off. 

![Screen Shot 2019-08-21 at 9 26 28 AM](https://user-images.githubusercontent.com/17481322/63435998-e94c3400-c3f5-11e9-9539-63095f50c642.png)

Looks like the computed value for `--pf-c-form__label-required--MarginLeft` is zero. 

![Screen Shot 2019-08-21 at 10 10 13 AM](https://user-images.githubusercontent.com/17481322/63439374-e48a7e80-c3fb-11e9-9fc7-1ae3d0f1587c.png)

Although, I see `--pf-global--spacer--sm` is set in the page.

![Screen Shot 2019-08-21 at 10 09 20 AM](https://user-images.githubusercontent.com/17481322/63439302-c3299280-c3fb-11e9-9e38-dcea0e89bcb4.png)


Could we be missing a utility? Note that the Insights platform includes the base css.

![Screen Shot 2019-08-21 at 10 06 00 AM](https://user-images.githubusercontent.com/17481322/63439051-5e6e3800-c3fb-11e9-96e3-c68c1cb9bf0a.png)

**Comment by rachael-phillips** [comment]
Hi @dlabrecq is there a workaround for this or is this blocking? Thanks for filing!

**Comment by dlabrecq** [comment]
We do not have a work around. In addition to the asterisk spacing, it is now being displayed as black VS red.

@mcoker suggested, "I’ve seen that pop up a number of times. The global reset CSS is being loaded after the component CSS, causing margins, paddings, etc to be overwritten."

Unfortunately, i don't believe we can control the order in which component CSS is loaded.

**Comment by rachael-phillips** [comment]
@mcoker is this an issue we would resolve in Core?

**Comment by mcoker** [comment]
@rachael-phillips no, this has to do with the order the CSS is being loaded in react or cost management

**Comment by dlabrecq** [comment]
This is no longer an issue for Cost Management. The latest milestone looks good.
