### ISSUE TITLE
Visual Regression testing

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#275]
I'd like to open this issue for conversation (since I've heard a few folks start to mention it). Visual Regression tests give us more detailed information (pixel-to-pixel) and granular level details about specific browsers. They also keep us aware of CSS changes happening upstream in PF Core (and let us know when something changes here in PF React that is expected/unexpected). 

There are many tools available, but one I've heard mentioned a few times and would really like to explore further w/ Storybook is [percy.io](https://percy.io/). There is already a storybook [guide](https://percy.io/docs/clients/javascript/react-storybook) so setup would be extremely easy.

I view these tests more as **informational** in PatternFly React (and less critical than they are in PF Core where the design application is happening). From the Percy [documentation notes](https://percy.io/docs/integrations/github):

> Percy provides a workflow for visual review alongside code review. If a build has visual diffs, it will be marked as a failure in the Pull Request. You can review and approve visual diffs in one click as part of your code review process.

> Approving a build is not required, you can still merge the Pull Request in GitHub. Approving a build in Percy simply sets the GitHub commit status to green/successful, so that your team can see that any visual changes were reviewed and approved.

So essentially, we would be notified and could approve or bypass (thus not blocking our dev build/release builds at any point).

@jeff-phillips-18 @Rohoover @jgiardino @LHinson @maryclarke 

I'm curious to hear your thoughts on this...

Also - if the community has any other tools along these lines they'd like to suggest, it would be great to know about them.

**Comment by jeff-phillips-18** [comment]
Sounds great @priley86   Definitely nice to know when things change and if there is little overhead, 👍 👍 👍

**Comment by Rohoover** [comment]
Agreed. I think this information could be valuable and interesting. 1-Click review/approval sound nice.

**Comment by maryclarke** [comment]
Agree, without understanding all the technical implications, this sounds like a good addition

**Comment by LHinson** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7e6af720-36b5-4740-bd15-f8a9e26af9a2-15206079-98a4-479e-bb46-baa63bbd1a81-v1.png?transparent=1&palette=1&width=246)

@priley86 this would be nice to review at the repo leads meeting
