### ISSUE TITLE
[PF4] ChipGroup withToolbar no apply styles

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#2756]
Hi, when you use chipGroup with toolbar styles  not applied

https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroup.tsx#L52

**Comment by aljesusg** [comment]
cc @serenamarie125 @abonas

**Comment by tlabaj** [comment]
@aljesusg  is this still an issue?  I believe it was resolved by #2881

**Comment by LHinson** [comment]
@aljesusg bumping this back into view.... see Titani's question above

**Comment by aljesusg** [comment]
I need to check it @LHinson , I'll update this asap

**Comment by aljesusg** [comment]
confirmed sorry delay
