### ISSUE TITLE
Add template to our issues

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2788]
This request is to add a template to our GitHub issues, so that we can glean more information about each issue that is filed.

https://docs.google.com/document/d/1wl1jROxHBhfGTIc4_YhW4g4VPsP6gIPTI3ctW_lLOLM/edit?usp=sharing

**Comment by rachael-phillips** [comment]
PR: https://github.com/patternfly/patternfly-react/pull/2804

**Comment by tlabaj** [comment]
closed by #2840
