### ISSUE TITLE
Cannot pass custom className to Accordion Content Body

### ISSUE THREAD

**Issue by rawagner** [patternfly/patternfly-react#2789]
I'd like to customize styling of this div https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Accordion/AccordionContent.tsx#L46 but I'm not able to pass custom className there.

I wonder if that div is even necessary ? Could we just do something like

```javascript
return (
  <AccordionContentContainer
    id={id}
    className={css(
      styles.accordionExpandedContent,
      styles.accordionExpandedContentBody
      isFixed && styles.modifiers.fixed,
      !isHidden && styles.modifiers.expanded,
      className
    )}
    hidden={isHidden}
    aria-label={ariaLabel}
    {...props}
  >
    {children}
  </AccordionContentContainer>
);
```

**Comment by rachael-phillips** [comment]
Hi @rawagner thanks for filing! A couple quick questions for you:

1. Is this bug currently blocking you or is there a workaround?
2. What is your product and what release version are you targeting?

**Comment by rawagner** [comment]
Hi @rachael-phillips 

1. not blocking, the workaround I currently use is to target `.pf-c-accordion__expanded-content-body` class which is used by the mentioned div.

2. product is openshift/console. Im using the Accordion in this PR https://github.com/openshift/console/pull/2543
