### ISSUE TITLE
Provider icons needed

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-react#2795]
In Cloud Services, we are using provider icons both in Sources and Topological Inventory. 

Can we add these to the pf4 icon set?
We need them both in color and black and white. 
I think it is a good idea to add them in pf as these can be reused in the future for other apps. 

Here is the list. 
{
  "data": {
    "source_types": [
      {
        "name": "openshift"
      },
      {
        "name": "amazon"
      },
      {
        "name": "ansible-tower"
      },
      {
        "name": "vsphere"
      },
      {
        "name": "ovirt"
      },
      {
        "name": "openstack"
      },
      {
        "name": "cloudforms"
      },
      {
        "name": "azure"
      }
    ]
  }
}

**Comment by rachael-phillips** [comment]
Hi @terezanovotna thanks for filing!

**Comment by karelhala** [comment]
openshift, amazon and ansible should be part of react icons. I tried to look for other and I couldn't find vsphere, ovirt and cloudforms. However azure and openstack were easy to find and create - https://github.com/patternfly/patternfly-react/pull/2827

**Comment by rachael-phillips** [comment]
Hi @terezanovotna what release are you targeting for these icons?

**Comment by terezanovotna** [comment]
@rachael-phillips summit release.
