### ISSUE TITLE
Npm install fails on prepublish 

### ISSUE THREAD

**Issue by matanwerbner** [patternfly/patternfly-react#28]
prepublish script runs **babel** command, however if babel is not installed globally it fails, since devDependencies have not yet been installed.

a quick solution may be:
https://github.com/npm/npm/issues/10366
`"prepublish": "npm install --ignore-scripts && npm run build",`
or to have travis run the build task on merge, which seems more natural to me.

**Comment by priley86** [comment]
Reference #29 

Closing this for now.
