### ISSUE TITLE
Modal Footer Overflows Out of the Modal

### ISSUE THREAD

**Issue by andrewballantyne** [patternfly/patternfly-react#2800]
When using the Modal examples over on https://patternfly-react.surge.sh/patternfly-4/components/modal/ try to view them in an emulated mobile mode in Chrome I found one of your examples has an overflow issue with the footer buttons:

<img width="376" alt="Screen Shot 2019-08-29 at 11 37 59 AM" src="https://user-images.githubusercontent.com/8126518/63963858-e4295d80-ca63-11e9-89d4-6a7db908854f.png">

**Comment by tlabaj** [comment]
@mcoker thoughts?

**Comment by mcoker** [comment]
@andrewballantyne thanks for reporting this. @tlabaj I opened an issue in core https://github.com/patternfly/patternfly-next/issues/2207

**Comment by LHinson** [comment]
see core issue https://github.com/patternfly/patternfly-next/issues/2021
