### ISSUE TITLE
[extension] Floating action box on inline edit table

### ISSUE THREAD

**Issue by johnsonm325** [patternfly/patternfly-react#2803]
When I click to edit a row in the inline edit table, everything looks good:
![image](https://user-images.githubusercontent.com/15373136/63976514-80149280-ca7f-11e9-8902-37e55850ea4b.png)

until I scroll:
![image](https://user-images.githubusercontent.com/15373136/63976558-94f12600-ca7f-11e9-8143-96dc4541cada.png)

**Comment by rachael-phillips** [comment]
HI @johnsonm325 I have the same set of questions here :) 

1. Please provide the steps to reproduce so we can better understand and address the issue. Feel free to link CodePen or another tool:

2. Is this bug currently blocking you or is there a workaround?

3. What is your product and what release version are you targeting?

**Comment by johnsonm325** [comment]
- Go here: https://patternfly-react.surge.sh/patternfly-4/inline%20table/inlineedit/
- Go to the 3rd table down and click one of the kebabs like I've shown in the above photos. Then click edit.
- Scroll up and down on the page and you'll see the box floating.

**Comment by LHinson** [comment]
on hold while we investigate effort in #2907
