### ISSUE TITLE
[extension] Inline Edit Table re-renders page on action resolver kebab click

### ISSUE THREAD

**Issue by johnsonm325** [patternfly/patternfly-react#2808]
If I have a table with many rows, and I click the action resolver kebab and then click edit, if I am editing a row that is further down the page (i.e. I have to scroll down to get to it) I get a re-render and it jumps to the top of the page. Then I have to scroll back down to find it.

![image](https://user-images.githubusercontent.com/15373136/64046918-38ebd780-cb3b-11e9-80ca-829236eab602.png)

**Comment by rachael-phillips** [comment]
Hi @johnsonm325 thanks for filing! A few quick questions:

1. Please provide the steps to reproduce so we can better understand and address the issue. Feel free to link CodePen or another tool: 

2. Is this bug currently blocking you or is there a workaround?

3. What is your product and what release version are you targeting?

**Comment by johnsonm325** [comment]
1.
- Go here: https://patternfly-react.surge.sh/patternfly-4/inline%20table/inlineedit/
- Go to the 3rd table and expand to edit code.
- Replace the `rows:` value in `this.state` to look like this: https://paste.fedoraproject.org/paste/1UcMdsqG0ORG0xPTr-n3~Q
- Scroll down to one of the values in the middle or towards the bottom and click the kebab and then click edit (You can also click to collapse one of the rows).
- You will see the page re render and send you all the way back to the top of the chart. You will also see that your check and 'X' mark are gone as a result of the floating box bug #2803 

2. It doesn't necessarily block, but it's just very frustrating to use. I'm not sure we'd release it as-is because of how users would have a hard time using the table.

3. Product is System Comparison for Cloud Services for RHEL.

**Comment by LHinson** [comment]
on hold while we investigate effort in #2907
