### ISSUE TITLE
[PF4] Switch label prop does not show when Switch is off

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#2814]
In https://github.com/patternfly/patternfly-react/pull/2468 the `label` prop was changed to only show when the Switch is on. Prior to this it was always showing `label` prop with no regard for if it was on or off.

`label` prop should always show unless `labelOff` is provided, otherwise this is a breaking change and should be rolled back and published in a major version

**Comment by rachael-phillips** [comment]
Hi @SpyTec it looks like @boaz0 's PR #2816  will resolve this. Any other concerns?

**Comment by SpyTec** [comment]
None from my side, awaiting for it to be released :)
