### ISSUE TITLE
PF4 - Attempted import error: 'chart_bullet_axis_tick_count' is not exported from '@patternfly/react-tokens'.

### ISSUE THREAD

**Issue by xeviknal** [patternfly/patternfly-react#2815]
Hi there,

I am trying to update patternfly charts to get the CharBullets component available in Kiali project.
After updating to 4.9.2, I get the following error:

```
./node_modules/@patternfly/react-charts/dist/esm/components/ChartTheme/styles/bullet-styles.js
Attempted import error: 'chart_bullet_axis_tick_count' is not exported from '@patternfly/react-tokens'.
```

I am using the following PF4 packages:

```
    "@patternfly/patternfly": "2.4.1",
    "@patternfly/react-charts": "4.9.2",
    "@patternfly/react-core": "3.89.2",
    "@patternfly/react-table": "2.16.4",
    "@patternfly/react-virtualized-extension": "1.1.97",
```

Should I update other patternfly components?
it might be trivial, first time I am facing this.

Thanks for you help.

**Comment by aljesusg** [comment]
We need @patternfly/react-tokens to 2.6.21 here, the version installed by react-charts is a old release that not include **chart_bullet_axis_tick_count**

**Comment by rachael-phillips** [comment]
@xeviknal is this currently blocking you? @dlabrecq do you have any insight here?

**Comment by dlabrecq** [comment]
You also need to update react-tokens. The latest package.json shows react-tokens@^2.6.21 as a dependency of react-charts.

**Comment by xeviknal** [comment]
Thank you team for being so effective. Closing bc it is fixed with both suggestions.

Since it is a dev dependency, we didn't get the package so it needs to be added manually.
