### ISSUE TITLE
[PF4] cellWidth in table is not working

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#2818]
Hi

In code the method assign width- to the cell.
```js
className: css(getModifier(styles, `width-${width}`))
```
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-table/src/components/Table/utils/decorators/cellWidth.ts#L4-L6

but in the styles modifiers are like width_

so we need change width- to width_ 

This block us in the migration of tables in WorkloadPage Kiali
Thanks 

cc @abonas @serenamarie125

**Comment by rachael-phillips** [comment]
HI @aljesusg we've seen this and are looking into it. Thanks for filing!
