### ISSUE TITLE
[PF4] Button with Loading Prop

### ISSUE THREAD

**Issue by glekner** [patternfly/patternfly-react#2824]
We could really use a button that greys out and shows a spinner after clicked by turning to a loading state. Something like this :

![ezgif-4-1d907f381c42](https://user-images.githubusercontent.com/24938324/64244228-56d98380-cf11-11e9-81c0-b74a9e34a4c2.png)

Could be a great issue for newcomers aswell as this one seems easy. Thoughts?

**Comment by rachael-phillips** [comment]
HI @glekner thanks for filing! What product are you currently working on and what release version are you targeting?

**Comment by glekner** [comment]
@rachael-phillips OpenShift 4.3 (CNV)
