### ISSUE TITLE
[PF4] Expanded icon in Table reverse turn onclick

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#2826]
I don't know how to explain this ^^

![Peek 2019-09-04 14-01](https://user-images.githubusercontent.com/3019213/64253069-c012c400-cf1c-11e9-9173-faf54ad736f9.gif)

PF4 storybook: https://patternfly-react.surge.sh/patternfly-4/components/table/

**Comment by rachael-phillips** [comment]
Hi @aljesusg is the bug you are seeing the way the caret is rotating? I want to make sure I understand your bug, and is this blocking you at this time or do you have a work around?

**Comment by aljesusg** [comment]
Yes @rachael-phillips , the carpet should rotate in the other way ^^. We want to use it....can we use any workaround with some css?

**Comment by rachael-phillips** [comment]
@mcoker @tlabaj any work around here that you can think of?

**Comment by mcoker** [comment]
Hi @aljesusg! We did make some changes to the rotation on 6/27 in this PR - https://github.com/patternfly/patternfly-next/pull/1932/files (look for "table.scss"). We added a transition and changed the rotation. Before this PR, the icon rotation matched what is in your screenshot (it rotated in the wrong direction), however it wasn't visible and didn't animate that way, since there was no `transition` applied to the rotation. What looks like is happening in your screenshot is you're using the older rotation from before  https://github.com/patternfly/patternfly-next/pull/1932/files combined with a transition for the rotation.

I've verified that the rotation and transition are OK in both PF core and react. Let me know if the information above helps. I'm happy to help troubleshoot further if you're still having issues!

**Comment by aljesusg** [comment]
Ok let me check it because I was working with: 

"@patternfly/react-core": "3.89.2",
"@patternfly/react-table": "2.17.5",

**Comment by aljesusg** [comment]
After upgrade to 2.19.14 I have the same result @mcoker . Do I have to update any dependencies?

**Comment by mcoker** [comment]
@tlabaj do you know if @aljesusg needs to update dependencies?

**Comment by aljesusg** [comment]
Hi @tlabaj @mcoker the css code applied is but in my case -webkit-transform is strikethrough
```css
.pf-c-table__toggle .pf-c-button > * {
    -webkit-transform: rotate(270deg);
    transform: rotate(270deg);
}
```

to 0 onlick, should it be negative to make the rotation to the other way?

**Comment by tlabaj** [comment]
@aljesusg how are you doing your imports?  We do not see this issue in our workspace with the latest core.

**Comment by aljesusg** [comment]
This is my code @tlabaj we have not problems with another components so my concern is if PF3 style could be giving problems here with PF4

```javascript
import * as React from 'react';
import { ObjectValidation, Pod } from '../../../types/IstioObjects';
import { Card, CardBody, Grid, GridItem, Tooltip } from '@patternfly/react-core';
import { ICell, IRow, Table, TableHeader, TableBody, TableVariant } from '@patternfly/react-table';
import { css } from '@patternfly/react-styles';
import { ConfigIndicator } from '../../../components/ConfigValidation/ConfigIndicator';
import Labels from '../../../components/Label/Labels';
import { icons } from '../../../config';

const textCenter = () => ({ textCenter: true });
const classNames = (...classNames: string[]) => () => ({
  className: css(...classNames)
});

type WorkloadPodsProps = {
  namespace: string;
  pods: Pod[];
  validations: { [key: string]: ObjectValidation };
};

type WorkloadPodsState = {
  columns: ICell[];
  rows: IRow[];
};

class WorkloadPods extends React.Component<WorkloadPodsProps, WorkloadPodsState> {
  constructor(props: WorkloadPodsProps) {
    super(props);

    this.state = {
      columns: this.columns(),
      rows: this.rows()
    }
  }
  columns() {
    return [
      {title: 'Status', transforms: [textCenter],
        cellTransforms: [textCenter]},
      {title: 'Name', transforms: [textCenter], columnTransforms: [classNames('pf-m-width-20')], cellTransforms: [textCenter]},
      {title: 'Created at', transforms: [textCenter], columnTransforms: [classNames('pf-m-width-20')], cellTransforms: [textCenter]},
      {title: 'Labels', transforms: [textCenter],
        columnTransforms: [classNames('pf-m-width-50')],
        cellTransforms: [textCenter]},
      {title: 'Phase', transforms: [textCenter], cellTransforms: [textCenter]}
    ];
  }

  renderStatus(status: string) {
    const state = icons.phase[status];
    return (
      <Tooltip content={<>{status}</>}>
        {React.createElement(state.icon, {style: {color:state.color}})}
      </Tooltip>
    )
  };

  renderInformation (pod: Pod) {
    const columns: string[] = [
      'Created by',
      'Istio Init Containers',
      'Istio Containers'
    ];
    const rows = [{
      cells: [
        pod.createdBy && pod.createdBy.length > 0 ? pod.createdBy.map(ref => ref.name + ' (' + ref.kind + ')').join(', ') : '',
        pod.istioInitContainers ? pod.istioInitContainers.map(c => `${c.image}`).join(', ') : '',
        pod.istioContainers ? pod.istioContainers.map(c => `${c.image}`).join(', ') : ''
      ]
    }];
    return (
      <Table variant={TableVariant.compact} aria-label={"list_pods"} onCollapse={this.onCollapse}  cells={columns} rows={rows}>
        <TableHeader/>
        <TableBody />
      </Table>
    );
  };

  rows() {
    let rows: IRow[] = [];
    (this.props.pods || []).map((pod, podIdx) => {
      const validations: ObjectValidation[] = [];
      if (this.props.validations[pod.name]) {
        validations.push(this.props.validations[pod.name]);
      }
      rows.push({
        isOpen: false,
        cells :[
          { title : <ConfigIndicator id={podIdx + '-config-validation'} validations={validations} definition={true} />},
          { title : pod.name},
          { title : new Date(pod.createdAt).toLocaleString()},
          { title : <Labels key={'labels' + podIdx} labels={pod.labels} />},
          { title : this.renderStatus(pod.status)}
        ]});
      rows.push({
        parent: rows.length - 1,
        cells: [
          { title : this.renderInformation(pod)},
        ]
      });
      return rows;
    });
    return rows;
  }

  onCollapse = (_, rowKey, isOpen) => {
    const { rows } = this.state;
    rows[rowKey].isOpen = isOpen;
    this.setState({
      rows
    });
  }

  render() {

    const { columns, rows } = this.state;
    return (
      <Grid>
        <GridItem span={12}>
          <Card>
            <CardBody>
            <Table variant={TableVariant.compact} aria-label={"list_pods"} onCollapse={this.onCollapse}  cells={columns} rows={rows}>
              <TableHeader/>
              <TableBody />
            </Table>
            </CardBody>
          </Card>
        </GridItem>
      </Grid>
    );
  }
}
export default WorkloadPods;
```

**Comment by aljesusg** [comment]
Update !
In styles .pf-c-table__toggle .pf-c-button.pf-m-expanded > * when user click the arrow,
We have the transform: rotate(0deg) when in demo there is a rotate(--pf-c-table__toggle--c-button--m-expanded__toggle-icon--Transform) => this value is 360 in patternfly

So it seems that this is not in last version @mcoker @tlabaj .

**Comment by aljesusg** [comment]
So I fixed this overriding styles with

```css
/* Override arrow expand in tables */
.pf-c-table__toggle .pf-c-button.pf-m-expanded > * {
  -webkit-transform: rotate(270deg);
  transform: rotate(270deg)
}
.pf-c-table__toggle .pf-c-button.pf-m-expanded > * {
  -webkit-transform: rotate(360deg);
  transform: rotate(360deg)
}
```

**Comment by mcoker** [comment]
@aljesusg if you remove all of the transforms in the dev tools that rotate the icon, is its default state a down arrow icon?

**Comment by aljesusg** [comment]
The default state is right arrow icon like the demo.

**Comment by mcoker** [comment]
@aljesusg the icon in the demo is actually a down arrow with a css `transform` applied that rotates it 270 degrees to make it appear as a right arrow. If you undo the `transform`, the icon points downward. Just wanted to make sure you have the same icon.
