### ISSUE TITLE
PF4: Wizard - missing onClose crashes the wizard

### ISSUE THREAD

**Issue by suomiy** [patternfly/patternfly-react#2831]
The `onClose` prop is optional but the wizard crashes when it is missing.

We can either:

- keep it optional. In that case multiple null checks have to be added to the wizard.
- change it to required which would be a breaking change

**Comment by SpyTec** [comment]
Is the error related to focusTrap? We've added another prop in Modal to disable it so no errors occur if it is true. The same can be added to Wizard
