### ISSUE TITLE
Sparkline location and design changes requested

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-react#2843]
After speaking with @mcarrano and @mceledonia, we'd like to move Sparkline to it's own page under Charts (remove from area chart examples). We also saw that the implementation did not match the design - there should be a 1 px line marking the data points (as we do with line chart) and the opaque area fill should be 10% opacity of that same line color (i.e. line is #0066cc and area fill is #0066cc at 10% opacity).

Assuming you'd be the best person to point this to! @dlabrecq

**Comment by dlabrecq** [comment]
Moving the example is not an issue. However, while implementing the initial charts, @mceledonia asked us to remove the line color from area charts. I assume that would also apply to sparkline since it's also an area chart?

**Comment by mceledonia** [comment]
@dlabrecq  I think as a general styling thing we can make them both have them. They are both the same color, but the line should be 100% opacity, and the fill be 10%.

**Comment by dlabrecq** [comment]
Per my discussion with @mceledonia, the opacity will be updated to 30%. We currently use an opacity of 40% and 10% is too light.

30% opacity
![Screen Shot 2019-09-09 at 11 18 13 AM](https://user-images.githubusercontent.com/17481322/64544441-05f0d300-d2f5-11e9-9da6-e2bba3c46766.png)

10% opacity
![Screen Shot 2019-09-09 at 11 14 27 AM](https://user-images.githubusercontent.com/17481322/64544484-1903a300-d2f5-11e9-969a-15ebe448e12e.png)

Note: The opacity will be updated via https://github.com/patternfly/patternfly-next/issues/2232
