### ISSUE TITLE
Request for documentation around writing code examples

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#2844]
There's this unwritten rule about how code examples for components need to be written. All imports need to be registered outside of the code examples, and the imports within the code examples do not actually import the modules as one might think.

I've noticed more than one contributor getting tripped up over this simply because it is not written down anywhere. Can we document how it works somewhere?

This is just one manifestation of problems that arise when the demo code is not actually being parsed as JS/TS code. The code examples are disconnected from reality and we don't benefit from all the type checking and other tools we have available to us. At the very least I think it would be good to spend some time documenting how what we have works, and at best we might consider re-evaluating the use of mdx altogether for our examples/demos.

**Comment by riccardo-forina** [comment]
+1, I just stumbled upon it. Also being forced to write examples in JS and not in TS feels bad.
