### ISSUE TITLE
ClipboardCopy adds commas to rendered text

### ISSUE THREAD

**Issue by newswangerd** [patternfly/patternfly-react#2845]
```
<ClipboardCopy>
    ansible-galaxy install {namespace.name}.
    {name}
</ClipboardCopy>
```

Adds a bunch of extra commas to the output
<img width="940" alt="Screen Shot 2019-09-05 at 8 59 04 AM" src="https://user-images.githubusercontent.com/6063371/64343966-7d53f900-cfbb-11e9-8a8e-64b0eb6e8495.png">

It looks like this might be happening because `children` is an array instead of a string and the component is adding in commas between the items in the array.

<img width="221" alt="Screen Shot 2019-09-05 at 9 00 10 AM" src="https://user-images.githubusercontent.com/6063371/64344076-b724ff80-cfbb-11e9-989b-454277ea20d8.png">

**Comment by rachael-phillips** [comment]
Hi @newswangerd is this currently blocking you?

**Comment by newswangerd** [comment]
@rachael-phillips no. I have a workaround for it. If you put everything in one variable it doesn't add commas.

**Comment by boaz0** [comment]
@newswangerd I can't reproduce it on my environment can you give me a link to your code so I can debug it?
