### ISSUE TITLE
ClipboardCopy doesn't update when children are updated

### ISSUE THREAD

**Issue by newswangerd** [patternfly/patternfly-react#2846]
![Screen Recording 2019-09-05 at 9 18 04 AM mov](https://user-images.githubusercontent.com/6063371/64345424-577c2380-cfbe-11e9-84c4-498a9eb360af.gif)

The `ClipboardCopy` component should be updating along with the counter in that video, but it doesn't.

Here's the code to generate that example:

```
class Test extends React.Component<{}, { counter: number }> {
    constructor(props) {
        super(props);
        this.state = { counter: 0 };
    }

    componentDidMount() {
        setInterval(
            () => this.setState({ counter: this.state.counter + 1 }),
            1000,
        );
    }

    render() {
        return (
            <React.Fragment>
                {this.state.counter.toString()}
                <ClipboardCopy>{this.state.counter.toString()}</ClipboardCopy>
            </React.Fragment>
        );
    }
}
```

**Comment by rachael-phillips** [comment]
Thanks for filing! A couple of quick questions. Is this currently blocking you at this time? Also, what product are you working on and what release version are you targeting?

**Comment by rachael-phillips** [comment]
@newswangerd ignore my question about product! I know you work on Ansible :D

**Comment by newswangerd** [comment]
@rachael-phillips this is a blocker. I'm using this component to copy an install command and I need to be able to update the command with additional parameters when the user makes selects the package version. I haven't found a workaround for this.

**Comment by SpyTec** [comment]
@newswangerd submitted a PR for it in #2849, luckily it's an easy fix :)

**Comment by rachael-phillips** [comment]
@newswangerd and @SpyTec thanks so much for the update!

**Comment by newswangerd** [comment]
I just updated our app to use the latest version of @patternfly/react-core (`v3.112.3`) and this is still broken, even though it looks like the patch to fix this was added in `v3.99.4`

**Comment by redallen** [comment]
Can you paste some example code or create a [CodeSandbox?](https://codesandbox.io/)

**Comment by newswangerd** [comment]
@redallen I tested it on code sandbox, and it worked. I did some digging and it turns out this was breaking on my app because the dependencies didn't get reloaded correctly after I updated them. Sorry to bother you with this!
