### ISSUE TITLE
FormGroup not passing `className` through to child

### ISSUE THREAD

**Issue by keithjgrant** [patternfly/patternfly-react#2855]
Expected behavior:
`<FormGroup className="some-class">` should render to `<div class="pf-c-form__group some-class">`

Actual behavior:
The className is ignored, so only `<div class="pf-c-form__group">` is rendered.

This seems to be a regression, as it worked before we recently upgraded to react-core ^3.87.3

**Comment by rachael-phillips** [comment]
Hi @keithjgrant is this currently blocking you and is this issue a PF3 or PF4 issue?

**Comment by keithjgrant** [comment]
This is PF4. Not really blocked as we can work around for the time being by wrapping things in an extra div.
