### ISSUE TITLE
ChipGroupToolbarItem is not propagating className

### ISSUE THREAD

**Issue by tumido** [patternfly/patternfly-react#2865]
`ChipGroupToolbarItem` component is not propagating `className` despite advertising this prop in documentation and TS.

jsx:
```jsx
<ChipGroup withToolbar>
  <ChipGroupToolbarItem categoryName='Category' className='some_cool_class'>
    <Chip>Chip</Chip>
  </ChipGroupToolbarItem>
</ChipGroup>
```

renders:
```html
<ul class="pf-c-chip-group pf-m-toolbar">
  <li>
    <h4 class="pf-c-chip-group__label">Category</h4>
    <ul class="pf-c-chip-group">
      <li class="pf-c-chip">
        <span class="pf-c-chip__text" id="pf-random-id-0">Chip</span>
      </li>
    </ul>
  </li>
</ul>
```

`className` prop is advertised in [docs](https://www.patternfly.org/v4/documentation/react/components/chipgroup/#chipgrouptoolbaritem-props) and present in the [consumed props](https://github.com/patternfly/patternfly-react/blob/ae5a74a9a8584ed4c4275247731d7b5ed24591f8/packages/patternfly-4/react-core/src/components/ChipGroup/ChipGroupToolbarItem.tsx#L18) as well.

**Comment by karelhala** [comment]
This is rather crucial issue, because we want to use chips in data toolbar component.
