### ISSUE TITLE
ChipGroupToolbarItem is missing remove button

### ISSUE THREAD

**Issue by tumido** [patternfly/patternfly-react#2867]
`ChipGroupToolbarItem` [is expected to contain a delete action button](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#filter-chips)

![attribute-value-multi-chips](https://user-images.githubusercontent.com/7453394/64417555-9a5ef980-d099-11e9-9aeb-0d93ba7e08ca.png)
 
The button [is missing](https://www.patternfly.org/v4/documentation/react/components/chipgroup/#chip-group-toolbar).

**Comment by karelhala** [comment]
This is rather crucial issue, because we want to use chips in data toolbar component.

**Comment by LHinson** [comment]
Added an issue for design to look at this so we can address this issue

**Comment by mcoker** [comment]
This work is completed in core - https://github.com/patternfly/patternfly-next/pull/2334
