### ISSUE TITLE
Enzyme testing approach / shallow rendering / component instance

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#287]
As further analysis is being done on the testing approaches of our React component's done to date here, I would like to revisit cases in the repository where we can begin to use [shallow](http://airbnb.io/enzyme/docs/api/shallow.html) rendering for constructing minimal snapshots that are easier to visualize and maintain. This would ensure snapshots are more targeted to each component and do not assert behavior on child components. 

* ensure tests maintain Coveralls coverage / proper code coverage and that snapshots target the component's being tested
* ensure snapshot names reflect this and are easy to follow
* ensure lifecycle methods are correctly targeted 
* avoid `wrapper.setState` and `wrapper.setProps` methods

More details were discussed [here](https://github.com/patternfly/patternfly-react/pull/268#issuecomment-375723540) and [here](https://github.com/patternfly/patternfly-react/pull/268#issuecomment-375753381)

cc: @jeff-phillips-18  @dmiller9911 @mturley @AllenBW @vojtechszocs @sharvit @cdcabrera

**Comment by jeff-phillips-18** [comment]
Agreed, I like this approach much better.

**Comment by priley86** [comment]
Closing this issue - it seems like we have settled on a testing approach w/ Enzyme now.
