### ISSUE TITLE
Charting documentation spike

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#2873]
How do we improve our Charting documentation? Design and dev should think through how this can be addressed on the site. Do we surface the Katkoda tutorials? What issues are required to complete the work? 

related to: https://github.com/patternfly/patternfly-react/issues/2730

**Comment by dlabrecq** [comment]
1. I've already created a Katacoda tutorial for bar chart. This shows how to create a chart with a given height and width, then adds padding for a legend, labels, tooltips, etc. 

My plan is to create a Katacoda tutorial for each type of chart and link to each from the API docs, perhaps as the first example.

2. I would also like to see the react-docs issue #2139 addressed. That would go a long way in helping us clarify the API documentation.

3. Until #2139 can be addressed, we may consider adding API types manually to the property description as Victory does. Less than ideal, but devs could at least view the API types.

**Comment by dlabrecq** [comment]
Update: #2 above has been completed. We now have a tutorial available for each chart type. See https://github.com/patternfly/patternfly-react/issues/2920

Unfortunately, #3 didn't work out very well. We don't have the ability to format the react-docgen documentation, so adding property types in the description isn't readable -- everything ends up on the same, unbroken line.

IMO, we really need to work on #1. The generated docs are not very useful as is.

**Comment by LHinson** [comment]
This is not a relevant issue anymore.
