### ISSUE TITLE
Column re-ordering on table 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#2875]
Introduce column re-ordering to table 
Assuming this is a feature of reactabular that we can surface, ensure that @mcarrano is able to review and does not have any concern from a design perspective.

**Comment by LHinson** [comment]
on hold while we investigate #2908

**Comment by maryshak1996** [comment]
Some very minor updates around how to access the column management have been posted to the working doc: https://docs.google.com/document/d/1QRCmAHcSrJ4uPlQsUiRLcezz9wo2zdIdAML1wBLTXYI/edit?usp=sharing
