### ISSUE TITLE
Dropdown and dropdown-like components should have the same interaction

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#2898]
Following up on https://github.com/patternfly/patternfly-react/pull/2890, I noticed that not all dropdown and dropdown-like components have the same interaction pattern. The components in question are:
- Application launcher
- Context selector
- Dropdown
- FormSelect
- Options menu
- Pagination
- Select

Here are some interactions i would generally expect to happen across these using the keyboard:
1. Tab to focus on a toggle
2. Enter key opens the menu
3. The focus is placed on the first menu item
4. I can use keyboard up/down to navigate between the items
5. One of:
     a) Enter key on an item closes the menu (if applicable and not multi-select)
     b) Escape key is pressed to close the menu
6. Focus is returned to the toggle
7. Hitting the enter key again should reopen the menu since focus is back on the toggle

I think the key to have the same behavior across all of these components is to fix this behavior first in DropdownToggle / DropdownMenu components and then reuse these components in the other mentioned components. We have started to reuse some Dropdown components in other components, but there is still a lot of redundant code, especially surrounding the Toggle/Menu part of it.

**Comment by tlabaj** [comment]
cc @jessiehuff @jgiardino 
Jenn isn't there a related accessibility issue open?

**Comment by jgiardino** [comment]
@jschuler Thanks for capturing your observations! I would love to see the keyboard interaction made consistent across all of the components. 

There is another issue that I had created related to this: https://github.com/patternfly/patternfly-react/issues/1615. Should we keep that one and copy your comments to that issue? (and maybe also identify that issue as a bug as you did here? 😉)

@jessiehuff and I have been chatting about next steps for this effort. I think these would be the next steps, but am curious what everyone's thoughts are.

1. For all the components we have (see list above), define an interaction pattern that can be applied consistently across all the components. 
    - There is a link in https://github.com/patternfly/patternfly-react/issues/1615 to a document I started a while ago
    - Ideally that interaction pattern would be captured in some documentation that's made available to all PF contributors
    - I would size this work as pretty large, so we should review the proposed solution together and make sure we all agree on the approach
    - Since this is about user interaction, we should also either include someone from the interaction design team, or review with the team to make sure everyone agrees with the proposed design (and review with 
2. Once the design is finalized, then all components should be reviewed and issues opened as needed to get them updated according to the proposed interaction design.
