### ISSUE TITLE
Styling of Pagination component is incorrect

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#2903]
The styling of the "items per page" select menu is not correct. This should not use standard Select list styling as shown below.

![Screen Shot 2019-09-10 at 4.33.20 PM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/febd2fcc-441b-42ae-aec1-7788ca14133b)

Core implementation is correct. See

![Screen Shot 2019-09-10 at 4.35.33 PM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/9bc82e6c-d8da-4fef-8cf7-2dce9a58f713)

**Comment by SpyTec** [comment]
I've fixed this up somewhat locally, though I'm having some difficulty understanding how fix the isPlain option for the dropdown.

At the moment if you apply isPlain to the component you will get the behaviour that exists for OptionsMenu, i.e. isPlain is slightly lighter and gets darker on hover as seen in the example here

![image](https://user-images.githubusercontent.com/6598829/64698490-4beb9980-d4a3-11e9-97a0-58ae3f22cd7f.png)


Any ideas what would be the best approach to fix this? I'll create a PR once this is done as it's the last item
