### ISSUE TITLE
Changing text input of type date manually does not transfer automatically from year to month, leading to a bug

### ISSUE THREAD

**Issue by davebertz** [patternfly/patternfly-react#2905]
Steps to reproduce:

1. Have a `<TextInput type="date"/>`

2. Enter any numeric value to replace yyyy.

3. Notice that after you enter your year of birth, the field does not switch over to mm.

*Note that if you enter any numeric values to replace mm, it automatically switched over to dd
**You can enter 5 digits in the yyyy section because of that bug

**Comment by boaz0** [comment]
@davebertz what browser are you using?
I was using Firefox and couldn't reproduce it.

**Comment by davebertz** [comment]
I was using chrome, also the text input was inside a form group component.

**Comment by rachael-phillips** [comment]
@davebertz is this a PF4 component? Is this currently blocking you?

**Comment by davebertz** [comment]
It's functionnal, so it's not a blocker, just an issue that should be fixed ! :)

**Comment by rachael-phillips** [comment]
@davebertz we've seen this issue and we're investigating it.

**Comment by dgutride** [comment]
@davebertz  - can you provide some more details?  This is using the html <input type = date when you do this and the behavior we've provided just utilizes the html component functionality.

When I change to a type date, I see mm/dd/yyyy and if I enter any date, it will move through the portions the normal way.  If I skip to yyyy, it doesn't bring the user back to the beginning as that is what the browser normally does.  If you can provide a quick video possibly if you are seeing some behavior that we've broken in the normal html input, that would also be helpful.

You can see how the html input behaves by using this link:  https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date
