### ISSUE TITLE
Security alerts showing up in product repos

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#2906]
These security alerts are showing up in Cost Management, partly due to PatternFly dependencies.

![Screen Shot 2019-09-11 at 1 40 51 PM](https://user-images.githubusercontent.com/17481322/64721301-29a14e00-d49a-11e9-8e5a-ae25a42607ef.png)

See https://github.com/project-koku/koku-ui/issues/976

**Comment by rachael-phillips** [comment]
@redallen will your PR solve the issue here?

**Comment by redallen** [comment]
Partially. All the important alerts that aren't a part of our `devDependencies` and build processes will be resolved.
