### ISSUE TITLE
Table spike: Column reordering

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#2908]
Can we make [Column re-ordering on table](https://github.com/patternfly/patternfly-react/issues/2875) available? We need to ensure design understand the default behavior to make sure they approve 

Clarifications: 
- This is only for PatternFly table (not extensions)
- This is an investigation 
- Follow up with Dana, Jan, Leslie, Titani to clarify effort and agree upon next steps

**Comment by seanforyou23** [comment]
@LHinson here's the takeaways from the investigation

Column reordering is totally possible, we'll be looking at rolling our own implementation of the drag and drop functionality as well as the column reordering, as [the one from reactabular](https://reactabular.js.org/#/drag-and-drop) currently has issues and is a bit overengineered it seems.

Design states needed

- Styling for the source column when a user has dragged it (in the middle of a drag operation - "item marked for drag")
- Styling for target insertion point (when a user has grabbed a column and is hovering over a potential drop point)
- Styling for a grab handle (consider how this works when a column is both sortable and reorderable)
- Styling for target insertion point in disallowed drag state (when a user has grabbed a column and is hovering over a drop point that is not allowed)
- Styling for the source node in disallowed drag state (when a user has grabbed a column and is hovering over a drop point that is not allowed)

Open design questions

- If using this feature from a touch device or driving from a keyboard, are the visual indicators the same?

Open accessibility questions

- If design calls for dedicated "grabbable" elements, how should these be labelled?
- Aria attributes for drag and drop are deprecated in 1.1 ([aria-dropeffect](https://www.w3.org/TR/wai-aria-1.1/#aria-dropeffect) and [aria-grabbed](https://www.w3.org/TR/wai-aria-1.1/#aria-grabbed)), is there anything special we need to do in this area to ensure the functions are made accessible to SRU?
- How to determine keyboard support? We could strive to match the keypress combinations that facilitate drag and drop in a native screen reader (for example `ctrl+opt+<` to mark item as drag and `ctrl+opt+>` to drop item). Is there another strategy to consider?
