### ISSUE TITLE
Spike: Identify the work involved for inline edit 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#2909]
What issues are required to address inline edit for tables #2679 ?

- What questions are there for design? 
- What required from core? 
- How does the markup provided by reactabular compare to the design established by PF?

**Comment by seanforyou23** [comment]
@LHinson here are the takeaways from this investigation:

From a design standpoint, we want to better understand any restrictions around entering edit mode for multiple rows at a time, and what validation errors should look like when the edit operation fails for some reason. If there are any particular keyboard interactions we want to behave a certain way, that would be good to know also.

From the core side, the main thing that would help move this along is to have examples of what the markup/css should be when in edit mode, and also for those same validation states I mentioned from the design side.

The current implementation around react-table package doesn't come with any pre-existing markup/styling as I initially thought it might, so the answer to the question of "How does the markup provided by reactabular compare to the design established by PF?" is that there is no out of box code we need to worry about extending or overriding, we should be able to specify only exactly what we need on the patternfly side and that's what we'll be using.

I'll close this issue now, feel free to reopen if there's anything further we'd like to capture as part of this effort.
