### ISSUE TITLE
Use TextInput with React Hook Form (using ref)

### ISSUE THREAD

**Issue by ia3andy** [patternfly/patternfly-react#2913]
I am trying to use this library with Patternfly-react 4: https://react-hook-form.com/

They say: 
> Most UI libraries do expose innerRef or ref to register. For components that are more complicated like react-select or react-datepicker, you can manually update the value via setValue or trigger an error with setError.

But I don't see such `ref` exposed. Any idea on how to solve that?

**Comment by rachael-phillips** [comment]
@tlabaj making you aware of this issue

**Comment by rachael-phillips** [comment]
Hi @ia3andy , we will make this a spike and let you know what the results are.

**Comment by boaz0** [comment]
@kmcfaul I started playing with this few weeks ago.
If you want an inspiration look at these:
- https://github.com/patternfly/patternfly-react/compare/master...boaz0:closes_2978#diff-f38b62f842ac8072cabe98f378404c07
- https://github.com/patternfly/patternfly-react/compare/master...boaz0:closes_2978#diff-f98c6bfa71a1898d10cd743b0957f404
- https://github.com/patternfly/patternfly-react/compare/master...boaz0:closes_2978#diff-45680876a17f41bcd3a736ce718e1b5e

Feel free to write your own solution. :smile:

**Comment by kmcfaul** [comment]
Currently, setting a `ref` prop on TextInput sets the ref on the component itself, and not the contained input element, which the library requires. A fix for this would be to either add an `innerRef` property, or forward the `ref` property down to the input element instead of setting it on TextInput. 

@rachael-phillips We can probably move forward with a bug fix for this after deciding to which method to use.

**Comment by boaz0** [comment]
@kmcfaul - you can find it [here](https://github.com/boaz0/patternfly-react/commit/669bb0cf63b9c5b4f176cc9ca66e77f3b281ec51). The main changes:
 - https://github.com/boaz0/patternfly-react/blob/669bb0cf63b9c5b4f176cc9ca66e77f3b281ec51/packages/patternfly-4/react-core/src/components/TextInput/TextInput.tsx#L88
- https://github.com/boaz0/patternfly-react/blob/669bb0cf63b9c5b4f176cc9ca66e77f3b281ec51/packages/patternfly-4/react-core/src/components/withInnerRef/withInnerRef.tsx
