### ISSUE TITLE
add support for expanded vs collapsed text in Expandable uncontrolled variant

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#2914]
Support for the expanded vs collapsed text for Expandable uncontrolled variant.

This issue, https://github.com/patternfly/patternfly-react/issues/2350, requested an uncontrolled variant for the Expandable component. Which was implemented. However it also requested support to supply two pieces of text. One for expanded, and another for collapsed. Without this feature, we're left with having to add an `onToggle` listener and track the expanded state still which defeats the purpose of using the uncontrolled variant.

Even the demos exhibit this missing feature:
![expand-collapse](https://user-images.githubusercontent.com/14068621/64799234-60d33600-d552-11e9-8b6f-9ab8a494c9a4.gif)

Ideally the Expandable component could be used as follows:
```
  <Expandable
    textExpanded="Show Less"
    textCollapsed="Show More"
  >...</Expandable>
```

**Comment by rachael-phillips** [comment]
@christianvogt we've seen this and will be taking a look. Is this feature blocking you at this time?

**Comment by christianvogt** [comment]
@rachael-phillips it's not blocking us because we worked around the issue by using the controlled variant.
