### ISSUE TITLE
cannot render Wizard and AboutModal to specified element 

### ISSUE THREAD

**Issue by thaorell** [patternfly/patternfly-react#2917]
Similar to #2551, an appendTo() props could be added to Wizard and AboutModal like what @jschuler did in #2802 so that these components could be rendered in specified element on the DOM tree.

**Comment by rachael-phillips** [comment]
Hi @thaorell we've seen this, and I've added the enhancement label for us to take a look at. Thanks for filing!

**Comment by thaorell** [comment]
Hi @rachael-phillips, has there been any update on this issue?

**Comment by boaz0** [comment]
@rachael-phillips can you assign this to me?
