### ISSUE TITLE
Incorrect color for link button in toolbar demo

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-react#2934]
The link button in this toolbar demo is supposed to be #0066cc I believe https://www.patternfly.org/v4/documentation/react/demos/toolbardemo/. This is appearing on the site (I assume the workspace as well but I can't access it right now).

@jschuler @rachael-phillips

**Comment by rachael-phillips** [comment]
HI @gdoyle1 can you include a screen shot of what you are seeing that is incorrect?

**Comment by gdoyle1** [comment]
@rachael-phillips 
<img width="985" alt="Screen Shot 2019-09-16 at 12 16 57 PM" src="https://user-images.githubusercontent.com/30870144/64974967-f1c04f00-d87b-11e9-8118-17f10abe0b18.png">

**Comment by jessiehuff** [comment]
It looks like this has since been fixed. 

![Image 9-27-19 at 9 49 AM](https://user-images.githubusercontent.com/28281340/65774431-39f93000-e10c-11e9-9a0d-d3843025ebb0.jpg)
