### ISSUE TITLE
Missing key prop console warning for ChartPie and related components

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#2938]
The same warning is thrown on ChartPie, ChartDonut, and ChartDonutUtilization pages.

<img width="1108" alt="Screen Shot 2019-09-16 at 4 18 01 PM" src="https://user-images.githubusercontent.com/22625502/64990325-9bfc9e80-d89d-11e9-85cd-aa09f754e048.png">

**Comment by dlabrecq** [comment]
Cannot reproduce with the examples.

If you rebuild clean, does it still occur?

**Comment by TheRealJon** [comment]
Yes, v5.0.0 with a fresh yarn install and build. I get this warning on the ChartDonutUtilization, ChartDonut, and ChartPie doc pages.

**Comment by dlabrecq** [comment]
Odd about ChartPie and ChartDonut. There are no lists or maps in either source. In fact, ChartPie is a really simple component.

**Comment by TheRealJon** [comment]
I think it has something to do with how the container component is cloned, then the children are passed in as an array (chart, getTitle(), getSubTitle()).

**Comment by dlabrecq** [comment]
Interesting... We're cloning the container because folks started providing their own in an effort to set `responsive=false`. 

Although it doesn't seem to matter if we clone or just use ChartContainer directly. If I make any change in the code, it will generate a key error for either scenario. If I then build clean, there's no error.

ChartDonutThreshold
![Screen Shot 2019-09-16 at 5 30 53 PM](https://user-images.githubusercontent.com/17481322/64994994-13cfc680-d8a8-11e9-94d2-9a2c022e25c0.png)

**Comment by dlabrecq** [comment]
Please take a look at PR https://github.com/patternfly/patternfly-react/pull/2943. If that doesn't work for you, perhaps we can use it as a base to debug further?

**Comment by dlabrecq** [comment]
I can reproduce the message consistently by changing `ChartPie` to simply render this:

![Screen Shot 2019-09-17 at 11 02 24 AM](https://user-images.githubusercontent.com/17481322/65054011-e08a4780-d93a-11e9-987d-87582d9d3652.png)

No legend, no container wrapper, etc...

![Screen Shot 2019-09-17 at 10 42 27 AM](https://user-images.githubusercontent.com/17481322/65054017-e3853800-d93a-11e9-9468-3eb577126301.png)

**Comment by dlabrecq** [comment]
There seems to be two issues; cloning the container and the labels prop. If the property was passed thru via `rest`, the warning was generated. It didn't matter if we cloned ChartContainer or VictoryContainer. 

That said, I was able to clone the container differently and eliminate my local warning messages. The tests no longer generate warnings, either.
