### ISSUE TITLE
Remove bindMethods in favor of Class properties

### ISSUE THREAD

**Issue by dmiller9911** [patternfly/patternfly-react#294]
Class properties are on their way to making it into the spec. Moving to them will also align us better with the greater React community since many projects have adopted this syntax.  Example of the change is below:
### Before
```jsx
class SomeComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isLoading: false,
    };
    bindMethods(this, ['handleClick']);
  }
  handleClick() {}
}
```
### After
```jsx
class SomeComponent extends Component {
  state = {
    isLoading: false,
  };
  handleClick = () => {}
}
```
[TC39 Proposal](https://github.com/tc39/proposal-class-fields)
[Stage Explanations](https://tc39.github.io/process-document/)

**Comment by dmiller9911** [comment]
I would say that this repo should use class properties, and then leave it up to consumers on whether they want to use `method.bind`, reflective-bind babel, or something similar to `bindMethods`.  I don't think that this repo should provide `bindMethods` though. The goal of the repo, at least in my opinion, would be to provide react components, along with promoting some best practices.  Class properties in my mind are a best practice and bindMethods should be avoided.  This is for a few reasons.
1. The majority of the React community is using class properties. Both create-react-app and react native support them out of the box through their babel-presets.
2. Class Properties make it harder to set the methods directly out of the context of the rendered react component.
3. They generate less code. See [babel REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAEAqCmEAu0DeAoAkABwE4HtsBGaAXmgAoBKMgPjQF91oXo9CAmMym0-1JqzYFsAZm7U6jdE3ShIMAPJIAFvFxoswfADtkuAK7Ak-XJIxCWqgJYQAdO2Lcb9xxCJ2ARtZ0ATCi5UANzMli4OIlzk4W4e3n4BKrbBoUIxIuLRSa4i7l4-_oEhQoLQOCJE5qUsjhxVqcKEovWy2noo8b4AsvCq-L4w5BRtSPAAHkgANNAAtr0q_RC8_KEA9KvQiCA-SAC0vrZgniDwuzrje9vn0Dr4u20Q-CehD0_wdgDuYLg6FAAGqU6PT6A2gBggYAA5vBoLZoL54Hh4MAwKNfLCdNAAGZgABupmg-Cx0HkUFm80WdkBBWBC1BH2sIBA0E8MNw8Bm-Fx8HRPmgqhh5wmszAACsCeyTpB4Kk_ikWHMQfYsaYAKJgYAqCiKulSCysEYXADaOv6AF1uIaJiaKb4zfkElakPLoAwUgwQnJwGTlGpcDAMJgHkhDMZTOYGiwgbaIIlbNMjQByRxERPTZORNPQDNNRNmqgNUrlQiVGgCBq1epCRzNMtMBhAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)
4.  They are faster. See jsperf: https://jsperf.com/class-property-vs-bind/1

I do believe deprecating is a good idea, but if the rest of the community around this needs this I am ok with leaving it in.

**Comment by jeff-phillips-18** [comment]
I'm in agreement with @dmiller9911. It's not the intention of this repo to provide that type of helper, especially if it's not being used within the repo.
