### ISSUE TITLE
Error using react-table actions: compilation error

### ISSUE THREAD

**Issue by lucasponce** [patternfly/patternfly-react#2944]
Using react-table "@patternfly/react-table": "2.17.5" I have following compilation error inside the component:

```
Failed to compile.

/home/lponce/Projects/repos/kiali-ui/node_modules/@patternfly/react-table/src/components/Table/ActionsColumn.tsx
TypeScript error in /home/lponce/Projects/repos/kiali-ui/node_modules/@patternfly/react-table/src/components/Table/ActionsColumn.tsx(54,84):
Argument of type 'IRowData | undefined' is not assignable to parameter of type 'IRowData'.
  Type 'undefined' is not assignable to type 'IRowData'.  TS2345

    52 |     event.preventDefault();
    53 |     // tslint:disable-next-line:no-unused-expression
  > 54 |     onClick && onClick(event as React.MouseEvent, extraData && extraData.rowIndex, rowData, extraData);
       |                                                                                    ^
    55 |     this.setState({
    56 |       isOpen: !this.state.isOpen
    57 |     });

```

Client code is something like this:

```
  // @ts-ignore
  actionResolver = (rowData: IRowData, extraData: IExtraData) : (IAction | ISeparator)[] => {
    if (rowData) {
      return [
        {
          title: 'Remove Rule',
          // @ts-ignore
          onClick: (event, rowIndex, rowData: IRowData, extraData)  => {
            if (rowData) {
              console.log(`clicked on RemoveRule action, on row ${rowIndex} of type ${rowData.type}`)
            }
          }
        }
      ];
    }
  };
```

```
      <Pf4Table
        cells={headerCells}
        rows={routeRules}
        actionResolver={this.actionResolver}
      >
        <Pf4TableHeader />
        <Pf4TableBody />
      </Pf4Table>
```

**Comment by lucasponce** [comment]
With react-scripts 3 we could finally workaround this changing tsconfig.json

```
 "strictNullChecks": false,
 "noUnusedParameters": false,
```

And using ` // @ts-ignore ` with some areas of the code.

Not ideal, but it's a workaround. 

I think perhaps react-table component should be protected to be used in react-scripts 3 scenarios.

**Comment by jotak** [comment]
I really wish we get a fix about that in Patternfly as the "solution" being to disable null-checks in consuming projects is really not satisfactory.

**Comment by lucasponce** [comment]
Absolutely, I hope @tlabaj can maintain this open and probably to involve authors of the react-table project for this.

The workaround is used to solve a blocker, but as you commented, it's not a "solution", I'd call it a "hack".

**Comment by lucasponce** [comment]
Closing this.
Finally there was a bad import that triggered ts compiler inside the react-table and in our project we have a more strict settings, but yes, fixing the wrong import fixed the problem, and we can consume react-table no matter what level of strict was used in that specific module.
