### ISSUE TITLE
PF4: Investigate what library to use  for the Date and Time Picker(s)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#2947]
Some investigation need to be done to determine what library we should use to implement the Dat and Time Picker(s).  The library chosen should support  our design.  This is related to core issue [#180 ](https://github.com/patternfly/patternfly-next/issues/180)

**Comment by dgutride** [comment]
Before a library can be chosen - we need to understand what product requirements are for timezone impacts on the date in a picker.  If there is any need to move a date or time based on a user defined timezone in any application, momentjs and general javascript date solutions would not be appropriate.

**Comment by dgutride** [comment]
This document outlines necessary technical considerations when reviewing a library:
https://docs.google.com/document/d/1HCUTWCk3It3pIRYFLD83H-wThA10yUs7KLJM3fU5Q7Y/edit?usp=sharing

**Comment by jcaianirh** [comment]
I updated the google doc with the investigation results. 

https://docs.google.com/document/d/1HCUTWCk3It3pIRYFLD83H-wThA10yUs7KLJM3fU5Q7Y/edit#heading=h.i6wtpaspo49f

Closing this issue.
