### ISSUE TITLE
RFE: Extend the "name" property in legends to accept react components/ html elements

### ISSUE THREAD

**Issue by afreen23** [patternfly/patternfly-react#2968]
### Current Scenario
The legends are defined as an array of objects of the following type:
```
{  name: string }
```
### Desirable Feature
Make `name` property to be of React Elements or Html Elements as well.

I needed it in a scenario where I want to make it a link.
Extending this can help in creating more custom legends

**Comment by afreen23** [comment]
Luckily found a solution for having this implemented.
We need to create custom legend component for doing anything extra on top of legends.
```
          <ChartLegend
            data={legends}
            labelComponent={<MyCustomLabels>}
            }}
```

**Comment by dlabrecq** [comment]
This is exactly how Victory supports customization. If you wanted to add tooltips; for example, this is how that feature would be added.
