### ISSUE TITLE
RFE: Manage empty space between the bars of Bar Charts

### ISSUE THREAD

**Issue by afreen23** [patternfly/patternfly-react#2971]
![bar](https://user-images.githubusercontent.com/25664409/65277081-cb820400-db46-11e9-9d47-6360ed986525.png)

### Issue

When there are only two datapoints the bars have a lot of empty space in between
Adding `domainPadding` just centralizes them.
If somebody needs to have bars left aligned, then it is not possible to fix this issue, except adding the extra conditions in code, to maintain the state when there are two datapoints and when there are not.

**Comment by rachael-phillips** [comment]
@dlabrecq does Victory charts allow for this? Curious to hear your thoughts!

**Comment by dlabrecq** [comment]
This was something we chatted about on the PatternFly charts channel. Victory evenly positions bars according to the size of the chart. The larger the chart, the more space between them.

You can adjust the chart size or adjust the position of each bars using the Chart's `domainPadding` property. For example, `domainPadding={{ x: [125, 125] }}` could be applied dynamically based on the number of data points you provide.

![Screen Shot 2019-09-24 at 9 46 17 AM](https://user-images.githubusercontent.com/17481322/65517318-80525300-deb0-11e9-861d-106d5b2a1cb3.png)

I don't know of any use case where the bars must be right aligned, but , you can adjust the padding so bars like so `domainPadding={{ x: [200, 10] }}`.

![Screen Shot 2019-09-24 at 9 48 13 AM](https://user-images.githubusercontent.com/17481322/65517339-89dbbb00-deb0-11e9-9f42-020d6dde910f.png)

The `offset` property for ChartGroup changes the spacing between bars.

**Comment by afreen23** [comment]
> I don't know of any use case where bars must be "right aligned", but you could potentially adjust the padding like so `domainPadding={{ x: [200, 10] }}`.

Sorry for the typo, I mean , if I want a left aligned graph, I wont be able to do that.
The `domainpadding` will centralize them up.
Moreover this ugly case with two datapoints, even with three, it does not look as bad.

Also @dlabrecq `offset` will create a space between the set of bars only.
We want to have something between the datapoints.

Now digging more into it, feels like a victory chart issue and understand that modifying anything on top of the victory chart here could break things in future.
I would rather create an issue there.

Thank you @dlabrecq @rachael-phillips

**Comment by dlabrecq** [comment]
I prefer Victory's default behavior in favor of consistency. However, I believe you can still achieve left alignment with something like `domainPadding={{ x: [25, 500] }}`.

![Screen Shot 2019-09-24 at 2 56 15 PM](https://user-images.githubusercontent.com/17481322/65541669-c5d84580-dedb-11e9-9447-7970e7e6ab4b.png)
The width in this particular example is 600px.

Feel free to reopen if needed.
