### ISSUE TITLE
Provide option auto-focus for Alert Component  

### ISSUE THREAD

**Issue by tonilxm** [patternfly/patternfly-react#2978]
Alert component should have option for auto-focus when rendered. This will allow user to focus on feedback after a long action (ie. filling a form).

**Comment by rachael-phillips** [comment]
Hi @tonilxm, a few quick questions for you: 

1. Is this issue currently blocking you?
2. What product is this request for?
3. What release version are you targeting?

Thank you!

**Comment by tonilxm** [comment]
Hi @rachael-phillips ,
1. Not an issue, more likely a feature request.
2. Alert as in '@patternfly/react-code'
3. PF4.

**Comment by boaz0** [comment]
@rachael-phillips can you please assign this to me too?
Thanks.

**Comment by rachael-phillips** [comment]
Hi @boaz0 this is currently under accessibility review, and we'll get back to you once that review has been complete. cc @jessiehuff @tlabaj
