### ISSUE TITLE
Incorrect alert on Spinner page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#2986]
There is an incorrect alert that appears on the spinner page that looks like: 
<img width="1167" alt="Screen Shot 2019-09-23 at 10 33 12 AM" src="https://user-images.githubusercontent.com/40275806/65434882-90552e80-dded-11e9-86f3-4626ac410fc3.png">

This needs to be corrected because it should look like: 

<img width="859" alt="Screen Shot 2019-09-23 at 10 34 04 AM" src="https://user-images.githubusercontent.com/40275806/65434961-afec5700-dded-11e9-9c44-373ce286f2fc.png">

Someone needs to remove that alert in patternfly-react repo and update the frontmatter in the examples markdown file to this i believe cc @jschuler 

section: 'experimental'
stage: 'early'

**Comment by tlabaj** [comment]
Closed by #3063
