### ISSUE TITLE
PF4 Table: The documentation needs improvements

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#2999]
- [ ] Clearly define the type of the `cells` and `rows` properties of the `Table` component
    - [ ] What is `IRow` - All properties here should be mentioned in the documentation
    - [ ] What is `ICell` - All properties here should be mentioned in the documentation
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-table/src/components/Table/Table.tsx#L127..L138
- [ ] What is `RowWrapper` and `BodyWrapper` - the props description mentions only that it's a Function.. 
- [ ] `cellFormatters`, `columnTransforms`, `cellTransforms`, `formatters`, `transforms` are not documented at all - there is issue about it but let's keep it here as well since this issue is more extended https://github.com/patternfly/patternfly-react/issues/2990
- [ ] The `TableBody` and `TableHeader` components are supposed to be used with properties? The examples never use them (Just use them without properties - and I guess the properties we pass to Table are propagated internally)
But it really makes sense for the consumers to be able to use `TableBody` so we need examples for that.
     - [ ] trying to use `TableBody` outside of table and without properties passed (which should be fine since the docs don't have any marked as required props gives error: TypeError: headerData is null 
- [ ] The link to the properties takes you to wrong place when clicked https://www.patternfly.org/v4/documentation/react/components/table/#tablebody-props
- [ ] `rowLabeledBy` property does not make sense to be part of the table (or I understand wrong what it is about?) It's row should be able to have it's only `rowLabeledBy` property.
- [ ] I could not find anywhere documented how to apply custom classes on Rows (in our use case we want to mark rows with a color that signals a warning if the resource on that row has some issue) 
- [ ] Document `TableVariant`

Note:  I will keep editing that inline as I find more issues.

**Comment by rachael-phillips** [comment]
Hi @KKoukiou we would like to turn this issue into an epic, so we can track your list in separate issues. Which list items have been completed so far with PR #3016?

**Comment by KKoukiou** [comment]
> Hi @KKoukiou we would like to turn this issue into an epic, so we can track your list in separate issues. Which list items have been completed so far with PR #3016?

None really... All of the above remain todo.

**Comment by jschuler** [comment]
This is nice, let's reopen this since we have a related issue to improve the documentation here https://github.com/patternfly/patternfly-react/issues/4793

**Comment by cben** [comment]
meanwhile some code pointers (I'm trying to see how to write my own transform/formatter... the following is my partial understanding):
- transforms/cellTransforms/formatters/cellFormatters from various sources are collected into simpler `transforms` and `formatters` arrays here: https://github.com/patternfly/patternfly-react/blob/master/packages/react-table/src/components/Table/utils/headerUtils.tsx
- applied in https://github.com/patternfly/patternfly-react/blob/master/packages/react-table/src/components/Table/base/evaluate-formatters.ts
- and https://github.com/patternfly/patternfly-react/blob/master/packages/react-table/src/components/Table/base/evaluate-transforms.ts
- both of which are called from https://github.com/patternfly/patternfly-react/blob/master/packages/react-table/src/components/Table/base/header-row.tsx, https://github.com/patternfly/patternfly-react/blob/master/packages/react-table/src/components/Table/base/body-row.tsx
