### ISSUE TITLE
Component - List

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#30]
Implement a component that provides the following UI element:

- [PatternFly List View](http://www.patternfly.org/pattern-library/content-views/list-view/)

Adds the new List styles here:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/list-pf.html

Started in #63 . Needs help ;)

Acceptance Criteria:

- When rendered, the component matches the examples in the PatternFly Pattern Library (see link above)

**Comment by waldenraines** [comment]
Shouldn't this be closed now?

**Comment by priley86** [comment]
good point! I will close #21 and leave this open... hoping to revisit the new list in #31 soon...

**Comment by priley86** [comment]
This PF3 issue is stale and no longer being actively worked. Closing this for now. Will reopen if we determine it is needed later.
