### ISSUE TITLE
Uncaught error when using Cards with height matching

### ISSUE THREAD

**Issue by michaelkro** [patternfly/patternfly-react#300]
Seeing this error in Chrome console when using Card with height matching

```
Uncaught TypeError: Cannot read property 'apply' of undefined
at helpers.js:15
```

Seems to have something to do with the use of the debounce helper [helpers.js](https://github.com/patternfly/patternfly-react/blob/master/src/common/helpers.js#L10)

## To Replicate Issue
1. Open storybook locally
2. Visit Cards --> Base Card w/HeightMatching
3. Inspect JS console

**Comment by priley86** [comment]
Hmm - this is different than the other issue I was having in #296. thanks @michaelkro

**Comment by dmiller9911** [comment]
Looks like this is the culpurate: [CardHeightMatching.js#L23](https://github.com/patternfly/patternfly-react/blob/master/src/components/Cards/CardHeightMatching.js#L23)
```jsx
        new ResizeSensor(
          elements,
          debounce(this._matchHeights([selector]), 200)
        )
      );
```
The `this._matchHeights([selector])` is invoked inside the debounce arg.  This should be something like 
```jsx
        new ResizeSensor(
          elements,
          debounce(() => this._matchHeights([selector]), 200)
        )
      );
```
