### ISSUE TITLE
PF4 Table: TableBody documentation not accurate

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#3018]
I noted in conversation w/ @KKoukiou today that some props currently showing in the `TableBody` definition are calculated (and not typically passed by a consumer). We should hide those props from the documentation:

<img width="969" alt="Screen Shot 2019-09-26 at 12 53 32 PM" src="https://user-images.githubusercontent.com/4237045/65708523-c4825680-e05c-11e9-8f2b-406326ed0365.png">

Alongside this issue, it may be nice to add an example to our docs with a "custom row wrapper". Here is one such example. This could also be modified to have `CustomRowWrapper` just render `RowWrapper` passing className prop... 
https://github.com/priley86/patternfly-react/commit/a020e837ff7e1e2ce0e40b65847c2e3ef0e148c7

**Comment by redallen** [comment]
Yes, I agree we should add a frontmatter or some special syntax in the interface definition (maybe `@hide`?) to hide props from the docs. I prefer the latter, but it'll take tweaking our `gatsby-transformer-react-docgen-typescript`.
