### ISSUE TITLE
Disappearing-selection bug in OptionsMenu caused by event handler change in InternalDropdownItem

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#3029]
In the OptionsMenu examples at https://patternfly-react.surge.sh/patternfly-4/components/optionsmenu/, changing the selection in the "single option" menu fails and causes the selection to disappear entirely.

![yuqLFtEQDl](https://user-images.githubusercontent.com/811963/65788990-5dcb6e80-e12a-11e9-9784-87e0e530844e.gif)

This is a bug that @nicolethoen noticed when working on her PR for chip groups in DataToolbar: https://github.com/patternfly/patternfly-react/pull/2969. It was causing errors in her usage of OptionsMenu for that chip groups example, and she initially fixed it with the help of @jschuler in this commit: https://github.com/patternfly/patternfly-react/pull/2969/commits/5544f2822bd7697e32bd6dbbc36b9fe3b7d1bde2

That fix caused unit test failures, and it turned out that according to @mcarrano we should have used Select instead of OptionsMenu for that PR's examples, so the fix was reverted and the issue was worked around by instead removing OptionsMenu from that PR. As a result, this bug still exists in master.

@jschuler found that it was caused by changes to the event handlers in the InternalDropdownItem component made in his recent PR https://github.com/patternfly/patternfly-react/pull/3011. I verified this by testing [the surge deployment from the PR merged immediately before that one](https://patternfly-react-pr-2981.surge.sh/patternfly-4/components/optionsmenu/) (https://github.com/patternfly/patternfly-react/pull/2981), where the bug is not present, and [the surge deployment from 3011](https://patternfly-react-pr-3011.surge.sh/patternfly-4/components/optionsmenu/), where it is.

To fix this we can probably cherry-pick [Nicole's commit](https://github.com/patternfly/patternfly-react/pull/2969/commits/5544f2822bd7697e32bd6dbbc36b9fe3b7d1bde2) and then work out the unit test failures.

**Comment by rebeccaalpert** [comment]
The unit test failures are happening in the keyhandler-related tests in util.test.js. Keyhandler is still behaving as expected in real life (and I confirmed that ids are being passed along correctly). For whatever reason, we're getting a null document.activeElement during the test, so the focus test fails. I'm going to look into alternative ways of checking the focus.
