### ISSUE TITLE
Clarification about dependency on node_modules/@patternfly/react-core/dist/styles/base.css

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3038]
From the documentation it is clear that we should import the css file mentioned in the title so that the components we use will not diverge in appearance from the ones we see in the blog. See https://github.com/patternfly/patternfly-react/tree/master/packages/patternfly-4/react-core#pre-requisites

My question here is, since that component clearly needs that file to look as expected why you don't import that file from inside the components code and expect the end user to do that?

This is not meant to be an bug report - I just need to understand why this css file is expected to be imported by the end user and not the react-core code itself.

Thanks for the feedback in advance.

cc @jkozol

**Comment by jschuler** [comment]
Hi @KKoukiou , as far as I can remember, it used to be the case that the common css and variables was bundled into each component, but that duplication came at the cost of size, so the decision was taken to take out common css and put it into a separate base.css file to keep the component css leaner. CC @mcoker
