### ISSUE TITLE
Inline Alert: icon hidden by background

### ISSUE THREAD

**Issue by xeviknal** [patternfly/patternfly-react#3039]
Hey there,

I am trying to implement a Inline Alert (both variants: Success and warning). The problem I have is the following:

![Screenshot of Kiali Console (50)](https://user-images.githubusercontent.com/613814/65893976-3cc48100-e3a9-11e9-93c3-72ac7682df82.jpg)

The Icon is hidden behind the background image. It looks like the components puts both icon and backgound in the same color.

![modal-inline-alert-bgn-error](https://user-images.githubusercontent.com/613814/65894225-aa70ad00-e3a9-11e9-8fb0-fdcc9e18ace7.png)

```tsx
<Alert
  title="Debug information has been copied to your clipboard."
  variant={AlertVariant.success}
  isInline={true}
  action={<AlertActionCloseButton onClose={this.hideAlert} />}
/>
```

```tsx
<Alert
  title="Debug information was copied to your clipboard, but is outdated now. It could be caused by new data received by auto refresh timers."
  variant={AlertVariant.warning}
  isInline={true}
  action={<AlertActionCloseButton onClose={this.hideAlert} />}
          />
```

After unmarking the background property from `.pf-c-alert__icon`, the Alert is properly rendered.

Am I doing something wrong?

Thank you,

**Comment by mcoker** [comment]
Hi @xeviknal the value of `background-color` should be `transparent` or `#0000` for inline alerts. Are you importing patternfly core (`@patternfly/patternfly`) separately or are you using what comes with patternfly-react? It looks like you aren't getting the correct styles for the inline variation of the alert component.

This is from https://www.patternfly.org/v4/documentation/react/components/alert/

<img width="1459" alt="Screen Shot 2019-09-30 at 1 17 33 PM" src="https://user-images.githubusercontent.com/35148959/65904902-0d9c1880-e385-11e9-8fd0-29246cb9efdb.png">

**Comment by xeviknal** [comment]
Hey @mcoker :)

I am importing the library like follows:

```
import { Alert, AlertActionCloseButton, AlertVariant, Button, ButtonVariant, Modal } from '@patternfly/react-core';
```

Actually you can see the source code here if that could provide you more information:
https://github.com/kiali/kiali-ui/pull/1455/files

Here another screenshot with the css:

![background-alert-error](https://user-images.githubusercontent.com/613814/65944037-219d5400-e431-11e9-98f3-b5a99954e77e.png)

Looks like the following overrides the transparent background:
```
.pf-c-alert__icon {
    background-color: var(--pf-c-alert__icon--BackgroundColor);
}
```

In the parent element `div class=pf-c-alert pf-m-inline pf-m-success` I see that the background it doesnt take the inline bg color but the normal one:

```
.pf-c-alert.pf-m-warning {
    --pf-c-alert__icon--Color: var(--pf-c-alert--m-success__icon--Color);
    --pf-c-alert__icon--BackgroundColor: var(--pf-c-alert--m-success__icon--BackgroundColor);
    --pf-c-alert__title--Color: var(--pf-c-alert--m-success__title--Color);
}
```

Whilst in the documentation page I see this:

```
.pf-c-alert.pf-m-inline {
    --pf-c-alert--BoxShadow: var(--pf-c-alert--m-inline--BoxShadow);
    --pf-c-alert__icon--BackgroundColor: var(--pf-c-alert--m-inline__icon--BackgroundColor);
}
```
That changes the background color bar to inline icon bg color. This chunk (I THINK) is missing in the version I am using:

```
"@patternfly/patternfly": "2.4.1", 
```

Thank you

**Comment by SpyTec** [comment]
Looking at the CSS in patternfly-next and they appear correct, so does my own React application and any experiments I've tried.

Trying out Kiali I do see the issue happening, but it seems like the CSS has been moved about. Inline is now at the very beginning of the inline CSS, whereas danger is now at line ~4000 when I ran it.

I would presume this has something to do with the build process and isn't related to PatternFly

![image](https://user-images.githubusercontent.com/6598829/65956213-26223680-e44a-11e9-9296-0efa5ea57358.png)

**Comment by xeviknal** [comment]
Thank you @SpyTec, Ill check that out. Could this be because we have both PF3 and PF4 coliving in the same project?

**Comment by SpyTec** [comment]
PF3 has different classes for alerts so that wouldn't be the problem. I would put my bets on the project importing PF4 CSS in an incorrect manner or if you're importing multiple things from PF4, that it's in the wrong order

**Comment by xeviknal** [comment]
Do you guys have documentation about how to do these imports?
We are doing this way: https://github.com/kiali/kiali-ui/blob/master/src/styles/index.scss

**Comment by SpyTec** [comment]
For my app I'm using something like this, which will include everything that's needed AFAIK. [Which is documented on the website](https://www.patternfly.org/v4/get-started/developers#install-and-configure-patternfly-react)

```scss
@import '~@patternfly/patternfly/patternfly.scss';
```

**Comment by xeviknal** [comment]
Good, thanks for that. I'll play around next week.
@aljesusg we should check that out together :)
