### ISSUE TITLE
Organization of storybook examples

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#304]
Currently, the way patterns are organized in [patternfly.org](http://www.patternfly.org/pattern-library/) and the [patternfly-react storybook](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html) do not align very well.

As a first step to making the organization of components in storybook better aligned with the information architecture in pf.org, we’d like to introduce a third level of grouping to the storybook components. This change includes the following updates:

1. The extra level is on top of what we currently have, and will become the 1st level group.
2. How storybook examples are currently grouped can remain as-is, unless there’s a reason to change that grouping. 
3. Structural patterns can be separated from UI patterns

The 1st level groupings we should use are the following. Refer to http://www.patternfly.org/pattern-library/ for what storybook examples would fall within these categories.

-  Application Framework
- Cards  
- Communication  
- Content Views  
- Dashboard  
- Data Visualization  
- Forms and Controls  
- Navigation  
- Widgets

**Comment by jeff-phillips-18** [comment]
without adding another layer I guess that's a good starting point. I'll start taking a look at adjusting to this to see how it goes.
