### ISSUE TITLE
For Popover, allow to hide close box

### ISSUE THREAD

**Issue by mtho11** [patternfly/patternfly-react#3043]
In migrating the from PF3 to PF4 the new [popover](https://patternfly-react.surge.sh/patternfly-4/components/popover/) component always displays the close box and there is no way to hide the close box.

Here is the PF4 Popover with close box:
![hide-closebox](https://user-images.githubusercontent.com/1312165/65921349-d9c9ee80-e396-11e9-9b56-3edd5a171bc6.png)

This is our [Kiali](https://www.kiali.io) current PF3 screen:
![old-popover](https://user-images.githubusercontent.com/1312165/65920950-8dca7a00-e395-11e9-9bc1-db3980523005.png)
That is what I want to replicate with PF4 version of Popover.

**Comment by mtho11** [comment]
We also have another more complicated Popover for namespaces:

![namnespace](https://user-images.githubusercontent.com/1312165/66231680-ee123200-e69b-11e9-9153-ac9d684049cf.png)

**Comment by tlabaj** [comment]
It looks like a different component will be used for this use case so I will be closing this issue.  Please feel free to open a new issue if you have any more concerns.
