### ISSUE TITLE
Correct naming of all components that should map 1:1

### ISSUE THREAD

**Issue by janwright73** [patternfly/patternfly-react#3062]
This issue is linked to:
https://github.com/patternfly/patternfly-org/issues/1486

React
Application Launcher some of the example names need updating ** app to application**
DataToolbar should be Data toolbar
FormSelect should be Form select
Nav should be Navigation
NotificationBadge should be Notification badge
TopologyView should be Topology view

**Comment by tlabaj** [comment]
Closed by PR #3054
