### ISSUE TITLE
Tooltip: Provide examples on how/why to use TooltipContent

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#3088]
This is a follow-up issue for #3013

We export `TooltipContent` in `Tooltip/index.ts` but don't show its props in the docs.

Edit: We should provide examples on how/why to use `TooltipContent`.

_Originally posted by @redallen in https://github.com/patternfly/patternfly-react/pull/3053_

**Comment by tlabaj** [comment]
@jenny-s51 I actually think that TooltipContent is internal and probably should never have been exported.  @jschuler do you know if this is the case?

**Comment by jschuler** [comment]
@jenny-s51 @tlabaj I don't see `TooltipContent` exported in https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Tooltip/index.ts and it shouldn't be as it is indeed an internal component. Looks like it snuck into the examples md file and references to it should be removed from there
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Tooltip/examples/Tooltip.md

Thanks!

**Comment by tlabaj** [comment]
Let's use this issue to track the work to clean up the md file.

**Comment by jenny-s51** [comment]
@tlabaj will do! it's listed in `Tooltip.md` in two places: under prop components, and in the import statement. Just to confirm, did you want me to remove both occurrences of `TooltipContent` in this file?

<img width="787" alt="Screen Shot 2019-12-20 at 12 02 04 PM" src="https://user-images.githubusercontent.com/32821331/71270902-b15fe980-2320-11ea-8f82-85f4ba437c97.png">
