### ISSUE TITLE
PF4 Table causes warning about duplicate keys if a column named ID exists on the table

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3090]
The warning looks like this:
```
Warning: Encountered two children with the same key, `[object Object]-row`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in tbody (created by BodyWrapper)
    in BodyWrapper (created by BaseBody)
    in BaseBody (created by Context.Consumer)
    in Body (created by ContextBody)
    in ContextBody (created by Context.Consumer)
    in TableBody (created by App)
    in table (created by Provider)
    in Provider (created by Table)
    in Table (created by App)
    in App
```

The problem is that rowData.id will be the rows cell description which is an object and not the id of the table. 
This the code here https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-table/src/components/Table/base/resolve-row-key.ts#L34
will end up creating for rowKey something that is {Object}-row which of course is not valid.

From the code it looks like there is way to WA it by passing a function for the rowKey, https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-table/src/components/Table/base/resolve-row-key.ts#L20

But I was not able to make the Table component accept such property. ( I assume that this property should be part of the row object)

A minimal example on how to reproduce the issue can be found here https://github.com/KKoukiou/patternfly-react-table-example/tree/duplicate-keys-column-id

**Comment by seanforyou23** [comment]
@KKoukiou it's not currently obvious from our docs, but you can instead attach the `rowKey` property directly to the TableBody component like so

`<TableBody rowKey={({ rowData, rowIndex }) => rowIndex} />` - that would basically generate the same type keys as they come out of the box. To customize the keys, you can incorporate rowData into the key like so

```js
const rowKeyResolver = ({ rowData, rowIndex }) => {
  return `${rowIndex}-${rowData.props.foo}`;
};
```

Another way of doing this is using a static property like so

```js
  {
    customStaticProperty: "custom-key-2",
    cells: [
      { title: "Row 2 column 1" },
      { title: "Row 2 column 2" },
      { title: "Row 2 column 3" }
    ]
  }
```

```jsx
<TableBody rowKey="customStaticProperty" />
```

Both of these approaches have the string `-row` appended to the end of the keys (just check with react dev tools).

We're giving the Table docs an [overhaul](https://github.com/patternfly/patternfly-react/issues/3099), I'll make sure these details are captured correctly. I'll close this issue in favor of the one I linked, feel free to re-open if something isn't clear. Thanks for bringing this up!
