### ISSUE TITLE
Compact sized table is not shrunk when used with <VirtualTableBody>

### ISSUE THREAD

**Issue by tonilxm** [patternfly/patternfly-react#3103]
Compact Table row size is not shrunk when used with `<VirtualTableBody>` from '@patternfly/react-virtualized-extension'.

**Comment by rachael-phillips** [comment]
@tonilxm could you provide us with an example of how you are using this? A code snippet would be great, thank you!

**Comment by rachael-phillips** [comment]
@tonilxm hello again! Do you mind providing us with an example of how you are using this? A code snippet would be great, thank you!
