### ISSUE TITLE
Missing Slider component from @patternfly/react-core

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3104]
The equivalent from PF3 is https://www.patternfly.org/v3/pattern-library/forms-and-controls/slider/

**Comment by LHinson** [comment]
Hey @KKoukiou thanks for filing this. we have a related issue over on the core side here: https://github.com/patternfly/patternfly-next/issues/296

I imagine you are currently still using the PF3 slider in the interim? We have a number of priorities ahead of this component and trying to determine if the PF3 slider is sufficient for now while we wait on the PF4 version. 

Thanks for you input!

**Comment by KKoukiou** [comment]
> Hey @KKoukiou thanks for filing this. we have a related issue over on the core side here: [patternfly/patternfly-next#296](https://github.com/patternfly/patternfly-next/issues/296)
> 
> I imagine you are currently still using the PF3 slider in the interim? We have a number of priorities ahead of this component and trying to determine if the PF3 slider is sufficient for now while we wait on the PF4 version.
> 
> Thanks for you input!

Hey @LHinson! we are actually not using PF3 sliders, but have our own implementation still, since there where some issues.
This is already solved: https://github.com/patternfly/patternfly-react/issues/783
But I opened one more today actually:
https://github.com/patternfly/patternfly-react/issues/3179

**Comment by garrett** [comment]
Update: We've actually switched to using PF3 sliders a little while back, but restyled like the WIP mockup for the PF4 sliders.

Reasoning: PF3's implementation was better than our own and styling them like PF4's upcoming sliders (whenever it is implemented) means swapping them out would basically improve the accessibility even further.

**Comment by LHinson** [comment]
Oh this is helpful to understand @garrett and @KKoukiou. If that's the case, we will look at prioritizing https://github.com/patternfly/patternfly-react/issues/3179. I've re-opened that issue.

**Comment by garrett** [comment]
This is still relevant, regardless of what stale bot "thinks". PF4 & PF4-React still need some sort of slider widget.

**Comment by KKoukiou** [comment]
@mcarrano I know we have talked about it, can we prioritize it in the backlog?
In addition I feel this belongs also to the @patternfly/patternfly repository.

**Comment by mcarrano** [comment]
@KKoukiou We are beginning work on this now. You can follow progress here: https://github.com/patternfly/patternfly/issues/296 We are currently targeting to release a React component in our 2021.01 milestone (end of January).

**Comment by KKoukiou** [comment]
This is released. It's missing some features [1] but its' already usable.

[1] https://github.com/patternfly/patternfly/issues/3864
