### ISSUE TITLE
react-console: Buttons are glued together

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3105]
![Screen Shot 2019-10-10 at 16 10 24](https://user-images.githubusercontent.com/14921356/66576727-7e5ae600-eb78-11e9-96d4-5e37e5872d24.png)

The dropdown button for Send key and the button for Disconnect are glued together.

It would look better if there was some space in between. Feel free to close if the design team disagrees.

(initially reported in Cockpit https://github.com/cockpit-project/cockpit/issues/12833)

The fix should probably be to add some css here https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/react-console/src/VncConsole/VncActions.js#L18

**Comment by rachael-phillips** [comment]
@kybaker , @mceledonia , and @mcarrano the buttons are sticking together in this issue. This is a PF3 issue. Is this an issue we want to fix in PF3?

**Comment by mcarrano** [comment]
I agree that there should be some spacing. But given that this is PF3, I don't believe we can simply drop these buttons into a standard layout as we would for PF4. My assumption in the there is some additional HTML or CSS that is needed to properly space these. @mcoker any idea how this can be made to work in a PF3 context? Components are arranged using the Bootstrap grid system, correct?

**Comment by rachael-phillips** [comment]
Updating here that we do not need a Core update - this will be an update in React

**Comment by nicolethoen** [comment]
@KKoukiou I just sent you a slack message. I'd love to ask you a few logistical questions when you get a chance! Thanks
