### ISSUE TITLE
[PF4] [Popover] Popover title bottom margin too big

### ISSUE THREAD

**Issue by jiridostal** [patternfly/patternfly-react#3134]
All our mockups show that popover title margin is smaller, can we please revisit this?

Now:
![image](https://user-images.githubusercontent.com/6286045/66749302-cd12c380-ee89-11e9-9edb-4836f9370675.png)

Expected:
![image](https://user-images.githubusercontent.com/6286045/66749445-3692d200-ee8a-11e9-8b1f-42cba1d3f251.png)

@katierik

**Comment by katierik** [comment]
Key issue is adding a table inside the popover.

**Comment by tlabaj** [comment]
cc @mcoker @kybaker

**Comment by mcoker** [comment]
+ @mceledonia we use a 24px/large spacer below the popover title. Should we consider changing that or offering a variation for a smaller spacer? 

This is also something consumers can override in their application, either globally, as a one-off, or by defining their own variant overriding the `--pf-c-popover--c-title--MarginBottom` variable to use a different spacer, like `--pf-global--spacer--md` or `--pf-global--spacer--sm`

**Comment by katierik** [comment]
For a Red Hat-made product, using Patternfly, would the recommendation be to override or to use the spacing that is included?

Perhaps a question to ponder for @LHinson @mcarrano @rachael-phillips

**Comment by mceledonia** [comment]
I would be in favor of dropping `--pf-c-popover--c-title--MarginBottom` down to `--pf-global--spacer--md` across the board. Is the issue here that a table doesn't fit at all, or that too much space between the header/body makes for an awkward look? I did think we had some flexibility in terms of popover size but it's been a while!

**Comment by katierik** [comment]
Its the awkward look :) The popover extends to meet the size a-ok

**Comment by mceledonia** [comment]
I'd drop it down from 24 to 16 under the header (..spacer--lg -> ..spacer--md) for the component, I don't think there's a strong reason to have a modifier or both, and I agree it is too large! @katierik @mcoker

**Comment by rachael-phillips** [comment]
@mcoker can we move this over to the Core repo? cc @jiridostal

**Comment by mcoker** [comment]
@rachael-phillips https://github.com/patternfly/patternfly-next/pull/2381 was already merged, so the change @mceledonia mentioned is updated in core. That said, we're only reducing the spacer by 8px (from 24px to 16px), and the screenshot in the original description looks like it's calling for an even smaller margin between the title and the content.

If the core update will work for this use case, I think we can close this issue either now or after react updates to core [v2.36.2](https://github.com/patternfly/patternfly-next/releases/tag/v2.36.2) and we verify the new spacing will work.

**Comment by rachael-phillips** [comment]
@jiridostal does the fix in patternfly/patternfly-next#2381 work for your use case?

**Comment by katierik** [comment]
Works for the design

**Comment by jiridostal** [comment]
@rachael-phillips Looks good! Thanks

**Comment by tlabaj** [comment]
Closing this issue since it was resolved in core.
