### ISSUE TITLE
ForwardRef issue with Tabs

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3143]
When I implement basic tabs I get the following

```sh
checkPropTypes.js?a15c:20 Warning: Failed prop type: The prop `title` is marked as required in `TabContainer`, but its value is `undefined`.
    in TabContainer (created by ForwardRef)
```

and 

```sh
Warning: Failed prop type: The prop `title` is marked as required in `Tab0`, but its value is `undefined`.
```

Seems like I've heard of others encountering similar issues, is there a known workaround or something I can check? I tried attaching refs as shown in one of the examples but no luck.

<img width="745" alt="Screen Shot 2019-10-14 at 8 11 33 PM" src="https://user-images.githubusercontent.com/5942899/66790697-dc603400-eebe-11e9-867f-b4e8591a33f1.png">

**Comment by boaz0** [comment]
@seanforyou23 this one got fixed by @tlabaj [here](https://github.com/patternfly/patternfly-react/pull/3031)

can you update the package and check that again?

Thanks.

**Comment by seanforyou23** [comment]
Thx @boaz0, I just needed to bump my version of react-core 👍
