### ISSUE TITLE
docs: Provide a "works with any framework/generic" setup minimal documentation 

### ISSUE THREAD

**Issue by ichtestemalwieder** [patternfly/patternfly-react#3171]
Hello, 

patternfly is absolutely great. And it is so well engineered and documented on a conceptuall level. But the devloper experience, i.e. the development usage docs, are quite the opposite and it is so hard to setup it up. You loose so many people thight might be interested in using patternfly. 

Its great that there is a demo Repo. But React development is so diverse. Millions of ways how to develop, and lots of people might for example want to use next.js with another dev workflow, so this repo does not help at all. Its a big black box.  

Please provide a rough guidline how to get a minimal React UI up and running: 

1.) What packages need to be added? 
2.) What elese needs to be done, seems wepback and babel are required? What are minimum Configs for both? 

What I did was: 
1.) Create a React Scaffold with Create React App 
2.) yarn add @patternfly/react-core (as documented https://www.patternfly.org/v4/get-started/developers)
3.) Copy an example page/component from here https://www.patternfly.org/v4/documentation/react/demos/pagelayout/#examples

=> And this completely fails (the layout is competlely missing). 

Please help me, so this will be documented for everyone interested, what the minium setup steps are.  

Thanks very much!

**Comment by rachael-phillips** [comment]
Hi @ichtestemalwieder thanks for the feedback. We'll get to the bottom of it. Did you start with React Seed as recommended at https://www.patternfly.org/v4/get-started/developers?
