### ISSUE TITLE
react-table 2.22.19 typing issue

### ISSUE THREAD

**Issue by israel-hdez** [patternfly/patternfly-react#3172]
In version 2.22.19 of react-table, which seems to be the latest at the time of writing, the sample found at this link is generating errors when building: https://www.patternfly.org/v4/documentation/react/components/table/#table-with-width-modifiers

The error is:

```
error TS2322: Type '(() => { className: string; })[]' is not assignable to type '((label?: (string & { title?: ReactNode; props?: any; }) | (object & { title?: ReactNode; props?: any; }) | (ComponentClass<any, any> & { title?: ReactNode; props?: any; }) | (FunctionComponent<any> & { ...; }) | undefined, rowData?: IRowData | undefined, columnIndex?: number | undefined, column?: IColumn | undefine...'.

168         transforms: [cellWidth(70)],
            ~~~~~~~~~~
```

Indeed, apparently, the `transforms` attribute of `ICell` is typed as `ITransforms` as seen in this code: https://github.com/patternfly/patternfly-react/blob/73c61699720ba29c5281183b3411dccfdde5aa05/packages/patternfly-4/react-table/src/components/Table/Table.tsx#L152-L164

But the `cellWidth` transform does not comply with that interface, so, typescript transpiler fails with error.

I think types/interfaces should be fixed.

**Comment by seanforyou23** [comment]
@israel-hdez this should be fixed in latest master, gonna close this one. Feel free to reopen if it still isn't fixed for you. Thx for reporting it!
