### ISSUE TITLE
Form label not usable in React (available in Core)

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-react#3177]
The form label is not available as a component in React. This label would be useful for showing read-only content etc.

**Comment by katierik** [comment]
cc @jdostal

**Comment by tlabaj** [comment]
Hi Katie can you supply a link to the corresponding Core component please.
I see that Core has a Label embedded in the Form component like React does.  Are you referring to something different?

**Comment by katierik** [comment]
As far as I can tell, and what I got from asking on PF slack, is that this is how to get the label style:
"label class=“pf-c-form__label”"
from here: https://www.patternfly.org/v4/documentation/core/components/form

I passed this on to the developers I worked with and this is not available in React. On the slack convo I was told there wasn't an equivalent in React.
The ask is to allow this to be used in React without needing to create a custom component.

**Comment by tlabaj** [comment]
@katierik are you saying you want to use the label outside of the FormGroup?  Right now in React and in Core the Label is always part of the FormGroup.

this is from core 
`.pf-c-form__group | <div> | Wraps form fields <label> + <field> + .form-helper-text.`

cc @mcoker

**Comment by jiridostal** [comment]
The thing here is that in our mocks the "pf-c-form__label" is used as a label for small headings. It means it's outside of FormGroup. The request here is to create that "label" as separate component (maybe style in Styled System etc.)

**Comment by mcoker** [comment]
@jiridostal @katierik can you include the mockup or a screenshot with the label you're referring to in your design?

**Comment by katierik** [comment]
![Xnip2019-10-24_10-44-50](https://user-images.githubusercontent.com/23172038/67497010-51640400-f64b-11e9-9acd-b8fc0a86092b.jpg)
Here is an example of needing the label style to display read-only data.

**Comment by rachael-phillips** [comment]
@mcoker there's Katies's mock-up above ^^

**Comment by mcoker** [comment]
\+ @mcarrano

@katierik is using the form component's form label styles outside of the context of a form to associate a small, bold label/title above regular text. We do not currently offer a flexible component that uses the small font size (`--pf-global--FontSize--sm`) with bold text that would be suitable for the use case in the screenshot.

One idea could be to support a "small" variation of the title component for uses like this. That might look something like this:

<img width="687" alt="Screen Shot 2019-10-28 at 3 55 48 PM" src="https://user-images.githubusercontent.com/35148959/67718219-4c7db800-f99d-11e9-9399-933262bc3f6a.png">

What do you think of that @mcarrano? Or do you have any other ideas in mind?

@jiridostal we no longer formally support the [Styled System](https://github.com/patternfly/patternfly-react/tree/master/packages/patternfly-4/react-styled-system), though I'm sure you could use that to create these styles. FWIW, I created a codepen with the styles you would want to apply - https://codepen.io/mcoker/pen/QWWMaja

From the codepen, the styles from our variable system that you would want to use would be:

```
  font-weight: var(--pf-global--FontWeight--bold);
  font-size: var(--pf-global--FontSize--sm);
  line-height: var(--pf-global--LineHeight--sm);
  padding-bottom: var(--pf-global--spacer--sm);
```

**Comment by mcarrano** [comment]
@mcoker It's possible that a small variation of the Title component would work here. There is also this Definition List issue that has been in our backlog for a long time: https://github.com/patternfly/patternfly-next/issues/1919  I feel like this is an instance of the same pattern. We definitely should have an approach to addressing this outside of a form.

@LHinson is this something we should get on our roadmap? I can open a core issue if that makes sense.

**Comment by LHinson** [comment]
@mcarrano yeah, given our move over to pf-design, I assume the issue would start there @mcarrano 

+1 for getting it on the roadmap. @katierik mind updating the management and automation spreadsheet with PF requests?  That will help clarify priority.

**Comment by mcarrano** [comment]
@mcoker do you feel like if we implement #1919 it will address this use case? If so, the design work is done.

**Comment by mcoker** [comment]
@mcarrano yes it looks like the definition list would work great for this.
