### ISSUE TITLE
PF3 Slider: No property available to control the value of the dropdown list

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3179]
When using the Slide component from another React Component, we need to have some way to get updated about the changes in the values of the Slider.

For the input range in self, onSlide is the property which does that.

Then for the input text element I figured out that onChange works, although it's no documented.

However for the dropdown list there is not property that we can pass to the Slider component so that we can get state updates on the dropdown.

Without having that, the dropdown component part is basically unusable.

I am not sure if we want to spend time fixing that, or work on the PF4 Slider implementation.

**Comment by KKoukiou** [comment]
Still calid. @tlabaj please reopen

**Comment by jschuler** [comment]
@KKoukiou the `onSlide` handler returns the value both for when the slider is changed as well as when the text input changes. For the formatter dropdown, I've added a new handler `onFormatChange` here: https://github.com/patternfly/patternfly-react/pull/3477
