### ISSUE TITLE
Docs: update PaginationToolbar demo to include spinner and error handling

### ISSUE THREAD

**Issue by boaz0** [patternfly/patternfly-react#3184]
Add to the pagination toolbar demo spinner instead of just displaying the "Loading" text.
In addition, add error handling to display an error state if there is no data fetched.

**Comment by rachael-phillips** [comment]
@mcarrano do you have any thoughts on this from a design perspective?

**Comment by mcarrano** [comment]
@boaz0 can you point to the specific page you want to update? I'm not seeing a demo called PaginationToolbar.

**Comment by boaz0** [comment]
@mcarrano https://patternfly-react.surge.sh/patternfly-4/documentation/react/demos/paginationtable

**Comment by mcarrano** [comment]
OK. Thanks @boaz0 

To answer the question @rachael-phillips , yes, I think that these elements should be included in the demo. There are Core demos for these states but they apparently never made it over to React.
