### ISSUE TITLE
PF3 Slider: onSlide does not strictly respect the minimum value

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3187]
When using the `onSlide` callback to get the current value of the Slider, we expect that the returned values will always be within the [min, max] range.
Let's say that min = 0, moving the slider to the left, will return as last value -1, although the slider will stick to 0.
There is clearly some min value check in the implementation that needs to be adjusted.

**Comment by tlabaj** [comment]
Can you please provide more context.  The onSlide callback is intended be provided by the consumer.  If the consumer does not provide it, it defaults to a noop.

**Comment by KKoukiou** [comment]
@tlabaj right, that was not clear from my side.

Let's say that onSlide is the following function provided by the user:
```
onSlide = value => console.info(value)
```
Which basically prints out the current value of the slider.
When you move the slider to the left, the last value that this function will print is the min - 1. Although it should print min as the last value.

This can lead to troubles, since we use onSlide to get the Value of the slider, consume it and pass it to the backend. But getting min -1 is already invalid value (outside of the boundaries).

**Comment by KKoukiou** [comment]
Still valid.

**Comment by rebeccaalpert** [comment]
Hi Katerina - I'm taking at look at this issue.

I haven't been able to recreate this on the PatternFly 3 storybook using the same function noted in the issue:
```
onSlide = value => console.info(value)
```

I'm just seeing the expected value logged when the slider is dragged to the left (0). Would you be able to share more details on your usage of the component so I can better track this down?

**Comment by KKoukiou** [comment]
> Hi Katerina - I'm taking at look at this issue.
> 
> I haven't been able to recreate this on the PatternFly 3 storybook using the same function noted in the issue:
> 
> ```
> onSlide = value => console.info(value)
> ```
> 
> I'm just seeing the expected value logged when the slider is dragged to the left (0). Would you be able to share more details on your usage of the component so I can better track this down?

Right - when dragged it works as expected. When using the keyboard though to move the slider to the left the above issue occurs. So try to use keyboard instead of mouse to reproduce this.

**Comment by rebeccaalpert** [comment]
@KKoukiou - Thanks for the follow-up. I see the issue now. I'll take a look this week and see what we can do to fix it.
