### ISSUE TITLE
PF4 Table: Hide TableBody props not passed by consumer from documentation

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#3190]
Split out from issue #3018 

Some props currently showing in the TableBody definition are calculated (and not typically passed by a consumer). We should hide those props from the documentation:

<img width="969" alt="Screen Shot 2019-09-26 at 12 53 32 PM" src="https://user-images.githubusercontent.com/4237045/65708523-c4825680-e05c-11e9-8f2b-406326ed0365.png">

**Comment by dlabrecq** [comment]
As a consumer, I prefer to see all available props. I need this information (e.g., specifically `children`) in order to customize components. Hiding props or leaving them undocumented makes customizing more difficult.

With Victory charts, they don't hide the `children` property. Instead, they add a warning about its use. For example:

> The `children` prop specifies the child or children that will be rendered within the container. This prop should not be set manually. It will be set by whatever Victory component is rendering the container.

Note that we have carried this approach over to the React charts. We wrap many components (e.g., VictoryPie), which need to use the `children` prop (e.g., donut threshold chart).

See https://formidable.com/open-source/victory/docs/common-container-props/

**Comment by ddonahue007** [comment]
I agree with dlabrecq, on the points he made here.  

I also want to highlight what I think is a bigger problem, which that at least half of the properties on the Table  have no descriptions at all. Table Body has none if its properties documented. TableHeader is in that same boat with no descriptions at all.  This could be done through the gatsby plugin configuration or even the propsTable.js file.

I believe that if we decide we have the need to hide properties form the documentation side of things we could do so in more than one way for sure. It could be done very easily by only publishing any propery that has a description. We could also use annotations on a property by property basis(this is more flexible but the first iteration of this would be painful.

**Comment by redallen** [comment]
Depends on #2139 .

I think we need to have a broader API discussion for not only Table to decide how we might want to use annotations.

**Comment by evwilkin** [comment]
@dlabrecq @ddonahue007 the infrastructure team has taken your advice not to hide props, but as this issue now pertains specifically to TableBody props would you like to take on updating the prop descriptions as you see fit, based on the needs in your comment above?

**Comment by ddonahue007** [comment]
Evan;

	I just had a conversation with Dan and I can take a look at this later on today. I think we can at the least update the descriptions to some of these to something like “not intended for consumer use”  I’ll check on what properties descriptions are missing and what properties should carry this description. 

	Cheers
	-Doug

**Comment by dlabrecq** [comment]
Not familiar with those TableBody props, but I'd like to follow Victory's example and add "This prop should not be set manually" to the description.

**Comment by evwilkin** [comment]
Thanks @ddonahue007 for taking a look, and @dlabrecq for the suggestion on the wording - that makes sense to me!
