### ISSUE TITLE
NavTertiaryList scroll bugs

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#3200]
In OpenShift console, we have tabbed navigation that can include more tabs than can be displayed at a given viewport.  `NavTertiaryList` seems like a good way for us to solve for this problem.  However, I've noticed a few bugs in attempting to implement `NavTertiaryList` in OpenShift console (see https://github.com/openshift/console/pull/3096). 

* In my OpenShift console prototype, the scroll buttons don't appear on initial load.  Resizing the viewport fixes the bug.  Initialization bug?
* Sometimes clicking the scroll buttons doesn't result in scrolling in the entire nav bar (stops short and remaining tabs are never revealed no matter how much clicking occurs). 
* Rapidly clicking the scroll button can result in the first or last tab being selected, which can be confusing (see below).  In my OpenShift console prototype, I accounted for this by not overlaying the scroll buttons on top of the tabs.
![rYKy0zMiSx](https://user-images.githubusercontent.com/895728/67515839-779a9b80-f66d-11e9-859f-a979f6d74ca9.gif)
* Scrolling the nav with the mouse pointer instead of the buttons does not show or hide the buttons when reaching the beginning or end of the scrollable area.
![RCGvmphUB1](https://user-images.githubusercontent.com/895728/67511303-96e0fb00-f664-11e9-901f-3aedd858519f.gif)
* Font weight increase for active item causes a "shimmy" of the nav items on select, and the last nav item can end up clipped. 
![nknYg1HqRK](https://user-images.githubusercontent.com/895728/67802911-6cc37a80-fa62-11e9-87f3-a3e5f63e4fe7.gif)

cc: @spadgett

**Comment by rhamilto** [comment]
cc: @janwright73

**Comment by nicolethoen** [comment]
> * Rapidly clicking the scroll button can result in the first or last tab being selected, which can be confusing (see below).  In my OpenShift console prototype, I accounted for this by not overlaying the scroll buttons on top of the tabs.
>   ![rYKy0zMiSx](https://user-images.githubusercontent.com/895728/67515839-779a9b80-f66d-11e9-859f-a979f6d74ca9.gif)

> * Font weight increase for active item causes a "shimmy" of the nav items on select, and the last nav item can end up clipped.
>   ![nknYg1HqRK](https://user-images.githubusercontent.com/895728/67802911-6cc37a80-fa62-11e9-87f3-a3e5f63e4fe7.gif)

@mcarrano @mcoker I believe both of these points are going to need to be design/core changes. I will open two issues in Core for these points.

**Comment by nicolethoen** [comment]
Still waiting on https://github.com/patternfly/patternfly-next/issues/2435

**Comment by mcoker** [comment]
@nicolethoen @tlabaj the core work for the disappearing scroll buttons is complete. This covers both horizontal (masthead) and tertiary (in page) navigation: https://github.com/patternfly/patternfly/pull/2942/

The `.pf-m-start` and `.pf-m-end` classes have been removed and the nav now supports `.pf-m-scrollable` which toggles the visibility of the scroll buttons. When scroll buttons are visible and there is no overflow content on a given end of the nav list, the button on that end is `disabled`. FYI - this behavior is basically the same as what will be introduced into the tabs component this sprint, too https://github.com/patternfly/patternfly-react/issues/3951
