### ISSUE TITLE
PF4 Button does not pass through tabIndex prop

### ISSUE THREAD

**Issue by petli-openshift** [patternfly/patternfly-react#3208]
Define a pf4 button with `tabIndex` prop,
```
import { Button } from '@patternfly/react-core';
......
<Button tabIndex="-1">test</Button>

```

The `tabIndex` prop is missing from the rendered DOM,
```
<button class="pf-c-button" type="button">test</button>
```

**Comment by boaz0** [comment]
@petli-openshift is there a reason you want to set tab index to -1 and still enable the button.
We set the tab index to -1 only when the button is disabled or the component is not a button.
