### ISSUE TITLE
Add keyboard interaction tests for options menu

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#3213]
Write integration tests to prevent keyboard interaction regressions. 
Use the [design documentation](https://docs.google.com/document/d/1m9nICFRgCXnXeHYN487BMX9MHw4DjvOln2B5p8yJa70/edit#heading=h.bg94bjykerss) to create the necessary cypress tests.

**Comment by nicolethoen** [comment]
This will be addressed once both
https://github.com/patternfly/patternfly-react/issues/6014 and https://github.com/patternfly/patternfly-react/issues/7594 are completed. I'm going to close this since it will have been covered
