### ISSUE TITLE
Dropdowns onSelect doesn't return useful event.

### ISSUE THREAD

**Issue by newswangerd** [patternfly/patternfly-react#3217]
I'm trying to create an input group based off of the documentation here: https://patternfly-react.surge.sh/patternfly-4/documentation/react/components/inputgroup

Specifically I want to build this one to use as a combo filter.
![Screen Shot 2019-10-25 at 3 58 39 PM](https://user-images.githubusercontent.com/6063371/67600541-55258280-f740-11e9-9fe6-5abee028fd6d.png)

According to the example, it looks like the text on the dropdown is supposed to change based on what I select, so if I click Option 1, the dropdown should say "Option 1"

```
          <DropdownToggle onToggle={this.onToggle}>
                {this.state.selected ? this.state.selected : 'Dropdown'}
          </DropdownToggle>
```
However, when I try to select an option from the dropdown on the example nothing changes.

Upon investigation, it looks like the root cause for this issue has to do with the event that gets passed to the `Dropdown` components `onSelect` function.

```
    this.onSelect = event => {
      this.setState({
        isOpen: false,
        selected: event.currentTarget.value
      });
    };
  }
```

In this case, it appears as though `event.currentTarget` is `<li id="" role="menuitem">`, which doesn't appear to have a `value` attribute.

Is there another way to get the selected item's value?

**Comment by rachael-phillips** [comment]
HI @newswangerd our team has seen this, and I'll get back to you soon with an update.

**Comment by tlabaj** [comment]
@newswangerd the Dropdown is intended to be an actions menu.  If you want to make a selection,  the select component would be better suited for your needs. That being said, The example in the inpyut group should be updated to use a select rather than a dropdown.
