### ISSUE TITLE
Empty State should be full width by default

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#3221]
When implementing the Empty State component in the MDC, I had to add a variant to make the empty state take up the width of its parent. To me this seemed like a bug, and by default, the empty state should take up 100% width of its parent.

**Comment by rachael-phillips** [comment]
Hey @christiemolloy I've seen this and will discuss with @tlabaj

**Comment by tlabaj** [comment]
Closed by #3933
