### ISSUE TITLE
react-integration compiler options masks type issues

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3223]
Currently, our react-integration pkg serves the purpose of ensuring our documentation examples will build and compile as expected. It works great, but I recently realized [strict type checking is turned off](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-integration/demo-app-ts/tsconfig.json#L20-L21). Because of this, issues go undetected until they are happened upon by community members. Setting `strict` to `true` is standard practice and it doesn't make sense to suggest consumers lessen their compiler strictness just to be able to consume our components.

I've increased the strictness of the checks we can without making further changes in https://github.com/patternfly/patternfly-react/pull/3222.

This leaves us needing to work through changes required to enable the following compiler options:

- [ ] strictPropertyInitialization
- [x] [noImplicitAny](https://github.com/patternfly/patternfly-react/issues/3231)
- [ ] [strictNullChecks](https://github.com/patternfly/patternfly-react/issues/3230)
- [x] [strictFunctionTypes](https://github.com/patternfly/patternfly-react/issues/3224)

**Comment by seanforyou23** [comment]
This is a critical issue, commenting so stale bot doesn't close it.

**Comment by dgutride** [comment]
@seanforyou23  - since the strict changes were made in https://github.com/patternfly/patternfly-react/pull/3222 is there some work this issue is still left open to capture?

**Comment by seanforyou23** [comment]
Hi @dgutride - yes we still have [several strict modes ](https://github.com/patternfly/patternfly-react/pull/3222/files#diff-2b96ca5fa7e86654dc36bfcf59237f20R24-R27)left turned off. I was kinda thinking of this issue as an epic and linked out to them from this one so it's easier to follow this work as a sort of "theme" since it requires breaking changes. Does this help or answer your question? Let me know if I should change anything about how they are captured.

**Comment by dgutride** [comment]
that makes sense - so we still need to enable them one by one and fix as we go - thx for the clarification!
