### ISSUE TITLE
Some component demos don't meet "strictFunctionTypes" requirements

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3224]
I noticed that when a consuming typescript app uses the `strictFunctionTypes` compiler option, following certain component examples causes errors to be thrown. Below is an example of what the error looks like, a typical type mismatch from what I can tell..

<img width="1189" alt="Screen Shot 2019-10-28 at 3 00 24 PM" src="https://user-images.githubusercontent.com/5942899/67710375-33bdd400-f996-11e9-9cc3-b9b91b96ad75.png">

These are the component demos in the react-integration package I see that are affected.

- [x] ContextSelectorDemo/ContextSelectorDemo.tsx
- [x] SelectDemo/SelectDemo.tsx
- [x] TableDemo/TableActionsDemo.tsx
- [x] TableDemo/TableCompactExpandableDemo.tsx
- [x] TableDemo/TableSortableForCompoundExpandableDemo.tsx
- [x] TabsDemo/TabsDemo.tsx
- [x] TabsDemo/TabsStringEventKeyDemo.tsx

**Comment by seanforyou23** [comment]
This is a critical issue, commenting so stale bot doesn't close it.

**Comment by seanforyou23** [comment]
Ping to keep this issue active

**Comment by evwilkin** [comment]
Resolved in #4019
