### ISSUE TITLE
Application launcher enhancements

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#3227]
This is a React implementation follow-up to Core issue https://github.com/patternfly/patternfly-next/issues/2365. This React issue is on hold until https://github.com/patternfly/patternfly-next/issues/2365 has been closed.

**Comment by mcoker** [comment]
https://github.com/patternfly/patternfly-next/pull/2428 is merged

* Creates a new element `.pf-c-app-launcher__menu-search` to hold the text input form control for searching the menu.
* Creates a new element `.pf-c-app-launcher__menu-wrapper` to be used as the list item that will wrap the item link and button inside when used with a favorites menu. Technically this could be used outside of the context of favorites in the future if we wanted to have more actions beside a link in an app launcher that do other things. This is just a way to establish a list item that will then take a link and action(s).
  * This gets the class `.pf-m-favorite` when an item in the list has been favorited.
* Creates a variation for `.pf-c-app-launcher__menu-item` called `.pf-m-link` that serves as the link inside `.pf-c-app-launcher__menu-wrapper`
* Creates a variation for `.pf-c-app-launcher__menu-item` called `.pf-m-action` that serves as an action inside `.pf-c-app-launcher__menu-wrapper`. Technically this could be anything, not just a favorite button. And I suppose you could have more than 1.
