### ISSUE TITLE
Hover for list view 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#3233]
Hover for list view as a follow up to https://github.com/patternfly/patternfly-next/issues/2370

**Comment by rachael-phillips** [comment]
The only functionality you’ll need from core is the ability to designate a data list as selectable or not (a prop that applies a CSS modifier class), which is what will differentiate the row hover and expanded left blue border color differences from non-selectable data lists.
Then when you select a row in a selectable data list, that applies a CSS modifier class to the row

**Comment by mcoker** [comment]
This is ready to be worked on. From https://github.com/patternfly/patternfly-next/pull/2491

* Selectable rows get the class `.pf-m-selectable` and attribute `tabindex="0"`
* Selected rows get the class `.pf-m-selected`

@jessiehuff how do you think we should announce that a row is selected? Each row (`.pf-c-data-list__item`) is `aria-labelledby` the `id` of the primary cell in the row. Could we incorporate "selected" text in that label somehow, or maybe use `aria-selected`?
