### ISSUE TITLE
PF4 Table: Sort controls look enabled despite being disabled

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3234]
When there is no table data available (e.g., due to an applied filter), the select-all checkbox and sort functionality is disabled as expected. However, the sort controls still look as if they're enabled -- see the "Cost" header below.

![Screen Shot 2019-10-29 at 9 40 23 AM](https://user-images.githubusercontent.com/17481322/67772705-e8a4cf00-fa30-11e9-9761-8cc756e651c6.png)

Ideally, there should be some styling applied to the sort controls so they don't appear to be clickable?

Please see the original issue here for details https://github.com/patternfly/patternfly-react/issues/1431

**Comment by tlabaj** [comment]
cc @mcoker Do we need an issue in core to add a modifier for this?

**Comment by mcoker** [comment]
@mcarrano wdyt, should we open an issue for design to investigate a disabled state for the sortable column headers?

Another option could be to remove the selected state from sortable headers if the table is empty so that all of the headers would look like the "Project names" header.

**Comment by mcarrano** [comment]
Good question @mcoker . So is the empty state actually inside of the table or should it replace the table? Why would we show a header row at all if the table is empty?

**Comment by mcoker** [comment]
@mcarrano it was in the original design from https://github.com/patternfly/patternfly-next/issues/2171 - https://marvelapp.com/cd929d4/screen/61020716

**Comment by mcarrano** [comment]
Fair enough, @mcoker What do you think the easiest fix is here? I agree that it seems odd for the column headers to be clickable. Any ideas @mceledonia ?

**Comment by rachael-phillips** [comment]
@mcoker and @mceledonia what are your thoughts here?

**Comment by mcoker** [comment]
@mcarrano @mceledonia I'm thinking w could add a disabled state to the sortable column header buttons. A few ideas:

1. Indicate the buttons are disabled by adding a variation that disables the click events and assigns a disabled state color (grey).
1. Add a disabled variation that disables the click events and removes the blue active/sorted color so that all of the column headers would be black.
1. #2, but the disabled state would also remove the arrows.

**Comment by mcarrano** [comment]
I am fine with adding a disabled state to the column headers as @mcoker suggests. Should this issue be transferred/opened in Core for further follow-up @rachael-phillips ?
