### ISSUE TITLE
PF4 Wizard throws warning about 'appendTo' prop

### ISSUE THREAD

**Issue by keithjgrant** [patternfly/patternfly-react#3237]
The PF4 Wizard component passes a subset of props to a `<div>` child, including the prop `appendTo`. This results in a warning in the console:

![Screen Shot 2019-10-29 at 10 35 39 AM](https://user-images.githubusercontent.com/410794/67794051-3de4de80-fa39-11e9-985a-523996404060.png)

This prop should probably be omitted from `rest` at https://github.com/patternfly/patternfly-react/blob/ec9d5ddbd353b6dea6b3299ab2f22128db0396dc/packages/patternfly-4/react-core/src/components/Wizard/Wizard.tsx#L367

This occurs in @patternfly/react-core v3.120.2

**Comment by boaz0** [comment]
thank you for noticing
