### ISSUE TITLE
Flex component TypeScript error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3248]
Attempting to use this simple Flex component example

```
<Flex className="example-border">
  <FlexItem breakpointMods={[{modifier: "align-right"}]}>Flex item</FlexItem>
  <FlexItem>Flex item</FlexItem>
</Flex>
```

And encountered the TypeScript error below:

![Screen Shot 2019-10-30 at 5 45 45 PM](https://user-images.githubusercontent.com/17481322/67901508-5b02d580-fb3d-11e9-8487-7b645bacc38c.png)

Also tried importing FlexBreakpointMod, but it is not exported properly.

![Screen Shot 2019-10-30 at 5 45 15 PM](https://user-images.githubusercontent.com/17481322/67901548-7241c300-fb3d-11e9-8a5b-eff74e5dfe8f.png)

**Comment by sahil143** [comment]
Related to this https://github.com/patternfly/patternfly-react/issues/3244
