### ISSUE TITLE
PF4: BackgroundImage produces console error

### ISSUE THREAD

**Issue by keithjgrant** [patternfly/patternfly-react#3250]
The BackgroundImage component generates a console error due to the empty `width` attribute on a `<filter>`. Probably caused by https://github.com/patternfly/patternfly-react/pull/2742

Chrome:
![Screen Shot 2019-10-31 at 11 19 10 AM](https://user-images.githubusercontent.com/410794/67975076-b6ca6e80-fbd0-11e9-8153-1848b93ff0b1.png)

Firefox:
![Screen Shot 2019-10-31 at 11 19 19 AM](https://user-images.githubusercontent.com/410794/67975091-bcc04f80-fbd0-11e9-9106-51c3ff4e8885.png)

This is in react-core v3.120.2. Seems like a regression of https://github.com/patternfly/patternfly-react/issues/2100

**Comment by nicolethoen** [comment]
Just in case I am not in Monday - here are my thoughts so far:

I wonder if a valid solution would be to remove the width=“” property all together from the <filter> tag in the background image component. 
I don’t see a difference and it makes the errors go away. 

Also the example here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter does not have a width in the filter tag. I’m not sure what the intent is for having it there.

**Comment by nicolethoen** [comment]
I do see in the documentation here: https://www.w3.org/TR/SVG11/filters.html#FilterEffectsRegion

"Negative values for ‘width’ or ‘height’ are an error (see Error processing). Zero values disable rendering of the element which referenced the filter."

so I imagine that is why it was there with a "0" value originally?

**Comment by seanforyou23** [comment]
@keithjgrant I took a stab at fixing this in https://github.com/patternfly/patternfly-react/pull/3758, would you mind test driving that PR to see if the error is gone? Thx!

**Comment by keithjgrant** [comment]
@seanforyou23 looks like that fixes it for us. thanks!
