### ISSUE TITLE
[PF4] Problems with PopOver in VirtualList 

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#3259]
Hi 

When we use the PopOver in a VirtualList and scrolling the upper line of the row matches with the bottom line of table header the masthead disappears when we change the page. (See Gif)

![Peek 2019-10-22 16-24](https://user-images.githubusercontent.com/23639005/67334895-80159980-f4e8-11e9-9040-b55a188dd708.gif)

If we use a tooltip instead Popover works correctly so it seems that  there is something broken with the styles here.

issue https://github.com/kiali/kiali/issues/1834
PR test : https://github.com/kiali/kiali-ui/pull/1521

cc @abonas @serenamarie125 @LHinson

**Comment by rachael-phillips** [comment]
Hi @aljesusg I've seen this, and I will be discussing this with the team tomorrow.

**Comment by jshaughn** [comment]
I have seen this in other situations as well but it always seems to involve a Popover.  By the way, yesterday I saw something unexpected, a crash in PopoverBase.js (see [this line](https://github.com/patternfly/patternfly-react/blob/c9e87a6223b91b0944fb386b2954262705dad16b/packages/patternfly-4/react-core/src/helpers/PopoverBase/PopoverBase.js#L101)).

this.tip was undefined.

It would indicate that componentWillUnmount can occur before componentDidMount completes, which seems strange, but adding null protection here may be valuable.
