### ISSUE TITLE
PF4 Table: When using onRowClick property a class should be automatically attached  the table to indicate the rows are clickable

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3267]
Right now we need to manually implement that by adding a custom class to tables that have clickable rows.
However I consider it as important that all products using PF, will have a similar behavior regarding how clickable rows look like.

**Comment by rachael-phillips** [comment]
Hi @KKoukiou thank you for opening this. Our team has seen this, and we have someone who can take a look at this next week.

**Comment by rachael-phillips** [comment]
Hi @mcoker do you know if this class exists in Core?

**Comment by mcoker** [comment]
@rachael-phillips we haven't added any specific styling for use with the `onRowClick` prop. It seems like this would overlap with our data-list/table hoverable/selectable designs, applying the same hover styles in that design to table rows that use this prop.

That also implies that we should designate hover styles as able to apply to individual rows, rather than designating an entire table/data-list as hoverable, where all of the rows would receive hover styles. This is something @mcarrano and I were discussing recently.

**Comment by KKoukiou** [comment]
I don't think issue was solved/decided upon.
@tlabaj can you please reopen it.

**Comment by mcoker** [comment]
@mcarrano there is a feature available in the react table that allows a row to be clickable, but there is no design support/associated styling for that currently. Looking ahead, we have an issue for adding the [selectable row variant](https://github.com/patternfly/patternfly-next/issues/2371) to the table component that would give "selectable" styles similar to the [selectable data-list rows](https://www.patternfly.org/v4/documentation/core/components/datalist#selectable-expandable-rows), where hovering over a selectable row changes the mouse cursor and applies a box shadow.

Would you expect to be able to re-use the selectable hover/cursor/shadow styles we'll add as https://github.com/patternfly/patternfly-next/issues/2371 to indicate a row is clickable (though not necessarily selectable), or should we have a specific design for clickable rows that is separate from the selectable design?

**Comment by mcarrano** [comment]
To me they feel like the same thing @mcoker . Anyone see a reason why they are different? Basically by "selectable" I meant that they take a click event and will display a selected state.

**Comment by mcoker** [comment]
They seem the same to me, too, as the selectable design just indicates that the row is interactive, and clicking on it will do something.

> Basically by "selectable" I meant that they take a click event and will display a selected state.

I guess the difference is here that the `onRowClick` property may only trigger a click event on the row, and will not necessarily display a selected state. The click event may do something else entirely, like link to another page, trigger a modal, etc. Not sure if we would (now or in the future) want to be able to differentiate between a row being clickable and selectable when you hover/focus on a row.

**Comment by mcarrano** [comment]
IMO this is not really different from how we handle events on buttons. The button has a down/selected state, but if the action takes you off to another page you will probably never see it. Does that make sense @mcoker ?

**Comment by KKoukiou** [comment]
@mcoker could you please reopen this? I was in the position of implementing a table with rows that have onClick signal handler (redirect to another page) and realized that still there is stil not CSS indicating that something will happen when clicking on the row.

**Comment by KKoukiou** [comment]
Still relevant. DataList component has pf-m-selectable, we could reuse that one.

**Comment by mcarrano** [comment]
@KKoukiou we do have this issue currently on the roadmap that seems like it addresses this: https://github.com/patternfly/patternfly/issues/2371 Do you agree? If so, I'd like to close this as a duplicate.

**Comment by KKoukiou** [comment]
> @KKoukiou we do have this issue currently on the roadmap that seems like it addresses this: [patternfly/patternfly#2371](https://github.com/patternfly/patternfly/issues/2371) Do you agree? If so, I'd like to close this as a duplicate.

Indeed thanks
