### ISSUE TITLE
Pagination doesn't look right in GNOME Web (epiphany, webkit)

### ISSUE THREAD

**Issue by elad661** [patternfly/patternfly-react#3277]
See attached screenshot. This is using `epiphany-3.32.5-1.fc30.x86_64` which uses webkit `605.1.15`, which is roughly equivalent to Safari 11

![Screenshot from 2019-11-07 14-22-01](https://user-images.githubusercontent.com/498903/68388868-48eeeb80-016a-11ea-8197-9bbb72da209a.png)

**Comment by rachael-phillips** [comment]
@redallen is this a website issue? If so, I'll transfer it over to Org.

**Comment by redallen** [comment]
I don't think this is a website issue. I think it's a Pagination issue that belongs in patternfly-next.

**Comment by rachael-phillips** [comment]
@mcoker making you aware of this issue. What do you think?

**Comment by mcoker** [comment]
@rachael-phillips sorry for the delay, I think we will need a testing environment to verify where the problem is exactly, though like @redallen said, it's likely an issue with the CSS compatibility in that browser and not with the website.

**Comment by tlabaj** [comment]
@elad661 GNOME Web is not a browser we support.  Are you able to reproduce the issue in other browser so we can debug it?
