### ISSUE TITLE
Link Button

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#3283]
I'm using the Link button with an icon in a Patternfly-org page. I want the icon to sit after the text like below, however the default is for the icon to sit before the link. Could we explore the option of having another variant that lets you determine where the icon sits whether its before or after the icon.
I can use a regular link button and then drop in the icon, however I don't get the correct spacing as seen below:

<img width="162" alt="Screen Shot 2019-11-07 at 11 27 20 AM" src="https://user-images.githubusercontent.com/20118816/68407458-9a3eb100-0151-11ea-812a-c3d47cd79f2a.png">

**Comment by rachael-phillips** [comment]
In Core right now you can position the icon to the left or right of the text by just moving the containers around. But in React you can’t it only is positioned to the left of the text

**Comment by tlabaj** [comment]
Putting this on hold until Core issue [#2507](https://github.com/patternfly/patternfly-next/issues/2507) is resolved

**Comment by christiemolloy** [comment]
@tlabaj the core issue is now resolved so work on this can begin again!
