### ISSUE TITLE
Tooltip triggers exit when changing content prop

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#3310]
**Describe the issue. What is the expected and unexpected behavior?**
When tooltip has its `content` prop changed, e.g. from "foo" to "bar", it will count as if your mouse has left the tooltip-root and close after waiting the `exitDelay` duration

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See:
https://codesandbox.io/s/infallible-euler-17580

1. Hover over button
1. Click button
1. Expect tooltip to remain

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. Non-blocking, no work-around

**What is your product and what release version are you targeting?** 
N/A

**Comment by rachael-phillips** [comment]
Hi @SpyTec our team has seen this, and I'll get back to you sometime this week with about this issue.

**Comment by rachael-phillips** [comment]
Hi @SpyTec we looked into this from the Ux and usability perspective, and our team would not recommend the proposed solution as a design best practice, so we would like to close this issue. Thank you for bringing this to us!

**Comment by SpyTec** [comment]
Hi @rachael-phillips, I'm copying [Clipboard Copy](This is editable) which is using a tooltip with changing tooltip content on user interaction.

Until there is a clipboard copy variant that is extensible I have no choice but to deploy my own variant of the clipboard copy button.

What else would you suggest for an implementation of a clipboard copy?

**Comment by rachael-phillips** [comment]
Thanks for the info @SpyTec. @mcarrano do you mind taking a look at this from the design perspective?

**Comment by mcarrano** [comment]
@SpyTec Can you say more about your requirements for Clipboard copy that the current PatternFly component does not satisfy?

**Comment by SpyTec** [comment]
@mcarrano right now we have a copy configuration view to clipboard, which will add to the clipboard based off of the current configuration from a store.

Since it's dynamic and based off of data across the page I didn't want to continually update the input field for Clipboard Copy as it's mostly a waste of resources. Instead having it reactively generate it with a button click was the way to go for us

It looks like this right now. I can send our internal RH URL if you want to take a closer look
![image](https://user-images.githubusercontent.com/6598829/69325867-23261400-0c4b-11ea-856f-d27b7d94aa97.png)

**Comment by mcarrano** [comment]
@SpyTec so is it the case then that clicking the button will both generate the content and copy it to the clipboard and you are using the tooltip to report the result? Yes, looking at a demo might be helpful.
