### ISSUE TITLE
Spike: Investigate breaking type changes

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#3321]
Introducing types at all is technically a breaking change for Typescript consumers. Yet, I don't think Typescript consumers were too upset with us when we introduced types for component properties because that gave them a compile-time check for their props.

But now comes Phase 2: supporting and modifying these types where we were previously incorrect or previously used `any`. How we should introduce this to consumers without breaking their compile-time check for their props? It's not good for our types to stay incorrect. It's also not good to break Typescript consumers from one minor version to the next.

I think something that will ease or pain is an official types package and looking at how other libraries manage their types between releases. I'm sure it can quickly get complicated, so I think it deserves an investigation.

Related: #3296

**Comment by seanforyou23** [comment]
Can we consider [all of the known type issues](https://github.com/patternfly/patternfly-react/issues/3223) in react-integration while putting together a strategy for what we're investigating how to address? This should hopefully give us a better idea of how to size up the effort.

Individual breaking releases for the individual issues will quickly raise the pkg version numbers which likely isn't what we want, so we probably want to group them in some way. Similarly, lumping _all_ the fixes in a single giant breaking change "types" release could be overly disruptive for consumers.

Here's a path to consider - we could shoot for 4 "milestone" releases that correspond to the strict modes we're currently out of alignment with. So for example, we could have one breaking change release where we fix all of the `noImplicitAny` errors. A future release could resolve `strictNullChecks`, etc. By giving the breaking releases a theme, it feels less like chaos and hopefully signals to the community that we're continuing our support for TypeScript, which was a key strategic initiative for our team.

WDYT?
