### ISSUE TITLE
Split button dropdown check shouldn't use <Checkbox> component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3325]
**Describe the issue. What is the expected and unexpected behavior?**

There is too much space to the right of the checkboxes in the split button dropdown.

<img width="255" alt="Screen Shot 2019-11-19 at 4 17 06 PM" src="https://user-images.githubusercontent.com/35148959/69191460-22c13800-0ae8-11ea-94ba-731383067f0c.png">

 The `<Checkbox>` component is designed to work with a check + label pairing. The checkbox here should just use a normal `<input type="checkbox">`. Reference the [core split button dropdown component](https://www.patternfly.org/v4/documentation/core/components/dropdown#split-button) for an example.

**Comment by tlabaj** [comment]
Closed by #3391
