### ISSUE TITLE
Alert component enhancements - optional icon and other features

### ISSUE THREAD

**Issue by AllenBW** [patternfly/patternfly-react#3326]
It would be super awesome, n valuable to ife if the [Inline alert variants ](https://patternfly-react.surge.sh/patternfly-4/documentation/react/components/alert#inline-types) supported custom icons (or no icon).  

Attached is a ss where we would like to use this future component (n currently use a card with a border instead)
<img width="1025" alt="Screen Shot 2019-11-20 at 11 10 22 AM" src="https://user-images.githubusercontent.com/6640236/69255785-6b2f3300-0b86-11ea-9fd7-42bdfc23b089.png">

This is an enhancement we would like to see in react-core.

**Comment by janwright73** [comment]
@LHinson - this one was discussed in the Cloud services Platform sync today.

**Comment by tlabaj** [comment]
@mcarrano making you aware.

**Comment by mcarrano** [comment]
I've asked @kendramar and @katierik to take a look at this and make a design recommendation.

**Comment by katierik** [comment]
Reevaluated the design and no longer need this. Ok to close!

**Comment by katierik** [comment]
Additional info: This is a "conditionally shown information that the user cares about but isn't instructions or a warning" - Here is the updated design using a card: https://marvelapp.com/i4441ie/screen/62092193

@mcarrano suggested @mceledonia take a look and see if he had any suggestions as well

**Comment by rachael-phillips** [comment]
@mcarrano would you like me to move forward with closing this issue?

**Comment by mcarrano** [comment]
Yes, I think we can close.
