### ISSUE TITLE
Add empty state and loading state Table demos to React

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#3330]
Core includes empty state and loading state table demos: https://www.patternfly.org/v4/documentation/core/demos/table

Users would appreciate demos for how to implement these designs in React

**Comment by mcarrano** [comment]
I agree that it would be useful to have these demos in React. They will help developers more consistently utilize tables in context. @LHinson @rachael-phillips is this something we can get on the roadmap?
