### ISSUE TITLE
Breadcrumbs capitalization - sentence case

### ISSUE THREAD

**Issue by MariSvirik** [patternfly/patternfly-react#3353]
**INCORRECT**
![Screenshot 2019-11-26 at 14 18 43](https://user-images.githubusercontent.com/51960547/69637146-6112a600-1058-11ea-8b8f-91aa0cca2d73.png)

In the documentation for [Page layout](https://www.patternfly.org/v4/documentation/react/demos/pagelayout) and [components](https://www.patternfly.org/v4/documentation/react/components/breadcrumb), there is an incorrectly displayed capitalization of breadcrumbs. **We don't use headline style (PF3) anymore.** 

Breadcrumbs should match the name of the object (including capitalization). Capitalization in the example should use  **sentence case** and look like this:

**CORRECT**
![Screenshot** 2019-11-26 at 14 27 **18](https://user-images.githubusercontent.com/51960547/69638049-388bab80-105a-11ea-8f41-fa68e6bbc51e.png)

-------
**INCORRECT**
![Screenshot 2019-11-26 at 14 34 13](https://user-images.githubusercontent.com/51960547/69638162-77b9fc80-105a-11ea-9313-9bbaf7b449f5.png)

**CORRECT**:  All the underlined objects should be in sentence case.

**[Guidelines for capitalizations:](https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology#sentence-style)** 
Sentence style
Use sentence-style capitalization for all text elements, except:
Product names and proper nouns
Sentence style capitalizes only the first word of each sentence and proper nouns, like names.

**Comment by karelhala** [comment]
ping @nlcwong

**Comment by rachael-phillips** [comment]
@MariSvirik we've placed this in the backlog to resolve in the future. Great catch!
