### ISSUE TITLE
2Xl breakpoint modifiers not being correctly applied in https://www.patternfly.org/v4/documentation/react/components/table#breakpoint-modifiers

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#3355]
**Describe the issue. What is the expected and unexpected behavior?**

Per the associated JSX, the `Repositories` column should be visible at 2Xl viewport sizes, but is not.  Inspecting the markup shows the 2xl modifier classes are not be added.

![Screen Shot 2019-11-26 at 1 32 04 PM](https://user-images.githubusercontent.com/895728/69661880-340ec500-1051-11ea-96f3-1a35a7f81393.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug.

**What is your product and what release version are you targeting?**

OpenShift v4.4.

cc: @spadgett, @janwright73, @mcoker

**Comment by boaz0** [comment]
It looks like hiddenOn2Xl and visibileOn2Xl should be hiddenOn_2xl and visibileOn_2xl respectively.

This is due to the way react-styles parsed the modifiers name from a css file ([here](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-styles/src/utils.js#L31))
