### ISSUE TITLE
react-hot-loader infinite loop

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3358]
I noticed that when making an update to a markdown file while running the react workspace locally, it sends react-hot-loader into an infinite loop. Not sure if it's `react-live` or `react-hot-loader` but seems to be between one of the two.

![2019-11-27 10 27 34](https://user-images.githubusercontent.com/5942899/69740211-097f4380-1107-11ea-8c64-07ed4423d8fd.gif)

**Comment by rachael-phillips** [comment]
@evwilkin making you aware of this issue :)

**Comment by redallen** [comment]
Solved by #3386
