### ISSUE TITLE
Type mismatch in RowWrapper

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3367]
I've noticed this type error, spent a bit of time trying to fix it but no luck so far. Using visual studio code, it flags this in standard fashion.

<img width="1190" alt="Screen Shot 2019-12-02 at 8 18 38 PM" src="https://user-images.githubusercontent.com/5942899/70012162-9bd97a00-1541-11ea-8a17-0fb24a712da0.png">

When I remove the [ouia context](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-table/src/components/Table/RowWrapper.tsx#L106-L109) bits the error goes away. It's not affecting anything directly, but I'm looking to extend the row wrapper code for inline edit and want to make sure the testing related types are correctly attached so the new features can be tested.

**Comment by boaz0** [comment]
I fixed it by replacing:
```
class RowWrapper extends React.Component<RowWrapperProps & InjectedOuiaProps, {}> {
```
To

```
class RowWrapper extends React.Component<RowWrapperProps, {}> {
```

and changing `RowWrapperProps` to

```
export interface RowWrapperProps extends InjectedOuiaProps {
```

**Comment by seanforyou23** [comment]
Thx @boaz0 - I'll give this a try and tag you for review

**Comment by boaz0** [comment]
would love that.
