### ISSUE TITLE
Popover text cannot be selected

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#3368]
**Steps to reproduce**

1. Go to https://patternfly-react.surge.sh/patternfly-4/documentation/react/components/popover
2. Open some popover
3. Try to select and copy a text inside the popover

**Current behavior**

Constant focus on the close button.

**Expected behavior**

The text is selected and can be copied.

cc @karelhala @terezanovotna

**Comment by karelhala** [comment]
@rachael-phillips this is quite a critical issue for us, since we wanted to add popover to inform users why something failed but turns out users are not able to copy+paste any info from popover.

**Comment by terezanovotna** [comment]
We have the same use case for popovers as Karel described.

**Comment by rachael-phillips** [comment]
Hi @karelhala @rvsia we have seen this, and the team will take a closer look this week. Thanks for opening this and making us aware!
