### ISSUE TITLE
Missing storybook for couple of components

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#338]
When I was reviewing the folder structure after merging monorepo (which is awesome!) I found out that couple of components are missing storybook.
* [ ] dropdown: [code](https://github.com/patternfly/patternfly-react/tree/master/packages/core/src/components/Dropdown)
* [ ] inline edit: [code](https://github.com/patternfly/patternfly-react/tree/master/packages/core/src/components/InlineEdit)
* [ ] nav: [code](https://github.com/patternfly/patternfly-react/tree/master/packages/core/src/components/Nav)
* [ ] navbar: [code](https://github.com/patternfly/patternfly-react/tree/master/packages/core/src/components/Navbar)
* [ ] notification - different types of messages: [code](https://github.com/patternfly/patternfly-react/tree/master/packages/core/src/components/Notification)
* [ ] overlay trigger: [code](https://github.com/patternfly/patternfly-react/tree/master/packages/core/src/components/OverlayTrigger)

**Comment by rachael-phillips** [comment]
Hi @mfrances17 is this something you are still working on?

**Comment by mfrances17** [comment]
@rachael-phillips No, sorry... haven't looked at this in over a year. Forgot all about it. Unassigned it.
