### ISSUE TITLE
Accessibility: No way to wrap PF4 modal content and footer in a single HTML form element

### ISSUE THREAD

**Issue by spadgett** [patternfly/patternfly-react#3397]
**Describe the issue. What is the expected and unexpected behavior?**

In OpenShift, we have many modals that are forms. We need to be able to wrap the form inputs from the modal body and the buttons from the footer in a single HTML `form` element with a submit handler for accessibility. Not being able to do this breaks features like pressing enter inside an input to submit the form. It doesn't appear to be possible with the PF4 modal, however.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, no clear workaround. Maybe it's possible to put the buttons in the modal body.

**What is your product and what release version are you targeting?**

OpenShift 4.4

cc @rebeccaalpert @janwright73 @rhamilto

**Comment by janwright73** [comment]
@tlabaj and @jessiehuff will you please review.

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
Hi @spadgett, when using the `<Form>` component in a modal, we advise you place the form actions in the `<ActionGroup>` that is part of the form component, and omit the modal footer.

**Comment by mcoker** [comment]
I followed up with @mcarrano and @rebeccaalpert and we should support the original request. I've created a core issue here where we can investigate the best way to introduce this - https://github.com/patternfly/patternfly/issues/3153

**Comment by mcoker** [comment]
@nicolethoen @spadgett would placing the `form` attribute on the submit button in the modal footer work? That's a browser native and probably the easiest way to associate a submit button with a form when the button is outside of the form.

**Comment by spadgett** [comment]
@mcoker I think that would work.
