### ISSUE TITLE
SerialConsole shows some extraneous components

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#340]
The SerialConsole is now showing an extra text area and span:

![image](https://user-images.githubusercontent.com/11633780/39874151-ff6e0212-543a-11e8-92c3-63a1be2f590a.png)

**Comment by jeff-phillips-18** [comment]
@mareklibra Any idea on this? Maybe some missing styling?

**Comment by mareklibra** [comment]
right, styling is missing the the storybook, related to the #332
