### ISSUE TITLE
Downgrade React  to 16.4.0

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#3435]
We should downgrade React across this repo so that we don't accidentally use new React features in our library while claiming to support ^16.4.0.

**Comment by boaz0** [comment]
I can work on it. @tlabaj @redallen 
I just wonder - does it mean it's recommended to work with react-^16.4.0 and to stay away from react-16.8.0?
I'm asking this because we are not upgrading to 16.8.0 (I really want to use React hooks) because PF4 downgraded to react 16.4.0.

**Comment by redallen** [comment]
I've thought some more about this, and I'm toying around with the idea of _upgrading_ React to 16.8.0 in our breaking change release so that our library can use hooks. We could lock our version of React for the docs and demo app to `16.8.0`.

Thoughts @dgutride @jeff-phillips-18 @jschuler ? What versions of React are products using?

**Comment by redallen** [comment]
Closing in favor of #3875 in an upcoming breaking change release.
