### ISSUE TITLE
Select component change for Openshift Search Toolbar. Display count rather than selections.

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#3456]
**Describe the issue. What is the expected and unexpected behavior?**
For Openshift Search Toolbar, there is a design that requires the selections for the multi-select type-ahead select component to display only the count of selections rather than values. 
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by janwright73** [comment]
Related design for this issue: http://openshift.github.io/openshift-origin-design/admin-perspective/future-openshift/search/search
