### ISSUE TITLE
[Select] Missing clear button

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#3460]
**Describe the issue. What is the expected and unexpected behavior?**
When using filterable Select there is clear button missing. It is designed https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#type-ahead-filters and implemented in CSS core repository https://www.patternfly.org/v4/documentation/core/components/select#single-with-typeahead-expanded.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

* Use Select component
* Pass options to it
* Use custom filter function to filter out items

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
It is blocking us from using this component since users has no way how to clear filter string.

**What is your product and what release version are you targeting?**
Cloudservices

**Comment by tlabaj** [comment]
closed by #3502
