### ISSUE TITLE
Truncated modal title tooltip

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3503]
We noticed for Cost Management that the modal truncates long titles. According to Natalie, PatternFly should display the truncated title as a tooltip. That is, considering PatternFly is automatically truncating.

**Comment by rachael-phillips** [comment]
@mcarrano do you have any design input to offer on this issue? Should we add the tooltip?

**Comment by mcarrano** [comment]
Yes, I suppose there should be a tooltip to reveal the full title @rachael-phillips . Does this work need to be applied in core or is this strictly a React issue @mcoker @tlabaj ?

**Comment by dlabrecq** [comment]
@nlcwong

**Comment by tlabaj** [comment]
The ellipsis already get added when the title is long and overflows.  We would have to make a change in react to add a tooltip . Similar to what we do with a Chip.  I don't think any changes are needed? @mcoker

**Comment by mcoker** [comment]
@tlabaj sounds good, this shouldn't require any changes in core.
