### ISSUE TITLE
It is difficult/impossible to find docs/source for some components

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/patternfly-react#3511]
Greetings!  
So I was trying to find the source code for a component in order to learn about its API. I wasn't able to find source or docs for the following:

```javascript
CheckCircleIcon
```
I have suspicion it is generated in some way but had to move on before looking further into this.  If there is a way to bubble this up to something public & easy to find via the docs site that would be fantastic!

Thanks.

**Comment by benjaminapetersen** [comment]
FWIW, I believe its just a permutation on this:

https://github.com/patternfly/patternfly-react/tree/master/packages/react-icons

**Comment by boaz0** [comment]
Hi @benjaminapetersen 
Sorry for the late response. The docs for the icons can be found [here](https://patternfly-react.surge.sh/patternfly-4/icons).

The link to this page is in the top navigation bar (above the side bar):
![image](https://user-images.githubusercontent.com/2453279/72809525-76750c80-3c64-11ea-8e78-abefe6bb4f4d.png)

**Comment by tlabaj** [comment]
Thank you @boaz0!  
@benjaminapetersen  do you have enough information to proceed?
