### ISSUE TITLE
Is ReactIcons leaking internals into public API?

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/patternfly-react#3512]
Greetings,

I am just looking at the docs for using `ReactIcons`.  I see the following:

| Prop  | Description                                                      | Default        |
| ----- | ---------------------------------------------------------------- | -------------- |
| color | Color of the icon (e.g. red, white, #c3ee)                       | 'currentColor' |
| size  | Size of the icon. There are 4 different sizes: sm, md, lg and xl | sm             |
| title | Label of the icon                                                | null           |

Which can be translated into something like this:

```typescript
<CheckCircleIcon
   color="var(--pf-global--primary-color--100)"
   className="properties-side-panel-pf-property-value__capability-level-icon"
   title="Checked"
   />
```
I'm wondering if `color` and `size` are the best things to make public API as assigning `class` to govern these is almost always a better option.  I was a little worried to see `var(--pf-global--primary-color--100)` as the value as well as this seems like it could be fragile, but open to thoughts.  

Thanks!

**Comment by rachael-phillips** [comment]
@evwilkin making you aware of this one.

cc @tlabaj

**Comment by redallen** [comment]
These props are meant to be exposed and we don't have any plans of hiding them. They are like using `style={{}}` tags.

We do have props that we would like to hide from consumers or add annotations to, see #2139 . If you would like to see the descriptions changed or better icon docs on our site, please open an issue at https://github.com/patternfly/patternfly-org/issues.
