### ISSUE TITLE
<Progress /> dynamic aria disrupts Jest snapshotting

### ISSUE THREAD

**Issue by lallmon** [patternfly/patternfly-react#3518]
The `aria-describedby` property inside the `<Progress />` component seems to be dynamically generated every render, which makes Jest snapshot testing of pages using that component impossible, as they will fail on every run.

To reproduce:
Drop the component in a place where you run a Jest Snapshot test. Generate the snapshot then run the test again.

<img width="854" alt="Screenshot 2020-01-16 14 04 49" src="https://user-images.githubusercontent.com/1824267/72531369-329b9500-3869-11ea-8c60-02a238b3089e.png">

The above screenshot is a default `<Progress />` component, no Props set, no dynamic data otherwise.

**Comment by rachael-phillips** [comment]
@lallmon thanks for opening this, and we'll take a look at this!

**Comment by boaz0** [comment]
@lallmon - what if you pass `id` to `Progress`:
```js
<Progress id="progress-id" />
```

**Comment by lallmon** [comment]
@boaz0 That seems to have cleared it up. Does that mean the ID is a required prop? Or should be?

**Comment by boaz0** [comment]
It is required for ARIA reasons but not really from the API perspective. Thus, if the user doesn't give any ID we randomly generates a unique ID.
