### ISSUE TITLE
tables: no way to let sortable column headers wrap

### ISSUE THREAD

**Issue by spadgett** [patternfly/patternfly-react#3520]
**Describe the issue. What is the expected and unexpected behavior?**

The `sortable` and `wrappable` table header transforms don't seem to work together, which results in overlapping text for long column headers.

![Metrics Dashboards · OKD 2020-01-16 09-52-21](https://user-images.githubusercontent.com/1167259/72535227-31a53c00-3846-11ea-9f71-bc633b2ef259.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, no obvious workaround.

**What is your product and what release version are you targeting?**

OpenShift 4.4

cc @janwright73 @rhamilto

**Comment by christiemolloy** [comment]
@spadgett thanks for bringing up this issue! This is a change we would need to make in Core so I created an issue there: https://github.com/patternfly/patternfly-next/issues/2584

**Comment by tlabaj** [comment]
This was resolved by issue #3608
