### ISSUE TITLE
add masthead functionality to drawer demo

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#3526]
When https://github.com/patternfly/patternfly-next/pull/2541 closes in Core, we can add the functionality in React. When a user clicks on the notification bell in the masthead, it opens the drawer up, and the modifier is applied to the button(notification bell) so that it takes on the new styling. The background behind the button should remain active the entire time the drawer is open.

cc: @tlabaj @rachael-phillips

**Comment by rachael-phillips** [comment]
Should be added after notification drawer work is complete

**Comment by tlabaj** [comment]
This can now be completed since Notification Drawer has been added. #1939

**Comment by tlabaj** [comment]
waiting for core issue https://github.com/patternfly/patternfly/issues/3186
