### ISSUE TITLE
Investigation: regression tests for pf-core -> pf-react html/css changes

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#353]
Investigate, identify a proposal and implement regression tests to keep PF-React in sync with PF-Core changes.

**Comment by dmiller9911** [comment]
This is acheived through a babel plugin and snapshot serializer. Docs for those two peices can be found here:

Babel: https://github.com/patternfly/patternfly-react/tree/master/packages/react-styles#babel-plugin-patternflyreact-stylesbabel
Snapshots: https://github.com/patternfly/patternfly-react/tree/master/packages/react-styles#snapshot-testing
