### ISSUE TITLE
Page demos are missing imports

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#3532]
The page demos are missing imports (Breadcrumb, Gallery, Card, etc.).  When I copied the example from patternfly.org to a typescript project, the missing imports where flagged.

https://www.patternfly.org/v4/documentation/react/demos/pagelayout

**Comment by boaz0** [comment]
@dlabaj - this is fixed in the current react-core. But there are still error when using codesandbox:

```
e/<@https://codesandbox.io/static/js/sandbox.d82ca999d.js:1:229636
d@https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:13828

l/n._invoke</<@https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:13617

w/</e[o]@https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:14250

t@https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:8537

l@https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:8784

​
```
