### ISSUE TITLE
Card bug fix

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#3539]
In Core an issue was filed for a bug with the Card component. When an image was added to `__head` it wouldn't resize properly. To fix this bug we added a new wrapper element called `pf-c-card__head-main` to wrap the image. We should update React accordingly.

Core issue: https://github.com/patternfly/patternfly-next/pull/2578/files

**Comment by boaz0** [comment]
@christiemolloy for some reason I can't find `pf-c-card__head-main` in https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/Card/card.scss

I checked in pf-core version 2.56.1

**Comment by christiemolloy** [comment]
@boaz0 theres actually no styling associated with the class so that's why it won't show up in `card.scss` it is just a wrapper element for an image in the card head

**Comment by boaz0** [comment]
I see. so if no class is set to that element, it will be OK, right?
