### ISSUE TITLE
Component: Form > Help on Form

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#354]
Update the html so that it is more aligned with the [core PatternFly example](http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/#code).

This includes (but is not necessarily limited to):

- Including the class `popover-pf-info` for the popover toggle
- Having the toggle display on Focus (instead of Enter keypress) in addition to on Click

**Comment by jeff-phillips-18** [comment]
@jgiardino The core patternfly example uses an anchor and depends on there being a space after the text and before the anchor for spacing 😢   Do we really want to follow that?

**Comment by jgiardino** [comment]
@jeff-phillips-18 Good point. I'm also now realizing that having the popover display on focus instead of Click/Enter makes any clickable elements inside the popover inaccessible. 

Should the only change we make be adding the class `popover-pf-info` so that the correct color is applied?
