### ISSUE TITLE
PF4: Remove Toolbar Layout

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#3543]
**Describe the issue. What is the expected and unexpected behavior?**
Remove Toolbar Layout

**Comment by SpyTec** [comment]
Is toolbar layout being removed completely? Should we start use a different layout component?

**Comment by tlabaj** [comment]
@SpyTec The Toolbar will be removed as part of our breaking change release.  The Data toolbar component should be used in its place.

**Comment by redallen** [comment]
Fixed in #4170
