### ISSUE TITLE
Best practice for using DataToolbarFilter with same components

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3553]
The filterable table demo currently has three unique options in its category dropdown. The first option uses a select menu, the second uses a text input, while the third option uses a select with checkboxes.

In Cost Management, we have a category dropdown with four options. However, three of those options; cluster, node, & project, all use a text input. 

<img width="403" alt="Screen Shot 2020-01-22 at 8 35 07 PM" src="https://user-images.githubusercontent.com/17481322/72949852-7c97e580-3d57-11ea-8384-754787457e2f.png">

Looking again at the filterable table demo, It appears that each category must wrap its own component (i.e., text input) with a DataToolbarFilter.

<img width="432" alt="Screen Shot 2020-01-24 at 11 06 43 AM" src="https://user-images.githubusercontent.com/17481322/73083803-d1437980-3e99-11ea-9e0b-cca14a2b3521.png">

It's not clear if wrapping each text input with DataToolbarFilter is necessary? Ideally, I'd like to use the same input for all categories; cluster, node, & project, instead of unique instances for each. 

My concern is with this approach is scale. The more category options, the more text input component instances required.

Perhaps a best practice could be demonstrated with the existing demo?

**Comment by rachael-phillips** [comment]
@dlabrecq thanks for opening this issue! @tlabaj making you aware.

**Comment by dlabrecq** [comment]
When filtering by tag keys, each tag key has its own value selections. Using the same `DataToolbarFilter` for each tag key, ends up looking like this:

![Screen Shot 2020-01-23 at 11 14 11 AM](https://user-images.githubusercontent.com/17481322/73002629-582d1f00-3dd2-11ea-8277-e70f924bd93e.png)

This appears to be another example where we need a unique `DataToolbarFilter` instance for each tag key (e.g., "storageclass") option?

![Screen Shot 2020-01-23 at 11 25 51 AM](https://user-images.githubusercontent.com/17481322/73003178-308a8680-3dd3-11ea-9b92-d55cb7b789a6.png)

**Comment by tlabaj** [comment]
cc @mcarrano
