### ISSUE TITLE
Best practice for using DataToolbar with pagination

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3554]
It's not clear how to best use pagination with DataToolbar. The filterable table demo does not demonstrate this, nor do the DataToolbar examples.

There is a stacked example, but not what I'm looking for -- I want pagination on the same row.

**Comment by dlabrecq** [comment]
Thru trial and error, I discovered that a modifier was required. And that my pagination controls should not be wrapped with DataToolbarContent, so they appear on the same line. Still, an non-stacked example would have been most helpful.

![Screen Shot 2020-01-23 at 10 36 23 AM](https://user-images.githubusercontent.com/17481322/72998826-72fc9500-3dcc-11ea-8ff5-6c76eeb9a49b.png)

**Comment by tlabaj** [comment]
@mcarrano

**Comment by mcarrano** [comment]
@dlabrecq is there a reason you are wanting to left align the pagination control? Our standard is to right align it in the toolbar. You can see a core demo that illustrates this here: https://www.patternfly.org/v4/documentation/core/demos/datatoolbar Does that help at all?

**Comment by dlabrecq** [comment]
@mcarrano No, I want the pagination controls to be right aligned. 

Like I said above, I figured it out. I'm simply asking for a best practice example showing others how to implement it.

**Comment by mcarrano** [comment]
Yeah, we should probably have a more robust toolbar demo in React like we have in core.

**Comment by dlabrecq** [comment]
@mcarrano No, I want the pagination controls to be right aligned. I was showing my misaligned pagination controls -- removed to avoid confusion.

Like I said above, I figured it out. I'm simply asking for a best practice example showing how to implement it for the filterable table demo.

This is what my toolbar looks like now
![Screen Shot 2020-01-23 at 2 59 59 PM](https://user-images.githubusercontent.com/17481322/73019161-119aed00-3df1-11ea-9851-b26113ce9efa.png)

**Comment by FraBle** [comment]
@dlabrecq How does your final code look like? I'm currently running into the same issue: how to right-align the pagination in a data toolbar...?

**Comment by dlabrecq** [comment]
This is my current impl

![Screen Shot 2020-03-09 at 10 43 56 AM](https://user-images.githubusercontent.com/17481322/76225466-e9294f80-61f2-11ea-97f1-1c3d56f4c52d.png)
