### ISSUE TITLE
Table IAction require onClick to be supplied

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#3557]
**Describe the issue. What is the expected and unexpected behavior?**
Looking at IAction interface for `<Table>` actions prop it requires onClick function prop to be provided.

https://github.com/patternfly/patternfly-react/blob/c0a63bc68879aa447b3d99a57d94f217e15777c9/packages/patternfly-4/react-table/src/components/Table/Table.tsx#L110-L115

This prevents the ability to have link actions, such as the example provided in
https://www.patternfly.org/v4/documentation/react/components/table#simple-actions

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**

**Comment by rachael-phillips** [comment]
Hi @SpyTec thank you for opening this issue! @tlabaj making you aware.
