### ISSUE TITLE
DataToolbar: adding duplicate removes filter

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3561]
Not sure if this is by design, but adding a duplicate entry removes the current filter. Seems that users would want to keep the existing filter, just not add it again.

Filterable table demo:
![chrome-capture](https://user-images.githubusercontent.com/17481322/72998299-9ecb4b00-3dcb-11ea-94f4-bf83b5217483.gif)

**Comment by tlabaj** [comment]
@mcarrano Thoughts about this interaction?

**Comment by mcarrano** [comment]
@dlabrecq Yes, I agree this seems like a bug. There is some problem with the logic here. I wouldn't expect duplicating the filter to remove it.

**Comment by dlabaj** [comment]
This is a bug in the example not the actual component.  The filter in the example above is returning the previous filter without the current inputvalue.  I'll create a PR for this.
