### ISSUE TITLE
DataToolbarFilter: SelectVariant.checkbox wrapping

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3574]
Migrating Cost Management to use the new DataToolbarFilter and noticed an issue with SelectVariant.checkbox wrapping. Although the toolbar appears to have enough space, the checkbox counter is forced onto a new line.

<img width="1305" alt="Screen Shot 2020-01-24 at 9 41 54 AM" src="https://user-images.githubusercontent.com/17481322/73077481-3f823f00-3e8e-11ea-81e4-9acd2d1b9c7a.png">

As a workaround, I can hard code the Select's width, but prefer not to do that because the label is localizable and could be longer.

For reference, this is the code I'm using for the Select
<img width="634" alt="Screen Shot 2020-01-24 at 9 43 22 AM" src="https://user-images.githubusercontent.com/17481322/73077869-08f8f400-3e8f-11ea-8770-f4aa0f87c5db.png">

**Comment by tlabaj** [comment]
cc @mattnolting @mcoker

**Comment by mattnolting** [comment]
@dlabrecq at first glance, it looks like you need to use https://patternfly-react.surge.sh/patternfly-4/documentation/react/experimental/datatoolbar#consumer-managed-toggle-groups. Is that right?

**Comment by dlabrecq** [comment]
No, I'm not using anything consumer managed.

**Comment by mattnolting** [comment]
Sorry, I mean to say that the spacing suggests the grouping is mixed up. It looks a filter group(contextual filter) next to an individual filter..

**Comment by dlabrecq** [comment]
Looks like I needed to wrap the select menu with `DataToolbarItem`. We can close this. Thanks!
