### ISSUE TITLE
Notification Badge Enhancements

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#3597]
**Describe the issue. What is the expected and unexpected behavior?**
If this issue is consumed in patternfly, can we also provide the functionality to the notification badge react component:

https://github.com/patternfly/patternfly-next/issues/2628

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**Enhancement

**What is your product and what release version are you targeting?**Product: Openshift for  Version: 4.5

**Comment by tlabaj** [comment]
On hold until issue [#2628](https://github.com/patternfly/patternfly-next/issues/2628) is resolved.
