### ISSUE TITLE
PF4 Popover scrolling issues

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#3599]
**Describe the issue. What is the expected and unexpected behavior?**

I have a popover in a table.

**When scrolling up**, when the Popover leaves screen, **a second scrollbar** is shown:

![whenup](https://user-images.githubusercontent.com/32869456/73271541-0bd24c80-41e1-11ea-85f1-20c6d576100a.gif)

**When scrolling down**, Popover is always shown at the top of the page.

![whendown](https://user-images.githubusercontent.com/32869456/73271637-39b79100-41e1-11ea-9158-9c957766affd.gif)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://github.com/RedHatInsights/sources-ui/blob/be3a29e2165fd4b2636046e9b340e44715d7cd53/src/components/SourcesSimpleView/formatters.js#L220

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Minor bug.

**What is your product and what release version are you targeting?**

Sources https://github.com/RedHatInsights/sources-ui
No target

**Comment by fhlavac** [comment]
It looks like the "two scrollbars" issue still remains.

![001](https://user-images.githubusercontent.com/50696716/93322525-b0a6a600-f813-11ea-8a99-b416c1dc74ff.png)

```
<Popover
  zIndex="110"
  position="right"
  isVisible={ isPopoverVisible }
  enableFlip={ false }
  shouldClose={ () => setPopoverVisible(false) }
  hideOnOutsideClick={ true }
  bodyContent="This group contains the roles that all users in your organization inherit by default."
>
  <OutlinedQuestionCircleIcon
    onClick={ () => setPopoverVisible(!isPopoverVisible) }
    className={ classNames('pf-c-question-circle-icon', { 'icon-active': isPopoverVisible }) }
  />
</Popover>
```

**Comment by rvsia** [comment]
@tlabaj Is it please possible to re-open this issue?
