### ISSUE TITLE
Component: Message Dialog 

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#360]
Create a message dialog component.

There is a PatternFly design pattern in progress, which can help guide the work.  There are also examples in the V2V project as well as in Sonar (quipicords)

[Example in Quipicords Repo](https://github.com/quipucords/quipucords/tree/master/client/src/components/confirmationModal)
Example Quipicords Screenshots:
![screenshot-2018-5-18 red hat entitlements reporting 50](https://user-images.githubusercontent.com/12504403/40264515-b2c56a80-5af3-11e8-957d-16cc2c05c3f5.png)
![screenshot-2018-5-18 red hat entitlements reporting 41](https://user-images.githubusercontent.com/12504403/40264516-b2d097b6-5af3-11e8-8ba4-9fbf6ff14c44.png)
![screenshot-2018-5-18 red hat entitlements reporting 11](https://user-images.githubusercontent.com/12504403/40264517-b2dc56d2-5af3-11e8-87a1-51876a7cdaa7.png)
![screenshot-2018-5-18 red hat entitlements reporting 10](https://user-images.githubusercontent.com/12504403/40264518-b2eac064-5af3-11e8-9e3a-88d6968e9f7a.png)

**Comment by serenamarie125** [comment]
@michaelkro can you take this after you have a PR up for your current PR?  Additionally, let's chat with @jeff-phillips-18 around how to structure the storybook with dialog options etc before you get to far.

**Comment by michaelkro** [comment]
@serenamarie125 sounds good, I'm on it!

**Comment by michaelkro** [comment]
That being said, any custom CSS I am introducing for this component has been updated to be inline with the provided specs

**Comment by michaelkro** [comment]
Also, question about the requested examples.  As far as I know, it won't be possible to have multiple dialogs showing simultaneously using the markup as is.  Instead, I can add a modal launcher button for each example.  Thoughts/suggestions?
