### ISSUE TITLE
Catalog tile multi line truncated gradient positioned incorrectly in Firefox

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly-react#3606]
White gradient is not positioned correctly at the end of multi line text.

<img width="564" alt="Screen Shot 2020-01-28 at 12 12 02 PM" src="https://user-images.githubusercontent.com/1874151/73288813-acb50d80-41c9-11ea-92ae-fbc0ef5f006f.png">

**Comment by rachael-phillips** [comment]
@tlabaj  making you aware

**Comment by rachael-phillips** [comment]
@rebeccaalpert I know you've been working on this so making you aware.

**Comment by rebeccaalpert** [comment]
We've actually removed the gradient, so let me take a look at what's going on there.

**Comment by rebeccaalpert** [comment]
I can't recreate the gradient issue (I suspect this has resolved since we removed it, but it does look like some styles are suddenly off).

**Comment by rebeccaalpert** [comment]
Someone changed the classes on the elements without updating the example CSS. Will push a change to fix that separate issue today (opening https://github.com/patternfly/patternfly-react/issues/3633). I believe #3606 is resolved and ok to close as we've recently removed the gradient entirely.
