### ISSUE TITLE
PF4: Table missing descriptions fro some properties

### ISSUE THREAD

**Issue by ddonahue007** [patternfly/patternfly-react#3615]
Looking at the code base and the documentation you can see that there are property values missing form table.

**src:**
```
  variant?: 'compact';
  borders?: boolean;
  gridBreakPoint?: '' | 'grid' | 'grid-md' | 'grid-lg' | 'grid-xl' | 'grid-2xl';
```
**ui view:**
![table_props_desc](https://user-images.githubusercontent.com/57504257/73366545-21488480-427c-11ea-93ee-60e359f8bb2a.png)

Bug not blocking

**Comment by rachael-phillips** [comment]
We also have this Table documentation issue that should be addressed and is related: https://github.com/patternfly/patternfly-react/issues/2999

**Comment by seanforyou23** [comment]
I think this can be closed by https://github.com/patternfly/patternfly-react/pull/3745  - I will pick up the remaining bits of #2999 unless someone else beats me to it!
