### ISSUE TITLE
Filterable table demo: DataToolbar text input should use type="search"

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3616]
It appears that the data toolbar's text input, for the filterable demo, was accidentally changed from `type=search` to `type=text`. Doing so removes the close icon shown with the text input.

**With `type=search`:**

![Screen Shot 2020-01-29 at 10 58 22 AM](https://user-images.githubusercontent.com/17481322/73373358-830dec00-4286-11ea-97fa-fe6f49c5524b.png)

**Filterable table demo:**

![Screen Shot 2020-01-29 at 10 57 55 AM](https://user-images.githubusercontent.com/17481322/73373413-93be6200-4286-11ea-8bd1-d90a2e4a63b3.png)

**Comment by tlabaj** [comment]
cc @mattnolting core also has the type set to "text".  Should this be updated in core?  Or is this intentional?

**Comment by mattnolting** [comment]
@tlabaj the demo is correct, the example is wrong. It should be `search` in this context https://github.com/patternfly/patternfly-next/issues/2639
