### ISSUE TITLE
fix(data-list): Keyboard selection of action causes data list item selection

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#3617]
**Describe the issue. What is the expected and unexpected behavior?**
When using keyboard navigation with selectable data list, pressing enter or space on the kebab causes the entire data list item to be selected. This is also the case when putting a link or a button inside the data list item. I think that this is due to an event listener stopping the event propagation. 

<img width="576" alt="Screen Shot 2020-01-29 at 11 58 41 AM" src="https://user-images.githubusercontent.com/28281340/73379058-91acd100-428f-11ea-8239-221c9175cc3c.png">

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
 
Navigate through the [selectable data-list](https://www.patternfly.org/v4/documentation/react/components/datalist/selectable-rows) with tab, press enter or space on the kebab, the entire item will show that it is selected. Likewise you can also try adding a link or a button to the same effect. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?** 
This is a bug, not blocking but does seem like an unexpected behavior for users.

**Comment by boaz0** [comment]
Hi @jessiehuff, as you guessed [here](https://github.com/patternfly/patternfly-react/pull/3587#pullrequestreview-350286636) the event bubbles and the `onSelect` function is being triggered. Maybe a way to fix it is to wrap the onClick function of the Dropdown menu with a function that runs `event.stopPropagation()` - we can introduce a prop saying `bubbleEvent` in case there are projects that want to propagate that event to parents.
