### ISSUE TITLE
Add namespacing into data-ouia-component-type attributes

### ISSUE THREAD

**Issue by quarckster** [patternfly/patternfly-react#3626]
**Describe the issue. What is the expected and unexpected behavior?**

There are cases when a web application can use more than one component library and there could be used similar components such as Dropdown. In order to distinguish components with OUIA in QA suite  `data-ouia-component-type` should contain namespace e.g. `data-ouia-component-type=PF4/Dropdown`

Here spec excerpt https://ouia.readthedocs.io/en/latest/README.html#ouia-component:

> A root level HTML element with a data-ouia-component-type attribute describing a unique name identifying ALL HTML components that can be controlled with the same code or interactions. These identifiers MAY and SHOULD be namespaced when used within a framework, particularly when the name is generic. The delimiter between namespace and type name should be a single / character.

> * e.g. A page that has a special dropdown could choose to name that dropdown as FrameworkA/CustomDropdown. All instances of this FrameworkA/CustomDropdown component MUST be expected to be able to be controlled via the same automation.

**Comment by redallen** [comment]
#3622 and #3174 revealed that we have an overly complicated OUIA implementation that has a lot of drawbacks for the single advantage of respecting `localstorage['ouia:enabled']` to show or hide `data-ouia` attributes.

After discussion in the PR and Slack, I think the best course of action is to always include these properties in our OUIA components. This reduces boilerplate and makes conforming to the spec easier. This implementation can be extended to globally hide `data-ouia` attributes should we have the need.

**Comment by redallen** [comment]
Closed in #3927
