### ISSUE TITLE
Table PF4: using fullwidth on some row when the first cell of the table has headerCol formatter will hide the left blue navigation line

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3631]
This issue occurs when using headerCol property on a column and then on the row fullWidth property.
See the code snippet below for a reproducer.

https://codesandbox.io/s/fervent-sea-cnhhp

In only happens on broad screen sizes, on mobile the blue line is back.

**Comment by rachael-phillips** [comment]
Hi @KKoukiou we've seen this and are looking into it. cc @tlabaj

**Comment by tlabaj** [comment]
@KKoukiou I am unable to reproduce this.  By navigation line, do you mean the line showing the row has been selected?

**Comment by KKoukiou** [comment]
@tlabaj please check again, i updated the link above.
See the screenshot here as well:
<kbd>
![Screen Shot 2020-02-06 at 10 45 00](https://user-images.githubusercontent.com/14921356/73925133-db1fa080-48cd-11ea-9b64-395c9384cd31.png)
</kbd>
Do you notice the the second expanded item does not have the blue line on the left border of the row? That's what happens when fullWidth is used.
I hope it's clear now.

**Comment by tlabaj** [comment]
@KKoukiou Thank you!  I will take another look.

**Comment by KKoukiou** [comment]
@tlabaj please reopen and as discussed in the previous cockpit/PF4 migration meeting please make sure that the bot does not close actual bugs without human approval.
