### ISSUE TITLE
Labels and buttons look almost the same

### ISSUE THREAD

**Issue by spadgett** [patternfly/patternfly-react#3638]
**Describe the issue. What is the expected and unexpected behavior?**

The `Button` and `Label` components have almost the same style. The only difference appears to be slightly different padding. This makes the `Label` look like a clickable element.

See the examples here:

https://patternfly-react.surge.sh/documentation/react/components/button
https://patternfly-react.surge.sh/documentation/react/components/label

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, arguably an accessibility issue.

cc @rhamilto @serenamarie125

**Comment by serenamarie125** [comment]
@mcarrano this was logged as a React issue - can you confirm if this is by design?  If so, should a patternfly-design issue be created as well?  

Looking at how they handle this on GH, buttons & labels are the same "shape, but buttons seem to have a border and some gradient applied.  Curious @spadgett if you think the differentiation on GH is enough and may be a possible solution to consider

FYI @beanh66 @LHinson

**Comment by serenamarie125** [comment]
@rachael-phillips FYI

**Comment by beanh66** [comment]
Thanks for bringing this up @spadgett. I think @maryshak1996 did a larger exploration around how to treat Buttons vs Labels vs Badges vs Filter chips for PF4. Mary, do you have more background here or any recommendations? Maybe a follow up design story is still needed. cc @mceledonia

**Comment by maryshak1996** [comment]
@spadgett it looks like some work is being done in the form of an enhancement to the labels here: https://github.com/patternfly/patternfly-design/issues/751

**Comment by maryshak1996** [comment]
@beanh66 I can't find the previous work I had done around labels, but I'm happy to jump on (if needed) for the design issue that I posted above

**Comment by mcarrano** [comment]
Yes, per @maryshak1996 's comment above, we do already have an open design issue for this and plan to address it for our breaking change release. Feel free to post further comments or ideas against that issue.

**Comment by maryshak1996** [comment]
was able to find some work comparing all of the visually similar components here: 
![image](https://user-images.githubusercontent.com/19824574/73669951-5dae2300-4676-11ea-8fd8-72277c542555.png)
