### ISSUE TITLE
Checkbox select does not handle items with the same name

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-react#3639]
Checkbox Select does not distinguish between items with the same name when checking them as selected or not, even with differing key values.

Example: https://codesandbox.io/s/peaceful-architecture-wn7nb
Open the select. Check a box. Note that the corresponding box for the second item with the same name is also selected.

This is a bug in the component. It is blocking Kogito Domain Explorer from using the checkbox select.

**Comment by kmcfaul** [comment]
@srambach 
`key` must be unique for React, but it is not used by the component.

Currently, selections are determined via string comparison of `value`, so it should be unique. But the display of the option does not have to be tied to `value` directly. 

To allow multiple options to share a display name, use the `children` property of `SelectOption`. For example, here is your sandbox with the options changed to the format `<SelectOption value="unique-value">display-name</SelectOption>`. https://codesandbox.io/s/sharp-meadow-0r574

Is this functionality sufficient for this use case?

**Comment by kmcfaul** [comment]
@srambach Is still still an open issue or did the above solution address it?

**Comment by srambach** [comment]
@kmcfaul Sorry for the delay. We've used the solution you mention, but the codesandbox linked from the example still breaks if you use two options with the same text. It would be good to make the example work properly so that anyone using it as an example won't run into this problem.
