### ISSUE TITLE
Cannot render <Spinner> in Patternfly 4

### ISSUE THREAD

**Issue by Andrei-Stepanov** [patternfly/patternfly-react#3659]
Hello, I am a bit not very confident user of React.
This could be not a bug, but, I tried in many different ways to add <Spinner> component.
It fails with:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

I took example from: https://www.patternfly.org/v4/documentation/react/components/spinner

react-core-3.129.3

**Comment by tlabaj** [comment]
Hi @Andrei-Stepanov can you provide a snippet of your code or link a code sandbox.

**Comment by Andrei-Stepanov** [comment]
@tlabaj  sure. Here is reproducer:

```
npx create-react-app spinertest
cd spinertest
npm install @patternfly/react-core=3.129.3
vim src/App.js
```

Add 2 lines:

```
import { Spinner } from '@patternfly/react-core'; <------------- add this

function App() {
  return (
    <div className="App">
      <Spinner size="xl"/> <------------- add this.
      <header className="App-header">

.......
```


Result:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by jschuler** [comment]
I think for that version of react-core, the Spinner was still an experimental component. Can you import it like this?
`import { Spinner } from '@patternfly/react-core/dist/esm/experimental';`
or 
`import { Spinner } from '@patternfly/react-core/dist/js/experimental';`

Or try to upgrade to the latest version of react-core (currently at 3.134.2)

**Comment by Andrei-Stepanov** [comment]
@jschuler hi,

On 3.134.2 there is no error.
But, also no visual Spinner. Check screenshot
![Screenshot 2020-02-06 at 15 57 24](https://user-images.githubusercontent.com/12443962/73948712-a1fd2580-48f9-11ea-8b1e-31f19059beec.png)
.

**Comment by jschuler** [comment]
Are you also importing `import "@patternfly/react-core/dist/styles/base.css";`?
Please check
https://codesandbox.io/s/happy-ptolemy-0mkv4

**Comment by Andrei-Stepanov** [comment]
@jschuler thank you! 
I added: `import "@patternfly/react-core/dis` and it works with 3.134.2.
It works!  But it does not work with 3.129.3

**Comment by jschuler** [comment]
happy to hear @Andrei-Stepanov !
