### ISSUE TITLE
borken link in README.md

### ISSUE THREAD

**Issue by goern** [patternfly/patternfly-react#366]
the section "Using patterfly-react Sass files" contains a link (last word) to https://github.com/patternfly/patternfly-react/blob/master/sass/patternfly-react.scss

This results in a 404

**Comment by ibolton336** [comment]
While playing around with PF3 locally, I noticed this broken link is still broken.

**Comment by jeff-phillips-18** [comment]
@ibolton336 Can you update the link to our story book from  `https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html`   to `http://patternfly-react.surge.sh/` while you are in there?

**Comment by rachael-phillips** [comment]
closing this issue
