### ISSUE TITLE
Changing Switch component id causes it to not be clickable

### ISSUE THREAD

**Issue by jeudy100** [patternfly/patternfly-react#3662]
**Describe the issue. What is the expected and unexpected behavior?**
When you change the id attribute on the switch the for attribute on the label that wraps around the switch input does not get changed. I would expect that when I change the id attribute, both the for attribute on the label and the id attribute on the input should be the same whenever the id is changed. The problem is that on [line #49](https://github.com/patternfly/patternfly-react/blob/6290a542f17baae3e84779dcc18bfe7dbbab40a1/packages/patternfly-4/react-core/src/components/Switch/Switch.tsx#L49) the id is set and never reset if the switch id gets changed, and then on [line #72](https://github.com/patternfly/patternfly-react/blob/6290a542f17baae3e84779dcc18bfe7dbbab40a1/packages/patternfly-4/react-core/src/components/Switch/Switch.tsx#L72) all the props are being deconstructed on the input which overwrites the the old id with the new, which is what causes the mismatch between the label's for attribute and the input's id attribute.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/jovial-montalcini-3dfdu

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug and the only workaround is that if you make the id static. For example, I just made the id's for the list of switches their index of the array they were in.

**Comment by boaz0** [comment]
That's odd - I was expecting React to show a warning message saying `key` prop is missing:

```js
  React.useEffect(() => {
    console.log('data',data)
    setRows(
      data.map(d => ({
        cells: [
          {
            title: (
              <Switch
                key={d.id}        <--------------- RIGHT HERE
                id={d.id}
                isChecked={d.isChecked}
                onChange={onChange(d)}
              />
            )
          }
        ]
      }))
    );
  }, [data]);
```

Do you mind testing it with the `key` prop set? Did it work?

Anyhow, I believe it's an easy fix on our side, I can work on it.
