### ISSUE TITLE
Wizard: The wizard is another implementation of modal

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#3668]
**Describe the issue. What is the expected and unexpected behavior?**
This issue is the follow up work needed in React once core issue [#2046](https://github.com/patternfly/patternfly-next/issues/2046) is resolved.  The Wizard will default to an in-page variation so the consumer can place it in a modal.

(This will address the first bullet point in issue #2114 )

**Comment by evwilkin** [comment]
May be partially resolved in #4116
