### ISSUE TITLE
Tabs: Update element name

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3681]
https://github.com/patternfly/patternfly-next/issues/2594 to better align the element/class names with other components.

**Comment by mcoker** [comment]
The work for this has been completed in https://github.com/patternfly/patternfly/pull/2919.

This work could be done with https://github.com/patternfly/patternfly-react/issues/3951

**Comment by tlabaj** [comment]
looks like this was already resolved.
