### ISSUE TITLE
Clipboard copy: replace custom button with button component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3683]
https://github.com/patternfly/patternfly-next/issues/2274

**Comment by mcoker** [comment]
The work for this is complete - https://github.com/patternfly/patternfly/pull/2922

It replaces the custom buttons in the clipboard copy component with the control variation of the button component.

**Comment by kmcfaul** [comment]
Closed in #4116

**Comment by redallen** [comment]
Yep, thanks @kmcfaul !
