### ISSUE TITLE
Chip group behavior updates

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3684]
Placeholder for the work in https://github.com/patternfly/patternfly-next/issues/1837

**Comment by mcoker** [comment]
There are behavioral issues in the issue that are beyond the changes introduced by core - https://github.com/patternfly/patternfly/issues/1837

The core work is complete https://github.com/patternfly/patternfly/pull/2961

* Changes `pf-m-toolbar` to `pf-m-category`
* The `<li>` in the top-level `<ul>` in a category/toolbar chip group now has a class `.pf-c-chip-group__list-item`
* The overflow chip now goes inside category/toolbar chip groups instead of outside

cc @christiemolloy anything else I missed?

**Comment by christiemolloy** [comment]
No, I think thats good. All other changes are documented by design in the issue

**Comment by mcoker** [comment]
We are still working on a restructure in core that should finish before this work begins - https://github.com/patternfly/patternfly/pull/3058/

I will update this PR when that work has merged.

**Comment by mcoker** [comment]
@tlabaj the work in https://github.com/patternfly/patternfly/pull/3058 has been merged, so this is ready to work on

**Comment by tlabaj** [comment]
closed by #4246
