### ISSUE TITLE
Label: updates to support new design

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3688]
Placeholder for https://github.com/patternfly/patternfly-next/issues/2656. Will likely result in changes to the current label component elements.

**Comment by mcoker** [comment]
The core work is complete. A full list of changes is in the description of the PR. https://github.com/patternfly/patternfly/pull/2943/

**Comment by evwilkin** [comment]
May be partially addressed in #4116 (removed isCompact prop)
