### ISSUE TITLE
react-console: Allow hiding `Send Key` or give it the ability to send different keys other than 'Ctrl-Alt-Delete'

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#3689]
The current implementation of the VncConsole component allows us to send 'Ctrl-Alt-Delete' key to the console, and there is a dropdown menu providing that action.
However that menu can't be extended with more keys, like `Ctrl-Alt-F1` etc which are usual key combination switching between consoles.
Then there is another property called `additionalButtons` defined [here](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/react-console/src/VncConsole/VncActions.js#L20), which will allow us to implement the rest of keys. In that case we would like to hide that default `Send key` button and add that option in the new dropdown through `additionalButtons`.

**Comment by rachael-phillips** [comment]
Hi @KKoukiou we've seen this issue and will be back soon with a response.
