### ISSUE TITLE
Select: make count badge optional in checkbox select

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3705]
https://github.com/patternfly/patternfly-next/pull/2642

Original issue - https://github.com/patternfly/patternfly-next/issues/2519

**Comment by andrewballantyne** [comment]
@mcoker @tlabaj This appears to have been fixed by #3976 can we close this issue? 

Also, does that mean this is an available feature for consumption downstream?

**Comment by mcoker** [comment]
Hi @andrewballantyne, yes this issue should be closed, thanks for catching that. The feature was released on March 31 and is ready for consumption. It was released in `@patternfly/react-core@3.153.3`. You can find more information about that particular release here on the [2020.04 release notes page](https://www.patternfly.org/v4/documentation/react/overview/release-notes#202004-release-notes-2020-03-31)

And if you want to test it out first, you can see the feature in the [select component examples](https://www.patternfly.org/v4/documentation/react/components/select#checkbox-input-no-badge). The prop for hiding the badge is `isCheckboxSelectionBadgeHidden`.
