### ISSUE TITLE
Selected SelectOption does not honor `isDisabled` attribute

### ISSUE THREAD

**Issue by romanblanco** [patternfly/patternfly-react#3707]
**Describe the issue. What is the expected and unexpected behavior?**

While the option is set as disabled, it's still possible to remove it from the list of selected items

![Screenshot_2020-02-10 CodeSandbox](https://user-images.githubusercontent.com/1187051/74148627-cc9ef500-4bfd-11ea-8fc1-4e0337c7b470.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

1. Open CodeSandbox for [Multiple Select](https://patternfly-react.surge.sh/documentation/react/components/select#multiple)
2. Set an option as disabled and add it in `selected`:

```typescript
    this.state = {
      options: [
        { value: 'Alabama', disabled: true },
        { value: 'Florida', disabled: false },
        { value: 'New Jersey', disabled: false },
        { value: 'New Mexico', disabled: false },
        { value: 'New York', disabled: false },
        { value: 'North Carolina', disabled: false }
      ],
      isExpanded: false,
      selected: ['Alabama'],
      isCreatable: false,
      hasOnCreateOption: false
    };
3. Refresh CodeSandbox brower
```

`Alabama` option can not be added anymore from the list of option, but still can be removed from the `selected` list.

On Chip object itself, this is possible to set by [`isReadOnly`](https://patternfly-react.surge.sh/documentation/react/components/chipgroup#props) attribute.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Either bug or `isReadOnly` possibility is missing.

**What is your product and what release version are you targeting?**

https://github.com/ansible/ansible-hub-ui/pull/94#issuecomment-582561366

**Comments**

I've also tried to use [`isPlaceholder`](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Select/SelectOption.tsx#L28-L29) attribute. This did not help either.

**Comment by rachael-phillips** [comment]
Hi @romanblanco we've seen this issue and will be back soon with a response.
