### ISSUE TITLE
popover display artifacts when closing

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#3722]
This bug is easily observed in the patternfly react documentation website.

Steps to reproduce:
- Open Popover documentation: https://www.patternfly.org/v4/documentation/react/components/popover
- scroll down to the first example popover. Make sure to scroll down enough so that the popover is forced to open to the right.
- toggle the popover open and closed by clicking the `Toggle Popover` button.

Observe: 
The contents of the popover are unmounted immediately on close which triggers tippy to reposition the popover causing the popover to move positions to the top.
![popover-flicker](https://user-images.githubusercontent.com/14068621/74247660-64f7b100-4cb4-11ea-8502-987c875a05bf.gif)

![image](https://user-images.githubusercontent.com/14068621/74247083-87d59580-4cb3-11ea-9e32-d2307857ac5d.png)

Expected:
The contents of the popover should not be unmounted until the animation is complete.

**Comment by rachael-phillips** [comment]
Hi @christianvogt we've seen this issue and will be back soon with a response.

**Comment by christianvogt** [comment]
bump. This is still an issue.
