### ISSUE TITLE
implement full clean target

### ISSUE THREAD

**Issue by ddonahue007** [patternfly/patternfly-react#3728]
List of files/dirs that the clean target should remove when called.

➜  patternfly-next git:(feat/size-report) git clean -ndfx
Would remove .cache/
Would remove .circleci/css-size-report/node_modules/
Would remove .circleci/css-size-report/package-lock.json
Would remove .circleci/css-size-report/report.html
Would remove .vscode/
Would remove allure-report/
Would remove coverage/
Would remove dist/
Would remove node_modules/
Would remove public/
Would remove src/icons/PfIcons/
Would remove static/assets/fontawesome/
Would remove static/assets/fonts/
Would remove static/assets/pficon/
Would remove workspace/

**Comment by redallen** [comment]
This should be opened under the patternfly-next repo.
