### ISSUE TITLE
PF4: Add  File Upload Component 

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#3735]
**Describe the issue. What is the expected and unexpected behavior?**
Introduce File Upload component according to the UI design here: https://marvelapp.com/de0ggah

This component will be introduced for uploading text files only. The user can upload a file by browsing to it, pasting its contents, or dragging and dropping it.

This is related to core issue https://github.com/patternfly/patternfly-next/issues/2624

**Comment by mturley** [comment]
Do we have a timeline for this? I would love to do this, depending on when I can free up some time.

**Comment by mturley** [comment]
cc @mcarrano @rachael-phillips @LHinson

**Comment by tlabaj** [comment]
@mturley We are hoping to get this in for Milestone 2020.03.  Code freeze is March sixth.  Do you think you can pick it up?

**Comment by mturley** [comment]
Yes, I think I can start it later this week. It shouldn't take too long, judging by my PF3 implementation.

**Comment by mturley** [comment]
I expect to start on this on Monday.

**Comment by mturley** [comment]
I have an open question about the invalid state, which I detailed in the core PR here (https://github.com/patternfly/patternfly-next/pull/2681#issuecomment-591618011) for visibility from folks who were involved in that implementation.
