### ISSUE TITLE
Add support for Vertical Divider

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-react#3736]
#### SUMMARY
Divider Component: https://www.patternfly.org/v4/documentation/react/components/divider

Currently the Divider component only supports horizontal line breaks. We use vertical dividers to visually break up toolbar actions and headers, it would be awesome if you could provide a vertical variation of the Divider. 

##### Header
<img width="278" alt="Screen Shot 2020-02-12 at 11 07 15 AM" src="https://user-images.githubusercontent.com/15881645/74353467-f3893280-4d87-11ea-9b00-15cd25e65f88.png">

##### Toolbar
<img width="304" alt="Screen Shot 2020-02-12 at 11 09 07 AM" src="https://user-images.githubusercontent.com/15881645/74353574-1ddaf000-4d88-11ea-909e-6c8d0e73e0f7.png">

##### DataList
<img width="298" alt="Screen Shot 2020-02-12 at 11 10 11 AM" src="https://user-images.githubusercontent.com/15881645/74353690-4bc03480-4d88-11ea-888f-0279893a1cc8.png">

**Comment by rachael-phillips** [comment]
Hi @marshmalien we have seen this issue and will be back soon with a response!

**Comment by tlabaj** [comment]
cc @mcarrano @mcoker

**Comment by mcoker** [comment]
We have a core issue for this and can bump up the priority https://github.com/patternfly/patternfly-next/issues/2148

**Comment by marshmalien** [comment]
@trahman73

**Comment by mcoker** [comment]
This has been merged in core https://github.com/patternfly/patternfly/pull/2734
