### ISSUE TITLE
Remove DataListAction children requirement

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-react#3751]
#### SUMMARY
DataList Props: https://www.patternfly.org/v4/documentation/react/components/datalist#props

DataListAction component requires { children }, but sometimes the action button children are "hidden" based on user permissions. 

```
Warning: Failed prop type: The prop `children` is marked 
as required in `DataListAction`, but its value is `undefined`.
```

Removing the requirement for children would help us get around this error.

**Comment by tlabaj** [comment]
@marshmalien are you saying that the Action list is empty?  If so, is it possible to not render the Action List?

**Comment by marshmalien** [comment]
> are you saying that the Action list is empty?

Yes, DataListAction could be empty given certain user permissions. For example, with the code below, the DataListAction component could have no { children } if the user did not have permission to delete, edit, or launch. 
```
<Row>
  {...content}
  <DataListAction>
    {canDelete && <DeleteButton />}
    {canEdit && <EditButton />}
    {canLaunch && <LaunchButton />}
  </DataListAction>
</Row>
```

Should I instead use the DataListAction component like this?
```
<Row>
  {...content}
  {canDelete && (
    <DataListAction>
      <DeleteButton />
    </DataListAction>
  )}
  {canEdit && (
    <DataListAction>
      <EditButton />
    </DataListAction>
  )}
  {canLaunch && (
    <DataListAction>
      <LaunchButton />
    </DataListAction>
  )}
</Row>
```

**Comment by marshmalien** [comment]
cc @trahman73

**Comment by tlabaj** [comment]
@marshmalien, yes that is how I would expect it to be coded.
@mcoker Is the  `.pf-c-data-list__action`. intended to wrap more than one action?

**Comment by mcoker** [comment]
> Is the .pf-c-data-list__action. intended to wrap more than one action?

@tlabaj `.pf-c-data-list__item-action` does support multiple actions. It's a flex row that adds a spacer between it's direct children and keeps them from wrapping. You can see it in [react datalist example](https://www.patternfly.org/v4/documentation/react/components/datalist#checkboxes-actions-and-additional-cells).

```
  <DataListAction
    className={css(DataListActionVisibility.visibleOnXl, DataListActionVisibility.hidden)}
    aria-labelledby="check-action-item3 check-action-action3"
    id="check-action-action3"
    aria-label="Actions"
  >
    <Button variant="primary">Primary</Button>
    <Button variant="secondary">Secondary</Button>
    <Button variant="secondary">Secondary</Button>
    <Button variant="secondary">Secondary</Button>
  </DataListAction>
```

However we do have `.pf-c-data-list__action` that wraps the kebab menus and positions the kebab menu vertically so that it aligns better with the row content, though looking at the react implementation, I don't see that class in use. I may be missing it. Can you verify?

You can see it in this [core datalist example](https://www.patternfly.org/v4/documentation/core/components/datalist#compact)

```
<div class="pf-c-data-list__item-action">
  <div class="pf-c-data-list__action">
    <div class="pf-c-dropdown">
      <button class="pf-c-dropdown__toggle pf-m-plain" type="button" id="data-list-compact-action1-button" aria-expanded="false" aria-label="Actions">
        <i class="fas fa-ellipsis-v" aria-hidden="true"></i>
      </button>
      <ul class="pf-c-dropdown__menu pf-m-align-right" aria-labelledby="data-list-compact-action1-button" hidden>
        <li>
          <a class="pf-c-dropdown__menu-item" href="#">Link</a>
        </li>
        <li>
          <button class="pf-c-dropdown__menu-item" type="button">Action</button>
        </li>
        <li>
          <a class="pf-c-dropdown__menu-item pf-m-disabled" href="#" aria-disabled="true" tabindex="-1">Disabled link</a>
        </li>
        <li>
          <button class="pf-c-dropdown__menu-item" type="button" disabled>Disabled action</button>
        </li>
        <li class="pf-c-dropdown__separator" role="separator"></li>
        <li>
          <a class="pf-c-dropdown__menu-item" href="#">Separated link</a>
        </li>
      </ul>
    </div>
  </div>
</div>
```

**Comment by tlabaj** [comment]
@mcoker I just did a quick look. You are right, `pf-c-data-list__action` is not being used in the react implementation it looks like the kebab is being wrapped in `pf-c-data-list__item-action`.

Another question @mcoker. Would rendering an empty `.pf-c-data-list__item-action` `<div>` as @marshmalien has in her example above we ok?  The current react code requires that the `div` has children.

**Comment by mcoker** [comment]
> pf-c-data-list__action is not being used in the react implementation

OK, I'll open an issue.

> Would rendering an empty .pf-c-data-list__item-action <div> as @marshmalien has in her example above we ok?

Not currently because the presence of `.pf-c-data-list__item-action` adds space in the data list, whether it has children or not. The second example where `<DataListAction>` is rendered conditionally is how I would do it, too.

**Comment by tlabaj** [comment]
@marshmalien I would like to close this issue since it is not recommended that you have an empty `<DataListAction>`.  Instead, you should conditionally render it if it has children.

**Comment by marshmalien** [comment]
Chatted with @tlabaj offline and came to the below solution: 
```
<Row>
  {...content}
  {canDelete || canEdit || canLaunch &&
  <DataListAction>
    {canDelete && <DeleteButton />}
    {canEdit && <EditButton />}
    {canLaunch && <LaunchButton />}
  </DataListAction>
}
</Row>
```
