### ISSUE TITLE
PF4 Table: empty state does not scale on smaller screens 

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#3756]
**Describe the issue. What is the expected and unexpected behavior?**

The empty state does not scale on smaller screens in tables.

**Current**

![image](https://user-images.githubusercontent.com/32869456/74641948-6c1a3580-5172-11ea-8389-cf4b6f2fef1b.png)

**Expected**

![image](https://user-images.githubusercontent.com/32869456/74641912-6290cd80-5172-11ea-9a16-2085059d76a2.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

1. Go to https://patternfly-react.surge.sh/documentation/react/components/table/empty-state
2. Shrink your window

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug. Probably the styles could be overridden but that would be crazy.

**What is your product and what release version are you targeting?**

Sources UI ASAP.  https://github.com/rvsia/sources-ui

**Comment by Hyperkid123** [comment]
Yup the empty state is very strange on mobile screens.

![screenshot-ci cloud redhat com-2020 02 17-13_07_00](https://user-images.githubusercontent.com/22619452/74652476-64648c00-5186-11ea-8244-58c6ba60e391.png)

**Comment by rachael-phillips** [comment]
Hi @rvsia and @Hyperkid123 thanks for opening this issue! We have seen this issue and will be back soon with a response.

**Comment by tlabaj** [comment]
@mcoker Can you please take a look at this one.

**Comment by mcoker** [comment]
@tlabaj the `<td>` should not have a `data-label` since that cell doesn't need a column name. Can you remove that?
