### ISSUE TITLE
PF4 Table: Expandable examples have misleading/incorrect arguments for `onCollapse` and include in-place mutation of React state

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#3762]
In the PF4 Table examples and demos which include expandable rows, there is an `onCollapse` method which looks like this ([example 1](https://github.com/patternfly/patternfly-react/blame/main/packages/react-table/src/components/Table/examples/Table.md#L1169), [example 2](https://github.com/patternfly/patternfly-react/blob/main/packages/react-integration/demo-app-ts/src/components/demos/TableDemo/TableCollapsibleDemo.tsx#L62)):
```ts
  onCollapse(event: React.MouseEvent, rowKey: number, isOpen: boolean) {
    const { rows } = this.state;
    /**
     * Please do not use rowKey as row index for more complex tables.
     * Rather use some kind of identifier like ID passed with each row.
     */
    rows[rowKey].isOpen = isOpen;
    this.setState({
      rows
    });
  }
```

There is also a `rowKey` prop in `TableBody`, and based on the above disclaimer, that led me to believe that the `rowKey` prop would define the value of the `rowKey` argument of `onCollapse` and give me a non-numeric reference to which row is being collapsed. In fact, `TableBody`'s `rowKey` prop seems unrelated (I'm not sure exactly what it's for).

The actual code which calls this `onCollapse` function is [here](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-table/src/components/Table/utils/decorators/collapsible.tsx#L27):
```ts
onCollapse && onCollapse(event, rowIndex, rowData && !rowData.isOpen, rowData, extraData);
```

So, the value being passed into the `rowKey` argument in these examples is actually the `rowIndex`, and the examples don't include the `rowData` or `extraData` arguments which actually are useful for identifying the row using its other properties.

We should at least change `rowKey` to `rowIndex` in the docs here, and possibly also show a use case where something like `rowData.id` is used instead, so that the disclaimer becomes unnecessary and people don't copy the problematic code.

The other problem with this code is that it mutates React state in-place (`rows[rowKey].isOpen = isOpen;`), which [the React docs say never to do](https://reactjs.org/docs/react-component.html#state):

> Never mutate `this.state` directly, as calling `setState()` afterwards may replace the mutation you made. Treat `this.state` as if it were immutable.

Even though `setState` is called in the next line and this is *probably* safe to do here, it is a bad practice to spread. Instead the function should do something like:
```ts
    const { rows } = this.state;
    const row = rows[rowIndex]; // or rows.find(...) if not using rowIndex
    const newRows = [...rows];
    newRows[rows.indexOf(row)] = { ...row, isOpen };
    this.setState({ rows: newRows });
```

And we should look for other examples of mutating state in-place like this to fix.

**Comment by mturley** [comment]
cc @srambach @AjayJagan

**Comment by cben** [comment]
I was also confused by this.

There are various ways to code the state and `onCollapse` with meaningful keys instead of numeric indexes.
But AFAICT, the `parent` of child rows must be a numeric index?  For example `rows[row.parent]` accessed here:
https://github.com/patternfly/patternfly-react/blob/c9eba54e3c252e567a37dda428dc8641e9589a05/packages/react-table/src/components/Table/utils/utils.tsx#L29-L34
Is there any way to use custom keys in `parent` instead?

**Comment by mturley** [comment]
I believe that would require a significant refactor (and breaking change, unless we deprecate it and add some kind of `parentKey` or something alongside it), but I agree it would be much better.

**Comment by mturley** [comment]
Note to self on resolving this one: To truly avoid mutating any state in-place, the spread (or equivalent Array.from) is not quite enough. I found that making a copy of an array of objects doesn't make a copy recursively, it makes a new array of references to the same objects from the old array. It protects against reassigning elements:
```ts
const newArray1 = oldArray;
newArray1[0] = something; // This modifies oldArray too!
const newArray2 = [...oldArray]; // or Array.from(oldArray);
newArray2[0] = something; // This is safe!
```
but it doesn't protect against mutating properties on elements (I learned this today in the REPL!):
```ts
const newArray = [...oldArray];
newArray[0].foo = something; // This modifies oldArray[0].foo too!
```
The real solution is to make full copies of everything you modify, as deep as you are modifying them:
```ts
const newArray = [...oldArray];
newArray[0] = { ...newArray[0], foo: something }; // This is safe!
// If we need to go deeper, we need to repeat the pattern at each level:
newArray[0] = { ...newArray[0], props: { ...newArray[0].props, foo: something } };
```

We should be on the lookout for other places in our examples (and components!) where we may have this problem. I'm fixing a few of them in Table demos for #6168.
