### ISSUE TITLE
PF4 component source maps

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#3763]
Source maps are not generated per component basis, only for the `index.js`. If you use absolute import paths, the console in the browser will be swarmed with warnings:

![Screenshot from 2020-02-18 10-25-29](https://user-images.githubusercontent.com/22619452/74722461-4310a800-5239-11ea-8f06-a54c72c953a5.png)

Solution: generate source maps for all components.

**Comment by rachael-phillips** [comment]
Thanks for opening this! cc @evwilkin

**Comment by evwilkin** [comment]
@Hyperkid123 FYI we've pulled this into the current milestone - it will be incorporated in the work @redallen is doing towards #3972 , which is currently breaking down #4010 into smaller PRs for review.
