### ISSUE TITLE
DataToolbarFilter: Maximum update depth exceeded

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#3770]
In Cost Management, we discovered a "Maximum update depth exceeded" issue with the data toolbar.

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops

![Screen Shot 2020-02-18 at 11 17 17 AM](https://user-images.githubusercontent.com/17481322/74754861-465b6200-5240-11ea-8205-00b118ac6991.png)

This appears to be a problem with how the PatternFly requires a unique DataToolbarFilter component to represent the chip values for each tag below. If there are 100 tags, we end up with 100 DataToolbarFilter components.

![Screen Shot 2020-02-18 at 10 25 02 AM](https://user-images.githubusercontent.com/17481322/74752263-6a1ca900-523c-11ea-8cec-b38e14c9f4b3.png)

**Comment by dlabrecq** [comment]
A possible workaround is to return null instead of relying on the `showToolbarItem` prop of `DataToolbarFilter`. For example:

![Screen Shot 2020-02-18 at 11 23 23 AM](https://user-images.githubusercontent.com/17481322/74755378-18c2e880-5241-11ea-9492-6da4cab5f0c0.png)

Ideally, the `showToolbarItem` prop would not render the `DataToolbarFilter` Vs only hiding it.

**Comment by dlabrecq** [comment]
Not the best workaround -- will try to find another. We discovered that the "Clear all filters" link will remain after clearing multiple categories.

![Screen Shot 2020-02-20 at 9 15 09 AM](https://user-images.githubusercontent.com/17481322/74941783-a4fc1980-53c1-11ea-82b4-aad9707ea85d.png)

**Comment by redallen** [comment]
#4056 was reverted, reopening

**Comment by redallen** [comment]
#4103 should fix this, closing.
