### ISSUE TITLE
PF4: Master Detail Demo

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#3779]
**Describe the issue. What is the expected and unexpected behavior?**
Add Master Detail Demo
https://github.com/patternfly/patternfly-next/issues/2471

**Comment by nicolethoen** [comment]
@mattnolting @mcarrano When either of you get a moment - I just want to verify the draw is intended to open when the used clicks the secondary button on each row? or something else?

**Comment by mcarrano** [comment]
Good question @nicolethoen . I think that the intent was that the drawer will show details when the user selects a row in the list (i.e. shows details related to that row). So the contents in the drawer should somehow reflect the row that was selected. @lboehling can you verify that this is the design intent? I'm also wondering whether there would always be a default selection or if the user has the option to somehow clear the selection. If the former, then the drawer would always be open. But then what does clicking the close on the drawer do?

**Comment by lboehling** [comment]
@mcarrano @nicolethoen Yes, the drawer would show by clicking on the entire row. The row would then get an active state, and then the details of that row would display in the drawer. If the user clicks close on the drawer, then the row that was selected would be automatically deselected.
