### ISSUE TITLE
Tooltip: position=left has wrong arrow background

### ISSUE THREAD

**Issue by jshaughn** [patternfly/patternfly-react#3808]
When changing from position=top to position=left the arrow background no longer matches the content background.

![image](https://user-images.githubusercontent.com/2104052/74965831-e3a2cb80-53e3-11ea-86a2-41b044e527d8.png)

![image](https://user-images.githubusercontent.com/2104052/74965559-742cdc00-53e3-11ea-93f1-a2247954e5a0.png)

Using:
    "@patternfly/patternfly": "2.44.2",
    "@patternfly/react-charts": "5.2.2",
    "@patternfly/react-core": "3.124.1",
    "@patternfly/react-styles": "3.6.11",
    "@patternfly/react-table": "2.24.41",
    "@patternfly/react-tokens": "2.7.10",

**Comment by tlabaj** [comment]
I am unable to reproduce this in my environment.  Can you please provide step to reproduce or a link to  running example with this error.  Thanks

**Comment by jshaughn** [comment]
@tlabaj Not sure if it's relevant but I noticed that there is a global css override in play, setting z-index for tooltip:

.tooltip {
  z-index: 10 !important;
}
