### ISSUE TITLE
Provide stateful versions of the charts

### ISSUE THREAD

**Issue by jotak** [patternfly/patternfly-react#381]
Hi,
I struggled lately while using LineChart in order to access to the underlying C3 chart object and be able to interact with it (example: show/hide the legend on demand, via calling `chart.legend.show()` and `chart.legend.hide()`).

As far as I know this is currently not possible without some changes either in `patternfly-react` or in `react-c3js`. One option I tried was to use `React.RefObject` in order to access underlying objects, but I got stuck with react not providing this functionality for stateless components such as `LineChart`.

So what do you think about providing a stateful version for every chart component?

Note, another option I investigated is to provide the C3 chart object via hooks from react-c3js, I opened a PR for that: https://github.com/bcbcarl/react-c3js/pull/40

**Comment by jeff-phillips-18** [comment]
I wouldn't mind replacing react-3cjs with our own version. It's not complicated and I believe it would be better to regenerate the chart when the props change (truly change)  rather than require all consumers to handle the onPropsChange themselves.

**Comment by jotak** [comment]
@jeff-phillips-18 I don't know, because regenerating the entire chart can be very time-consuming if all we need is, let's say, show or hide something like the legend. So IMO it's good to call the C3 API directly to perform a single change.

Eventually, the PF charts could make a best effort to handle some common configuration changes, but handling *all* of possible C3 configuration changes in that way seems crazy, so it seems to me legit to allow the user to have access to the chart, no?

**Comment by jeff-phillips-18** [comment]
@jotak Yeah, seems reasonable to me. I thought we could make decisions based on prop changes but you are right, there are too many to try to cover all bases. 

I like the approach of your PR above. Should we create a C3Chart component within PF-React that provides this feature?
