### ISSUE TITLE
Allow components to forward refs

### ISSUE THREAD

**Issue by riccardo-forina** [patternfly/patternfly-react#3827]
I need to pass to some component coming from PF a `ref` to do some analysis of the rendered DOM (getting the component's coordinates and dimensions mostly) but I can't since PF's components aren't wrapped with `forwardRef`. 

To give you an example of what I'm trying to achieve, this code would render two lists inside an `svg` element - the `Canvas` component - and would render the list items with links connecting list items together.

## Working example (using plain html components)

```tsx
<CanvasProvider>
  <Canvas>
    <AutoLinkProvider>
      <HTMLObject width={80} height={250} x={50} y={50}>
          <AutoLinkNode id='a'>
            <ul>
              <AutoLinkNode id='a1'><li>item a1</li></AutoLinkNode>
              <AutoLinkNode id='a2'><li>item a2</li></AutoLinkNode>
              <AutoLinkNode id='a3'><li>item a3</li></AutoLinkNode>
            </ul>
          </AutoLinkNode>
      </HTMLObject>
      <HTMLObject width={80} height={250} x={350} y={50}>
          <AutoLinkNode id='b'>
            <ul>
              <AutoLinkNode id='b1'><li>item b1</li></AutoLinkNode>
              <AutoLinkNode id='b2'><li>item b2</li></AutoLinkNode>
              <AutoLinkNode id='b3'><li>item b3</li></AutoLinkNode>
            </ul>
          </AutoLinkNode>
      </HTMLObject>
      <AutoLink start={'a1'} end={'b3'} />
      <AutoLink start={'a3'} end={'b2'} />
      <AutoLink start={'a2'} end={'b1'} />
    </AutoLinkProvider>
  </Canvas>
</CanvasProvider>
```
_Result: links between nodes are rendered_
![image](https://user-images.githubusercontent.com/966316/75264241-6e723480-57ef-11ea-9b51-007c20c141d0.png)

## Non working example (using PF components)

```tsx
<CanvasProvider height={350}>
  <Canvas>
    <AutoLinkProvider>
      <HTMLObject width={200} height={250} x={50} y={50}>
        <TextContent>
          <AutoLinkNode id='a'>
            <List>
              <AutoLinkNode id='a1'><ListItem>item a1</ListItem></AutoLinkNode>
              <AutoLinkNode id='a2'><ListItem>item a2</ListItem></AutoLinkNode>
              <AutoLinkNode id='a3'><ListItem>item a3</ListItem></AutoLinkNode>
            </List>
          </AutoLinkNode>
        </TextContent>
      </HTMLObject>
      <HTMLObject width={200} height={250} x={350} y={50}>
        <TextContent>
          <AutoLinkNode id='b'>
            <List>
              <AutoLinkNode id='b1'><ListItem>item b1</ListItem></AutoLinkNode>
              <AutoLinkNode id='b2'><ListItem>item b2</ListItem></AutoLinkNode>
              <AutoLinkNode id='b3'><ListItem>item b3</ListItem></AutoLinkNode>
            </List>
          </AutoLinkNode>
        </TextContent>
      </HTMLObject>
      <AutoLink start={'a1'} end={'b3'} />
      <AutoLink start={'a3'} end={'b2'} />
      <AutoLink start={'a2'} end={'b1'} />
    </AutoLinkProvider>
  </Canvas>
</CanvasProvider>
```
_Result: links between nodes are not rendered_
![image](https://user-images.githubusercontent.com/966316/75264535-d58fe900-57ef-11ea-9fd1-c99ace08a488.png)

## Example explanation

Basically the `AutoLineNode` components inject a ref to the children node to then calculate the position of the element relative to the `Canvas`. All positions are then stored into the `AutoLinkProvider` context and used by `AutoLink` components to render svg paths.

When `AutoLineNode` is used to wrap a PF component, React gives you this warning:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

I can in same cases work around the problem by wrapping the PF component with a custom one that's basically just a `div` - or whatever is needed not to break the wrapped component. 
This isn't a real solution tho. For components like `ListItem`, a wrapping component can't be used since `li` items can't be wrapped. I guess that any component that makes use of `flex` for its layout would break too.

## Suggested fix

Wrap all components with `forwardRef` I guess?

---

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

It's an enhancement.

**What is your product and what release version are you targeting?**

Project: [Atlasmap](https://github.com/atlasmap/atlasmap)
Release: fuse-7.7

**Comment by rachael-phillips** [comment]
Hi @riccardo-forina we've seen this, and we'll be looking into this soon. Thank you for opening this!
