### ISSUE TITLE
Modal title and aria-label

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3840]
**Describe the issue. What is the expected and unexpected behavior?**

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://www.patternfly.org/v4/documentation/react/components/modal

Looking at the modal component, I noticed the following:

* The `title` prop value is used to populate the `aria-label`, which seems reasonable.
* If you omit `title`, you end up with an empty `<h1 class="pf-c-title">` element, which doesn't seem ideal from a code perspective, and it breaks the layout by creating extra space at the top of the modal from the empty element.
  * To get the proper layout in a modal without a title, you also have to specify the `hideTitle` prop. That seems unnecessary.
* If you want the modal to have an `aria-label`, but with no visible title, you specify the label in the `title` prop, then use `hideTitle` to remove the title from the page. This is a bit confusing.
* Since the value of `title` is also used as the `aria-label`, the title value needs to be a string type, which may not always be ideal if maybe you wanted to use a `<span>` or `<strong>` element or icon or something like that.

I wonder if it might be better to:

* If you specify a `title`, it generates the title in the markup and assigns the title an `id` that is then used with `aria-labelledby` on the modal. Since the value of the title prop is no longer also used as the `aria-label`, the title would no longer need to be a string.
* If you omit the `title`, it removes the title from the component. No need to do anything else to address the layout.
* Add the ability to specify an `ariaLabel` or `ariaLabelledById` prop (similar to the existing `ariaDescribedById`) that gives the modal a label in the case that 1) there is no `title`, or 2) when used with a `title`, the value they pass would override the `id` the component would normally generate from the title.

**Comment by tlabaj** [comment]
cc @jessiehuff
