### ISSUE TITLE
feat(Table): Disable specific actions in table dropdown

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#3841]
**Describe the issue. What is the expected and unexpected behavior?**
When a Table has actions, those actions can either be completely disabled or removed. But there is no possbility of disabling specific actions within the dropdown for some rows.

If we imagine a row of self and other's configurations, and the user can do actions of Set active, Share, and Delete on those configs. We'd want to disable Delete if the config is not owned by the user.

We can provide an `isDisabled` prop into an action but it will not be aware of the row it's in. An example of how we do onClick and would love to do something similar for `isDisabled`

```javscript
{
  title: 'Delete',
  // isDisabled: , 
  onClick: (_event: unknown, _rowId: unknown, {config}: {config: IUserConfig}) => props.onDelete(config)
}
```

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Feature

**What is your product and what release version are you targeting?**

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@tlabaj This seems like a reasonable ask. Any reason we couldn't do this?

**Comment by QasimRRizvi** [comment]
Any update regarding this feature?

**Comment by QasimRRizvi** [comment]
Need this feature, it's so important in some cases

**Comment by SpyTec** [comment]
@QasimRRizvi it is already possible in some aspects. Instead of using `actions` prop you can use the `actionResolver`. It allows you to dynamically create the actions for each row:

```ts
const actionResolver = useCallback((rowData: IRowData): (IAction | ISeparator)[] => {
  if (rowData.hasOwnProperty('parent')) {
    return null as any; // null means we don't get row action, interpret as any to avoid TS errors
  }
  return [
    {
      title: 'Set Active',
      onClick: (_event: React.MouseEvent, _rowIndex: number, rowData: IRowData) => console.log(rowData),
      isDisabled: !currentUserConfig || currentUserConfig?.owner?.includes(owner.id)
    }
  ]
}, [/* all dependencies */]);
```

**Comment by QasimRRizvi** [comment]
@SpyTec, thanks!
You are right, and I used the same way to disable my action but I think it would be good if we have just a simple way to do it i.e pass `isDisabled` key
