### ISSUE TITLE
Feature Request: Solid Radio Button

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-react#3847]
**Describe the issue. What is the expected and unexpected behavior?**
We have a use case for a variant of the radio button:
* Used to select a single state from multiple options
* Styled as a button

_Screenshot of Ansible Tower_
<img width="494" alt="Screen Shot 2020-02-28 at 5 02 06 PM" src="https://user-images.githubusercontent.com/15881645/75590913-62cf7980-5a4c-11ea-88a8-e8055b30f275.png">

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Feature Request. 
Alternative is to build a custom component. 

**What is your product and what release version are you targeting?**
Ansible Tower

cc @trahman73

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@marshmalien We have an issue in our backlog to create a component called a toogle group. You can see the design here: https://github.com/patternfly/patternfly-next/issues/2625 Would that address your need?

**Comment by marshmalien** [comment]
@mcarrano Yes, that is exactly what we are looking for. Thank you!

**Comment by mcarrano** [comment]
@LHinson do we have https://github.com/patternfly/patternfly/issues/2625 on our roadmap? Implementing that would address this issue.

**Comment by mcarrano** [comment]
This is currently scheduled for core implementation in our 2020.08 milestone.

**Comment by tlabaj** [comment]
closed by #4702
