### ISSUE TITLE
PF4 Switch: label does not accept React.node

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#3850]
If react node is passed as a label to Switch component, you will get an invalid prop type error, even though the label gets rendered:
```jsx
/**
* outputs error
*/
<Switch label={<span>Hello<span>} ... />


/**
* no error
*/
<Switch label="Hello" ... />
```

Is it possible to allow Reat.node as a valid prop type?

**Comment by karelhala** [comment]
ping @tlabaj can you look at this and prioritize it?

**Comment by dgutride** [comment]
@wojta  - here's a good one to start with (just to get the repo going)

**Comment by wojta** [comment]
ack
