### ISSUE TITLE
Compile error when adding patternfly/react-charts

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-react#3862]
**Describe the issue. What is the expected and unexpected behavior?**

I'm working on migrating a donut chart from `patternfly-react` to `@patternfly/react-charts`.  I've added the latest version of react-charts to my project and migrated the code, however I get a build error in an unrelated component from react-charts:

![image](https://user-images.githubusercontent.com/351660/75784314-07450a80-5d30-11ea-92c7-314dc1803ba2.png)

I had actually done this work initially earlier this month against version 5.2.21 and it compiled fine at that point, however as of yesterday building against either that old version or the latest/prelease fails with this compile error.

The changes made are [here](https://github.com/syndesisio/syndesis/pull/8003/files) and full compile output is [here](https://app.circleci.com/jobs/github/syndesisio/syndesis/273900/parallel-runs/0/steps/0-105), any pointers would be appreciated!

**Comment by gashcrumb** [comment]
@seanforyou23 hey, does this ring any bells?

**Comment by tlabaj** [comment]
cc @dlabrecq

**Comment by dlabrecq** [comment]
I'm not able to reproduce this in Cost Management with the latest packages; however, I'm not setup to use rollup. Note that PatternFly installed Victory 33.1.7, while Cost Management is referencing 33.0.5 interfaces.

![Screen Shot 2020-03-10 at 9 36 06 AM](https://user-images.githubusercontent.com/17481322/76317533-b6df2700-62b2-11ea-9c3a-c1f8aa295b7b.png)

That said, I suspect there could be an issue related to the linting changes recently introduced? The PRs below are the only recent changes to the `ChartScatter` component.

- Remove PF3 packages #3852 3/3/20
- Fixed linting errors #3713 2/14/20 

FYI @evwilkin

**Comment by redallen** [comment]
This looks like something up my alley since I'm working on #3836 and have a decent amount of rollup experience. I'll checkout `syndesis` sometime today.

**Comment by gashcrumb** [comment]
Appreciate a second pair of eyes on this one!  Really odd since it was fine when I initially migrated this component.  For unrelated reasons I wound up parking it on a branch for a month while migrating the rest of the app, so was surprised when this failed to build.

**Comment by gashcrumb** [comment]
Well, I've taken that branch; rebased it on all my work removing `patternfly-react` and have been able to get it to build now.  Can't point to any definitive root cause but it does mean I'm unstuck, so I'd be fine with closing this issue.

**Comment by redallen** [comment]
That's an awesome report @gashcrumb ! Feel free to reopen if you have further problems.
