### ISSUE TITLE
Enhancement - Need a more involved Radio example

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-react#3869]
**Describe the issue. What is the expected and unexpected behavior?**

The [current examples](https://www.patternfly.org/v4/documentation/react/components/radio) for the Radio component are great, however they're all kinda simple.  And the [page on the Form component]() doesn't include an example with a Radio component either.

For example, how would this form be composed, where I have additional controls that the radio buttons enable:

![image](https://user-images.githubusercontent.com/351660/75909037-4733ec80-5e19-11ea-9662-fd8ded188293.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This would be an enhancement

**What is your product and what release version are you targeting?**
This is for Fuse Online's next release.

@seanforyou23 :wink:

**Comment by gashcrumb** [comment]
I came up with [this](https://github.com/syndesisio/syndesis/pull/8042/files#diff-c2a2ce7c3b4882543ac0d9693dbc56d2R153) for the time being, however I'm kinda faking the radio control semantics via putting an onClick handler on the containing `Split` component.

**Comment by tlabaj** [comment]
@mcarrano @mcoker perhaps we should add a more involved Form Demo.

**Comment by mcarrano** [comment]
We have had an issue in the backlog for a while to provide more robust examples of form layout: https://github.com/patternfly/patternfly-next/issues/919 Not sure where this lives on our roadmap. @LHinson ?

**Comment by mcoker** [comment]
Hey @gashcrumb! @mcarrano If this is a common enough pattern, for radios and checkboxes to have some sort of disclosure, and the disclosure content aligns in the grid with the checkbox/radio label, that's something we could also build into that component positioned similar to the existing "description", something like: https://codepen.io/mcoker/pen/gOpXWgM

If the radio could disclose something in a separate form group, here's a demo of how that could be done now: https://codepen.io/mcoker/pen/GRJOmyj

**Comment by gashcrumb** [comment]
@mcoker cool!  It's ever so slightly different from the use case I have to implement, in my case the form fields are there and visible but disabled unless the radio item is selected.

Do radio buttons support a `description` property in the react implementation?  If so, awesome!  And it'd be good if there was an example showing that.

**Comment by mcoker** [comment]
@gashcrumb yep! https://www.patternfly.org/v4/documentation/react/components/radio#with-description

Though it's worth noting that `description` is to provide the "description," so we may make changes to the way that's presented that might conflict with a custom use of that property.
