### ISSUE TITLE
Empty state sizing is inconsistent with other components

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-react#3873]
**Describe the issue. What is the expected and unexpected behavior?**
Other PatternFly components use a convention of "xs," "sm," "md," etc. Empty state has these values spelled out in full, i.e. "large."

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug. It's not a blocker, but it would be great if this could be made consistent in a future breaking changes release.

**Comment by dlabrecq** [comment]
Looking at the 'full' variant and it appears be an empty string. Perhaps it could be 'xxl', or possibly omitted?

**Comment by tlabaj** [comment]
closed by  #3933
