### ISSUE TITLE
Can't use Text component

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-react#3878]
@SS-TT commented on [Thu Mar 05 2020](https://github.com/patternfly/patternfly-next/issues/2778)

Hi there,
I just pasted the `Text` sample in one of my components, but I can't get it to work.

Here's what I'm rendering:

```tsx
<TextContent>
  <Text component={TextVariants.h1}>Hello World</Text>
  <Text component={TextVariants.h2}>Second level</Text>
  <Text component={TextVariants.h3}>Third level</Text>
  <Text component={TextVariants.h4}>Fourth level</Text>
  <Text component={TextVariants.h5}>Fifth level</Text>
  <Text component={TextVariants.h6}>Sixth level</Text>
</TextContent>
```

Launching `yarn build` doesn't cause any issue, but as long as I navigate to that page, I get a blank page.
Hovering on my `Text` components shows this message:

> JSX element type 'Text' is not a constructor function for JSX elements.
  Type 'Text' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.ts(2605)
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)

I'm quite new to React, so sorry if this is a stupid issue/question, but I find it odd that I'm having issues with one of the simplest components out there while I could setup a complex `Wizard` with no problems at all.

Thanks.

**Comment by dlabaj** [comment]
@mattnolting do you have your code somewhere that I could look at?

**Comment by SS-TT** [comment]
Just paste the one in the OP in the `Dashboard.tsx` file in the [seed project](https://github.com/patternfly/patternfly-react-seed).

I know that's outside this issue's scope, but using the seed I can't even use `Spinner` nor `DataToolbar`.
I ran `yarn upgrade` to see if it was related to package version but nothing changed.

**Comment by michpetrov** [comment]
@SS-TT are you importing `Text`? [Text](https://developer.mozilla.org/en-US/docs/Web/API/Text) is a native interface so if you're not importing it the app might be trying to use this one instead.

**Comment by SS-TT** [comment]
I thought it was something else as I'm having issues with more components, thanks for your help.

**Comment by tlabaj** [comment]
@SS-TT are you still have an issue?  If not, can we close this?

**Comment by tlabaj** [comment]
Closing this one.  If you are still having issues please reopen.
