### ISSUE TITLE
TextInput: Props are not displayed in the workspace docs. 

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#3885]
**Describe the issue. What is the expected and unexpected behavior?**
The props for the TextInput are missing form the workspace docs.

**Comment by mturley** [comment]
+1, noticed this as well. Probably related to the fact that it is exported as a forwardRef component.

**Comment by jenny-s51** [comment]
Closing as this was fixed by @ddonahue007 in https://github.com/patternfly/patternfly-react/pull/4249. See https://patternfly-react.surge.sh/documentation/react/components/textinput#props
