### ISSUE TITLE
SelectOptionObject does not show checked items for Select component

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#3899]
Currently the SelectOptionObject does not show the checked items when used with a checked variant of Select.  A work around for now is to map the select object to strings which will allow it to be displayed as checked with in the Select check variant.

The code here:

https://github.com/patternfly/patternfly-react/blob/4abb5b6e766ff1c669423dcb7cafc29fe4b02464/packages/react-core/src/components/Select/SelectMenu.tsx#L106

and here:

https://github.com/patternfly/patternfly-react/blob/4abb5b6e766ff1c669423dcb7cafc29fe4b02464/packages/react-core/src/components/Select/SelectMenu.tsx#L119

Should be updated to support SelectOptionObjects.

**Comment by dlabaj** [comment]
Closing issue after looking at code.

**Comment by kmcfaul** [comment]
@nicolethoen The workaround is to use strings for `value`, mentioned at the top. For customized display, the `children` property of SelectOption may be used instead of SelectOptionObject's toString function.

**Comment by dlabrecq** [comment]
The `SelectOptionObject` now displays the checked items, but shows the wrong total checked items. In the example below, only one item has been selected, but the `Select` component shows 9 as the count.

See https://github.com/patternfly/patternfly-react/issues/4478
