### ISSUE TITLE
Errors in webpack dev mode with ouia 

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#3901]
**Describe the issue. What is the expected and unexpected behavior?**

Seeing errors in the console while in dev mode

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Can be seen in latest PF seed master branch, seems to be related to the dynamicimport component's loading state.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Looks like a bug

**What is your product and what release version are you targeting?**

PF seed getting started project

<img width="828" alt="Screen Shot 2020-03-06 at 9 31 00 AM" src="https://user-images.githubusercontent.com/5942899/76418077-63351200-6374-11ea-85ec-ef36a1a2f90f.png">

**Comment by redallen** [comment]
Should be fine on `v4` after #3927. Can you reproduce this using a `v4` prerelease?

**Comment by seanforyou23** [comment]
_latest_ v4 prerelease seems to have it fixed, feel free to add this issue to what that work closes

**Comment by seanforyou23** [comment]
Closed with https://github.com/patternfly/patternfly-react/pull/3927
