### ISSUE TITLE
PageHeader -> logoComponent properties cannot be set to Link

### ISSUE THREAD

**Issue by Andrei-Stepanov** [patternfly/patternfly-react#3902]
Hello,

I am trying to have a PageHeader with logo that is clickable with <Link/> that react application is not going to reload completely.

https://www.patternfly.org/v4/documentation/react/components/page#props
Says:
`logoComponent | React.ReactNode | No | 'a' | Component to use to wrap the passed <logo>
`

When I have:

`logoComponent={Link}` then browser complains with:

`index.js:1 Warning: Failed prop type: Invalid prop `logoComponent` supplied to `PageHeader`, expected a ReactNode.
    in PageHeader (at MainPage.js:114)
    in MainPage (created by Context.Consumer)
    in withRouter(MainPage) (at App.js:14)
    in Page (created by Context.Consumer)
    in Route (at App.js:23)
    in Switch (at App.js:21)
    in Router (created by HashRouter)
    in HashRouter (at App.js:20)
    in div (at App.js:19)
    in App (at src/index.js:10)
    in Provider (at src/index.js:9)`

`logoComponent='Link'` also doesn't work
`logoComponent={<Link/>}'` also doesn't work

Is there way to create a clickable logo and without app reload?
    "@patternfly/react-core": "^3.140.11",
Thank you.

**Comment by jschuler** [comment]
If programmatically possible, you could try to pass something like `logoProps={{ onClick: () => console.log('clicked') }}`. and logoProps are forwarded to the Logo container.
Also should be possible:
```
<PageHeader
  logoComponent="div"
  logo={<Link>My router link</Link>}
/>

**Comment by jschuler** [comment]
logoComponent can also be valid HTML elements I believe

**Comment by Andrei-Stepanov** [comment]
@jschuler thank you! The ticket can be closed.
