### ISSUE TITLE
Dropdown: Kebab size is different between pf react and pf html

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#3905]
**Describe the issue. What is the expected and unexpected behavior?**
Kebab size for a pf-react dropdown kebab is 28, vs 36 in pf html components
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See both sets of examples.
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by jschuler** [comment]
Looks like in core the `<i>` tag gets line-height 1.5 from this rule:
```
.pf-c-dropdown__toggle.pf-m-plain>* {
  line-height: var(--pf-c-dropdown__toggle--LineHeight)
}
```

In react instead of an `<i>` we use `<svg>`. And even though the same css rule exists there, line-height does not appear to affect the svg element
