### ISSUE TITLE
Donut Chart generates extra white space between colors

### ISSUE THREAD

**Issue by carlosthe19916** [patternfly/patternfly-react#3907]
When there are data and one of the values is 0 then extra white space is generated

Steps to reproduce it:
- Enter to https://www.patternfly.org/v4/documentation/react/charts/chartdonut#basic
- Using the JSX editor change one of the `Y` values to `0` (see screenshot) and then change the other `Y` values in a way that one is much greater than the other (let's say 90 and 10)
- You will see that the donut chart generated creates extra white space between colors.

![Screenshot from 2020-03-12 12-05-17](https://user-images.githubusercontent.com/2582866/76536517-be522c00-647c-11ea-88b3-3b2ffe0faec0.png)

I know this is a very simple detail but fixing this will make the donut chart look better

**Comment by tlabaj** [comment]
cc @dlabrecq

**Comment by dlabrecq** [comment]
I don't believe there is much we can do here, given the underlying component is a Victory pie chart. To achieve the look of spacing, we use the pie chart's `padAngle` prop. This prop is applied to all segments of the pie -- there is no individual padding between data segments.

This can be best seen with the [pie chart examples](https://patternfly-react.surge.sh/documentation/react/charts/chartpie). For example, apply `padAngle={2}`, padAngle={6}, etc. to any pie chart which will demo how spacing is applied to all segments.

**Comment by dlabrecq** [comment]
I don't believe there is much we can do here, given the underlying component is a Victory pie chart. That is, except perhaps remove the data from the chart?

To achieve the look of spacing, we use the pie chart's `padAngle` prop. This prop is applied to all segments of the pie -- there is no individual padding between data segments.

This can be best seen with the [pie chart examples](https://patternfly-react.surge.sh/documentation/react/charts/chartpie). For example, apply `padAngle={2}`, padAngle={6}, etc. to any pie chart which will demo how spacing is applied to all segments.

![Screen Shot 2020-03-13 at 9 13 01 AM](https://user-images.githubusercontent.com/17481322/76624007-dbcdd700-650a-11ea-9e1a-16fbb4a798b4.png)

**Comment by carlosthe19916** [comment]
Thanks @tlabaj and @dlabrecq for the quick answer. I think the only option, for now, is to remove the data which contains `0`.

However, removing data whose values are `0` might cause this kind of problems (see the image below):

- If I use the default colors for charts and remove the data `0` then the colors for some legends will change. In the example below the legend `Unsupported` change from Orange to Gray

![donut_chart_remove_cero_values](https://user-images.githubusercontent.com/2582866/76641397-d21b9200-6551-11ea-81bb-c06bd81dca05.png)

**Comment by dlabrecq** [comment]
True. Victory iterates over color scales to apply a color to each data segment. You could provide your own color scale for the pie and/or legend, but probably not worth the effort to sync.
