### ISSUE TITLE
Add the component name/page heading to the page title in the reference documentation

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-react#3911]
**Describe the issue. What is the expected and unexpected behavior?**
The patternfly 4 reference site only uses the text "Patternfly 4" for the page title, so every browser history entry simply has this text.  For example I've clicked through a few React component pages and look at the browser history:

![image](https://user-images.githubusercontent.com/351660/76646646-b2747180-6531-11ea-9bf3-d0eb01a62080.png)

I've no idea which entry is whatever page I've looked at.  And I've another tab open to look up icons, which also has the same page title, so I can never tell which page is which at a glance.

**Comment by kahboom** [comment]
+1 this would be a huge help, especially if you have a bunch of tabs open at once and use a tab/session manager

**Comment by seanforyou23** [comment]
I think this is now fixed with https://github.com/patternfly/patternfly-org/pull/1707 - feel free to reopen if I missed anything!
