### ISSUE TITLE
Feat: Select selections prop could be replaced with a type definition

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-react#3931]
`Select`'s [`selections`](https://github.com/patternfly/patternfly-react/blob/cf3559ee61fff0c1b679743a17e4521011fc7651/packages/react-core/src/components/Select/Select.tsx#L46) is able to take in multiple different prop types, namely `string | SelectOptionObject | (string | SelectOptionObject)[]`

If we were to change this to 

```ts
export type SelectionsType = string | SelectOptionObject | (string | SelectOptionObject)[];
export interface SelectProps {
  // ...
  /** Selected item for single select variant.  Array of selected items for multi select variants. */
  selections?: SelectionsType;
}
```
I would be able to simply define my selections variable in my code as follows which makes it much easier to read.
```ts
const selections: SelectionsType = "some selection"
<Select
  selections={selections}
/>
```

**Comment by tlabaj** [comment]
cc @kmcfaul

**Comment by SpyTec** [comment]
Closing as this will be reduced in #3734

**Comment by tlabaj** [comment]
#3734 is being rolled back so I am reopening this issue.
