### ISSUE TITLE
Bulk selection demo not showing the mixed selection state

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#3935]
The Bulk Select Table demo (https://www.patternfly.org/v4/documentation/react/demos/bulkselecttable) does not show a mixed state checkbox when there is partial selection. The design guideline here shows how this should work: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/bulk-selection

I see the same problem in the new Card View demo. Seems like this used to work correctly so I'm assuming a bug got introduced in a recent release.

**Comment by tlabaj** [comment]
@mcarrano I believe this is a duplicate of issue 
#3648

**Comment by mcarrano** [comment]
It's definitely a similar issue. Probably has the same root cause. I'll let you decide whether to close @tlabaj
