### ISSUE TITLE
Handle numbers when they are passed using toLocaleString function or provide a prop to format displayed numbers

### ISSUE THREAD

**Issue by vrathee** [patternfly/patternfly-react#3939]
**Describe the issue. What is the expected and unexpected behavior?**

The Pagination component 
```
<Pagination
      itemCount={props.itemCount}
      widgetId="pagination-options-menu-top"
      perPage={perPage}
      page={currentPage}
      variant={PaginationVariant.bottom}
      onSetPage={onSetPage}
      onPerPageSelect={onPerPageSelect}
    />
```

If I try to pass the itemCount as `itemCount={props.itemCount.toLocaleString()}` to display large numbers in human readable format, it shows the number correctly at one place but shows `NaN` at the second place.
It's understandable as the toLocaleString converted it to string and component is not able to handle it However, it would be great if it can handle that.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Not blocking but there is no workaround either.

**Comment by vrathee** [comment]
@tlabaj if this is accepted, I can work on an MR for this one.

**Comment by tlabaj** [comment]
@vrathee are you still interested in working on this one?

**Comment by vrathee** [comment]
@tlabaj Yes, I can send a MR.
