### ISSUE TITLE
Select/context selector - update search box element name

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3948]
https://github.com/patternfly/patternfly/pull/2826

* `.pf-c-context-selector__menu-input` changed to `.pf-c-context-selector__menu-search`
* `.pf-c-select__menu-input` changed to `.pf-c-select__menu-search`

**Comment by jessiehuff** [comment]
Duplicate issue as https://github.com/patternfly/patternfly-react/issues/3675
