### ISSUE TITLE
Review current react i18n libraries and recommend strategy for localization

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#3952]
**Describe the issue. What is the expected and unexpected behavior?**

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by evwilkin** [comment]
Goal: provide a recommendation strategy for localization that can be incorporated into OpenShift

Options:
- `react-intl` (Insights uses this lightly)
- `react-i18n`
- Any other solutions we identify
- Cost management has a solution in place, need to identify what they are using

**Comment by jschuler** [comment]
**.Will edit this comment as I learn more **
---
# Internationalization (i18n) / Localization (l10n)

[Dependencies used amongst products](https://github.com/rh-uxd/patternfly-analytics/blob/master/stats-static/2020-04-13/_all_dependencies.json)

## All found i18n libs

- react-intl
0: Foreman-Console
1: Foreman-Tasks
2: Insights-Compliance
3: Insights-Dashboard
4: Insights-Vulnerability
5: Product-Shared-Library
6: Product-Shared-Library
7: RHEL-Composer
8: Settings-Catalog
9: Settings-RBAC
10: Settings-Sources
11: Virtualization-Frontend

- react-intl-po
0: RHEL-Composer
1: Virtualization-Frontend

- babel-plugin-react-intl
0: Insights-Dashboard
1: Product-Shared-Library
2: Product-Shared-Library
3: RHEL-Composer

- babel-plugin-react-intl-auto
0: RHEL-Composer

- i18next
0: 3Scale
1: Cost-Management
2: Fuse-Online
3: Insights-Curiosity
4: Integreatly

- i18next-browser-languagedetector
0: 3Scale
1: Fuse-Online

- i18next-express-middleware
0:Cost-Management

- i18next-json-sync
0: Cost-Management
1: Integreatly

- i18next-xhr-backend
0: Cost-Management
1: Insights-Curiosity
2: Integreatly

- react-i18next
0: 3Scale
1: Cost-Management
2: Fuse-Online
3: Insights-Curiosity
4: Integreatly

## Overall

| react-intl | i18next |
|--|--|
| [Foreman (Console/Tasks)](https://github.com/theforeman/foreman) | [3scale](https://github.com/3scale) |
| [Insights (Compliance/Dashboard/Vulnerability)](https://github.com/RedHatInsights) | [Koku (Cost-Management)](https://github.com/project-koku/koku-ui) |
| [Cockpit (incl. Composer)](https://github.com/cockpit-project/cockpit) | [Fuse-Online](https://github.com/syndesisio/syndesis) |
| [oVirt](https://github.com/oVirt/ovirt-web-ui) | [Insights-Curiosity](https://github.com/RedHatInsights/curiosity-frontend) |
|  | [Integreatly](https://github.com/integr8ly/tutorial-web-app) |

Comparison
[Library comparisons react-i18next vs react-intl](https://www.npmtrends.com/react-i18next-vs-react-intl)

## react-intl
### Features

-   Display numbers with separators.
-   Display dates and times correctly.
-   Display dates relative to "now".
-   Pluralize labels in strings.
-   Support for 150+ languages.
-   Runs in the browser and Node.js.
-   Built on standards.

### Example that integrates react-intl into patternfly-react-seed
https://github.com/jschuler/patternfly-react-seed/pull/1
Viewable example: http://pf-seed-react-intl.surge.sh/support

**Comment by jschuler** [comment]
i18n libraries have been reviewed, and a PR was created for OpenShift following the findings.

**Comment by jschuler** [comment]
## (WIP) Koku (Cost Management) 
Koku uses i18next. An investigation was done to see what it would take to convert it over to react-intl, and to explore further what the advantages/disadvantages of react-intl are.

The PR (WIP) is here [https://github.com/jschuler/koku-ui/pull/1](https://github.com/jschuler/koku-ui/pull/1)
