### ISSUE TITLE
tab key navigation of Tabs does not fully reveal Tab button

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#3957]
**Describe the issue. What is the expected and unexpected behavior?**
If there are more Tabs to display then there is available space, these arrow buttons appear on either end of the tab bar. When using the `tab` key to navigate through the Tab component, the focused tab is scrolled to however it doesn't always become fully visible. In some cases it jumps to the middle but other times it remains partially hidden by the arrow buttons on the end.

![tab-nav](https://user-images.githubusercontent.com/14068621/77345744-75676680-6d0b-11ea-87dd-d0305a1900c4.gif)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Reproducible using the `Scroll buttons primary` example here:
https://www.patternfly.org/v4/documentation/react/components/tabs

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**Comment by tlabaj** [comment]
@christianvogt Tabs are currently being refactored and will address this issue.  Her is the related issue #3951

**Comment by tlabaj** [comment]
closed by #4146
