### ISSUE TITLE
Sortable table columns don't allow for interactive children

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-react#3969]
**Describe the issue. What is the expected and unexpected behavior?**
Sortable table columns don't support children with popovers and tooltips.

We're looking to add an icon with a popover to a sortable table header cell:
<img width="592" alt="Screen Shot 2020-03-24 at 4 50 30 PM" src="https://user-images.githubusercontent.com/7014965/77475710-9903dd00-6def-11ea-9ab9-871e1a24a806.png">

Sortable header cells currently wrap children in a button. Tooltips and popovers don't play well with this (it breaks their behavior).

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug.

**What is your product and what release version are you targeting?**
A design was proposed for OpenShift that requires this functionality.

**Comment by mcarrano** [comment]
@rebeccaalpert I don't know that I'd call this a bug. It was never intended to work this way by design. @mcoker what would it take to do something like this? Would we require a core change to separate the sort and the info icon into separate button actions?

**Comment by mcoker** [comment]
ping @mceledonia we were chatting about this recently and he was investigating the design.

**Comment by rachael-phillips** [comment]
Hey @rebeccaalpert and @mcoker what is the status of this issue? https://github.com/patternfly/patternfly-react/issues/3969

**Comment by rebeccaalpert** [comment]
@rachael-phillips I haven't heard anything since @mcoker's comment 25 days ago.

**Comment by mceledonia** [comment]
I remember discussing this and we got stuck on refactoring the structure of the table headers to accommodate this. If this isn't something we want to natively support (@mcarrano) we should probably recommend an alternate solution like an override or perhaps a design workaround like having the whole button always trigger the tooltip on hover.

**Comment by rebeccaalpert** [comment]
It looks like this has been added to Core and can be brought into React: https://github.com/patternfly/patternfly/pull/3189

**Comment by rebeccaalpert** [comment]
This is going to require some modification to the way the table processes transforms (sort, etc.) for the sort-with-help case. I took a look at it on Friday with Nicole, but may not have time to take another look this week.
