### ISSUE TITLE
ModalBox

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#398]
Add the pf4 alert component for react: https://pf-next.com/components/ModalBox/examples/

**Comment by jgiardino** [comment]
For keyboard interaction, let's follow what's recommended in the authoring practice guide for modal dialogs: https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

This section also includes a note about where to place focus (it has the green background).

**Comment by dmiller9911** [comment]
Side nite. We will want to make sure we test these scenarios with unit tests.
