### ISSUE TITLE
Set goals for integration suite

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#3980]
Right now [we require contributors write demos in TSX in our integration suite](https://github.com/patternfly/patternfly-react/blob/master/packages/react-integration/README.md) for typechecking purposes. These demos are often copied from MD files, types added haphazardly, and many are out of date from the MD files.

We should set goals for what we want this integration suite to accomplish. Some possible goals are:
- Typechecking published examples outside of what `ts-jest` could
- Interaction testing complex interactions outside of what Jest can
- Only requiring a single set of Typescript demos rather than the 2 sets we have now
  - Contributors only have to write their demo _once._
  - Examples are documented in Typescript for our increasing number of Typescript consumers.
- Verifying react-inline-edit-extension, react-topology, and react-virtualized-extension per https://github.com/patternfly/patternfly-react/pull/4073#pullrequestreview-393141638

**Comment by seanforyou23** [comment]
Type checking the exported components 👍
Interaction testing complex interactions 👍

About using react-integration src as a single source of truth, I'd like to open up a discussion about it. I've always seen a lot of value in having two workspaces that each serve different purposes. We need the main one like we have today, which shows the main examples in their best form, those examples are curated and optimized by the whole team with special care and they only show a subset of the functionality. These represent the "blessed" interaction patterns as described in the usage and behavior guidelines (or something along these lines).

That's when this second workspace comes into play. We need a place where we can verify things like complex customizations of the components, case-specific usages, all possible variations of a prop, etc. Those are often things we don't necessarily want to show from the main docs and it affords us more flexibility around the types of demos we can create without having to run each one through a whole design process.

One way this could fit in incrementally is that the TypeScript examples could then be exposed in the docs in some way where the JavaScript examples are. Maybe we could formalize how the TS demos are formatted/added and simply link to them from the main docs (leaving JS as the primary example snippets). I can see how publishing the react-integration build would be helpful for a lot of reasons. Thoughts?
