### ISSUE TITLE
Drawer panel is missing support for pf-m-no-border modifier

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#3983]
**Describe the issue. What is the expected and unexpected behavior?**
Expect to be able to set a prop so that pf-m-no-border modifier class is applied to the drawer panel

**Comment by jenny-s51** [comment]
Is there any work left to do here? Looks like this was addressed in #4036 🙂

**Comment by tlabaj** [comment]
@jenny-s51 that is correct.
closed by #4036
