### ISSUE TITLE
Drawer panel updates

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-react#3984]
- https://www.patternfly.org/v4/documentation/react/components/drawer#static-drawer has `hidden="" aria-hidden="true" aria-expanded="false"` set by default

- `pf-c-drawer__panel` only needs to toggle `hidden` attribute. `aria-hidden="true" aria-expanded="false"` can be removed

**Comment by boaz0** [comment]
@tlabaj can I work on it?

**Comment by tlabaj** [comment]
@boaz.  Sure!  Please do the work on the master.
