### ISSUE TITLE
Drawer - remove ability to add a border to panel

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#3988]
In https://github.com/patternfly/patternfly/pull/2887/ we removed the `.pf-m-border` variation. All non-inline/static drawers where the panel overlays the content should have a drop shadow. All inline/static drawer panels should have a border. Either the shadow or border can be removed with `.pf-m-no-border`, but there is already an issue to handle that - https://github.com/patternfly/patternfly-react/issues/3983

**Comment by tlabaj** [comment]
@mcoker. is this a breaking change?  The drawer is still beta?  Should this not go in master?

**Comment by mcoker** [comment]
Ah good point, I forgot drawer is beta. That works for me.

**Comment by tlabaj** [comment]
Looks like core work was done on v4.  So we will do the work on v4 as well.
