### ISSUE TITLE
Switch Component should fire change event without id attribute

### ISSUE THREAD

**Issue by Christopher-Chianelli** [patternfly/patternfly-react#3992]
Currently, if a Switch Component does not have an id attribute, the `onChange` handler is not fired. This breaks previous behaviour, where the `onChange` handler is fired regardless of having an id attribute or not.

**Comment by redallen** [comment]
I'm unable to reproduce this. In the following code example our Switch currently prints "change" every time it is clicked.
```jsx
import React from "react";
import { Switch } from "@patternfly/react-core";

class SimpleSwitch extends React.Component {
  constructor(props) {
    super(props);
    this.handleChange = isChecked => {
      console.log("change");
    };
  }

  render() {
    return <Switch onChange={this.handleChange} />;
  }
}
```

Can you please provide a [codesandbox](https://codesandbox.io/s/optimistic-raman-hkckg) or something similar with how to reproduce this?

**Comment by Christopher-Chianelli** [comment]
Look like the issue is fixed; it was last present in "3.134.2" (https://codesandbox.io/s/vibrant-hawking-ho8yv?file=/index.js)

**Comment by Christopher-Chianelli** [comment]
@redallen ^

**Comment by redallen** [comment]
Thanks @Christopher-Chianelli ! Glad it's fixed 🔧  .
