### ISSUE TITLE
DropdownToggleCheckbox - checkbox does not show indeterminate state

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#3994]
**Describe the issue. What is the expected and unexpected behavior?**
When isChecked or checked is null, an indeterminate state should show in the checkbox.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by tlabaj** [comment]
close by #3990
