### ISSUE TITLE
patternfly-react has dev build errors on Windows

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#3997]
Repo cannot build successfully out of the box when built in VSCode with Windows OS. 

@redallen 
What I've noticed so far:
- Some single quotes have to be changed into escaped double quotes in the package.json of react-catalog-view-extension and react-table.
- `generateClasses.js` in react-styles outputs to dist incorrectly on Windows due to path slash differences (failing to remove the extra src/css)
- The project level `./node_modules/.bin/gatsby.js` reference in the package.json of react-docs had to be changed to point directly at the top node_modules. Unsure if this is an error or just my environment not picking up the sym link.

**Comment by redallen** [comment]
This is something I'm willing to do after https://github.com/patternfly/patternfly-react/issues/3972 . I'd like to properly support Windows and it should only take about a day since I've done work on Windows support in the past.
