### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#4]
## Contribution Guidelines
In Patternfly, we adhere to the [Contributor Covenant Code of Conduct](http://contributor-covenant.org/). We also use the Apache 2.0 license (see [LICENSE.txt](https://github.com/patternfly/patternfly/blob/master/LICENSE.txt)). We also have HTML/CSS [guidelines](http://codeguide.patternfly.org/) along with an [eslint.yaml](https://github.com/patternfly/patternfly/blob/master/eslint.yaml) which contains our JS lint standards. Our Pull Request template lives [here](https://github.com/patternfly/patternfly/blob/master/.github/PULL_REQUEST_TEMPLATE.md). What sort of contribution guidelines would you like to adhere to? What lint standards would you like to see in this project?  What kinds of things should we point out in our PR template for new contributions?

**Comment by jtomasek** [comment]
IMHO we should adhere to industry standards in terms of linting as much as possible. There are several respected style guides available:
http://standardjs.com/ - oppinionated style guide
https://github.com/airbnb/javascript - Airbnb style guide
https://github.com/facebookincubator/create-react-app/tree/master/packages/eslint-config-react-app - create-react-app eslint config

Personally I quite like standardjs although we'd need to test it if it matches our needs as it does not allow any configuration changes.

In TripleO-UI we use slightly modified version of Airbnb eslint config https://github.com/openstack/tripleo-ui/blob/master/.eslintrc

**Comment by gregsheremeta** [comment]
We follow standardjs in oVirt projects.

**Comment by priley86** [comment]
+1 to standardjs. I'm ok with this linter.
