### ISSUE TITLE
Table inline edit - dropdown

### ISSUE THREAD

**Issue by vconzola** [patternfly/patternfly-react#4003]
There is a need in the OpenShift migration UI to be able to change the storage class of a given persistent volume (PV) within a table row. In the current implementation a dropdown (I guess technically, it's a PF select component.) with all of the available storage class options is displayed in each table row. See below.
![Screen Shot 2020-03-30 at 4 23 01 PM](https://user-images.githubusercontent.com/22823035/77958833-a9aacc00-72a3-11ea-9996-d96cc6746e77.png)
This is problematic because a "preferred" storage class is selected by default for each PV and we really don't want users messing with the selection unless they're sure they know what they're doing. A better design would be to display the "preferred" selection as text with the user having the option to edit it.

**Comment by mcarrano** [comment]
Adding this to React backlog to be added to the roadmap. No design or core work should be required. @vconzola do you have a timeframe when this is needed?

cc @LHinson @tlabaj

**Comment by vconzola** [comment]
@mcarrano We have the work around I described above implemented today, so no urgency. But sometime in the next few months would be great.
