### ISSUE TITLE
Cursor in table actions is no correct

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#4005]
**Describe the issue. What is the expected and unexpected behavior?**
When hovering over action item in table cursor is not correct, it shows `text` variant instead of `pointer`
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Any version, PF react demo page.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

* bug - kinda blocking, it's not user friendly to show this type of cursor

**What is your product and what release version are you targeting?**

* cloud services - the sooner the better

**Comment by seanforyou23** [comment]
Hi @karelhala - having a little trouble reproducing this. Can you help me understand the environment a little better? What browser/platform combo are you seeing this on? I don't see it on the [docs site](https://www.patternfly.org/v4/documentation/react/components/table#simple-actions) or when running latest master locally. Thanks!

**Comment by karelhala** [comment]
If you click on the 3 dots representing the action and hover over the `Some action` text you'll see differet cursor than what you can see in regular dropdown.

**Comment by seanforyou23** [comment]
Ah, I see what you mean now. Thanks - taking a look!
