### ISSUE TITLE
CompoundLabel

### ISSUE THREAD

**Issue by PanSpagetka** [patternfly/patternfly-react#401]
Implement `CompoundLabel` component which will be used in http://www.patternfly.org/pattern-library/forms-and-controls/filter/#overview and #351 

## Input props:

| Name        | Type           | Description  |
| ------------- | ------------- | ----- |
| onDeleteClick     | function | Function which is called when `X` button is pressed |
| category      | object      |  Object with this shape { id: any,  label: string } |
| values      | arrayOf(Value)      | Array of Objects with this shape [{ id: any,  label: string }] |
| Value | object     |    id: any,  label: string |
| categoryTruncate     | function | Function which is used for truncating `Key` string |
| valueTruncate     | function | Function which is used for truncating each `Value` string  |

## Properties
- When there are multiple `Values`, they should be alphabetically sorted.
- Each element (Key or Value) has it's own tooltip with non truncated label string.
- When click on `X` respectable value is deleted (NOT implemented in this component)
- Default truncate function is set for 18 characters and three dots `.` so 21 characters in total max.

## This is how it should look:

![screenshot from 2018-06-18 15-10-51](https://user-images.githubusercontent.com/9535558/41538123-b9600a9c-730a-11e8-9fb1-8a126df0c656.png)
![screenshot from 2018-06-18 15-21-54](https://user-images.githubusercontent.com/9535558/41538272-38aa1ac2-730b-11e8-8165-3e5bd56b1e16.png)
![screenshot from 2018-06-18 15-18-21](https://user-images.githubusercontent.com/9535558/41538216-0dd7990a-730b-11e8-8804-886c091bb975.png)

EDIT: I forgot, that key is reserved name in React. Let's call it category instead.

**Comment by ohadlevy** [comment]
not sure if its related, @amirfefer created https://www.npmjs.com/package/react-ellipsis-with-tooltip that is used in foreman, can we reuse it perhaps? :)

**Comment by jgiardino** [comment]
Hi @PanSpagetka, since we don't have css for the compound label in core patternfly yet, I created this codepen to illustrate how we could use what's already defined, plus extend it, to match the design: https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-react/less/label-remove.less

Let me know if you have any questions.

**Comment by PanSpagetka** [comment]
@ohadlevy I could use it for the category (right part) but not inside of label (on the left). So I am not sure if I should use it at all. I would more likely not use it, because at least we will have consistent way how to do it (in this component).

**Comment by ohadlevy** [comment]
can we extend it in a way its common and solves everyone's kind of
problems? @amirfefer ?

**Comment by PanSpagetka** [comment]
@ohadlevy I think problem is not the `EllipsisWithTooltip` but `Label`, even putting simple `<div>abc</div>` inside `Label` causes problems.

**Comment by jeff-phillips-18** [comment]
Feature added by #464
