### ISSUE TITLE
Tooltip doesn't flip from left or right even if there is not enought space

### ISSUE THREAD

**Issue by leSamo** [patternfly/patternfly-react#4011]
Tooltip component doesn't flip from left or right to next element in flipBehavior array even if it should because it has no space. Here it overflows bottom of the page, but doesn't flip to 'top' option in flipBehavior.
![image](https://user-images.githubusercontent.com/8426204/78246488-86715e00-74e9-11ea-8eac-8b4bcc7c986e.png)

Reproduce:
```
<Tooltip 
    content={<div>{put 10 rows of text here}</div>} 
    position: 'right'
    flipBehavior: ['right', 'top']
    // enableFlip is true by default
>
    This is tooltip
 </Tooltip>
```
Make sure the tooltip overflows the bottom of the page in which case it is expect to flip to top, but it doesn't.

This is a bug.

product: RH Insights/Vulnerability
release: patternfly/react-core": "^3.134.2",

**Comment by jschuler** [comment]
Hi @leSamo , i just tested it and could not reproduce the issue
https://codesandbox.io/s/admiring-babbage-metbw
Another prop you may want to look at is the `boundary` prop. By default it lets the tooltip know that the boundary is the window, but you can define other elements that it tries to stay in.

**Comment by leSamo** [comment]
Thanks, `boundary` prop fixed it.
