### ISSUE TITLE
Migrate topology components into react-topology package

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#4012]
We'd like to look at using the topology components - (https://github.com/openshift/console/tree/master/frontend/packages/topology) within the react-topology package as our topology implementation.

This requires the following steps:

Phase 1 - goal by 4/9/20
- [x] Copy components over to react-topology 
- [x] Update directory structure to match patternfly standards
- [x] Remove storybook code 
- [x] Create first simple beta example

Phase 2
- [x] Group components similar to wizard components in react-core so the documentation is consolidated
- [x] Identify components that should be exported from the top level for public consumption (add to this issue for review in comment)
- [x] Create examples mimicking what was in storybook previously using mdx format that is common in react-core/topology for showing documentation/examples
- [x] Make sure all exported components are marked as beta

Phase 3
- [x] Add documentation for required/optional properties that will be necessary for exported components
- [x] Add jest tests for components
- [ ] Add cypress tests in react-integration

**Comment by dgutride** [comment]
Popup support and context menu issues need to be resolved in order to support moving topology over - console-shared package includes a common component that is used within topology and this functionality would need to be handled within PatternFly for this package to be viable.

The dropdown look and feel from PatternFly was also adopted within the context menu, so design work is necessary for this to be viable within topology.

Performance issues - some fixes landing shortly in upstream openshift console that we will need to adopt.  Testing with a significant number of nodes should also be done prior to adoption and there are potentially some performance issues that could impact adoption depending on use case.  

Please add more details if necessary @christianvogt

**Comment by christianvogt** [comment]
On the performance note. Our topology was built on react and mobx with the intention to support very interactive nodes. Therefore there was a trade off in using this tech vs canvas and the approach taken by cytoscape. Different uses but always room for improvement.

For context menu support we are using patternfly `DropdownMenu`, `DropdownItem` and `DropdownContext`. We wanted to try and reuse the dropdown for its various features but we make use of these component in ways they weren't intended to.
Our context menu support also includes sub-menus.
https://github.com/openshift/console/blob/master/frontend/packages/topology/src/components/contextmenu/

We also make use of Popperjs for context menus positioning:
https://github.com/openshift/console/tree/master/frontend/packages/console-shared/src/components/popper

**Comment by wojta** [comment]
As we agreed with @dgutride @janwright73, it would be better to start with cataloging the existing code (we need to understand what's there and what's possible to use). Some high-level components should be designed based on some common use-cases to simplify otherwise complex use of the existing low-level components.

**Comment by dgutride** [comment]
@christianvogt  - thanks for commenting on this.  Do you have links to the patternfly issues describing the bug you needed to work around for the context menu sub-menus and the positioning (if I'm reading your comment right)?

**Comment by christianvogt** [comment]
The context menu and sub menu isn't a bug because patternfly doesn't have components for this yet. But here are some links that are related:
https://github.com/patternfly/patternfly-react/issues/1615
https://github.com/patternfly/patternfly/issues/2950
https://github.com/patternfly/patternfly-design/issues/774

And this one in particular about using popperjs for dropdowns:
https://github.com/patternfly/patternfly-react/issues/2790

**Comment by tlabaj** [comment]
cc @jessiehuff
