### ISSUE TITLE
Consistent Prop names for adding/removing padding

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#4039]
**Describe the issue. What is the expected and unexpected behavior?**
We currently have inconsistent prop naming for adding/removing padding.
We should update props from names frmo `noPadding` to `hasNoPadding`.  The following Components need updates

- DataListContent
- Page Section

**Comment by redallen** [comment]
What about just `hasPadding`?

**Comment by redallen** [comment]
Closed in #4133
