### ISSUE TITLE
Drawer:  update padding prop names for consistency

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#4040]
**Describe the issue. What is the expected and unexpected behavior?**
We currently have inconsistent prop naming for adding/removing padding.
We should update props from names from `noPadding` to `hasNoPadding` in DrawerPanelBody and DrawerHead

**Comment by redallen** [comment]
What about just `hasPadding`?

**Comment by redallen** [comment]
Closed in #4133
