### ISSUE TITLE
DataToolbarFilter - Add ability to remove all chips in a ChipGroupToolbarItem.

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4059]
**Describe the issue. What is the expected and unexpected behavior?**
The ChipGroupToolbarItem component allows removal of all chips on its own, but not when rendered by the DataToolbarFilter. Openshift currently uses the remove all X to remove all chips in the filter category.

**What is your product and what release version are you targeting?**
Openshift v4.5

**Comment by tlabaj** [comment]
closed by #4203 4060
