### ISSUE TITLE
Contributor guide for PF4 components 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#406]
This is an issue to start a draft (google doc) for a contributors guide for the PF4 react component effort. This guide should include answers to commonly asked questions, best practices for developing and any other helpful tips/tricks.

**Comment by LHinson** [comment]
@amarie401 @tlabaj any update on this one? If this is a distraction, we can close this one.

**Comment by tlabaj** [comment]
This is still  work in progress. There are a few Notes in the Document.  As the framework and environment continue to solidify, we should continue to add notes.

**Comment by LHinson** [comment]
ok thanks for the update @tlabaj!

**Comment by LHinson** [comment]
Closing this for now. We'll add additional issues and post info as necessary.
