### ISSUE TITLE
Layout Stack is not adding gutter class names

### ISSUE THREAD

**Issue by carlosthe19916** [patternfly/patternfly-react#4062]
The react component `<Stack gutter="lg">` is not adding the correct gutter class name when gutter's value is `lg, md, or sm`.

To reproduce the problem we only need to enter the official web page https://www.patternfly.org/v4/documentation/react/layouts/stack#with-gutter and change the value `<Stack gutter="md">` to `<Stack gutter="lg">`, you will see that nothing changed in the class names or DOM.

The expected behavior should be to have the class `pf-lg-gutter` added to the `<div>` element and see some difference between `<Stack gutter="md">` and `<Stack gutter="lg">`

**Comment by tlabaj** [comment]
@carlosthe19916 this is a mistake in the implementation and documentation.  The gutter prop acts as a boolean and adds or removes the gutter.   There is only one size for the gutter.  This will be updated in our breaking changes release.  Please see this issue that addressed this
#1982

**Comment by carlosthe19916** [comment]
@tlabaj thanks for your reply... now it is clear to me. I think we can close this issue because it was already solved by https://github.com/patternfly/patternfly-react/issues/1982.
