### ISSUE TITLE
Build scripts are in JavaScript, ideally they should be converted to TypeScript

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#4068]
**Describe the issue. What is the expected and unexpected behavior?**

We use a lot of plain JS in our node-based build scripts (e.g. https://github.com/patternfly/patternfly-react/blob/v4/packages/react-styles/scripts/copyStyles.js, https://github.com/patternfly/patternfly-react/blob/v4/scripts/bumpCore.js, etc). It would be nice to have TS used across the board to ease maintainability. Definitely a low priority.

See https://github.com/patternfly/patternfly-react/pull/4066#pullrequestreview-392364427.

**Comment by mturley** [comment]
@redallen do you think this is worth keeping open or should I let it go stale?

**Comment by redallen** [comment]
Not worth it given the stage this project is at. We are much more concerned about fixing existing bugs or adding features to the library than clearly defining APIs for our build scripts.

**Comment by mturley** [comment]
Sounds reasonable. Closing.
