### ISSUE TITLE
Chip - remove pf-m-read-only from isReadOnly variant

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4071]
For reference, the core PR: https://github.com/patternfly/patternfly/pull/2941

The `.pf-m-read-only` class was only for styling in core, and it's no longer needed as you can simply remove the close button. So we can remove that class from being applied when `isReadOnly` is true, and just show the close button.

Looks like the `isReadOnly && styles.modifiers.readOnly` bit in these lines

https://github.com/patternfly/patternfly-react/blob/43348f29d59689a3077ee9c5f90164cbd9bf23dd/packages/react-core/src/components/ChipGroup/Chip.tsx#L104

https://github.com/patternfly/patternfly-react/blob/43348f29d59689a3077ee9c5f90164cbd9bf23dd/packages/react-core/src/components/ChipGroup/Chip.tsx#L81

**Comment by evwilkin** [comment]
Looks to be resolved by #4116
