### ISSUE TITLE
Tabs: Uncaught TypeError: Cannot set property 'hidden' of null

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4074]
In Cost Management, we're seeing the following errors in the browser console. I believe this is due to the recent change to PatternFly's tab ref code.

<img width="526" alt="Screen Shot 2020-04-14 at 1 14 16 PM" src="https://user-images.githubusercontent.com/17481322/79253843-dc32f800-7e51-11ea-8ab9-c1bf69a989bb.png">

Didn't notice this issue while testing previous milestone builds, but it's a blocker for production. If a user double clicks on the same tab, the page goes blank.

![chrome-capture (1)](https://user-images.githubusercontent.com/17481322/79254705-1ea90480-7e53-11ea-883d-e618fa6ecda1.gif)

In Cost Management, we use a set of tabs, which is separated from its content. The tabs appear in the header, while the content is in a different container. See the "Separate content" example in the patternFly docs.

We lazily load tabs based on the active index. That is, we return null as the tab content if the tab is not active. Otherwise, all API requests are invoked when entering the page, which is a big performance hit.

**Comment by michpetrov** [comment]
Does this need fixing? The empty tab "workaround" seems like a better design in this case, as opposed to allowing explicitly null content and having to perform null checks. (Though I guess PatternFly can export an EmptyTabContent component itself)

**Comment by dlabrecq** [comment]
Returning null instead of a component should be valid when a component is not rendered. Ideally, tab children wouldn't be rendered at all, except for the current tab.

**Comment by michpetrov** [comment]
As far as I understand the TabContent component is like a parking spot for the actual content. I don't know how specifically React handles this but when it comes to rendering things I'd assume "there but hidden" is preferred over "not there at all".

**Comment by redallen** [comment]
Closed in #4179 , #4205, and #4211
