### ISSUE TITLE
Epic: Charting for PF4

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#408]
Check out associated core issue for history and design: https://github.com/patternfly/patternfly-next/issues/276

We will proceed with leveraging Victory charting and leverage the Victory theme system to handle the designs. https://drive.google.com/open?id=1tt4CP2TVvgxLC5Tq1D5kxnUIc6FVidhe

For information checking out the library investigation, check out: https://docs.google.com/document/d/1LnIRwtxSmkYr87EIMkUL2JbfVKx7IEUc5Uaml1d7F_8/edit

**Comment by karelhala** [comment]
If we want to use newest technologies we should drop C3, even tho they are awesome and easy to work with, the drawback here is that they are using SVG and I don't think D3 will switch to canvas. From my point of view it really doesn't matter. We can use C3 and change our graphs thanks to D3 (but that would eventually require much more work).

But I'd really like to see PF4 to use newer technologies and canvas would be awesome here, alongside with great library https://www.chartjs.org/ for simpler graphs and then use some sophisticated tools for much bigger graphs (like topology).

**Comment by LHinson** [comment]
Per @dmiller9911 

> For React D3 will most likely remain. C3 will probably not. We will be using either Victory or Plotly I imagine. Both allow for trimming off pieces that are not being used. Both of those are wrappers around pieces of D3.

**Comment by dlabrecq** [comment]
We now have a react-charts package, consisting of several types of charts, but there is more work to be done. For example, we don't have a bullet chart. The new color pallet has yet to be integrated into patternfly-core, react-tokens, etc. If you want to close this one, it might be a good idea to create separate issues for the remaining work.

**Comment by dlabrecq** [comment]
Remaining basic tasks:

1. Need a grey color pallet for bullet chart ranges. This is the only chart that uses grey.
2. The patternfly/react-tokens package needs to be updated to include the new color pallet variables from core. The package doesn't appear to have been updated in a very long time.
3. Need to create CSS variables for charts; margins, padding, font sizes, etc. Each chart type has its own style properties, which should all be defined by PatternFly core. An extensive list of properties can be found here https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-charts/src/components/ChartTheme/theme-common.js
4. Need to decide what color themes we want to support for charts? There are multiple color pallets, each could be it's own theme. Currently, we have Victory based themes for both light and dark screens, but should have a discussion with design folks. For example, we have a green-dark theme, which uses the green color pallet and white text for dark backgrounds. And a green-light theme which uses black text for light backgrounds. (This also allows tooltip background colors also change for a dark screen.) We also have a multi-color theme, based on Michael's mocks.

**Comment by mcarrano** [comment]
There were also a number of deltas that were captured by @gdoyle as she was working on design documentation. We should verify that these are captured here.

**Comment by dlabrecq** [comment]
Yes, we just had a meeting with her to discuss. The tasks above are basic architecture issues which needs to be handled first, IMO.

**Comment by dlabrecq** [comment]
This can be closed. The architecture is now in place and all tasks listed above have been completed. For example:

- Chart color pallets have been created
- Chart CSS variables have been added to pf-core
- The react-tokens package now includes all chart vars from pf-core
- Color themes have been created in react-charts
- Donut utilization chart has been merged in react-charts
- Bullet chart has been merged in react-charts
- Chart examples have been updated per design feedback -- related issues have been closed
