### ISSUE TITLE
Update react-charts types to match Victory v34 types

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#4080]
**Describe the issue. What is the expected and unexpected behavior?**
PatternFly v4 testing showed a `'victory' has no exported members` build error, which appears to be due to 34.x version of Victory exporting types, whereas 33.x does not. We should update our types in `react-charts` to match the Victory types.

![image](https://user-images.githubusercontent.com/8651509/79382233-35be2400-7f31-11ea-9bc5-e65ce78fbee7.png)

**Comment by redallen** [comment]
Closed in #4138, thanks @dlabrecq !
