### ISSUE TITLE
Page sidebar/vertical nav breakpoint changed

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4087]
https://github.com/patternfly/patternfly/pull/2962/

We changed the breakpoint at which the vertical nav is hidden. This also introduced some page component chrome spacing changes so that the horizontal spacers in the header, sidebar, page sections, and certain components in the page section (tables, data-lists, tabs, wizard) become more compact at this new breakpoint (this was pre-existing behavior at the old breakpoint, just updated to happen at the new breakpoint instead).

I don't believe this will require any changes in react, but I would like to verify just in case there is some logic with the page component toggle that referenced the old breakpoint, and just as a general smoke test to make sure everything behaves correctly after pulling in this update.

Update - after doing some more investigation, looks like the managed sidebar code will need to be updated - https://github.com/patternfly/patternfly-react/blob/a5fcf88b90eaa5001e23d0cc8f456b504a6b3809/packages/react-core/src/components/Page/Page.tsx#L104

**Comment by evwilkin** [comment]
May be resolved in #4116 :
https://github.com/patternfly/patternfly-react/pull/4116/files?file-filters%5B%5D=.tsx#diff-72a98c6cde8b853417019d7a3d558a21R104
