### ISSUE TITLE
"description" props is not declared in ModalProps at Modal.d.ts

### ISSUE THREAD

**Issue by indraraj** [patternfly/patternfly-react#4102]
"description" props is not declared in ModalProps at Modal.d.ts

**Comment by tlabaj** [comment]
Hi @indraraj can you double check what version you have in your node modules directory?  I am seeing that Modal.d.ts has the description prop in the distribution directory.

**Comment by indraraj** [comment]
yeah, it turns out in syndesis we are still using little older pf4 version that is not supporting the "description" props. Thanks for the response. I will close this issue
