### ISSUE TITLE
Toolbar layout needs to be removed from the Page component (on the black header) and on all demos that use the Page component.

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#4106]
**Describe the issue. What is the expected and unexpected behavior?**
This should be done to match Core. Currently core and react are out of sync.
I believe a flex layout can be used instead.
There may also be a header-tools component that can be used.

**Comment by redallen** [comment]
The Toolbar component has been removed (and DataToolbar renamed to Toolbar), but we need a substitute for our page demos and react-integration app that matches http://patternfly-v4.surge.sh/documentation/core/demos/page . I believe the change from Core to do this over a year old, but React never got around to implementing it: https://github.com/patternfly/patternfly/pull/1233/files
