### ISSUE TITLE
Select: Add Grouped checkbox input with filtering to the react integration demo app

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4107]
**Describe the issue. What is the expected and unexpected behavior?**
Grouped checkbox input with filtering missing from the react integration demo app
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by tlabaj** [comment]
There is already a demo for this called FilteringSelectDemo so I will close this one.  @evwilkin @redallen should we maybe look at the file structure to see if there is anyway to make it less confusing?

**Comment by evwilkin** [comment]
@tlabaj thanks for looping us in - we'll revisit this after the v4 work wraps up, potentially looking at moving the demos to live with the components
