### ISSUE TITLE
Options component: Bullet in Multi options dropdown

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#4110]
There is a bullet visible in the multi options dropdown example
https://www.patternfly.org/v4/documentation/react/components/optionsmenu#multiple-options

<img width="255" alt="Screen Shot 2020-04-21 at 10 45 17 AM" src="https://user-images.githubusercontent.com/869106/79880331-dc854300-83bd-11ea-9e94-cd40015c218d.png">

**Comment by tlabaj** [comment]
@jschuler I think this is no longer an issue.  Can you verify that and close this if everything looks ok?
