### ISSUE TITLE
Wrap icons in elements with a class

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4114]
To better support styling and positioning of icons, we introduced a simple wrapper with a BEM element name for icons where we either didn't have and were styling an icon or are applying classes to the icons directly. The wrappers are `<span>` elements unless noted otherwise.

https://github.com/patternfly/patternfly/pull/2927/

The following classes should be removed from icons directly and moved to a new element that wraps the icon.

* `.pf-c-accordion__toggle-icon` 
*  `.pf-c-context-selector__toggle-icon`
* `.pf-c-expandable-section__toggle-icon`
  * the text is now also wrapped in a `<span>` with class `.pf-c-expandable-section__toggle-text`
* `.pf-c-options-menu__menu-item-icon`
* `.pf-c-options-menu__toggle-icon`
* `.pf-c-select__toggle-arrow`
* `.pf-c-select__menu-item-icon`
* `.pf-c-wizard__toggle-icon`

The icon in `.pf-c-options-menu__toggle-button` should be wrapped in a new element with class `.pf-c-options-menu__toggle-button-icon`

The icon in the button in `.pf-c-table__toggle` should be wrapped with a new element with class `.pf-c-table__toggle-icon`

The icon in the button in `.pf-c-data-list__toggle` should be wrapped with a new element with class `.pf-c-data-list__toggle-icon` - wrapper should be a `<div>`

The icon in `.pf-c-nav__toggle` should be wrapped in a new element with class `.pf-c-nav__toggle-icon`

**Comment by evwilkin** [comment]
@mcoker the `Pagination` dropdown renders a check beside the selected pagination option using an `<i>` with the `.pf-c-options-menu__menu-item-icon` class wrapped around a `<CheckIcon>`:
<img width="491" alt="Screen Shot 2020-04-22 at 5 14 49 PM" src="https://user-images.githubusercontent.com/8651509/80034882-1721d500-84bd-11ea-887f-155c422d0002.png">

This renders as follows:
<img width="485" alt="Screen Shot 2020-04-22 at 5 20 51 PM" src="https://user-images.githubusercontent.com/8651509/80035256-bb0b8080-84bd-11ea-8591-fe45c8af6d7e.png">



Should we replace the `<i>` completely with a `<span>` containing the same class as seen below, or wrap the `<i>` with a `<span>` and move the class up to that parent `<span>`?
<img width="486" alt="Screen Shot 2020-04-22 at 5 08 45 PM" src="https://user-images.githubusercontent.com/8651509/80034760-e9d52700-84bc-11ea-9007-d58508bfa463.png">

**Comment by mcoker** [comment]
@evwilkin ah, sorry I must have missed that the react component already has a wrapper. The way it is now is fine, but I would swap the `<i>` with a `<span>` like you have it both for consistency and that a `<span>` in generic where an `<i>` is not (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i)
