### ISSUE TITLE
react-docs: Upgrade to Gatsby v2

### ISSUE THREAD

**Issue by dmiller9911** [patternfly/patternfly-react#412]
Gatsby V2 fixes most, if not all, of the workarounds that had to be put in place for the current docs.  Upgrading will also open the door for a more seamless docs generation.

**Comment by LHinson** [comment]
@dmiller9911 are you actively working on this? If not, please remove your name so others know the issue is available and still a to-do.

**Comment by tlabaj** [comment]
closed by PR #1179
