### ISSUE TITLE
PF4 include components styles inside the JS output file.

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#4125]
**Describe the issue**
Currently, compiled components do not include related CSS. Instead of living inside the component JS file, they are built into a separate CSS file and imported.

This has negative effects when using the react-core repository. 

Users have to include several different builder plugins in order to use the react-core package. These packages are not an auto-include for every react app there-fore devs should not be required to include them if they want to use the react-core library.
  - style-loader (for css)
  - resolve-url-loader (for additional references in css files)
  - url-loader (for images included inside the library)

Probably a bigger issue is the fact that the CSS imports disable Server Side Rendering. Usually, modules for the browser part of the app are excluded from the server node_modules. In order to work around the CSS imports, these modules have to be included in the server part of the application which increases the bundle size and has a negative impact on performance and mainly on the time to first render and bandwidth usage. We have to basically duplicate the client-side of the app on the server-side.

### How does the build look like now
there is this one line in every component chunk which requires related CSS files. this one is for the button:
```jsx
var _button = _interopRequireDefault(require("@patternfly/react-styles/css/components/Button/button"));
```

### Proposed usage
Use standard CSS inject method for JS files. Styles should be simple strings living in the component and the component should inject the styles when the file is loaded. Depending on the build tool, there is some inject function inside the component (pasted rollup example, but every build tool have some alternative):
```JSX
// ___$insertStyle(`button {color: 'red'}`)
function ___$insertStyle(e){if(e&&"undefined"!=typeof window){var t=document.createElement("style");return t.setAttribute("type","text/css"),t.innerHTML=e,document.head.appendChild(t),e}}
```
Another example might be postcss babel plugin, which adds the option to remove the styles imports:
https://github.com/gajus/babel-plugin-react-css-modules#options (see the `removeImport` option)

### EDIT:

How to replicate? Try and use react-core with some server-side framework like next.js (https://nextjs.org/)

**Comment by karelhala** [comment]
@evwilkin @dlabaj @tlabaj this could intersting for you

**Comment by evwilkin** [comment]
@Hyperkid123 @karelhala thanks for flagging this - I believe we've had a conversation around this that was put on hold with some of the current changes being implemented, but can take another look as soon as those are behind us

**Comment by redallen** [comment]
Style-loader and url-loader are standard Webpack plugins we built PatternFly around. Being able to require CSS files elegantly includes only the component CSS you use in your app (and you can do whatever you want with it!) instead of our entire giant stylesheet and having to add another `<link rel="stylsheet">` tag to your page.

We cannot use style injection like:
```js
function ___$insertStyle(e){if(e&&"undefined"!=typeof window){var t=document.createElement("style");return t.setAttribute("type","text/css"),t.innerHTML=e,document.head.appendChild(t),e}}
```
because of #2919. It also will bloat live HTML pages with hundreds of `<style>` tags, and it will bloat our bundles with CSS consumers might not want to load because they are using a `<style>` tag to implement parts of `@patternfly/patternfly` themselves. We will not use any `style` tags in our upcoming v4 major release (currently we use them for BackgroundImage).

For SSR, can't you just use your own CSS loader or none at all? What system are you using, and what are your problems with it? The following works just fine for me:

```js
require.extensions['css'] = mod => {}
```

**Comment by Hyperkid123** [comment]
@redallen we are using [next.js](https://nextjs.org/). It is using webpack for module bundling.

I set up a simple app that is trying to render just button. No loaders no extra webpack config.
https://github.com/Hyperkid123/pf4-ssr

`require.extensions['css'] = mod => {}` does not work. This is something I tried before. The only way how to currently make PF work with this library is as I said to force the PF package to the server bundle.

adding this to webpack config (next.config.js)
```jsx
module.exports = {
  webpack: (config, options) => {
    const { dir, isServer } = options;
    config.externals = [];

    if (isServer) {
      config.externals.push((context, request, callback) => {
        resolve(
          request,
          { basedir: dir, preserveSymlinks: true },
          (err, res) => {
            if (err) {
              return callback();
            }

            if (
              res.match(/node_modules[/\\].*\.js/) &&
              !res.match(/node_modules[/\\]webpack/) &&
              !res.match(/node_modules[/\\]@patternfly\/react-core/) &&
              !res.match(/node_modules[/\\]@patternfly\/react-styles/)
            ) {
              return callback(null, `commonjs ${request}`);
            }

            callback();
          }
        );
      });
    }
   ...
   return config
  }
}
```
> It also will bloat live HTML pages with hundreds of <style> tags

Correct me if I am wrong, but this is what is currently happening. Components from react-core do inject style tags to the document. Injecting style tags is a common practice especially for libraries using JSS, but If that is a security concern I understand. And if that is the case, why including any CSS into components and not just use classic stylesheet that in the head of the document.

> Style-loader and url-loader are standard Webpack plugins we built PatternFly around

I don't think that PF (or any other library) should be built around any module bundler. Installing and using PF should be as easy as it is with any other common package. Just run npm install, and import files. No additional configuration. I've never encountered any other component library where I had to do add anything to my bundler config.

**Comment by redallen** [comment]
> Correct me if I am wrong, but this is what is currently happening. Components from react-core do inject style tags to the document.

Not necessarily. You can use something like [`mini-css-extract-plugin`](https://webpack.js.org/plugins/mini-css-extract-plugin/) to combine CSS imports into a `<link rel="stylesheet">`. You're probably thinking of [`style-loader`](https://webpack.js.org/loaders/style-loader/) (useful for development), which does inject a tag per-required CSS file.

> I don't think that PF (or any other library) should be built around any module bundler.

This is a complicated topic. Our products have been around using module bundlers (Webpack specifically), so that's what we historically have built around. If you strongly believe this, web components are a technology that only require a browser and that we plan to support.

> The framework team themselves are not going to support importing any CSS files inside node_modules.

If true, that's a shame for because [css-loader](https://www.npmjs.com/package/css-loader) is a popular webpack loader (9mil downloads/week) that is 18x more popular than [next](https://www.npmjs.com/package/next) (500k downloads/week). I'm not sure why they wouldn't support CSS loading if they support webpack.

All that being said, I'm willing to spend time hacking at next.js if you're product is locked into it in order to get CSS imports ignored so it can just happily render the HTML.

**Comment by Hyperkid123** [comment]
@redallen So I've been playing with the PF/next combination over the weekend.

Unfortunately, the only other option I have found is transpilling the modules which include CSS and duplicating them on the server. if somebody doesn't want to writhe the config snippet I posted before, there is a plugin called `next-transpile-modules`. It does essentially the same.

> I'm not sure why they wouldn't support CSS loading if they support webpack.

I probably did not choose the right words. You can load CSS, even from node_modules, but only directly (importing them manually). The only issues are when you try to load JS files which themselves require some CSS file.

> If you strongly believe this, web components are a technology that only require a browser and that we plan to support.

Again I think I did not communicate my point properly. I don't think that web components will become mainstream anytime soon (even though it would solve so many issues). I believe that using any component library should not require more work from the developer than adding it to the dependencies and importing it.

```
yarn add library
```
```jsx
import {component} from 'library'
```
That is all that should be required IMO. I have never encountered any library which requires installing additional plugins or loaders to your module bundler of choice. They either use CSS in JS or you can just add CDN links to your document or import the CSS directly.

But if PF was designed around these requirements, it is not going to be something easily changed. It might be a good idea to add a short paragraph to your [get started](https://www.patternfly.org/v4/get-started/about) guide for people who do not use create-react-app template so they are not supprised.

Feel free to close this issue if you want. I realize you have probably more pressing issues in your backlog. With the additional "pre-transpilation" PF does work and it did for some I just thought it might be a good idea to revisit this one when you are planning a release with breaking changes.

**Comment by wojta** [comment]
I think that [next.js](url) have exactly the same solution in their _next.config.js_ in the "official" example for PatternFly. 
I have started with this one:
https://github.com/zeit/next.js/blob/master/examples/with-patternfly/next.config.js
It seems to work for me, but I'm not sure how this looks if it's not working.

**Comment by Hyperkid123** [comment]
@wojta yep that does essentially the same.

**Comment by Hyperkid123** [comment]
@wojta 
> It seems to work for me, but I'm not sure how this looks if it's not working.
If it does not work you will get a webpack error about missing loader for CSS files. Something like
```
unexpected character at 1:1 . in /path/to/file

.css-selecor {...
```

**Comment by willieseabrook** [comment]
@Hyperkid123 did you ever find a solid solution? The nextjs transpile solution has stopped working for me. Pondering dropping PF but it would be a huge amount of rework for me.

**Comment by Hyperkid123** [comment]
@willieseabrook yep. We have a working next.js app using PF. Check out this config: https://github.com/RedHatInsights/frontend-components/blob/docs/packages/docs/next.config.js#L13

You need to override PF assets compilation on the server-side of the APP. You also need CSS transpilation. The `withCSS` plugin has been officially deprecated but still works. This app is using the latest PF version.

**Comment by willieseabrook** [comment]
@Hyperkid123 wow thanks for the reply and the link! I spent 3 days and failed to come up with a working next.config.js using up to date (rather than deprecated) techniques.

See the following:

- An issue I just logged requesting the official Nextjs Patternfly example be updated: https://github.com/vercel/next.js/issues/20916
- An updated with-patternfly example using the latest versions and that also works with SASS provided you use the deprecated node-sass module https://github.com/willieseabrook/nextjs-with-patternfly

**Comment by Hyperkid123** [comment]
@willieseabrook I would not be so discouraged by the with-css deprecations. Sure the package itself is deprecated and framework creators have valid reasons for it but there is nothing wrong with the technique itself.

So if you are worried about long term support, I would create a custom "withCss" like config decorator. It would sure be less work than migrating to a different component library.

**Comment by altwarg** [comment]
@willieseabrook, I'm having some issues while trying to run your updated with-patternfly example.
Opening localhost:3000 gives me `Cannot find module 'webpack/lib/node/NodeTemplatePlugin'` error:

![image](https://user-images.githubusercontent.com/34391398/110620174-c2a54800-81a9-11eb-995f-b6f5cfd7fa78.png)

After some googling I tried to install latest webpack as dev dependency but it gives me `TypeError: The 'compilation' argument must be an instance of Compilation` error:

![image](https://user-images.githubusercontent.com/34391398/110620399-04ce8980-81aa-11eb-8a33-41a47c557d6f.png)

Of course, such behavior is OS independent. I would be very appreciate if you could help me or give me some advice.

@Hyperkid123, The RedHat `next.config.js` also didn't work for me and I got the same issues as above.

**Comment by Hyperkid123** [comment]
@altwarg  we are using the config to build our docs and it's working fine for me. I would try playing around with the regexp that excludes the packages. We are using Linux-based OS to build it.

**Comment by Hyperkid123** [comment]
> TypeError: The 'compilation' argument must be an instance of Compilation
@altwarg ah and this. Try installing webpack@4 directly in your dependencies. I recall this issue was happening with some of our loaders when upgrading to webpack 5. I think it might work.

**Comment by wojta** [comment]
@Hyperkid123  I think that it's the way to go. https://github.com/wojta/patternfly-next-js-stub/blob/master/package.json 
I'll try to investigate more on that CSS stuff though.

**Comment by Hyperkid123** [comment]
Yeah, it's not ideal though. I think I might fork the "deprecated" decorator and adjust it to work with webpack 5. We don't want to be stuck on a legacy version forever.

**Comment by altwarg** [comment]
@Hyperkid123
> We are using Linux-based OS to build it
As I mentioned above, such behavior is OS independent.

Installing webpack 4.44.2 helped to start @willieseabrook modified example. Thanks for your quick reply!
I'll see if this approach comes in handy for further development. Also, is it necessary to install webpack as dependency and not as dev dependency?

**Comment by Hyperkid123** [comment]
Dev dependency should be enough.
