### ISSUE TITLE
PF4 Wizard: Allow step names to be nodes

### ISSUE THREAD

**Issue by keithjgrant** [patternfly/patternfly-react#4134]
Requested enhancement: Currently the step names for the Wizard are typed as strings. We would like to use a React node rather than a plain string to apply some additional styling/tooltips to the step names.

Our specific use case in Ansible Tower is that we allow the user to navigate freely between Wizard steps, but would like to change the step name to red text to indicate that step has unresolved form errors the user should address (possibly adding a tooltip indicating this as well).

Note: passing in a node does appear to work currently, but it logs errors to the console for invalid prop type.

**Comment by tlabaj** [comment]
closed by #4063
