### ISSUE TITLE
React props exposed to DOM elements in Toolbar

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#4149]
**Describe the issue. What is the expected and unexpected behavior?** Seeing warnings in the console for DataToolbar

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.** Run latest v4 branch and navigate to `http://localhost:8000/documentation/react/components/datatoolbar`

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?** Bug

```
Warning: React does not recognize the `clearAllFilters` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `clearallfilters` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

```
Warning: React does not recognize the `clearFiltersButtonText` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `clearfiltersbuttontext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

```
Warning: React does not recognize the `showClearFiltersButton` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showclearfiltersbutton` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

```
Warning: React does not recognize the `isExpanded` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isexpanded` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

```
Warning: React does not recognize the `toolbarId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `toolbarid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

<img width="703" alt="Screen Shot 2020-04-29 at 12 30 30 PM" src="https://user-images.githubusercontent.com/5942899/80621662-9c553e80-8a15-11ea-9dae-583e1d74dc6e.png">

**Comment by boaz0** [comment]
@seanforyou23 can you upload the code?
Maybe it happens because you need to wrap `DataToolbar` children with `DataToolbarContent`?

**Comment by seanforyou23** [comment]
Good point @boaz0 I should have mentioned, but I'm seeing it on the V4 branch in the main doc page for DataToolbar (recently renamed "Toolbar").

**Comment by boaz0** [comment]
Hoo I see this too.
It looks like this error comes from `React.cloneElement`

**Comment by seanforyou23** [comment]
Yep exactly. We fixed this same type of issue before ([in Alert](https://github.com/patternfly/patternfly-react/pull/3771/files#diff-3c7439478e25fad3c720e081f6dfc4bfL83-R94)) by swapping out use of cloneElement for use of context, but in Toolbar there's already use of context, so maybe context alone wasn't enough to handle the case? Maybe @kmcfaul or @redallen has an idea?
