### ISSUE TITLE
NotificationDrawer: Add stripped down example of notification drawer.

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4160]
**Describe the issue. What is the expected and unexpected behavior?**
Add an example of the notification drawer as used in openshift where neither read/unread nor kebabs are used

**Comment by mcarrano** [comment]
@jcaianirh Thanks for adding this example to reflect the OpenShift implementation. I'm just struggling a bit with the naming and ordering of the examples in this case. Seems like the most basic example is what you are doing without any global actions or read/unread. Then we add unread notifications and grouping to give us more complex versions of the drawer. @mcoker wanted to get your thoughts on this. Should we be adding the new example to Core also and do you think we then need to refactor the examples at all or do you think this is OK?

As for the example itself, there was only one small nit I had @jcaianirh . Where there are 0 alerts to display and you are showing the empty state, I'm wondering why the 'View all alerts' action is there. What would that do?
