### ISSUE TITLE
EmptyStateIcon missing color prop

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4166]
This issue #3336 (PR #4065) removes the "unused" props from the `EmptyStateIcon`. Perhaps folks were unaware, but the props are in use.

In Cost Management, we provide an icon and color like so.

`<EmptyStateIcon icon={OkIcon} color="green" />`

My workaround is to wrap the `OkIcon`, like so:

```
const MyOkIcon = () => (
  <OkIcon color="green"/>
);
...
<EmptyStateIcon icon={MyOkIcon} />
```

It seems like a simple feature to provide, instead of forcing devs to create custom icons?

**Comment by tlabaj** [comment]
Hi Dan.  Color was marked deprecated by accident.  We will add this back.  Size and title will still be removed.
