### ISSUE TITLE
RC2: Wizard padding

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4169]
Updated to the latest v4 packages, RC1. The wizard now has an odd border, which is noticeable around the header.

<img width="409" alt="Screen Shot 2020-05-19 at 10 46 09 AM" src="https://user-images.githubusercontent.com/17481322/82342232-60334f00-99bf-11ea-9040-c0c48b46f9ac.png">

The wizard no longer appears full page, but now has a white border.

<img width="1148" alt="Screen Shot 2020-05-08 at 2 22 24 PM" src="https://user-images.githubusercontent.com/17481322/81437044-7d069180-9138-11ea-8001-2945492361a4.png">

**Comment by dlabrecq** [comment]
Updated to the latest v4 packages.

<img width="325" alt="Screen Shot 2020-05-08 at 2 30 56 PM" src="https://user-images.githubusercontent.com/17481322/81437087-93ace880-9138-11ea-868d-056d17d119eb.png">

The wizard no longer appears full page, but now has a white border.

<img width="1148" alt="Screen Shot 2020-05-08 at 2 22 24 PM" src="https://user-images.githubusercontent.com/17481322/81437044-7d069180-9138-11ea-8001-2945492361a4.png">

**Comment by redallen** [comment]
We still need to write codemods for this, so please do share a diff of your Wizard code once this is resolved @dlabrecq !

**Comment by dlabrecq** [comment]
Will do.

**Comment by redallen** [comment]
@nicolethoen Here's cost management's wizard code: https://github.com/project-koku/koku-ui/blob/master/src/pages/costModels/createCostModelWizard/index.tsx#L65

@dlabrecq Have you modified this code any further?

**Comment by dlabrecq** [comment]
No, I have not needed to modify the code -- already using isOpen

**Comment by dlabrecq** [comment]
Same issue with RC2

**Comment by redallen** [comment]
Probably a duplicate of #4337...

**Comment by nicolethoen** [comment]
@dlabrecq can you see what patternfly value/variable/class is adding this padding using the inspector? I believe the styling that adds the padding was removed, so I'm not sure what would be adding it.

**Comment by dlabrecq** [comment]
Met with @mcoker and the extra padding appears to be from Insights and their older version of PatternFly
