### ISSUE TITLE
ChartDonut subTitleComponent is ignored in some cases

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#4172]
When subTitlePosition is  'center', the subTitleComponent prop is ignored completely and the titleComponent styles are applied to the sub title instead. Unless you inspect the source code, there is no way to know that this is going to happen, or that passing an array of styles to the titleComponent can override the sub title styles.

**getSubTitle returns null if position is center**
https://github.com/patternfly/patternfly-react/blob/82db41fc2f1b0f3c6105f2038284204b0d641c9a/packages/react-charts/src/components/ChartDonut/ChartDonut.tsx#L490-L492

**getTitle renders both title and subTitle when subTitlePosition === 'center'**
The only way to override subTitle style in this scenario is to pass a styles object as the second element in an array through the titleComponent styles prop. This is not intuitive at all.

https://github.com/patternfly/patternfly-react/blob/82db41fc2f1b0f3c6105f2038284204b0d641c9a/packages/react-charts/src/components/ChartDonut/ChartDonut.tsx#L519-L548

**Comment by dlabrecq** [comment]
Line 490 doesn't look correct. 

We can clarify this in the docs. However, I believe the intention was that a subtitle must also appear with a title -- centering the titles depends on some x/y positioning.

The code probably should have tested `!subTitle` by itself or mimic line 524.

`subTitle && subTitlePosition === ChartDonutSubTitlePosition.center`

**Comment by michpetrov** [comment]
I feel like there are two issues at hand.

In case `subTitlePosition="center"` the title and subtitle have to be positioned relative to each other. Easy to do if they are a single component. If we "relinquish control" and render both separately then it's up to you to figure out the position of the subtitle but also the title.

In case you just want to change some styles (e.g. the text color) then the above is an overkill.

So there are two use-cases which aren't fully supported:
 * I want to change just the style of the subTitle
   * I assume here it would be enough to merge `subTitleComponent.props.style`
 * I want to have full control
   * this requires a change in the checks for `subTitlePosition === ChartDonutSubTitlePosition.center`

**Comment by dlabrecq** [comment]
The reason `getSubTitle` returns null is because `getTitle` already renders both title and subTitle when used together. If we didn't return null, you would see two subTitles.

The reason why your styles are not applied is because the `titleComponent` is rendering both title and `subTitle`.

You can override styles using an array, representing the styles for title and subTitle.

<img width="633" alt="Screen Shot 2020-05-06 at 3 37 11 PM" src="https://user-images.githubusercontent.com/17481322/81220665-b3fd6b80-8faf-11ea-9352-5e40b30f37d7.png">

**Comment by TheRealJon** [comment]
Yeah, I think that it is working as intended, but doesn't make for a very intuitive API. Here's the scenario that led to this issue:

- The sub title in our donut chart was too long to fit in the center of the donut
- We go to the docs to see what props or options we have to customize the donut chart sub title
- Moving the sub title position to the bottom or right are not ideal solutions
- The subTitleComponent is listed in the docs and seems to be exactly what we need
- We try adding a custom subTitleComponent with custom styles and it does nothing
- After 3 people scour the docs and source code, we figure out exactly how it works, and by then have already figured out a different work around that bypasses the component props altogether.

I think it's very counter-intuitive that a subTitleComponent prop exists but is completely ignored by default, and as you've noted this isn't covered by the docs. Even if this was covered in the docs, it's still confusing that you have two different ways of controlling the subTitle (a subTitleComponent prop, and the styles array of the. titleComponent). We should either treat the title/subTitle as separate entities, or not. It's confusing that they are sometimes handled separately and sometimes not, depending on what props and values are passed.

**Comment by dlabrecq** [comment]
I hear your frustration, but Victory doesn't provide an alternate way to vertically center multiple labels. It's possible to adjust manually, but doesn't work well with various fonts and sizes.

Alternatively, we don't have to render both labels together when `subTitleComponent` is provided. However, you would end up with `title` and `subTitle` overlaying each other. (They would be centered individually, but occupying the same space.) You would be responsible for setting your own `capHeight` and positioning it using the `x` and `y` props.

**Comment by dlabrecq** [comment]
Fixed by https://github.com/patternfly/patternfly-react/pull/4206
