### ISSUE TITLE
Table (PF4): When using headerCol with expandable rows the blue line on the right disappear from the expanded item

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#4177]
Expected result:
![Screen Shot 2020-05-04 at 18 28 22](https://user-images.githubusercontent.com/14921356/80989318-141bd280-8e35-11ea-9100-818581dc8e7b.png)

Actual result:
![Screen Shot 2020-05-04 at 18 26 58](https://user-images.githubusercontent.com/14921356/80989221-efbff600-8e34-11ea-8121-56839af29940.png)

Notice the blue line missing from the expandable item.

**Comment by nicolethoen** [comment]
Hi @KKoukiou !
I believe with the latest updates to react-table, this may have been fixed, but I wanted to verify with you.

**Comment by KKoukiou** [comment]
> Hi @KKoukiou !
> I believe with the latest updates to react-table, this may have been fixed, but I wanted to verify with you.

I checked it directly on the website examples and indeed it works as expected.
