### ISSUE TITLE
`tabIndex` in `<Page>` should be an optional prop

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#4180]
See https://github.com/patternfly/patternfly-react/blob/v4/packages/react-core/src/components/Page/Page.tsx#L159

This creates an issue if scrolling occurs on a child element instead of `<main>` where the keyboard cannot be used to scroll the scrollable element.  The workaround is to add `tabIndex={-1}` to the scrollable element; however, it seems this should not be necessary as PatternFly should provide the option to not include `tabIndex` in `<Page>`.

**Comment by redallen** [comment]
Fixed in #4181.
