### ISSUE TITLE
Remove react-tokens dependency from react-core pagination by using number formatting

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#4184]
**Describe the issue. What is the expected and unexpected behavior?**
When passing large number of items to pagination it automatically expands and take too much space on toolbar. This should be resolved by using [Verify Number Formats](http://www.unicode.org/cldr/charts/28/verify/numbers/en.html) (specification for short writing large numbers) - `400, 4K,400K, 4M, 400M,4B,400B,4B ,400B , 4T`. We have an account with `44296` items which will eventually be shown as `4430` number of pages. It would be easier to read if we'd show `44K` items and `4K` pages. If user hovers over pagination element he could see tooltip with full information
```
Number of items: 44 296
Number of pages: 4 430
Items per page: 10
```

Ideally I'd like to pass custom renderer to pagination count in order to use custom renderer for any number.

I guess that this could eventually be part of design guidelines so we can use this number formatting in any place.

I am raising this issue, because we've tried using the latest build (>=4.0.0) and we've noticed bundle increase and identified react-tokens as one culprit of this problem
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement.

**What is your product and what release version are you targeting?**
cloud.redhat.com

**Comment by karelhala** [comment]
ping @dlabaj @tlabaj @redallen

**Comment by rvsia** [comment]
Yeah, I can confirm this hugely increases the bundle size of Sources UI. :(

At least we should change it to not import it from the root index.

**Comment by Hyperkid123** [comment]
https://github.com/patternfly/patternfly-react/commit/0d506074e4084f8dadd3ffdfafb04dde7d13ed7c#diff-d87281f50eaab3e4a6bdc984f079b2cfR9

Here is the change. Now pulls all the tokens again if used in a library as an external dependency.

**Comment by redallen** [comment]
Just changing that import to
```js
import c_pagination__nav_page_select_c_form_control_width_chars from '@patternfly/react-tokens/dist/js/c_pagination__nav_page_select_c_form_control_width_chars';
```
should be enough to fix your CJS bundle sizes...

I'll fix this and write a linting rule to disallow imports from the tokens and icons barrel files.

**Comment by redallen** [comment]
It looks like this change has already been implemented on `v4`. I've added a rule for it called `import-tokens-icons` to `eslint-plugin-patternfly-react` and you can use this rule yourself in product.

**Comment by redallen** [comment]
Feel free to open a new issue surrounding number formats in Pagination.

**Comment by rvsia** [comment]
@redallen So, the bundle size will be fixed in the next major release?

**Comment by redallen** [comment]
Yes, it should! I'm seeing 23% size reduction with [the seed app.](github.com/patternfly/patternfly-react-seed/)

- React-core dist size down 20Kb due to smaller base.css , withOUIA removal, and smaller react-icons (down to 8Kb from 16Kb) and react-styles (down to 6Kb from 11Kb)
- Overall dist size down 63Kb due to removing no-case and create-emotion as a dependency from react-styles (26Kb + 32Kb), and then an extra 5Kb was shaved in babel helpers being able to consolidate down into tslib.es6.ts which the seed app already depends on (since it's Typescript)
