### ISSUE TITLE
Add "0" and "All" selected badging for Select

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-react#4186]
**Describe the issue. What is the expected and unexpected behavior?**
OpenShift uses something similar to select, but it has badging for "0" and "All" selected. Right now, Select only supports badging for 1+ items selected. OpenShift folks were wondering if PatternFly would be willing to support the "0" and "All" badging cases.

None:
<img width="196" alt="Screen Shot 2020-05-05 at 9 30 05 AM" src="https://user-images.githubusercontent.com/7014965/81071681-0f95ff00-8eb3-11ea-8484-464339131a6e.png">

All:
<img width="191" alt="Screen Shot 2020-05-05 at 9 30 16 AM" src="https://user-images.githubusercontent.com/7014965/81071696-145ab300-8eb3-11ea-831d-6bb64061e283.png">

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is an enhancement. We're going to look into passing a React node into the placeholder text so we can work around this limitation per @tlabaj's guidance for now. However, it would be great if PatternFly supported this more formally.

**What is your product and what release version are you targeting?**
OpenShift 4.5+

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
I don't have a problem with this. What do you think @mceledonia ? 

@mcoker would this require any Core change?

**Comment by mcoker** [comment]
@mcarrano no changes needed in core, it's just a different string in the badge.

<img width="280" alt="Screen Shot 2020-05-05 at 11 06 32 AM" src="https://user-images.githubusercontent.com/35148959/81088471-97363a80-8ec0-11ea-80f9-7776fd233875.png">

**Comment by rebeccaalpert** [comment]
I opened a PR here: https://github.com/patternfly/patternfly-react/pull/4198/files

Let me know if you have feedback on the approach.

**Comment by mcarrano** [comment]
PR looks good @rebeccaalpert
