### ISSUE TITLE
TabButton, TabContent, ToolbarGroup props missing from docs

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#4197]
**Describe the issue. What is the expected and unexpected behavior?**

Extends #3885 and @mturley's comment there:

> Probably related to the fact that it is exported as a forwardRef component.

_Originally posted by @mturley in https://github.com/patternfly/patternfly-react/issues/3885#issuecomment-611216493_

These are all exported as `forwardRefs` and their props are also not being displayed in the docs.

**Comment by redallen** [comment]
This is a react-docgen issue we might be able to work around. The source code for what we use is upstream in patternfly-org: https://github.com/patternfly/patternfly-org/blob/master/packages/gatsby-transformer-react-docgen-typescript/gatsby-node.js#L102

We really should contribute to react-docgen if we can't find a workaround.

**Comment by mturley** [comment]
This is one of a few things I'd like to see us fix in react-docgen. I think it might be worth meeting at some point to share some knowledge about how we use it and how it works, so we can more easily figure out what changes we need to propose for it. I'm curious if anyone else in the TS React community is also looking for changes like that in react-docgen.

**Comment by ddonahue007** [comment]
I saw this from searching around. At the bottom they talk about the a specific pattern that they do not believe should be applied.

https://github.com/reactjs/react-docgen/pull/350
