### ISSUE TITLE
Modal resizes oddly

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4226]
Seeing strange behavior in with the modal resizing. The modal briefly appears full page in height, but then resizes to match its loaded contents.

Note that if there is no size variant, it appears full page, both in height and width. Seems odd to begin as a full page Vs growing as contents are added.

![chrome-capture](https://user-images.githubusercontent.com/17481322/81440883-c2c65880-913e-11ea-8bf2-629dffdc436c.gif)

<img width="580" alt="Screen Shot 2020-05-08 at 3 14 43 PM" src="https://user-images.githubusercontent.com/17481322/81441002-f5705100-913e-11ea-8229-c0c671e69def.png">

**Comment by dlabrecq** [comment]
This also appears to happen with the wizard from the latest v4 breaking changes packages.

![chrome-capture](https://user-images.githubusercontent.com/17481322/81446771-69175b80-9149-11ea-98fc-4cf840675c31.gif)

**Comment by tlabaj** [comment]
@dlabrecq Are both issues in v4?

**Comment by jschuler** [comment]
Looks like the `Looking for sources` spinner is pushed down and the container reacts by expanding the height. Any way you could keep it in the loading state and inspect why it is getting pushed down @dlabrecq ?

**Comment by dlabrecq** [comment]
@tlabaj The second issue only occurs with the breaking change release.

**Comment by dlabrecq** [comment]
I found a solution on our end
