### ISSUE TITLE
Tab/Tabs: Setting href on Tab breaks activeKey

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#4229]
**Describe the issue. What is the expected and unexpected behavior?**

Setting the `href` prop on the `Tab` component seems to prevent `activeKey` from working correctly.

The hrefs in [the example](https://www.patternfly.org/v4/documentation/react/components/tabs#using-nav-element) are all set to `#` which works as expected, but the example breaks when they are set to different anchor tags.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/nervous-pare-ok0mr?file=/index.js

**Comment by redallen** [comment]
This is an issue because browsers do not fire `onClick` for anchor tags with non-`#` or `'javascript:void(0)'` URLs. A possible solution would be to wrap these in a `<div>` that has an `onClick` or use a router link component like `import { Link } from '@reach/router';`.
