### ISSUE TITLE
PageSection: 2xl padding moddifier is not getting applied 

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#4240]
**Describe the issue. What is the expected and unexpected behavior?**
2xl padding  is not getting applied.  This is because the formatBreakpointMods utility function does not account for `_`

**Comment by boaz0** [comment]
@tlabaj I believe this: https://github.com/patternfly/patternfly-react/pull/4270 should fix it.

**Comment by redallen** [comment]
Fixed in #4270.
