### ISSUE TITLE
Select: Support for scrolling

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-react#4242]
**Describe the issue. What is the expected and unexpected behavior?**
OpenShift is looking into using Select, but we would need it to scroll because we have around 90 items in it. We tried a CSS approach on our end, but the eternal focus on the filter input for the grouped checkbox input with filtering prevents users from selecting items further down in the list by clicking on their name.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is an enhancement request and is blocking us.

**What is your product and what release version are you targeting?**
OpenShift 4.5+

**Comment by kmcfaul** [comment]
Is the issue that the options list continues to expand to try to fit all of the items? If you use the `maxHeight` property of Select to impose a height limit, extra items should be scrollable with the mouse.

**Comment by rebeccaalpert** [comment]
The focus on the input prevents selection when you impose a height limit.

**Comment by kmcfaul** [comment]
There is also an open issue with FocusTrap found by @nicolethoen that may impact this: https://github.com/patternfly/patternfly-react/issues/4217#issuecomment-635496288

Ah, I do see the odd selection behavior in our examples when using `maxHeight` too. Thanks for the info! I'll take a deeper look in case this lies outside the FocusTrap issue.

**Comment by rebeccaalpert** [comment]
Thanks, I appreciate it!

**Comment by kmcfaul** [comment]
This does appear to be due to the FocusTrap issue with `maxHeight`. Clicking on the checkboxes specifically works, but the text just sends you to the top without selection. 

We'll keep track of their open issue, and may have to look into alternatives in our code if it doesn't release soon.

**Comment by rebeccaalpert** [comment]
Thanks Katie!

**Comment by rebeccaalpert** [comment]
This is still an issue, stale bot!

**Comment by rebeccaalpert** [comment]
Closing since it's a duplicate of https://github.com/patternfly/patternfly-react/issues/4421.
