### ISSUE TITLE
topology: address followup comments

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#4245]
- Delete the .bak file
- Ensure lodash and tslib dependencies are consistent with other packages
- Talk to core about topology-components.css
- Verify Jest tests are working and add integration tests
- Source code review (decorators/mobx)
- demo-app tsconfig changes

@redallen @wojta

**Comment by wojta** [comment]
@dgutride

**Comment by redallen** [comment]
Some of these issues still exist.
