### ISSUE TITLE
TypeAheadSelect component is functional

### ISSUE THREAD

**Issue by shaded-enmity** [patternfly/patternfly-react#427]
The current definition:
https://github.com/patternfly/patternfly-react/blob/5883c7e54053b8ba970fad2728ba3b57fee07538/packages/patternfly-react/src/components/TypeAheadSelect/TypeAheadSelect.js#L4
makes `TypeAheadSelect` a functional component and thus preventing me from using `ref=`:

```
Stateless function components cannot be given refs. Attempts to access this ref will fail.
```

**Comment by dmiller9911** [comment]
@shaded-enmity what is the usecase you are trying to cover? I took a look, and it looks as though the typeahead lib we uses does expose an inputRef prop to get a ref for the input rendered.

**Comment by shaded-enmity** [comment]
@dmiller9911 I need to focus the component and this is the suggested way of doing it - https://github.com/ericgio/react-bootstrap-typeahead/blob/master/example/examples/PublicMethodsExample.react.js
Besides, the exposed key is slightly different (`inputProps`) and for some reason that didn't work for me.
I'm curious as to what is the benefit of there being a functional facade over a class based component because it *only* changes the semantics of the exposed proxy function compared to the wrapped component.
It seems to me that this would fare much better:
```
export { Typeahead as TypeAheadSelect } from 'react-bootstrap-typeahead';
```

**Comment by dmiller9911** [comment]
Yeah I definitely agreed with that. It will probably be better to just rexport with the name we want. I just wanted to make sure we met what you needed in case we need to do more than just the re-export.
