### ISSUE TITLE
Drawer: Hidden drawer becomes visible by tabbing through the page

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4279]
**Describe the issue. What is the expected and unexpected behavior?**
React component with these core changes from this issue: https://github.com/patternfly/patternfly/issues/3129

**Comment by seanforyou23** [comment]
I reviewed the [solution](https://github.com/patternfly/patternfly/pull/3184) for https://github.com/patternfly/patternfly/issues/3129 and after speaking further with @mattnolting we came to the conclusion there's no longer an action item on the react side. The core changes seem to satisfy the problem well. The markup validates and focusable child elements of the drawer are not visible (as expected) when the drawer is closed. Closing for now, feel free to re-open in case I've missed anything.
