### ISSUE TITLE
[ChartDonut] padAngle prop type definition does not match Victory

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/patternfly-react#4282]
**Describe the issue. What is the expected and unexpected behavior?**
For the ChartDonut component, we define the padAngle prop type as `number`, but Victory defines it as `number | function`. If we try to define a padAngle prop as a function, we get TS errors. I would expect to be able to use the same prop types that are accepted by the underlying Victory chart component.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
In a TypeScript project, create a ChartDonut component and provide a function to the 'padAngle' prop. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, there is a workaround, but it requires overriding the type or disabling TypeScript for that line.

**What is your product and what release version are you targeting?**
OpenShift Admin Console 4.6

**Comment by dlabrecq** [comment]
For the victory-pie package, version 34.1.3, the `padAngle` type is `number`. Here is a snapshot from their index.d.ts file.

<img width="709" alt="Screen Shot 2020-05-28 at 8 55 06 PM" src="https://user-images.githubusercontent.com/17481322/83209258-db1a0980-a125-11ea-833e-f51171f747c3.png">

That said, I see in Victory's latest code that the type has changed to `NumberOrCallback`. Will investigate updating to the latest version if there are not too many changes.
