### ISSUE TITLE
Breaking change review - Login page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#4289]
Login example looks correct on current pattenfly.org but the large PatternFly icon is back on Surge: https://patternfly-react.surge.sh/documentation/react/components/loginpage/basic/

Can we update to the correct image as seen on https://www.patternfly.org/v4/documentation/react/components/loginpage/basic

cc @redallen @tlabaj

**Comment by redallen** [comment]
Which icon is not matching? Surge site:
![image](https://user-images.githubusercontent.com/47335686/83030890-ea079b80-a001-11ea-9c45-325a61b9be0e.png)
Org site:
![image](https://user-images.githubusercontent.com/47335686/83031040-19b6a380-a002-11ea-90be-2fba57c3c554.png)

**Comment by redallen** [comment]
Our surge site was incorrect for a while. I have a PR up for the fix.
