### ISSUE TITLE
Render custom MastHead from within VerticalNav

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#429]
While working on the PF React Demo App w/ @amarie401 - I noted that we currently cannot override the default `nav` element rendered by the `VerticalNav`. It would be nice to be able to use the new `MastHead` component so that I can customize the MastHead within `VerticalNav`.

This would basically involve no longer rendering the `nav` element here with the Vert Nav if the user specifies:
https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-react/src/components/VerticalNav/VerticalNav.js#L405

Vert Nav reference code:
https://github.com/patternfly/patternfly-react-demo-app/blob/master/src/App.js#L105

**Comment by aljesusg** [comment]
Yeah, I am working in Kiali project and we can't.
The problem is that verticalnav render a nav.

https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-react/src/components/VerticalNav/VerticalNav.js#L405
