### ISSUE TITLE
Select dropdown width can't be controlled

### ISSUE THREAD

**Issue by riccardo-forina** [patternfly/patternfly-react#4305]
**Describe the issue. What is the expected and unexpected behavior?**

If one of the options displayed with a `Select` is very long, the dropdown stretches to contain it all.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/qhil7

It's possible to tweak the css to add a `max-width: 100%` to `.pf-c-select__menu`, but maybe this should be supported out of the box with a `maxWidth` property, since there is a `maxHeight` one already.

**Comment by MariaAga** [comment]
https://github.com/patternfly/patternfly-react/pull/4579 Does this solve the issue?

**Comment by riccardo-forina** [comment]
Not exactly, it would be better to allow the menu's width to automatically adjust like the default behavior, but with the possibility to specify the max width to avoid the overflow (which could be the default behavior IMHO)
