### ISSUE TITLE
Cannot create a branch from upstream/master

### ISSUE THREAD

**Issue by DaoDaoNoCode** [patternfly/patternfly-react#4318]
**Describe the issue. What is the expected and unexpected behavior?**
In contributing guidelines, I followed the steps in section **Guidelines and Requirements** part **Code Contribution Guidelines** as below.

<img width="661" alt="Screen Shot 2020-06-01 at 3 06 05 PM" src="https://user-images.githubusercontent.com/37624318/83532266-03a25a80-a4bc-11ea-8dd4-8a8e1093e50d.png">

After I finished step 1, I met an error when creating a branch.

<img width="630" alt="Screen Shot 2020-06-01 at 3 09 55 PM" src="https://user-images.githubusercontent.com/37624318/83532491-4f550400-a4bc-11ea-9802-c9dcfd77f4f5.png">

**Comment by redallen** [comment]
The `-t` shouldn't be there. Can you update #4319 to remove it?

**Comment by DaoDaoNoCode** [comment]
@redallen Updated. PTAL, thanks.
