### ISSUE TITLE
Spike: Investigate effort to pull the Virtual table into component library

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#4322]
**Describe the issue. What is the expected and unexpected behavior?**
The virtual table is currently an extension.  It is being used by multiple teams and we would like to investigate the feasibility and effort of pulling this into our component library.

**Comment by kmcfaul** [comment]
I would say it's a moderate to heavy lift to bring in the extension.

The extension is partially a fork, partially a re-export of `react-virtualized`, which has a lot of open issues that could potentially come up later down the line if we fully integrate the extension. The other potential hurdle would be making sure the extension is accessible, however looking back at Patrick's [initial PR]( https://github.com/patternfly/patternfly-react/pull/2011) it appears he put some thought into this already when bringing it in. It would still require an audit though.

**Comment by tlabaj** [comment]
Investigation was completed and new issues #4453, #4454 and #4457 have been opened for follow up work.
#
