### ISSUE TITLE
RC2: Tertiary nav

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4333]
Updated to the RC2 packages. Noted a strange border around the tertiary nav.

<img width="472" alt="Screen Shot 2020-06-04 at 2 33 06 PM" src="https://user-images.githubusercontent.com/17481322/83797385-9126ab80-a670-11ea-9a5d-f24d53aea09a.png">

**Comment by redallen** [comment]
I think some custom CSS is being applied to that tertiary nav because the font weight looks different than on https://patternfly-react.surge.sh/documentation/react/components/nav#tertiary

**Comment by dlabrecq** [comment]
Cost Management isn't applying any custom styles to the nav. However, it's possible there is a conflict with the version of PatternFly used by the Insights platform?

**Comment by dlabrecq** [comment]
Met with @mcoker and we're a bit stumped ATM. He's going to try debugging Cost Management locally.

**Comment by dlabrecq** [comment]
Tested with Insights platform, after they also updated, and this is no longer an issue
