### ISSUE TITLE
RC2: Missing Toolbar filter

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4335]
Updated to the RC2 packages. Noted an issue with the toolbar filter.

In the screenshot below, the filter is missing.

<img width="1183" alt="Screen Shot 2020-06-04 at 2 38 35 PM" src="https://user-images.githubusercontent.com/17481322/83797747-16aa5b80-a671-11ea-876d-45d3236710f9.png">

This could be a result of a bad code mod applied to Cost Management? Will investigate...

**Comment by redallen** [comment]
`DataToolbar` has been renamed to `Toolbar`. If you previously updated this and then ran codemods again recently, you may have had your `Toolbar`s renamed to `PageHeaderTool`s and have to revert them back.

**Comment by dlabrecq** [comment]
No, that's not it.

Looks like my toolbar is hidden because of the new breakpoints. The thing is, the filter won't show up at all if this is omitted.

`show={{ xl: 'show' }}`

**Comment by dlabrecq** [comment]
My workaround is to add `show={{ default: 'show' }}`, but this should not be necessary?

<img width="528" alt="Screen Shot 2020-06-04 at 9 49 46 PM" src="https://user-images.githubusercontent.com/17481322/83827910-660e7d00-a6ad-11ea-9bb3-7ff045f5cfc4.png">

Rendered toolbar filter:
<img width="1526" alt="Screen Shot 2020-06-04 at 9 51 08 PM" src="https://user-images.githubusercontent.com/17481322/83827973-8c341d00-a6ad-11ea-8f67-9e7bdd80788c.png">

**Comment by redallen** [comment]
This is the way the core implementation works. All of our examples used to include the `breakpoint` prop that has since been changed to use the new `show={{}}` API. I've opened #4341 to default ToolbarToggleGroup to `show={{ default: 'show' }}`!
