### ISSUE TITLE
RC2: Font is heavy weighted

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4336]
Updated to the RC2 packages. Noted an issue with fonts in the Cost Management header.

In the screenshot below, the font is very heavy weighted compared to what is was previously. Is this expected?

<img width="1424" alt="Screen Shot 2020-06-04 at 2 42 28 PM" src="https://user-images.githubusercontent.com/17481322/83798162-cf709a80-a671-11ea-8ac2-1b8895d78aa7.png">

**Comment by redallen** [comment]
The default font has changed to Red Hat Text, which might have something to do with it.

Did we make any font weight updated that might have done this @mcoker ?

**Comment by mcoker** [comment]
@dlabrecq @redallen yep, we changed those from `RedHatDisplay` normal weight (which was semi-bold already) to `RedHatText` bold.

**Comment by redallen** [comment]
Do you have the old values handy @mcoker ? I think [I've found the PR](https://github.com/patternfly/patternfly/pull/2955/files)

**Comment by redallen** [comment]
From @mcoker, the old CSS is:
```css
font-family: RedHatDisplay;
font-weight: 400;
```

If you run into more trouble let us know.
