### ISSUE TITLE
RC2: Modal padding

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4337]
Updated to the RC2 packages. Noted an issue with the modal padding.

In the screenshots below, there is much more padding around the modal. Is this expected?

Screenshot 1:
<img width="1597" alt="Screen Shot 2020-06-04 at 2 25 25 PM" src="https://user-images.githubusercontent.com/17481322/83798395-355d2200-a672-11ea-8092-021273e8f0ee.png">

Screenshot 2:
<img width="2135" alt="Screen Shot 2020-06-04 at 2 27 08 PM" src="https://user-images.githubusercontent.com/17481322/83798355-21192500-a672-11ea-9e17-68f4c09def46.png">

Screenshot 3:
<img width="1630" alt="Screen Shot 2020-06-04 at 2 23 07 PM" src="https://user-images.githubusercontent.com/17481322/83799210-77d32e80-a673-11ea-914a-df9772f3467e.png">

**Comment by redallen** [comment]
What does your Modal code look like? I'm not noticing any extra padding on [our surge site](http://patternfly-react.surge.sh/documentation/react/components/modal) compared to [patternfly.org](https://www.patternfly.org/v4/documentation/react/components/modal).

**Comment by dlabrecq** [comment]
This is from screenshot #1

<img width="590" alt="Screen Shot 2020-06-04 at 10 17 31 PM" src="https://user-images.githubusercontent.com/17481322/83829616-3f524580-a6b1-11ea-9c25-8742e4fa2a9f.png">

The only style we add is for form width.
<img width="421" alt="Screen Shot 2020-06-04 at 10 17 41 PM" src="https://user-images.githubusercontent.com/17481322/83829649-5729c980-a6b1-11ea-8ba9-3f1e2b8cdf01.png">

**Comment by dlabrecq** [comment]
Met with @mcoker and the extra padding appears to be from Insights and their older version of PatternFly
