### ISSUE TITLE
RC2: Card actions

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4338]
Updated to the RC2 packages. Noted an issue with card actions.

In the screenshots below, there seems to be an issue with the card layout.

<img width="1375" alt="Screen Shot 2020-06-04 at 2 25 44 PM" src="https://user-images.githubusercontent.com/17481322/83798686-9a187c80-a672-11ea-9692-4a743b570acb.png">

Code:
<img width="608" alt="Screen Shot 2020-06-04 at 2 53 15 PM" src="https://user-images.githubusercontent.com/17481322/83799034-2dea4880-a673-11ea-8f27-8b78cca78ce2.png">

It could be that the fonts are more heavy weighted or possibly an issue with the code mods? Will investigate.

**Comment by redallen** [comment]
I think the outermost `CardTitle` may have been codemodded by mistake and should be `CardHeader`.

For reference:
Old:
```jsx
<Card>
  <CardHead>
    <CardHeadMain>Header</CardHeadMain>
  </CardHead>
  <CardHeader>
    Title
  </CardHeader>
</Card>
```
New:
```jsx
<Card>
  <CardHeader data-codemods="true">
    <CardHeaderMain>Header</CardHeaderMain>
  </CardHeader>
  <CardTitle>
    Title
  </CardTitle>
</Card>
```

**Comment by dlabrecq** [comment]
I changed the code to use `CardHeaderMain` instead of `CardTitle`. Looks better now. Thanks.

<img width="442" alt="Screen Shot 2020-06-04 at 10 08 20 PM" src="https://user-images.githubusercontent.com/17481322/83829037-ffd72980-a6af-11ea-9553-0a73528f2ee6.png">

**Comment by dlabrecq** [comment]
Unless you plan to update the code mod, this can be closed
