### ISSUE TITLE
Stack Layout does not fill space when minHeight is set and greater than parent's height

### ISSUE THREAD

**Issue by Christopher-Chianelli** [patternfly/patternfly-react#4350]
**Describe the issue. What is the expected and unexpected behavior?**
When a parent container uses `minHeight` instead of `height`, The `Stack` layout does not fill the parent's container height.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
1. Set parent container's minHeight to a value larger than the Component's height
2. Add a Stack to the parent container.
3. Observe the stacked elements lie on top of one another instead of spacing out and using
the parent's entire height.

Reproducer:
https://codesandbox.io/s/spring-microservice-l3bjr?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug (although it might be impossible to do with CSS)

**What is your product and what release version are you targeting?**
Affects: `patternfly/react-core: 4.18.5`

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
@Christopher-Chianelli I think you're right re: a CSS solution. For [height: 100%;](https://github.com/patternfly/patternfly/blob/21f79ed0605fc7c72e75f755bcbe0209270d1647/src/patternfly/layouts/Stack/stack.scss#L6) to work, the parent needs either an explicit or implicit height as well.

Here are a couple of ways I would achieve that in CSS:

* Make the parent element a flex column, and set the stack layout to `flex-grow` - https://codepen.io/mcoker/pen/gOPxwNb
  * We could enable a modifier on the stack layout for cases like that by extending the `isFilled` prop to also apply to `<Stack>`, which applies `flex-grow: 1;`. Though it would still be up to you to ensure the parent is a flex layout.
* Make the parent's parent element a flex layout, which gives the parent an implicit height - https://codepen.io/mcoker/pen/yLeoaWo

Would either of those work for you?

**Comment by Christopher-Chianelli** [comment]
@mcoker The first one works for me. Thanks! (Feel free to close since it is probably impossible to do without modifying the parent)

**Comment by mcoker** [comment]
You're welcome!
