### ISSUE TITLE
PF major release: Table headings misaligned

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4363]
Updated to the latest PF4 (breaking changes) packages. Noted an issue with the table column heading alignment.

In the screenshot below, the "Month over month change" and "Cost" headings are misaligned.

<img width="1189" alt="Screen Shot 2020-06-04 at 2 36 44 PM" src="https://user-images.githubusercontent.com/17481322/83797544-d3e88380-a670-11ea-8628-f9a2aad4ddab.png">

<img width="274" alt="Screen Shot 2020-06-09 at 2 46 38 PM" src="https://user-images.githubusercontent.com/17481322/84187457-138fe080-aa60-11ea-8538-32fe4769e742.png">

Note that this was tested with Insights platform, after it had also updated to the same packages.

**Comment by ryelo** [comment]
Just an FYI, i'm looking into this from the cloud.redhat.com side to see if it's possibly a style that we're injected by accident.

**Comment by dlabrecq** [comment]
Met with M. Coker and discovered the issue. This can be closed in favor of https://github.com/patternfly/patternfly/issues/3183
