### ISSUE TITLE
Spinner component isn't applying the classes passed in className prop.

### ISSUE THREAD

**Issue by diwanshi** [patternfly/patternfly-react#4373]
**Describe the issue. What is the expected and unexpected behavior?**
Spinner component isn't applying the classes passed in className prop.
If we try to apply a custom class to a spinner component, those classes are not being applied with the parent span classes  i.e 
```html
<span class="pf-c-spinner pf-m-xl" role="progressbar" aria-valuetext="Loading...">
    <span class="pf-c-spinner__clipper"></span>
    <span class="pf-c-spinner__lead-ball"></span>
    <span class="pf-c-spinner__tail-ball"></span>
</span>
```

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/objective-dust-816u9

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug.
Its not a blocker but we have to write an unnecessary wrapper around the Spinner to include it in our SPAs(more than two atm) where we could've just directly used the Spinner

**What is your product and what release version are you targeting?**
We are working on RedHat Partner Connect Certified Technology Apps. All the SPAs we are developing are part of RHPC i.e https://connect.redhat.com

**Comment by gautamkrishnar** [comment]
I had faced the same problem once, What I did to fix it was adding a wrapper around the spinner, It is not an ideal solution. The spinner should support passing class names.

**Comment by gautamkrishnar** [comment]
Just opened a PR to fix the same
