### ISSUE TITLE
NavItem should make text linkable and not entire list item

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#4378]
**Describe the issue. What is the expected and unexpected behavior?**
We've gotten some feedback that the default browser behavior which shows the URL in the bottom left corner is distracting while hovering around the navigation:
![image](https://user-images.githubusercontent.com/14068621/84424870-afe7ed80-abee-11ea-9679-9035e445defb.png)

The reason for this is because the entire box is a link and not just the text. The fact that `NavExpandable` is also a link adds to this issue (https://github.com/patternfly/patternfly-react/issues/4377).

In comparison to gmail, only the text is made a link while the list item is still clickable as an action. If the user wants to right click and open in a new tab, they need to do so on the link text itself.
eg `Inbox`:
![image](https://user-images.githubusercontent.com/14068621/84425159-1c62ec80-abef-11ea-9772-17b9e55f0e25.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See example: https://www.patternfly.org/v4/documentation/react/components/nav#default

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement

**What is your product and what release version are you targeting?**
OpenShift Console 4.6

**Comment by tlabaj** [comment]
cc @mcoker thoughts on this one?

**Comment by mcoker** [comment]
My initial thought is this doesn't seem like a good best practice. The browser providing a preview of the URL is standard behavior when hovering/focusing on a link, and we would need to replicate behavior that the browser gives you for free by using the correct element (with the issue in https://github.com/patternfly/patternfly-react/issues/4377 aside).

**Comment by christianvogt** [comment]
This was a proposal based on some feedback but I am indifferent to the choice to implement it or not.
Material UI nav component link the entire nav item itself and not just the text similar to PF today.

**Comment by mcoker** [comment]
@christianvogt I reviewed this with the larger team and we agreed this is not something we want to support at this time.
