### ISSUE TITLE
Horizontal form renders buttons in a column

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#4383]
**Describe the issue. What is the expected and unexpected behavior?**

![image](https://user-images.githubusercontent.com/32869456/84650202-111e0280-af08-11ea-822a-88a430fe547f.png)

https://patternfly-react.surge.sh/documentation/react/components/form#horizontal

Buttons should be in a row, not in a column.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug. Blocking.

**What is your product and what release version are you targeting?**

Sources UI
We have a deadline for the upgrade on 7/6/2020.

**Comment by rvsia** [comment]
cc @Hyperkid123 @karelhala

**Comment by Hyperkid123** [comment]
cc @evwilkin @tlabaj

**Comment by evwilkin** [comment]
@tlabaj @mcoker it looks like the horizontal form has these styles applied for all `.pf-c-form__group`, including the `.pf-m-action` element containing the buttons circled in the screenshot above.

Should these styles be overruled for the `.pf-m-action` element?

![Screen Shot 2020-06-15 at 1 20 10 PM](https://user-images.githubusercontent.com/8651509/84687201-51cb4b00-af0b-11ea-9ae8-f3eb97fb69aa.png)

**Comment by mcoker** [comment]
@evwilkin @tlabaj looks like the `.pf-c-forms__actions` element needs to be wrapped in `.pf-c-form__group-control`. Anything that belongs in the form control/elements section (the things on the right in a horizontal form) needs to be wrapped in `.pf-c-form__group-control`.

**Comment by evwilkin** [comment]
@rvsia @Hyperkid123 we're working on getting this into the current milestone for release next week
