### ISSUE TITLE
Prettier printWidth setting

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#439]
Per the slack discussion, I would like to consider moving this repo to a 120 printWidth (and overriding Prettier's default of 80). This seems to be the preference amongst some downstream teams for various reasons.

https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/443
https://prettier.io/docs/en/options.html#print-width

Does anyone have an issue w/ this before we move this direction?

**Comment by jeff-phillips-18** [comment]
works for me!
