### ISSUE TITLE
Modal in docs should use variant instead of size

### ISSUE THREAD

**Issue by DarrienG** [patternfly/patternfly-react#4393]
**Describe the issue. What is the expected and unexpected behavior?**

As of the latest PF, modal uses variant instead of size to describe the size. Current modal docs do not compile.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Can be seen here: https://www.patternfly.org/v4/documentation/react/components/modal/

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug in the docs. Can get around it by knowing the right API.

**What is your product and what release version are you targeting?**

    "@patternfly/patternfly": "^4.10.31",
    "@patternfly/react-core": "4.18.5",

**Comment by redallen** [comment]
Closed by #4385
