### ISSUE TITLE
Code in docs should be checked in CI

### ISSUE THREAD

**Issue by DarrienG** [patternfly/patternfly-react#4396]
**Describe the issue. What is the expected and unexpected behavior?**

Given a few of some of the latest issues I put together:

* https://github.com/patternfly/patternfly-react/issues/4395
* https://github.com/patternfly/patternfly-react/issues/4394
* https://github.com/patternfly/patternfly-react/issues/4393

I think code in docs should ideally be checked during CI. The docs are quite good, but clearly are checked entirely by humans by hand.

This is not ideal and leads to anything from small lint warnings in docs like missing recommended attributes and unused imports to compile errors that make it much more difficult to know if the docs are accurate or not.

I know [Rust does this automagically](https://doc.rust-lang.org/rustdoc/documentation-tests.html) and it's extremely helpful for knowing when you look at generated docs they will work.

Some equivalent for guarantees in docs would be great.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See above issues

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

I think bug is the proper tag for this.

**What is your product and what release version are you targeting?**

    "@patternfly/patternfly": "^4.10.31",
    "@patternfly/react-core": "4.18.5",

**Comment by DarrienG** [comment]
Side note - I believe we do this for internal docs at HubSpot although I'm not totally certain how since I do backend there. I can try and check around in case you folks need some suggestions.

**Comment by redallen** [comment]
We have a `yarn lint:md` target, but ideally we don't write our docs in JS but rather in TS that we can better verify.

**Comment by DarrienG** [comment]
If only. But I see, if there is a target then you're already doing what you can. It's just JS being JS.

Thanks for the response, I'll close this guy out then.
