### ISSUE TITLE
DataToolbar: responsive issue when filters are activated is reproducible on the docs page

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#4397]
**Describe the issue. What is the expected and unexpected behavior?**
Changing the screen size of a datatoolbar with filter components activated has a responsive layout issue with the active filter section of the toolbar. This exists both in product as well as in the examples in the documentation. See screenshots below.
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Shrink browser page width to see the issues detailed in the screenshots below
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug
**What is your product and what release version are you targeting?**
openshift 4.6

![Screen Shot 2020-06-15 at 4 56 07 PM](https://user-images.githubusercontent.com/35978579/84705618-ad0c3600-af29-11ea-9d92-aa8b3efc794b.png)

![image (1)](https://user-images.githubusercontent.com/35978579/84705677-c4e3ba00-af29-11ea-8f6d-48140fa93a66.png)

**Comment by nicolethoen** [comment]
I believe to address this issue, a few things need to be addressed:

- The `breakpoint` prop on `ToolbarToggleGroup` should default to `xl` 
- The `collapseListedFiltersBreakpoint` prop on `Toolbar` should default to `xl`
- all appropriate breakpoints in `OverflowMenu` should also default to `xl`

I have opened an issue in pf core and react to address the wrapping behavior in chip groups. Design will have to consider if there are clever solutions.

**Comment by nicolethoen** [comment]
I believe this is still an issue: waiting for core issue [#3182](https://github.com/patternfly/patternfly/issues/3182) and related to react issue #4404

**Comment by jcaianirh** [comment]
This issue has been fixed by the above core and react issues.
