### ISSUE TITLE
Auditing and Standardizing all OUIA components for WT integration

### ISSUE THREAD

**Issue by psav** [patternfly/patternfly-react#4400]
OUIA attrs need to be added to some components and updated for others to allow integration with widgetastic.

- [x] Alert  #4401
- [x] Breadcrumb  #4401
- [x] Button  #4401
- [x] Chip Group  #4401
- [x] Context Selector  #4401
- [ ] Donut Chart
- [x] Dropdown  #4401
- [x] FormSelect  #4401
- [x] Modal  #4401
- [x] Nav  #4401
- [x] Options Menu  #4401
- [x] Pagination  #4401
- [x] Select  #4401
- [x] Switch  #4401
- [x] Table  #4401
- [x] Tabs  #4401

**Comment by dlabrecq** [comment]
Created `https://github.com/FormidableLabs/victory/pull/1654` to add OUIA props. This should allow us to pass these props to `VictoryContainer`.

**Comment by dlabrecq** [comment]
FYI, my Victory PR (above) was just merged, so we'll update the Victory packages when they become available.
