### ISSUE TITLE
Alert & notification drawer - improved title wrapping

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4407]
https://github.com/patternfly/patternfly/pull/3145/files

You can truncate the alert title (`.pf-c-alert__title`) with `.pf-m-truncate`. Also if enabled, you can set the `--pf-c-alert__title--max-lines` var to specify the number of lines before truncation happens.

Same with `.pf-c-notification-drawer__list-item-header-title` except the var is `--pf-c-notification-drawer__list-item-header-title--max-lines`.

The element `.pf-c-notification-drawer__group-toggle-title` now truncates by default, but you can also specify the number of lines before truncation with `--pf-c-notification-drawer__group-toggle-title--max-lines`

**Comment by boaz0** [comment]
hi @mcoker - what is the diff between this and #4357 ?

**Comment by mcoker** [comment]
@boaz0 doh! Forgot I opened that one, thanks!
