### ISSUE TITLE
Toolbar - update examples to use the actual overflow menu component

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#4420]
the examples currently just use stand in text 'overflow menu' rather than demonstrating how to use it. Many consumers are asking about hiding buttons and other things at different break points without realizing that the capability exists with an Overflow Menu.

**Comment by mattnolting** [comment]
Here are examples I've found
- https://www.patternfly.org/v4/documentation/react/demos/cardview/basic
- https://www.patternfly.org/v4/documentation/react/demos/masterdetaildemo/master-detail-card-view
- https://www.patternfly.org/v4/documentation/react/demos/tablecolumnmanagementdemo
