### ISSUE TITLE
Select - FocusTrap issue causes scrollable menu to jump

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#4421]
reported by a user is with checkbox selects (where the pf-c-select__menu-item element is label.pf-c-check), if you set a maxHeight on the select that is shorter than the select menu (so that the menu scrolls), and you scroll down in the menu a bit, if you click anywhere in the item that is not the <input type="checkbox">, the scroll position in the menu is reset and you're taken to the top of the menu. Clicking on the checkbox seems to work fine.

![image](https://user-images.githubusercontent.com/26305082/85169724-4a24e280-b23a-11ea-8a3c-a5b490c475fe.png)

FocusTrap has a fix in the works but it has not yet been released. [FocusTrap issue #104](https://github.com/davidtheclark/focus-trap/issues/104)
@redallen was made a co-maintainer of FocusTrap to get the fixed released.

**Comment by redallen** [comment]
Yep -- I can merge upstream PRs now! I still need to be given NPM publishing privileges after that.

**Comment by rebeccaalpert** [comment]
This also affects OpenShift - we were looking to switch to PF4 Select two versions ago, but it didn't work out. See https://github.com/patternfly/patternfly-react/issues/4242.

Love to tackle this in a future release!

**Comment by tlabaj** [comment]
We may want  to bring FocusTrap in house.
