### ISSUE TITLE
Select - add support for item description 

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4430]
https://github.com/patternfly/patternfly/pull/3130

If a menu item has a description:

* The `.pf-c-select__menu-item` element adds `.pf-m-description`
* The children of `.pf-c-select__menu-item` are placed in a new element `div.pf-c-select__menu-item-main`
* `div.pf-c-select__menu-item-description` with the user's description is placed after `.pf-c-select__menu-item-main` inside of `.pf-c-select__menu-item`

**Comment by dlabrecq** [comment]
While testing in Cost Management, we discovered some issues with option labels wrapping in the toolbar. See https://github.com/patternfly/patternfly-react/issues/4477
