### ISSUE TITLE
Ability to have radio buttons in tables

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-react#4436]
Currently, tables in PF only support checkboxes. Would be useful to have tables that support radio buttons as well, without having to customize the component!

**Use case in cloud.redhat.com:**
Users have the opportunity to create a role from an existing role, and are presented with a table containing the existing roles they can choose from. They can only choose a single role here, before going to the next step.

![image](https://user-images.githubusercontent.com/51165119/85407058-b2bcd980-b530-11ea-89e8-bbde2ff13d0a.png)

@ryelo

**Comment by tlabaj** [comment]
Issue moved to [patternfly/patternfly-design #884](https://github.com/patternfly/patternfly-design/issues/884) via [**ZenHub**](https://www.zenhub.com/)
