### ISSUE TITLE
Tooltip examples aren't read by VO in Safari

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#4446]
**Describe the issue. What is the expected and unexpected behavior?**
The tooltip examples don't seem to be read in VO when using Safari, except for the positions example. I've noticed that it does currently work in Chrome, but seems to have some difficulty in Safari. It only reads the item that the tooltip is on and then tells you what type of element it is. So in this case, it reads "I have a tooltip" then "You are currently on a text element." I would expect it to read out the tooltip as well.

<img width="1025" alt="Screen Shot 2020-06-24 at 11 50 16 AM" src="https://user-images.githubusercontent.com/28281340/85588686-e8d18a80-b610-11ea-8371-306caab31c4f.png">

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**Comment by thatblindgeye** [comment]
The tooltip examples are resolved in Safari as the examples have been updated to use buttons. Per the epic this is linked to, tooltips on static elements generally aren't well supported so it's less a Safari issue and more an issue with how AT may announce accessible names/descriptions. So this can be closed.

 However I will open a followup issue to investigate the tooltips on MenuItem components as the tooltips aren't being announced in any browser for me there (tested VO and NVDA).
