### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#4462]
We should rename our master branches across all of PatternFly to main.

**Comment by evwilkin** [comment]
Updated recommendation from Github: https://github.com/github/renaming

**Comment by evwilkin** [comment]
Update 9/21 - Github to rename new repos to `main` starting next month, provide steps for updating existing repos to by EOY: https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by evwilkin** [comment]
We're planning on making the switch to `main` when Github provides an automated process for this, sometime before the end of the year.

**Comment by redallen** [comment]
Finished updating today.
