### ISSUE TITLE
FileUpload  onChange getting called twice

### ISSUE THREAD

**Issue by AindriuBrennan** [patternfly/patternfly-react#4463]
I am using the FileUpload component in a React Typescript project to upload a certificate. I noticed that the component was not uploading the certificate correctly and setting a value in the State as null. Investigating the issue in the browser console showed me that the FileUploads  onChange property seems to be getting called twice. I am using the onChange to set the value and the filename, it seems to call the filename first and then onChange is called again for the value, using setState however sets the value as null when the filename is set in the state the first time the onChange is called. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

```   
<FileUpload
            id="certificateFile"
            type={'dataURL'}
            value={this.state.iosCertificate}
            filename={this.state.filename}
            onChange={(value, filename) => {
              let parsedCertificate = parseDataURL(value);
              this.setState({ iosCertificate: parsedCertificate, filename })
              }
            }
   />
```
this is an example of the how I am using the component.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
I believe this might be a bug, and this is the workaround I am using

```
<FileUpload
            id="certificateFile"
            type={'dataURL'}
            value={this.state.iosCertificate}
            filename={this.state.filename}
            onChange={(value, filename) => {
              if (value && (value as string).length > 0) {
                const parsedCertificate = parseDataURL(value);
                console.log({ parsedCertificate, value, filename, type: typeof value });
                this.setState({ iosCertificate: parsedCertificate, filename })
              }
            }
           }
   />
```

**What is your product and what release version are you targeting?**
I am working on the upgrading the UnifiedPush Admin UI to using Patternfly4 v4.18.5

**Comment by boaz0** [comment]
@Aindriunannerb this happens because you're setting the type to 'dataURL' or 'text'. If you do not set it, it will treat it as a file object and it will not show the filename while reading.

You can read more [here](https://patternfly-react.surge.sh/documentation/react/components/fileupload#other-file-types)

@tlabaj I think we can close this unless @Aindriunannerb wants to add anything.

**Comment by boaz0** [comment]
@tlabaj you can close this now.
@AindriuBrennan  if what I suggested [here](https://github.com/patternfly/patternfly-react/issues/4463#issuecomment-688469884) doesn't work for you feel free to re-open this issue.

Thanks
