### ISSUE TITLE
aria-labelledby and tabIndex: Type 'null' is not assignable

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#4467]
**Describe the issue. What is the expected and unexpected behavior?**

When compiling our project using PF, TypeScript fails:

```jsx
node_modules/@patternfly/react-core/dist/js/components/Dropdown/DropdownItem.d.ts:3:18 - error TS2430: Interface 'DropdownItemProps' incorrectly extends interface 'InternalDropdownItemProps'.
  Types of property 'tabIndex' are incompatible.
    Type 'number | null | undefined' is not assignable to type 'number | undefined'.
      Type 'null' is not assignable to type 'number | undefined'.

3 export interface DropdownItemProps extends InternalDropdownItemProps {
                   ~~~~~~~~~~~~~~~~~

node_modules/@patternfly/react-core/dist/js/components/Modal/Modal.d.ts:3:18 - error TS2430: Interface 'ModalProps' incorrectly extends interface 'HTMLProps<HTMLDivElement>'.
  Types of property ''aria-labelledby'' are incompatible.
    Type 'string | null | undefined' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.

3 export interface ModalProps extends React.HTMLProps<HTMLDivElement> {
```

I believe these two lines should not include the null option:

https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Dropdown/DropdownItem.tsx#L34

https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Modal/Modal.tsx#L21

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug

**What is your product and what release version are you targeting?**

"@patternfly/react-core": "^4.18.5",

Data Driven Forms

**Comment by Hyperkid123** [comment]
cc @evwilkin

**Comment by redallen** [comment]
@seanforyou23 and I had a previous issue about this that resulted in `null` should be allowed to not render the `tabIndex` prop in the DOM at all, whereas `undefined` might result in a default `tabIndex` being set. However, this does not match the `React.HTMLProps<HTMLDivElement>` which is just `number | undefined`.

This problem is not unique to `tabIndex`. We could use [Object.prototype.hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#:~:text=Description,in%20the%20object's%20prototype%20chain) but this is not compatible with the default prop syntax we use like `({ propName = 'default' }) => React.ReactElement`.

**Comment by Hyperkid123** [comment]
@redallen can you show an example when `undefined` results in `tabIndex={0}`? I was not aware that is possible. I am curious of how this could happen.

We could do something like this:
```typescript
interface ExtendedHTMLDivElement {
  tabIndex: number | null | undefined;
}

type FooProps = Omit<React.HTMLProps<HTMLDivElement>, "tabIndex"> & ExtendedHTMLDivElement;
```

This will allow us to pass null to the component, but then there will be an error while assigning the tab index to the actual div element. But I suppose you must already handle it.

Here is an example: https://codesandbox.io/s/fancy-grass-6ycxj?file=/src/App.tsx

**Comment by redallen** [comment]
This problem is not specific to React, but to destructured props with default values. [Example.](https://codesandbox.io/s/competent-cloud-do5zm?file=/src/App.js)

**Comment by Hyperkid123** [comment]
Ah gotcha i was missing the default props piece
