### ISSUE TITLE
Select option description property wraps labels

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4477]
The new `Select` option `description` property is wrapping option labels. While in the toolbar, the option width is not expanding to accommodate its longest value.

See https://github.com/patternfly/patternfly-react/pull/4460

**Before**
<img width="610" alt="Screen Shot 2020-07-06 at 11 21 17 AM" src="https://user-images.githubusercontent.com/17481322/86610405-4ce24000-bf7b-11ea-91e6-6df104593871.png">

**After**
<img width="503" alt="Screen Shot 2020-07-06 at 11 20 00 AM" src="https://user-images.githubusercontent.com/17481322/86610416-510e5d80-bf7b-11ea-96b4-7efab319bdc7.png">

cc @kmcfaul

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
@dlabrecq fixed in https://github.com/patternfly/patternfly/pull/3224 if you want to verify.

**Comment by dlabrecq** [comment]
Looks fine now
