### ISSUE TITLE
On mobile the navigation toolbar only disappears when the "kebab" is clicked again

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#4480]
When a user on mobile uses the page navigation to navigate to a particular "page" the navigation bar does not hide after the navigation is complete. Nor does it disappear when the "page" that is in the background is clicked. The only way to get rid of it is by clicking the kebab item again. This is not very user friendly and not on par with other mobile websites.

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
Yes, I agree. This feels like a bug. I will add this to the next sprint to take a look at @tlabaj .

**Comment by redallen** [comment]
This is a problem that needs solving on patternfly.org as well. I'll pick it up and add this functionality to the `isManagedSidebar` prop for small viewports.
