### ISSUE TITLE
DataListAction should be converted to Functional Component

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#4489]
**Describe the issue. What is the expected and unexpected behavior?**
DataListAction. has a state that is never used.  It also has an onSelect and onToggle function that are not used.  These should be removed and the component should be functional instead os class.  This is a breaking change since the state is exported.

**Comment by redallen** [comment]
I don't think the interface for the state is exported. We declared it as private to `DataListAction.tsx`:
```tsx
interface DataListActionState {
  isOpen: boolean;
}
```

In this case it's not breaking.
