### ISSUE TITLE
Documentation for Drawer is wrong - Panel on left should be Panel on right

### ISSUE THREAD

**Issue by wojta** [patternfly/patternfly-react#4496]
**Describe the issue. What is the expected and unexpected behavior?**
Wrong text in the documentation. Copy & paste issue. 
_Panel on left_ should be _Panel on right_
_Inline panel on left_ should be _Inline panel on right_

![image](https://user-images.githubusercontent.com/2912228/86919176-1e559800-c128-11ea-943e-5f0a990cf36b.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
1. At current release 2020.08 go to page:
https://www.patternfly.org/v4/documentation/react/components/drawer

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
2020.08

**Comment by tlabaj** [comment]
closed by #4473
