### ISSUE TITLE
Drawer should not render contents unless expanded

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#4498]
**Describe the issue. What is the expected and unexpected behavior?**
The contents of a `Drawer` are rendered regardless of whether the drawer is opened or closed. There should at least be an option for the drawer to not render the panel contents when collapsed. But TBH I'm not sure what use case you would ever need the contents present unless the drawer is expanded. The reason for not rendering the contents is because they could be expensive to render and / or be network chatty. This is unnecessary if the contents are not visible to the user.

A workaround is to conditionally render the `panelContents` if the drawer is expanded or not. However this has a side effect of losing the animation. The `Drawer` component should render the content immediately before opening and perform the open animation. On collapsed, the `Drawer` should animate closed and then unmount the contents.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See patternfly react documentation samples:
https://patternfly-react.surge.sh/documentation/react/components/drawer

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
I see this as a Bug because the workaround loses the animation.

**What is your product and what release version are you targeting?**
OpenShift 4.6

**Comment by redallen** [comment]
I believe it was implemented this way [in Core](https://pf4.patternfly.org/documentation/core/components/drawer) for easier development (just adding `pf-m-expanded` opens the drawer).

We can fix it in React.

**Comment by seanforyou23** [comment]
If we try to fix this on React side, won't we then have two different approaches on how Drawer is documented between Core and React (in terms of markup structure)? Core docs would be suggesting to include the markup for the drawer and rely on the animation/styling to hide it from users when collapsed but React implementation would show a version where the markup isn't rendered at all. I think we need alignment here. If we can go with the strategy of not rendering/initializing the Drawer markup unless it's expanded (which I agree is the way to go) then we can remove the need for [this animation](https://github.com/patternfly/patternfly/pull/3184/files#diff-73c2fdc37522181d1a4b03d1a9cad3d0R207-R211) on core side, that, while it works great, is a bit unconventional.

**Comment by christianvogt** [comment]
There's nothing wrong with the animation unless you want to do it through some other means (eg react-transition-group). This animation can still work if the (un)mounting order is performed as described in https://github.com/patternfly/patternfly-react/issues/4498#issue-653425331

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by seanforyou23** [comment]
@christianvogt agree there's nothing wrong with the animation, I was just pointing out that it's strange to rely on this solely for the display given the other constraints/complications it presents. So maybe not "remove the need for that animation" but instead "not solely rely on the animation for facilitating the display". Good catch!

**Comment by redallen** [comment]
@seanforyou23 Yes we'll have different approaches, but this isn't the first time we conditionally render in React components that are hidden behind `visible` or `hidden` CSS in Core. It'd be nice if Core could conditionally hide components without having to write a new example each time. Perhaps a templating system other than handlebars could help, but that's a separate issue.

**Comment by seanforyou23** [comment]
I get it, just doing my part to try and keep the implementations aligned where possible. Just because it's something we're doing currently doesn't necessarily mean it's the best strategy. If a consumer is using another framework, let's say Angular, and they want to implement Drawer, keep in mind the current recommendation is to reference core to see what the markup strategy should be. If users do this, they'd be following down a similar road where they'll be met with these same issues. If we adjusted core to reflect what we plan to do in React, other JS implementations could also reference the same core examples without re-creating this same issue regarding unnecessary renders which could be expensive. Just food for thought!
