### ISSUE TITLE
ToolbarItem visibility prop spelled visiblity

### ISSUE THREAD

**Issue by ryelo** [patternfly/patternfly-react#4499]
**Describe the issue. What is the expected and unexpected behavior?**

`ToolbarItem` has a prop `visiblity` which should be `visibility`

https://github.com/patternfly/patternfly-react/blob/652b4161222f6a07a1c2c9de1e5ab1213857709f/packages/react-core/src/components/Toolbar/ToolbarItem.tsx#L32

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
cloud.redhat.com

**Comment by ryelo** [comment]
This actually looks like it takes place in other Toolbar components too.

https://github.com/patternfly/patternfly-react/blob/652b4161222f6a07a1c2c9de1e5ab1213857709f/packages/react-core/src/components/Toolbar/ToolbarContent.tsx#L12
https://github.com/patternfly/patternfly-react/blob/652b4161222f6a07a1c2c9de1e5ab1213857709f/packages/react-core/src/components/Toolbar/ToolbarGroup.tsx#L18
https://github.com/patternfly/patternfly-react/blob/652b4161222f6a07a1c2c9de1e5ab1213857709f/packages/react-core/src/components/Toolbar/ToolbarToggleGroup.tsx#L18

**Comment by tlabaj** [comment]
This would break the API.  We can however add a second prop with the correct spelling and deprecate the the misspelled.  prop

**Comment by tlabaj** [comment]
issue #4501 has been opened to add the new correctly spelled props.

**Comment by nicolethoen** [comment]
closed by #8212
