### ISSUE TITLE
Select - placeholderText prop doesn't work as intended

### ISSUE THREAD

**Issue by divyanshiGupta** [patternfly/patternfly-react#4511]
**Describe the issue. What is the expected and unexpected behavior?**
`ReactElements` are not correctly rendered in `Select` placeholder even though the `placeholderText` prop is of type `ReactNode` so technically all types of `ReactNodes` must be supported.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/tender-buck-ltvi0

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. Using `Select` in PR - https://github.com/openshift/console/pull/5875 and wanted to keep the placeholder consistent with other drop-downs by using the same placeholder element here as well. No work-around.

**What is your product and what release version are you targeting?**
Openshift Container Platform v4.6

**Comment by KKoukiou** [comment]
This behavior you describe only exists in SelectVariant.typeaheadMulti && SelectVariant.typeahead variants.

The problem with actually allowing React.ReactNode and React.Element here, is that that is directly passed to the `placeholder` attribute of the `input` element. This of course can't accept anything else than string.

Unless someone has a better idea on how to fix that, I really don't see a way of supporting non string placeholders on the text input element of the typeahead.

@jschuler maybe you have a better idea?
