### ISSUE TITLE
uncontrolled Popover not as responsive to show / hide as controlled

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#4515]
**Describe the issue. What is the expected and unexpected behavior?**
Tested on https://github.com/patternfly/patternfly-react/pull/4491
When using a `Popover` in an uncontrolled manner by not specifying `isVisible`, the `Popover` isn't as responsive to show / hide state updates. For example, using the first `Popover` example in the documentation. Quickly clicking the button 3 times should result in `open -> close -> open` however it results in it being closed.

By converting this example to controlled via the following snippet. The state updates quickly and as expected.
```
import React from 'react';
import { Popover, PopoverPosition, Button } from '@patternfly/react-core';

SimplePopover = () => {
const [ open, setOpen] = React.useState(false);
return (
  <div style={{ margin: '100px' }}>
    <Popover isVisible={open}
      headerContent={<div>Popover Header</div>}
      bodyContent={
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id feugiat augue, nec fringilla turpis.</div>
      }
      footerContent="Popover Footer"
    >
      <Button onClick={() => setOpen(!open)}>Toggle Popover</Button>
    </Popover>
  </div>
);
}
```

Whether controlled or uncontrolled variants are used, the behavior should be the same.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**Comment by christianvogt** [comment]
Still an issue.

**Comment by christianvogt** [comment]
Bunp. Still an issue.

**Comment by CooperRedhat** [comment]
https://user-images.githubusercontent.com/87719785/127872617-31056e45-c123-450d-88fc-9260a183278f.mov

@christianvogt I'm seeing the same behavior on controlled and uncontrolled instances, using the triple click `open -> close -> open`. 

However:
A double click from closed state `open -> close` results in `closed` as expected.
A double click from open state `close -> open` results in `closed` which is unexpected.

**Comment by CooperRedhat** [comment]
Found a workaround: `animationDuration={0}`
