### ISSUE TITLE
Add tile component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4524]
New component! https://github.com/patternfly/patternfly/pull/3238

Some interaction details are in the design in the original issue - https://github.com/patternfly/patternfly/issues/3100

* Only title is required
* Component is a `div` with `tabindex="0"` so it's focusable
* It can be:
  * selected via `.pf-m-selected`
  * disabled via `.pf-m-disabled`
  * can have a stacked layout via `.pf-m-stacked` on `.pf-c-tile__header`
  * set to a larger variation via `.pf-m-display-lg` (if the header is stacked)

cc @christiemolloy

**Comment by mcarrano** [comment]
@kmcfaul there are two scenarios for usage of this component. It will be typically used to select between a set of options. It could be used to select one or more options like a set of checkboxes or mutually exclusive selection like a set of radio buttons. I will be on PTO during the week of July 20, but please reach out to @maryshaks1996 if you have design questions.
