### ISSUE TITLE
Notification drawer demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4535]
Follow on to https://github.com/patternfly/patternfly/issues/3186 for adding a notification drawer demo in React. Should demonstrate behavior of the drawer integrated into a page including the notification badge with latest updates (#4323 

cc @mcoker @tlabaj

**Comment by nicolethoen** [comment]
usage and behavior documentation: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/notification-drawer/
