### ISSUE TITLE
Wizard finished step demo has broken styling

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#4537]
**Describe the issue. What is the expected and unexpected behavior?**

Finished step demo in the documentation is broken.

![demo](https://user-images.githubusercontent.com/32869456/87414128-9100c080-c5cb-11ea-9612-32ea158c7ed5.gif)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

1. Go to https://www.patternfly.org/v4/documentation/react/components/wizard#finished
2. Checkout the demo

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
@tlabaj that's odd. The rendered wizard code is missing `div.pf-c-empty-state__content` that wraps all of the children in `div.pf-c-empty-state`. 

The [finished page empty state code](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Wizard/examples/FinishedStep.js) looks OK.

And looks like `div.pf-c-empty-state__content` is in the [empty state component code](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/EmptyState/EmptyState.tsx), and the [empty state examples](https://www.patternfly.org/v4/documentation/react/components/emptystate) look OK.

We added that element in the v4 breaking change release. Do you know why that instance of empty state wouldn't be rendering the `div.pf-c-empty-state__content`?

**Comment by jschuler** [comment]
Looks to be fixed in this release?
https://patternfly-react.surge.sh/documentation/react/components/wizard#finished

**Comment by KKoukiou** [comment]
It's already fixed on https://www.patternfly.org/v4/documentation/react/components/wizard#finished at least:

https://www.patternfly.org/v4/documentation/react/components/wizard#finished
