### ISSUE TITLE
"Shift click select" for table row selections

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-react#4540]
Request to add ability to select multiple rows in a table at once using the shift click functionality on keyboard.
Demo of this here:
![shift-click select](https://user-images.githubusercontent.com/51165119/87439791-2d709600-c5bf-11ea-91ae-f9cb20725032.gif)

We would like to add this functionality to cloud.redhat.com tables.

FYI: @ryelo @evwilkin @mcarrano @kendraMar

**Comment by tlabaj** [comment]
closed by #6032
