### ISSUE TITLE
Select: A typeahead Select breaks when the options are grouped

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#4541]
When a user begins typing in a `typeahead Select` with `isGrouped` set to true, the component crashes.

It appears that the `typeaheadFilteredChildren` do not account for the children existing in `SelectGroup` components. It assumes a flat list of options. The `SelectGroup` does not have a `value` prop so setting `typeaheadFilteredChildren` fails.
https://github.com/patternfly/patternfly-react/blob/9382cff5b2e403628aa1db4dd017875740693a59/packages/react-core/src/components/Select/Select.tsx#L207

**Comment by tlabaj** [comment]
Fixed will be tracked by issue #4590
