### ISSUE TITLE
Adding isManagedSidebar causes warnings 

### ISSUE THREAD

**Issue by MariaAga** [patternfly/patternfly-react#4549]
**Describe the issue. What is the expected and unexpected behavior?**
Adding isManagedSidebar prop causes warnings/errors
in header
```
index.js:2177 Warning: React does not recognize the `isManagedSidebar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ismanagedsidebar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in header (created by Context.Consumer)
    in PageHeader (created by VerticalPage)
    in div (created by Page)
    in Page (created by VerticalPage)
```
and in the sidebar
```
Warning: React does not recognize the `isManagedSidebar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ismanagedsidebar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Context.Consumer)
    in PageSidebar (created by VerticalPage)
    in div (created by Page)
    in Page (created by VerticalPage)
    in VerticalPage (created by ErrorBoundary)
```
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

just add `isManagedSidebar` to the example here: 
https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Page/examples/Page.md
```js
     <PageHeader
        isManagedSidebar
        logo="Logo"
        logoProps={logoProps}
        headerTools={<PageHeaderTools>header-tools</PageHeaderTools>}
        showNavToggle
        isNavOpen={isNavOpen}
        onNavToggle={this.onNavToggle}
      />
```
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug

**Comment by boaz0** [comment]
hey @MariaAga - it is indeed a bug. However, a workaround is to pass `isManagedSidebar` to `Page`.
I believe `isManagedSidebar` is going to be deprecated in the next version of PF4.

@tlabaj @nicolethoen - can you assign this to me, I think I know how to fix this.

**Comment by MariaAga** [comment]
@boaz0 When I pass it to Page then `isNavOpen` and `onNavToggle` don't work. How will it work in the next version instead?

**Comment by boaz0** [comment]
`isNavOpen` and `onNavToggle` are passed through `Page` too?

**Comment by MariaAga** [comment]
When `isNavOpen` and `onNavToggle` are passed through Page they are ignored and also the following errors are shown:
```
Warning: React does not recognize the `isNavOpen` prop on a DOM element. 
If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isnavopen` instead. 
If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Page)
    in Page (created by Layout)
```
`Warning: Unknown event handler property `onNavToggle`. It will be ignored.
    in div (created by Page)`

**Comment by boaz0** [comment]
Umm, what version of PF4 are using?

**Comment by MariaAga** [comment]
@patternfly/react-core@4.32.1

**Comment by boaz0** [comment]
OK - if you want PF4 to control the sidebar state (open/close) pass `isManagedSidebar` in the `Page` component.
I do not see any reason to put `isManagedSidebar` in `PageHeader` and seems like a mistake.

//cc @dtaylor113 - can you take a look at this?
thanks.
