### ISSUE TITLE
Update user menu example to include Avatar and not user icon

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4551]
This example should be showing how an Avatar component can be integrated into a dropdown to create a user menu. https://www.patternfly.org/v4/documentation/react/components/dropdown#dropdown-with-image-and-text  This will make it consistent with the core example, also.

cc @tlabaj

**Comment by mcarrano** [comment]
@tlabaj Looks like this was done?

**Comment by tlabaj** [comment]
closed by #4566
