### ISSUE TITLE
Adding className to Tab overrides default styling

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#4567]
**Describe the issue. What is the expected and unexpected behavior?**
When adding a `className` property `Tab` component, append it to initial className list

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Add className to `Tab` component
```jsx
<Tab className="foo" ... />
```
results in: 
![screenshot-www patternfly org-2020 07 17-10_28_31](https://user-images.githubusercontent.com/22619452/87765614-517ae400-c818-11ea-90d6-010bde7fba85.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
CRC. PF version: @patternfly/react-core@4.23.1

**Comment by karelhala** [comment]
ping @tlabaj @jschuler
