### ISSUE TITLE
Error when SelectGroup contains only one SelectOption

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#4592]
**Describe the issue. What is the expected and unexpected behavior?**
Error when `SelectGroup` contains only one `SelectOption`

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
In page https://www.patternfly.org/v4/documentation/react/components/select
1. change `JSX` code for `Grouped single` to contain only one `SelectOption`
2. click on the rendered result above
3. the rendered select disappears and an error appears - see below:
![single-select-option](https://user-images.githubusercontent.com/16188254/88060804-fa9e4300-cb66-11ea-9132-69bdfb80f755.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug.

**What is your product and what release version are you targeting?**

**Comment by KKoukiou** [comment]
Closes by #4622
