### ISSUE TITLE
Add new attention state icon for NotificationBadge

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#4593]
Follow-up to https://github.com/patternfly/patternfly-design/issues/895 & related Core issue https://github.com/patternfly/patternfly/issues/3308

We need to add the new bell w/exclamation mark icon to react-icons for use in NotificationBadge enhancements https://github.com/patternfly/patternfly-react/issues/4431

**Comment by mcoker** [comment]
@evwilkin the core work is done in https://github.com/patternfly/patternfly/pull/3309

**Comment by evwilkin** [comment]
Closing - React has already been updated to include these changes, new icon is [reflected in the workspace](http://patternfly-react.surge.sh/icons).  Website updates to add text for new icon will be handled in https://github.com/patternfly/patternfly-org/issues/1980.

**Comment by mcoker** [comment]
@evwilkin do you know what the icon name is? I'm trying it out as the tooltip text that displays over the icon (`AttentionBellIcon`) but am getting this. I'm trying to verify that `<BellIcon />` and `<AttentionBellIcon />` can be used in place of one another on the fly and there is no shifting or anything that happens.

<img width="705" alt="Screen Shot 2020-07-27 at 4 38 37 PM" src="https://user-images.githubusercontent.com/35148959/88594926-bc51c980-d027-11ea-808e-d7a0cee2fe0a.png">

**Comment by evwilkin** [comment]
@mcoker it looks like you have the right name, you may need to update to more recent prerelease versions to get the icon - here are the latest versions and a working example:

https://codesandbox.io/s/naughty-herschel-yj158?file=/index.js
![Screen Shot 2020-07-28 at 9 52 36 AM](https://user-images.githubusercontent.com/8651509/88674801-4184bf00-d0b8-11ea-90ff-8f7d7ce97d2c.png)

**Comment by mcoker** [comment]
Perfect, thanks @evwilkin!!
