### ISSUE TITLE
Add an 'update' variant to 'Alert'

### ISSUE THREAD

**Issue by megan-hall** [patternfly/patternfly-react#4594]
It would be great to add the 'update' variant to the teal general 'Alert' so that we have the ability to swap out the bell icon for the up arrow icon.

OpenShift console is currently using the 'update' variant for the 'alert' in the notification drawer which allows us to replace the bell icon with the up arrow icon. We have hacked a work around for the time being as this work is apart of the 4.6 release. 

Spoke with Christie and it seems like we could pass through a custom icon into the default alert type.

See screenshot below of what the current limitation looks like (the bell icon cannot be changed):
<img width="1256" alt="screen_shot_2020-07-21_at_10 00 23_am" src="https://user-images.githubusercontent.com/62031580/88077109-e4818a00-cb48-11ea-8e06-7ee6e3eaf840.png">

See screenshot below of what we would like to be able to do (replace the bell icon with the up arrow to match the notification in the notification drawer):
![About-Modal-Teal](https://user-images.githubusercontent.com/62031580/88077034-cfa4f680-cb48-11ea-9fbe-9168bf36b786.png)

**Comment by megan-hall** [comment]
FYI @rhamilto

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@megan-hall We currently have a request on our roadmap for a more flexible alert here: https://github.com/patternfly/patternfly-design/issues/861  Would this satisfy your use case?

**Comment by megan-hall** [comment]
> @megan-hall We currently have a request on our roadmap for a more flexible alert here: [patternfly/patternfly-design#861](https://github.com/patternfly/patternfly-design/issues/861) Would this satisfy your use case?

@mcarrano yes! I believe it would. cc @rhamilto just to make sure.

**Comment by mcarrano** [comment]
@tlabaj up to you whether you want to keep this open or close and open a new issue once this passes through core implementation. We currently have a core issue open here: https://github.com/patternfly/patternfly/issues/3257

**Comment by rhamilto** [comment]
> > @megan-hall We currently have a request on our roadmap for a more flexible alert here: [patternfly/patternfly-design#861](https://github.com/patternfly/patternfly-design/issues/861) Would this satisfy your use case?
> 
> @mcarrano yes! I believe it would. cc @rhamilto just to make sure.

Yep.  That seems like a good option.

**Comment by tlabaj** [comment]
[Custom icons](https://www.patternfly.org/v4/components/alert#custom-icons) have been added to alerts (PR #5140) so I will be closing this issue.  Please feel free to open another issue if you are looking for additional enhancements.
