### ISSUE TITLE
GitHub release does not include lib / support Bower

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#46]
I noticed that patternfly-react has a transpiled lib directory, but it's only available if you install the npm package. 

For example, when I download the Github release for 0.5.0, the lib directory cannot be found -- only the source is available. This is true whether I download the zip, tar, or select the tag for https://github.com/patternfly/patternfly-react/tree/v0.5.0

Considering there are Github releases available, I'm expecting the lib directory to be included in the download.

**Comment by priley86** [comment]
thanks for noting this @dlabrecq. 

I don't think this is super pressing at the moment (as I believe most of our consumers in the React community have adopted NPM), but in the future once we've adopted Storybooks in `patternfly-ng` and `patternfly-webcomponents` (more details in our PR [there](https://github.com/patternfly-webcomponents/patternfly-webcomponents/pull/65)) i'm happy to revisit this for ensured Bower support. 

I'll leave this issue open until we get there...

**Comment by priley86** [comment]
Also please note that we are currently using npm@5 here and will no longer need the `shrinkwrap`.

**Comment by dlabrecq** [comment]
I just want to clarify that the GitHub release isn't necessarily to support Bower. My point is that the released GitHub download simply doesn't contain the released lib files. Regardless if we support bower, the download should probably have right files for the release.
