### ISSUE TITLE
Select: basic multiple select

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#4604]
Select should either have a variant that looks like `single` but supports multiple selections, or `single` should be updated to support both a single selection and multiple selections. 

If `single` would be updated, we many want to consider renaming the variant in a future breaking change release.

**Comment by kmcfaul** [comment]
@mcarrano Would this enhancement make sense design-wise?

**Comment by mcarrano** [comment]
@kmcfaul So do you mean that we should have a multi-select option that is different from the Checkbox select? I could see allowing for that, but I'm curious if you have a use case where the checkbox selection would not work. I've been working on an approach to refactor the dropdown components somewhat to be more modular. That's described here: https://docs.google.com/document/d/1GyVgog_SbErqbYyF08_N2rfLDUgwAVbdKP5udBjdxYI/edit?usp=sharing  Feel free to comment on that.

**Comment by kmcfaul** [comment]
@bipuladh linked an issue where this use case is desired.

Would adding this new variant be fine for the interim until we refactor a more modular dropdown?

**Comment by mcarrano** [comment]
@kmcfaul @bipuladh I'm still confused as the linked designs seem to show examples of single select lists. What am I missing?

**Comment by bipuladh** [comment]
![Screenshot from 2020-07-30 11-27-38](https://user-images.githubusercontent.com/54092533/88886263-b3473f00-d257-11ea-9a58-7ac03b283f95.png)
So in the second Select List, we want behaviour where we can select multiple items but not show the chip groups and instead show a custom Text. This is currently not possible in Typeahead multi-select. 

The two ways I see we can tackle this is either by allowing the SIngle variant to accept an array of selected items and behave accordingly or give a prop to typeahead multi to hide the chip group, close button and instead show the custom text as shown in the Single variant.

**Comment by mcarrano** [comment]
Thanks for sharing this @bipuladh as it makes it very clear what you are looking for. We currently have a component called an Options menu that allows multiple selections like this. Take a look at https://www.patternfly.org/v4/documentation/react/components/optionsmenu#multiple-options  It seems like this would work well for your use case, but let me know what you think.

**Comment by bipuladh** [comment]
Thanks, @mcarrano for pointing me in the right direction. I tried the component and it works as expected.
https://github.com/openshift/console/pull/6174
/close
