### ISSUE TITLE
Table: provide a way to have more complicated actions as Table's  last column cells

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#4612]
In [cockpit](cockpit-project.org/) we have a Table whose last column incorporates some actions.
See the screenshot which is self explanatory.
![Screen Shot 2020-07-24 at 10 11 20](https://user-images.githubusercontent.com/14921356/88372498-4daa0d00-cd96-11ea-90e1-d9397a9cf562.png)

I was trying to implement that we the `actions` or `actionResolver` properties of the Table component without luck since that's limiting us to use kebab only. So please either allow actions to be more generic or provide a way to add custom classes to rows cells, so that we can add the `pf-c-table__action` class to that last column cells.

**Comment by tlabaj** [comment]
cc @jschuler @nicolethoen
