### ISSUE TITLE
Maximum call stack size exceeded in a read-only typeahead Select field when pressing enter

### ISSUE THREAD

**Issue by jerolimov** [patternfly/patternfly-react#4615]
**Describe the issue. What is the expected and unexpected behavior?**

When creating a typeahead Select field which do not support new items (no isCreatable prop) the components crashs when the user types an entry which does not exist and press enter the application crashs with an "Maximum call stack size exceeded" error.

* If you have the values aaaaa, bbbbb, .... Entering aaa and press enter works and selects the entry aaaaa.
* But when you enter eee, no entry was shown. If you then press enter the error above was thrown.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Codesandbox to reproduce the error: https://codesandbox.io/s/elegant-hofstadter-omfke?file=/index.js

```jsx
import ReactDOM from "react-dom";
import "@patternfly/react-core/dist/styles/base.css";

import * as React from "react";
import { Select, SelectVariant, SelectOption } from "@patternfly/react-core";

const YourIssue = () => {
  const [isOpen, setIsOpen] = React.useState(false);
  const [options] = React.useState(["aaaaa", "bbbbb", "ccccc"]);
  const [value, setValue] = React.useState("aaaaa");

  const onToggle = () => setIsOpen(!isOpen);
  const onSelect = (_, selection) => {
    setValue(selection);
    setIsOpen(false);
  };
  const onClear = () => setValue(null);
  const onCreateOption = () => setValue(null);

  return (
    <div style={{ padding: "40px" }}>
      <Select
        variant={SelectVariant.typeahead}
        placeholderText="Placeholder"
        selections={value}
        isOpen={isOpen}
        isCreatable={false} // Works with true!
        onCreateOption={onCreateOption}
        onToggle={onToggle}
        onSelect={onSelect}
        onClear={onClear}
      >
        {options.map(option => (
          <SelectOption key={option} value={option}>
            {option}
          </SelectOption>
        ))}
      </Select>
    </div>
  );
};

ReactDOM.render(<YourIssue />, document.getElementById("root"));
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
No workaround other than enable isCreatable

**What is your product and what release version are you targeting?**
OpenShift

**Comment by jerolimov** [comment]
PR: https://github.com/patternfly/patternfly-react/pull/4616

**Comment by tiagojufr** [comment]
This issue still exists in a different scenario:
1. Open a typeahead select
2. Type something that does not match any option until you see the `No results found` message
3. Start pressing the up/down keyboard arrow repeatedly
4. The browser console will show that `Maximum call stack size exceeded` error

Should I create a separate bug for this scenario?

**Comment by jerolimov** [comment]
@tiagojufr Yes please. And if you have an idea how to fix it a PR is always welcome as well. But someone will check your new bug and hopefully solve it soon. Feel free to ping me in your new bug as well.
