### ISSUE TITLE
A11y: PageHeader Burger Button Needs Discernable Text

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-react#4638]
**Describe the issue. What is the expected and unexpected behavior?**
All buttons need some sort of text for non-visual users, if you inspect the example in the docs there is no text, I don't think there's a way to add text to it?

https://www.patternfly.org/v4/documentation/react/components/page

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, not blocking.

**Comment by tlabaj** [comment]
cc @jessiehuff

**Comment by jessiehuff** [comment]
Hey @wesruv! 🙂 Just wanted to check in and get a better understanding of what you're seeing. Currently the PageHeader burger button has an `aria-label` that should make it discernible to screen readers. With a quick test of VO, I'm seeing it read as "Global navigation, collapsed, button". Or are you thinking of tooltips on icons? I've heard that brought up before from the design perspective, but I believe that's typically only common on icons that are not widely known. Can you point out what you're seeing?

**Comment by wesruv** [comment]
Ahh, crap. I'm so wrong! I'm not sure what I was seeing, but I was convinced at the time.

Thanks for your effort, sorry about that!

**Comment by jessiehuff** [comment]
@wesruv No worries at all! Always appreciate people taking a look at our accessibility! 😄
