### ISSUE TITLE
eslint-plugin-patternfly-react: ESLint couldn't find the config "plugin:react-hooks/recommended" to extend from

### ISSUE THREAD

**Issue by sharvit** [patternfly/patternfly-react#4644]
**Describe the issue. What is the expected and unexpected behavior?**

I am trying to upgrade the `eslint-plugin-patternfly-react` from v0.3.0 to v4.1.2 and getting this error when running eslint:
```
Oops! Something went wrong! :(
ESLint: 7.6.0
ESLint couldn't find the config "plugin:react-hooks/recommended" to extend from. Please check that the name of the config is correct.
The config "plugin:react-hooks/recommended" was referenced from the config file in "/home/vagrant/foreman-js/node_modules/eslint-plugin-patternfly-react/lib/index.js".
If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
See in the CI: https://github.com/theforeman/foreman-js/pull/189/checks?check_run_id=939905158#step:8:22

Also, you can test with my PR (just clone and `npm i && npm run lint`):
https://github.com/theforeman/foreman-js/pull/189

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, couldn't find any workaround except downgrading the pf-eslint-plugin.

**What is your product and what release version are you targeting?**
https://github.com/theforeman/foreman-js

Thanks!

**Comment by redallen** [comment]
This is an [upstream issue](https://github.com/facebook/react/issues/18208) that can be fixed by our upgrading `eslint-plugin-react-hooks` or you manually specifying it in your package.json.
