### ISSUE TITLE
Clear button on type-ahead select should always clear selection

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4648]
Expect the clear (x) button on the [Type-ahead select](https://www.patternfly.org/v4/documentation/react/components/select#typeahead) component to always clear the selected value(s) whenever a selection has been made or when the user is typing a new selection. Currently it only clears the field when entering text from the keyboard but does nothing when clicked at other times.

**Comment by tlabaj** [comment]
there was an issue in the example code that was resolved in the PR.  this is not an issue.
