### ISSUE TITLE
Cannot resolve symbol 'XXX' on import

### ISSUE THREAD

**Issue by ia3andy** [patternfly/patternfly-react#465]
IntelliJ Ultimate is not able to resolve patternfly-react imports:
![image](https://user-images.githubusercontent.com/2223984/42576661-3d4cb8d0-8523-11e8-90a2-ff9acfaca056.png)

It seems to be resolving `patternfly-react/dist/js` instead of `patternfly-react/dist/esm` folder.

Please note that I don't have any problem if I use react-boostrap components.

Could someone help me?

**Comment by ia3andy** [comment]
I am using the demo app: https://github.com/patternfly/patternfly-react-demo-app

**Comment by priley86** [comment]
welcome and thanks for reporting this...

I haven't tried this w/ IntelliJ before. Do you see the same thing in VS Code? I'm curious if there are any IntelliJ settings we could specify. The Dropdown is just re-exported from react-bootstrap in patternfly-react. It should be available though... I would also double check that deleting `node_modules`, re installing `yarn install`, and restarting your IDE does not fix it...

**Comment by ia3andy** [comment]
Hi @priley86,

Sorry I was in PTO :)

Thanks for answering, I don't use VS Code but a friend of mine does and told me it's nearly the same problem there since you can't follow link on the patternfly-react imports (but no warning).

I tried restarting and all you said..

Cheers,
