### ISSUE TITLE
Table: support for pf-m-no-padding on th cells

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4657]
I'm not sure if there is any react follow up work needed for this enhancement, but we recently extended the ability to apply the `.pf-m-no-padding` class to `.pf-c-table__expandable-row > th`, where we previously only supported the class on `.pf-c-table__expandable-row > td`.

For reference, here is the core PR - https://github.com/patternfly/patternfly/pull/3323

**Comment by jschuler** [comment]
Verify if this is still an issue
