### ISSUE TITLE
Inline edit for description list

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4673]
Want to support editable fields in a definition list (re-only form) allowing user to place either a single field or an entire form into edit mode.

Design doc: https://docs.google.com/document/d/15aOWgpkd0Zp0hvbKM4jfG6Jf00FHjY_f92bkosbo1Ds/edit?usp=sharing

Design issue: https://github.com/patternfly/patternfly-next/issues/295

cc: @rachael-phillips @mcoker Not sure if this is a new component or just a demo

**Comment by ncameronbritt** [comment]
@mcarrano any update when this might be available?

**Comment by mcarrano** [comment]
I don't have an ETA right now @ncameronbritt . Do you have specific dates when this is needed?

**Comment by ncameronbritt** [comment]
@mcarrano no specific date. We are getting by without it for now.
