### ISSUE TITLE
Victory Charts performance issues

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#4679]
Related OpenShift Dev Console issue: https://issues.redhat.com/browse/ODC-4421

> There are graph performance issues in both the Monitoring dashboards and the Metrics tab...it sounds like preliminary investigation indicates that the performance issues are due to Victory charts. Victory is the charting subsystem utilized by PatternFly.

Explore performance issues related to Victory Charts.

**Comment by dlabrecq** [comment]
Related:

Victory performance update
https://github.com/patternfly/patternfly-react/issues/4119

Using PondJS for large data sets
https://github.com/patternfly/patternfly-react/issues/3429

**Comment by evwilkin** [comment]
Resolved in https://issues.redhat.com/browse/ODC-4421
