### ISSUE TITLE
table body cell truncation not working on cell HTML element

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#4682]
Using the truncation transform works as expected for cells only containing string, e.g. `rows: [ 'cell A' ]`
but if the cell is an HTML element, the truncation is not working
`rows: [ { title: <div>cell A</div> } ]`

Example:
https://codesandbox.io/s/nifty-mahavira-7sezb?file=/index.js

**Comment by michpetrov** [comment]
I don't think this is a bug. The truncation is achieved by having `text-overflow: ellipsis` on the table cell, however that works only on inline elements. In order for this to work you'd have to use 
```
<div style={{display: "inline"}}>This text will truncate instead of wrap.</div>
```
I haven't checked the code but I think the transformers are agnostic of the cell content.

**Comment by jschuler** [comment]
@michpetrov That is true, perhaps in that case it is the responsibility of the developer to ensure that content that can overflow should either support truncation if it is string, or make it possible to wrap.
