### ISSUE TITLE
Table data into 1 column

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#4699]
This is more of a question then an issue, because I don't know how to do it. I have the following data:

```javascript
const data = ['one', 'two', 'three'];
```
and I want `two` and `three` into one column on the table:

```jsx
   <Table
        cells={[
          'number one',
          { title: 'two and three' },
        ]}
        rows={data}
      >
        <TableHeader />
        <TableBody />
    </Table>
```
I see that the `ICell` type also has `props?: any;` and `data?: any;` but now idea how they would could / should be used.

**Comment by lizagilman** [comment]
Hi @edewit 
Compact table may be what you're looking for. See https://www.patternfly.org/v4/documentation/react/components/table#compact

**Comment by edewit** [comment]
can you tell me what `props?: any;` and `data?: any;` are for? because the compact table only changed the look and feel that's not what I'm interested in. What I want to accomplish is an easy way to make 2 "columns" in the data fit into one column in the table

**Comment by edewit** [comment]
okay got it working now, although I feel there must be a nicer way to do it. I merge the columns with a special symbol (a hash)
```js
  const data = clients!
    .map((r) => {
      r.clientId = r.clientId + '#' + r.enabled;
      return r;
    })
```
then I use a formatter to change the '#true' or '#false' into a component:
```js
  const enabled = (): IFormatter => (data?: IFormatterValueType) => {
    const field = data!.toString();
    const value = field.substring(0, field.indexOf('#'));
    return field.indexOf('true') != -1 ? (
      <>{value}</>
    ) : (
      <>
        {value} <Badge isRead>Disabled</Badge>
      </>
    );
```
```tsx
      <Table
        variant={TableVariant.compact}
        cells={[
          { title: 'Client ID', cellFormatters: [enabled()] },
        ]}
        rows={data}
        aria-label="Client list"
      >
        <TableHeader />
        <TableBody />
      </Table>
```
is this really the only way to do this or am I missing something?

**Comment by josejulio** [comment]
Maybe I'm not understanding. Do you want to have a Component as value in one cell? you can use this syntax for the data:
```js
const data = [
    {
        cells: [ 
            {
                title: 'one'
            }, 
            {
                title: <React.Fragment>
                    <span> two </span> <span> three</pan> // or <span>cllientId</span> <Badge isRead>Disabled</Badge>
                </React.Fragment>
            } 
       ]
    }
];
```

**Comment by edewit** [comment]
@josejulio no, I want two fields from the data, into one column in the table! Have a look at my example where I concatenate the two fields with a "#" and then use the formatter to format the field into a value and a component based on those two fields.

**Comment by josejulio** [comment]
This is a pattern that I use to build my rows. I transform my input into rows, merging the columns as needed.

![Screenshot_2020-09-24_12-29-44](https://user-images.githubusercontent.com/3845764/94179096-a57df680-fe61-11ea-93b3-e7868e6eb8dc.png)

https://codesandbox.io/s/funny-bassi-07bzu?file=/index.js

Hope that's what you need.

**Comment by edewit** [comment]
@josejulio that is exactly what I need, I feel stupid for not thinking of this! I was thinking I need to keep the data as is and do the formatting in the table component. Your version is so elegant thanks.

**Comment by josejulio** [comment]
You're welcome. I'm glad I could help :smile:.
