### ISSUE TITLE
Table headers of type other than text are broken on mobile devices

### ISSUE THREAD

**Issue by lizagilman** [patternfly/patternfly-react#4700]
Using table components, I have two cases for the cells prop. In one case, strings only:
```
const columns = [
    { title: 'Name' },
    { title: 'Type' },
    { title: 'Auth Callback URL' },
  ];

<Table cells={columns} ... >

```

Works well on small screens.

![image](https://user-images.githubusercontent.com/15361156/90619169-93cd8180-e219-11ea-9ea6-5ad467b66439.png)

But if I need another html piece in the title, for example title with tooltip, than it breaks on mobile devices / small screens / zoom-in the page.

```
  const columns = [
      {
        title: (
          <>
          User ID
            <Popover
              position={PopoverPosition.top}
              aria-label="User IDs"
              bodyContent={(
                <p>
                  User IDs are matched by the cluster&apos;s identity providers.
                </p>
              )}
            >
              <Button variant="plain" isInline>
                <HelpIcon size="sm" />
              </Button>
            </Popover>
          </>
        ),
      },
...
]


```

On small screens -

![image](https://user-images.githubusercontent.com/15361156/90619298-be1f3f00-e219-11ea-9f4e-caa344f21cac.png)

The root cause of that is in the data-label attribute and media query css -   content: attr(data-label)  -

```
@media screen and (max-width: 768px)
.pf-m-grid-md.pf-c-table [data-label]::before {
    font-weight: bold;
    text-align: left;
    content: attr(data-label);
```
In case of string only, the data-label gets the string, but on the second case it gets  `column-${key}`

**Comment by tlabaj** [comment]
cc @jschuler
