### ISSUE TITLE
Disable all children inside InputGroup

### ISSUE THREAD

**Issue by AlexSCorey** [patternfly/patternfly-react#4709]
There is a use case where the children inside of Input Group should be able to have disabled styling applied to them.  In my case I have 
```
<InputGroup> 
    <Button>
      Submit
    </Button>
    <ChipGroup> 
      <Chips/>
    </ChipGroup>
  </InputGroup>
```

If I can add isDisabled to the InputGroup then I would expect the background of the ChipGroup and the chips to have disabled styling.

Below is the component in question:

![Screen Shot 2020-08-21 at 2 36 55 PM](https://user-images.githubusercontent.com/39280967/90923507-cdd68900-e3bb-11ea-8cad-1e2ddb885552.png)

**Comment by boaz0** [comment]
@AlexSCorey I see what you're saying. A way to solve it is to inject the `isDisabled` prop to `InputGroup` specific children like `TextInput`, `ChipGroup` and etc. Will that work for you?

Nonetheless, I do believe it is better to let the users do it manually rather than magically inject it to the children.

**Comment by AlexSCorey** [comment]
@boaz0 Thanks for getting back to me.  I agree that injecting the isDisabled prop is the best way to do it however, based on the docs and my trials there isn't a real easy way to apply disabled styling to a chip group.  

Additionally, lets say that I have a series of labels inside of an input group.  I think you should be able have a prop that will apply disabled styling to the input group.

**Comment by boaz0** [comment]
@AlexSCorey I think I understand what you were saying. There is no way to set chip/chip-group to disabled.

//cc @mcoker @mcarrano would you consider adding a disabled modifier to the chip/chip-group component?

**Comment by mcarrano** [comment]
@AlexSCorey Can you provide more background about your use case? It's not clear to me what it means to disable a chip. What exactly are you disabling? The Chip itself is not designed to take mouse or keyboard events.

**Comment by boaz0** [comment]
@mcarrano I think what he means is that you can remove a chip from a chip group. By disabling a chip-group you are not allowing the user to remove it from a chip-group.
Correct me if I'm wrong @AlexSCorey

**Comment by mcarrano** [comment]
If that's the case, we support a "read-only chip" as shown here: https://www.patternfly.org/v4/documentation/react/components/chipgroup#single  That's just a chip without the remove button. We should be able to use any of these chip variations inside of a group. Any reason that wouldn't work @boaz0 @AlexSCorey ?

**Comment by boaz0** [comment]
Thank you @mcarrano I don't know how I missed that! :+1:

**Comment by boaz0** [comment]
@AlexSCorey does setting chips to `isReadOnly' work for you?

**Comment by AlexSCorey** [comment]
@boaz0 @mcarrano 
I think the best way to think about it is not to focus on the chip or the chipgroup, but rather the wrapper that holds the chip group.  In the case I described above, that wrapper is the Input Group, which can't be disabled. In the screen shot in the issue you can see that the search button with the magnifying class icon is disabled, with grey background.  I think we should be able to apply a grey back to the chip group wrapper as well so that the whole field appears disabled. I believe, when looking at the screen shot it isn't clear what part of that field is disabled.  Is it the button, the input part, or the whole thing?  One might think to themselves "Will the button become enabled if I can write something, or add a chip to the input?  If so, how do I do that?"

**Comment by mcarrano** [comment]
Thanks @AlexSCorey I think I understand a little bit better what you are asking for. But I'm still not sure I understand what it means to disable the chip group. Right now, a chip group is not something that has a disabled state. In your case, what's the interaction when the field is enabled? Can I type into the field to set search terms? Is this intended as something more like a type-ahead select here that uses chips? https://www.patternfly.org/v4/documentation/react/components/select#multiple

**Comment by AlexSCorey** [comment]
@mcarrano I don't think you can/should disable a chip group.  I think what should appear to be disabled is the wrapper.  That would be the items in blue below.
![Screen Shot 2020-08-21 at 2 36 55 PM](https://user-images.githubusercontent.com/39280967/92628698-36b67000-f29b-11ea-8f6a-cd44a251f861.png).  That area, I think, should have a grey background when the input group is disabled.

**Comment by mcarrano** [comment]
@mcoker can you comment on this? Is there or should there be a way to set the entire Input group disabled vs disabling separate elements that make up the group?

**Comment by mcoker** [comment]
I don't know that I've seen anyone use chips in the input group like that. @AlexSCorey can you reproduce the layout you have in this codesandbox? I'm not sure where you're getting the styling around the chips. https://codesandbox.io/s/still-pond-lo51z?file=/index.js

The input group is typically used with form control elements (`<button>`, `<input>`, `<textarea>`, `<select>`), and components that mimic form elements like dropdown, select, etc. They're all the same height, have similar styling, and are designed to go side-by-side. And each of those elements/components have a disabled state, so typically if anything is disabled in an input group, the element(s) are disabled. 

One concern with changing the background color of the input group for a disabled state would be with accessibility of elements that a user may have added to the input group. If there is an element with grey text in the input group, a disabled background could reduce the contrast of the text against the background to the point that it is no longer accessible.
