### ISSUE TITLE
Menu component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4712]
https://github.com/patternfly/patternfly/pull/3397

We created a menu component for general use. It should support most/all of the features we have with our current individual menus (dropdown, select, app launcher, etc). The end goal would be to use this menu either inside of those components, or for it to serve as the framework to build individual menus in those components with a set of shared base code.

This should inherit mouse and keyboard interactions from existing dropdown and select menus. Flyout is a new pattern - should follow guidance on implementing accessible fly-out menus here: https://www.w3.org/WAI/tutorials/menus/flyout/  This must include adding a 1 second timer on mouseout events before closing the menu.

**Comment by jessiehuff** [comment]
Just to add some initial thoughts on keyboard interaction, I think it would make sense to be able to Tab through the menu and have the following interactions:
- Enter and right/left arrow keys should enter and interact with menu (right arrow key opens menu or left arrow key closes).
- When inside submenus, arrow keys to shift focus within submenus (up and down like a dropdown menu). 
- If inside a submenu, Esc should return focus to the parent menu and close that submenu (not the entire menu). 
- If inside a submenu, Tab would close the submenu and put focus back to the parent menu and then next Tab would go to the next menu item.

Also, it's worth noting that we should probably do some testing on `aria-haspopup`. Based on conversations I've had with Jenn, it seems that that attribute could have some potential negative interactions that we should likely test out here.
