### ISSUE TITLE
Splitter component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4715]
New component! https://github.com/patternfly/patternfly/pull/3407

@jessiehuff to add keyboard interaction details

**Comment by jessiehuff** [comment]
For the keyboard interaction, I would expect the following: 

Key | Function
-- | --
Left arrows | Moves a vertical splitter to the left.
Right arrows | Moves a vertical splitter to the right.
Up arrows | Moves a horizontal splitter up.
Down arrows | Moves a horizontal splitter down.

This [demo](https://codepen.io/captainKAIO/full/yLYPPxX) is what I would expect for the splitter. I think it's also worth noting that we should have the appropriate aria here. I think we already have `aria-orientation`, but I think like this example, we'll also need `aria-valuemin`, `aria-valuenow`, and `aria-valuemax`. This is similar to how our current [progress](https://www.patternfly.org/v4/documentation/core/components/progress#simple) component functions. These attributes help screen readers understand what is happening.
