### ISSUE TITLE
add manual ouia component ids to cards in demos/cardview/basic

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [patternfly/patternfly-react#4718]
http://patternfly-react.surge.sh/documentation/react/demos/cardview/basic

uses auto generated auto-increment ouia ids, for additional fun they change every time the view is changed (filtered, checkbox clicked)

instead there should be actual matching ouia ids for each of the cards

**Comment by jschuler** [comment]
https://github.com/patternfly/patternfly-react/pull/4746 should fix that

**Comment by evwilkin** [comment]
Resolved in #4746
