### ISSUE TITLE
use development react builds for the demos

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [patternfly/patternfly-react#4719]
the demons currently use production builds,
that makes it impossible to actually introspect the react components

for investigation/debugging/understanding i would love to see the actual react components with a react debug tool

**Comment by jschuler** [comment]
Can you clarify what you expect to see? When i look at the demo i can see the react props
![Screen Shot 2020-08-26 at 11 46 28 AM](https://user-images.githubusercontent.com/869106/91326045-e0710980-e791-11ea-829e-72f527d44a22.png)

**Comment by RonnyPfannschmidt** [comment]
i apologize, after a browser update today everything seems to work again, thanks for pointing out how its expected to work
