### ISSUE TITLE
annotate autogenerated ouiaID's and warn when they are used

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [patternfly/patternfly-react#4723]
the autogenerated ouia ids can be misleading, as practically they are just almost random numbers (depending on how many componets are laid out/nested

a current demo example is http://patternfly-react.surge.sh/documentation/react/demos/cardview/basic where the ids of all cards change every time a checkbox is checked/unchecked

as far as im concerned, the auto-generated ids are dangerous, misleading and a potential error source for automation

they should include a part that indicates they where autogenerated, and trigger warnings

additionally there should be a opt-out (unless there is one i missed when looking)

**Comment by jschuler** [comment]
Hey @RonnyPfannschmidt , is there any use case for having generated ids or would it just be better to leave the `data-ouia-component-id` attributes off if no id is supplied?
Also, are you running tests against the demos? Should we update the demos to provide unique ids that don't change?

**Comment by jschuler** [comment]
Also, i was briefly looking at the spec https://ouia.readthedocs.io/en/latest/README.html#ouia-component, it appears to be spec compliant it requires a lot more on the page, for example, the `body` tag should have `data-ouia-page-type` and much more... how are you testing PatternFly?

**Comment by RonnyPfannschmidt** [comment]
@jschuler ideally there should only be a warning if they are not supplied, and there should be a opt out - autogenerated is only helping in the sense that it helps to identify misses

**Comment by jschuler** [comment]
The demos are generally user facing so we wouldn't want them to see ouia warnings, could we just set prefix the id to have something like `generated-12`? And/or add an extra `data-ouia-component-generated="true"` attribute to the HTML?

**Comment by RonnyPfannschmidt** [comment]
As far as I can tell the demo could get fully annotated with actual ids, which may be much better than just avoiding warnings

**Comment by jschuler** [comment]
@RonnyPfannschmidt would you be happy with generated ids that stay the same on the page in the format `Generated-{Component}-{number}`? i.e. `Generated-Card-1`
And they would be unique based on the url, so if URL `/documentation/react/a` has cards the first generated one starts at `Generated-Card-1` and if URL `/documentation/react/b` has also cards they also begin at `Generated-Card-1`

**Comment by RonnyPfannschmidt** [comment]
It would be better, but still missleading, the ideal case would be to have actual related ids (in many cases the I'd should match the key, or it should denote the named intent of the component

**Comment by jschuler** [comment]
All the examples in the documentation won't have specific `ouiaId`s set. In the case where they are not provided, what would you like to see? It will be difficult to generate smart defaults beyond what I described above. Alternatively we could not provide ids and just add an attribute like `data-ouia-component-missing-id="true"` cc @quarckster

**Comment by quarckster** [comment]
@RonnyPfannschmidt  @jschuler That's why I decided to extend examples in patternfly docs and add OUIA section with correct `ouiaId` values in #4741. It's not complete and I'm going to add more examples if you ok with #4741.

**Comment by jschuler** [comment]
@RonnyPfannschmidt @quarckster Please check out https://github.com/patternfly/patternfly-react/pull/4746 thanks
