### ISSUE TITLE
Add auto direction for menu expansion on Select component

### ISSUE THREAD

**Issue by glekner** [patternfly/patternfly-react#4729]
**Describe the issue. What is the expected and unexpected behavior?**
When having Select components inside a Wizard component, the footer overlaps the dropdown content, it would be nice if the component would know automatically to render the menu upwards or downwards

Screenshot:
<img width="720" alt="Screen Shot 2020-08-25 at 17 15 47" src="https://user-images.githubusercontent.com/24938324/91302100-9ea28c00-e7ae-11ea-8da7-be3647c32167.png">

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement
**What is your product and what release version are you targeting?**
latest

**Comment by jschuler** [comment]
To fix the issue of the Dropdown getting cut off, set the `menuAppendTo` prop:
```
<Select menuAppendTo="parent" />
```

**Comment by glekner** [comment]
@jschuler that sure helps, thanks.
still would be nice to render it upwards automatically.

**Comment by jschuler** [comment]
The `menuAppendTo` prop can also be set to other elements, like `menuAppendTo={() => document.body}`, `menuAppendTo={() => document.querySelector('.my-item')}`, `menuAppendTo={() => ref.current}`

You can manually specify the dropdown (dropup) direction, the first example here lets you play with that:
https://www.patternfly.org/v4/documentation/react/components/select#single

I don't think there are any plans at the moment to auto-detect where the menu should flow, and I am not sure how the logic for that would look.
