### ISSUE TITLE
Build basic time picker

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#4731]
Does not include timezones.

**Comment by nicolethoen** [comment]
@mcoker @mcarrano I have built a `TimePicker` prototype to be styled.
it uses a typeahead `Select` so there are a few behaviors that are built into a `Select` I still want to modify. But I figure this is a good starting point. 

Primarily, i know the keyboard interactions are still imperfect. Hopefully I can work out kinks without making updates to the Select component itself. But any/all feedback at this point is good. I wanted to tag both of you at this point to make sure we are headed down a better road.

http://timepicker-in-progress.surge.sh/components/time-picker

also note: we definitely want to make sure we consider what the error state is for an invalid input

**Comment by mcarrano** [comment]
@nicolethoen finally got a chance to look at this. Makes sense that typeahead select is a place to start, but it does seem like there are some differences. Entering a value into the field should help scroll the list but not necessarily filter it. Right now I don't seem to be able to input something that is not part of the list (like 2:12pm). Also not sure how AM/PM entry should work. What should happen if the user enters something other than this from the keyboard? What if I type "2:00pm" vs "2:00 PM" would both be accepted?

Happy to meet and talk this through more. Perhaps we can compare against existing time picker components to model this.

**Comment by nicolethoen** [comment]
@jschuler @kmcfaul @tlabaj @redallen 
Any of you know how to make a dropdown auto scroll to an option? I have investigated a few options but the restraints I am trying to work within:

1.  focus needs to stay on the input while the dropdown repositions itself <-- that's the big one
2. the page itself cant scroll, just the options in the dropdown (and there are a lot if it's a time picker)

**Comment by redallen** [comment]
If first you need set `max-height: 500px; overflow-y: auto;` on `ul.pf-c-dropdown-menu` you can simply do `liRef.offsetParent.scrollTop = liRef.offsetTop` to scroll `liRef` to the top of the dropdown list. It shouldn't affect the page scrolling or input focus.
