### ISSUE TITLE
Build Date Range picker

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#4732]

**Comment by unlikelyzero** [comment]
@mcarrano @nicolethoen how does this relate to https://github.com/patternfly/patternfly-react/issues/4504

**Comment by nicolethoen** [comment]
@unlikelyzero 
This issue is part of the Date and Time picker epic.
It is the next priority after introducing a basic Time picker (https://github.com/patternfly/patternfly-react/issues/4731) and cleaning up the calendar (https://github.com/patternfly/patternfly-react/issues/5057)
