### ISSUE TITLE
No option to programmatically set `No results found` option in Select

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-react#4744]
**Describe the issue. What is the expected and unexpected behavior?**
If consumer passes empty array it would be really good if PF would show `No results found` option instead of empty dropdown menu. I would gate this behind prop `showNoResults` in a way, that if this prop is not set the component would have show current bahavior, but if consumer set this up it would show the `No results found`.

So 2 criterias needs to be met:
* empty children
* `showNoResults` prop is set to `true`

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
http://patternfly-react.surge.sh/documentation/react/components/select#typeahead and change the chilren of Select to empty array.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
We are showing different option when there are no results, but our UX would like to use PF's option, so I would frame this as a bug?

**What is your product and what release version are you targeting?**
cloud.redhat.com the sooner, the better

**Comment by karelhala** [comment]
ping @mcarrano @kmcfaul @evwilkin

**Comment by evwilkin** [comment]
@tlabaj FYI in case this ties into any of the Select work already in progress

**Comment by KendraMar** [comment]
FWIW, no results found already appears in this component:

https://www.patternfly.org/v4/documentation/react/components/select#grouped-checkbox-input-with-filtering-and-custom-badging
