### ISSUE TITLE
Remove lodash from patternfly

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#4750]
Recently we did an analysis on how many functions are used by patternfly from lodash.  There is less than a handful.  The size of lodash is larger then our entire component library if you do a bundle analysis.  We should remove this dependence to improve load times, reduce our foot print, and not increase consumers bundle size by including this library.

**Comment by dlabrecq** [comment]
Note that the the charts package makes use of lodash; however, it's a Victory dependency. We won't be able to eliminate lodash from Victory, but at least charts is its own package.
