### ISSUE TITLE
Please export WizardContext so that it can be used in a React Hook

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#4751]
Please export `WizardContext` so that it can be used in a React Hook. Currently only `WizardContextProvider` and `WizardContextConsumer` are exported:

https://github.com/patternfly/patternfly-react/blob/26b3e1d8e2e52240024ff86e08ce1f327760838c/packages/react-core/src/components/Wizard/WizardContext.ts#L13-L23

**Comment by wojta** [comment]
@tlabaj  taking this one

**Comment by wojta** [comment]
Not sure about the PR. Is it really just simple like that or am I missing something?

**Comment by idevat** [comment]
@wojta It could be so simple, I guess. Currently, it is possible to import `WizardContextConsumer`
```javascript
import { WizardContextConsumer } from "@patternfly/react-core";
```
and it is expected to be able import also `WizardContext`
```javascript
import { WizardContext } from "@patternfly/react-core";
```
But I'm not sure about contribution requirements (e.g. tests).
