### ISSUE TITLE
TypeAhead Select should have a prop to support partial matches

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#4763]
Enhancement request:

Currently, when using `Select` with `variant="typeahead"` or `variant="typeaheadmulti"`, when the user types their search term the only matching results are items with that text as a prefix. I propose a prop, `allowPartialMatch` or something, that will show matching items containing the typed text anywhere in the item text.

For example: my typeahead is for selecting networks that each have a provider prefix, with items like:
* VCenter1 / vmware-network-1
* VCenter1 / vmware-network-2
* VCenter2 / vmware-network-3

The user should be able to find these options by typing `vmware-network-` and not having to type the `VCenter` prefix first.

**Comment by boaz0** [comment]
You can do it even now by passing a function to `onFilter` just be advised that the function needs to return `SelectOption`s.

For example, `customFilter` will match anything that contains the search text in the [multiple example](https://patternfly-react.surge.sh/documentation/react/components/select#multiple):
```js
    this.customFilter = e => {
      let input;
      try {
        input = new RegExp(e.target.value, 'i');
      } catch (err) {}
      console.log('input ', input, this.state.options.filter(child => input.test(child.value)));
      const res = e.target.value !== '' ? this.state.options.filter(child => input.test(child.value)) : this.state.options;
      return res.map((option, index) => {
        return (
          <SelectOption
            isDisabled={option.disabled}
            key={index}
            value={option.value}
            {...(option.description && { description: option.description })}
          />
        );
      })
    };
```

**Comment by mturley** [comment]
Good to know, thanks @boaz0 ! Perhaps we should just make this more obvious in the documentation.

**Comment by KKoukiou** [comment]
@mturley the documentation actually is pretty good on this one in my opinion, there is a section called `custom filtering`. https://www.patternfly.org/v4/documentation/react/components/select#custom-filtering

 Let's not provide one more extra property in my opinion, since the filter function is pretty flexible and straightforward solution.

**Comment by mturley** [comment]
@KKoukiou I totally missed that example! You're totally right. This is perfect. Thanks for pointing that out.
