### ISSUE TITLE
Does this setup work in windows machine ?

### ISSUE THREAD

**Issue by Private-SO** [patternfly/patternfly-react#478]
Hi,

I am running into different types of errors when i am installing the setup in my Windows machine.

These are the commands i had used to 

-  yarn add patternfly-react
- yarn install
- yarn build

When i am running yarn build it is throwing different errors like this 

```
C:\Program Files\nodejs\patternfly-react>yarn build
yarn run v1.7.0
$ yarn copy-fonts && yarn copy-img && yarn build-css && yarn build-js
$ ncp node_modules/patternfly/dist/fonts src/fonts
There were errors during the copy.
Error: ENOENT: no such file or directory, mkdir 'C:\Program Files\nodejs\pattern
fly-react\src\fonts'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

```

But the setup is working fine in Ubuntu and mac . Why i am getting these errors in my Windows Machine? 

BTW i am running above code in CMD prompt in Admin mode.

Thanks

**Comment by dlabaj** [comment]
Currently OS specific command prevent this from running on Windows.  Converting this to a bug we should fix this by updating package.json to not have OS specific commands.

**Comment by jschuler** [comment]
Close in favor of #1557
