### ISSUE TITLE
Primary-detail demo page doesn't show mobile interaction properly

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-react#4782]
https://www.patternfly.org/v4/documentation/react/demos/primarydetail

For the simple list in card and data list in card examples, the mobile version of the demo page doesn't have a way to show how to expose the detail section. The items in the primary area are clickable but nothing happen on click. 

This example does toggle between the primary and detail on click:
https://www.patternfly.org/v4/documentation/react/demos/primarydetail/primary--detail-full-page
However it is missing this part from the [wireframes](https://marvelapp.com/prototype/9iefh5b/screen/63567621)
"primary item title will appear as a header with clear navigation back to primary component". @lboehling can you confirm that's the correct interaction?

I did not check any other examples.

**Comment by wesruv** [comment]
Putting my 2 cents in here, I'm hoping this is an accordion at mobile, but let me know what you all decide!
