### ISSUE TITLE
VerticalNav links ignore the modified clicks

### ISSUE THREAD

**Issue by xprazak2** [patternfly/patternfly-react#4783]
**Describe the issue. What is the expected and unexpected behavior?**

Links in VerticalNav open in a current tab instead of in a new one when using ctrl+click. Same for new window and shift+click.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

This is reproducible when we pass `onNavigate` prop which should handle the navigation:

```js
import React from "react";
import { Route, Router } from "react-router-dom";
import { createBrowserHistory } from 'history';
import { VerticalNav } from 'patternfly-react';

const Foo = (props) => <div>Foo</div>;
const Bar = (props) => <div>Bar</div>;

const items = [
  { title: 'foo', href: '/foo' },
  { title: 'bar', href: '/bar' },
]

const history = createBrowserHistory();

const App = (props) => {
 
  return (
    <React.Fragment>
      <VerticalNav
        items={items}
        onNavigate={({ href }) => history.push(href)}

      />
      <Router history={history}>
        <Route exact path="/foo" component={Foo} />
        <Route exact path="/bar" component={Bar} />
      </Router>
    </React.Fragment>
  );
};
```
`onItemClick` in `VerticalNavItemHelper` does not check for modified clicks and does not pass original click event to `onNavigate` click handler.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, no workaround known.

**What is your product and what release version are you targeting?**

https://projects.theforeman.org/issues/29020

**Comment by tlabaj** [comment]
closed by #4747
