### ISSUE TITLE
Expandable table: add capability for an "expand/collapse all" toggle in the header of the column containing expand/collapse controls

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#4798]
**Describe the issue. What is the expected and unexpected behavior?**

Currently when using the `expandable` transforms in Table, the column containing the expandable controls is generated internally and it is impossible for the consumer to modify it / add their own custom header cell for it (as far as I can tell). We want to add a control to the header of that column in our table that will expand/collapse all the expandable rows in the table, perhaps with a `canExpandAll` prop that behaves similarly to the `canSelectAll` prop we have today.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Observable in the workspace examples.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Enhancement / nice to have

**What is your product and what release version are you targeting?**

https://github.com/konveyor/virt-ui (Red Hat Migration Toolkit for Virtualization), no particular release target.

**Comment by mcarrano** [comment]
@mturley we currently have an open design issue about this. See https://github.com/patternfly/patternfly-design/issues/905. @mmenestr is currently working on this. We decided that the control to the toolbar rather than the header of the table since the Ansible team had requested this same functionality for data lists. Otherwise the functionality is as you describe.

cc @tlabaj @evwilkin

**Comment by mturley** [comment]
Sounds good, thanks @mcarrano. Should I close this issue for now or leave it open?

**Comment by mcarrano** [comment]
Up to @tlabaj  and @evwilkin . Do you prefer to open a clean issue when this is handed off from design or should we just keep this open and send a PR against this when it is ready to be implemented?

**Comment by tlabaj** [comment]
I think we should close this one if @mturley is ok with it. The design is slightly different than the ask her since the button will be in the toolbar.

**Comment by mturley** [comment]
Sounds good. Thanks @tlabaj
