### ISSUE TITLE
Tree view: add support for action to not be wrapped in a <button>

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#4799]
**Describe the issue. What is the expected and unexpected behavior?**

Currently, the `action` property in a `TreeViewDataItem` creates the children for a `<button>` that is rendered internally. You can pass props to that button with `actionProps`, but you can't replace it. I'd like to render a `<Dropdown>` in place of that button, since it provides its own toggle button. Currently when I do that I get a button inside a button.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Render a `<Dropdown>` inside the `action` property of a tree view item.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Enhancement

**What is your product and what release version are you targeting?**

https://github.com/konveyor/mig-ui (Migration Toolkit for Containers), no specific target release.

**Comment by mturley** [comment]
cc @kmcfaul

**Comment by mcoker** [comment]
Hey @mturley I've opened a core issue and will see if we can get that in this milestone https://github.com/patternfly/patternfly/issues/3518

**Comment by mturley** [comment]
Awesome! Thanks @mcoker

**Comment by mcoker** [comment]
@mturley this work was merged, but looks like we may have introduced a bug in the react tree view since it wasn't updated in react. https://github.com/patternfly/patternfly/pull/3522/

cc @tlabaj
