### ISSUE TITLE
Update skip to content component to support react router

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#4809]
**Describe the issue. What is the expected and unexpected behavior?**
When trying to add the skip to content component to OpenShift, I noticed an odd behavior where instead of appending #content to the end of the path in the route, it would replace it, going from `localhost:9000/dashboards#content` to `localhost:9000/#content`. OpenShift uses react router which is likely the reason this is happening. We should update the SkipToContent component to accept other router components instead of always rendering as an anchor tag. We should update the code to be similar to this one
https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Nav/NavItem.tsx#L72

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

![Screen Recording 2020-09-11 at 9 46 47 AM](https://user-images.githubusercontent.com/28281340/92950998-a6f3fb80-f42b-11ea-838d-47b9992395e7.gif)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

**What is your product and what release version are you targeting?**
Trying to target the OpenShift 4.7 release

**Comment by tlabaj** [comment]
closed by #4831

**Comment by tlabaj** [comment]
This was resolved in product.
