### ISSUE TITLE
Table with column 'ID' breaks React keys

### ISSUE THREAD

**Issue by mohd-akram** [patternfly/patternfly-react#4835]
**Describe the issue. What is the expected and unexpected behavior?**

Expected behavior: no errors
Actual behavior: Encountered two children with the same key, `[object Object]-row`.

https://codesandbox.io/s/youthful-noyce-s1bwg?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug. Don't know what's the workaround apart from renaming the column which one shouldn't have to do.

**Comment by KKoukiou** [comment]
@mohd-akram I had the same issue some months ago https://github.com/patternfly/patternfly-react/issues/3090

There is a clean workaround there which I think it's easy to implement to avoid rewriting this coed here.

**Comment by renanrodrigo** [comment]
+1 to this - although a workaround exists, there could be a fix in the resolve-row-key to avoid this
