### ISSUE TITLE
DropdownToggleCheckbox / Checkbox: isChecked and checked documentation / code fixes

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#4845]
These components (maybe there are some more I missed?) have both `isChecked` and `checked` props. I assume this comes from fixing the prop name to have the `is` prefix while also not removing the old prop name to not break current consumers.

We should add to the docs that checked prop is deprecated and perhaps add a dev environment warning about its deprecation.
Also add a dev environment warning if both isChecked and checked are used.
Also the indeterminate logic appears to be only tied to the `isChecked` prop and not the previous `checked` prop.

**Comment by tlabaj** [comment]
closed by #4844
