### ISSUE TITLE
Table - Expanded content is always one cell (<td>)

### ISSUE THREAD

**Issue by josejulio** [patternfly/patternfly-react#4858]
**Describe the issue. What is the expected and unexpected behavior?**

I have a table that shows an expanded content that aligns with the row headers, I added the cells to the expanded content (a cells inside the row with with the correct parent id).

**Expected behavior**: All the cells show as I configured it.
**Unexpected behavior**: It always takes the first cell and applies a colSpan of the total number of headers.

Notice that this only happens when `onCollapse` is specified on the `Table` component:

**With `onCollapse`**
![Screenshot_2020-09-22_10-15-39](https://user-images.githubusercontent.com/3845764/93901879-97db3c00-fcbc-11ea-8e96-a587c4322ceb.png)

**Without `onCollapse` (The way I want to have it minus the toggle)**
![Screenshot_2020-09-22_10-14-41](https://user-images.githubusercontent.com/3845764/93901867-94e04b80-fcbc-11ea-948e-9f3c256c7e98.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

`child - 1 with more rows` should have all the rows
 
https://codesandbox.io/s/musing-silence-8bc0z?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
It could be a bug or by design (I suppose), is blocking some of my work and I don't have any workaround yet.

**What is your product and what release version are you targeting?**
Insights Notifications UI

**Comment by tlabaj** [comment]
cc @jschuler

**Comment by mcarrano** [comment]
@mcoker can you also take a look?

**Comment by mcoker** [comment]
@mcarrano currently expandable rows expand a single row with a single table cell where a user puts the expanded content. It sounds like this request is to have an expandable row expand additional rows in the table, which is something we don't currently support. We can create a core issue to figure out the structure and any styling if you'd like us to make that enhancement.

**Comment by mcarrano** [comment]
@josejulio I looked into this a bit more and consulted with @kriker to take a look at the design mocks you are trying to implement. Unfortunately, row expansion in the Table is not intended to work as designed here. We would need to modify the table component to group a set of rows like this. What's your timeframe for this? If you need a fix short term, I think there are some modifications that can be made to the design to make this work by nesting tables inside of an expandable data list. I'd be glad to help with that.

**Comment by josejulio** [comment]
Thanks @mcarrano, there is already some work in #4899 to fix this issue.
