### ISSUE TITLE
How to add favicon

### ISSUE THREAD

**Issue by QasimRRizvi** [patternfly/patternfly-react#4863]
I'm trying to add favicon in index.html with this ```<link rel="icon" type="image/png" href="favicon.png">``` tag in ```<head>``` but favicon is not changed. My index.html file and favicon is in same folder  i.e ```/src```

I'm new on patternfly-react so don't know how to do it.

I cloned this repo https://github.com/patternfly/patternfly-react-seed and working on it

**Comment by redallen** [comment]
Hey @QasimRRizvi ,

The seed uses [HTMLWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/) and after you add the `<link rel="icon" type="image/png" href="favicon.png">` to its template `index.html` you'll have to make sure your `favicon.png` gets copied over to your `dist` folder using something like [CopyWebpackPlugin](https://webpack.js.org/plugins/copy-webpack-plugin/).

If you need more help, please ask on https://patternfly.slack.com !

**Comment by QasimRRizvi** [comment]
Thanks, @redallen, 

HTMLWebpackPlugin helped me, I've made it to a solution without CopyWebpackPlugin.
Here's the solution in case anyone is having the same issue

```plugins: [
      new HtmlWebpackPlugin({
        template: path.resolve(__dirname, 'src', 'index.html'),
        favicon: path.resolve(__dirname, 'src', 'favicon.ico'),
      })
    ]
```

Added this favicon: path.resolve(__dirname, 'src', 'favicon.ico'), line in my webpack.common.js
favicon.ico is in /src folder.
