### ISSUE TITLE
Add actions footer to the Context Menu

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#4865]
React follow-up issue to Core issue https://github.com/patternfly/patternfly/issues/3475.

Add an optional footer to the Context menu component. The footer can hold a button right aligned in the footer according to the design in https://github.com/patternfly/patternfly/issues/3475.

Replacement for original contribution #4517

@jessiehuff to investigate accessibility

**Comment by mcoker** [comment]
Core work is finished - https://github.com/patternfly/patternfly/pull/3494

**Comment by jessiehuff** [comment]
Currently our context menu's interaction pattern is to tab through each item. If we added the actions footer, I imagine it wouldn't interfere with the current interaction where they would tab to the footer as the next interactive item. However, this also means that the user has to tab through every menu item to get to the footer. An enhancement that we'd like to make with the context selector would be to Tab through the top search fields, then Tab into the menu and you can switch to up/down arrow keys to go through the options. Tab again would take you to the footer. This way the user can choose to jump over the menu items if they want to just get to the actions footer, especially if it's a particularly long list. This interaction pattern is also described in #3108 and the [Design Documentation](https://docs.google.com/document/d/1m9nICFRgCXnXeHYN487BMX9MHw4DjvOln2B5p8yJa70/edit#heading=h.1b322xkjq2i7) that Jenn, Matt, and I wrote up for dropdown type interaction patterns.
