### ISSUE TITLE
Popover component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#487]
Popover component from here: https://pf-next.com/components/Popover/examples/

See notes below about leveraging popper.js. This issue also includes identifying the best approach for a wrapper and utilizing core CSS.

Note re: behavior, ensure that popover only closes when the user clicks either the close icon or outside of the popover itself as there are use cases where a user needs to be able to select text from the popover body.

**Comment by jschuler** [comment]
We've identified the following thirdparty to use for the tooltip and popover components:

[popper.js](https://popper.js.org) - Positioning engine
To use it we need a react wrapper. We can create or own or use ready-made libraries. 

Examples from other projects that have created their own:
[material-ui](https://github.com/mui-org/material-ui/tree/master/packages/material-ui/src/Popper)
[reactstrap](https://github.com/reactstrap/reactstrap/blob/master/src/PopperContent.js)
[gist example](https://gist.github.com/atomiks/25ba93a551fc1e8a1ef18aa7669c6699)

Examples for react components that have already done so:
**Tooltip**
[react-tippy](https://github.com/tvkhoa/react-tippy)
[react-popper-tooltip](https://github.com/mohsinulhaq/react-popper-tooltip)
[react-tooltip](https://github.com/cypress-io/react-tooltip)
**Popover**
[react-popper](https://github.com/FezVrasta/react-popper)

Note: To keep bundle sizes down, we shouldn't require the consumer to have these thirdparty libraries loaded in if they are not using tooltip/popover components.

**Comment by jschuler** [comment]
Reopening, we can close this once the work for the positioning engine has gone in

**Comment by jgiardino** [comment]
Is this story intended to capture the behavior of showing/hiding the popover? 

I expect that the popover would behave similar to the modal (e.g. keyboard interaction, trapping focus), and there's currently an open issue for handling keyboard interaction with the modal (#561). I'm also assuming that the solution we end up with for #561 is probably what we'd want to use for popover.
