### ISSUE TITLE
Tree View bugs

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#4872]
Comparing PatternFly Core with PatternFly React. Some of the new updates that we made in Core need to be updated in React as per this PR: https://github.com/patternfly/patternfly/pull/3410 

- spacing between the toggle and the text is smaller in react
- In the check example: tree-view-node should be a div not a button, so that you can click on the text to turn the check on and off which currently is happening in Core not React
- For current items, only the text should be blue not the arrow
- the text next to the check should be a label not a span
- in react there should be a toggle wrapper around the toggle icon

cc: @mcoker @tlabaj

**Comment by mturley** [comment]
Related to the first bullet: https://github.com/patternfly/patternfly-react/issues/5165
