### ISSUE TITLE
Progress component title prop accepts only a string

### ISSUE THREAD

**Issue by gildub** [patternfly/patternfly-react#4875]
The Progress bar accepts only a string. Would it be possible to make it accept a `React.ReactNode` instead (or both)?

For example:
Currently passing only text (or string variable):
`<Progress title="blah" label={label} />} value={value} />` 
It would allow a component in place of the title:
`<Progress title={<StatusIcon status={StatusType.Warning} label="blah" />} value={value} />`

This would be a must have enhancement for the Progress component. 

Our product is https://github.com/konveyor/virt-ui

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@vconzola could use your input here. We do have a solution for including a warning state in the progress bar as shown here: https://www.patternfly.org/v4/components/progress/html#warning Any reason you can't use that?

**Comment by vconzola** [comment]
@mcarrano I think that will work. @gildub Try implementing as in the warning state example linked above. Move the warning icon after the "x of y VMs migrated" text on the right end of the progress bar. Sorry for the confusion. My mockup didn't follow the PF design.

**Comment by gildub** [comment]
@vconzola, using the Progress bar as suggestted above makes more sense in regards of our needs.

@mcarrano, letting the title prop being a React.ReactNode object will still give it flexibility (and maybe not use that for displaying a status icon). So I believe this is still a valid RFE.

**Comment by gildub** [comment]
@vconzola, @mcarrano, the offered workaround doesn't meet our requirements, effectively the `value` Prop takes only a number (the percentage of completion) therefore we can't use it to display a string, for example "x of y VMs migrated".

**Comment by vconzola** [comment]
@gildub See the [Finite Step example](https://www.patternfly.org/v4/components/progress#finite-step). That shows a way to display a string in that location.

**Comment by gildub** [comment]
@vconzola, thanks. Now I get what's `valueText` for!

**Comment by gildub** [comment]
@mcarrano, the only issue I've got left is being able to choose explictely the default variant (blue bar).

Because `variant` can't be undefined I end up have to do something like this:
``` 
return variant ? (
    <Progress title={title} value={value} variant={variant} label={message} valueText={message} />
  ) : (
    <Progress title={title} value={value} label={message} valueText={message} />
  );

```

**Comment by redallen** [comment]
Enforcing a string will help us solve issues like https://github.com/patternfly/patternfly/issues/3529.

Feel free to reopen if you can't use a workaround.
