### ISSUE TITLE
Add optional Help button to modal header

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#4883]
Includes an optional help button to the left of the Close button. Core issue here: https://github.com/patternfly/patternfly/issues/3474

For keyboard interaction, the Close button should continue to have focus when the user opens the modal. @jessiehuff will further investigate overall keyboard navigation when the help button is present.

**Comment by mcoker** [comment]
FYI this adds a `.pf-m-help` modifier to `.pf-c-modal-box__header` if there is a help button for the title (title is required for the help button).

Then we need 2 new containers as children for `__header` when the modifier is present
* `pf-c-modal-box__header-help` - holds the help button
* `pf-c-modal-box__header-main` - the regular contents for the header - title & optional description for a normal modal, and the value of the `header` prop if the users passes a custom header.
