### ISSUE TITLE
Select component (variant typeahead and multiTypeahead) shows the clear button regardless if there is onClear or not

### ISSUE THREAD

**Issue by josejulio** [patternfly/patternfly-react#4886]
**Describe the issue. What is the expected and unexpected behavior?**

Created a `Select` with variant `typeahead` and `multiTypeahead`, without `onClear` function.

**Expected behavior:**  There is no button to clear
**Unexpected behavior:** The button actually shows

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/focused-moon-6buwr

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
Insights Notifications UI

**Comment by mcarrano** [comment]
@josejulio can you explain why you would want to remove the ability for a user to clear the field?

**Comment by josejulio** [comment]
@mcarrano I only want to remove the clear button when the `onClear` function is not provided to the `Select` component.

This is a pattern already used by `SelectVariant.single`  and `SelectVariant.checkbox` but not for the `SelectVariant.typeahead` and `Select.typeaheadmulti`, so i though it must be a bug.

**Comment by mcarrano** [comment]
@tlabaj @kmcfaul can either of you comment on why typeahead is different?
