### ISSUE TITLE
Toolbar inset for page

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-react#4900]
Relates to [#3527](https://github.com/patternfly/patternfly/issues/3527)

Add pf-m-inset-page as a selector for insets. React needs to add this as a value for the inset prop.

**Comment by mcoker** [comment]
cc @tlabaj @mcarrano can we get this on the roadmap? It adds a value for the `inset` prop to match the page spacing which automatically adapts depending on the viewport size. The work was done in https://github.com/patternfly/patternfly/pull/3403/
