### ISSUE TITLE
Compound expandable table mobile issues

### ISSUE THREAD

**Issue by epwinchell** [patternfly/patternfly-react#4922]
The react version of Compound expandable table displays the data-label in the mobile state. 

Here's PF vs PF-react demo:
![Screen Shot 2020-10-01 at 11 54 01 AM](https://user-images.githubusercontent.com/1287144/94833181-d075c680-03dc-11eb-90ee-addcf72dedfb.png)

Also, both versions force a scrollbar in the mobile layout, causing double scrollbars on the screen. I think, the tables should be fully expanded. If it's helpful, I was able to work around both issues here: https://github.com/RedHatInsights/insights-rbac-ui/pull/506/files#diff-bba9a102d05f9535d646071a40a9c868R16-R23

**Comment by tlabaj** [comment]
cc @mcoker @jschuler
