### ISSUE TITLE
React.js specifics re: how to use RCUE

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#493]
There is a quick start to explain how to use RCUE on pf-core: https://github.com/patternfly/patternfly/blob/master/RCUE-QUICKSTART.md

We also need a modified version to explain the specifics of using RCUE and pf-react.

**Comment by cdcabrera** [comment]
This is a great idea! @LHinson taking a look at the Quick Start guide, looks like it covers the basics. Will see if there are any extra bits we discovered along the way with some of the basic Entitlements work. 

Another aspect may also be to list other products using RCUE.

**Comment by mtho11** [comment]
This would be a great help! And huge time savings.

**Comment by mtho11** [comment]
@cdcabrera Any progress on the list of products using RCUE (and links to their repos) ?

**Comment by LHinson** [comment]
@mtho11 were you able to successfully get rcue working? If not, I'd suggest a call with @cdcabrera for immediate/quick resolution as well as send a PR to close out this issue. 

As for the list, I'll let @cdcabrera speak to this but I'm pretty sure this was just an idea and hasn't been immediate action on this. It would need to be prioritized and assigned. I assume the above action items helps to address your needs and the RCUE product list is a nice to have but let me know if this is not the case!

**Comment by cdcabrera** [comment]
@mtho11 to get you started, couple of apps using the RCUE styling ... they're subject to change, but should relate the idea
- https://github.com/cloudigrade/frontigrade
- https://github.com/quipucords/quipucords

**Comment by mtho11** [comment]
@LHinson I just started on this yesterday (I have been on vacation and other tasks). Will get back to you on my progress. Thank you guys for your prompt action.

**Comment by mtho11** [comment]
@LHinson thanks to you and @cdcabrera examples I was able to get RCUE into Kiali.
Great teamwork!
https://github.com/kiali/kiali-ui/pull/586
