### ISSUE TITLE
PF4 Table: onRowSelect gets triggered with the actionResolver clicks

### ISSUE THREAD

**Issue by akhilmhdh** [patternfly/patternfly-react#4932]
**Describe the issue. What is the expected and unexpected behavior?**

When both onRowSelect and actionResolver are attached to a table, clicking on side dropdown triggers both functions.

Expected : Only actionResolver must be triggered on clicking the side dropdown. onRowSelect should be triggered elsewhere on row. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
CodeSandbox Link : https://codesandbox.io/s/old-waterfall-9g8dg
As you can see when I click on action it also triggers the onRowSelect

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**Comment by jschuler** [comment]
onRowSelect listener is attached to the whole row, perhaps you can just do something like this to not trigger the selection when the actions dropdown button is clicked?
```
rowClickHandler = (event, row) => {
    if (event.target.type === 'button') {
      event.stopPropagation();
      return;
    }
    console.log("handle row click", row);
  };
```

**Comment by tlabaj** [comment]
@akhilmhdh please let us know if the solution @jschuler provided does not work for you.  Otherwise we can close the issue.

**Comment by akhilmhdh** [comment]
@tlabaj @jschuler Thank you that did solved the issue. Ill close this issue then 😄
