### ISSUE TITLE
Data list - allow user to specify the breakpoint for switching between desktop and mobile layout

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#4965]
https://github.com/patternfly/patternfly/pull/3528

Adds `pf-m-grid` modifiers that work like the table's modifiers to switch to the mobile/grid view at a specific breakpoint.

Default behavior is the same.

* `pf-m-grid` will display the grid layout at all breakpoints
* `pf-m-grid-none` will retain the desktop layout at all breakpoints
* `pf-m-grid-[sm, md, lg, xl, 2xl]` will display the grid layout below the specified breakpoint

**Comment by KKoukiou** [comment]
> [patternfly/patternfly#3528](https://github.com/patternfly/patternfly/pull/3528)
> 
> Adds `pf-m-grid` modifiers that work like the table's modifiers to switch to the mobile/grid view at a specific breakpoint.
> 
> Default behavior is the same.
> 
>     * `pf-m-grid` will display the grid layout at all breakpoints

There is no modifier with this class for this component.

> 
>     * `pf-m-grid-none` will retain the desktop layout at all breakpoints
> 
>     * `pf-m-grid-[sm, md, lg, xl, 2xl]` will display the grid layout below the specified breakpoint

**Comment by mcoker** [comment]
@KKoukiou hmmm... yeah this is a bit different in that we don't have a specific class defined for this, but the class triggers the desired layout because it has `pf-m-grid` in the classname, but doesn't match one of the desktop layout selectors here 

https://github.com/patternfly/patternfly/blob/2f4ad756a10f0bbd1aa9b0f712e018621c166e51/src/patternfly/components/DataList/data-list-grid.scss#L1-L23

Is there a way we can apply the class anyways? I know in the past we've added HTML elements with classnames that are not defined in the component CSS, and we had to apply the classname manually instead of using `css(componentStyles.componentElementName)`

**Comment by KKoukiou** [comment]
> @KKoukiou hmmm... yeah this is a bit different in that we don't have a specific class defined for this, but the class triggers the desired layout because it has `pf-m-grid` in the classname, but doesn't match one of the desktop layout selectors here
> 
> https://github.com/patternfly/patternfly/blob/2f4ad756a10f0bbd1aa9b0f712e018621c166e51/src/patternfly/components/DataList/data-list-grid.scss#L1-L23
> 
> Is there a way we can apply the class anyways? I know in the past we've added HTML elements with classnames that are not defined in the component CSS, and we had to apply the classname manually instead of using `css(componentStyles.componentElementName)`

Ah sure, I just though it was an oversight, I will apply the class then.
