### ISSUE TITLE
Broken code sandbox chart examples

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#4988]
A quick look at the chart examples will show that most code sandbox examples are broken. For example, under "Tooltip chart", only the "Wrapped chart" and "Legend" examples are working.

<img width="1381" alt="Screen Shot 2020-10-09 at 2 09 16 PM" src="https://user-images.githubusercontent.com/17481322/95617197-08ae8200-0a39-11eb-81bd-374861df7331.png">

**Comment by redallen** [comment]
With our new MD pipeline we can enforce example JS having identifiers compatible with CodeSandbox.
