### ISSUE TITLE
Update issue template

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#4991]
**Describe the issue. What is the expected and unexpected behavior?**
Update the issue template to ask for the release date in addition to the release version - reflect changes made for Core in [#4610](https://github.com/patternfly/patternfly/issues/4610)

**Comment by drewwmercer** [comment]
@evwilkin or @tlabaj  is this still needed? It looks like the [Template for filing an issue in our repos](https://docs.google.com/document/d/1wl1jROxHBhfGTIc4_YhW4g4VPsP6gIPTI3ctW_lLOLM/edit#heading=h.gfbz7yoo981a) doc doesn't currently include the release date prompt. 

The main patternfly/patternfly repository also doesn't seem to use templates currently. I also saw that the patternfly/patternfly-react template has a warning for the template: 
`You are using an old version of issue templates. Please update to the new issue template workflow.`

If still valid, would it be helpful if I converted the current form to the newer YAML config? If so, should it prompt for a release date or match to the questions listed in the doc from above?

**Comment by evwilkin** [comment]
@drewwmercer thanks for reaching out - it would be helpful to see this updated to the YAML config, and yes adding the ask for the release date prompt.  The `patternfly/patternfly` repo has a [recent issue](https://github.com/patternfly/patternfly/issues/4610) to add the template back & update it, which we may want to build off of eventually.

**Comment by nicolethoen** [comment]
I think it should match the beauty of the core template: https://github.com/patternfly/patternfly/pull/4671

Mark all new issues with 'needs triage' label
