### ISSUE TITLE
Dependency Guidelines

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#5]
## Dependency Guidelines
Some of our components in Patternfly are managed in other OS upstream projects. Today, we have a few other React Bootstrap implementations already underway. Some of these include:

- [Reactstrap](https://reactstrap.github.io/): BS4 with React Components
- [React Bootstrap](https://react-bootstrap.github.io/): BS3 with React Components

To get things going sooner than later, we'd like to consume the current Patternfly CSS (BS3), with the hopes of adopting [Patternfly 5 CSS](https://github.com/patternfly/patternfly-css) (BS4) in the future. Do you have thoughts about integrating third party components such as [React Bootstrap](https://react-bootstrap.github.io/)? Would you be willing to help enhance, develop, and test these according to [Patternfly Design](https://github.com/patternfly/patternfly-design) standards?

**Comment by jtomasek** [comment]
This is quite a big decision to make, since it will introduce another dependency into the chain (bootstrap > patternfly css > react-bootstrap > patternfly-react) So in case of update to bootstrap 4, we'd need to wait for react-bootstrap to get updated to bootstrap 4 version. I am not sure how much of a problem this is. And on the other side, we'd have to make this change in our codebase by ourselves anyway.

Another question is if the react-bootstrap components are compatible with patternfly or how to apply patternfly styling to these components. I can imagine that in most cases this should be possible by simply wrapping the react-bootstrap component in patternfly component which will pass relevant classNames as props. (It seems react-bootstrap has this API to support such usecase:https://react-bootstrap.github.io/components.html#custom-styles)

In general, I tend to be in favor of using react-bootstrap as it will save us time reinventing the components by ourselves.

**Comment by andresgalante** [comment]
Hi Thomas,

Thanks for bringing this up. We are already working on a patternfly based on bootstrap 4 here https://github.com/patternfly/patternfly-css

There are 2 things to be aware of:
- Bootstrap 4 is still on alpha 6, they'll release betas soon but I don't see a stable version of BS4 for quite a long time. Every alpha that has been release so far was full of huge changes, but I believe that it's more stable now. IMO building anything over BS4 at the moment would be like building over quicksand.
- Patternfly.next is in very early stages and it's a definitely a braking change. We've change [the way we write CSS](https://github.com/patternfly/patternfly-css/blob/master/CODE-GUIDELINES.md) to a more flexible, flat and modular way. 
We've also made visual changes, specially around [typography size and family](https://blog.patternfly.org/choosing-the-best-font-for-application-design/).

I'll keep you guys updated on the status of that effort, but I although I am expecting to cut alphas  as soon as we start having parts enough to build templates, I don't see it been a thing before the end of the year.

I hope this helps, if you need any more details about it let me know.

**Comment by priley86** [comment]
@jtomasek thanks for reaching out and a warm welcome 😸. I am definitely looking forward to collaborating on this! I will dig into the `react-bootstrap` examples further this week (and thanks for noting this bit about custom-styles, agree it will help). Completely agree that we will have to ensure PF styles and HTML can be rendered correctly according to our existing PF design standards. There may be some cases we go outside of this (such as when defining a new component), but for these cases we can review closely with UXers & Designers (like @andresgalante @maryclarke @jgiardino). 

@andresgalante thanks for providing this helpful note about BS4, it certainly helps. It seems as if we should definitely target BS3 for now, and maybe introduce a BS4 branch when PF5 is beta.

**Comment by jtomasek** [comment]
I've been adding react-bootstrap to TripleO UI currently and I've implemented a set of Patternfly-based components using it and it was working very well. It saves a lot of time reimplementing those basic components and ensures that they are going to work properly. Here is the patch which introduces it in TripleO UI if anyone is interested: https://review.openstack.org/#/c/452175/

I'd be happy to include and use react-bootstrap in patternfly-react.

**Comment by priley86** [comment]
Hey @jtomasek. Thanks for reaching out and noting this. I would like to update this issue on a few things after some discussions here...

After looking further at `react-bootstrap` (BS3) and `reactstrap` (BS4), we've identified that Patternfly is both a **subset** of Bootstrap (for example, we only suggest the use of primary, secondary, and destructive buttons [link](http://www.patternfly.org/pattern-library/widgets/#buttons)), and a **superset** of Boostrap (we add things such as the close action to the Label in the Toolbar for [example](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toolbar.html)). This list goes on and on...

For this reason, we'd like to implement these basic components here and draw ideas from both of these open source projects mentioned. While this may take more time, it will allow us to be a bit more prescriptive in our approach and make sure it is consistent with our design standards. We can also ensure that we properly document these patterns in our Storyboard. However, there may be cases we can quickly draw on other open source solutions w/ minor modification, so I think your point is still valid...

We are currently strategizing about which components we'd like to implement and will be sharing this in the next PF React Community Meeting (look for an announcement later this week). We'll also be discussing a contribution guideline proposal, a release process proposal (i've started researching `semantic-releases` as an option), and asking for your feedback!

Very much appreciate your help and look forward to getting this going soon!

**Comment by priley86** [comment]
@jtomasek i should also point out, that there exists a large number of complex patterns that have been implemented outside of PF that we'd like to standardize w/ React and our designs as part of this process. Graphs, Charts, Table View w/ pagination, List View w/ pagination, etc. Over time, this should make life on everyone easier and build more consistency in products...

Hope this helps.

**Comment by jtomasek** [comment]
@priley86 thanks for the info, much appretiated. My point about react-bootstrap is that we don't necessarily need make user use components which react-bootstrap exposes. We could very simply create wrapper components which would render react-bootstrap components internally (where needed) - allowing us to add usage restrictions to match patternfly standards, while allowing us to leverage the large infrastructure of components which react-bootstrap defines. This might seem not very valuable at first, but in my experience with implementing Toolbar components, I was very happy that I could easily define custom 'patternfly' dropdowns, form inputs, view selector, etc. using react-bootstrap components under the hood. This way I did not have to reimplement non-trivial logic of toggling dropdowns etc. react-bootstrap provides a lot of such utilities. Implementing this from scratch is something I would personally be quite hesitant to do :)

**Comment by priley86** [comment]
@jtomasek I think we are getting into the nuts and bolts of this topic (which is good). I would agree that creating wrapper components is an option (where we create extensions and also restrictions of `react-bootstrap` components). I would also propose that copying all dependency source per component is also an option, and would allow for more customization (w/o all the excess code we don't want).

Take our Alert for example implemented in `react-bootstrap` [here](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Alert.js). We'd have a few more imports that `react-bootstrap` imposes such as the StyleConfig, splitBsProps, etc. I'm perfectly OK with including these imports in our project (as they'd likely make life easier for us too), but there will likely be cases we'll want to change the underlying implementation of these imports or modify them. We'd have the option to extend them, or just reimplement them ourselves (if we copy the source). 

The pros of extending are that we stay in sync with this upstream project more easily as changes are made. It also gives us a chance to contribute to this upstream community as well. The cons of extending are potential challenges w/ modifying the component's source/upstream behavior.

Certainly agree that it would be nice to avoid the non-trivial logic as we have run into this with other projects. At any rate, I think we should still do our utmost to ensure PF Design standards/ proper Storybooks get implemented.

Thoughts on this @jtomasek ?

**Comment by priley86** [comment]
Also - as a follow up. If you feel confident with the "extension" approach, maybe you could share a proposal on this for our `Alert`? @jtomasek

**Comment by bleathem** [comment]
The extension approach is also better aligned with our goal of consuming patternfly-webcomponents in patternfly-react.

**Comment by priley86** [comment]
@bleathem I was talking specifically about "copying React Bootstrap" vs "extending React Bootstrap", but agree that `patternfly-webcomponents` could be extended directly and imported into a React application (as these are standalone components /vanilla es6 modules w/ very few dependencies). When we look at frameworks like `React Bootstrap` or `Reactstrap` though, they are written with a lot of underlying plumbing / nested imports for things such as styling, keyboard/event handling, other helpers, etc which we may decide need updating. Are we OK with incorporating (extending) those same "helpers" into our PF React framework too? I just see the potential for duplication which may be reduced if we "copy" only what's necessary, component by component. Webpack2/Tree shaking should help with eliminating non-used imports, but removing any duplication in an upstream could also be done by manually constructing our components. Just noting this, that's all...

Good topic!
