### ISSUE TITLE
Dual-list selector component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5019]
Introduce a Dual list selector as a new component.

Core issue: https://github.com/patternfly/patternfly/issues/3556
Design: https://marvelapp.com/prototype/12e47bhj

@jessiehuff this might be a good one to review for keyboard interaction.

**Comment by jessiehuff** [comment]
Also [this example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/listbox/listbox-rearrangeable.html) would be great to look at in terms of interaction 🙂
