### ISSUE TITLE
Table - Add Expand/collapse all toggle functionality into the column header 

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#5035]
Similar to how we have a Select/Deselect all functionality built-in if a user specifies the `canSelectAll` prop on the Table, we should have a Expand/collapse all toggle that can be shown in the column header

**Comment by mcarrano** [comment]
On the surface this seems fine. However, there might be reasons I'm forgetting that we did not want to do it this way. @mmenestr I believe you worked on this design. Any reason to not make this addition?

**Comment by mmenestr** [comment]
Yes, the reason we didn't ultimately do it this way is because we wanted the same solution for tables and data lists. Since data lists don't have headers, we decided to put the expand all/collapse all arrow in the toolbar, to the left of the bulk select in the toolbar.
