### ISSUE TITLE
Class to fix data list shifting when rows are dragged

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#5041]
Currently we're setting an inline style of `overflow-anchor: none;` on the data-list once the dragging event starts

https://github.com/patternfly/patternfly-react/blob/196bcb84d8f4bcfba134a92dd8f058d55089c04b/packages/react-core/src/components/DataList/DataList.tsx#L316

We added a class `.pf-m-drag-over` that can be applied to the data-list while dragging instead.

https://github.com/patternfly/patternfly/pull/3574/files

cc @kmcfaul

**Comment by boaz0** [comment]
@mcoker @kmcfaul can I work on this?
