### ISSUE TITLE
Not able to use Skeleton

### ISSUE THREAD

**Issue by QasimRRizvi** [patternfly/patternfly-react#5045]
**Describe the issue. What is the expected and unexpected behavior?**
Trying to add skeleton in my code, but when I did import through ```import { Skeleton } from "@patternfly/react-core";```
Expected Behavior: it imports skeleton.
Actual Behavior:  it's showing red underline, on hover it says ```Module '"../../../../node_modules/@patternfly/react-core/dist/js"' has no exported member 'Skeleton'.ts(2305)```

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Import Skeleton through @patternfly/react-core.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug or maybe I'm doing something wrong

**What is your product and what release version are you targeting?**
using ```@patternfly/react-core": "^4.32.1```

**Comment by jschuler** [comment]
Skeleton is contained in `@patternfly/react-core@4.50.2`. Can you check what version of react-core is in your workspace at `"../../../../node_modules/@patternfly/react-core/package.json`?

**Comment by QasimRRizvi** [comment]
Ohh, it's ```version: 4.47.0```.
So, that's the reason why skeleton not working for me.
BTW thanks @jschuler  for the guidance
