### ISSUE TITLE
bug(DataListDragButton): isDisabled add `pf-m-disabled` class but one can still move around the row

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5048]
**Describe the issue. What is the expected and unexpected behavior?**

When DataListDragButton has isDisabled set one should not be able to move the row around.

**Comment by KKoukiou** [comment]
@kmcfaul any idea about a workaround here to disable dragging for specific items, till it's fixed properly?

**Comment by redallen** [comment]
I know a way to quickly fix this.

**Comment by redallen** [comment]
I have a dirty fix to make the item not draggable, but we probably also want to support an `isFixed` behavior which keeps the item in the existing order.

**Comment by KKoukiou** [comment]
> I have a dirty fix to make the item not draggable, but we probably also want to support an `isFixed` behavior which keeps the item in the existing order.

I would say that isFixed on DataListItem and isDisabled on DataListDragButton should not be both exposed. One wants to disable the drag button when they want the row to be fixed.
