### ISSUE TITLE
Add Drawer and MasterDetails demos(?)/variants(?) which incorporate a sliding splitter

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#5050]
Create interactive demos that show usage of the Splitter component. A core issue has been opened here to build the required layouts: https://github.com/patternfly/patternfly/issues/3610

**Comment by mcarrano** [comment]
Per discussions with Core we decided to move the splitter to be a feature of the drawer component rather than a free-standing component. @mcoker anything more to add?

**Comment by mcoker** [comment]
That's correct. The core work is complete - https://github.com/patternfly/patternfly/pull/3659
