### ISSUE TITLE
Gallery layout supports customizable min/max-width

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#5055]
PRs:
* https://github.com/patternfly/patternfly/pull/3549/
* https://github.com/patternfly/patternfly/pull/3703/

You can override the column width by setting `--pf-l-gallery--GridTemplateColumns--min{-on-[breakpoint]}` and `--pf-l-gallery--GridTemplateColumns--max{-on-[breakpoint]}`

Examples are on https://pf4.patternfly.org/layouts/gallery

**Comment by tlabaj** [comment]
cc @mcarrano is this one on the roadmap?
