### ISSUE TITLE
DatePicker omitting onChange event  

### ISSUE THREAD

**Issue by akshygupt** [patternfly/patternfly-react#5069]
**Describe the issue. What is the expected and unexpected behavior?**
The patternfly react-datetime props are omitting onChange event, there is no way to use DatePicker with typescript. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. There is no work around, it's completely blocking me.

**What is your product and what release version are you targeting?**
Product - @patternfly/react-datetime@4.1.0

**Comment by tlabaj** [comment]
this issue has been addressed in PR  #5184
