### ISSUE TITLE
Expandable Table with ID column - additionalFormaters is not iterable

### ISSUE THREAD

**Issue by knokit** [patternfly/patternfly-react#5076]
**Describe the issue. What is the expected and unexpected behavior?**
Expandable table, with an 'ID' column, can't be rendered due to `TypeError: additionalFormaters is not iterable`.
Prior to #4899 it was working fine. Perhaps checking if `additionalFormaters` is an array on [body-row.tsx:L74](https://github.com/patternfly/patternfly-react/blob/b2685a90205497936d7f87656bc186a7de5dcc0d/packages/react-table/src/components/Table/base/body-row.tsx#L74) might fix it.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/expandable-table-w-id-column-jpyh6?file=/src/Table.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. It's blocking me, as the table cannot be rendered at all. Had to downgrade react-table to a previous version.

**What is your product and what release version are you targeting?**
@patternfly/react-table@4.19.5

**Comment by jschuler** [comment]
Thanks for reporting @knokit ! The bug turned out to be a bit more subtle, it was due to a naming collision between an internal Table property named `id` and columns that also have the title of `ID`

**Comment by knokit** [comment]
Thanks @jschuler!
