### ISSUE TITLE
Support for React 17 in PatternFly 3?

### ISSUE THREAD

**Issue by Mhbuur** [patternfly/patternfly-react#5077]
I tried to update to React 17.0.1 and it seems that at least menu items in the masthead breaks (on click and drop down menus dont work). I believe this is due to the change of event logic with React 17, but I have not been able to locate the specific problem - I guess it also could be Bootstrap. I'm using latest PatternFly 3 release.

Any plans on supporting React 17 in PatternFly 3?

**Comment by redallen** [comment]
We have no immediate plans to support React 17 in PatternFly 3. We will evaluate it when we add support for React 17 PatternFly 4.
