### ISSUE TITLE
PF 4 Table Component (Reactabular)

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#509]
Provide Table component based on design and CSS implementation from this issue: patternfly/patternfly-next#513. It has been decided to use Reactabular for this, similar to PF3.

Related to #402 and https://github.com/patternfly/patternfly-next/issues/513

**Comment by dmiller9911** [comment]
Provide Table component based on design and CSS implementation from this issue: https://github.com/patternfly/patternfly-next/issues/513. It has been decided to use Reactabular for this, similar to PF3.

**Comment by rachael-phillips** [comment]
Are we ready to close this issue, @karelhala ?

**Comment by karelhala** [comment]
@rachael-phillips yes, we are!
