### ISSUE TITLE
Jump links demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5103]
Create a more robust jump links demo according to the designs here: https://github.com/patternfly/patternfly-design/issues/792. Core issue: https://github.com/patternfly/patternfly/issues/3560

**Comment by mcarrano** [comment]
@redallen I think you covered this in your last PR, but let me know if more work is needed here. Thanks.

**Comment by redallen** [comment]
Nope. Closed in #5314.
