### ISSUE TITLE
React peer dependency version restriction

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#5108]
When using npm@7 and react 17.x PF throws invalid peer dependency error (npm@7 will try to install all peer dependencies).

Is it possible to change the version restriction of React peer dependency from `^16.8.x` to `>=16.8.x`? As far as I can tell PF4 works with react 17.

You can get around this error by using `--force` or use legacy peer deps resolution, but that can lead to issues with other packages.

**Comment by Hyperkid123** [comment]
cc @evwilkin

**Comment by redallen** [comment]
> As far as I can tell PF4 works with react 17.

I'm hesitant to make that claim until we upgrade our workspace to React 17 and ensure our 3rd party deps also work with React 17. We'll change the peer dependency to `^16.8.0 || ^17.0.0` once we upgrade.

**Comment by Hyperkid123** [comment]
It is not critical we won't be migrating to npm@7 any time soon, it's just something I have noticed while playing around with the new stuff.
