### ISSUE TITLE
Compound expandable table refreshes page when in edit mode

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#5118]
**Describe the issue. What is the expected and unexpected behavior?**

When selecting a [compound expandable](https://www.patternfly.org/v4/components/table/#compound-expandable) table cell (it's a button element), when the table is also [editable](https://www.patternfly.org/v4/components/table/#editable-rows), a full page refresh occurs instead of expanding the cell.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Add `onRowEdit={() => {}}` to a compound expandable table and then select one of the expandable cells. Notice it attempts to submit the form to the current url and a "?" query param token is added to the url.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug. It's not blocking. It's not a combination of features we even "officially" support, though I think the general expectation is that the table features are composable and can be used along with one another. We did work around the issue by abandoning this workflow and instead of trying to get expandable cells to be editable, we opt for a workflow where we instead use a [selectable](https://www.patternfly.org/v4/components/table/#selectable) table and launch a modal with a form inside to do the edit operation. I think this pattern ended up being a better workflow in the end, but wanted to report the unexpected interaction fwiw.

**Comment by jschuler** [comment]
@seanforyou23 now that #5058 is merged can this be closed?

**Comment by seanforyou23** [comment]
Yep @jschuler!
