### ISSUE TITLE
Tooltips on disabled actions in react-table

### ISSUE THREAD

**Issue by wsamsnyder** [patternfly/patternfly-react#5127]
**Describe the issue. What is the expected and unexpected behavior?**
I have a use case where I would like to disable an `action` in the action's dropdown on a `Table` row and display a tooltip on why it is disabled. Looking through similar issues, mainly #2470 and #4581, the workaround for standard `DropDownItem`s is to wrap the it in a tooltip; this is not viable because the `Table` is generating the `DropDownItem`s.  

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Passing `tooltip` will display the tool tip, as long as the action isn't diabled. Passing `isDisabled` will create the desired button behavoir but will also disable the tooltip. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, Blocking.

**Comment by jschuler** [comment]
Somewhat of a workaround, but you can add some style to the action/dropdown item to see the tooltip
```
{
        title: 'Some action',
        onClick: (event, rowId, rowData, extra) => console.log('clicked on Some action, on row: ', rowId),
        tooltip: 'Hello',
        isDisabled: true,
        style: {
          pointerEvents: 'auto',
          cursor: 'default'
        }
      },
```

**Comment by jgiardino** [comment]
We also require this functionality. I will pass along the work-around, but I also expect this tooltip to be available when using the keyboard to interact with the menu. Without testing this work-around, I can't say this solution isn't keyboard accessible. But when testing the work-around for https://github.com/patternfly/patternfly-react/issues/4581, this solution did not support keyboard accessibility.

**Comment by jgiardino** [comment]
I just realized I could test this using the PF examples 🤪 and the workaround is actually keyboard accessible.

**Comment by wsamsnyder** [comment]
I was not able to work my way back to this section of the code until recently and this workaround worked perfectly. Thanks @jschuler!

**Comment by jschuler** [comment]
Closing since the workaround is good for now
