### ISSUE TITLE
Popover not dismissing on click of an action button inside the popover

### ISSUE THREAD

**Issue by darrenrevans10** [patternfly/patternfly-react#5132]
**Describe the issue. What is the expected and unexpected behavior?**

The Docs state that...
Popovers are triggered by a click and dismissed in one of the following ways:

The user clicks the exit icon
**The user clicks an action button inside the popover**
The user clicks anywhere on the screen outside the popover

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
You can see this unexpected behavior here, https://www.patternfly.org/v4/components/popover/react. The first example shows a button within the popover that doesn't automatically dismiss the popover.

**Comment by jschuler** [comment]
@mcarrano is this guideline still accurate? If so do we differentiate between types of action buttons? For example the datepicker has buttons but you wouldn't expect the popover to auto-close. Should there be a special type of button that can be used within a Popover to make it auto-close?

**Comment by mcarrano** [comment]
@jschuler I agree that clicking on an action should not always close the popover. But I think it should also be possible to include a button besides the close button that will trigger an action and close the popover, like a modal. Is this feasible? @mmenestr anything to add? I believe you authored the guideline document.

**Comment by mmenestr** [comment]
Yes, I can definitely change it according to what we decide here!
When writing that guideline I was referring to actions like "Learn more" that would link you out to external documentation for more information, and assumed that clicking on it would close the popover. But let me know if that's not the case, I don't feel too strongly about this!

Also, could you give me more background on the use case where you would have a date picker inside a popover? Like what would the scenario be?

**Comment by mcarrano** [comment]
> Also, could you give me more background on the use case where you would have a date picker inside a popover? Like what would the scenario be?

@mmenestr I think this was just referencing the fact that the date picker calendar uses the popover as a container for the calendar. It's all integrated as part of the date picker and not something a designer using the date picker needs to be concerned with.

**Comment by jschuler** [comment]
@mcarrano @mmenestr thanks, sounds like we need to provide some way to add elements into the popover that can auto-close it. I'll take a look at this and see what we can do in that regard!

**Comment by jschuler** [comment]
@mmenestr maybe the docs could be updated to reflect that actions buttons may close the popover? (not always)
