### ISSUE TITLE
Dropdowns to support Native Select "Type Selection"

### ISSUE THREAD

**Issue by andrewballantyne** [patternfly/patternfly-react#5141]
**Describe the issue. What is the expected and unexpected behavior?**

When viewing a short list of elements (say 3) having a typeahead ([PF design](https://www.patternfly.org/v4/components/select#typeahead)) functionality is a bit much.

Suggestion would be to support the native functionality of the Select component so typing is straight forward to the user:
[MDN \<select\> Doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See the MDN select component for desired functionality. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Enhancement

**What is your product and what release version are you targeting?**

OpenShift Console, not a high priority but ideally in time to code it into 4.8 (~March 2021)

**Comment by andrewballantyne** [comment]
bump

**Comment by tlabaj** [comment]
Hi @andrewballantyne.  PF has the [FormSelect](https://patternfly-react.surge.sh/components/form-select) component.  It is based off the MDN select.  Would this better suit your needs?

**Comment by andrewballantyne** [comment]
@tlabaj that would be indeed what I was looking for when I made this issue. Sorry that I missed this component. Thanks! Closing the issue.
