### ISSUE TITLE
Can @patternfly/react-datetime DatePicker component be a controlled component?

### ISSUE THREAD

**Issue by jeudy100** [patternfly/patternfly-react#5142]
**Describe the issue. What is the expected and unexpected behavior?**
I am trying to use the date picker component (`@patternfly/react-datetime`) to scroll through a certain range of dates. I have another component that is just a left and right arrow button to go forward or backward a day. From what I have tried and looking through the code, it seems like the date picker can't be controlled and the value attribute for the date picker is just used as a default value. I was wondering if it would be possible to make this a controlled component as well? I made a codesandbox below giving a simple example of how I am using the date picker and then I made a simple native html date picker (`<input type="date"/>`) that can be controlled to show a working example. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/busy-worker-gtzls?file=/src/App.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

**What is your product and what release version are you targeting?**
@patternfly/react-datetime@lateset

**Comment by redallen** [comment]
We don't support this behavior but post-refactor it's now possible. See #5161.
