### ISSUE TITLE
VncConsole fails to create connections

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#5157]
**Describe the issue. What is the expected and unexpected behavior?**
Connecting to the VncConsole does not work. An error is raised at https://github.com/patternfly/patternfly-react/blob/master/packages/react-console/src/components/VncConsole/VncConsole.tsx#L114

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Attempt to connect via VncConsole

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug, blocking move to PF4 react-console

**What is your product and what release version are you targeting?**
OpenShift 4.7

**Comment by jeff-phillips-18** [comment]
@KKoukiou Any thoughts?

**Comment by KKoukiou** [comment]
> @KKoukiou Any thoughts?

I will take a look today.

**Comment by KKoukiou** [comment]
Ok I can reproduce of course, the thing is that this package is really hard to test within the demo app. I need to test it with some actual VNC server running. If you enable debug in the logging level from the consumer you can see the actual issue. 
So I think the following patch will fix this, but I really need to test it before sending the PR.

``` diff

diff --git packages/react-console/src/components/VncConsole/VncConsole.tsx packages/react-console/src/components/VncConsole/VncConsole.tsx
index cc9be7cdc..995964d5d 100644
--- packages/react-console/src/components/VncConsole/VncConsole.tsx
+++ packages/react-console/src/components/VncConsole/VncConsole.tsx
@@ -90,7 +90,7 @@ export const VncConsole: React.FunctionComponent<VncConsoleProps> = ({
 }) => {
   let rfb: any;
   let novncStaticComponent: React.ReactNode;
-  let novncElem: HTMLDivElement;
+  const novncElem = React.createRef<HTMLDivElement>();
 
   const [status, setStatus] = React.useState(CONNECTING);
 
@@ -111,7 +111,7 @@ export const VncConsole: React.FunctionComponent<VncConsoleProps> = ({
         shared,
         credentials
       };
-      rfb = (new RFB() as any)(novncElem, url, options);
+      rfb = (new RFB() as any)(novncElem.current, url, options);
       addEventListeners();
       rfb.viewOnly = viewOnly;
       rfb.scaleViewport = scaleViewport;
@@ -196,7 +196,7 @@ export const VncConsole: React.FunctionComponent<VncConsoleProps> = ({
   }
 
   if (!novncStaticComponent) {
-    novncStaticComponent = <div id={consoleContainerId} ref={e => (novncElem = e)} />;
+    novncStaticComponent = <div id={consoleContainerId} ref={novncElem} />;
   }
 
   return (

```

**Comment by KKoukiou** [comment]
Ignore, I will just run debug it against cockpit.
