### ISSUE TITLE
CatalogView extension: component migrated to pf4 still has pf3 dependencies. 

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#5167]
**Describe the issue. What is the expected and unexpected behavior?**

CatalogView extension: component migrated to pf4 still has pf3 dependencies. 
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**

**Comment by spadgett** [comment]
This issue is still valid and blocks OpenShift from removing its PF3 dependency.

**Comment by spadgett** [comment]
This should be fixed by #5987.

**Comment by tlabaj** [comment]
closed by #5987
