### ISSUE TITLE
Select menu component doesn't scroll to overflowe options with up and down arrow keys

### ISSUE THREAD

**Issue by jeudy100** [patternfly/patternfly-react#5180]
**Describe the issue. What is the expected and unexpected behavior?**
When I create a select component with enough options that they overflow and cause the menu to be scrollable, I can use the arrow keys to go to the next/previous option in the list until I get to the overflowed options and it continues going to the next option but without scrolling to it. Is this a bug, or is the scrolling aspect meant to be implemented separately/still needs to be implemented?
 
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/recursing-hooks-u2qvl

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug (maybe)

**What is your product and what release version are you targeting?**

**Comment by tlabaj** [comment]
I tested this in our workspace and it works as expected.
