### ISSUE TITLE
Toggle Group buttons are missing `type="button"`

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#5195]
**Describe the issue. What is the expected and unexpected behavior?**
When using a Toggle Group component inside a form inside a modal, clicking one of the buttons closes the modal.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Here is a [codesandbox](https://codesandbox.io/s/nifty-haze-nrnrj?file=/index.js) that demonstrates the issue.

This codesandbox includes the react component inside a modal, as well as two test `<button>` elements inside the modal, one with `type="button"` and one without. Clicking either the toggle group button or the "Test without type" button will close the modal. But clicking the "Test with type" button will not close the modal. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. Our workaround currently is to use the html for this component and add the `type="button"`. This works as a temporary solution, since this component will be disabled in our first implementation. 

**What is your product and what release version are you targeting?**
An application to be released on cloud.redhat.com by Summit.

**Comment by tlabaj** [comment]
@mcoker You probably need to make  similar update in core.
