### ISSUE TITLE
Component - Tabs

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#52]
Implement a component that provides the following UI element:

- [PatternFly Tabs](http://www.patternfly.org/pattern-library/widgets/#tabs)

Acceptance Criteria:

- When rendered, the component matches the examples in the PatternFly Pattern Library (see link above)
- Support for basic tabs, justified tabs, patternfly tabs, secondary tabs

**Comment by priley86** [comment]
Existing PR is quite dated and needs updating...
https://github.com/patternfly/patternfly-react/pull/49

**Comment by dabeng** [comment]
Hi @priley86 , because #49 involves many dated code snippets and conflicts, I created new [PR](https://github.com/patternfly/patternfly-react/pull/112) for component tabs.
