### ISSUE TITLE
React fragments and VerticalNav

### ISSUE THREAD

**Issue by Mhbuur** [patternfly/patternfly-react#521]
I'm trying to structure my app into components that deliver different parts of the navigation parts. 

One component should deliver the VerticalNavItems for the side menu. Hence multiple items returned. I wanted to use the React.Fragment element to wrap the result, but it doesn't work. 

Here is a trivial example. The two items "hello", "world" are rendered. The items inside the React.Fragment block are not rendered.

Is it not possible to use fragments this way or what is going on?

```
<VerticalNav>
  <VerticalNavMasthead>...</VerticalNavMasthead>
  <VerticalNavItem title="hello" />         
  <VerticalNavItem title="world" />
  <React.Fragment>
    <VerticalNavItem title="here">
      <VerticalNavSecondaryItem title="is johnny" />
    </VerticalNavItem>
  </React.Fragment>
</VerticalNav>
```

**Comment by dmiller9911** [comment]
@Mhbuur Sadly we are iterating over children here. https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-react/src/components/VerticalNav/VerticalNav.js#L306 Your best bet is to use the `items` prop or use an array for the items

```
<VerticalNav>
  <VerticalNavMasthead>...</VerticalNavMasthead>
  <VerticalNavItem title="hello" />         
  <VerticalNavItem title="world" />
{[
    <VerticalNavItem key="here" title="here">
      <VerticalNavSecondaryItem title="is johnny" />
    </VerticalNavItem>
]}
</VerticalNav>
```
keys are needed if you go the array route.

**Comment by Mhbuur** [comment]
Thanks! That explains.

Could you elaborate on the items prop route. How would I separate the "here is johnny" items into another component?

**Comment by dmiller9911** [comment]
It is sadly an all or nothing on that prop.  It would look something like
```jsx
<VerticalNav
  items={[
    {title: 'hello' },
    {title: 'world' },
    { title: 'here', subItems: [{ title: 'is johnny' }] }
  ]}
>
  <VerticalNavMasthead>...</VerticalNavMasthead>
```
If they the items are from different sources you can just concat the arrays
```jsx
<VerticalNav
  items={[
     {title: 'hello' },
    ...someBasicItems,
    ...additionalItems,
  ]}
>
```

**Comment by dgutride** [comment]
Moving to closed based on above discussion
