### ISSUE TITLE
Drawer: update splitter keyboard interaction & aria labelling

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#5212]
Drawer splitter keyboard behavior needs updating and aria labelling needs to be refined. See [Jessie's comment](https://github.com/patternfly/patternfly-react/pull/5193#pullrequestreview-544476838)

**Comment by jessiehuff** [comment]
@mcarrano Can we add this to the roadmap? We've seen it as an issue in Quick Starts.
