### ISSUE TITLE
will TreeView support customized Badge content?

### ISSUE THREAD

**Issue by myan9** [patternfly/patternfly-react#5214]
**Describe the issue. What is the expected and unexpected behavior?**
1. enhancement: `TreeView` in master hardcoded the Badge content to be the number of children. Will this be customizable? For example, I have a use case that showing a customized summarization of the children using Badge, but I can't do it via TreeView.Props directly. I have to hack the badge innerText after the component is rendered.

2. bug:  in [TreeView.tsx](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/TreeView/TreeView.tsx#L92), `badgeProps` was incorrectly set to `checkProps`. It's not blocking me since I'm not using checkProps currently.

3. bug: in [TreeView.tsx](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/TreeView/TreeView.tsx#L83), TreeView.name's type is `ReactNode`, but `TreeViewListItem` used `name.toString()` as `key` of the array.  I tried using a ReactNode for the name, but I got react error with duplicated keys.

**What is your product and what release version are you targeting?**
product: https://github.com/IBM/kui
release version: "@patternfly/react-core": "4.79.2"

**Comment by tlabaj** [comment]
cc @mcarrano @mcoker

**Comment by mcarrano** [comment]
@tlabaj I am fine with allowing the badge contents to be customizable, but can this change be made so that it still defaults to just counting the number of children in a node?

**Comment by tlabaj** [comment]
Yes.  We can make that change @mcarrano

**Comment by mcarrano** [comment]
@myan9 We have a PR up to add this support. You can see a preview here: https://patternfly-react-pr-5512.surge.sh/components/tree-view#with-custom-badges Is this what you were expecting?

cc @tlabaj
