### ISSUE TITLE
Tab key does not jump/focus the next input field for Table with Inline Edit

### ISSUE THREAD

**Issue by sbernhard** [patternfly/patternfly-react#5217]
I'm using https://patternfly-react-pf3.surge.sh/?path=/story/patternfly-react-content-views-table-view--table-with-inline-edit-row 

- I press "Edit" on the first line
- Issue 1: is it somehow possible to select and focus the first column?
- I select the first column by using the mouse
- I change the entry and press "tab" to jump and focus the second column
- Issue 2: this doesn't work. The next column is not selected

Is there a workaround to get this working? Especially issue 2?

The question is about patternfly v3.

**Comment by sbernhard** [comment]
activity.
please fix the issue :-)

**Comment by sbernhard** [comment]
the issue still occurs.

**Comment by nicolethoen** [comment]
Hello @sbernhard!

Unfortunately, patternfly-3 and this implementation of a table component have been deprecated for some time. If you'd like to fix this issue, we'd be happy to merge it into the codebase.

Alternatively, we do have a patternfly-4 table implementation which is fully supported: https://www.patternfly.org/v4/components/table.

Let me know if you have any other questions.
