### ISSUE TITLE
Tooltip lifecyle bug - Tooltip disappears on table sorting

### ISSUE THREAD

**Issue by johnsonm325** [patternfly/patternfly-react#5252]
I've got a table where each row has a state icon with a tooltip. When I sort that table based on state, I lose my tooltip, unless that row is in the same position after the sort. If I filter or sort based on a different column, I keep my tooltip. I'm still rendering the component that renders the tooltip and all of the data is there to build the tooltip, but it doesn't show up.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
I appear to only be getting this in a custom table, which I was having a hard time recreating in the sandbox provided. The reason I think it's only on a custom table is because in the sandbox provided by Joachim (https://codesandbox.io/s/funny-ptolemy-r4svd?file=/index.js) we were not able to reproduce the issue.

This is a bug and there is a workaround where I give the tooltip a unique key on the sort. The tooltip shows up when I add the key.

My product is the drift-frontend under the Red Hat Insights product. Here is where the broken component is: https://github.com/RedHatInsights/drift-frontend/blob/master/src/SmartComponents/StateIcon/StateIcon.js

**Comment by jschuler** [comment]
@johnsonm325 @mturley Maybe Tooltip has some trouble location the reference to the child if it's an `svg`.
I don't yet know why, but wrapping the svg in a span should fix it for you as well.
In StateIcon:
`<span>{this.icon()}</span>`
