### ISSUE TITLE
Dual List Selector is not usable in forms

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#5263]
**Describe the issue. What is the expected and unexpected behavior?**

Dual List Selector is not usable in forms as the list items (buttons) are not `type="button"` so when users click on them, it triggers form submit.

https://www.patternfly.org/v4/components/dual-list-selector

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/reverent-goldstine-jxixo

![dual](https://user-images.githubusercontent.com/32869456/102239298-ffd5a300-3ef6-11eb-9657-91b740b5d5c7.gif)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug.

**What is your product and what release version are you targeting?**

Data Driven Forms, Cost Management

cc @Hyperkid123

**Comment by Hyperkid123** [comment]
I am also curious why are these list items buttons at all? As far as I see, selecting them does not really trigger any event. The movement buttons do. Could it be a normal `option` like within native HTML multiple select?

**Comment by mcarrano** [comment]
@mcoker @tlabaj @kmcfaul thoughts?

**Comment by mcoker** [comment]
re: the `type`, that just looks like an oversight. They're set to `type="button"` in the core docs.

**Comment by nicolethoen** [comment]
There is an outstanding issue to consider the html structure as far as it impacts accessibility. And considering that the tree view implementation does not use a button, I think that moving away from a button during that update will be discussed. I'll be sure to note it in the open issue.
