### ISSUE TITLE
Dual List Selector: provide clearer guidance for using React Nodes as options

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#5264]
**Describe the issue. What is the expected and unexpected behavior?**

https://www.patternfly.org/v4/components/dual-list-selector#duallistselector

`availableOptions` and `chosenOptions` are type of React Node however when you put a Node there, the component breaks on select, it cannot handle filtering etc.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/funny-hooks-zu29f

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug.

**What is your product and what release version are you targeting?**

Data Driven Forms. Cost Management.

**Comment by nicolethoen** [comment]
Hi @rvsia,

I'd love to point your attention to the following example in the PatternFly documentation: 
[Using more complex options with actions](https://www.patternfly.org/v4/components/dual-list-selector#using-more-complex-options-with-actions)

Out of the box, the component expects the options to be strings, but allows for functions to be provided when using more complex React nodes as options for features and actions such as Search. Could this example meet your needs?

**Comment by rvsia** [comment]
@nicolethoen 

Thanks for the quick response!

Not sure if the example alone is enough. I would expect this information stated somewhere in the documentation. (In the description of the props?)

Or maybe the component should throw a warning if there is a node as an option. (Something like `You are using nodes as options, please provide onOptionSelect function.`)

**Comment by nicolethoen** [comment]
Makes sense. I will update the issue to improve the documentation and consider adding warnings.
