### ISSUE TITLE
Progress component: `title` prop is a string, could be more flexible as a `React.ReactNode`

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#5276]
I have a use case where I want to be able to click on the title of a `<Progress>` bar and have a popover appear with more details about the current phase of the process. I can't do that right now without breaking the TypeScript type of the `title` prop, which is currently `string`.

**Comment by boaz0** [comment]
This is going to be tricky when the truncate props is set because we will have to apply the CSS styling directly to the element that contains the text somehow.

**Comment by mturley** [comment]
hm. maybe if you pass a node it just requires you to handle truncation yourself. We could have it check if `typeof title === 'string'` and ignore the truncate prop. Would have to document that clearly.

**Comment by mturley** [comment]
I'd still like to address this when I have time.

**Comment by mturley** [comment]
bump
