### ISSUE TITLE
Resizable drawer: splitter disappears on parent resize

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#5283]
Resizing parent width to be smaller when drawer is already at min width makes splitter disappear

**Comment by kmcfaul** [comment]
@mcoker Do you mind taking a quick look at this issue from the core-side? From what I can tell, the panel width doesn't matter, it's just when the parent size is narrowed, after a point the `::after` styling that forms the splitter disappears.

**Comment by mcoker** [comment]
@kmcfaul submitted https://github.com/patternfly/patternfly/pull/3788 which should fix this.

**Comment by kmcfaul** [comment]
Closed in #5313
