### ISSUE TITLE
Resizable drawer: resizing inconsistent with nested resizable drawers

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#5285]
resizing is inconsistent when using nested resizable drawers; drawers no longer resize independently

**Comment by evwilkin** [comment]
@christianvogt @serenamarie125 can you confirm Vojta's understanding above of this issue is correct?  Thank you!

**Comment by christianvogt** [comment]
We will have 2 levels of nested drawers (like this example: https://gist.github.com/christianvogt/b8018b9798913ecfb2cb0ef4cf9f4d12). However they are not immediate children. When one of the drawers is resized, I wouldn't expect the other to be affected. Therefore your description is correct. However this is just my opinion and if the intended behavior of the PF drawer had different goals, let's discuss.

**Comment by wojta** [comment]
Thanks for the explanation, this is a little bit different case to one I made. I'll try to do it your way. 
Do you intend to split the workspace by the drawers? Maybe we should have it implemented in a completely different component.

**Comment by christianvogt** [comment]
We will also have another drawer at the bottom of the page for our terminal. I think we'll have at most 3 nested drawers. But again they are not direct descendants of each other.

**Comment by wojta** [comment]
We agreed with @christianvogt that after recent changes it is no longer an issue.
