### ISSUE TITLE
Resizable drawer: no touch support

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#5287]
Does not work with touch device (however only tested using chrome dev tools on desktop)

**Comment by DaoDaoNoCode** [comment]
@nicolethoen When I am working on my issue #5279 , I realized maybe this issue could also be fixed. Should we use `PointerEvent` instead of `MouseEvent` to support touch?

**Comment by nicolethoen** [comment]
very possible! I'll look into it!
