### ISSUE TITLE
Resizable drawer: collapsed inline drawer always consumes height

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#5289]
Inline drawer with `position=”bottom”` always consumes height when collapsed

**Comment by mcoker** [comment]
Submitted https://github.com/patternfly/patternfly/pull/3785, which should hopefully fix this issue.

**Comment by kmcfaul** [comment]
Fixed in core bump to v4.76.2 (#5338). 

Drawer container needs to have a set height, like other bottom drawer examples.
