### ISSUE TITLE
Resizable drawer

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-react#5291]
OpenShift 4.8 is looking to adopt the resizable drawer in 3 Epics for ODC (Dev Console: Quick Starts, Web Terminal, & Topology side panel) but has identified the included issues to be resolved:

https://docs.google.com/document/d/1BlVATH7MWtHzWLOMWl6YmUy4ZrOqOm2AwLG5Ilm_rR8/edit

**Comment by evwilkin** [comment]
@mcarrano @kmcfaul FYI set up this Epic to track the Resizable drawer issues 👍

**Comment by tlabaj** [comment]
closing this since all issues in the epic have been addressed
