### ISSUE TITLE
Enable translation of pagination string

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#5322]
**Describe the issue. What is the expected and unexpected behavior?**
The following strings that displays in the pagination component does not appear to support translation:
> 1 - 10 of 333 

> of 34

as shown in this example:
![image](https://user-images.githubusercontent.com/21063328/104490506-edef2a80-559e-11eb-9836-2aa31644ab8d.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Currently all strings in the Pagination component are defined in the `titles` prop. Both instances of "of" appears to be missing.

However, I think to properly translate these strings, they should by provided for translation as a whole, for example:
`{{first}} - {{last}} of {{total}}` for "1 - 10 of 333"

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement 🤷 

**What is your product and what release version are you targeting?**
No timeline on translation requirements yet.

**Comment by jgiardino** [comment]
A couple of additional notes when looking at the `titles` prop:
1. `itemsPerPage` does not appear to be used. Currently, `optionsToggle` has the same default string, and this is what seems to be used for the 🔽 options menu toggle.
2. `page` does not support translation. When testing this, I used "test 3", and in the example below, you can see an "s" is added to the end. So when viewing a translated UI for Japanese, for example, this doesn't work. But relative to the original issue description, the translation for "page" should be provided as part of the entire string for proper translation, something like `{{current page}} of {{count}} pages` or even just `of {{count}} pages` (given that current page is presented in an input).
    ![image](https://user-images.githubusercontent.com/21063328/104489215-5e954780-559d-11eb-8a24-2ab0f0373aa9.png)


These 2 items are not blocking issues, I just wanted to note them as they're semi-related to the original issue.

**Comment by rkaw92** [comment]
I agree that allowing one to translate the entire string is the right solution - this enables the use of proper translation toolkits such as Mozilla's Fluent that does pluralization on its own. Attempting to "pluralize" may be outside PatternFly's responsibilities, as it seems to belong to the domain of i18n.
