### ISSUE TITLE
Form Select only supports string type value.

### ISSUE THREAD

**Issue by dev-hikun** [patternfly/patternfly-react#5326]
**Describe the issue. What is the expected and unexpected behavior?**

I want to use Object type value in form select component, but form select only supports string type value.
so my code added an unnecessary JSON conversion process.
I think that would be more convenient if there is a Select components that supports various types of string rather than present

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

[Patternfly Form Select](https://www.patternfly.org/v4/components/form-select)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
No.

**What is your product and what release version are you targeting?**
ASAP

**Comment by tlabaj** [comment]
@dev-hikun are you referring to the `label` prop of the `FormSelectOption`?

**Comment by dev-hikun** [comment]
@tlabaj Yes, I hope that the value of the component and the value of the Select component do not only support strings, but also support objects.

**Comment by tlabaj** [comment]
The Form select is built with the  HTML select. Valid content for  an `<option>` is "Text, possibly with escaped characters" (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option).
Could you share more about your use case?  Perhaps the [Select](https://www.patternfly.org/v4/components/select) or [Menu](https://www.patternfly.org/v4/components/menu) might better align with your use case.  You can find a demo [here](https://www.patternfly.org/v4/demos/composable-menu#select-menu) on how to build a select with the menu component.
