### ISSUE TITLE
Jump links don't work with anchor links 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-react#5327]
Jump link component doesn't support standard anchor links. 

Example: Send an email to a customer with a link directly to a section of the Trust page https://cloud.redhat.com/security/insights#section-faq. After landing on page, I expect to be able to use jump links. They don't work as expected/at all.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

![jump-links](https://user-images.githubusercontent.com/5385435/104473198-b6768300-558a-11eb-8998-257af2869e32.gif)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
[cloud.redhat.com](cloud.redhat.com) current version

**Comment by redallen** [comment]
The `<base href="/">` tag is the reason for your pain.

![image](https://user-images.githubusercontent.com/47335686/104474302-dfe3de80-558b-11eb-974e-d4bedfe0ed1e.png)

Removing it fixes it for me. If you can't edit this tag you should change the `href="/security/insights#section-faq"` and add `node="#section-faq"`.

**Comment by AllenBW** [comment]
Desired behavior is when clicking any of the jump links, the url is updated to reflect the selection.  Additionally, whenever navigating to ah jump link via the url, we end up there... (with that link highlighted and the content selected) 

tried both, adding the `node` and removing the base href, still not seeing [success here](https://github.com/RedHatInsights/trust-frontend/pull/21)  wondering if yah have any thoughts @redallen ?

**Comment by redallen** [comment]
Try `onClick={ev => {history.pushState({}, null, `#heading-${i}`); ev.preventDefault()}}`. I just used this in our demo and it worked.

**Comment by AllenBW** [comment]
gonna do something kinda like ☝️ venture outside of react-router 😬  id say this one can be closed as notta bug
