### ISSUE TITLE
Click table column header always sorts by ascending first

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#5329]
**Describe the issue. What is the expected and unexpected behavior?**

If you click the table header of a column that isn’t currently sorting the table, the first sort order is ascending, then the second click it’s descending. There doesn’t appear to be a way to specify the sort order for the first click to be descending.

In the context of a table view with a date column, if someone wants to change the sort order to be date created or modified, it’s going to show oldest first (i.e. ascending). However, in most cases, the user is likely more interested in seeing the newer items first (i.e. descending).

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
No steps to reproduce. The expected behavior doesn't appear to be supported.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
enhancement

**What is your product and what release version are you targeting?**
App Services, nice to have for end of March

cc @mcarrano @christiemolloy

**Comment by mcarrano** [comment]
@tlabaj @jschuler I discussed this issue with @jgiardino and we both agreed that the descending sort made better sense as the default for dates. Is there any reason we couldn't change the default sort order when we know that the data in a table column is a date or time value?

**Comment by jschuler** [comment]
We should add an option or a way to specify the initial sort direction on a column click.
Here's a workaround though @jgiardino 
https://codesandbox.io/s/table-sort-date-desc-qsp9j?file=/index.js

**Comment by mcarrano** [comment]
I will add this to our roadmap for a more permanent solution.
