### ISSUE TITLE
Attribute-value search input

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5332]
Enhance the Search input component to support advanced attribute-value search use cases that allow the user to enter a query string directly in the input field or fill out a search form. 

Designs: https://marvelapp.com/prototype/276i4086

Core: https://github.com/patternfly/patternfly/pull/3783

For keyboard accessibility - treat similar to other dropdown components. Need to manage focus shift into and out of the form.

Requesting project: KeyCloak
Date needed: February
Contacts: @yih-wang, @amysueg

**Comment by nicolethoen** [comment]
@mcarrano do we want to include the autocomplete feature as part of this issue? Or make that a separate issue?

**Comment by mcarrano** [comment]
@nicolethoen I think that could be a separate issue. What do you prefer?

**Comment by nicolethoen** [comment]
I think we'd at least need to meet about what the interaction and configuration expectations would be. Like what sorts of information would be needed from the consumer and when the auto complete would be invoked.

**Comment by mcarrano** [comment]
@nicolethoen I've opened a new issue here so we can elaborate on the requirements for this: https://github.com/patternfly/patternfly-react/issues/5387  I'll add this to the next sprint as follow-on work and can set up a time to talk further bout what's involved. Thanks for bringing this up.
