### ISSUE TITLE
Menu component: add drill-down with breadcrumbs

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5333]
Add optional bread crumbs to drill down menu. See https://github.com/patternfly/patternfly/issues/3491 for designs and core implementation https://github.com/patternfly/patternfly/pull/3797.

When using the collapsible breadcrumb, the consumer should be able to set how many levels to display before collapsing via a prop.

Requesting projects: Multiple (cloud platform, app services)
Date needed: March
Contacts: @ajacobs21e @nlcwong @aprilma419

**Comment by tlabaj** [comment]
closed by #5548
