### ISSUE TITLE
Type of an attribute "variant" of the component "Select" lacks value "panel"

### ISSUE THREAD

**Issue by idevat** [patternfly/patternfly-react#5340]
There is an option `panel` in the `SelectVariant` enum:

https://github.com/patternfly/patternfly-react/blob/f514aecd0125e3f5ca1e301fc4b94e73074d757c/packages/react-core/src/components/Select/selectConstants.tsx#L21-L27

However, the component `Select` allows only values `'single' | 'checkbox' | 'typeahead' | 'typeaheadmulti'`:

https://github.com/patternfly/patternfly-react/blob/f514aecd0125e3f5ca1e301fc4b94e73074d757c/packages/react-core/src/components/Select/Select.tsx#L95

So, typescript complains when `variant` `panel` is used:
```typescript
<Select
  variant={SelectVariant.panel}
  ...
 // [tsserver 2322] [E] Type 'SelectVariant.panel' is not assignable to type '"single" | "checkbox" | "typeahead" | "typeaheadmulti" | undefined'.
```

**Comment by DaoDaoNoCode** [comment]
@idevat Hi, create a PR #5600  for this. You could simply not pass `variant` to `Select` component and make sure you pass `customContent` into it.
