### ISSUE TITLE
Typeahead Select with isCreatable prop: should not offer to create an option that already exists

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#5349]
**Describe the issue. What is the expected and unexpected behavior?**

This can be seen in the Typeahead Select example [here](https://www.patternfly.org/v4/components/select#typeahead), if you turn on the `isCreatable` option and type the full text of an existing option. Both the existing `Alabama` option and the `Create "Alabama"` option appear. It would make sense to me that the "Create" option should only be available if the exact option name you typed in doesn't already exist. (could this cause undesirable behavior in the consumer's `onCreateOption` if a resource with that name already exists?)

![Screen Shot 2021-01-20 at 2 00 52 PM](https://user-images.githubusercontent.com/811963/105222265-48046880-5b28-11eb-8f56-6f0dc638c815.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, or perhaps a design decision?

**What is your product and what release version are you targeting?**

Migration Toolkit for Virtualization. No particular release, not high priority.

**Comment by mturley** [comment]
Still an issue

**Comment by mturley** [comment]
bump

**Comment by DaoDaoNoCode** [comment]
I think this issue has been addressed in https://github.com/patternfly/patternfly-react/pull/6467 so it could be closed.

**Comment by mturley** [comment]
Yep, looks like it! Thanks @DaoDaoNoCode
