### ISSUE TITLE
Treeview: Using search with treeview should reveal leaf nodes matching the search criteria

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#5351]
**Describe the issue. What is the expected and unexpected behavior?**
When using treeview to search a string in the tree, the branch nodes are correctly filtered, however the leaf nodes aren't expanded when there is a match. The user would have to expand manually to see the matched string.
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**
Openshift, unscheduled

cc: @evwilkin

**Comment by evwilkin** [comment]
@mcarrano FYI Treeview discussion
