### ISSUE TITLE
Add collapsible breadcrmb variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5361]
Introduce a collapsible variant of the Breadcrumb to implement core updates here: https://github.com/patternfly/patternfly/pull/3797

Consumer must be able to specify now many levels to show before collapsing via a prop. Default behavior will always be to not collapse the breadcrumb.

**Comment by mcarrano** [comment]
@jessiehuff can you look into accessibility considerations?

**Comment by mcarrano** [comment]
Maybe addressed as part of https://github.com/patternfly/patternfly-react/issues/5333? @kmcfaul ?

**Comment by jessiehuff** [comment]
I think for keyboard interaction I would expect the breadcrumb to follow normal breadcrumb functionality using Tab to navigate through breadcrumb items. The collapsible aspect to the breadcrumb should likely be treated like a modal with a menu inside (enter to open the modal, arrow keys inside that collapsible menu). When the user tabs through all of the breadcrumb options, they use arrow keys inside the menu: up/down to navigate through options, left/right if there is a submenu to be opened or to go back to a parent menu.

![UNADJUSTEDNONRAW_thumb_182](https://user-images.githubusercontent.com/28281340/110037677-bc781d00-7d0c-11eb-9638-67d2e9f83c08.jpg)
For example, here the user would be able to Tab through the interactive elements in the breadcrumb. In this case, "All" link and the badge button. If they press enter on the button, it opens the modal and shifts focus to the first option. Here that would be "Edit". Whatever the functionality is for the mouse user is when they click on this option should be available to keyboard users as well (so if this arrow on edit goes to the parent menu of Edit, pressing enter would do the same). If they press Esc from here, it would go back to the badge button, when they hit Tab again it goes to the first menu item. From there, the user should be able to use up/down arrow keys to go through the options. The first option "Labels" has an arrow key so I assume that opens to a new menu. Pressing enter or left/right arrow keys to navigate this should be possible.

The menu itself should follow [these guidelines](https://www.w3.org/TR/wai-aria-practices-1.2/#keyboard-interaction-12).
