### ISSUE TITLE
Date range - selection issue

### ISSUE THREAD

**Issue by MariSvirik** [patternfly/patternfly-react#5368]
[In Patternfly Date picker -react demo (date range)](https://www.patternfly.org/v4/components/date-picker/react-demos)
When I select a start date in the calendar (1st January), but in the date field, I see a date that is a day before the selected (31st December). The same when I select the end date - a field displays the day after the selected one.  

<img width="609" alt="Screenshot 2021-01-25 at 16 44 01" src="https://user-images.githubusercontent.com/51960547/105730084-3ce97800-5f2e-11eb-9294-345ba2416c76.png">

What's more, if I select just a start date (1st January), it displays the day before and automatically enters the value to the end date which would be in this case 1st January.

<img width="534" alt="Screenshot 2021-01-25 at 16 58 50" src="https://user-images.githubusercontent.com/51960547/105730529-c26d2800-5f2e-11eb-8b37-8a9ff47d2ab4.png">

When the value is entered directly as input the end date copies the start date.

<img width="501" alt="Screenshot 2021-01-25 at 17 08 38" src="https://user-images.githubusercontent.com/51960547/105731735-ff85ea00-5f2f-11eb-868e-f36c4015d336.png">

This interaction is frustrating and the field should display whatever I as a user select in the calendar.

I tried that on my Mac (Catalina, Chrome/Firefox) and also on Think Pad (Fedora/Chrome). 
@mcarrano wasn't able to reproduce this interaction so I don't know where the problem is.

**Comment by redallen** [comment]
> When I select a start date in the calendar (1st January), but in the date field, I see a date that is a day before the selected (31st December).

This looks like the underlying issue. Can you give steps to reproduce this?
