### ISSUE TITLE
[feat request] Gallery should add "maxCol" and "minCol"

### ISSUE THREAD

**Issue by kunyan** [patternfly/patternfly-react#5400]
**Describe the issue. What is the expected and unexpected behavior?**

The current gallery layout is not able(or very difficult) to custom columns.
In some wide screen, we might only want to 3 or 4 columns, but the default columns are 6-7. it makes every item only show limit width.

I suggest add `maxCol` and `minCol` props to `Gallery`. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**

**Comment by kunyan** [comment]
There has a workaround could implement similar behavior

```
.pf-l-gallery {
  --pf-l-gallery--GridTemplateColumns--min: 350px !important;
}
```

**Comment by tlabaj** [comment]
cc @mcoker @mcarrano

**Comment by mcoker** [comment]
Hi @kunyan we have an open issue to implement the CSS var you referenced, as well as a max width var - https://github.com/patternfly/patternfly-react/issues/5055. I imagine that will be implemented as min/max props on the `<Gallery>` component that set the CSS vars inline. Those vars also support being defined at specific breakpoints, and are documented here - https://www.patternfly.org/v4/layouts/gallery/html#documentation

Until support for defining the min/max vars via props on the react component is implemented, you can always set the variables in your own CSS for a particular gallery layout.  Let me know if you need any help with that.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly-react/pull/5735, implemented as `minWidths` and `maxWidths` on `<Gallery>`
