### ISSUE TITLE
Drawer: resizable css cleanup & transition property conflict

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#5412]
The current `transition` property being set on the panel is conflicting with other transitions. The property needs to be removed on `mouseup` and also can be set to `none` instead of the current curve (it seems that the other transitions were slowing the drag op rather than the op needing a transition). 

After talking with @mcoker, we should move the `transition` property to a class that will be added/removed instead of setting it on the style object. The local CSS stylesheet added the classes for the pointer-events will also be moved to core. So this issue should be updating the transition & local css references to the upcoming core classes.

**Comment by tlabaj** [comment]
closed by #5426
