### ISSUE TITLE
Enhancement: Code editor as a controlled component

### ISSUE THREAD

**Issue by keithjgrant** [patternfly/patternfly-react#5421]
I've been evaluating the beta Code Editor component for use in Ansible Tower, but it's lacking a feature we would need in order to use it. Ideally the component would be a controlled component, meaning that if the `code` prop changes, the component would update with the new code displayed.

In our use case, we need this specifically because we have some inputs that can be toggled between JSON and YAML code. When the user toggles the view, we translate the code between the two and update the prop. In the current version of the code editor, this updated prop is ignored.

Related issue in AWX project: https://github.com/ansible/awx/issues/8905

**Comment by tlabaj** [comment]
cc @nicolethoen
