### ISSUE TITLE
Cannot find module: '@patternfly/react-styles/css/components/Touchspin/touchspin'.

### ISSUE THREAD

**Issue by dev-hikun** [patternfly/patternfly-react#5424]
**Describe the issue. What is the expected and unexpected behavior?**

I use
```
		"@patternfly/patternfly": "4.65.6",
		"@patternfly/react-core": "4.79.2"
```
But when I try to build(npx react-scripts build), I get an error saying that the module could not be found that "@patternfly/react-styles/css/components/Touchspin/touchspin."
I deleted the node_modules folder and tried reinstalling and building several times, but the symptoms are the same.
I wonder if the module doesn't exist. Can you check if the module exists?
If it exists, I am also curious to see if the distribution was successful.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Maybe it is bug

**What is your product and what release version are you targeting?**

**Comment by redallen** [comment]
We renamed TouchSpin to NumberInput in `"@patternfly/react-core": "4.79.2"`.

**Comment by dev-hikun** [comment]
> We renamed TouchSpin to NumberInput in `"@patternfly/react-core": "4.79.2"`.

thank you
