### ISSUE TITLE
Dual List Selector: enhancement to allow more user control over the dual list selector

### ISSUE THREAD

**Issue by jkozol** [patternfly/patternfly-react#5436]
I have been trying to use the [dual list selector component](https://www.patternfly.org/v4/components/dual-list-selector/#using-more-complex-options-with-actions) but am unable to get it to work with nested react components. Looking over the documentation I see the option to pass `React.ReactNode[]` for the available and chosen options. The example uses a list of spans. I would like to be able to pass in a more complex react component such as a list of:

```
<TextContent>
    <Text>"Name"</Text>
    <Text>"Description"</Text>
</TextContent>
```
I would like to have more control over the onListChange and onOptionSelect functions. Currently, I am able to pass in my desired list of elements but if I click on anything the component breaks.

This is a request for enhancement.

My product is Image Builder.

Thank you for any assistance you can offer.

**Comment by katierik** [comment]
This is a request from Red Hat Insights - I added it to the tracker for Mgmt apps @mcarrano

**Comment by mcarrano** [comment]
Sounds good @katierik . Note that there is already a PR up for this that you can see here: https://github.com/patternfly/patternfly-react/pull/5448

**Comment by jkozol** [comment]
I am going to add to this issue but would be happy to open another if anyone sees fit.

I would like more control over the search bars. Specifically I would like the ability to handle onChange for the left and right toolbars independently of each other. Our use case in Image Builder is to use the left search bar to query our api for packages that get displayed in the available list and then to use the right search bar to filter the list of selected items.
