### ISSUE TITLE
Add breadcrumbs switcher support

### ISSUE THREAD

**Issue by ohadlevy** [patternfly/patternfly-react#545]
add the missing functionality of breadcrums switcher (see [design](https://www.patternfly.org/pattern-library/navigation/breadcrumbs/#design))
there is an existing implementation [here](https://theforeman.github.io/foreman/?knob-is%20switcher%20open=true&knob-total%20pages=3&knob-current%20page=2&selectedKind=Components%2FBreadcrumbBar&selectedStory=With%20open%20switcher&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) from Foreman,

**Comment by ohadlevy** [comment]
and the actual code is at https://github.com/theforeman/foreman/tree/develop/webpack/assets/javascripts/react_app/components/BreadcrumbBar

**Comment by jeff-phillips-18** [comment]
@ohadlevy There is a breadcrumb component already: [Breadcrumb Storybook](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=patternfly-react%2FNavigation%2FBreadcrumb&selectedStory=Breadcrumb&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) 

Does that provide what you need?

**Comment by ohadlevy** [comment]
@jeff-phillips-18 no - note the **switcher** functionality in the attached storybook above.
