### ISSUE TITLE
[BUG] Search Input: component styling problem on user input

### ISSUE THREAD

**Issue by richiepiya** [patternfly/patternfly-react#5452]
**Current behavior:** when there is user input, the `Search Input` component's controls ("x" close btn, result count pill, nav options) are pushed below the search bar

https://www.patternfly.org/v4/components/search-input/

<img width="875" alt="Screen Shot 2021-02-11 at 10 35 44 AM" src="https://user-images.githubusercontent.com/39634227/107659210-e9c53400-6c54-11eb-9013-173e33c25a9a.png">

**Expected behavior:** when there is user input, the controls should appear in the right side of the search bar
<img width="940" alt="Screen Shot 2021-02-11 at 10 34 41 AM" src="https://user-images.githubusercontent.com/39634227/107659069-c4382a80-6c54-11eb-91f6-da068edfaf76.png">

**Comment by richiepiya** [comment]
I'm not able to add the “bug” label. Is this the correct process for submitting issues? Thank you

**Comment by mcoker** [comment]
Hi @richiepiya, thanks for the issue. This bug should be resolved via https://github.com/patternfly/patternfly-react/pull/5425 and available in our upcoming release scheduled for next week.

**Comment by tlabaj** [comment]
closed by #5425
