### ISSUE TITLE
Draggable Datalist doesn't work in Firefox or Safari

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#5455]
**Describe the issue. What is the expected and unexpected behavior?**
The [draggable datalist example](https://www.patternfly.org/v4/components/data-list/#draggable) does not seem to work in Firefox or Safari. It does seem to work in Chrome though. On Firefox I can drag the row, it creates the ghost row, but when I release the mouse it goes back to it's starting position. I'm not sure if this is an implementation/example, component, or browser issue (or a combination), but we should probably investigate it. It also shows up in the React Table column management with draggable demo, but it followed the pf draggable example as well. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Open the [example](https://www.patternfly.org/v4/components/data-list/#draggable) on Firefox or Chrome and attempt to rearrange the datalist. 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**Comment by kmcfaul** [comment]
There is an issue with Firefox, combined with how the dragged items are being reordered. When the DOM is reordered/moved/deleted, the `dragEnd` event never fires in Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=460801 

I think that's what is causing the issue in FF at least.

**Comment by redallen** [comment]
The issue was `onDragEnd` returning 0,0 as the cursor location in Firefox. The solution was to use the [`onDrop` event](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#drag_events) which correctly returns the cursor location in both browsers.
