### ISSUE TITLE
Newest react-core is not installable

### ISSUE THREAD

**Issue by marusak** [patternfly/patternfly-react#5458]
**Describe the issue. What is the expected and unexpected behavior?**

`npm install @patternfly/react-core` fails because [in this commit](https://github.com/patternfly/patternfly-react/commit/07993d7f4f2ebd51ddbd1bed08f4f6126ac8ae5e) its dependancy on `react-icons` was bumped to `4.8.7` but this package version was never released as seen in [npm](https://www.npmjs.com/package/@patternfly/react-icons)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
```
 $ npm install @patternfly/react-core
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @patternfly/react-icons@^4.8.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@patternfly/react-core'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mmarusak/.npm/_logs/2021-02-12T09_54_32_018Z-debug.log
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

It is a bug and in Cockpit team we cannot upgrade to the newest version. Not the end of the world, but would be nice to fix it up.

**Comment by tlabaj** [comment]
`react-icons`  `4.8.7` and `react-tokens` `4.9.29` have now been published.
