### ISSUE TITLE
A11y support for react tables

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#546]
Add support for a11y to react tables for PF4.  Support should contain the same functionality as the HTML counterpart.  A demo of the HTML version can be seen in the following pull request:

https://github.com/mattnolting/patternfly-next/pull/14

We should verify that reactabular can be used with a11y as part of this issue. this is related to #402

**Comment by dlabaj** [comment]
PR https://github.com/patternfly/patternfly-react/pull/821

**Comment by rachael-phillips** [comment]
Complete
