### ISSUE TITLE
Slider - use standard input element

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#5464]
I found several issues with the [Slider](https://www.patternfly.org/v4/components/slider) component.

1. Use standard `type="range"` input variant

Why a custom div is used when sliders are supported by default in HTML? The component should also support the same API as the input element (`step`, `max`, `min`, `value`).

2. `isDiscrete={false}` variant does not trigger change events when used together with `steps`

You can see it in the first example - if you remove the `isDiscrete` prop, then the value is never changed.

3. `onChange` and `value` should serve as the main props to be consistent with all other form elements

There should be no `currentValue` vs `inputValue`, `onChange` vs `onValueChange`. It's not clear at all.

cc @Hyperkid123

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by mcoker** [comment]
> Use standard type="range" input variant

@rvsia just want to make sure I understand - are you suggesting using/styling a native `<input type="range">` as the slider component, or including a hidden element in the react component that updates with the user selection, or maybe something else?

**Comment by rvsia** [comment]
@mcarrano I think it would be awesome to just reskin range input element, but I understand that the styling (and the functionality) is complex and it can be hard or even impossible to customize it. Hidden input would be nice for testing purposes, maybe even more accessible? However, at least we should keep the same API as for standard inputs element, because I believe that consumers will automatically suppose that it’s a range input element.

So it’s really up to you. Restyling requires the biggest effort, but it would be the best solution. Change the api + hidden input element is also something I can live with.

**Comment by mcoker** [comment]
> I think it would be awesome to just reskin range input element, but I understand that the styling (and the functionality) is complex and it can be hard or even impossible to customize it.

@rvsia I couldn't agree more, but as you mentioned a cross-browser solution that meets the design and functionality requirements would likely be impossible using the native HTML element.

**Comment by Hyperkid123** [comment]
@mcoker can we just hide the input and use its API for the component and the event control? And then just re-use the custom DOM tree for the styling.

**Comment by mcoker** [comment]
@Hyperkid123 I'll defer to @tlabaj for that part of the implementation.

**Comment by tlabaj** [comment]
We can certainly change the API for the slider to match the rang input.

**Comment by mcarrano** [comment]
Thanks @mcoker @tlabaj . Based on that, I will get this on the roadmap for our next sprint with the assumption that we will update the API, but continue with our custom approach for the HTML component.
