### ISSUE TITLE
feat(Alert): Toast component should enforce that all its children have a isLiveRegion property set

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5477]
Docs say: 
isLiveRegion | boolean | No | false | Flag to indicate if the Alert is in a live region

Really for me this means not much :) And it's not required, one can easily miss it. Resulting in a component which is not ideal for assistive technologies.
 
So let's ensure that Toast is having children with `aria-polite=true`

Also related to https://github.com/patternfly/patternfly-react/issues/5397

**Comment by tlabaj** [comment]
cc @jessiehuff

**Comment by nicolethoen** [comment]
Hi @KKoukiou 
Im digging up this issue to see if it's been addressed.
I think with some updates surrounding the documentation and examples of `Alert` and `AlertGroup`, we've made it clearer how to use `aria-live` with toast alert groups.

https://www.patternfly.org/v4/components/alert-group#toast-alert-group

There is also a new `Accessibility` tab at the [top of the AlertGroup docs](https://www.patternfly.org/v4/components/alert-group/accessibility) which explains things even further.
