### ISSUE TITLE
Page Layout 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#548]
Introduce PF4 page layout: https://pf-next.com/demos/PageLayout/examples/

In addition to a React review, this issue should be reviewed by the core contributors of this demo: 
* CSS: @andresgalante

**Comment by jschuler** [comment]
@andresgalante Hi Andres, the layout is viewable here:
https://714-pr-patternfly-react-patternfly.surge.sh/patternfly-4/layouts/page
