### ISSUE TITLE
Popover unexpectedly closes from child component actions

### ISSUE THREAD

**Issue by darrenrevans10** [patternfly/patternfly-react#5480]
**Describe the issue. What is the expected and unexpected behavior?**
We are currently using a third party multi-select dropdown (React-Select) within the Popover. Whenever a user goes to select a menu item from the dropdown, as well as delete a "chip" item, the Popover is closing. 

I've tested this with both the "controlled" version where the callback shouldClose is being called from this action as well as the uncontrolled version. Both produce the same result where the Popover is closing unexpectedly.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This seems to be a bug that any event within a popover should not close the Popover (unless manually wanting to do so). We do have a current work around using "shouldClose" 3rd argument (Mouse event) that checks to see if the targeted ID came from our Select component.

**What is your product and what release version are you targeting?**
Current version being used is 4.84.4

**Comment by redallen** [comment]
Our Popover contains [a check to see if you've clicked inside the Popover:](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Popover/Popover.tsx#L277)
```ts
const isChild = popperElement && popperElement.contains(event.target as Node);
```
where `popperElement` is the outermost element in [Popper's `React.createPortal`](https://github.com/patternfly/patternfly-react/blob/d4f0f2624bf3c77a43ae7ec0f0197a72b408f1e0/packages/react-core/src/helpers/Popper/Popper.tsx#L294).

I think this should catch anything you put in a Popover that doesn't create another portal. If you [create a codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f?file=/index.js) we can further debug.
