### ISSUE TITLE
Login page background flickering when typing

### ISSUE THREAD

**Issue by mohd-akram** [patternfly/patternfly-react#5488]
**Describe the issue. What is the expected and unexpected behavior?**
The background of the login page flickers while typing credentials.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://zfn8z.csb.app/ (open in Chrome)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. No known work-around.

**Comment by tlabaj** [comment]
Hi @mohd-akram a couple of us tried this and we are unable to reproduce the issue.  Is there any other information you can provide to help us reproduce this?

**Comment by mohd-akram** [comment]
It seems to more readily reproduce if the developer console is open while typing in the form. AFAICT the issue is in https://github.com/patternfly/patternfly-react/blob/acae00b469a09c70aeffef0b6b6051bc14b22139/packages/react-core/src/components/BackgroundImage/BackgroundImage.tsx#L58. The incrementing counter is a global variable which causes the background to re-render every time.

**Comment by tlabaj** [comment]
Thank you.  We were able to reproduce it.
