### ISSUE TITLE
do not hide toast alert when mouse is over

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#5489]
**Describe the issue. What is the expected and unexpected behavior?**
Alerts used as a toast notification can have a timeout which will hide the toast after the timeout expires. This request is to halt the timeout while the user's mouse is over the toast. If the user is trying to read the message or copy something from the toast, it shouldn't disappear out from under their mouse.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

**What is your product and what release version are you targeting?**
OpenShift Console 4.8

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
I agree with @christianvogt that this is pretty standard behavior for toast alerts. Is this something that we can easily add @tlabaj ?

**Comment by redallen** [comment]
@christianvogt Patternfly doesn't hide alerts or have examples that hide alerts after a timeout. What exactly do you want changed in `Alert` or `AlertGroup`?

**Comment by redallen** [comment]
@christianvogt Disregard, I missed that we have a `timeout` prop...
