### ISSUE TITLE
Type-Ahead Select: Add option to retain keyboard-entered value in text field when tabbing away

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5502]
Add a prop to retain the value entered by a user from the keyboard if the user tabs out of the field without explicitly selecting the new value. Currently the field value is not retained when tabbing away which is a potential usability issue when including type-ahead select components in the context of a form.

See the related design discussion here: https://github.com/patternfly/patternfly-design/issues/1003

**Comment by Swabisan** [comment]
Hi there, developer consuming patternfly-react here,

It seems that this is already the current behavior of Select, https://www.patternfly.org/v4/components/select

whereas an older version doesn't retain the value, https://www.patternfly.org/2020.04/documentation/react/components/select

In https://github.com/patternfly/patternfly-design/issues/1003 there's a discussion on how to retain the typeahead value on tab, in my application I need to **clear the typeahead on tab**, where it doesn't seem to be possible with the latest version. 

I was about to open an issue for this but I found the thread mentioned above, would appreciate some clarification on this.

**Comment by mcarrano** [comment]
@tlabaj can you help clarify?

**Comment by KKoukiou** [comment]
@Swabisan your use case it that you always want to clear on tab? We also consume this component in cockpit, and I except that the behavior is as follows:

* When tab is hit and the input value is already matching one of the options, this should retained
* When tab is hit and the input value does not match any of the options, this should be ignored.
* When tab is hit the input value is prefix of one of the options, I think it should get autocompleted and retained. 

  In any case, it seems that different teams have different expectations here, so let's make it as configurable as possible.
