### ISSUE TITLE
PF4 core refactored variables to remove property name from state variables

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#551]
<needs info>

Update react as appropriate since this merged on core: https://github.com/patternfly/patternfly-next/pull/540

**Comment by tlabaj** [comment]
@LHinson I took a look at react-core.  None of the global variables that have changed are being used so no code changes are needed for this PR.

**Comment by LHinson** [comment]
Great, thanks for confirming. Closing!
