### ISSUE TITLE
Selecting a month in DatePicker's popover closes the popover when using react-dom ^17

### ISSUE THREAD

**Issue by wsamsnyder** [patternfly/patternfly-react#5515]
**Describe the issue. What is the expected and unexpected behavior?**
When a month is selected from the Date picker's popover month dropdown, the popover will close. When using react-dom v16.14, the popover remains open after month selection.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Here is a sandbox that uses `@patternfly/react-core v4.97.2`, `react v17.0.0`, and `react-dom v17.0.0`. The same effect can be seen with `react-dom v17.0.1`.
https://codesandbox.io/s/loving-pond-9vsb3

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. Date picker is still in beta and months can still be selected via the arrows, so while it is blocking, I am aware it is "use at your own risk" component. One work-around would be to roll back `react-dom`, unfortunately, this is not possible in my application.

**Comment by redallen** [comment]
Looks like with React 17 the Dropdown's `onClick` event is firing before the DatePicker's Popper's `onDocumentClick`.

I'll have a fix up soon.
