### ISSUE TITLE
Dynamic Menu drilldown

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#5534]
Regarding the new Menu with drilldown example. Can all those menu items be created dynamically; for example, as the user traverses an org hierarchy?

My concern is having to create all the components upfront with such a large hierarchy. It looks like the `drilldownMenu` prop of `MenuItem` doesn't accept a function?

@tlabaj suggested "we could modify the prop to accept a function"

**Comment by tlabaj** [comment]
@mcarrano Can we prioritize this one.
