### ISSUE TITLE
Pagination: make fully translatable for internationalization

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5560]
The word "of," as in "2 of 4 pages" is not currently exposed in strings for translation. This is needed to deliver internationalized versions of Ansible Tower on PatternFly.

cc @nicolethoen

**Comment by redallen** [comment]
Currently a user can pass a custom `ToggleTemplate` to format the "2 of 4 pages" however they want using the [toggleTemplate](https://www.patternfly.org/v4/components/pagination/#pagination) prop of `Pagination`.

We could add an `ofWord` prop to `Pagination`, is that what you're asking for?

**Comment by mcarrano** [comment]
@redallen I'm not sure that we need a prop. Can you take a look at the comment thread here and feel free to add a comment or question? https://docs.google.com/document/d/1-rQa8RIokhcFcdI9ExmQVGZdIAxU2aeQkMN0C3VhboA/edit?usp=sharing
