### ISSUE TITLE
TimePicker: no way to know if they provided time is valid

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5564]
When using the component in forms, we need to block submission of the form if the TimePicker input is invalid. We currently do that by disabling the component's validation, by setting invalidFormatErrorMessage='' and doing the validation on our side on submit.  Ideally we would like to let the component do the validation, but have a way to know if the inserted time is valid.

I suggest that we add another parameter to the onChange, related to the validity.

**Comment by redallen** [comment]
We could adopt a similar approach to DatePicker.
```ts
/** Functions that returns an error message if a date is invalid */
validators?: ((date: Date) => string)[];
```

**Comment by redallen** [comment]
@KKoukiou In DatePicker those validators are in addition to the component's validation. The way DatePicker gives feedback is the 2nd parameter in the onChange event:
```ts
/** Callback called every time the input value changes */
onChange?: (value: string, date?: Date) => void;
```

We could just do the same thing with TimePicker.

**Comment by KKoukiou** [comment]
@redallen so let's make the second argument in the onChange can be used for validation in the TimePicker as well. (I just did not see how the extra validators are related)

Thanks for the pointer!

**Comment by redallen** [comment]
We should standardize the APIs while in beta and before we make a `DateTimePicker`.

**Comment by tlabaj** [comment]
@mcarrano can you add this one to a milestone please.

**Comment by thatblindgeye** [comment]
It looks like I've picked up another TimePicker issue from you, @KKoukiou! 

I just wanted to confirm since it's been so long, was the current iteration of the TimePicker still in need of any changes for this issue you had submitted last year?

**Comment by KKoukiou** [comment]
@thatblindgeye from what I see in the current implementation is that, there is an isValid property in the callback, so this issue can already be closed.

**Comment by tlabaj** [comment]
Thanks Eric and Katerina for taking a look.
