### ISSUE TITLE
Expandable card - support expandable toggle on the right

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#5583]
On an expandable card, adding `.pf-m-toggle-right` to `.pf-c-card__header` will align the toggle to the right side of the header.

This was added as part of new card demos https://github.com/patternfly/patternfly/pull/3848/files

cc @mcarrano

**Comment by nicolethoen** [comment]
Hi @KKoukiou! Just want to double check that you still have this on your radar? We've added it to the current milestone and code freeze will be on May 5th. Let me know if you'd like to hand if off. That'd be fine, too!

**Comment by KKoukiou** [comment]
Ups doh, no actually I think I self assigned it by mistake. It looks like quick fix, but I will leave it to someone from the PF4 team. Sorry for the confusion @nicolethoen  :)
