### ISSUE TITLE
Move Card View demo from Card to a new page within Demos

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5599]
Want to move the Card View demo from the Card component page to a new page that lives in the Demos section. This will group them better with other similar demos (like primary-detail) and reserve Card demos for examples of specific card types. New page should have ID: Card view and section: demos.

**Comment by kmcfaul** [comment]
Ignore the closed PR, I made a mistake while pushing it and included some unrelated commits.
