### ISSUE TITLE
Component - Vertical Navigation

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#56]
Implement a component that provides the following UI element:

* [PatternFly Vertical Navigation](http://www.patternfly.org/pattern-library/navigation/vertical-navigation/)

And with initial support for the following features:
* mobile support
* burger bar toggles menu text labels
* secondary nav

Support for ability to pin navigation and display tertiary navigation could be added later.

The navbar-header component that currently exists for the horizontal navigation component should also be updated as needed to be reused for the vertical navigation component.

https://patternfly.atlassian.net/browse/OSUX-292

**Comment by mturley** [comment]
After discussing it with Serena, it looks like I'll be taking this on as my first contribution!

**Comment by ohadlevy** [comment]
@mturley looking forward to it

**Comment by mturley** [comment]
I don't have membership in https://github.com/orgs/patternfly/people yet, does anyone mind assigning me to this issue?  Or adding me to the org if you have permissions. Not sure what the official process is for that, if any. I verified my redhat email on github.

**Comment by priley86** [comment]
i've added you as a maintainer just now @mturley !

**Comment by mturley** [comment]
Thanks!  Getting started on this, hopefully I'll have a PR up tonight or tomorrow sometime.

**Comment by jgiardino** [comment]
Work for this component is included in PR #88
