### ISSUE TITLE
CardBody: provide hasNoPadding property to remove body padding

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5606]
In Cockpit we use everywhere card, but when these contain list we decided that it's too much wasted space to have the padding in the card body. So we remove it. It looks like this:

![Screen Shot 2021-03-31 at 10 43 13](https://user-images.githubusercontent.com/14921356/113116632-ea6a5780-920d-11eb-8275-f910344b9cfa.png)

Would you be interested to expose a property to do that properly?

**Comment by mcoker** [comment]
@KKoukiou you can omit `<CardBody>` to use a card without padding - would that work?

```
  <Card>
    This card has no padding
  </Card>
```
