### ISSUE TITLE
Page Section in Main is missing Main wrapper in PF React

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#5609]
**Describe the issue. What is the expected and unexpected behavior?**

I have ran into this issue a few times. When I used the PF Drawer with the Page Section inside, it seems like the PF React implementation is missing the class `<main class="pf-c-page__main">` which wraps the Page Sections. This causes the page section to not grow to the full height of the Drawer Body. When I added the class pf-c-page__main it fixed the problem.

I might just be implementing this incorrectly, so please correct me if im wrong :) 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug

**What is your product and what release version are you targeting?**

**Comment by KKoukiou** [comment]
@christiemolloy I wanted to take a look to fix this but I can't reproduce. 
I checked the PF4 docs page, https://www.patternfly.org/v4/components/page in the dom inspector I can see ```<main class="pf-c-page__main">```

Also in the code the class seems to be always added. Can you specify the exact reproducer? Is it some specific example that you talk about?
