### ISSUE TITLE
Chart tooltip appears not on the mousepoint

### ISSUE THREAD

**Issue by Fewwy** [patternfly/patternfly-react#5612]
**Describe the issue. What is the expected and unexpected behavior?**
Current Behavior:
When I hover over the chart the tooltip appears at the right border. 
Expected Behavior:
When I hover over the chart the tooltip appears at the mousepoint.
![image](https://user-images.githubusercontent.com/62722417/113289383-6fc63880-92f0-11eb-8c7e-dfdca4a83156.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
You can import any chart and render it, documentation have the same issue as well.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**
patternfly-react

**Comment by tlabaj** [comment]
cc @dlabrecq

**Comment by dlabrecq** [comment]
This is not a bug. The pointers of Victory tooltips are located top center of a bar by default. 
See https://formidable.com/open-source/victory/docs/victory-tooltip

The chart could be a stack chart, but looks custom? However, you can change the tooltip behavior. The bullet chart; for example, customizes the dx and dy props of ChartTooltip to position the pointer differently.

If you want the tooltip pointer to follow the cursor, you'll need to wrap your chart with a VoronoiContainer. This snapshot below shows what that could look like.

![chrome-capture](https://user-images.githubusercontent.com/17481322/113631038-d7ed8500-9636-11eb-974a-3be098660688.gif)

**Comment by Fewwy** [comment]
> This is not a bug. The pointers of Victory tooltips snap to the top center of a `VictoryBar` by default.
> See https://formidable.com/open-source/victory/docs/victory-tooltip
> 
> The chart above could be a stack chart, but looks custom? Regardless, you can change the tooltip behavior. The bullet chart; for example, customizes the `dx` and `dy` props of `ChartTooltip` to position the pointer differently.
> 
> If you want the tooltip pointer to follow the cursor, you'll need to wrap your chart with a Voronoi container. This snapshot below shows what that could look like.
> 
> ![chrome-capture](https://user-images.githubusercontent.com/17481322/113631038-d7ed8500-9636-11eb-974a-3be098660688.gif)
> 
> There are PatternFly Voronoi container examples here:
> http://patternfly-react.surge.sh/charts/tooltip-chart#combined-cursor-and-voronoi-containers
> 
> And more Victory examples here:
> https://formidable.com/open-source/victory/docs/victory-voronoi-container

Ok, I will try to follow your examples and will get back to you.
