### ISSUE TITLE
Tooltip position changes when content updates and missing onShow/onHide events

### ISSUE THREAD

**Issue by sahil143** [patternfly/patternfly-react#5620]
**Describe the issue. What is the expected and unexpected behavior?**

1. [Bug] If content changes while the tooltip is open, its position shift from the target
2. [Enhancement] Tooltip component is missing the onShow/OnHide events which are fired when the tooltip opens/closed

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

![defect-ctc](https://user-images.githubusercontent.com/9278015/113584419-7f26e800-9648-11eb-995e-67a9a012d00f.gif)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Both

**What is your product and what release version are you targeting?**
DevConsole[release 4.8]

**Comment by christianvogt** [comment]
AFAIK there is no work around as Sahil created his own component.

**Comment by christianvogt** [comment]
bump

**Comment by tlabaj** [comment]
@mcarrano can we add this one to a milestone please.
