### ISSUE TITLE
Incorrect type for `onFilter` prop of Select component - can break an app when Select children are updated

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#5625]
**Describe the issue. What is the expected and unexpected behavior?**

The TypeScript type of Select's `onFilter` prop is `(e: React.ChangeEvent<HTMLInputElement>) => React.ReactElement[]`, implying that the event passed to it will always be defined/truthy. It appears that after https://github.com/patternfly/patternfly-react/pull/5375, `onFilter` gets called with a `null` value for its event argument when the component's children change. See https://github.com/patternfly/patternfly-react/blame/fe2da75b77e4cbf92ef11b71e87aef998fa8dd46/packages/react-core/src/components/Select/Select.tsx#L209

When I upgraded PF, this caused an error in my code which passes a handler to `onFilter` expecting the event to always be defined and non-null. The example in our docs doesn't hit it because it has a try-catch block when it references the event.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

See this CodeSandbox: https://codesandbox.io/s/laughing-forest-o01j4?file=/index.js
It is based on the one from [the Custom Filtering example](https://www.patternfly.org/v4/components/select#custom-filtering) in the docs, with the try-catch in `onFilter` removed and a new state property introduced that forces the children to change after the component mounts.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

This is a bug. The workaround is to use a try-catch or otherwise defensively code around the possibility of the event being null, but TypeScript could catch this for consumers if the `onFilter` prop type was changed to `(e: React.ChangeEvent<HTMLInputElement> | null) => React.ReactElement[]`.

**What is your product and what release version are you targeting?**

Migration Toolkit for Virtualization. No particular target release.

**Comment by mturley** [comment]
cc @KKoukiou

**Comment by mturley** [comment]
It actually appears that the new behavior of passing `null` as the event to `onFilter` breaks my custom filtering entirely when the children change, even when I work around the type error. The `onFilter` behavior relies on `event.target.value` being available to do its filtering, so when I update my children (new options become available due to polling) my filter results get reset.

To fix this I think we may need to modify `onFilter` so it can take a string (the `typeaheadInputValue`) instead of an event.

**Comment by KKoukiou** [comment]
@mturley right, sorry for breaking it in the first place. I think this will work for you. https://github.com/patternfly/patternfly-react/pull/5631

However, since I edit the arguments of `onFilter` I expect this to be a breaking change, let's see what the PF-react maintainers say.

**Comment by mturley** [comment]
No problem at all! Thanks for opening the fix!

I wonder if it would be worth swapping the arguments so it's not a breaking change (the event is still the first arg)? I know that would be different from `onChange` which may be weird.

**Comment by KKoukiou** [comment]
@mturley I thought about swapping the arguments as well. To be honest i don't know when is the next breaking change release. So let's ask @redallen about this. If it's soon let's leave it like this, otherwise I will swap.

**Comment by redallen** [comment]
I think the earliest we might have a breaking change release is post-summit 2022.

**Comment by mturley** [comment]
Maybe we could do the non-breaking change (swap the args) and then later on, swap them back as a breaking change to make it consistent with `onChange`?

**Comment by KKoukiou** [comment]
> Maybe we could do the non-breaking change (swap the args) and then later on, swap them back as a breaking change to make it consistent with `onChange`?

Sure, let's do that.
