### ISSUE TITLE
Table: add multi-column ordering

### ISSUE THREAD

**Issue by Josca** [patternfly/patternfly-react#5633]
Allow to sort by multiple columns with defined priorities.
Described e.g. [here](https://datatables.net/examples/basic_init/multi_col_sort.html)

It can be useful when displaying data from some sql query like `... ORDER BY column1, column2, column3`

**Comment by tlestach** [comment]
I guess the request is to have an standardized way to visualize when tables are sorted according to multiple columns (with what order).

**Comment by terezanovotna** [comment]
The use case is coming from Insights Patch - pretty sure @Josca can share more about the use case.

**Comment by Josca** [comment]
Sure, namely we want visual form for this url: https://cloud.redhat.com/insights/patch/advisories?offset=0&sort=-advisory_type&sort=-applicable_systems&sort=-public_date, See, there are already multiple "sort" query params support. However it's not reflected in any way visually. Also you can not reach that url using UI components - typically by clicking on column headers one by one.

**Comment by tlabaj** [comment]
cc @mcarrano  @jschuler

**Comment by mcarrano** [comment]
@jschuler is this something our React table supports? Is it just a matter of designing a visual affordance to indicate secondary sort parameters?
