### ISSUE TITLE
'helperTextInvalidIcon' prop of 'FormGroup' component position is fixed to left

### ISSUE THREAD

**Issue by avivtur** [patternfly/patternfly-react#5653]
Trying to work with 'FormGroup' component, it has a prop named 'helperTextInvalidIcon' and it has fixed position to be on the left of 'helperTextInvalid' prop. IMO there should be a boolean variable that controls the position and fix the position to be on the right of the text, or a similar solution.

I saw the source code here:
https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Form/FormGroup.tsx

and had something like this in my mind, 
Add to 'FormGroupProps' interface in lines 7-40 the following:
/** Icon displayed to the right of the helper text when the field is invalid.*/
  isHelperTextInvalidIconAfter?: boolean;

Add to 'FormGroupProps' in lines 44-61 the following:
isHelperTextInvalidIconAfter = false,

Change code in lines 82-83 to something like:
{(helperTextInvalidIcon && !isHelperTextInvalidIconAfter )&& <span className={css(styles.formHelperTextIcon)}>{helperTextInvalidIcon}</span>}
        {helperTextInvalid}
        {(helperTextInvalidIcon && isHelperTextInvalidIconAfter )&& <span className={css(styles.formHelperTextIcon)}>{helperTextInvalidIcon}</span>}

Steps to reproduce:
Use 'FormGroup' component and have no prop to adjust 'helperTextInvalidIcon' position.

this is an enhancement to improve 'FormGroup' component to be more adjustable.
I guess something similar can also be achieved 'helperText' and 'helperTextIcon' props
I had a workaround to make it work, which goes like this:

helperTextInvalid={[message, icon]} 

I get the correct position, but message is not getting color from 'validated' prop with 'error' value

**Comment by redallen** [comment]
Your suggested change sounds wonderful @avivtur ! I welcome you to submit a PR with it since it may be a while until our team can.

**Comment by tlabaj** [comment]
cc @mcarrano is the design intention the helper text Icon is always to the left of the text?

**Comment by mcarrano** [comment]
Just to make sure I am clear, are we talking about this icon?

![Screen Shot 2021-04-12 at 4 39 32 PM](https://user-images.githubusercontent.com/6619860/114458844-bef05100-9bad-11eb-97c9-d3cc00cbd3a3.png)

By design, the icon is intentionally placed before the message to ensure consistent usage. Is there a reason you want to move this icon to the right (after the message0 @avivtur ?

**Comment by avivtur** [comment]
Hi all, 
thanks for your fast reply :) 
@mcarrano First of all, you are right this is the icon I'm referring to.
Secondly Yes I do, I wish to create an icon for more info on invalid state, so it is more logical in that specific use-case to make it after the text.
something like this example:
![Screenshot from 2021-04-13 10-46-54](https://user-images.githubusercontent.com/67270715/114516096-bd726780-9c45-11eb-863d-d9b2c46efe29.png)

This was made with a workaround to achieve my goal, and I thought it would be nice to have this option built-in

**Comment by mcarrano** [comment]
Thanks @avivtur . I can see how this would be useful. I still think we should have an error icon preceding the text, but it would be nice to add the help icon at the end as shown. @tlabaj looks like `helperTextInvalid` takes a React node so any reason you couldn't just pass a string followed by an icon?

**Comment by avivtur** [comment]
> @tlabaj looks like `helperTextInvalid` takes a React node so any reason you couldn't just pass a string followed by an icon?

That is indeed possible, however when doing as you suggest, for some reason the text passed is failing to get the proper text color from the 'validated' prop. I guess so at least that could be fixed
