### ISSUE TITLE
Filter tree demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5655]
Create a new React demo that shows how a Tree view can be placed inside of a dropdown to satisfy the use case described here: https://github.com/patternfly/patternfly-design/issues/912  - see comments on desired solution and behavior.

**Comment by tlabaj** [comment]
@mcarrano did you mean the menu and not dropdown?

**Comment by mcarrano** [comment]
@tlabaj I'm not sure. I'll leave it to you and @kmcfaul to decide what the best approach is to realize the design request. Basically we want a tree menu placed in a dropdown. If we can use the composable menu approach for that, I'd be in favor of it.
