### ISSUE TITLE
Error: Can't resolve '@patternfly/react-core/dist/esm/helpers/OUIA/ouia'

### ISSUE THREAD

**Issue by dmatis2** [patternfly/patternfly-react#5660]
**Describe the issue. What is the expected and unexpected behavior?**

It should render `Table` component properly. Instead, I'm getting 

```
ERROR in ./node_modules/@patternfly/react-table/dist/esm/components/Table/RowWrapper.js
Module not found: Error: Can't resolve '@patternfly/react-core/dist/esm/helpers/OUIA/ouia' in '/home/dmatis/alice-ctp/node_modules/@patternfly/react-table/dist/esm/components/Table'
```

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

* `create-react-app`
* `npm i @patternfly/patternfly @patternfly/react-core @patternfly/react-table`
* create component with `Table` from `@patternfly/react-table`
* `npm start`

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

This should be a bug and I don't have a workaround.

**What is your product and what release version are you targeting?**

I'm creating a module for a Cockpit. Version of packages:

- patternfly: `4.87.3`
- patternfly-core: `4.97.2`
- patternfly-table: `4.24.1`

**Comment by tlabaj** [comment]
cc @redallen

**Comment by redallen** [comment]
It looks like your versions of `@patternfly/react-core` and `@patternfly/react-table` are mismatching. You can find version matches [in our release notes](https://www.patternfly.org/v4/developer-resources/release-notes#2021.02-release-notes-2021-02-17) or run `npm ls @patternfly/react-table` after you've installed.

If that doesn't work for you please share a test repo and I'll take a look!
