### ISSUE TITLE
Docs are missing for 'ToolbarGroup'

### ISSUE THREAD

**Issue by ddonahue007** [patternfly/patternfly-react#5664]
**Describe the issue. What is the expected and unexpected behavior?**
When looking at the latest docs online there is no documentation in the patternfly APIs for 'ToolbarGroup'

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Look here and you will see no 'ToolBarGroup'
https://www.patternfly.org/v4/components/toolbar

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**
Patternfly React Docs

**Comment by ddonahue007** [comment]
PR: https://github.com/patternfly/patternfly-react/pull/5665

**Comment by tlabaj** [comment]
closed by #5665
