### ISSUE TITLE
Add prop to Toolbar component for custom filter tag action

### ISSUE THREAD

**Issue by jlmitch5** [patternfly/patternfly-react#5668]
In automation analytics, we will be adding a "Save filter" action to allow users to save the current set of filter tags as a custom filter.  The idea is that this will live as an additional action at the filter tag level:

<img width="1390" alt="Screen Shot 2021-04-14 at 12 34 09 PM" src="https://user-images.githubusercontent.com/1342624/114746515-db130000-9d1d-11eb-84b6-76d5f9f7febe.png">

In order to do so (and after talking with @nicolethoen who had this great idea), I think it would make sense for the Toolbar to have an additional prop which accepts an arbitrary JSX blob that renders next to the tags when they are shown.  In usage I think it would look something like:

```
<Toolbar
  customFilterAction={
    <Button variant="link">Save filter</Button>
  }
/>

**Comment by nicolethoen** [comment]
@jlmitch5 is this still something you'd like? 
If so, we'd probably want to add it to the roadmap @mcarrano

**Comment by mcarrano** [comment]
I like this idea, also, as the need for saving filters has come up before. @nicolethoen would this approach require core work or can this be handled directly as a core update?

**Comment by nicolethoen** [comment]
This could still be addressed - and I don't think it'd require core work.
