### ISSUE TITLE
Form inside modal will cause page refresh when pressing Enter while focused on a form field

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5680]
Here is a live working example: https://codesandbox.io/s/gifted-wood-2962m

So the question is. What is the expected behavior? Obisouly refreshing the page is not.

Should we handle the form submit event and apply the modal?
Should we ignore the form submit event?

Should modals which contain forms with multiple fields behave differently than modals which contain one field?

We will be grateful with some clarification about the expected usage of forms in modals. 

Lastly:
Can patternfly-react do something about it? Like exposing an onSubmit property for the Form component for the users to consume if they need, but prevent the default behavior?
 
Or in the docs page one can use the following code:

``` js

import React from 'react';
import { Modal, Button, Form, FormGroup, TextInput } from '@patternfly/react-core';

class SimpleModal extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isModalOpen: false,
      value: '',
      invalidText: 'Age has to be a number',
      validated: 'default',
      helperText: 'Enter your age to continue'
    };

    this.handleModalToggle = () => {
      this.setState(({ isModalOpen }) => ({
        isModalOpen: !isModalOpen
      }));
    };

    this.simulateNetworkCall = callback => {
      setTimeout(callback, 2000);
    };

    this.handleTextInputChange = value => {
      this.setState(
        { value, validated: 'default', helperText: 'Validating...' },
        this.simulateNetworkCall(() => {
          if (/^\d+$/.test(value)) {
            if (parseInt(value, 10) >= 21) {
              this.setState({ validated: 'success', helperText: 'Enjoy your stay' });
            } else {
              this.setState({ validated: 'warning', helperText: 'You must be at least 21 to continue' });
            }
          } else {
            this.setState({ validated: 'error', invalidText: 'Age has to be a number' });
          }
        })
      );
    };
  }

  render() {
    const { value, validated, helperText, invalidText, isModalOpen } = this.state;

    return (
      <React.Fragment>
        <Button variant="primary" onClick={this.handleModalToggle}>
          Show Modal
        </Button>
        <Modal
          title="Simple modal header"
          isOpen={isModalOpen}
          onClose={this.handleModalToggle}
          actions={[
            <Button key="confirm" variant="primary" onClick={this.handleModalToggle}>
              Confirm
            </Button>,
            <Button key="cancel" variant="link" onClick={this.handleModalToggle}>
              Cancel
            </Button>
          ]}
        >
          <Form>
            <FormGroup
              label="Age"
              type="number"
              helperText={helperText}
              helperTextInvalid={invalidText}
              fieldId="age-3"
              validated={validated}
            >
              <TextInput
                validated={validated}
                value={value}
                id="age-3"
                aria-describedby="age-3-helper"
                onChange={this.handleTextInputChange}
              />
            </FormGroup>
          </Form>
        </Modal>
      </React.Fragment>
    );
  }
}
```

**Comment by mvollmer** [comment]
> Like exposing an onSubmit property for the Form component for the users to consume if they need, but prevent the default behavior?

I think this is available. Patternfly `<Form>` passes on all extra props to the `<form>` element that it will instantiate.

**Comment by KKoukiou** [comment]
> > Like exposing an onSubmit property for the Form component for the users to consume if they need, but prevent the default behavior?
> 
> I think this is available. Patternfly `<Form>` passes on all extra props to the `<form>` element that it will instantiate.

Correct it's passed directly which means we always need to handle it when we use it. But I think it would make sense that they have something like this:

``` js
this.onSubmit(e) {
  if (this.props.onSubmit)
    this.props.onSubmit(e);
  else
    return false;
}
```

So that the default behavior would be to call the user's provides onSubmit but if the user did not pass it just do nothing, to prevent the weird page refreshes.

**Comment by KKoukiou** [comment]
@tlabaj who is most familiar with the Form component to help us with this?

**Comment by redallen** [comment]
Generally in single page applications you don't want the default `<form>` submission behavior. Most of the time you want `onSubmit={ev => { ev.preventDefault(); fetch('/api/v1/...').then(() => closeModal(); });`. I'm in favor of changing `onSubmit`'s default to `ev => ev.preventDefault()`, but unfortunately it's a breaking change.

**Comment by KKoukiou** [comment]
@redallen thanks for you aswer. I will still keep this open, for getting answer in the other question regarding expected functionality, namely:

When using forms inside modals,

* Should we handle the form submit event and apply the modal?
* Should we ignore the form submit event? (preventDefault)

What we currently want do in cockpit is the latter, but for modals with only one textInput we run the primary button handler when the onSubmit is triggered. Is this correct?

**Comment by redallen** [comment]
Our [design guidelines](https://www.patternfly.org/v4/components/form/design-guidelines) don't specify.

It depends on whether or not our designers think pressing enter while in a form field should submit the form (which is the default HTML5 behavior and can be done regardless of whether the button is enabled or disabled) or whether it can only be done by clicking the button. cc @mcarrano

**Comment by mcarrano** [comment]
@KKoukiou @redallen It's true that we probably don't document this anywhere, but my understanding of the convention is that pressing ENTER should trigger the default form action (i.e. the submit button) if the user only needs to enter a single value. I agree this would be unexpected for a form with multiple fields, however. In either case, I think the implementation should be flexible as it may be impossible to know the right thing to do in every context. Does that make sense?

**Comment by KKoukiou** [comment]
@mcarrano Yes thanks a lot for your feedback.
