### ISSUE TITLE
Mobile Issues 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#5682]
Some bugs were recently filed in the Managed Kafka repo, particularly with the Control Plane UI. I have tested these bugs myself in BrowserStack and was able to reproduce some of them and also verify that they were happening in PatternFly: 

**Describe the issue. What is the expected and unexpected behavior?**

1. On most new Android Devices: 
- E.g. Samsung: Galaxy S21
PatternFly Toolbar component with Text Input Filter inside of the Toggle Group Expanded has a bug where you go to type into the filter field and the filter input immediately loses focus and the toggle group closes.

2. On Android devices:
PatternFly Toolbar component inside the toggle group expanded, the filter options and inputs positions are moving up and down depending on the selected filter type. The gap between the input and the applied filters is too big 

<img width="568" alt="Screen Shot 2021-04-15 at 11 51 39 AM" src="https://user-images.githubusercontent.com/20118816/114899815-4a9df380-9de1-11eb-9dc3-4c1e109b27a1.png">
<img width="582" alt="Screen Shot 2021-04-15 at 11 51 48 AM" src="https://user-images.githubusercontent.com/20118816/114899829-4d98e400-9de1-11eb-8c72-6e13fa6ee921.png">

3. on iPadOS 14
1536 x 2048 px screen, iPadOS 14 and 13, vertical orientation - table with kafkas in the row legend "name" is broken. Horizontal orientation is ok. Happens in both Safari and Chrome.

<img width="568" alt="Screen Shot 2021-04-15 at 12 04 47 PM" src="https://user-images.githubusercontent.com/20118816/114901496-da906d00-9de2-11eb-9a07-7b7723fea351.png">

4. on iPadOS 14
iPadOS 14, shadows of selected buttons are left after clicking in the place where the button was. This Issue was observed only on our iPad Air 2, not observed on iPad Air 4, iPad Pro and iPhone 12 Pro on Browserstack.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

- You can use this link to see the bugs in Managed Kafka: https://cloud.redhat.com/beta/application-services/streams/kafkas 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug

**What is your product and what release version are you targeting?**

By Summit, but ideally as soon as possible. A lot of users at Summit will be using their mobile phones.

**Comment by evwilkin** [comment]
@jschuler see the issue #3 & last screenshot above - have you seen anything similar with the first column title showing vertically instead of horizontally (issue is on iPad)?  You may be able to see the example [here](https://cloud.redhat.com/beta/application-services/streams/kafkas)

**Comment by jschuler** [comment]
I haven;t been able to repro it. IN safari i used the responsive design mode and clicked around but could not observe the table issue seen above
![Uploading Screen Shot 2021-04-16 at 12.30.31 PM.png…]()

**Comment by srambach** [comment]
#3 was fixed in https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/pull/443 by changing the **min**-width media query to be at 769 instead of 768. I suspect there was funny business with the **max**-width queries in PatternFly.

**Comment by christiemolloy** [comment]
Thanks @srambach @evwilkin and @nicolethoen for helping out with those issues. I need to follow up with Marek who originally filed the issues but I am also unable to reproduce 2 and 4. I think we can close out this issue and I'll follow up with any other issues once I can reproduce them!

**Comment by evwilkin** [comment]
Closing per comment above - issue 1 (#5692 ) and 3(https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/pull/443) resolved, issues 2 and 4 no action needed.
