### ISSUE TITLE
Toolbar: breakpoints for switching to responsive view are not working correctly

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#5694]
the `closeExpandableContent` function in `Toolbar.tsx` does not need to collapse at any page width.

It needs to set the `isManagedToggleExpanded` state value to false only when the width of the window(?) or parent(?) is smaller than the `ToolbarToggleGroup`'s `breakpoint` prop.

the `closeExpandableContent` function may need to move into the `ToolbarToggleGroup` and call the `toggleIsExpanded` function passed in via the context.

Be sure to test this solution on mobile

we should test that the tool bar works when windowWidth is set by consumer.

**Comment by evwilkin** [comment]
Related issue: https://github.com/patternfly/patternfly-react/issues/5682
