### ISSUE TITLE
Select/Dropdown closes when clicking scrollbar in order to scroll down and see all options

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#5703]
**Describe the issue. What is the expected and unexpected behavior?**

This may not be fixable due to the nature of click events on the document. I have a form with a Select that is near the bottom of the window, so the user needs to scroll down after opening it to see all the options. If they want to scroll by clicking and dragging the scrollbar, this triggers a `mousedown` event on the document, which causes the `onToggle` event to trigger and close the menu. They can't simply open it again after scrolling down, since its position at the bottom of the document means that when it is closed, the page shrinks a bit and scrolls back up. So the user must use a scroll wheel or gesture to scroll down and see the menu.

If possible, it would be ideal to find a way to detect whether that mousedown event is targeting the browser's scrollbar, and if so prevent the `onToggle` handler from being called. However, I see no clear way to make this detection, in my testing the event triggered when clicking the scrollbar has `event.target` set to the element underneath the scrollbar as if you clicked through it (this is on mac, where scrollbars are semi-hidden and float over the page). Solutions I've found online involve measuring whether the click location is in that scrollbar zone, which feels hacky to me.

Suggestions welcome.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Can be reproduced on all of the Select and Dropdown examples in our docs. Open a menu, use the scrollbar by dragging with the mouse to scroll down, observe that the menu closes.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

I'd consider it a bug, this can potentially make using the scrollbar with the mouse pointer not viable in certain contexts.

**What is your product and what release version are you targeting?**

Migration Toolkit for Virtualization. No particular target release.

**Comment by mturley** [comment]
@kmcfaul here's an idea: i just tested comparing the `mousedown`, `mouseup` and `click` events, and it looks like while clicking and dragging across the page itself does trigger all 3, if you drag the scrollbar it only triggers `mousedown` and then `mouseup`, without triggering `click`. Maybe if we just have the dropdown's `onToggle` handler called only on `click` instead of `mousedown` that would fix it? Not sure why we chose `mousedown` there.

**Comment by kmcfaul** [comment]
You know I think that's the difference. Composable menu demos use `click` not `mousedown` event handlers. Testing locally, it looks like that does resolve the issue! I'll put up a PR with the fix.
