### ISSUE TITLE
Slider: the TextInput when used with the Slider should respect the max value of the slider 

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5707]
This is the example from the docs:
![Screen Shot 2021-04-23 at 09 49 08](https://user-images.githubusercontent.com/14921356/115676637-129e2f80-a350-11eb-8f4c-809a3deede37.png)
In the first slider, one can see that the slider max value is 8, the user can however insert in the text input a value bigger than that.

I did not check if it's an implementation issue of the example code, or the component implementation in the react-core.

**Comment by tlabaj** [comment]
Hi @KKoukiou.  Once you hit enter the input refreshes to the max value.  Are you saying that the component should not let the consumer enter in anything above the max value?

**Comment by KKoukiou** [comment]
@tlabaj Oh interesting, I just tabbed away. I would expect that when the text input loses focus (not only on enter) it would get reset to the min or max value if it's outside of the boundaries.

**Comment by KKoukiou** [comment]
However, this is really just my expectation, I think we need to consult someone with more experience than me here, regarding the expected behavior :)

**Comment by tlabaj** [comment]
It should have changed when it looses focus as well.  I will look into that!

**Comment by KKoukiou** [comment]
Relevant still
