### ISSUE TITLE
Slider: the need for the user to keep track of the slider percentage values is unnecessary

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5708]
Right, now the steps of the Slider component which are provided by the user should have the user desired value but also the percentage based value for the Slider.

The later is of no interest for the consumers of this component, it's really only interesting for the PF internal  implementation of the component. Therefore I believe it should be an implementation detail, not a user provided value.

In fact, this jump between the actual steps and the percentage steps, not only makes consuming this component not an optimal experience but has performance issues as well.

Will explain here, copying the example code of the component inline: ( I just changed the length of the steps array and autogenerated it, no other changes from the initial example code)

```

class DiscreteInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: 1000
    };

   const maxValue = 5000; 
   const minValue = 1000;

    this.steps = (
       Array.apply(null, { length: maxValue + 1 })
               .map(Number.call, Number)
               .slice(minValue)
               .map(step => ({ value: ((step - minValue) / (maxValue - minValue)) * 100, label: step.toString(), isLabelHidden: true }))
   );

   this.onValueChange = value => {
        this.setState({
          value
        });
    };
  }

  render() {
    const step = this.steps.find(step => step.value === this.state.value); <---- This is problematic here. find has O(n) complexity so at each move of the slider thumb we need to go over the array to find the matching value! The initial example code has 10 steps, but steps can be really a lot. We use sliders for memory manipulation, so we talk about 0 - 10000MiB.

    const displayValue = step ? step.label : 0;
    return (
      <>
        <Text component={TextVariants.h3}>Slider Value is: {displayValue}</Text>
        <Slider isDiscrete currentValue={this.state.value} onValueChange={this.onValueChange} steps={this.steps} />
      </>
    );
  }
}
``` 

What I suggest, is that since this component is still Beta, we change the steps property, and define it as { label, isLabelHidden } only. The value => percentage mapping can be stored in a JS object where key is the label and value is the percentage and handled internally by the component. Does this makes sense? 

Is there some reasoning behind the current implementation that I don't understand?

CC @tlabaj @redallen

**Comment by KKoukiou** [comment]
I just saw https://github.com/patternfly/patternfly-react/pull/5669, seems that this actually solves this since it completely reapproached how the steps are defined.

**Comment by KKoukiou** [comment]
OK I just checked the new implementation and there is still need to provide percentage when using custom steps. So this is still valid.

**Comment by tlabaj** [comment]
Thanks for evaluating the component and giving  all the feedback!  It is great to get early feedback while the component is Beta!   
Just to make sure I am understanding the request correctly, Are you suggesting adding another prop that would have the key value pair?

**Comment by KKoukiou** [comment]
@tlabaj actually not, changing how the customSteps property is exposed. I say that steps can be just steps like:

```
[
{ value: 10, label: "10" },
{ value: 15, label: "10" },
{ value: 17, label: "17" },
{ value: 20, label: "20 },
]
```

Without having any values for the percentage the slider component should display. The latter can be calculated in the Slider implemention, not the provided by the user in the steps.

So in the slider code we can just get the percentage by: `((step.value - minValue) / (maxValue - minValue)) * 100` where minValue is the first step and maxValue the last step.

Then onValueChange shoud provide the actual value, not the percentage value.

**Comment by tlabaj** [comment]
Got you!  Thanks for clarifying.  Yes. that should work!
