### ISSUE TITLE
Slider: when using min/max slider (no custom steps) there should be a property to show the min/max limits

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5709]
Something like this: ( existed in the PF3 slider)
![Screen Shot 2021-04-23 at 11 53 05](https://user-images.githubusercontent.com/14921356/115694733-6f561600-a361-11eb-9178-67ef4e869a50.png)

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
This makes sense to me. Thanks for suggesting this @KKoukiou .

**Comment by tlabaj** [comment]
@mcarrano would we want to show a tick at the min/max points?

**Comment by mcarrano** [comment]
Yes, I think we'd want to make the appearance the same as any custom tick marks we add.
