### ISSUE TITLE
Tabs: disable select content border on click

### ISSUE THREAD

**Issue by altwarg** [patternfly/patternfly-react#5721]
I want to disable the display of the borders of the tab content when clicking on an empty tab content space.

Image:
![image](https://user-images.githubusercontent.com/34391398/116272060-41216d80-a789-11eb-8c49-db8e6ed37350.png)

Video:

https://user-images.githubusercontent.com/34391398/116272872-f2280800-a789-11eb-986e-6bbdbf3d3352.mp4

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
1. Open documentation: https://patternfly-react.surge.sh/components/tabs
2. Move the mouse pointer over the contents of the tab and click on it
3. Click on free tab content.

**What is your product and what release version are you targeting?**
@patternfly/react-core@4.115.2

**Comment by tlabaj** [comment]
cc @mcoker
