### ISSUE TITLE
Incorrect expand icon in nested Expandable Datalist component

### ISSUE THREAD

**Issue by bookwar** [patternfly/patternfly-react#5728]
**Describe the issue. What is the expected and unexpected behavior?**

In the nested expandable DataList component toggle icon always shows arrow pointing down. Even when the row is not expanded.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/sleepy-breeze-c8c41?file=/src/App.js

```
const ExpandedDataList = (props) => {
    const [expanded, setExpanded] = useState(false);
    console.log(props)
    let nested = (
	<p> something </p>
    );
    if (props.add == "yes") {
	nested = (<ExpandedDataList add="no" />);
    }
    
    return (
		<DataList id={props.add} isCompact>
		    <DataListItem isExpanded={expanded}>
			<DataListItemRow id={props.add}>
			    <DataListToggle
				onClick={() => setExpanded(!expanded)}
				isExpanded={expanded}
				id={props.add}
			    />
			    <DataListItemCells id={props.add}
				dataListCells={[
				    <DataListCell key="version" id={props.add}>
					Data Header
				    </DataListCell>,
				]}
			    />
			</DataListItemRow>
			<DataListContent
			    isHidden={!expanded}
			    id={props.add}
			>
			    {nested}
			</DataListContent>
		    </DataListItem>
		</DataList>
    );
}

const Local = (props) => {
    return (
	<ExpandedDataList add="yes"/>
    );
};
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

This is a bug. The workaround is to ignore the label, but it is confusing to users.

**What is your product and what release version are you targeting?**

"@patternfly/react-core": "^4.97.2",

**Comment by Andrei-Stepanov** [comment]
Relates to https://github.com/patternfly/patternfly/issues/2177

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
I see the issue. I think this needs to be a core fix. @mcoker can you confirm?

**Comment by mcoker** [comment]
@mcarrano yes, it's the same as https://github.com/patternfly/patternfly/issues/2177

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/issues/2177#:~:text=fix(data-list)%3A%20fixed%20toggle%20icon%20bug%20with%20nested%20data%20lists%20%234041
