### ISSUE TITLE
AreaChart Line Axis

### ISSUE THREAD

**Issue by Makoto7** [patternfly/patternfly-react#573]
Hello,

I am using the AreaChart component : 
https://www.patternfly.org/pattern-library/data-visualization/area-chart/#overview

And I haven't found in the documentation how to initialize my own values for the line axis (x) of the Chart, only for the column (y) ... If someone can answer to my problem, it would be great  \(+o+)/  Thanks

**Comment by rebeccaalpert** [comment]
Hi there @Makoto7! You can pass in x axis data via an axis prop on the AreaChart.

Example x axis data:
`const areaChartAxis = {
  "x": {
    "categories": ["Cats", "Dogs", "Rabbits", "Turtles"],
    "type": "category"
  }
};`

Example y axis data:
`const areaChartDataColumns = [
  ['happy', 350, 400, 350, 0],
  ['hungry', 140, 100, 150, 205],
  ['bored', 10, 60, 90, 10],
  ['sleepy', 260, 10, 305, 100]
];`

Example of props:
`<AreaChart id="area-chart-1" axis={areaChartAxis} size={{ width: 600 }} data={areaChartData} />`

Result:
<img width="620" alt="screen shot 2018-10-19 at 11 10 57 am" src="https://user-images.githubusercontent.com/7014965/47226949-b5e0e900-d38f-11e8-884d-070e701d5119.png">
