### ISSUE TITLE
[BUG] Toolbar window reference prevents the component to be used with SSR

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#5732]
Browser window reference in constructor prevents the component to be used with SSR

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Use the component in SSR app

It is a bug and can be fixed by setting the value in `useEffect`/`componentDidMount` lifecycle.
Here is the line: https://github.com/patternfly/patternfly-react/commit/73a0f60ebb64235a1d63b7d01d15da324b790f14#diff-36c890e98584934106f358ac37c47371f6ea68605720b1a5f156446ac53a4d13R60

**What is your product and what release version are you targeting?**
CRC UI docs, anyone using server-side rendering.

**Comment by redallen** [comment]
Depending on your SSR framework `componentDidMount` and/or `useEffect` are still called. I've put up a PR to make react-core, react-table, and react-topology work regardless of `window` being defined. It sets a reasonable guess of `window.innerWidth = 1200`.
