### ISSUE TITLE
Horizontal navigation - missing hamburger on small screen size

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#574]
https://github.com/patternfly/patternfly-react/pull/171 - this contribution nearly capture all of the patternfly functionality defined for horizontal nav, but when resizing storybook and the example, the hamburger menu doesn't show up.

https://www.patternfly.org/pattern-library/navigation/horizontal-navigation/#code - here is a working html/css example that can be used

**Comment by rachael-phillips** [comment]
This was resolved. Closing this out.
