### ISSUE TITLE
Primary detail cards on last row don't have shadows

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-react#5742]
The primary detail demo shows the cards in all rows except for the bottom row having shadows as normal cards do.
![Screen Shot 2021-05-04 at 12 06 36 PM](https://user-images.githubusercontent.com/30870144/117034480-58081880-acd1-11eb-94b7-e6b8b7a39f2c.png)

We are about to implement this into OCM for our add-ons although it isn't blocking our release. I assumed this was a bug but if there was some reason it was approached this way from a design POV, I'd like to hear more!

Assuming this is fixed, we can a push a fix into OCM whenever, so there is no defined timeline from us.

**Comment by tlabaj** [comment]
cc @mcoker
