### ISSUE TITLE
Composite components

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#5747]
I have a question about the component variants and customization. I will use the `SelectOption` as an example but a similar pattern could be found in most components with different variants.

My question is, can we use composite components to create "advanced" variants of components instead of using props? Reason being, that if I use the most basic version of a component, I will still end up with all of the code for other variants in my production bundle. It is negligible in one component, but it can very quickly snowball and we end up with a lot of dead code.

Here is an example with `SelectOption` component and its `description` prop: https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Select/SelectOption.tsx#L299

```jsx
// current
import {SelectOption} from '@patternfly/react-core';

...
<SelectOption description="Foo" />

// composite component
import {SelectOption, SelectOptionDescription /*or some other name*/} from '@patternfly/react-core';

...
<SelectOption>
  <SelectOptionDescription>Foo</SelectOptionDescription>
</SelectOption>
```

The difference between the two is the following. Currently, if I choose to use the most basic `SelectOption` I will still end up with the description code in my production bundle. There is no way around it, its a part of the JSX markup.

With the composite component, I would only include the description code if I were to also include the `SelectOptionDescription`.

Right now, if I use the most basic `SelectOption` component only with the `value` prop set, I will still end up with JSX markup for the following variants:
- `SelectVariant.checkbox`
- `description`
- `favoriteButton`
- `itemCount`
- `isNoResultsOption`

But the only thing I am basically interested in is the `value` prop.

I understand the intention behind using the props to make it as easy as possible to start using the components without necessary requirements. However, we could achieve both by, exposing all of these composite components. By using them the developer can construct only the bare minimum they require. Then we can expose an additional "complete" component that would provide all the features out of the box. Similar to like the card component works for example. If I want a header or footer, I just add it as a child to my component. If I don't the code is not in my bundle.

I know there is not much we can do about existing components without introducing breaking changes, but I would like to discuss this approach for upcoming components.

cc @redallen

**Comment by redallen** [comment]
@Hyperkid123 If you didn't have to pay the cost of `import { SelectOptionDescription } from '@patternfly/react-core';` when not using the `description` prop, which API do you prefer?

**Comment by Hyperkid123** [comment]
@redallen 

My preference is the composite approach

```jsx
<SelectOption>
  <SelectOptionDescription>Foo</SelectOptionDescription>
</SelectOption>
```

I don't mind sacrificing a bit more time over fine control. But I said we can always have both if we create these "complete" components.
