### ISSUE TITLE
Select: enable hasInlineFilter for single select

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#5764]
Enable `hasInlineFilter` for single select / grouped single select variants in addition to the checkbox select variant.

**Comment by kmcfaul** [comment]
@mcarrano Does this have an okay from design to implement? I pinged you in the thread that sourced this enhancement request.

**Comment by mcarrano** [comment]
Yes. I hadn't realized that the filter was restricted to checkbox select, only.
