### ISSUE TITLE
Enhancement: Enable table columns to be resizable/ draggable (width)

### ISSUE THREAD

**Issue by Swabisan** [patternfly/patternfly-react#5785]
For table content that has long text (besides wrapping) does it make sense for the PF Table columns to have an enhancement for resizing width by dragging?

I would imagine that this would be an optional flag feature, or the table columns would have a method where a downstream application could implement this feature.

**Comment by tlabaj** [comment]
cc @mcarrano @mcoker

**Comment by mcarrano** [comment]
@tlabaj @nicolethoen is this something we can potentially support with our table implementation? If so, we can work on a design for this.

**Comment by mcarrano** [comment]
I am going to close as we have no plan to implement in the near future. We can revisit if this need arises again in the future.
