### ISSUE TITLE
Table: add draggable rows

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5817]
Add draggable row capability to Table as a follow up to: https://github.com/patternfly/patternfly/issues/4065  This feature may be added to the composable table if that seems like the best approach.

cc @jessiehuff accessibility considerations here?

**Comment by jessiehuff** [comment]
I imagine that this would follow similar accessibility considerations as the [draggable datalist component](https://www.patternfly.org/v4/components/data-list#draggable) that we implemented with [this PR](https://github.com/patternfly/patternfly-react/pull/4852). We might need to make adjustments when considering for table though that we can determine if implementation issues come up.

**Comment by mcoker** [comment]
@nicolethoen @kmcfaul the core work has been merged - https://github.com/patternfly/patternfly/pull/4120

* Creates a `td.pf-c-table__draggable` for the draggable button
* `.pf-c-button.pf-m-plain` goes in `td.pf-c-table__draggable`
* Adds `.pf-m-ghost-row` to the parent `tr` when dragging
* Same a11y as the draggable data-list - documented under the draggable table example in core
