### ISSUE TITLE
Form: field validation/password strength demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5819]
Add the ability to implement password strength validation on the Login page.

Core issue: https://github.com/patternfly/patternfly/issues/4018 

Design: https://marvelapp.com/prototype/6jehce7/screen/78511266 

--

This demo relies on https://github.com/patternfly/patternfly-react/issues/6002

**Comment by nicolethoen** [comment]
We need to be sure this demo utilizes a 'live-region' correctly. May need to collaborate with @jessiehuff some.

**Comment by tlabaj** [comment]
closed by #6053 6053
