### ISSUE TITLE
Support for tooltips on disabled dropdown items (aria-disabled variation)

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#5826]
From a discussion in this issue - https://github.com/patternfly/patternfly-react/issues/5127

We added support for a `.pf-m-aria-disabled` variation on dropdown items to support adding tooltips on disabled items

https://github.com/patternfly/patternfly/pull/4072

cc @jschuler @mcarrano

**Comment by mcoker** [comment]
@tlabaj is this the same issue as https://github.com/patternfly/patternfly-react/issues/4581?

**Comment by tlabaj** [comment]
@mcoker.  I believe so.  I will close the other issues since this one has already been prioritized.
