### ISSUE TITLE
Dual List Selector tree variant ignores initial chosenOptions

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#5828]
**Describe the issue. What is the expected and unexpected behavior?**

When [Dual List Selector](https://www.patternfly.org/v4/components/dual-list-selector) tree variant has initial `chosenOptions`, it ignores them - when moved to available, they are not moved and the selected disappear. When some available are moved to chosen, the chosen are completely rewritten.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/recursing-murdock-kw4ci?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug

**What is your product and what release version are you targeting?**

Data Driven Forms, Cost Management

**Comment by rvsia** [comment]
cc @ddonahue007

**Comment by ddonahue007** [comment]
Also there is certainly a bug here. If you try to move the initial options back to the left pane you will notice that they are remove from the list completely.

**Comment by ddonahue007** [comment]
This should be fixed, please

**Comment by tlabaj** [comment]
closed by #6180
