### ISSUE TITLE
ToolbarChipGroupContent: 'filters applied' string needs to be expose so that it can be I18n

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5836]
![Screen Shot 2021-05-27 at 14 04 32](https://user-images.githubusercontent.com/14921356/119656731-4f67b580-be2b-11eb-88d0-055dd801d687.png)

**Comment by KKoukiou** [comment]
That's not solved still but also not straightforward.
The reason is that the is `$0 filters applied`, where $0 is the number of the filters. Letting the user provide the `flters applied` string through a property translated is wrong, as the number won't be a prefix to that string in all languages. Any ideas here?

**Comment by tlabaj** [comment]
@mcarrano can we add this one to a milestone please.
