### ISSUE TITLE
Extraneous header for expandable content of first table row

### ISSUE THREAD

**Issue by KevinFCormier** [patternfly/patternfly-react#5843]
**Describe the issue. What is the expected and unexpected behavior?**
When using an expandable table, if the first row has expandable content, the headers are not hidden because the `data-label` attribute is included on the `<td>`.

I believe the problem is this line, which does not account for `parentId` being 0 for the first row.
https://github.com/patternfly/patternfly-react/blob/master/packages/react-table/src/components/Table/BodyCell.tsx#L71

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/runtime-star-z0l1g?file=/index.js
![image](https://user-images.githubusercontent.com/42188127/119728332-57caeb00-be41-11eb-9c08-02ff939494e3.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. No workaround that I'm aware of.

**What is your product and what release version are you targeting?**
RHACM 2.3. We are using the latest PatternFly versions.

**Comment by KevinFCormier** [comment]
FYI @mcarrano @mcoker

This is the main issue with the expandable table that I mentioned. I couldn't reproduce it with your examples at first, so in the process of trying to figure out why I was able to track down the problem.

**Comment by mcarrano** [comment]
@tlabaj @nicolethoen thoughts?

**Comment by KevinFCormier** [comment]
How can I track when this will be available on npmjs.com and in what version?

**Comment by redallen** [comment]
@patternfly-build will leave a comment in the next 30m or so with a prerelease. The official validated release will come later this week which you can track on https://www.patternfly.org/v4/developer-resources/release-notes.

**Comment by redallen** [comment]
We merged another PR after yours so the prerelease is there:
https://github.com/patternfly/patternfly-react/pull/5827#issuecomment-852233048
> @patternfly/react-catalog-view-extension@4.11.38
@patternfly/react-code-editor@4.2.72
@patternfly/react-console@4.8.14
@patternfly/react-core@4.126.2
@patternfly/react-docs@5.18.47
@patternfly/react-inline-edit-extension@4.6.121
demo-app-ts@4.103.2
@patternfly/react-log-viewer@4.1.15
@patternfly/react-table@4.27.20
@patternfly/react-topology@4.8.68
@patternfly/react-virtualized-extension@4.8.19
