### ISSUE TITLE
Dual list bug for moving filtered items

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-react#5854]
We got the following message in our Patternfly slack from Eric Gustavsson:

> With dual list I was notified of another UX concern from our application. Where if a user filters for something and sees something in the list, they might click select all button instead. They expect that only the items in the filtered results are moved over, not everything

I personally would agree with this statement. If you filter for "Option 4" and then click the double arrow, I'd expect that only "Option 4" would get moved over to the other side.

See gif below:
![patternfly-dual-list-move-all](https://user-images.githubusercontent.com/51165119/120323760-d5fd1680-c2b3-11eb-8b03-99cdf26fb52e.gif)

cc @mcarrano

**Comment by mcarrano** [comment]
We agree this is a bug. Will pull this into our upcoming sprint.
