### ISSUE TITLE
Spike: DateTimePicker Component

### ISSUE THREAD

**Issue by jkupferer** [patternfly/patternfly-react#5858]
## Description

A component that allows users to select a date and time, combining functionality of the DatePicker and TimePicker.

![Screenshot from 2021-05-27 13-55-20](https://user-images.githubusercontent.com/7378166/119882122-a933b280-bef3-11eb-9856-e6c0eb2557a4.png)

### Use Cases

* Select a time within working hours on work days.
* Select a time within the next 12 hours possibly overlapping midnight to the next day.

## Why this component is needed

While it is possible to stitch the DatePicker and TimePicker together, it puts a lot of extra complexity on the application developer to manage changes in both components when values are validated and processed together. For example, if a value is out of range it is not that the date is invalid or the time is invalid but the combined date/time is invalid. It would also be good to have a single text box where the date + time value could be copied or pasted from the box rather than two separate text inputs.

## Specific Applications

Red Hat GPTE Service Catalog

Our specific use case is setting runtime and lifetime for environments where a user should be able to select a time within a bounded time range (ex: within the next 72 hours). We have our own work-around using a dropdown we can use for now.

**Comment by mcarrano** [comment]
@jkupferer See the draft PR (https://github.com/patternfly/patternfly-react/pull/6545) in response to your issue and let us know if this meets your needs.

cc @nicolethoen @gabipodolnikova
