### ISSUE TITLE
SVG icons, especially those of different sizes, are not properly aligned

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-react#5862]
Icon alignment for inline SVGs has inline CSS that applies `vertical-align: -0.125em`.

However, this doesn't work in the following cases:
1. When CSP is enforced, as inline CSS should not be allowed.
2. When icons change sizes, as the offset is different for the line of text versus the (larger) icon.

**Comment by garrett** [comment]
This is still an issue. I was sick for the past few weeks, so I didn't catch stale bot in time. Please re-open.

**Comment by redallen** [comment]
Will be closed by #5275.

Unfortunately it's a breaking change.
