### ISSUE TITLE
Editable label group

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#5875]
Implement an editable label group. Core issue and requirements: https://github.com/patternfly/patternfly/issues/3741

Allows user to click on a label to enable it for editing. Click enter to commit changes.

**Comment by nicolethoen** [comment]
We should definitely intentionally consider accessibility in this update - both keyboard interaction and communication the functionality using the screen reader. I also just approved the a11y docs on org for Label and know they'd probably need to be updated substantially after this change is made, so we'd likely need to create a follow up issue in org once this is done.

**Comment by kmcfaul** [comment]
Time allowing, I will also try to add in the icon from InlineEdit and a set of interaction patterns if the icon is present. Otherwise, I will open a follow up issue.

**Comment by kmcfaul** [comment]
Interactions without icon:

Mouse:
Click on text to start editing

Keyboard:
Press `Tab` to navigate to editable text
Press `Enter` to start editing

Both:
Press `Enter`/`Tab`/click off to complete an edit (include an optional onComplete callback)
Press `Escape` to cancel an edit (include an optional onCancel callback)
