### ISSUE TITLE
Select Typeahead: missing bottom border

### ISSUE THREAD

**Issue by knokit** [patternfly/patternfly-react#5882]
**Describe the issue. What is the expected and unexpected behavior?**
After `@patternfly/react-core@4.106.2` the bottom border of the typeahead's input is not showing up.

![select_typeahead_missing_border-bottom](https://user-images.githubusercontent.com/3659829/121017691-d9097280-c79d-11eb-98a9-d11986db0f56.png)

![select_typeahead_missing_border-bottom2](https://user-images.githubusercontent.com/3659829/121014502-58954280-c79a-11eb-9b17-1b05a68423e0.png)

It seems that the color is overridden by this rule:

![typeahead_border-bottom-color](https://user-images.githubusercontent.com/3659829/121014655-7ebae280-c79a-11eb-905d-ba6ef3d5b5fe.png)
  

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
My setup is based on patternfly-react-seed and I can't reproduce this issue with CodeSandbox.

So, I've forked patternfly-react-seed and added a Typeahead component to the dashboard page:
https://github.com/knokit/patternfly-react-seed/tree/bug/select-typeahead-missing-bottom-border

1. checkout `bug/select-typeahead-missing-bottom-border` branch
2. `npm run start:dev`
3. check the Typeahead component in the dashboard page

**Comment by nicolethoen** [comment]
@knokit 

We have actually been actively investigating this issue.
Could you do me a favor and see if the issue resolves itself when you update your versions to the following?

"@patternfly/patternfly": "4.108.2",
"@patternfly/react-catalog-view-extension": "4.11.42",
"@patternfly/react-charts": "6.14.29",
"@patternfly/react-code-editor": "4.2.76",
"@patternfly/react-core": "4.128.2",
"@patternfly/react-icons": "4.10.11",
"@patternfly/react-inline-edit-extension": "4.6.125",
"@patternfly/react-log-viewer": "4.1.19",
"@patternfly/react-styles": "4.10.11",
"@patternfly/react-table": "4.27.24",
"@patternfly/react-tokens": "4.11.12",
"@patternfly/react-topology": "4.8.72",
"@patternfly/react-virtualized-extension": "4.8.23"

We are actively testing these release candidates an would love to know if it seems to sort out the product in the wild.

**Comment by knokit** [comment]
@nicolethoen, updating to the versions you've mentioned seems to solve the problem for me! Thanks!

In my case, I'm only using the following packages:

"@patternfly/react-core": "4.128.2",
"@patternfly/react-icons": "4.10.11",
"@patternfly/react-styles": "4.10.11",

**Comment by seanforyou23** [comment]
I noticed after upgrading to the below pkg versions the borders are gone from Select components, but it's only in "prod" mode (after having run a build with webpack). In dev mode the borders show up just fine. Might it be related?

```
    "@patternfly/react-core": "^4.128.2",
    "@patternfly/react-icons": "^4.10.11",
    "@patternfly/react-styles": "^4.10.11",
    "@patternfly/react-table": "^4.27.24",
    "@patternfly/react-tokens": "^4.11.12",
```

<img width="400" alt="Screen Shot 2021-06-14 at 9 51 14 AM" src="https://user-images.githubusercontent.com/5942899/121903678-8a585d00-ccf6-11eb-9564-39e83da285c9.png">

<img width="400" alt="Screen Shot 2021-06-14 at 9 51 21 AM" src="https://user-images.githubusercontent.com/5942899/121903682-8a585d00-ccf6-11eb-84cf-06b3d91df6c0.png">

**Comment by seanforyou23** [comment]
Nvm - I just tried to do a minimal reproduction of the issue and it seems to work fine. Must be something in the consuming app. False alarm 😅

**Comment by knokit** [comment]
@seanforyou23, did you check this issue https://github.com/patternfly/patternfly-react/issues/5650?

**Comment by seanforyou23** [comment]
Ah, nope, but that looks very relevant - thank you @knokit
