### ISSUE TITLE
Bug: Value input in Slider component doesn't respect max/min constraints.

### ISSUE THREAD

**Issue by MariSvirik** [patternfly/patternfly-react#5893]
If I try to enter a value that's larger than the prescribed maximum, it should be constrained to what's shown on the slider. 

Constraints work if I try to enter a value directly to the value input - after clicking enter a value that exceeds the maximum change to the maximum allowed value. What seems to be an issue is that prescribed constraints don't work when I use carets to increase or decrease the value by set increments over the maximum/ minimum.
<img width="830" alt="Screenshot 2021-06-08 at 9 48 42" src="https://user-images.githubusercontent.com/51960547/121145359-28ec4600-c83f-11eb-8a97-30cf615a8a7f.png">

**Thumb value input**
What's more, if I enter a value lesser than a prescribed minimum to a thumb value input it let me do that (see the picture below)

<img width="863" alt="Screenshot 2021-06-08 at 9 50 13" src="https://user-images.githubusercontent.com/51960547/121145350-27bb1900-c83f-11eb-9e0b-3ffdcc9eb8fe.png">

But after clicking enter, a thumb and a thumb value input moved far left from 0 (minimum) - out of the sight. It appears again if you click anywhere on a slider. This is the case for both direct inputs and for value changes made by carets as well.

Value entered -4
<img width="868" alt="Screenshot 2021-06-08 at 10 01 28" src="https://user-images.githubusercontent.com/51960547/121146788-8fbe2f00-c840-11eb-8d9a-9ff376947215.png">

Value entered -14
<img width="834" alt="Screenshot 2021-06-08 at 9 50 01" src="https://user-images.githubusercontent.com/51960547/121145356-2853af80-c83f-11eb-85fb-4671cb59a4b7.png">

Allowed maximimum is 100 (this bugcan be reproduce by using carets but sometimes also by direct input)
<img width="888" alt="Screenshot 2021-06-08 at 10 08 57" src="https://user-images.githubusercontent.com/51960547/121147931-9e591600-c841-11eb-8ce2-2cf549a7dc17.png">

Check all the value inputs on [this page](https://www.patternfly.org/v4/components/slider) as none of them seems to be working correctly.

**Comment by MariSvirik** [comment]
@mcarrano

**Comment by mcarrano** [comment]
Thanks for filing this and providing a detailed explanation @MariSvirik . Now I am able to reproduce the problem by using the spin buttons. @tlabaj can you take a look at this?
