### ISSUE TITLE
The Label component takes specific strings for color, hard to use in Typescript

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#5895]
**Description**
The color prop for `Label` is defined as:
```
color?: 'blue' | 'cyan' | 'green' | 'orange' | 'purple' | 'red' | 'grey';
```

This makes it difficult to use in typescript where you want to be able to set the label color based on the type of item you are trying to label. Ie: 
```
const labelColors = {
 type1: 'blue',
 type2: 'green',
...
```
as it gives a typescript error that string cannot be assigned to  'blue' | 'cyan' | 'green' | 'orange' | 'purple' | 'red' | 'grey'

**What is your product and what release version are you targeting?**
RHODS 1.0

**Comment by redallen** [comment]
What's wrong with casting to `LabelProps["color"]`?
```ts
import { LabelProps } from '@patternfly/react-core';

const labelColors = {
 type1: 'blue',
 type2: 'green',
...
} as { [key: string]: LabelProps["color"] };
```

We could provide an enum, but I find they just bloat our bundles with redundant strings.

**Comment by jeff-phillips-18** [comment]
I try to avoid casting whenever possible. I can do the above but I, personally, prefer the enums.

**Comment by jeff-phillips-18** [comment]
I'll gladly fix this and other instances if deemed worthwhile, jlmk

**Comment by redallen** [comment]
I've though about this some more and since we started down the path of exporting enums it's worthwhile to help our Typescript consumers. Bundle size is rarely a concern of PatternFly and these enums gzip well.
