### ISSUE TITLE
TimePicker component accepts 0:00/00:00 AM/PM as valid values for 12 hour format

### ISSUE THREAD

**Issue by sahare** [patternfly/patternfly-react#5898]
**Describe the issue. What is the expected and unexpected behavior?**
TimePicker component accepts 0:00 AM/PM as valid values for 12 hour format

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Enter either 0:00 AM or 0:00 PM in TimePicker, it doesn't show invalid value error

Sandbox: https://codesandbox.io/s/lfncl

<img width="247" alt="Screen Shot 2021-06-08 at 3 50 47 PM" src="https://user-images.githubusercontent.com/11761226/121250799-26581380-c874-11eb-9e7b-3b4af8582fd4.png">
<img width="239" alt="Screen Shot 2021-06-08 at 3 54 06 PM" src="https://user-images.githubusercontent.com/11761226/121250802-26581380-c874-11eb-835e-0a099627ffe5.png">

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
RedHat Open-Cluster-Management release 2.3

**Comment by KevinFCormier** [comment]
I think anything with hour 0 would be invalid for 12-hour format. `00:30 PM`, for instance.

**Comment by tlabaj** [comment]
closed by #6134
