### ISSUE TITLE
Add chart performance disclaimer

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#5906]
Victory is an SVG-based library which comes with tradeoffs compared to canvas. It'd be good to include these alongside some benchmarks that explain when it's good to use canvas or SVG.

Some reading material:
- https://css-tricks.com/when-to-use-svg-vs-when-to-use-canvas/
- https://www.barchart.com/solutions/company/blog/3852318/comparing-html5-canvas-vs-svg-for-charting

**Comment by nicolethoen** [comment]
If we'd like a canvas based PF solution, this would definitely require a spike.
@redallen suggested possibly looking into [uPlot](https://github.com/leeoniya/uPlot) as a tool.
