### ISSUE TITLE
How to use story codes

### ISSUE THREAD

**Issue by vermarajput** [patternfly/patternfly-react#591]
How to use story codes in my project specifically https://www.patternfly.org/pattern-library/content-views/list-view/list-view-inline-edit.html
the actual React Story version is different from above example.

Thanks
Aman

**Comment by jeff-phillips-18** [comment]
There is no inline edit for list view available in patternfly-react at this time. There are stories for a couple of different list view examples. That code coupled with the patternfly core example code for inline edit should allow you to get there but with some work.

**Comment by dgutride** [comment]
Moving to closed due to answer inline.
