### ISSUE TITLE
Menu filtering with text input, user cannot get to menu via keyboard

### ISSUE THREAD

**Issue by kdoberst** [patternfly/patternfly-react#5915]
**Describe the issue. What is the expected and unexpected behavior?**
This relates to [menu items with text input](https://www.patternfly.org/v4/components/menu#filtering-with-text-input).  When a user filters out options, the menu is no longer available via the keyboard.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Method 1
 - Navigate to the filter box.  
 - Enter text that will filter out the first option, but leave others.  In the example linked above, enter `2` to filter out `Action 1` and `Action 3`.
 - Click on 'tab'.  This should move the user to the menu, but the menu is completely skipped and the user has no way to get to the menu via the keyboard.
 
 Method 2
- Navigate to the filter box
- Enter text that will filter out all options.  In the example linked above, enter `no more options` to filter out all three options.
- Hit the delete key until the filter box is empty and all options are visible.
- Click on 'tab'.  This should move the user to the menu, but the menu is completely skipped  and the user has no way to get to the menu via the keyboard.
 

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug - blocking.  There doesn't appear to be a way for the user to get to the menu via the keyboard.

**What is your product and what release version are you targeting?**
Openshift console.  Targeting Openshift console 4.9

**Comment by gdoyle1** [comment]
@mcarrano would it be possible to get this fix in by July 23rd? Looks like that's when Feature Freeze is for OpenShift 4.9 (which is when this will be added into OpenShift

**Comment by kmcfaul** [comment]
This bug can be worked around in the meantime. What is happening is that after the filtering, the `tabIndex` attributes on the menu options are not updated. We can fix this for now in the example code (workaround) and/or can update the menu component to detect when the children property has changed without a re-mount and re-map the `tabIndex` attributes internally.

After the filtering is complete and `menuListItems` is created in the example, add the following line:
`menuListItems[0].props.tabIndex = 0;`

**Comment by mcarrano** [comment]
@gdoyle1 we spoke about this during our Leads meeting today and are going to try and pull this fix into the 2021.08 release scheduled for next week.

**Comment by gdoyle1** [comment]
Thank you @mcarrano !!

**Comment by kdoberst** [comment]
@kmcfaul Your suggestions doesn't quite work.  What it does is change tabindex on the parent `li` tab.  So when a user filters and then hits the `tab` key, it does go to the first element in the menu, but because the focus is on the `li`, the arrow keys to move with in the menu don't work.  

In our specific example, we are using both the filtering box along with favoriting.  Because the user must use the arrow keys to get both the next options and the favoriting button, the use of the arrow keys are important.

**Comment by kmcfaul** [comment]
@kdoberst The PR that was just merged addressing the bug will also address this, as the internal fix will target the first tabbable element. The workaround line would have to find the child `button` of the `li` and set the `tabIndex` there, rather than just on the top item.
