### ISSUE TITLE
Component Tree View: enhance with a more flexible toolbar/header  

### ISSUE THREAD

**Issue by gildub** [patternfly/patternfly-react#5933]
Following initial discussion from https://github.com/patternfly/patternfly-react/issues/4797#issuecomment-739988375, we'd like to continue on the idea to "make the toolbar/header area flexible to pass in anything you want including a search input, actions, or anything that makes sense"

**Comment by tlabaj** [comment]
cc @mcarrano can we get this on the roadmap please.

**Comment by mcarrano** [comment]
Sure. I will get this on our roadmap. Is there a timeframe when this is needed? Right now I'm scheduling into Q4.

**Comment by gildub** [comment]
@mcarrano, 

The konveyor/forklift-ui project has this feature on the target list for it's next release.
I'm currently working on a PR, so hopefully that would be available sooner than later.

**Comment by mcarrano** [comment]
OK. Our next scheduled release is August 4.

**Comment by gildub** [comment]
@mcarrano, great, working on it to get it pushed asap. Thank you.
