### ISSUE TITLE
Slider: Floating input is truncated

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-react#5939]
On [slider: thumb value input](https://patternfly-react.surge.sh/components/slider/#thumb-value-input) the thumb value input truncates oddly and inconsistently:

![Screenshot 2021-06-22 at 09-40-50 PatternFly 4 • Slider](https://user-images.githubusercontent.com/10246/122884113-180efa80-d33e-11eb-8398-f88031b1f229.png)
![Screenshot 2021-06-22 at 09-41-13 PatternFly 4 • Slider](https://user-images.githubusercontent.com/10246/122884114-18a79100-d33e-11eb-9132-7a4f6c635741.png)

This is on Firefox on Linux, and the inputs to the right of the slider on that page do not have this issue.

**Comment by mcoker** [comment]
cc @tlabaj looks like the slider value is adding `.00` to the percentage in the [thumb value input example](https://patternfly-react.surge.sh/components/slider#thumb-value-input). I would expect the input value to exclude that similar to the [value input examples](https://patternfly-react.surge.sh/components/slider#value-input). 

If we want to include decimal points, and the number of characters in the input changes, we can have something watch the input value when it changes, and set `--pf-c-slider__value--c-form-control--width-chars` inline on the `.pf-c-slider` element with the number of characters the input should show. The default for that var if unset is 3.

**Comment by tlabaj** [comment]
@mcoker the way it is implemented, the consumer controls the value that is displayed in the input. 
I think we should support the consumer having decimals since they control the value.  This would also be a problem for large numbers (e.g. the max value is 10000).

**Comment by mcoker** [comment]
@tlabaj can we update our example to better handle the overflow in the text input? We'll need to set `--pf-c-slider__value--c-form-control--width-chars` when the value changes since a text input size doesn't change to fit its value.

**Comment by garrett** [comment]
Still an issue, bot.
