### ISSUE TITLE
Add HelperText demo/documentation

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#5941]
**Describe the issue. What is the expected and unexpected behavior?**
Our helper text component currently requires the user to add all accessibility considerations to dynamic helper text. However, this leaves a lot of room for error for users implementing it. We should create a demo of dynamic helper text that would follow the pattern used by form. I imagine the use case would be similar to our invalid form example where the helper text would need to be inside of a live region (`aria-live="polite"`). Depending on the expected use cases, there may need to be additional attributes to make it accessible (for example, in our [invalid form example](https://www.patternfly.org/v4/components/form#invalid) the input has to also have an `aria-invalid` attribute to announce that the input is invalid). I think it would also be valuable to add a little bit of documentation around this explaining what is being added/these considerations when implementing dynamic helper text.

Potential use cases/examples could be:

#### Invalid
* Form control elements (text input, textarea, form select) 
* Select component

#### Error
* Form component helper text (existing helper text this will likely replace)
* Date picker helper text

#### Danger
* Progress
* Alert
* Button
* Notification drawer item (similar to alert)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement

**Comment by tlabaj** [comment]
@mcarrano can you please add this one to a future milestone.
