### ISSUE TITLE
Slider: can we provide a tooltip for the thumb like PF3 did? 

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5955]
![Screen Shot 2021-04-23 at 11 52 21](https://user-images.githubusercontent.com/14921356/115695246-ea1f3100-a361-11eb-8004-4ca1656e2268.png)

**Comment by mcoker** [comment]
Thanks @KKoukiou!!

**Comment by KKoukiou** [comment]
I tried this - I was not able to come with a satisfying result without flickering etc. I might take a look at it again when I find time, but please if someone else is interested feel free to take over.
