### ISSUE TITLE
Wrong filter accidentally applied using Typeahead Select and isCreatable

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#5961]
The typeahead `Select`'s enter key behavior is confusing with `isCreatable`. It appears that pressing enter will always select the first option available in the list, even without a match. 

We're using typeahead in Cost Management as shown in the screenshot below, but users still want to apply their own filters. That is, when our typeahead API does not discover a match. Thus, users expect to apply text from the input field when the enter key is pressed.

In this case, the user typed "red hat" and immediately pressed enter. However, the "test" option has been selected because it was the first item in the list.

This is confusing to users because pressing the enter key behaves differently here than the search inputs used throughout the Insights Platform. This is a potential blocker because we would be replacing our remaining searches with odd typeahead behavior.

![chrome-capture](https://user-images.githubusercontent.com/17481322/123689553-56feed80-d821-11eb-815b-53925019fd51.gif)

This can also be reproduced with the typeahead Select example here:
https://www.patternfly.org/v4/components/select#typeahead

**Comment by tlabaj** [comment]
cc @mcarrano thoughts on create option always being first?

**Comment by mcarrano** [comment]
I'm OK with that @tlabaj . But under what conditions does the Create option appear when there are still things in the list to be selected? Shouldn't it only come up if we've exhausted choices?

**Comment by nlcwong** [comment]
@mcarrano My issue with it not being first is if we have a person trying to do a like search/filter in where they want to search on the partial word of "AWS" to get both results of "AWS Group" and "AWS Regions".  As it stands, if I choose AWS Group and AWS Regions separately it'll be an AND operator and therefore 0 results would be returned when in fact i want both returned and the way to do it is use "AWS" as the string to match on.

**Comment by dlabrecq** [comment]
Cost Management recently encountered a slightly different customer issue related to the down-arrow icon. See https://bugzilla.redhat.com/show_bug.cgi?id=1992139

Since our items are not populated until the user types, the component appears to users as an unpopulated dropdown. That is, clicking on the icon just shows an empty list.

<img width="1126" alt="Screen Shot 2021-08-10 at 9 36 14 PM" src="https://user-images.githubusercontent.com/17481322/128956433-51b51a3b-01a3-4ff8-8668-69b50268ca51.png">

**Comment by nicolethoen** [comment]
@nlcwong @mcarrano 
It sounds like they don't actually want a Select in this use case.
If they want to be able to use partial strings and treat the Typeahead Select like a search input with some autocomplete suggestions, then this is a different use case than the intended Typeahead Select. We are currently working on a variant of the SearchInput component with an autocomplete (or list of consumer provided suggestions) feature which will likely replace a typeahead select in any of our Toolbar demos.

**Comment by mcarrano** [comment]
@dlabrecq @nlcwong please take a look at the demo just created by @wise-king-sullyman here: https://github.com/patternfly/patternfly-react/issues/6586  I think this might solve your problem, in which case we can close this. Let me know.

**Comment by dlabrecq** [comment]
The example appears to replace the `Select` component with multiple `TextInput` components. This search works a bit differently; for example, you cannot click on the search icon. The search icon also disappears when chips are added.

In addition, the text field becomes smaller as chips are added to the left. I don't believe we want to add chips like that? We also have multiple chip categories.

FYI @nlcwong 
https://patternfly-react-pr-6661.surge.sh/components/text-input-group/react-demos/#auto-complete-search

**Comment by nicolethoen** [comment]
@dlabrecq that is also only a demo - demonstrating one way to wire up the TextInputGroup to handle a chip group and a Menu component to build out an autocomplete.

It is not demonstrating the only way to wire things up. The TextInputGroup can consume anything instead of a single chip group as a child to display there. And the behavior of the items in the menu, as well as the displaying and using of various buttons and controls at the end of the input, is all completely controlled by the product/consumer.

So this should be flexible enough to accommodate your needs. But if you think it's missing the proper hooks and props to do something, let us know :)

**Comment by nlcwong** [comment]
The chips w/in the input box isn't desirable for our use case, but if this is flexible, I'll defer to @dlabrecq on whether or not the vision can be done with this new way of doing things.

**Comment by nicolethoen** [comment]
Yes - for example, you could place the something like this demo - maybe without the chips into a Toolbar and utilize the Toolbar's built in method for displaying chip groups in a section below the filters. Ideally we are moving toward a direction where these building blocks can be configured a number of custom ways.

**Comment by dlabrecq** [comment]
Basically, I'm looking for a pattern / example that fits our use case Vs piecing something together. The functionality around the search icon is confusing.

For example, this filter example shows the search icon on the right. In addition to being able to click on the icon.
http://patternfly-react.surge.sh/components/toolbar#with-filters

**Comment by mcarrano** [comment]
@dlabrecq @nlcwong Can one of you share a design with me or somehow demonstrate the use case you are trying to fulfill? I feel like we can probably solve this with existing components, but I understand how it might be confusing to identify what pattern you should be using. I'm happy to work with you to resolve this.

**Comment by dlabrecq** [comment]
The "toolbar with filters" example is our scenario, but we need the new type-ahead functionality.
http://patternfly-react.surge.sh/components/toolbar#with-filters

I'd really like to see the Text Input Group component used in that scenario, mainly because of the different search icon placement. We have to be mindful not to implement a vastly different toolbar than the other apps under the Insights platform.

FYI, this is what we have today with the Select type-ahead component.

![chrome-capture](https://user-images.githubusercontent.com/17481322/145411021-ece16a25-7259-40a9-99e8-17894bfa4366.gif)

**Comment by dlabrecq** [comment]
FYI, I added PatternFly's new `Text Input Group` component to Cost Management. The type-ahead is more usable, but there are limitations. For example, we cannot add place holder text and aria label. 

I also had to take some liberties regarding how keyboard navigation works.

Below are the observations I made while implementing the `Text Input Group` component.

**Component Issues**

1. Cannot add place holder text and aria label
2. `TextInputGroupMain` does not clear input text for a value of undefined — must be an empty string

**Example issues**

1. Input focus box not rendered correctly without clear button — must conditionally render `TextInputGroupUtilities`
2. Input value cleared when menu has focus and escape key is pressed — should just close the menu and set focus on the text input for further editing

**Cost Management implementation**

1. Added “No results found” label instead of always showing “Suggestions”
2. A lot of keyboard navigation code must be added manually — painstaking to get working correctly

![chrome-capture](https://user-images.githubusercontent.com/17481322/145926414-cc8cb676-7ebf-4de9-a962-066edd14efb1.gif)

**Comment by mcarrano** [comment]
@dlabrecq thanks for documenting all of this and opening a follow-on issue. We will get that work (along with #6682 opened by @nicolethoen ) on our roadmap. There is also a design issue that @mmenestr is working on to clarify our filter guidance a bit. See https://github.com/patternfly/patternfly-design/issues/1045 I agree that our guidelines and examples could be improved to provide a more consistent filter pattern across projects. Will close this issue in favor of the ones mentioned.
