### ISSUE TITLE
Unexpected spacing below Toolbar / ToolbarContent

### ISSUE THREAD

**Issue by jerolimov** [patternfly/patternfly-react#5962]
**Describe the issue. What is the expected and unexpected behavior?**
With one of the latest updates, the `Toolbar` component switches to a grid layout. But the ToolbarContent component renders a "hidden" `div` element which results in an unexpected spacing below the visible toolbar.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/toolbar-grid-gap-exe36?file=/index.js

```tsx
      <div style={{ border: '2px solid red'}}>
        <Toolbar>
          <ToolbarContent>
            <ToolbarItem>
              <Button variant="primary">Action</Button>
            </ToolbarItem>
          </ToolbarContent>
        </Toolbar>
      </div>
```

renders:
![image](https://user-images.githubusercontent.com/139310/123710404-fbf3e780-d86e-11eb-968f-33d728bcc820.png)

The spacing below the "Action" button is unexpected!

Debugging the HTML dom:

`Toolbar` has an unexpected height and is rendered as `grid`:
![image](https://user-images.githubusercontent.com/139310/123710585-4e350880-d86f-11eb-8a0e-2e0a7063f66e.png)

First `ToolbarContent` is what we added above:
![image](https://user-images.githubusercontent.com/139310/123710654-6c026d80-d86f-11eb-9e3d-2293bdf5c7b5.png)

Second ToolbarContent (`<div class="pf-c-toolbar__content pf-m-hidden" hidden=""><div class="pf-c-toolbar__group pf-m-hidden" hidden="" aria-hidden="true"></div></div>`) is rendered `ToolbarChipGroupContent` within the `Toolbar`!
![image](https://user-images.githubusercontent.com/139310/123710778-994f1b80-d86f-11eb-90ea-ec1bbd67de91.png)

The spacing comes from the `ToolbarContent` grid `row-gap`:
![Peek 2021-06-29 00-22](https://user-images.githubusercontent.com/139310/123711034-0d89bf00-d870-11eb-97bf-e9c5bf0798ee.gif)

See [Toolbar.tsx#L150-L159](https://github.com/patternfly/patternfly-react/blob/9866c1a43993d32c3155dfa3851acabe9602c785/packages/react-core/src/components/Toolbar/Toolbar.tsx#L150-L159) and [ToolbarChipGroupContent.tsx#L65-L74](https://github.com/patternfly/patternfly-react/blob/9866c1a43993d32c3155dfa3851acabe9602c785/packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx#L65-L74)

https://github.com/patternfly/patternfly-react/blob/9866c1a43993d32c3155dfa3851acabe9602c785/packages/react-core/src/components/Toolbar/Toolbar.tsx#L150-L159

https://github.com/patternfly/patternfly-react/blob/9866c1a43993d32c3155dfa3851acabe9602c785/packages/react-core/src/components/Toolbar/ToolbarChipGroupContent.tsx#L65-L74

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**
OpenShift Developer Console, related issue: https://issues.redhat.com/browse/ODC-6064

**Comment by mcarrano** [comment]
@mcoker @mattnolting can you take a look at this?

**Comment by mattnolting** [comment]
@jerolimov cc @mcarrano Nice catch! The bug was introduced here: https://github.com/patternfly/patternfly/commit/01daebf5dd145ba26557c836ca61a8c84f03c89f#diff-04ccd6c8202d765341068296fa23550c82f714d91342163ee9329f44f3bee512L411. I'll open an issue to resolve.

**Comment by jerolimov** [comment]
Hey @mattnolting thanks for the pix in patternfly/patternfly. I updated my codesandbox.io example to this version but still got an issue. Did we need an addtional fix or @patternfly/react-core release as well?

**Comment by mattnolting** [comment]
@redallen is it possible to release this bugfix https://github.com/patternfly/patternfly/pull/4197?

**Comment by redallen** [comment]
It's already released in `@patternfly/patternfly@4.119.1`.

**Comment by jerolimov** [comment]
Then this fix alone doesn't help. I don't know. See https://codesandbox.io/s/toolbar-grid-gap-exe36?file=/index.js

**Comment by mattnolting** [comment]
@jerolimov The fix addresses this issue, but the CSS updates aren't present in `4.119.2`. In regards to padding, the toolbar has always had padding, not sure what changed there in your example, but you can control padding with inset modifiers. @redallen any ideas?

**Comment by redallen** [comment]
The issue won't be resolved in `@patternfly/react-core` (which is what @jerolimov is using in the codesandbox) until https://github.com/patternfly/patternfly-react/pull/5971 is merged and we get new `@patternfly/react-core` versions.

**Comment by jerolimov** [comment]
Okay, I will monitor #5971 and will then retry this. If this works I will close this issue. Thanks again :)

**Comment by mattnolting** [comment]
@redallen thanks for looking into it!

**Comment by jerolimov** [comment]
Could verified that the latest `@patternfly/react-core` contains the fix and the toolbar works fine again.

Thanks everyone.
