### ISSUE TITLE
Full height variation of menu toggle

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#5964]
menu toggle: https://github.com/patternfly/patternfly/pull/4153

Adds `.pf-m-full-height` as a variation to the toggle that removes the top/bottom border and makes it fill the vertical space of the parent. Primary use case for this is with the new masthead component.

**Comment by mcoker** [comment]
not stale

**Comment by nicolethoen** [comment]
@mcarrano could we add this to a milestone?
