### ISSUE TITLE
Center aligned page sections

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#5966]
https://github.com/patternfly/patternfly/pull/4011/

Adds a `.pf-m-align-center` variation to the following page section elements. Only works with `.pf-m-limit-width` (`isWidthLimited`, `isBreadcrumbWidthLimited`, `isTertiaryNavWidthLimited`)

* `.pf-c-page__main-nav`
* `.pf-c-page__main-breadcrumb`
* `.pf-c-page__main-tabs`
* `.pf-c-page__main-section`
* `.pf-c-page__main-wizard`

**Comment by mcoker** [comment]
not stale

**Comment by KKoukiou** [comment]
@mcoker when I want to center align the content of the page I just use Flex or Bulseye component directl child of the PageSectoin element. What's the advantage if this way that this issue is going to introduce?

**Comment by mcoker** [comment]
@KKoukiou that's a valid way of doing it, too, and is more flexible than using the prop this will add to page sections. A benefit of this prop is not needing to use another component, so it's less code.
