### ISSUE TITLE
Table examples: rewrite using Hooks and better state management practices

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#5977]
Based on a discussion with @tlabaj. We plan to rewrite all our component examples using function components + hooks instead of class components + `this.state`. I'll be starting with the Table examples since I already have some opinions on how we could improve them in other ways while I'm at it (see https://github.com/patternfly/patternfly-react/issues/3762).

Planning to make time for this soon while we're in a slow period on my product work.

**Comment by mturley** [comment]
Not stale, working on it in https://github.com/patternfly/patternfly-react/pull/6168.

**Comment by mturley** [comment]
@nicolethoen the more I look at and remember #3650, the more I think it should be another PR that looks at what we can memoize, both inside the Table components and in the examples. Katie's TreeView memoization demo today gave me some inspiration :) I'll take a crack at it after I finish the examples (hopefully soon... I've been very distracted by this MTV release deadline next week)

**Comment by nicolethoen** [comment]
Fabulous - thank you @mturley.
After you wrap up everything you've been working on I'll follow up about that other issue.
