### ISSUE TITLE
bug(Datepicker): build in validator does not respext the locale

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#5994]
**Describe the issue. What is the expected and unexpected behavior?**

Inserting a valid date in a different locale than en-us, will make built in validators fail.

The code snippet bellow will make the Datepicker show an 'Invalid date' error, although the date inserted is perfectly valid.

 ``` js
GermanDate = () => {
  const initialValue = new Date().toLocaleDateString("de");
  const [value, setValue] = React.useState(initialValue);
  return (
    <React.Fragment>
      <Button onClick={() => setValue(initialValue)}>
        Reset date
      </Button>
      <DatePicker
        value={value}
        locale="de"
        onChange={value => setValue(value)}
      />
    </React.Fragment>
  );
}
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug

**What is your product and what release version are you targeting?**
Cockpit. Can workaround with custom validators.(theoretically, I was not able to figure this out yet)

**Comment by redallen** [comment]
Try passing a valid `dateParse` function. The default is `(val: string) => new Date(`${val}T00:00:00`)` which leads to invalid dates if not using the ISO format.

Generalizing the `dateParse` function based on locale would almost certainly require a 3rd party library like [date-fns](https://date-fns.org/v2.22.1/docs/parse) or [moment (deprecated)](https://momentjs.com/docs/#/parsing/) which could support all locales. However it was a goal of the PatternFly implementation to not rely on any 3rd party libs and stick strictly to the JS date standard (for which there is no parsing anything beside ISO dates).

**Comment by KKoukiou** [comment]
@redallen wrote this solution for performing localized string -> date conversion:

``` js
const { parse } = require('date-fns');
const locales = require('date-fns/locale');
const locale = 'de';
const formatString = locales[locale].formatLong.date({ width: 'short' });
console.log(formatString);
function parseDate(dateStr) {
  const parsed = parse(dateStr, formatString, new Date());
  // Strip time which may cause bugs in calendar
  const timePortion = parsed.getTime() % (3600 * 1000 * 24);
  return new Date(parsed - timePortion);
}
console.log(parseDate('01.01.1990'))
```
