### ISSUE TITLE
Question: Will TimePicker component support seconds in the future? 

### ISSUE THREAD

**Issue by ljmotta** [patternfly/patternfly-react#5998]
I'm not sure about the other options to handle time on Patternfly, but the two that I'm aware of `TimePicker` and `TextField` with `time` type can't handle seconds. They're both `Time` components and for me it's kind strange to not handle seconds on it. Will it be supported in the future? Or already have any other option?

![image](https://user-images.githubusercontent.com/24302289/124969765-7bb34c00-dffd-11eb-924a-3e72ab1b894d.png)

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by mcarrano** [comment]
@ljmotta We currently don't have any plan to allow time to be entered to the second, although I imagine we could support that. Do you have a specific use case where this is required? If you can provide more background, that would be helpful.

cc @nicolethoen

**Comment by ljmotta** [comment]
Hi there, I'm sorry for taking this long to answer you @mcarrano .

In my use case, we auto-generate a form using a DMN (Decision Model and Notation) model as input. Keeping things simple, using a DMN editor it's possible to create business rules and evaluate them. The nodes from the DMN editor have data types, which are mapped to specifics Patternfly components when the form is beings auto-generated. Some options of data types are `time` and `date-time` (both have seconds on the DMN editor), and on top of it, it's possible to create constraints on them. Patternfly doesn't provide a way to handle seconds.

Example:
- User creates a node using a `time` type and puts a range constraint: 01:00:00 to 01:00:30.

I know my case is more specific, but I believe it could be valuable for some other people to have the possibility to use minutes and seconds (mm:ss) instead of just hours and minutes (hh:mm).

If you want to have a better look at the DMN Editor, you can check the editor [here](dmn.new). :smile:

**Comment by mcarrano** [comment]
@ljmotta We had a similar request here: https://github.com/patternfly/patternfly-design/issues/1082. Looks like we can do this. Here was the reply on that issue from @nicolethoen 

> Adding seconds to the time picker might be a feature we could include. In that case, the user could still use the dropdown to include the hours and minutes as it already does, but I cannot imagine how it could include the seconds unless they were all .00 seconds. But - for a variant which includes seconds - if no seconds are manually typed by the user, then a trailing .00 seconds could be appended to the end of the time if selected from the dropdown and could be manually adjusted by the user typing them directly into the input.

Will that solution work for you? I can get this on our roadmap. Do you have an specific schedule requirements? Right now I am scheduling into Q1 of next year.

**Comment by ljmotta** [comment]
> Will that solution work for you?

This solution works for my case, giving the possibility to write the seconds it would be suficient. 

> Do you have an specific schedule requirements? Right now I am scheduling into Q1 of next year.

It sounds good to me. We don't have a schedule for this requirement.
