### ISSUE TITLE
Log Viewer: Support ansi escape character sequences: ie: ^M carriage return and color coding

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#6003]
**Describe the issue. What is the expected and unexpected behavior?**
Support ansi escape character sequences: ie: ^M carriage return and color coding
See https://issues.redhat.com/browse/CONSOLE-402

![image](https://user-images.githubusercontent.com/35978579/125114011-67338a00-e0b7-11eb-88a3-1c2bf072f401.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

**What is your product and what release version are you targeting?**
4.10

**Comment by jcaianirh** [comment]
Ben looked into some support libraries to achieve this here:
https://github.com/openshift/origin/issues/6931#issuecomment-180424619

I could see this being a toggle on/off especially if its a costly operation.

**Comment by jcaianirh** [comment]
not stale

**Comment by serenamarie125** [comment]
can we get this prioritized?  I know it's a need for Admin console, but we also have a number of requests on the Pipelines Log Viewer as well on the Dev side.
