### ISSUE TITLE
bug(Select): noResultsFoundText will never show in the typeahead variant when one of the options is a Divider component

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#6005]
**Describe the issue. What is the expected and unexpected behavior?**
Issue as described in the tittle. The empty state text should be shown if none of the options match, regardless if divider is used.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/competent-cherry-kiiqi?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug

**What is your product and what release version are you targeting?**
Cockpit, no workaround.

**Comment by michpetrov** [comment]
This is easy to fix when there are no results but I'm wondering what do in the case of empty groups, e.g.
![filtered](https://user-images.githubusercontent.com/1999074/127003263-76b66297-b32a-4bc1-a57d-7a9c87736163.png)
which doesn't look that great.
