### ISSUE TITLE
bug(VncConsole): Disconnect and 'Send Keys' buttons don't work

### ISSUE THREAD

**Issue by pcbailey** [patternfly/patternfly-react#6007]
The 'Disconnect' button in the VncConsole component of the react-console package should close the console when clicked and the included 'Ctrl+Alt+Del' option in the 'Send Keys' drop down menu should pass those keys to the console; but, currently neither option works.

**Comment by pcbailey** [comment]
@KKoukiou @yaacov Tracking the 'Disconnect' button issue here.

**Comment by evwilkin** [comment]
@pcbailey just to confirm - should this issue be closed out now that #6012 is merged?  Thanks!

**Comment by pcbailey** [comment]
@evwilkin That's correct!

**Comment by evwilkin** [comment]
Closed by #6012
