### ISSUE TITLE
PF4: "Danger" prefix in Alert title

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#601]
The Alert outputs the variant name in the title.

Example:
![screen shot 2018-09-05 at 4 53 12 pm](https://user-images.githubusercontent.com/17481322/45120480-3c1cd500-b12c-11e8-9833-daa0f5a110e9.png)

It seems odd to prefix an unlocalizable, "Danger:" string like this. I assume (from accessibleStyles.srOnly) that this is not intended to be seen?

```
const readerTitle = (
    <React.Fragment>
      <span className={css(accessibleStyles.srOnly)}>{capitalize(AlertVariant[variant])}: </span>
      {title}
    </React.Fragment>
  );
```

I don't see srOnly in @patternfly/patternfly-next/utilities/Accessibility/styles.css

**Comment by boaz1337** [comment]
I am sorry for the mess. But I think i found the source of our problem.
It seems like there was a patch made by Douglas 2 months ago which changes the way `class-names` are parsed (https://github.com/patternfly/patternfly-react/commit/0d2f9a64ebbfed1c32848248a3119f043d8ad7da#diff-7c877b1a11c14c3fb5eda62953dfb00bR37) and it was published in version `2.1.0` while `react-core` is using version `2.0.x`.

This is why we could find `uSrOnly` but not `srOnly` in `accessibleStyles`.
I tested this on my local machine and it seemed to be working correctly.

**Comment by dgutride** [comment]
The title is now configurable using the title attribute.  Moving to closed.

**Comment by dgutride** [comment]
Reopening - title is fixed but the screenreader/aria attributes need to be fixed still.
