### ISSUE TITLE
Refactor components/ build demos to use composable Menu + Toggle under the hood

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6014]
Avoiding breaking changes: i.e. don't change API and existing props

Build demos for the following:

- [x] #6017
- [x] #6018
- [x] #6019
- [x] #6016 
- [x] #6888
- [x] #7367

**Comment by tlabaj** [comment]
All related demos have been built out.  I am closing this issue and tracking implementation of new components in this epic
[Epic- Build next versions of menu like components](https://github.com/patternfly/patternfly-react/issues/8068)**
