### ISSUE TITLE
Spike: Draggable data list demos

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6020]
Could we use a third party library to implement a draggable data list and build a demo to demonstrate?
Ideally, we are not building our own draggable implementation, and we are not building the Data List component to have a 3rd party library built in.

**Comment by tlabaj** [comment]
Make sure that the library is accessible.  If not, we need to make sure that we can make the component accessible.

**Comment by kmcfaul** [comment]
Big features to look out for:

Dragging expandable lists / dragging items between expanded folders (i.e. nesting while dragging)
Dragging over a list with items that have varying heights
Keyboard accessibility or the ability to add some keyboard interactions to keep things accessible
Ideally flexible enough to work for both DataList and Table

I don't think any requests have come to drag between two separate lists/drop zones but may be a good feature to look out for as well.

**Comment by redallen** [comment]
Started a doc:

https://docs.google.com/document/d/e/2PACX-1vRWMiWKbGRbe9efkYeVq_xtOL6nBO1icjGqopIS7HfJaZ4jz2Wqw7D3VYWaa8Wsq_9anCGTRZ3W_7J_/pub

React-beautiful-dnd looks the most hopeful but it may be more work than further extending our own code.

**Comment by redallen** [comment]
There was a recent request on Slack to be able to drag between two different data lists:
![image](https://user-images.githubusercontent.com/47335686/127207953-d1ac0c24-7f14-4d0c-adc6-a4fb7919792b.png)

**Comment by redallen** [comment]
I opened #6074 to showcase a flexible basic demo and a two-dropzone demo using `react-beautiful-dnd`.

I personally think we should ask design how drag and drop interactions should work before deciding on a library. For example:
1. Should we preserve the current data list "ghost row" that makes it difficult to see what you're dragging or apply new styles?
2. Should we add dropzone styles to better clarify side-by-side data lists?
3. Should dragging an item up/down the page scroll the page?
4. Should we add animations?

Based on the answers to those questions (and how difficult adding proper a11y + keyboard interaction to the demos are) we can decide whether to modularize our current drag and drop implementation or add `react-beautiful-dnd`.

**Comment by redallen** [comment]
Closing in favor of https://github.com/patternfly/patternfly-design/issues/1077
