### ISSUE TITLE
Refactor Pagination to use Menu

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#6029]
Since the dropdown is not compassable in this component, we can not create a demo.  We will need to replace it under the hood.

**Comment by nicolethoen** [comment]
Part of the epic: https://github.com/patternfly/patternfly-react/issues/6014

**Comment by tlabaj** [comment]
Closing this issue.  The next version of pagination will use menu under the hood.  tracked in #8067

**Comment by nicolethoen** [comment]
Closed by #8319
