### ISSUE TITLE
Menu footer is not accessible via the keyboard

### ISSUE THREAD

**Issue by kdoberst** [patternfly/patternfly-react#6031]
**Describe the issue. What is the expected and unexpected behavior?**
When navigating the menu via the keyboard, the footer items are not accessible.  A user cannot use the tab nor the arrow keys to access buttons/links within the menu footer.

See: https://www.patternfly.org/v4/components/menu#with-footer

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Use the tab key to navigate to the menu.  The first tab key should put focus on a menu item.  The second tab key should put focus on the menu footer item(s)

Actual:
The menu footer items are skipped.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug.  Blocker.  Workaround is to not use the menu footer and create a series of custom CSS.

**What is your product and what release version are you targeting?**
Openshift Console 4.9

**Comment by tlabaj** [comment]
Hi @kdoberst this is a know issue that is being addressed in our next sprint.
https://github.com/patternfly/patternfly-react/issues/5772

**Comment by tlabaj** [comment]
@kdoberst  the issue linked above actually for the select.  This PR has resolved the issue with the Menu.  It will be available with our next release. #5972

**Comment by tlabaj** [comment]
closed by #5972
