### ISSUE TITLE
Incomplete date entered by text input is parsed as valid date for DatePicker

### ISSUE THREAD

**Issue by mslwang** [patternfly/patternfly-react#6036]
**Describe the issue. What is the expected and unexpected behavior?**

When we enter in a date into the DatePicker by text input, the date value we're provided as a second argument automatically converts it to the first valid date it sees, which doesn't necessarily come from an ISO-formatted date. While this might be its expected behaviour, I don't think it's useful when DatePicker mainly uses ISO-formatted dates when selected with the picker.
The expected behaviour would be for it to wait until you have entered in a full ISO date to be valid.

https://github.com/patternfly/patternfly-react/blob/aac2e7cf90ea46337ed5bd630beb84209b8551cd/packages/react-core/src/components/DatePicker/DatePicker.tsx#L100

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Here's a link to a sandbox containing the issue. 
https://codesandbox.io/s/optimistic-shaw-egk7w?file=/index.js
If you type in 2021 into the datepicker box, with this.state.date tracking the current value, we see that the date outputted is 2021-01-01.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

This is a bug. The workaround is just to use the raw value (the first parameter in https://github.com/patternfly/patternfly-react/blob/aac2e7cf90ea46337ed5bd630beb84209b8551cd/packages/react-core/src/components/DatePicker/DatePicker.tsx#L101), but I feel like that makes the second parameter obsolete.

**Comment by redallen** [comment]
You can change the default `dateParse = (val: string) => new Date(`${val}T00:00:00`),` to an implementation you want like:
```js
function dateParse(val) {
  const split = val.split('-');
  if (split.length !== 3) {
    return;
  }

  return new Date(`${val}T00:00:00`);
}
```

@mcarrano Would you expect `2021` or `2021-01` to be valid dates equivalent to `2021-01-01` in a DatePicker?

**Comment by mcarrano** [comment]
I don't think so @redallen . Seems like the date needs to map to a valid calendar day.

**Comment by redallen** [comment]
Incomplete dates do map to the first valid calendar day in the given year (and month, if specified): 
![image](https://user-images.githubusercontent.com/47335686/125838596-11be4ad2-ddf5-4c60-9eb3-c46e08fb6bef.png)

I've opened #6039 which requires the input format to be y-m-d for you to play around with @mcarrano .

**Comment by mslwang** [comment]
> Incomplete dates do map to the first valid calendar day in the given year (and month, if specified):
> ![image](https://user-images.githubusercontent.com/47335686/125838596-11be4ad2-ddf5-4c60-9eb3-c46e08fb6bef.png)

I encountered this as well for javascript, but I think validity within the language shouldn't reflect to validity in purpose here. I don't think it follows the y-m-d standard correctly, which is what we see from the date, so it can come off as confusing.

**Comment by redallen** [comment]
> so it can come off as confusing

I understand `"2021"` parsing to `2021-01-01` can be confusing. However, it can also be a useful shortcut to some consumers. While it doesn't technically conform to ISO399 (which was meant for writing datetimes unambiguously), neither does `2021-01-01`!

> I don't think it follows the y-m-d standard correctly

ISO8601 requires not only `y-m-d`, but also the time delimiter "T", minutes, seconds, milliseconds, and a timezone. That's rather long to put in an html `<input>`. For that reason the [ECMA standard](https://262.ecma-international.org/11.0/#sec-date.parse) requires only a year and makes the rest optional:

> When the MM or DD elements are absent, "01" is used.

In our designs for DatePicker the American "mm/dd/yyyy" format was used everywhere. Given that ECMA allows `yyyy` or `yyyy-mm` I'll leave it up to @mcarrano whether we should disallow parsing those by default due to possible confusion although the spec allows them.

**Comment by mcarrano** [comment]
From a usability perspective I could argue two ways. Yes, it's nice to have a shortcut, but it could also be unexpected if I accidentally hit enter without completing the string and don't get an error. Should it be possible to configure the component to require an exact date or not @redallen ?

**Comment by redallen** [comment]
It's possible by passing ```dateParse={val.split('-').length === 3 && new Date(`${val}T00:00:00`)}``` like in #6039.
