### ISSUE TITLE
Datepicker does not remove error text as soon as you make modification

### ISSUE THREAD

**Issue by mslwang** [patternfly/patternfly-react#6054]
**Describe the issue. What is the expected and unexpected behavior?**
The DatePicker component does not remove the error message that appears after submitting an invalid date when the user starts modifying the text input. The expected behaviour from a UI signalling perspective is that as soon as a user starts modifying their input, no errors should be shown because we're not in the state immediately preceding the validation of an invalid date.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Using this [link](https://codesandbox.io/s/happy-moore-udy07), try typing an arbitrary string that isn't a valid date and press enter. Then try to start changing the input.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug, but not a blocker. 

A potential solution is to add `setErrorText('')` to the onTextInput function https://github.com/patternfly/patternfly-react/blob/aac2e7cf90ea46337ed5bd630beb84209b8551cd/packages/react-core/src/components/DatePicker/DatePicker.tsx#L95

**Comment by redallen** [comment]
I'm not sure what design expects. cc @mcarrano

**Comment by mcarrano** [comment]
@redallen I'm comparing this behavior with what we are doing for general form field validation. See the example here: https://www.patternfly.org/v4/components/form#invalid  In the case of a standard text input, the error message is cleared once the invalid input value is cleared (but remains as long as there is an invalid entry in the field). It's not necessary to wait until a valid entry has been entered to clear the field. For consistency, I think this should work the same way. Do you agree?

**Comment by redallen** [comment]
Yes, there are 2 differences between DatePicker and TextInput validation:
1. DatePicker validates `onBlur` and pressing enter, while TextInput validates every keystroke in `onChange`
2. DatePicker internally validates that it can parse the date while the consumer decides how to validate a TextInput

> It's not necessary to wait until a valid entry has been entered to clear the field.

Do you mean clear the helper text? On what condition should it be cleared? I've opened #6066 which clears it on **any** text input as @mslwang suggested for you to review.

**Comment by mcarrano** [comment]
@redallen Thanks for making that update and clarifying how this differs from a standard text field. I think what you've modeled in the PR is better. @mslwang what do you think?
