### ISSUE TITLE
Allow switch to be on the right of the label

### ISSUE THREAD

**Issue by kdoberst** [patternfly/patternfly-react#6059]
**Describe the issue. What is the expected and unexpected behavior?**
Add a prop to have the switch to the right of the label. 

Example in use:
<img width="200" alt="Screen Shot 2021-07-20 at 3 42 52 PM" src="https://user-images.githubusercontent.com/82059948/126420149-c6a04456-9f01-41ae-9bcb-106b5f837b95.png">

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Example with custom css: https://codesandbox.io/s/magical-https-osqup?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement.  Workaround is to add custom SCSS

**What is your product and what release version are you targeting?**
OpenShift 4.9

**Comment by tlabaj** [comment]
cc @mcoker

**Comment by tlabaj** [comment]
cc @mcarrano

**Comment by CooperRedhat** [comment]
Core PR before react change [#4235](https://github.com/patternfly/patternfly/pull/4235)

**Comment by mcarrano** [comment]
@kdoberst I think that it should be possible to do what you want without making this change. The text to the right of the switch is designed to reflect the state of the switch (i.e., off or on) and not for use as a static label. But you should be able to place an unlabeled switch to the right of a static text label. @mcoker am I getting this right? Can the menu above be created with existing components? If not, what's the best way to enable this?

**Comment by mcoker** [comment]
> Can the menu above be created with existing components? If not, what's the best way to enable this?

@mcarrano if we want to support the existing switch behavior, look/feel, etc, this core change is the best way to do it. The way the switch component is built

* Our component associates the switch with the label (the label is built into the component), so that if you click on the label it toggles the switch
* Clicking on the switch swaps the text shown
* We handle the correct spacing/alignment
* If you use the switch without its built in label, you get a check mark in the switch

If a user wanted to hook this up on their own using an external label, they would need to try and replicate all of that and remove the check somehow to be consistent with other switches that might be on the page or on another page.

**Comment by mcarrano** [comment]
Thanks @mcoker . So maybe then the question is what the expected interaction here is @kdoberst . Is the intent that clicking anywhere on the label will toggle the state, i.e. does "Show system projects" change to "Hide system projects" or something like that? Or is the intent that the text to the left is just a label for the control?

**Comment by kdoberst** [comment]
> Is the intent that clicking anywhere on the label will toggle the state, i.e. does "Show system projects" change to "Hide system projects" or something like that? Or is the intent that the text to the left is just a label for the control?

@mcoker @mcarrano. The answer is both.  From an accessibility perspective, the label text (what is shown to the user) needs to be associated with the underlaying checkbox. 

From a user's perspective when a user mouse clicks on the label it will change the state of the switch and the text displayed to the user (if shown).

In short, I need for the switch to behave exactly how it does, but just move the text to the left and the actual switch to the right.  If it would help, I can make the example (https://codesandbox.io/s/magical-https-osqup?file=/index.js) into a more fully working switch.

As a side note,  if I add a switch with missing or empty label attribute(s) the component creates a label tag with no text.  This is would be extremely confusing for assistive technology users.  I would recommend that the label attribute be required but at the very least highly recommended.

**Comment by mcarrano** [comment]
@kdoberst Thank you for this detailed explanation. So yes, I see how this makes sense.

@mcoker assuming that we merge the PR into the current core release, I can get this on our React roadmap for the upcoming sprint. @kdoberst can you remind me what the freeze dates are for OS 4.9?

Also, @jessiehuff see this comment:

> As a side note, if I add a switch with missing or empty label attribute(s) the component creates a label tag with no text. This is would be extremely confusing for assistive technology users. I would recommend that the label attribute be required but at the very least highly recommended.

Is there something we should address to improve accessibility?

**Comment by mcoker** [comment]
> @mcoker assuming that we merge the PR into the current core release, I can get this on our React roadmap for the upcoming sprint.

@mcarrano, we should be able to get this change in on the react side this release. @CooperRedhat will be working on it and says it's pretty straight forward.

**Comment by CooperRedhat** [comment]
> > As a side note, if I add a switch with missing or empty label attribute(s) the component creates a label tag with no text. This is would be extremely confusing for assistive technology users. I would recommend that the label attribute be required but at the very least highly recommended.
> 
> Is there something we should address to improve accessibility?
    
https://github.com/patternfly/patternfly-react/blob/3b1cb922e21d499d566b4bc5d87d580a699cca66/packages/react-core/src/components/Switch/Switch.tsx#L42-L45

@jessiehuff  It looks like we are handling the empty label case by throwing an error in the console when the `aria-label` is also not supplied.
