### ISSUE TITLE
Label: editable labels with inline edit icons + confirm/cancel icons

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#6088]
Add a variant of editable label that uses icons in its interaction opposed to direct interaction with the editable div. The inline edit icon should be used to toggle the editable div and while actively editing, the icon should be replaced by confirm and cancel icon buttons that will respectively complete or cancel an edit.

**Comment by mcarrano** [comment]
Note: I've opened a design issue here to explore this experience and make some recommendations: https://github.com/patternfly/patternfly-design/issues/1073

**Comment by mcarrano** [comment]
Based on more discussion with the design team, I'd like to put this on hold until we have more feedback about editable labels and determine if we need these additional affordances.
