### ISSUE TITLE
PF4 Dropdown does not hot reload in the workspace

### ISSUE THREAD

**Issue by michaelkro** [patternfly/patternfly-react#609]
Currently, modifications made to any of the `Dropdown` components and subcomponents are not being hot loaded into the workspace.  For instance, I modified the return value of `DropdownItem.js` with an extra `<div>`

```js
   return (
    <Component
      {...aditionalProps}
      className={css(isDisabled && styles.modifiers.disabled, isHovered && styles.modifiers.hover, className)}
      role={role}
    >
      <React.Fragment>
        {children}
        <div>hello</div>
      </React.Fragment>
    </Component>
  );
```

I cannot see these changes in the workspace UI without having to stop my development server and totally rebuilding the project.

@karelhala, ping :)

**Comment by dmiller9911** [comment]
This is likely the issue: https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/Dropdown/examples/DirectionUpDropdown.js#L2 this should be from `@patternfly/react-core'
