### ISSUE TITLE
Feature request: add copy & paste support to the react console

### ISSUE THREAD

**Issue by Verhoeckx** [patternfly/patternfly-react#6092]
According to the [feature list of noVNC](https://github.com/novnc/noVNC) they support `Clipboard copy/paste`.
I think it would be great if this could be added to the Patternfly React Console.

Why? This way I could use it in the VNC console in [Cockpit](https://cockpit-project.org/) :-).

Disclaimer: I don't know much about noVNC and the Patternfly React Console. I just ask for this feature request after a short discussion on [the Cockpit Discussion list](https://github.com/cockpit-project/cockpit-machines/discussions/293).

**Comment by KKoukiou** [comment]
Thanks for reporting this.

**Comment by Verhoeckx** [comment]
It seems still a good idea to me!

**Comment by WardPearce** [comment]
bump

**Comment by WardPearce** [comment]
still relevant

**Comment by mackncheesiest** [comment]
bot pls no

**Comment by beachrunner2k** [comment]
following in case this ever get's reopened

**Comment by megabitsenmzq** [comment]
still relevant

**Comment by dylancm** [comment]
still relevant still
