### ISSUE TITLE
Investigate why JAWS and NVDA have odd interaction with editable label

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-react#6096]
**Describe the issue. What is the expected and unexpected behavior?**
When using JAWS and NVDA, they require two enter key presses in order to interact with the editable label. I'm curious why this is happening, and if there is a way to make it simpler/more straight forward for users. I worry that screen reader users wouldn't think to press the key twice to interact with it. 

My current theory is that perhaps screen readers are opening up a different mode (like forms mode) when pressing enter initially and then they have to press it again to get the interaction. Not sure how to get around this yet.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Could be argued as either. Technically it's accessible so you could argue that this is an enhancement, but I think that users who come across this would think it's a bug.

**Comment by tlabaj** [comment]
This might have something to do with the div contentEditable
