### ISSUE TITLE
Select typeahead variant doesn't map data-testid to it's input control and it ought to

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-react#6107]
**Describe the issue. What is the expected and unexpected behavior?**

In other variants the Select component maps a `data-testid` prop to the control.  However when using the typeahead variant, no mapping is done, so as a random example:

```
        <Select
          variant={SelectVariant.typeahead}
          data-testid={id}
          id={id}
          aria-label={props.property.displayName || props.field.name}
          title={props.property.controlHint}
        >
```

yields this markup which doesn't have `data-testid` set like I'd expect:

![image](https://user-images.githubusercontent.com/351660/127907057-219fbe0b-f0d1-4636-9acb-c47da2968213.png)

Unlike the regular select:

![image](https://user-images.githubusercontent.com/351660/127907170-71758dcb-d15d-4981-841b-6aa0232eb91e.png)

It'd be nicer if the typeahead variant worked the same way.

**Comment by KKoukiou** [comment]
@gashcrumb the data-testid (or any other random prop) that you pass is actually present in the DOM attached to pf-c-select__menu element. For the typeahead and any other implementation in https://www.patternfly.org/v4/components/select it's the same.
The second example you posted is from https://www.patternfly.org/v4/components/form-select which indeed is a pure select - option and has the custom properties attached to the select.
