### ISSUE TITLE
dual list selector does not allow for sub folder selection

### ISSUE THREAD

**Issue by ddonahue007** [patternfly/patternfly-react#6124]
**Describe the issue. What is the expected and unexpected behavior?**
When there is a nested folder you can not select the subfolder and have its children selected. It is not possible to select the subfolder at all. 

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
This is easily reproduced in the examples here
https://patternfly-react.surge.sh/components/dual-list-selector/#expandable-options-with-checkboxes

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug
**What is your product and what release version are you targeting?**
Cost Management

**Comment by tlabaj** [comment]
closed by #6180
