### ISSUE TITLE
Also support text for ToggleIcon in ToolbarToggleGroup

### ISSUE THREAD

**Issue by marusak** [patternfly/patternfly-react#6140]
**Describe the issue. What is the expected and unexpected behavior?**

Currently it is possible to specify `ToggleIcon` for `ToolbarToggleGroup` e.g.:
```js
<ToolbarToggleGroup toggleIcon={<FilterIcon />} breakpoint="md">
```
 This renders the icon, but it feels hardly discoverable, would be very useful if it would be possible to also specify text to go with it. 

A local workaround I have:
```js
<ToolbarToggleGroup toggleIcon={<><span className="pf-c-button__icon pf-m-start"><FilterIcon /></span>{_("Toggle filters")}</>} breakpoint="md">
```
and with `.scss`:
```
.pf-c-toolbar__toggle {
    .pf-c-button.pf-m-plain {
         color: unset;
    }

    svg {
        color: var(--pf-c-button--m-plain--Color);
    }
}

```
yields:
![Screenshot from 2021-08-06 14-56-55ff](https://user-images.githubusercontent.com/12330670/128513663-eb9ae8a2-64a6-438e-ac60-5b12f3d7c6f0.png)

Is there simpler way already?

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

enhancement

**What is your product and what release version are you targeting?**

**Comment by KKoukiou** [comment]
@mcarrano what do you think about this? Do you belive that the toggle icon alone by itself is discoverable enough?

**Comment by mattnolting** [comment]
@mcarrano You're correct, the intention of the toggle is to conserve space where space is limited (mobile view). But by all means, if you've planned for the mobile view and the desired text fits without obstructing other elements, you could certainly use another type/style of button. 

As per the coding approach, React would probably want to make `ToggleGroup` composable to support this request.

**Comment by mcarrano** [comment]
@marusak @KKoukiou Do you need anything else from us here? If not, I'd like to close this.
