### ISSUE TITLE
JumpList will not highlight last item when selected

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#6156]
**Describe the issue. What is the expected and unexpected behavior?**

**Expected behavior**
When clicking the last item in the JumpList we scroll to the section and it is highlighted.

**Actual behavior**
When clicking the last item in the JumpList we scroll to the section but it's not highlighted.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
1. Visit the [PatternFly documentation](https://www.patternfly.org/v4/components/jump-links)
2. Click the last item in the table of contents to the right.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
It's a bug, it's not blocking but just a bit annoying for the user. 

**What is your product and what release version are you targeting?**
Keycloak Admin console, original issue can be found there (https://github.com/keycloak/keycloak-admin-ui/issues/960).

**Comment by tlabaj** [comment]
cc @mcarrano thoughts

**Comment by mcarrano** [comment]
I understand why this is happening, but it does feel like a bug. @redallen is there a way to change this so when you click an item, the highlight always goes with that item, even if the scroll position would not automatically make that the selected item?

**Comment by redallen** [comment]
Yes, but then as soon as the page scrolls you'll be back to the old behavior.

Right now scrollspy highlights the first visible element in the scroll region. It sounds like what you're asking for is to not do that, but instead clamp elements at the beginning or end of the list based on the viewport height. That's a hard problem to solve requiring some math on how to clamp them.
