### ISSUE TITLE
Introduce 'Back to top' component and demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6166]
Back to top is a floating button that, when clicked, scrolls the user back to the top of the page. The component should include a demo that shows how this behaves in the context of a page.

Core issue: https://github.com/patternfly/patternfly/issues/4255

**Comment by mcarrano** [comment]
@jessiehuff can you take a look at this one from an a11y standpoint? The designs are attached to the core issue. We are wondering how the user would navigate to this via the keyboard.

**Comment by jessiehuff** [comment]
In terms of keyboard navigation, it will be in order of wherever it appears in the DOM. I imagine that in this case it would be important for us to place this at the bottom of whatever content that the user is scrolling back to the top of. I think we should include documentation about this as well.
