### ISSUE TITLE
Select, error using typeahead with multiple children

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-react#6173]
**Describe the issue. What is the expected and unexpected behavior?**
When the select component contains multiple children typing anything into the typeahead field will cause an error (Maximum update depth exceeded). Caused by #6052

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/mystifying-morning-e102r

The issue happens only when there is an explicit `<SelectOption>` combined with a mapped array.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. Can be worked around by putting all options into a single collection.

**What is your product and what release version are you targeting?**
N/A

**Comment by elad661** [comment]
I can reproduce this issue in OCM even with a select that *isn't* a typeahead. 

in this example, https://codesandbox.io/s/funny-water-78t97
open the select, don't select anything, and click on the document to close it. The same crash will occur.
