### ISSUE TITLE
Refactor DashboardWrapper, Page demos to use Masthead (over PageHeader)

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#6174]
DashboardWrapper and full page demos that still include PageHeader should be refactored to use the Masthead component instead.

**Comment by kmcfaul** [comment]
Follow up to #6170

**Comment by nicolethoen** [comment]
Also, there is an advanced core demo introduced in this PR that would likely demonstrate the same things as this wrapper
 https://github.com/patternfly/patternfly/pull/4211
