### ISSUE TITLE
Spike: Query builder

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6211]
Several products have asked for the ability to define complex Boolean queries. We should perform some investigation into what PatternFly can/should provide in that regard. There is a corresponding design issue open here: https://github.com/patternfly/patternfly-design/issues/972

**Comment by nicolethoen** [comment]
I personally feel like PatternFly should stay out of the game of parsing strings as much as we are able.

Possibly we could create a demo which uses a composable advanced search form. The search input could open a form inside a popover which includes input fields for something like: 'Includes ALL words:', 'Includes SOME words:', 'Excludes words:', etc... to demonstrate how a consumer might get the pieces needed to construct query strings?

For the sake of a consistent Red Hat experience, it makes sense to have an official query string building solution, but it is probably not something that should come out of a design system. It might only have a patternfly related solution in an extension?

Unless there is a magical third party library that can solve some of this for us - I have not done research yet.
