### ISSUE TITLE
DualListSelector: support list of objects as options

### ISSUE THREAD

**Issue by xprazak2** [patternfly/patternfly-react#6213]
**Describe the issue. What is the expected and unexpected behavior?**

`availableOptions` and `chosenOptions` props have the type `React.ReactNode[] | DualListSelectorTreeItemData[]`. When using basic select (no tree/checkboxes), I would like to pass array of objects as available and chosen options.

The use case is to separate what is presented to user for selection and how the items are identified. We often want to present a user-friendly name while keeping track of the items by id.  

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

```js
const available = [{ id: 'xyz', name: 'First available' }, { id: 'pqr', name: 'Second available' }]
const chosen = [{ id: 'abc', name: 'First chosen' }]

<DualListSelector
  availableOptions={available}
  chosenOptions={chosen}
/>
```

A posiblilty is to use a formatter function: `{ id: 'abx', toString: () => "Pretty name for users" }`

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Enhancement

**Comment by tlabaj** [comment]
cc @nicolethoen

**Comment by nicolethoen** [comment]
I think this can still happen - @xprazak2 is this still something you need?

**Comment by xprazak2** [comment]
@nicolethoen, there is no urgent need, it is an enhancement that would make it easier to use the component.

**Comment by nicolethoen** [comment]
For now, there is a way to pass more data to available or chosen options in a dynamically generated DualListSelector.
You will always have more flexibility if you build your Dual List Selector composably, but I've created a code sandbox to demonstrate how to pass more information to your Dual List Selector items.
https://codesandbox.io/s/nifty-wave-z4ppuj?file=/index.js
