### ISSUE TITLE
PF4 Toolbar demo

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#622]
Add the PF4 Toolbar demo: https://pf-next.com/demos/Toolbar/examples/

Note: there is still a to-do to update the toolbar demo on core with the select component once that has been introduced. See related issues: 
* Add select: https://github.com/patternfly/patternfly-next/issues/708
* Update toolbar with select: https://github.com/patternfly/patternfly-next/issues/709

In addition to a React review, this issue should be reviewed by the core contributors of this demo: 
* CSS: @christiemolloy 
* Design: @mcarrano

**Comment by amarie401** [comment]
The PR for this issue has been merged. See #755
