### ISSUE TITLE
Add custom PF-icons to PF4

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#623]
Once PF4-Core has added pf-icons, PF-React can take those SVG and load it.
Currently blocked by core issue here: https://github.com/patternfly/patternfly-next/issues/730

**Comment by karelhala** [comment]
I'll add documentation about how to add custom icons to react-icons so other can contribute as well.

**Comment by LHinson** [comment]
Thanks @karelhala! I'm going to close out this issue.
