### ISSUE TITLE
@patternfly/react-code-editor warning when installing from scratch

### ISSUE THREAD

**Issue by riccardo-forina** [patternfly/patternfly-react#6244]
I just noticed this warning when performing a full install of the deps from a project of mine where I nuked the yarn.lock file.

```
warning @patternfly/react-code-editor > react-dropzone > attr-accept > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

It looks like the version of [react-dropzone in use](https://github.com/patternfly/patternfly-react/blob/main/packages/react-code-editor/package.json#L36)(9.0.0) is quite old, it being released [on 22 Feb 2019](https://github.com/react-dropzone/react-dropzone/releases/tag/v9.0.0). The latest version is 11.3.4.

**Comment by tlabaj** [comment]
Closing.  This will be resolved with #6611
