### ISSUE TITLE
Select: clicking twice Enter in the typeahead variant will select the first entry

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#6245]
**Describe the issue. What is the expected and unexpected behavior?**

Use this example code. https://www.patternfly.org/v4/components/select/#typeahead
Select New York. Click enter (this will open the dropdown, and enter again. This will close the dropdown menu and select Alabama which is the first entry in the menu.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Unclear if this is a bug or expected behavior. 
Personally I would expect enter to open and close the menu and leave the selected option untouched, but feel free to close if this is already the desired behavior.

**What is your product and what release version are you targeting?**
Cockpit Machines.

Related BZ https://bugzilla.redhat.com/show_bug.cgi?id=1994867

**Comment by tlabaj** [comment]
cc @jessiehuff @mcarrano

**Comment by nicolethoen** [comment]
@mcarrano could you add this to a milestone?
