### ISSUE TITLE
Filterable table demo updates

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#6262]
Spotted in this demo - https://www.patternfly.org/v4/components/table/react-demos#filterable. Seems like we should exclude the checkbox in the body if there is an empty state result.

<img width="879" alt="Screen Shot 2021-09-02 at 1 22 40 PM" src="https://user-images.githubusercontent.com/35148959/131896761-dba96d07-4609-40c2-a140-a0a318b4c421.png">

Also the dropdown toggle text and left icon are a little close. We could pass the toggle icon as an `icon` prop to the toggle instead. It would look like this:

<img width="425" alt="Screen Shot 2021-09-02 at 1 33 30 PM" src="https://user-images.githubusercontent.com/35148959/131898210-f980b7a2-ef70-4161-9fee-b9c08d5d90d2.png">

**Comment by nicolethoen** [comment]
It seems that the checkbox has been removed, but the dropdown icon positioning could still be updated.
