### ISSUE TITLE
Dual list selector: Enable optional drag and drop reordering of selected items

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6265]
Want to enable items in the right-hand list to be manually ordered via drag & drop per the design here:

![image](https://user-images.githubusercontent.com/6619860/132056541-0f41537a-0b5b-49d9-a3a7-220ba6c5c1d6.png)

**Comment by garrett** [comment]
Would this be affected by https://github.com/patternfly/patternfly-react/issues/5910 when heights of the items are different? (Basically: Asking if the implementation needs to be fixed for draggables at a lower level too. Even if draggable is buggy with different heights here as well, it shouldn't stop this from being implemented.)

**Comment by redallen** [comment]
@garrett I've created a new DragDrop component which doesn't have the existing DataList bug of items with different heights. I believe Dual list selector will use this implementation.

**Comment by garrett** [comment]
@redallen: That's great to hear!

(Do you think the DataList might be ported to this new DragDrop component too, in the future?)

**Comment by redallen** [comment]
Yes, that's one of the first things we want to do before releasing the component to consumers.
