### ISSUE TITLE
Feedback on TreeView

### ISSUE THREAD

**Issue by ianw** [patternfly/patternfly-react#6268]
Hello,

The beta component requests feedback so I thought I would provide it.

I have recently re-implemented https://zuul.opendev.org/t/openstack/jobs using TreeView

The change is https://review.opendev.org/c/zuul/zuul/+/804956

Our CI provides a "live" view of this.  If you go to the above change and select "Zuul Summary -> zuul-build-dashboard-opendev" that will take you to a job run, and then select "artifacts -> site preview".  Then click on "Jobs" next to "openstack"

The biggest problem is probably performance for expansion.  

Firstly I wanted to emulate the old page by bringing it up already fully expanded.  That killed the browser (setting `allExpanded` by default).  If it would be helpful, I could propose a change with this enabled and using the live preview model above it could be profiled to see if there is anything that can be done.

I had to make the search only start completing after 6 characters, because trying to expand when you're typing just a few characters kills the browser.  This makes sense; I mean tying a vowel like "a" is basically the same as expanding the entire tree, the issue above.  One thought was perhaps there could be an example of taking the key inputs in the search box, and not triggering the filtering update until maybe 1 second after the last keypress or something?  basically give you time to type in your value before searching.  Or, I guess there should be a search model that is more -- synchronous?  As in it doesn't start searching until a button is pushed, and puts up a spinner. I could not really see that the "Search Input" has a way to do this, although I'm sure it's possible (an example would help :)

The other issue was the extant page has a "flat" view.  When I tried doing this -- flattening the input tree -- the browser totally died (I think it's about 5000 entries; with no children obviously in flat mode).  On the original page clicking it takes a few seconds.

If providing the underlying data as a json, or making changes and providing a site preview will help maybe diagnose anything we can do; please let me know.

On the search bar 

* it would be good to expand the documentation so that it's clear `searchProps` is the argument to the `Search Input` component.  It took me a while to figure out that I could use `placeholder` here.  It would probably be useful to add this to the example.
* I couldn't figure out how to get the `X` to clear the current search icon to come up?  I think it would be good if this just happened by default, or the examples showed how to make this work.

None of the examples showed putting `React.Fragments` in the `name` field.  So in my `onSearch` event I'm matching against the `id` (because `name` is a bunch of react objects).  Maybe this is "assumed knowledge" but again, an example of items with a badge next to them or something might be good.

I think it looks good though!  Hoping to get it through review and into production soon.

**Comment by nicolethoen** [comment]
May be related to this issue: https://github.com/patternfly/patternfly-react/issues/6314

**Comment by mturley** [comment]
This doesn't address the performance issues, but ever since https://github.com/patternfly/patternfly-react/pull/6133 (released in `@patternfly/react-core@4.152.4`) we have removed `onSearch` and `searchProps` in favor of passing in a custom `toolbar`, which can include the `TreeViewSearch` component with whatever custom props you need for your search input. I think you could use this approach to achieve the more synchronous search behavior you mention, if you want to. See the updated example code here: https://www.patternfly.org/v4/components/tree-view#with-search

**Comment by ianw** [comment]
@kmcfaul thanks; I have to update our example for the recent changes to the search bar; will update when i have something to look at.  I'm currently hitting an issue with the search that it doesn't expand everything (https://github.com/patternfly/patternfly/issues/4395)

@mturley Thanks I'm updating to this now. Is there a reason this search input doesn't use a ... SearchInput?  Currently it has no way to clear the search, where as the search box has a "X" to clear when you type, and match counts, etc.  This seems a better match for the filtering that's happening.

I also note in the TreeView example page with the new ToolBar search; if you search "current" it doesn't actually expand to the node with "Current" in it, e.g.

![Screenshot 2021-09-22 at 16-02-10 PatternFly 4 • Tree view](https://user-images.githubusercontent.com/108448/134291147-cb3d078a-5f86-46ac-87da-2c0e4862f8c5.png)

(this may be related to prior issue?)

**Comment by kmcfaul** [comment]
I've got a PR up for bug with `allExpanded` (#6326) - to workaround & test in the meantime you need to also set `defaultAllExpanded` (or just use `defaultAllExpanded`).

`SearchInput` was implemented after `TreeView` and I think also after the refactor that took out the toolbar. We wanted the current `TreeView` example to maintain the same look and styling as well.

Yeah I think the search for "current" in the example is hitting same the `allExpanded` bug.
