### ISSUE TITLE
Hoverable/selectable datalist + table rows not VO accessible

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6295]
How will we notify screen reader users that the item is selectable or selected. I've often questioned this in other components as well such as with the Selectable Datalist. With that one though, we had it in the name of the example so it at least had some indication that it was selectable (perhaps not an ideal solution though).

**Comment by tlabaj** [comment]
@mcarrano can you please add this one to a milestone

**Comment by wise-king-sullyman** [comment]
I'm addressing the table portion of this issue under this issue number and creating a separate issue for the datalist portion.
