### ISSUE TITLE
Nav: Add drill-down menu variant and demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6299]
Add a new drill-down menu variant. Core PR: https://github.com/patternfly/patternfly/pull/4364

We should also include a demo to reflect how this can be applied to a vertical navigation. Here is a reference to the design: https://www.figma.com/proto/AJi4XmCkrdGEK532YmbAqH/tertiary-nav?node-id=54%3A2191&scaling=min-zoom&page-id=53%3A2106

**Comment by jeffpuzzo** [comment]
FYI, I spoke with @mattnolting, and we agreed that no changes need to be made to the existing `Nav` component since `Menu` already possesses the drilldown variant. 

I've marked the change that addresses this issue as a chore since an example and demo were added without any new features.
