### ISSUE TITLE
@patternfly/react-core@1.12.0 release kills pf-c-card background color var

### ISSUE THREAD

**Issue by AllenBW** [patternfly/patternfly-react#630]
`--pf-c-card--BackgroundColor:var(--pf-global--BackgroundColor--light-100);`

is missing from 1.12.0 😭 or something like that, cards that were once with a white background now are transparent 😱 😭 

Will update issue if any new information comes to light

**Comment by AllenBW** [comment]
Well there's this... https://github.com/patternfly/patternfly-react/commit/4b213fbdb05fe3054293357f51394d2b2be859d1#diff-284fa961c9780f103254ba5caa89ee2cL9

but that's only a test 🤔

**Comment by AllenBW** [comment]
Also noticed the storybook is only on Version: 1.11.0 sooooooooo... can't see if the issue materializes there....

**Comment by AllenBW** [comment]
Or maybe this is cuz https://github.com/patternfly/patternfly-react/commit/4b213fbdb05fe3054293357f51394d2b2be859d1#diff-36a83b862d91d6316f0c91a8bfb55888R44 and on snap, there it is
https://github.com/patternfly/patternfly-next/releases/tag/v1.0.44

gonna pr for this fix

**Comment by andresgalante** [comment]
Hi @AllenBW you are right, the background was commented out by mistake.

It was fixed here: https://github.com/patternfly/patternfly-next/pull/734

You might notice that we are not forcing the card to be alway light anymore. Now, with this new addition, if you place a card within a dark container (like a dashboard) it turns transparent dark background and white typography.

**Comment by AllenBW** [comment]
Yep! @andresgalante did catch the fix, mentioned it in the above comment, thanks for the tidbit about background!
