### ISSUE TITLE
Typeahead Multi Select: closes after select

### ISSUE THREAD

**Issue by MariaAga** [patternfly/patternfly-react#6321]
**Describe the issue. What is the expected and unexpected behavior?**
After selecting one item in the select the select box closes, instead of staying open so the user can select more items.
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Could not reproduce in codesandbox
https://github.com/MariaAga/foreman_remote_execution/blob/add-hosts-selection-job-wizard/webpack/JobWizard/steps/HostsAndInputs/HostSelect.js

**What is your product and what release version are you targeting?**
using `"@patternfly/react-core": "4.128.6"`

From what I see the issue is that in 
https://github.com/patternfly/patternfly-react/blob/212bd9ede00cf57eb6180d785f42cc5e78af29e4/packages/react-core/src/components/Select/SelectToggle.tsx#L95-L103

`event.target` has the `pf-m-selected` class and icon but the item in menuRef doesn't have that class.
So event.target=
``` html
<button class="pf-c-select__menu-item pf-m-selected" role="option" aria-selected="true" type="button">
item<svg ... />
</button>
```
and menuRef.current.children[1].children[0]=
``` html
<button class="pf-c-select__menu-item" role="option" aria-selected="true" type="button">
item
</button>
```
So on click `onToggle(false)` is called

**Comment by tlabaj** [comment]
Hi @MariaAga Can you please provide a codePen or a way for us to reproduce?  We will need to reproduce to test a fix.

**Comment by MariaAga** [comment]
Found the reason. This only happens when `onFilter` is defined with `typeaheadMulti`.
In this example: https://www.patternfly.org/v4/components/select/#multiple-with-custom-objects 
It doesn't happen because `this.customFilter` is `undefined`.
Example where it does happen:
https://codesandbox.io/s/typeaheadmulti-with-onfilter-oibfn?file=/index.js

**Comment by tlabaj** [comment]
Thank you!  we will take a look.

**Comment by MariaAga** [comment]
@rbertucat yeah, you're right, then I can't reproduce it in a codesandbox. But I don't have a set `isOpen` in my code.
The only things that changes isOpen is onToggle ` <Select onToggle={setIsOpen} .../>`.

**Comment by rbertucat** [comment]
Try adding `event.stopPropagation();` in your `onSelect` function. 
That should fix it, see: https://codesandbox.io/s/typeaheadmulti-with-onfilter-forked-xy979?file=/index.js:746-754

**Comment by MariaAga** [comment]
@rbertucat Thanks that solved it!

**Comment by evwilkin** [comment]
Thanks for taking a look @rbertucat !  

@MariaAga should we close this issue out, or is it still giving you any trouble?

**Comment by MariaAga** [comment]
I have the `event.stopPropagation();` work around, but I still think this is a bug

**Comment by MariaAga** [comment]
Not sure if I tested it wrong before, but it looks like the fix isn't working for me
