### ISSUE TITLE
Update Documentation for Package descriptions

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#635]
Add a simple break down of those packages in the patternfly-react/packages, patternfly-3 and patternfly-4 directories that illustrate the value from a business justification point of view.

The following files shouold be updated:
- patternfly-react/packages/README.md
- patternfly-react/packages/patternfly-3/README.md
- patternfly-react/packages/patternfly-4/README.md

**Comment by dgutride** [comment]
Docs were updated - moving to closed
