### ISSUE TITLE
bug(Nav): Cant see flyout nav when using page component

### ISSUE THREAD

**Issue by MariaAga** [patternfly/patternfly-react#6396]
**Describe the issue. What is the expected and unexpected behavior?**
When using the `Nav` with flyout option inside `PageSidebar`, the flyout elements aren't shown on hover, they appear in the dom but are hidden
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://codesandbox.io/s/summer-star-f9h1e?file=/index.js
![Screenshot from 2021-10-04 12-56-33](https://user-images.githubusercontent.com/30431079/135839721-33548a9b-9b5a-457d-8ebf-b4c564ed3451.png)

**What is your product and what release version are you targeting?**
Product - foreman
pf version: "@patternfly/react-core": "4.155.0",

**Comment by tlabaj** [comment]
Hi @MariaAga Flyout is not currently supported in Nav.  We started working on it last release, and are continuing work this sprint to finish it up for our next release.  Can we close this issue and you can reopen it or create a new issue if you have problems with t flyout once it is released?
