### ISSUE TITLE
DualListSelector - tree variant performance improvements

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#6424]
Large data sets for DualListSelector have a large amount of latency as well (same structure as TreeView). Memoization similar to TreeView (PR https://github.com/patternfly/patternfly-react/pull/6362) should be implemented here as well. Potentially also investigate using a non-recursive solution for further performance improvements.

**Comment by ddonahue007** [comment]
We are seeing latency in Cost Management when we have large data sets. I will pull together more details on what we are seeing if it is helpful.
