### ISSUE TITLE
Date select demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6460]
Per https://github.com/patternfly/patternfly-design/issues/1082 want to create a new "select list" component for date picking, which includes a list of relative date ranges. Additionally, when a date range is picked from the list, we would want the actual dates to be written out with the toggle itself.

![image](https://user-images.githubusercontent.com/6619860/137519543-b3a0e398-daa6-4f7c-9da4-ec233b6e2596.png) 

cc @mmenestr

**Comment by nicolethoen** [comment]
Possibly similar to this? https://www.patternfly.org/v4/components/search-input/react-demos

**Comment by mcarrano** [comment]
A little bit different because seems like this just becomes a custom Select. Maybe we just create as a new demo using a composable Select component?
