### ISSUE TITLE
OverflowMenuGroup/OverflowMenuControl do not forward props

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#6478]
I should be able to add other valid HTML props to OverflowMenuGroup/OverflowMenuControl

**Comment by edreeseg** [comment]
Do you mind assigning this to me? I should be able to get it done pretty quick.

**Comment by boaz0** [comment]
@edreeseg are you still working on it?

**Comment by edreeseg** [comment]
@boaz0 Very sorry for the inconvenience, haven't been able to get to this. Life gets in the way. Please feel free to grab it if you're wanting to.

**Comment by boaz0** [comment]
@edreeseg thanks for your fast response.
Yes, I feel your pain. I hope everything is OK.
In the future if you find something you want to work on, feel free to reach out to me on [Slack](https://slack.patternfly.org/) and I would love to help you.

Best regards and have a good one.
