### ISSUE TITLE
Allow Context selector menu's FocusTrap to be made inactive

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#6494]
Similar to how it's done in Modal:
https://github.com/patternfly/patternfly-react/blob/977d6ac719802b9d0fb0d1cc5c6688dd9ff336a3/packages/react-core/src/components/Modal/Modal.tsx#L47
Which through a prop let's you disable FocusTrap
```
<FocusTrap active={!disableFocusTrap} />
```

**Comment by evwilkin** [comment]
@BeAmazedVariable thanks for taking a look!  We should just need to update [one file](https://github.com/patternfly/patternfly-react/blob/977d6ac719/packages/react-core/src/components/ContextSelector/ContextSelector.tsx) for this issue, by adding a `disableFocusTrap` prop to the ContextSelector component and then using this new prop inside the `FocusTrap` component further down the file.

See the Modal example jschuler linked above for [where the prop is defined](https://github.com/patternfly/patternfly-react/blob/977d6ac719/packages/react-core/src/components/Modal/ModalContent.tsx#L66-L67) and [where it is used within FocusTrap](https://github.com/patternfly/patternfly-react/blob/977d6ac719/packages/react-core/src/components/Modal/ModalContent.tsx#L173-L174) (by passing it through to the FocusTrap's `active` prop).

Would you like to take on this issue?  If so we'll assign it to you, if not just let us know if any other issues may be a good fit!

**Comment by BeAmazedVariable** [comment]
@evwilkin I would love to give it a try sir

**Comment by evwilkin** [comment]
@BeAmazedVariable great, thanks for taking this on!  We've assigned it to you, and are happy to review the PR when it's ready.  Cheers!

**Comment by tpmai22** [comment]
@evwilkin when I try to run `test` locally all my test break. When I try to commit my stagged files I bump into this

```bash
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
Do I need to do anything else in order to complete my environment set up ?
