### ISSUE TITLE
Dual list selector addAll button does not work as expected. 

### ISSUE THREAD

**Issue by jkozol** [patternfly/patternfly-react#6495]
According to the props of the Dual list selector, the addAll callback should return (newAvailableOptions: React.ReactNode[], newChosenOptions: React.ReactNode[]). However, I am experiencing it returning the existing available and chosen options. This causes the addAll button to be useless.

**Comment by KKoukiou** [comment]
@nicolethoen I can verify that it works as expected, at least with the version of PF used in the sandbox. Let's close this and if @jkozol can find a reproducer we can reopen.
