### ISSUE TITLE
Component - Search

### ISSUE THREAD

**Issue by sharvit** [patternfly/patternfly-react#65]
Implement a component that provides the following UI element:
* http://www.patternfly.org/pattern-library/widgets/#search

Would you consider it necessary as a standalone component?
Or just have the basic FormControls like in react-bootstrap?
https://react-bootstrap.github.io/components.html#forms

**Comment by danseethaler** [comment]
I'm working on a search component that has a filter dropdown, a search bar with auto-completion, and a bookmark tooltip (implemented in https://github.com/theforeman/foreman/pull/4807). I think the standard form controls are a good place to start. Using react gives us so much flexibility. It would be fairly simple to integrate several components into one once we get the main building blocks in place.

![image](https://user-images.githubusercontent.com/11202705/32563940-925f9c20-c480-11e7-97ce-db040e9f7841.png)

**Comment by priley86** [comment]
Referencing the existing ux-design [documentation](https://github.com/patternfly/patternfly-design/blob/master/pattern-library/forms-and-controls/find/design/overview.md) we have in PF. It looks like the widget pattern on the patternfly.org website is much simpler than what's in those specs. We also have this existing test page: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/search.html.

We may need to ask @Rohoover or @jgiardino if there are any specific design questions on these variations (b/c these docs seem a bit dated). Feel free to reach out to them...

**Comment by jgiardino** [comment]
To answer your question, @sharvit, I don't have a strong preference, but I kind of lean toward a more basic component, like the [react-bootstrap FormControls](https://react-bootstrap.github.io/components.html#forms) that you referenced, versus having one component that is specific for search. Ideally, the basic component could accommodate the combination of elements that are present in the Search component.

For reference, here is a link to the Search test page that includes different variations:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/search.html

**Comment by sharvit** [comment]
Thanks for replying!

As @danseethaler and I discussed, ideally, we would like to use only `patternfly-react` and stop using `react-bootstrap` as a dependency in our project.

I think that the strategy to have the `search-widget` is something like:
Wrap or export (depends on the differences between bootstrap to patternfly) the form components:
- [ ] [FormGroup, FormControl, ControlLabel](https://react-bootstrap.github.io/components.html#forms)
- [ ] [Checkbox, Radio, FormControl.Static, HelpBlock](https://react-bootstrap.github.io/components.html#forms-controls)
- [ ] [Form](https://react-bootstrap.github.io/components.html#forms-layout)
- [ ] [InputGroup, InputGroup.Addon, InputGroup.Button](https://react-bootstrap.github.io/components.html#forms-input-groups)
- [ ] [FormControl.Feedback](https://react-bootstrap.github.io/components.html#forms-validation)
- [ ] Implement the `search-widget` based on those components

**Comment by priley86** [comment]
This sounds reasonable to me @sharvit, and I like the approach of starting small and building up to the more complex form components. 

I'm not quite sure how best to lay out the stories/documentation in pf-react at this point, but please work w/ @jgiardino on this.

**Comment by priley86** [comment]
@sharvit @danseethaler what is the status here? I think we are planning to attempt the Toolbar pattern next sprint. From the PR @danseethaler mentioned, it does not seem to match the current PF design pattern for [Toolbar](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toolbar.html?#), but maybe we can reuse some of the components started there? 

Any thoughts here are definitely appreciated.

**Comment by sharvit** [comment]
@priley86 , I am in the development process of it as it's a part of a feature i am implementing for foreman.
http://projects.theforeman.org/issues/21604

Soon i will publish a pr that exporting the From related components from bootstrap and show how to use them.
