### ISSUE TITLE
Text Input group

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#6524]
**Describe the issue. What is the expected and unexpected behavior?**
Add `onBlur` and `onFocus` callbacks.  Also add `type` prop to match TextInput component and the `isDisabled` prop.

**Comment by wise-king-sullyman** [comment]
@mcoker it looks like the gray background on [Text Input's disabled example](https://www.patternfly.org/v4/components/text-input/#disabled) comes from a style on form-control that isn't available on text-input-group.

Is this something that would need to be added to text-input-group on the core side?

**Comment by mcoker** [comment]
@wise-king-sullyman yep, if you'll create a core issue I can add that for you.
