### ISSUE TITLE
Add option to hide topology connector menu on drag end

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6532]
Currently the only way to manually hide connector context menu on drag end in topology is by returning null/empty array from the onCreate callback. But it is not possible to do so when rendering custom react elements (i.e. not using ContextMenuItem) for the choices.

Add an additional option to the connector options which hides the connector menu on drag end when the option is set.

**Comment by rottencandy** [comment]
Implemented in #6522
