### ISSUE TITLE
TableGrid - Support Row and Cell Selection

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#656]
The TableGrid should provide click callbacks and styling for selection of items in the table. Row and individual Cell selection should be supported.

**Comment by priley86** [comment]
An additional enhancement that may be nice to see along these lines would be an example of infinite scrolling with [react-virtualized](https://github.com/openshift/console/blob/master/frontend/package.json#L86).

**Comment by jeff-phillips-18** [comment]
That's a completely different issue 😉 

Feel free to add another issue for that support.

**Comment by priley86** [comment]
will do 👍
