### ISSUE TITLE
Question/suggestion: Is there a way to implement a clear "X" button for the TimePicker?

### ISSUE THREAD

**Issue by FedeLacabaratz** [patternfly/patternfly-react#6569]
I think it would be good to count with a clear "X" button as it is already implemented in inputSelects here for patternfly and I wonder if there is a way to do it? I tried to set up a custom button and force a setState (local state) to set my time string to null but it just won't work . 

Maybe there is a onClear function or something I'm not seeing in the descripted props down below your web page?

I believe this could be a good enhancement if it doesn't exists. If it does could you please provide a small example of how to do this?

I'm using React v17.0.2

I look forward to hearing from you. Thanks!

**Comment by nicolethoen** [comment]
@FedeLacabaratz You are correct, this is currently not a supported feature. It has been added to the roadmap.

**Comment by nicolethoen** [comment]
Whenever this is implemented, it may be worth investigating whether it'd be wise to refactor the TimePicker to use a TextInputGroup under the hood.
