### ISSUE TITLE
Table: add sticky columns to legacy table

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#6575]
Legacy table should also support sticky columns as ComposableTable.

**Comment by KKoukiou** [comment]
I know there are still consumers of the legacy table. openshift console for example. FYI dropped it's usage a few weeks ago. 

Since this is clearly deprecated, I don't think its necessary to add more usages in the docs.

**Comment by tlabaj** [comment]
Thanks for that information @KKoukiou.  Our plan initially was to implemented this in compassable table only.
@dlabrecq's team (Cost Management) is still using the legacy table and they are requesting this be added.

cc @mcarrano

**Comment by mcarrano** [comment]
@tlabaj @nicolethoen should this be added to an upcoming milestone?
