### ISSUE TITLE
Droppable and Draggable ignore children classname

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#6593]
**Describe the issue. What is the expected and unexpected behavior?**

`Droppable`([here](https://github.com/patternfly/patternfly-react/blob/8c1eb5d895aa2512f7b4197654e414394ff25b30/packages/react-core/src/components/DragDrop/Droppable.tsx#L30)) and `Draggable` ([here](https://github.com/patternfly/patternfly-react/blob/8c1eb5d895aa2512f7b4197654e414394ff25b30/packages/react-core/src/components/DragDrop/Draggable.tsx#L299)) overwrites children `classname` and so the classname is being ignored.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

```jsx
    <DragDrop onDrop={onDrop}>
      <Droppable hasNoWrapper>
        <DataList className="rca-notifications-list" aria-label="draggable data list example" isCompact>
          {notifications.map((notification) => (
            <NotificationItem key={notification.id} id={notification.id} notification={notification} />
          ))}
        </DataList>
      </Droppable>
    </DragDrop>
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug 🐛 

Workaround - pass `classname` to Droppable/Draggable instead of the child.

```diff
    <DragDrop onDrop={onDrop}>
-      <Droppable hasNoWrapper>
+      <Droppable className="rca-notifications-list" hasNoWrapper>
-        <DataList className="rca-notifications-list" aria-label="draggable data list example" isCompact>
+         <DataList aria-label="draggable data list example" isCompact>
          {notifications.map((notification) => (
            <NotificationItem key={notification.id} id={notification.id} notification={notification} />
          ))}
        </DataList>
      </Droppable>
    </DragDrop>
```

**What is your product and what release version are you targeting?**

WEB-RCA-UI (internal Red Hat tool)

**Comment by boaz0** [comment]
@tlabaj can you assign it to me?
Thanks.
