### ISSUE TITLE
Pagination: make itemCount optional

### ISSUE THREAD

**Issue by mhuin** [patternfly/patternfly-react#6602]
**Describe the issue. What is the expected and unexpected behavior?**
Some search APIs do not return a total count of elements matching a query, for performance reasons. The pagination component should just display "results X-Y from **many**" or something equivalent if itemCount is not provided.
The page count element already handles the case when itemCount is not a number.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a request for enhancement on the Pagination component.

**Comment by nicolethoen** [comment]
Hello @mhuin 
We have just merged a PR that will be released this week to add this feature:
PR: https://github.com/patternfly/patternfly-react/pull/6556
issue: https://github.com/patternfly/patternfly-react/issues/6497

**Comment by mhuin** [comment]
Fantastic! Apologies for not finding the issue earlier. Let's close this then.
