### ISSUE TITLE
Breaking change: Upgrade react-dropzone or remove it and roll our own file drag/drop functionality

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#6611]
See https://github.com/patternfly/patternfly-react/pull/6610 and https://github.com/patternfly/patternfly-react/issues/3966.

Upgrading react-dropzone would potentially fix some issues (need to check their changelog) but is a breaking change because of its types.

**Comment by nicolethoen** [comment]
Closed by #7926
