### ISSUE TITLE
About Modal: Refactor to be built with the modal component

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6614]
Follow up to https://github.com/patternfly/patternfly/issues/4526

Per https://github.com/patternfly/patternfly/pull/5216/files, the `.pf-c-about-modal-box` component is no longer styled as its own modal, and is now a regular element/box. This update allows us to place the about modal component in the existing modal component. This is similar to how a wizard behaves when inside of a modal.

The update from core is to remove the following attributes from the about modal, since they will now be on the modal component
  * `role="dialog"`
  * `aria-modal="true"`
  * `aria-label[ledby]`
  * `aria-describedby`

We're using a large modal in the core demo, but I imagine that can be configurable by the user, similar to the existing wizard in a modal. Though I think it begs the question - if it's more composable to be used with the `<Modal>` (instead of shipping with the `<Modal>`):
* Should it be called `<AboutModal>`? Or should we take "modal" out of the name?
* Could it be used outside of a `<Modal>`?

cc @mcarrano @mceledonia @tlabaj - opinions on the usage/naming above?

**Comment by mcarrano** [comment]
While I don't see a reason that the About would be used outside of a modal, I also think that calling the component <AboutModal> is a bit redundant if it will always just be placed inside of a <Modal>. Am I understanding that correctly? So maybe then it does make more sense for the component to be named just <About>? Although I would not change the name in the website nav, so leave as is if that will be confusing.
