### ISSUE TITLE
"React state update on an unmounted component" message being triggered after copying text

### ISSUE THREAD

**Issue by jkilzi** [patternfly/patternfly-react#6649]
It happens here:
https://github.com/patternfly/patternfly-react/blob/d026d3fbbcdaa8438312b71ebe59a2f232103b4d/packages/react-core/src/components/ClipboardCopy/ClipboardCopy.tsx#L197

I have this modal that renders the ClipboardCopy component. Right after copying the text if one closes the modal immediately, you'll get the warning in the browser's console saying: `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method`

Sample consumer code:
https://github.com/openshift-assisted/assisted-ui-lib/blob/a3b9ca6a5b1895b5e3daf15b1c492a955ba6f7f4/src/common/components/clusterConfiguration/DownloadIso.tsx#L48

**Comment by boaz0** [comment]
@jkilzi thank you for opening this issue. It seems like an easy fix.
The issue is that we forgot to clear the timeout timer on unmounting and that's why we get this error message.
I will open a PR to solve this issue.

//cc @mcarrano @tlabaj @nicolethoen
