### ISSUE TITLE
CalendarMonth RFEs

### ISSUE THREAD

**Issue by knokit** [patternfly/patternfly-react#6654]
Currently, _CalendarMonth_ always requires a `date` prop and it seems this prop should be optional, as it defaults to `today` if not provided.

Two other things that would be useful:
- allow selecting multiple individual dates (not a range)
- expose the month change events (for example `onMonthChange`)

The following issues are stories for this epic:
- [x] #7026
- [x] #7027

**Comment by mcarrano** [comment]
We will get this on our roadmap. We are currently scheduling into Q2 2022.

**Comment by tlabaj** [comment]
I opened a new issue for the first part of about the required prop #7026 since that is independent of the other requests.

**Comment by tlabaj** [comment]
@knokit is the request "allow selecting multiple individual dates (not a range)" for the CalendarMonth component or the Date picker component?

**Comment by tlabaj** [comment]
@mcarrano I also opened #7027 to add the missing examples in react for the date range selection.

**Comment by knokit** [comment]
> @knokit is the request "allow selecting multiple individual dates (not a range)" for the CalendarMonth component or the Date picker component?

@tlabaj, it's for the CalendarMonth component.
 
> For the second bullet point, we have prop for the `onChange` call back. Is there something else you were looking for?

`onChange` is called when a date is selected and I'm looking for something different.

My idea is that `onMonthChange` (and `onYearChange`?) would be called whenever the visible month changes - for example, this would be useful for loading data for the visible month from an API and enable/disable dates based on it.

**Comment by thatblindgeye** [comment]
@knokit The optional date prop issue has been resolved in PR #7077 . A quick note:

We have removed the default of "today" when a date prop is not passed in, which can be explained in the following comment chain within that PR: https://github.com/patternfly/patternfly-react/pull/7077#discussion_r831466050

Despite there not being a default _selected_ date when the date prop is not passed in, the Calendar Month component should still default to visually showing the current "today" month as well as applying a style to the "today" day.

**Comment by mcarrano** [comment]
@knokit I wanted to follow up again about the request to support picking multiple dates from the calendar (as opposed to a range). DO you have a specific use case for this? Can you describe what that is? Thanks.

**Comment by knokit** [comment]
I have this component:
<img alt="events calendar" src="https://user-images.githubusercontent.com/3659829/172127088-f56c0b79-1da5-4b82-85c6-49761b3b7cb8.png" width="400" />

Only dates that have events (can have multiple) are enabled. The user can select a single date or multiple dates to view the events - I think this can also work with a range selection, so probably you can **ignore** the request for picking multiple individual dates from the calendar.


> expose the month change events (for example onMonthChange)

I'll still need a way to load the events from an API when the month/year is changed, that's why I think these events would be useful.

**Comment by nicolethoen** [comment]
[Here is a codesandbox demonstrating](https://codesandbox.io/s/naughty-einstein-lzjhds?file=/index.tsx) how to only have certain dates selectable. @knokit would that satisfy the requirement?

**Comment by knokit** [comment]
Thanks for the example, @nicolethoen! That's actually what I'm already doing. However when the user changes the month/year I'd need to have a way to load a new list of valid dates for the visible month from an API - that's why I asked to expose the month/year change events.

**Comment by nicolethoen** [comment]
I opened a PR to add an onMonthChange event that will fire whenever a new month/year is selected. I think you should be able to implement your design with this change.
