### ISSUE TITLE
Code editor: demo for adding keyboard shortcuts

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6663]
The Monaco editor already supports keyboard shortcuts, but want to create a demo that shows how to expose these in the toolbar. Here is the current design: https://marvelapp.com/prototype/15bb10j4/screen/81521392  This includes a popover with shortcuts. Can this be built using text and chips? I'd like to leverage existing components and not create anything unique if it can be avoided. We can iterate on the design, if needed.

**Comment by DaoDaoNoCode** [comment]
This issue needs to wait until https://github.com/patternfly/patternfly/issues/4658 is fixed.
