### ISSUE TITLE
Select: isInputValuePersisted not working with in Grouped single with filtering example

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react#6669]
**Describe the issue. What is the expected and unexpected behavior?**

When I use `isInputValuePersisted` prop in the Grouped single with filtering example, it only seems to work if I select the option element that says `Create "xyz"`  - if I instead blur the field it doesn't retain the value like the other simple select case. Is it expected?

**Please provide the steps to reproduce.**

- Navigate to [Grouped single with filtering example](https://www.patternfly.org/v4/components/select/#grouped-single-with-filtering)
- Add the `isInputValuePersisted` prop to the Select component
- Type into the filter input "asdf"
- Click outside of the bounds of the Select input
- Notice the input value is not persisted

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Not sure if isInputValuePersisted was ever intended to work with the inline filter input. If it was, probably a bug, otherwise it's an enhancement. I did find a workaround is to couple this option with `isCreatable` and as long as the user selects the menu input itself, the rest of the experience is without issue.

**What is your product and what release version are you targeting?**

Migration toolkit for virtualization

![2021-12-02 12 48 31](https://user-images.githubusercontent.com/5942899/144476292-fb507a3d-92f8-4081-be90-7a470a035a60.gif)

**Comment by nicolethoen** [comment]
Closed by: https://github.com/patternfly/patternfly-react/pull/6670
