### ISSUE TITLE
CardActions are not aligned with CardTitle

### ISSUE THREAD

**Issue by rawagner** [patternfly/patternfly-react#6673]
**Describe the issue. What is the expected and unexpected behavior?**
The CardActions content is not aligned with CardTitle.

CardActions has `align-self: flex-start` - removing the property fixes the issue though Im not sure it thats a proper fix.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/eager-rgb-11ir4

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug
not blocking - it is a visual bug
workaround is to remove `align-self: flex-start` from CardActions but that is not really a viable option as the goal of my changes is to use clean PF without css modifications.

**What is your product and what release version are you targeting?**
Openshift Console, 4.10

**Comment by mcoker** [comment]
Hey @rawagner, the card actions were created with the original intent that the most common use case is with a kebab/plain button action as the action trigger for a dropdown menu, so we move that actions element up a little bit (the size of the button's top padding) to keep the title text and the icon in the button aligned with one another. For other use cases, such as the link in your example, a primary button, etc, you can use `<CardActions hasNoOffset>` to remove that positioning. Here's an example - https://codesandbox.io/s/confident-microservice-df4lq?file=/index.js. Let me know if that works for you.

**Comment by mcarrano** [comment]
For housekeeping sake, I am going to close this out. @rawagner if you are still seeing an issue, feel free to reopen.
