### ISSUE TITLE
Replace text input / select filters in Toolbar demos with SearchInput

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6682]
follow up related to this comment: https://github.com/patternfly/patternfly-react/issues/5961#issuecomment-896834219

**Comment by mcarrano** [comment]
@MariaAga I wanted to follow up with you on this issue. We've had more time to discuss this and did an audit of various components and demos to ensure we were presenting search inputs in a consistent way everywhere. Based on that we opened a new issue here: https://github.com/patternfly/patternfly-react/issues/6792 with a spreadsheet that calls out changes to be made across the library.

Essentially our recommendation is to use the [basic search input ](https://www.patternfly.org/v4/components/search-input#basic)as the default choice for toolbar examples and demos. If you want to continue with this issue, it would be great if you can update your existing PR based on that. If not, then we will close this out and schedule follow-up work against the newer issue. Let us know your thoughts.

cc @nicolethoen
