### ISSUE TITLE
Button: add demo to show progress completion state

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6684]
The demo should illustrate how a progress button can be used to reflect status. When the user clicks the button, it should enter "in-progress" state and upon completion, the completion state is displayed. See core issue with linked PR for more detail. https://github.com/patternfly/patternfly/issues/4354

**Comment by MariaAga** [comment]
Should this be the same demo as https://github.com/patternfly/patternfly/pull/4528?

**Comment by mcarrano** [comment]
Yes, it's intended as the React version of that demo that shows the change in state.
