### ISSUE TITLE
Description list: Add option to fill columns first

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6685]
Optionally fill columns and not rows first. Core PR: https://github.com/patternfly/patternfly/pull/4544

**Comment by boaz0** [comment]
@mcarrano can you assign this to me?

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj ^^^

**Comment by nicolethoen** [comment]
@boaz0 this has the same January 20th deadline. But you are welcome to work on it!
