### ISSUE TITLE
Dropdown: add plain text variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6687]
Adds a plain text variant of the dropdown component. Core PR: https://github.com/patternfly/patternfly/pull/4542

**Comment by boaz0** [comment]
@mcarrano / @nicolethoen - can I work on this please? 🙏 
![](https://media.giphy.com/media/3oz8xZMZox78ZbWbFC/giphy.gif)

**Comment by nicolethoen** [comment]
@boaz0 Sure! Let me know if you have any questions!

**Comment by nicolethoen** [comment]
We are hoping to have it completed for our next release. Code freeze is January 20th.

**Comment by boaz0** [comment]
@nicolethoen sounds reasonable.
