### ISSUE TITLE
Text Input Group issues

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#6697]
I added PatternFly's new `Text Input Group` component to Cost Management. The type-ahead is more usable than the `Select` component, but there are limitations. For example, we cannot add place holder text and an aria label. I also had to take some liberties regarding how keyboard navigation works.

Below are the observations I made while implementing the Text Input Group component.

**Component Issues**

1. Cannot add place holder text
2. . `TextInputGroupMain` does not clear input text for a value of undefined — must be an empty string

**Example issues**

1. Example doesn't use aira labels
2. Input focus box not rendered correctly without clear button — must conditionally render `TextInputGroupUtilities`
3. Input value cleared when menu has focus and escape key is pressed — should just close the menu and set focus on the text input for further editing
4. The tab key doesn't appear to work at all -- code looks like it was intended to select a menu option?

**Cost Management implementation**

1. Added “No results found” label instead of always showing “Suggestions”
2. Made the tab key clear the input value and navigate to the next tab index
3. A lot of keyboard navigation code must be added manually — painstaking to get working correctly

![chrome-capture](https://user-images.githubusercontent.com/17481322/145926414-cc8cb676-7ebf-4de9-a962-066edd14efb1.gif)

**Comment by tlabaj** [comment]
I opened issue [#4577](https://github.com/patternfly/patternfly/issues/4577) for the core work to support the place holder text.

**Comment by wise-king-sullyman** [comment]
@dlabrecq I have a few questions:

**Component Issues**

> Cannot add place holder text and aria label

Where are you wanting an aria label to be added?

`TextInputGroup` and `TextInputGroupUtilities` can take aria labels as additional props and will place them on the divs they return, `TextInputGroupMain` currently passes any aria labels it receives to the text input that it contains.

> `TextInputGroupMain` does not clear input text for a value of undefined — must be an empty string

`TextInputGroupMain` could be edited to set the input value as an empty string when its value prop is `undefined` (or falsy in general) and I wouldn't be opposed to that change, but this might be something better handled on the implementation side. @tlabaj do you have an opinion on this?

**Example issues**

> Input focus box not rendered correctly without clear button — must conditionally render `TextInputGroupUtilities`

`TextInputGroupUtilities`being conditionally rendered is fully optional behavior dependant on the composition of `TextInputGroup`. Is this something you'd like to see in a demo/example?

> Input value cleared when menu has focus and escape key is pressed — should just close the menu and set focus on the text input for further editing

I wouldn't be opposed to changing the `escape` interaction in the auto-complete search demo, but clearing the input is how [typeahead Select](https://www.patternfly.org/v4/components/select/#typeahead) works which this part of the interaction was modeled after. @mcarrano is this a change you'd like to see?

> The tab key doesn't appear to work at all -- code looks like it was intended to select a menu option?

Tab seems to be working as I expect/describe in the auto-complete search demo so I'm not sure that I understand this issue?

**Cost Management implementation**

> Added “No results found” label instead of always showing “Suggestions”

That functionality is already been built into the auto-complete search demo, so again I'm not sure that I understand this issue?

> Made the tab key clear the input value and navigate to the next tab index

The current tab behavior in the auto-complete search demo was [something @mcarrano specifically requested](https://github.com/patternfly/patternfly-react/pull/6661#pullrequestreview-821801062). Is this something you'd like to see changed?

> A lot of keyboard navigation code must be added manually — painstaking to get working correctly

I'd be very interested to see the additional keyboard navigation functionality that you had to add if you can link it/tell me where I can find it. I'm more than happy to do what I can to improve the keyboard navigation of the component/demos.

**Comment by mcarrano** [comment]
My best attempt to answer your questions @wise-king-sullyman ...

>   Input value cleared when menu has focus and escape key is pressed — should just close the menu and set focus on the text input for further editing. 

This makes sense to me. 

> The current tab behavior in the auto-complete search demo was something @mcarrano specifically requested. 

Yes, the intent was to make this work like an auto-complete text field so the user can use the tab key to autofill the string. Why do you expect the tab key to clear the field @dlabrecq ?

Would be great to get your input on these interactions, also, @jessiehuff .

**Comment by dlabrecq** [comment]
@mcarrano Pressing the escape key closes the dropdown, while focus should remain on the text field. This is useful in order to change the current text input value. At least, this is how I implemented it for Cost management.

Pressing the tab key moves focus from the text input to the next HTML element. IMO, it looks odd to leave a value in the text input after moving focus elsewhere. That is, considering it does not apply to anything in view.

That said, I can change Cost Management if this behavior is not desirable. However, the current example behavior doesn't make sense to me.

**Tab key:**
![chrome-capture](https://user-images.githubusercontent.com/17481322/147950164-cd3757d1-273a-4874-8939-df31955d1946.gif)

**Escape key:**
![chrome-capture (1)](https://user-images.githubusercontent.com/17481322/147950615-d8330f7e-c0a9-4576-b7b4-671a6aca0638.gif)

**Comment by mcarrano** [comment]
> Pressing the escape key closes the dropdown, while focus should remain on the text field. This is useful in order to change the current text input value. At least, this is how I implemented it for Cost management -- the example doesn't do that.

@dlabrecq I'm a bit confused about what the complaint is here. I agree that this is how it should work. Isn't the example working that way or am I missing something?

> Pressing the tab key (while in the dropdown area) moves focus from the text input to the next HTML element. IMO, it looks odd to leave a value in the text input after moving focus elsewhere. That is, considering it does not apply to anything in view.

The intent is for this to work like an autocomplete search field as in the demo here: https://www.patternfly.org/v4/components/search-input/react-demos#search-with-autocomplete It will make more sense when the ghost text is added. Hopefully in the next release. But it does look like there's a slight bug in the Text Input Group example where the focus is not moving upon pressing Tab @wise-king-sullyman . It may be that this is not the correct control for your use case @dlabrecq . Seems like you want something more like a type-ahead select that requires the  value to be a member of a closed list? This demo was intended to be for something more like a Google search where the input string is unbound.

**Comment by wise-king-sullyman** [comment]
> Isn't the example working that way or am I missing something?

@mcarrano currently in the example when you're focusing on the menu and hit `escape` the text in the input is deleted. I am happy to change this behavior when I address these items.

> But it does look like there's a slight bug in the Text Input Group example where the focus is not moving upon pressing Tab

Tabs default behavior is prevented in the auto complete search demo when only one item remains in the menu to enable easier auto completion per [this previous discussion](https://github.com/patternfly/patternfly-react/pull/6661#issuecomment-984889327).

Is this the potential bug, or am I misunderstanding and Tab is also preventing default behavior under other conditions?

**Comment by nicolethoen** [comment]
I think in both scenarios - the Tab behavior should move the focus to the clear button (if it exists) or the next focusable element.
If there is only one option, it should do the autocomplete and still move focus to the clear button - I think that's how it works in my search input autocomplete demo

**Comment by mcarrano** [comment]
> @mcarrano currently in the example when you're focusing on the menu and hit escape the text in the input is deleted. I am happy to change this behavior when I address these items.

Funny, that's not what I'm seeing when I test this. But in any case, yes, the menu should close, but the text should remain, I think.

**Comment by dlabrecq** [comment]
If the intent was to make it work like the "Search with autocomplete" example, I can implement it that way. The "Search with autocomplete" example does not behave quite the same way.

I just wanted to share my notes, so devs (including me) don't implement something different than what was intended.

**Comment by dlabrecq** [comment]
If the intent was to make it work like the Search Input's "Search with autocomplete" example, I can implement it that way. The Text Input Group example does not behave quite the same way. I just wanted to share my notes, so we don't implement something different.

That said, I probably could have just used the Search Input. It's not clear when to use one over the other (i.e., why I was pointed to the Text Input Group)?

**Comment by dlabrecq** [comment]
@nicolethoen If the intent was to make it work like the Search Input's "Search with autocomplete" example, I can implement it that way. The Text Input Group example does not behave quite the same way.

@mcarrano, our users need to enter text when it's "not available in the list of suggestions". It's not clear when to use Search Input Vs Text Group Input, but the latter seems like a better fit?

**Comment by nicolethoen** [comment]
@dlabrecq 
Search Input will soon be refactored to use a Text Input Group under the hood. There are just a few more features that need to be added to enable full parity. Using the Text Input Group allows you to implement a solution like the Search Input but with finer tuned customizable control. Using a Search Input means more of the functionality will come working right out of the box.

**Comment by mcarrano** [comment]
To add to what @nicolethoen is saying, one key behavioral difference between the two component is that the Text Input Group supports multi-selection with chips and the Search input is only good for single select. Does your user need to select multiple items? If not, the Search Input might be the better solution.

**Comment by dlabrecq** [comment]
Thanks, @mcarrano. I'll probably stick with the Text Input Group for now. 

After some discussion with Austin, I really only have a couple issues remaining with the example:

1. Need the ability to add placeholder text
2. Want to see how aria labels are used in the example
3. The tab key doesn't land on the clear button, like the Search Input example

When the example is updated to mimic Search Input, I'll take another look and update Cost Management to reflect that.

**Comment by wise-king-sullyman** [comment]
@dlabrecq I'll have a PR up today which will:

- Add a placeholder text prop to `TextInputGroupMain`
- Demonstrate aria-label and placeholder usage in the `AutoCompleteSearch` demo
- Make tab _always_ focus on the next element in the `AutoCompleteSearch` demo
- Make `TextInputGroupMain` clear the input when given a value prop that's falsy
- Undo input clearing when escape is hit while focusing on the Menu in the `AutoCompleteSearch` demo
- Add input clearing when tab is hit while focusing on the Menu in the `AutoCompleteSearch` demo
-  Explain in a comment why the search icon is conditionally rendered in our current examples/demos

I'm putting the finishing touches on the PR now, if there's anything not listed here that you'd want to see addressed for this issue please let me know!
