### ISSUE TITLE
Log Viewer: Non-wrapped log pushes the horizontal scrollbar out of view

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#6706]
When there are enough (non-wrapped) rows to create a vertical scrollbar, the horizontal scrollbar is pushed out of view as it scrolls along vertically with the rest of the line items.

Where's the horizontal scrollbar? (it is out of view)
![Screen Shot 2021-12-16 at 2 42 28 PM](https://user-images.githubusercontent.com/869106/146437959-fa85dbfd-a537-4066-819a-775ad54171b3.png)

Oh, i see it now when i scroll all the way to the bottom!
![Screen Shot 2021-12-16 at 2 42 38 PM](https://user-images.githubusercontent.com/869106/146437998-00996737-4fa6-4583-8a80-64fcf6d90b80.png)

**Comment by nicolethoen** [comment]
@DaoDaoNoCode has this been addressed?

**Comment by DaoDaoNoCode** [comment]
@nicolethoen Oh yes, I forgot this issue. It's already addressed in this PR https://github.com/patternfly/patternfly/pull/4587.

**Comment by nicolethoen** [comment]
Closed via: https://github.com/patternfly/patternfly/pull/4587
