### ISSUE TITLE
bug(Pagination): pluralize function only works for English

### ISSUE THREAD

**Issue by MariaAga** [patternfly/patternfly-react#6707]
I'm using the pagination component and our project replaces English strings with their translation. The pagination adds "s" to the word 'page' and that only works in english (using the pluralize function) this function is only used in Navigation.tsx .
https://github.com/patternfly/patternfly-react/blob/23202e2b45e7538d5c0e6516c8b3f65431968a0a/packages/react-core/src/helpers/util.ts#L230
Can this function be removed and just use 'page' for 1 item and 'pages' for multiple? 
Otherwise we get weird results for other langues like:
![Screenshot from 2021-12-17 12-02-23](https://user-images.githubusercontent.com/30431079/146535012-b71a0d8b-57d3-4bb2-b066-fdb666517778.png)

**Comment by boaz0** [comment]
@MariaAga / @tlabaj - there are many ways we can fix that. But I think the easiest way is to add to titles the "plural" option that we will be passed [here](https://github.com/patternfly/patternfly-react/blob/23202e2b45e7538d5c0e6516c8b3f65431968a0a/packages/react-core/src/components/Pagination/Navigation.tsx#L218) and then to `pluralize`.

Does that sound reasonable?
Thanks

**Comment by Ron-Lavi** [comment]
@boaz0++ sounds like a good solution :)

**Comment by Ron-Lavi** [comment]
on second hand, seem that the `page` title is always passed as plural `pagesTitle` in https://github.com/patternfly/patternfly-react/blob/26733a6a256ad0e873afbc268a712027470fdeaa/packages/react-core/src/components/Pagination/Pagination.tsx#L337

and then used in https://github.com/patternfly/patternfly-react/blob/23202e2b45e7538d5c0e6516c8b3f65431968a0a/packages/react-core/src/components/Pagination/Navigation.tsx#L218

wondering if we could just pass the plural in this case, and rename `page` to `pages` in titles

**Comment by boaz0** [comment]
@Ron-Lavi - thanks for your feedback. Let me explain myself better.

What I had in mind was adding to [here](https://github.com/patternfly/patternfly-react/blob/23202e2b45e7538d5c0e6516c8b3f65431968a0a/packages/react-core/src/components/Pagination/Navigation.tsx#L218):
```
 {ofWord} {pagesTitle ? pluralize(lastPage, pagesTitle, pagesTitlePlular) : lastPage}
```

which will come from `titles.plular` and be passed to [Navigation](https://github.com/patternfly/patternfly-react/blob/26733a6a256ad0e873afbc268a712027470fdeaa/packages/react-core/src/components/Pagination/Pagination.tsx#L337):
```
        <Navigation
          pagesTitle={titles.page}
          pagesTitlePlular={titles.plular}
          ...
        />
```

Obviously we can come up with better props names but this is my idea.

Let me know what you think.
Thanks 🙂

**Comment by Ron-Lavi** [comment]
yeah, I agree, adding `plural` key in `titles` seems to be the best way.
Thanks @boaz0 :)

**Comment by boaz0** [comment]
@tlabaj can you assign this to me. Thanks.
