### ISSUE TITLE
Composable tree table example is calculating rowIndex incorrectly

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#6719]
`ComposableTreeTable.tsx` defines a recursive `renderRows` function that tries to increment the row index for each recursive function call.

In the function's return statement, the row index passed via param to future recursive calls presumes that any sibling nodes only have one level of children. If a sibling has more than one level of children, then the row indexes are incorrect.

```
return [
      <TreeRowWrapper key={node.name} row={{ props: treeRow.props }}>
        <Td dataLabel={columnNames.name} treeRow={treeRow}>
          {node.name}
        </Td>
        <Td dataLabel={columnNames.branches}>{node.branches}</Td>
        <Td dataLabel={columnNames.prs}>{node.pullRequests}</Td>
        <Td dataLabel={columnNames.workspaces}>{node.workspaces}</Td>
      </TreeRowWrapper>,
      ...(node.children && node.children.length
        ? renderRows(node.children, level + 1, 1, rowIndex + 1, !isExpanded || isHidden)
        : []),
      ...renderRows(
        remainingNodes,
        level,
        posinset + 1,
        rowIndex + 1 + ((node.children && node.children.length) || 0), <------ this is the problematic piece of logic
        isHidden
      )
    ];
```

**Comment by eliranmal** [comment]
hmm, i initially thought we'd have to write some lookahead function to walk the tree and count all descendants, but then realized we're inside a tree-walking function, so we should have that data somewhere. and we do.

my suggestion; use the child rows length (which is known per execution) to calculate the correct row index. something [like this][1]:

```ts
// extract child row creation, so we have a reference when counting the remaining rows
const childRows = node.children && node.children.length
? renderRows(node.children, level + 1, 1, rowIndex + 1, !isExpanded || isHidden)
: []

 return [
  <TreeRowWrapper key={node.name} row={{ props: treeRow.props }}>
    // ...
  </TreeRowWrapper>,
  ...childRows,
  ...renderRows(
    remainingNodes,
    level,
    posinset + 1,
    // ditch that approach:
    // rowIndex + 1 + ((node.children && node.children.length) || 0),
    // ... and use the data we already have to count descendants:
    rowIndex + 1 + childRows.length,
    isHidden
  )
];
```


[1]: https://codesandbox.io/s/eager-golick-0jzpc

**Comment by eliranmal** [comment]
also, this should probably be fixed in [LegacyTableTree][1] as well, as the problematic logic is duplicated from there.

i will add this change to my PR when it's ready.

[1]: packages/react-table/src/components/Table/examples/LegacyTableTree.tsx

**Comment by nicolethoen** [comment]
Thank you @eliranmal !
