### ISSUE TITLE
Deprecated dependencies in tippy.js

### ISSUE THREAD

**Issue by ghjm** [patternfly/patternfly-react#6720]
Installing patternfly-react-core via npm gives deprecation warnings:

```
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

The old popper.js is a dependency of tippy.js:
```
$ npm ls popper.js
foo@0.0.1 /home/graham/foo
└─┬ @patternfly/react-core@4.181.1
  └─┬ tippy.js@5.1.2
    └── popper.js@1.16.1
```
The tippy.js dependency was last updated in https://github.com/patternfly/patternfly-react/pull/3370, about two years ago, and is probably in need of further updating.  The current version is v6.3.7, which is a major version update.  There is an upstream migration guide from v5 to v6 here: https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md.

The old core-js version is a dependency of react-dropzone:
```
$ npm ls core-js
foo@0.0.1 /home/graham/foo
└─┬ @patternfly/react-core@4.181.1
  └─┬ react-dropzone@9.0.0
    └─┬ attr-accept@1.1.3
      └── core-js@2.6.12
```
There was an intentional downgrade to react-dropzone 9.0.0 to fix an issue: https://github.com/patternfly/patternfly-react/pull/6610.  However, react-dropzone 9.0.0 is coming up on three years old, and the very old core-js dependency will only become more of a problem as time goes on.  At the time of the downgrade, the then-current react-dropzone version was 10.2.2, but the current version today is 11.4.2.  Perhaps upstream has solved the behavior issues by now.

**Comment by tlabaj** [comment]
This issue will track tippy dependency upgrades.  Dropzone is covered in #6611

**Comment by tlabaj** [comment]
closing this.  The tippy depencendy will no longer be needed in Breaking change release.  See #8243
