### ISSUE TITLE
Menu: setting an initial activeMenu different than the 'root' menu crashes the component (drilldown variant)

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#6761]
**Describe the issue. What is the expected and unexpected behaviors
I am implementing a language selection feature, which this (drilldown menu variant) Menu component seems to serve very well.

![Screen Shot 2022-01-11 at 09 27 21](https://user-images.githubusercontent.com/14921356/148907382-34aef87f-6688-448e-9e52-c5c45387c972.png) 
![Screen Shot 2022-01-11 at 09 27 13](https://user-images.githubusercontent.com/14921356/148907388-b3cce082-7df9-4471-b2e8-cff65bef4f5f.png)

The menu should have a preselected language, and for this reason I need to have the 'activeMenu', 'drilldownPath' and 'menuDrilledIn' properties set accordingly.

I tried doing it and the component crashes.

Could I get an advice from the designers if you think this component is the right one to use? @mcoker 

If yes, let's keep this bug report and make sure the component works with the non-root preselected menu item.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/optimistic-bird-0flyu?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
/bug

**What is your product and what release version are you targeting?**
Anaconda - https://communityblog.fedoraproject.org/anaconda-is-getting-a-new-suit/#more-10593

For the record the component previously (in a GTK app) looked like this:
![lanaguage-first](https://user-images.githubusercontent.com/14921356/148908821-52bb8056-74dd-49ba-b069-d025b4ea43da.png)

**Comment by mcarrano** [comment]
@KKoukiou I do think that the drill down menu is a good fit for your language selection use case. I don't think we have any other current standard. Are you aware of anything else we've done in product @mmenestr ?

cc @nicolethoen @mattnolting

**Comment by mmenestr** [comment]
@mcarrano @KKoukiou I'm not aware of anything we've done in product for this sort of use case, but some other components to consider could be the [tree view](https://www.patternfly.org/v4/components/tree-view#with-checkboxes) component or a [dual list](https://www.patternfly.org/v4/components/dual-list-selector) component.

Though, seeing the screenshot you've included, it does look like the drill down is the one that most closely matches what was previously implemented, and would seemingly work well for this use case!

**Comment by KKoukiou** [comment]
@mmenestr https://www.patternfly.org/v4/components/tree-view/#with-search this looks very promising as well. Thanks! 
So keeping this open only for the react bug.

For designers :) Feel free to unfollow!
