### ISSUE TITLE
NumberInput ignores min/max when increment overruns these values (equals comparison)

### ISSUE THREAD

**Issue by gbraad** [patternfly/patternfly-react#6765]
Consider the following:

```javascript
import React from 'react';
import { NumberInput } from '@patternfly/react-core';

class UnitThresholdNumberInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: 1     // <-- initial value is odd, and allows therefore to overrun the max/min
    };
    this.minValue = 0;     // <-- lower boundary to clamp; expected to allow >=0, not < 0
    this.maxValue = 10;    // <-- upper boundary to clamp; expected to allow <=10, not >10

    this.onMinus = () => {
      this.setState({
        value: this.state.value - 2    // <-- increment by 2, when started at 1 this means values are odd on plus, minus
      });
    };

    this.onChange = event => {
      // This only gets executed on a manual input, like key presses ?
      // therefore 'any' value is possible, 1, 2, 3, 4 as it doesn't increment with onPlus, onMinus
      const newValue = isNaN(event.target.value) ? 0 : Number(event.target.value);
      this.setState({
        value: newValue > this.maxValue ? this.maxValue : newValue < this.minValue ? this.minValue : newValue
      });
    };

    this.onPlus = () => {
      this.setState({
        value: this.state.value + 2
      });
    };
  }

  render() {
    const { value } = this.state;

    return (
      <React.Fragment>
        With a minimum value of 0 and maximum value of 10
        However: I can overrun (&gt;10) and underrun (&lt;0) these values when increment happens with 2 and is initially at 1.
        <br />
        <NumberInput
          value={value}
          min={this.minValue}
          max={this.maxValue}
          onMinus={this.onMinus}
          onChange={this.onChange}
          onPlus={this.onPlus}
          inputName="input"
          inputAriaLabel="number input"
          minusBtnAriaLabel="minus"
          plusBtnAriaLabel="plus"
          unit="%"
        />
      </React.Fragment>
    );
  }
}
```

When this code is used, the values increase or decrease by `2` when the buttons are clicked. When the initial value is even, like `0` or `2` this works as expected, but when an initial value of `1` is used you can overrun the max and min value and therefore have `-1` and `11` as values. It feels like the check is performed as an equal for `onPlus`/`onMinus` and min/max comparison. 

~~This is relevant, as an unexpected (like here an `odd` value can be inserted as the cursor keys do not use the expected events. This affects an earlier issue we have: #6753~~ While this is resolved in #6764, it is not impossible to get a value that is offset and does not match the `===` https://github.com/patternfly/patternfly-react/issues/6765#issuecomment-1010687125

Note: why doesn't clamp happen with an `onChange` ? it could be done by invoking the user specified `onChange` wrapped by a PatternFly `onChange` that clamps based on min and max.

**Comment by gbraad** [comment]
> It feels like the check is performed as an equal for onPlus/onMinus and min/max comparison.

https://github.com/patternfly/patternfly-react/blob/004cdf8648be921f15c9dafa489964f4bc4fa8d5/packages/react-core/src/components/NumberInput/NumberInput.tsx#L85
https://github.com/patternfly/patternfly-react/blob/004cdf8648be921f15c9dafa489964f4bc4fa8d5/packages/react-core/src/components/NumberInput/NumberInput.tsx#L107

**Comment by boaz0** [comment]
@mcarrano can you assign this to me? :pray: 
Thanks

**Comment by boaz0** [comment]
@gbraad the problem I have here is that when the user specifies `min` and `max` it means we need also to control the state of the value that is passed to the `value` props. Because if we set `max` to 30 and on `onPlus` the value is changed to 40 then even though the `plus` and `minus` buttons are disabled the value is not between `max` and `min` and that feels odd.

So it seems like the options we have right now are:
1) breaking the api and coming up with a better props that allow us to avoid these cases.
2) on exceeding, an error message will be shown below the input and one of the buttons will be disable.

Do you have a better suggestion?

**Comment by gbraad** [comment]
You could only increase the value to the clamped value of max. Even if you are at 30, and a max of 40, and I plus. Aluenof 20, you can't disable the button. That can only happen after the clamped value is reached or forced set due to overrun/exceed.

Error message might be the responsibility of the user. I'd rather have an event that gets triggers so this can be handled by the developer. Though not actually necessary. I wouldn't use it. The clamping and disabled button should be enough

**Comment by mcarrano** [comment]
@boaz0 I agree with @gbraad . You should just clamp the value so that it never exceeds the max or is less than the min value.

@tlabaj @nicolethoen can you assign this to @boaz0 ?

**Comment by boaz0** [comment]
@tlabaj - yes sure. I will push a pull request tomorrow.
