### ISSUE TITLE
Component - Modal Overlay

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#68]
Provide implementation for the modal overlay as documented here: http://www.patternfly.org/pattern-library/forms-and-controls/modal-overlay/

Note that @jeff-phillips-18 implemented this in OpenShift, but this has not yet been contributed back to Angular PatternFly (associated Issue: https://github.com/patternfly/angular-patternfly/issues/673)
He has some suggestions re: implementation that should be considered.

cc: @priley86

**Comment by priley86** [comment]
@serenamarie125 i've added PR #69 to start the Wizard pattern in PF React. I have setup some time next week to review this further w/ @jeff-phillips-18. thanks!  :bowtie:
