### ISSUE TITLE
ClipboardCopy extra commas

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#6863]
ClipboardCopy component renders unnecessary commas between text elements.
Example:
```
import React from 'react';
import { ClipboardCopy } from '@patternfly/react-core';

const someValue = "hello world";
const Basic = () => <ClipboardCopy hoverTip="Copy" clickTip="Copied">
This is editable {someValue}
{' '}
test
</ClipboardCopy>;
```
![Screen Shot 2022-01-26 at 11 52 17 AM](https://user-images.githubusercontent.com/869106/151209045-b109ff95-adbe-4305-b34c-96136c23687a.png)

**Comment by DaoDaoNoCode** [comment]
@jschuler I think this is because the `props.children` will be a string array in this way, one workaround could be setting the children to a string:
```
{`This is editable ${someValue}
${' '}
test`}
```

**Comment by DaoDaoNoCode** [comment]
This ClipboardCopy currently accepts the type `ReactNode` as its children type based on the doc, is it purposed to do so? I think it would be better to limit it to the `string | number` because there is no point to render a non-text node to a ClipboardCopy. Any thoughts? @tlabaj @mcarrano

**Comment by tlabaj** [comment]
@DaoDaoNoCode I agree, string or number would be more appropriate type.  However, that would be. breaking change.  Can we fix this with current implementation and perhaps open ac breaking change issue?
