### ISSUE TITLE
Not possible to set isChecked prop on SelectOption creation

### ISSUE THREAD

**Issue by nadjaheitmann** [patternfly/patternfly-react#6874]
**Describe the issue. What is the expected and unexpected behavior?**
I am trying to set `isChecked` option to `true` when creating a `SelectOption` within a `Select` with variant `checkbox`. It defaults to `false`, though. I can see that it is not documented, either, but I don't see any obvious reason why it should not be able to set this prop on component creation.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
See above.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
As it is missing in documentation, might be an enhancement. Not sure how to work around this.

**What is your product and what release version are you targeting?**

**Comment by DaoDaoNoCode** [comment]
@nadjaheitmann Hi, are you referring to this example https://www.patternfly.org/v4/components/select#checkbox-input? If you are looking for a way to set some default options to `isChecked`, you could set the initial state `selected` to the array that includes the value you want to check.
I create an example to demonstrate this https://codesandbox.io/s/white-night-o6mry.

**Comment by nadjaheitmann** [comment]
@DaoDaoNoCode Thanks for the hint with the `selected` array, this is a good workaround. Still, more complexity than I wished for :)

**Comment by kmcfaul** [comment]
@nadjaheitmann `isChecked` for `SelectOption` is an internal property that is manipulated by `Select`, which is the reason the flag is not included in the docs. Setting `selected` would be the intended method for defaulting with a checked checkbox.
