### ISSUE TITLE
Adding 'noPadding' prop to table cell does not remove padding

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#6878]
**Describe the issue. What is the expected and unexpected behavior?**
When passing the `noPadding` prop to the `Td` component I expect the padding to be removed from the cell, instead the padding remains the same.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/heuristic-night-9r4md?file=/index.js

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
This is a bug.

**What is your product and what release version are you targeting?**
```
npm ls | grep @patternfly
├── @patternfly/patternfly@4.164.2
├── @patternfly/react-code-editor@4.22.1
├── @patternfly/react-core@4.192.7
├── @patternfly/react-icons@4.43.7
├── @patternfly/react-table@4.50.1
```

**Comment by MariaAga** [comment]
I think this only works for expendable rows, from the html docs:

> Note: To apply padding to `.pf-c-table__expandable-row`, wrap the content in `.pf-c-table__expandable-row-content`. For no padding add `.pf-m-no-padding` to `.pf-c-table__expandable-row` > `<td>`

https://www.patternfly.org/v4/components/table/html#expandable-with-nested-table-example

**Comment by mcoker** [comment]
@jonkoops - @MariaAga is correct, that's a feature of expandable row cells. If you have a use case for regular cells without padding, would you mind sharing that? Seems like something we could add.

**Comment by jonkoops** [comment]
We're using the table in a form, where we also want to align some inputs inside of the table with the rest of the form (see below). 

![image](https://user-images.githubusercontent.com/695720/152001506-970d5b12-8634-48ec-a9d7-2a111f56ae91.png)

Here the inputs in the 'Annotations' section are actually in a table. This is the code that I am using to back it up:


```jsx
<TableComposable variant="compact" borders={false}>
  <Thead className="pf-u-screen-reader">
    <Th>{t("attributes-group:keyColumnHeader")}</Th>
    <Th>{t("attributes-group:valueColumnHeader")}</Th>
    <Th>{t("attributes-group:actionsColumnHeader")}</Th>
  </Thead>
  <Tbody>
    {annotationsControl.fields.map((item, index) => (
      <Tr key={item.id}>
        <Td className="pf-u-p-0 pf-u-pr-xs">
          <TextInput
            name={`annotations[${index}].key`}
            ref={form.register()}
            placeholder={t("attributes-group:keyPlaceholder")}
          />
        </Td>
        <Td className="pf-u-p-0 pf-u-pl-xs">
          <TextInput
            name={`annotations[${index}].value`}
            ref={form.register()}
            placeholder={t("attributes-group:valuePlaceholder")}
          />
        </Td>
        <Td className="pf-u-p-0" isActionCell>
          <Button
            variant="link"
            title={t("attributes-group:deleteAnnotationText")}
            aria-label={t("attributes-group:deleteAnnotationText")}
            isDisabled={annotationsControl.fields.length === 1}
            onClick={() => removeAnnotation(index)}
          >
            <MinusCircleIcon />
          </Button>
        </Td>
      </Tr>
    ))}
  </Tbody>
</TableComposable>
```

**Comment by mcoker** [comment]
@jonkoops is the table here just for layout, or does it serve some other purpose? I suspect you could do this just using the form component and a layout (like the [flex layout](https://www.patternfly.org/v4/layouts/flex)) in place of the table and utility classes. I'm happy to put together a demo for you if you'd like.

**Comment by jonkoops** [comment]
Yeah, this is pretty much an existing component in our project that we are using. I think I will refactor this to a different layout as the table seems like overkill.

**Comment by mcoker** [comment]
@jonkoops sounds good. OK to close out this issue?

**Comment by jonkoops** [comment]
Yes, let's
