### ISSUE TITLE
Receiving an AXE violation when using the dropzoneProps in conjunction with the FileUpload component

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-react#6879]
**Describe the issue. What is the expected and unexpected behavior?**
On the openshift console, when upgrading to 2021-16 and 2022-1, the e2e tests are reporting AXE violations with the fileUpload component when used in conjunction with dropzoneProps. 

The AXE error is here: https://dequeuniversity.com/rules/axe/3.5/autocomplete-valid?application=axeAPI

The PR's showing the e2e test errors are:

- https://github.com/openshift/console/pull/10645
- https://github.com/openshift/console/pull/10962

The dropzoneProps adds the attribute autocomplete="off" here: https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L769, and the autocomplete is causing the AXE error.

The code refs in the console are here: 

- https://github.com/openshift/console/blob/master/frontend/packages/console-shared/src/components/formik-fields/FileUploadField.tsx#L6
- https://github.com/openshift/console/blob/master/frontend/packages/dev-console/src/components/import/jar/section/JarSection.tsx

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Run e2e tests on the console with the last two pf releases
**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug
**What is your product and what release version are you targeting?**
4.11

**Comment by jschuler** [comment]
Once this PR gets into a release, OS should upgrade to that and it should pass those a11y tests again
https://github.com/patternfly/patternfly-react/pull/6873
