### ISSUE TITLE
Menu uses `role="menubar"` incorrectly 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-react#6881]
**Describe the issue. What is the expected and unexpected behavior?**

## `role="menubar"` is used incorrectly in menu implementation.

@jessiehuff @mcoker 

![Screen Shot 2022-02-02 at 11 26 20 AM](https://user-images.githubusercontent.com/5385435/152195019-ba73cfa3-ae6d-4a2e-a27d-c5124fcd3db6.png)

https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#menubar

```
menubar (role)§
A presentation of menu that usually remains visible and is usually presented horizontally.

The menubar role is used to create a menu bar similar to those found in Windows, Mac, and Gnome desktop applications. A menu bar is used to create a consistent set of frequently used commands. Authors SHOULD ensure that menubar interaction is similar to the typical menu bar interaction in a desktop graphical user interface.

To be keyboard accessible, authors SHOULD manage focus of descendants for all instances of this role, as described in Managing Focus.

Elements with the role menubar have an implicit aria-orientation value of horizontal.
```
Looks like the issue was introduced here: https://github.com/patternfly/patternfly-react/pull/5789/files#diff-b36dd79f43392929bd33775b355ed31e3307fc83c7f18bf61b897fee3d4d4dc2R17

![Screen Shot 2022-02-02 at 11 30 13 AM](https://user-images.githubusercontent.com/5385435/152196260-509122e5-7fc2-4483-9d07-92b373d307bd.png)

Also, looks like we have a `role` conflict on the child `<li role="none">`. `role="none"` is correct, however this role [cannot be focusable (either natively or using tabindex)](https://dequeuniversity.com/rules/axe/4.2/presentation-role-conflict). 

![Screen Shot 2022-02-02 at 11 32 13 AM](https://user-images.githubusercontent.com/5385435/152196190-cd0702df-8ccf-45c5-a3cc-0904da32fb95.png)

```
Ensure that each element with role="none" or role="presentation" does not have one of the following characteristics:

A global ARIA attribute
Is focusable (either natively or using tabindex)
```

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

Visible in all menu implementations

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, not blocking

**What is your product and what release version are you targeting?**

PF next release

### In menu
```
.pf-c-menu
  .pf-c-menu__list(role="menu")
    .pf-c-menu__list-item(role="none") // remove tabindex
      .pf-c-menu__item(role="menuitem")
```

### In nav
```
.pf-c-nav.pf-m-horizontal
  .pf-c-menu(role="menubar")
    .pf-c-menu__list(role="menu")
      .pf-c-menu__list-item(role="none") // remove tabindex
        .pf-c-menu__item(role="menuitem")
```

**Comment by jessiehuff** [comment]
I think this suggestion makes sense to me.
