### ISSUE TITLE
Using ExpandedSection inside Form breaks spacing between FormGroups

### ISSUE THREAD

**Issue by skobyda** [patternfly/patternfly-react#6891]
When using ExpandableSection in Form, the spacing in FormGroup between elements (Field3 and Field4 in the screenshot) inside the ExpandableSection gets broken. 
 
![Screenshot from 2022-02-04 13-47-38](https://user-images.githubusercontent.com/42733240/152531698-079d5843-99b7-4878-b7c0-d2a6139f1c3f.png)

How to reproduce:
```
<Form isHorizontal>
    <FormGroup label="Field1">
        <TextInput />
    </FormGroup>
    <FormGroup label="Field2">
        <TextInput />
    </FormGroup>
    <ExpandableSection toggleText={"Additional options"} isExpanded>
        <FormGroup label="Field3">
            <TextInput />
        </FormGroup>
        <FormGroup label="Field4">
            <TextInput />
        </FormGroup>
    </ExpandableSection>
</Form>
```

**Comment by nicolethoen** [comment]
Hello @skobyda! Thank you for opening this issue.

I'd wonder if the `Field group` feature of PatternFly forms might serve your purpose for expandable sections?
https://www.patternfly.org/v4/components/form#field-groups
