### ISSUE TITLE
ReferenceError: navigator is not defined when use Select in VSCode extension webview

### ISSUE THREAD

**Issue by mgubaidullin** [patternfly/patternfly-react#6892]
I'm using Select component in VSCode webview extension (https://github.com/apache/camel-karavan/tree/main/karavan-vscode)
After upgrade to 4.192.15 I got an error `ReferenceError: navigator is not defined`

https://github.com/patternfly/patternfly-react/blob/7f06125cfb52884708107da82ca3800207c9846f/packages/react-core/src/components/Select/Select.tsx#L227

**Comment by jschuler** [comment]
Looks like this is fixed in this PR
https://github.com/patternfly/patternfly-react/pull/6873
Included in `react-core@4.192.19`

**Comment by nicolethoen** [comment]
closed via https://github.com/patternfly/patternfly-react/pull/6873
