### ISSUE TITLE
Add PF4 Content: Text Component

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#692]
Add PF4 Content Components for the Text Component: https://pf-next.com/components/Content/examples/

Additional issue will be added for other content components, separate from this issue. 

In addition to a React review, this issue should be reviewed by the core contributors of this demo:
CSS: @matthewcarleton

**Comment by dmiller9911** [comment]
Note: This component should probably be broken into many for the react implementation or even possibly the core. It has a ton of child selectors targeting elements. It is likely that the styles from this component will cause some unforeseen style changes in a component-based architecture, like React. It would be better to have the padding/margins for content to be part of this component, and then have components for the body text, bullet list, detail list, titles (already done), etc.

**Comment by LHinson** [comment]
Thanks @dmiller9911 for the input there. 

@jschuler given this information, which component from the content would be required to ensure that the nav + page layout looks as it should? I'd be interested in completing that first as well as breaking out the issues as necessary for React. If we need changes on the Core side, I'd suggest we first discuss with @matthewcarleton

**Comment by jschuler** [comment]
The nav+page layout demo right now just has an `<h1>` and `<p>` elements. So maybe a ContentHeading and a ContentBody component would be granular enough
