### ISSUE TITLE
Table Composable: Actions: rowId returns undefined

### ISSUE THREAD

**Issue by aferd** [patternfly/patternfly-react#6925]
**Describe the issue. What is the expected and unexpected behavior?**
row returns undefined. Clicking on the 'Some Action' returns 'clicked on Some action, on row: **undefined**

[sandbox](https://codesandbox.io/s/5d4ym?file=/index.js)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug

**Comment by josejulio** [comment]
The same issue is seen in the demo: https://patternfly-react.surge.sh/components/table#composable-actions
Instead of receiving the rowId/index we get undefined.

@tlabaj could you take a look? thanks!
