### ISSUE TITLE
Topology: Convex algorithm for nodes of different sizes looks wired

### ISSUE THREAD

**Issue by jerolimov** [patternfly/patternfly-react#6968]
**Describe the issue. What is the expected and unexpected behavior?**
The hull algorithm used to draw the outline of or groups on topology was built to support nodes of the same size. It identifies the point of the node and then adds padding. If all nodes are the same size, the tangent lines between nodes always intersect the circle outline of the nodes where a 90 degree angle could be formed that goes to the center of the node.

This however doesn't work with nodes of different sizes are shown here:

![image](https://user-images.githubusercontent.com/139310/155303817-dd8034a2-880e-4f74-b5dc-1f39066e4f10.png)

Another example:

![image](https://user-images.githubusercontent.com/139310/155303831-b6bf225e-d701-44b2-b2b9-a658a1729ea6.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

n/a

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
More a bug, but also an enhancement :smirk: 

**What is your product and what release version are you targeting?**
OpenShift Developer Console, this is a known issue since 4.6, and was reported initially as [ODC-2071](https://issues.redhat.com/browse/ODC-2071), but since the code was extracted into @patternfly/react-topology we believe we should follow up this issue here.

**Comment by jeff-phillips-18** [comment]
Closing in favor of https://github.com/patternfly/react-topology/issues/14
