### ISSUE TITLE
Table Composable: Actions: Dropdown still shows when all actions are outside of it

### ISSUE THREAD

**Issue by josejulio** [patternfly/patternfly-react#6969]
**Describe the issue. What is the expected and unexpected behavior?**

I created a TableComposable with 2 actions outside of the dropdown but no action inside it.

Expected behavior: only 2 actions are visible
Actual behavior: 2 actions and the dropdown are visible. The dropdown has no action and shows empty

![Screenshot_2022-02-23_07-24-12](https://user-images.githubusercontent.com/3845764/155338234-8f9ad3f7-bead-4c40-9e03-1bf644e8feb9.png)
![Screenshot_2022-02-23_07-23-58](https://user-images.githubusercontent.com/3845764/155338236-6eef9e44-1ffd-4488-ad02-406a2866655d.png)
![Screenshot_2022-02-23_07-27-30](https://user-images.githubusercontent.com/3845764/155338914-1f2f2ea3-fd49-45b5-b820-b059ac47f1da.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Add only actionts outside the dropdown of a TableComposable
https://codesandbox.io/s/cocky-frog-gurryh?file=/index.js:600-617

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug

**What is your product and what release version are you targeting?**

Notifications & Integrations

**Workaround**
We can set the the following in the actions:
`actionsToggle: (_props) => <React.Fragment />` to hide it.

**Comment by nicolethoen** [comment]
hello @josejulio 
We are aiming to release the example added in [this PR](https://github.com/patternfly/patternfly-react/pull/6979) next week. It shows how to use an overflow menu in the composable table instead of an actions column in situations like yours so that the columns are all still responsive :)

I think this should address this issue

**Comment by josejulio** [comment]
Thanks!

**Comment by nicolethoen** [comment]
Hi @josejulio
We released the new example this morning. You can view it here: https://www.patternfly.org/v4/components/table#composable-actions-overflow
Does it meet your needs?

**Comment by josejulio** [comment]
> Does it meet your needs?

Looks like it does. thanks!
