### ISSUE TITLE
Drag and Drop: Feature request for DragHandler support

### ISSUE THREAD

**Issue by jerolimov** [patternfly/patternfly-react#6982]
**Describe the issue. What is the expected and unexpected behavior?**
Based on your documentation https://patternfly-react.surge.sh/components/drag-and-drop/ and the code of the Drag n Drop code https://github.com/patternfly/patternfly-react/tree/main/packages/react-core/src/components/DragDrop I miss a feature other D&D libraries are calling "Drag Handler".

In your basic example, you show how to implement a reorderable list with the components `DragDrop`, `Droppable` and `Draggable`.

But sometimes it is required that just a sub-component is "moveable" (which means not the complete `Draggable` child).

For example, when using input fields, this doesn't allow the user to select their input anymore:

![Peek 2022-02-28 10-23](https://user-images.githubusercontent.com/139310/155957673-1ab3142a-681b-4bce-af9f-34be3922b55d.gif)

A common pattern to fix this is adding a "DragHandler" only to a part of the child elements so that the user can drag the complete element only there. For example:

![Peek 2022-02-28 10-27](https://user-images.githubusercontent.com/139310/155958292-ccebaa32-3622-4fe5-af97-0d8bf82f507f.gif)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
https://codesandbox.io/s/patternfly-drag-and-drop-missed-draghandler-0h03tx

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement / feature request

**What is your product and what release version are you targeting?**
OpenShift console

**Comment by tlabaj** [comment]
cc @nicolethoen
