### ISSUE TITLE
Dropdown - menuAppendTo is missing from docs

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#6985]
In the dropdown component docs, we have an [append menu document body example](https://www.patternfly.org/v4/components/dropdown#append-menu-document-body) that uses `menuAppendTo`,  but that prop is missing from the docs. I checked the select component docs and it's listed there. I'm not sure what all components support that prop but it might be good to double check the docs for those components, too.

**Comment by tlabaj** [comment]
@mcarrano we had to revert the PR that closed this.  Can you reprioritize this issue please.
