### ISSUE TITLE
Expandable section: update toggle to support a badge

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-react#6996]
**Describe the issue. What is the expected and unexpected behavior?**
We have a design where we would like to include a badge as part of the expandable section toggle to provide a count of items listed in the section. The `toggleText` prop only supports string values, which prevents us from including the badge

Below are some examples:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/21063328/156769046-fb043d73-6aae-488c-be32-4cea73d1c3c2.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/21063328/156769079-011614e0-8867-4fa8-8fd1-9efe959154fa.png">

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Enhancement. 

**What is your product and what release version are you targeting?**
This is a pattern for the App Services bundle on consoledot. This is not critical functionality, and more of an enhancement we would like to include.

**Comment by nicolethoen** [comment]
I think this will be addressed whenever we implement the feature for [this additional request](https://github.com/patternfly/patternfly-react/issues/6967)

**Comment by mcarrano** [comment]
@jgiardino we will get this on our roadmap. We have a related request on the roadmap for June so we would look to get this in at the same time. @mcoker can you take a look to see if this would need any core work first.

**Comment by mcoker** [comment]
> take a look to see if this would need any core work first.

@mcarrano it shouldn't - assuming you can put whatever you want in the toggle, you can use a layout to manage the spacing and alignment

<img width="1012" alt="Screen Shot 2022-03-16 at 6 13 28 PM" src="https://user-images.githubusercontent.com/35148959/158706464-2f6c2d9d-0cac-468f-bb37-cec5797cf07f.png">

**Comment by mcarrano** [comment]
@jgiardino for housekeeping purposes, I am going to close this as a duplicate in favor of https://github.com/patternfly/patternfly-react/issues/6967 which is a more generalized version of the same issue. This is currently on our roadmap for June.
