### ISSUE TITLE
Possible bug on Clipboard Copy component position property

### ISSUE THREAD

**Issue by carlosga** [patternfly/patternfly-react#6997]
Hello:

The ClipboardCopy component has a position property declared as PopoverPosition

```typescript
  /** Copy button popover position. */
  position?:
    | PopoverPosition
    ...
```

but, the ClipboardCopyButton uses a Tooltip and has it's position property declared as TooltipPosition:

```typescript
  /** Position of the copy button tooltip */
  position?:
    | TooltipPosition
    ...
```

¿shouldn't the ClipboardCopy position property be declared as TooltipPosition instead ?

Thanks in advance.

**Comment by nicolethoen** [comment]
we can probably solve this for now by making both types a union of the two position enums
