### ISSUE TITLE
Fix vertical positioning of an image in Menu toggle

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#6998]
Follow up to https://github.com/patternfly/patternfly/pull/4701

**Comment by wise-king-sullyman** [comment]
@mcarrano I'm unsure what exactly this issue is meant to address.

Should it be enabling the addition of `.pf-m-avatar` (as @mattnolting suggested in the opening comment of the linked PR?

**Comment by mcarrano** [comment]
@wise-king-sullyman I am not really sure, either. I think it's just as you said, but you should confirm with @mattnolting or @mcoker next week.

**Comment by mcoker** [comment]
@mcarrano @wise-king-sullyman that update just removes support for the `.pf-c-menu-toggle__image` element in the menu toggle component, and it updates a couple of examples. I couldn't find support for the `.pf-c-menu-toggle__image` element in the react component - maybe you can keep me honest and verify that, and we could also update the examples to match core if that makes sense.

**Comment by wise-king-sullyman** [comment]
@mcoker I'm also not seeing `.pf-c-menu-toggle__image` being used in React, so to confirm we don't need to do anything for that on the React side right?

I can definitely update the React examples to match core.
