### ISSUE TITLE
Enhancement: Convert CSS to Styled Components

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#70]
I'm not sure if there is interest in the PatternFly community for this, but https://www.styled-components.com/ is a very neat and powerful way to express styles in React components, and has been gaining popularity lately.  It provides a lot of benefits, the most compelling of which for me is that it would make components more modular, and useful alongside components styled differently without the risk of CSS collisions.

Just a thought, I would love to work on converting components if there is interest :)

**Comment by jtomasek** [comment]
I like styled components too but I'd like to see more detail on what does it mean in terms of whole patternfly ecosystem. Potential problem with this approach is that patternfly styles are defined in separate library and patternfly-react as well as other patternfly js libs are reusing them.

Do I understand it correctly that using styled components would mean we'd have to rewrite the styles for the components which are currently defined in patternfly lib? I think that would mean code duplication and additional maintenance burden on our side.

Another question is whether future versions on patternfly lib would be more component oriented or even consider using styled-components if that was generally useful for other ecosystems, not just react js.

On the other hand, I am absolutely OK with using styled-components to add patternfly-react specific styles tweaks to the components. I think for that it is ideal use. We currently have patternfly-react.less for that, but I like using styled components better.

**Comment by mturley** [comment]
I like that approach. Good points.

**Comment by priley86** [comment]
The #1 front-end topic of 2017 😸 

I have a lot of thoughts on this, but I think the material-ui team did a great job comparing some of the "CSS in JS" libraries recently here:
https://github.com/oliviertassinari/a-journey-toward-better-style

Of the ones I've looked at so far, I like [Glamorous](https://github.com/paypal/glamorous) the most b/c it can be compiled to "real CSS" (for performance reasons inline styles can be avoided, see [speedy mode](https://github.com/threepointone/glamor#speedy-mode)) , and would support things like [rtl](https://github.com/kentcdodds/rtl-css-js) for better internationalization support of our UIs. It also supports Slots and Web Components now if we ever decide to explore those in the futrue. 😄 

That being said, this is a very big jump for our current design team. I would be happy to introduce such a thing in PF React _slowly_ if we get community support for it and agree w/ @jtomasek 's points about cautioning this. It's also important that we share CSS w/ the Angular teams at RH where possible in PF Core...

**Comment by priley86** [comment]
thanks @mturley for bring this one to light!

**Comment by priley86** [comment]
i would be curious to hear @ohadlevy's thoughts on this issue too...

**Comment by mturley** [comment]
Thanks for your reply, @priley86. I hadn't looked at Glamorous yet, I'll check that out.

As @jtomasek mentioned, the fact that the Patternfly CSS is currently shared between multiple projects means that moving those styles into the React components definitely would be a maintainability nightmare.  I hadn't realized when I first posted this issue that the styles were in a separate library (that seems pretty obvious now.. go easy on me, I'm new 😏 ).  The benefits would absolutely not be worth the code duplication.

I wonder if there is a good way to take advantage of the benefits of CSS-in-JS, without duplicating the code?  Maybe there could be automation in place to take the styles as they are written and compile them back to raw CSS for compatibility with other libs?  I suppose that would require the new styles in patternfly-react to be source of truth for Patternfly CSS, so maybe that's not a great plan either.  No need to force angular projects to take patternfly-react as a dependency just so they can get the CSS.

Anyway, I'm getting ahead of myself... maybe it's not worth it to take this further, but I'm glad I got this discussion started. If nothing else, @jtomasek I like your idea of using CSS-in-JS instead of `patternfly-react.less` for the react-specific tweaks.

**Comment by priley86** [comment]
+1 @mturley ... also great meeting you today after orientation! A warm welcome to Red Hat ;)

What initially got me turned onto Glamorous was this demo by Kent Dodds (I'm a big fan). I love love love the demo of jest-glamor-react... and introducing the ability of "true" css regression testing with Jest. This was a jaw dropping moment for me when I first saw it. He did waht ?!? 😮 

Fast forward to 23 minute mark if this sounds interesting...
https://www.youtube.com/watch?v=3-4KsXPO2Q4&feature=youtu.be&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf

**Comment by mturley** [comment]
Thanks! That does look pretty awesome.

**Comment by mturley** [comment]
@priley86 should we close this issue? It's clear that we have reasons not to move all the CSS into JS like I was originally thinking. Or should we leave it open just to track the idea of maybe doing something with it later?

**Comment by priley86** [comment]
@mturley I'm fine with closing this for now. Let's revisit this later when ready and remember to re-open this issue when the time comes ;)
