### ISSUE TITLE
Table - Update "Custom row wrapper" example

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#7037]
Want to update the Custom row wrapper example for tables so it doesn't get confused with selected rows which have the same styling. It's this example: https://www.patternfly.org/v4/components/table#composable-custom-row-wrapper-header-tooltips--popovers.

A design recommendation can be found here: https://github.com/patternfly/patternfly-design/issues/963#issuecomment-1058397366  This sets a background of pf-color-blue-400 with 50% opacity.

**Comment by tompsota** [comment]
@mcarrano I couldn't find `--pf-color-blue-400` color, is this really correct color code? I assume that it was meant to be `--pf-global--palette--blue-400`. 
Anyway, adding opacity to hex color stored in variable is quite complicated and would add unnecessary complexity to the demo in my opinion. (It would require to extract the hex code from computed style of the html document and add the alpha programatically)

Could we consider using a different color instead? Maybe `--pf-global--palette--blue-100` or `--pf-global--palette--blue-200`. Those colors are lighter so we won't need to use alpha

**Comment by mcarrano** [comment]
@tompsota Yes, you are probably right here that we really meant `--pf-global--palette-blue-400`. I get what you are saying about applying opacity. @mceledonia can you help out here? What do think about using something like `--pf-global--palette-blue-400` to highlight rows. Here is the original issue for reference: https://github.com/patternfly/patternfly-design/issues/963

**Comment by mceledonia** [comment]
`--pf-global--palette--blue-50` was added for this exact purpose if I'm understanding the need correctly. Light blue background color in a light theme is what blue-50 was made for!
