### ISSUE TITLE
Topology Component : Group icons / edges refresh

### ISSUE THREAD

**Issue by jpinsonneau** [patternfly/patternfly-react#7092]
**Describe the issue. What is the expected and unexpected behavior?**
On Topology Component, some components doesn't refresh correctly:
- Collapsing a group doesn't refresh it's icon correctly:
![image](https://user-images.githubusercontent.com/91894519/159248194-3475d87c-6a1a-4f9d-afd2-dcf8a9d6c377.png)
The groups is blank until you click on it:
![image](https://user-images.githubusercontent.com/91894519/159248223-6005f782-ca12-47da-8896-e7a007575b30.png)
- Labels (text / color) are not updated on edges:
![image](https://user-images.githubusercontent.com/91894519/159249017-e94d0daf-9a7a-44ac-b85d-9a776921f34b.png)
Style is updated but labels doesn't:
![image](https://user-images.githubusercontent.com/91894519/159249092-1c15e69e-9949-440e-8bc5-82f9f636ba74.png)
Label is updated on click (here it's undefined so it disappear but it's the same on value change):
![image](https://user-images.githubusercontent.com/91894519/159249229-06fe6634-89a5-470d-9faa-d8c9fa4e96df.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

You can try our current implementation:
https://github.com/netobserv/network-observability-console-plugin/pull/97

I will try to do a CodeSandbox if needed

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug - work around is to force render updating / recreating model but it may be tricky and not performant.

**What is your product and what release version are you targeting?**
Openshift 4.10

**Comment by jeff-phillips-18** [comment]
@jpinsonneau These are working fine in the `Topology Package` in the demo app. If you could create a CodeSandbox that exhibits the problem that would be very helpful.

**Comment by jpinsonneau** [comment]
@jeff-phillips-18 you are right, it was a `import` mistake in my code skipping `observer` that made refresh issues. 
Both groups & edges refresh now works correctly :+1: 

Sorry for the false issue !
