### ISSUE TITLE
Pluralize helper function doesn't pluralize properly

### ISSUE THREAD

**Issue by AlexSCorey** [patternfly/patternfly-react#7109]
Navigation component overwrite pluralization.
This [line](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/helpers/util.ts#L248) overwrites my plural page title I send to PF and messes up my translations.  Also, English pluralization is not as simple as adding a `S` at the end of a word.

https://github.com/ansible/awx/issues/11400

**Comment by michpetrov** [comment]
@AlexSCorey I don't assume you have a reproducer? Since you provide the plural form yourselves the `pluralize` method shouldn't be attempting to construct it, so this looks like the data aren't being passed properly between your component and PatternFly.

**Comment by tlabaj** [comment]
@AlexSCorey just following up on if this is still an issue for you or did suggestion above help you?

**Comment by AlexSCorey** [comment]
@michpetrov We are using the patternfly component in this file. https://github.com/ansible/awx/blob/devel/awx/ui/src/components/Pagination/Pagination.js#L23.  You can see we have declared the titles prop with a `pages` value.  However, if you look at the issue linked above you will see that the translation isn't occurring properly. This is why I think the PF code is overwriting our props and adding a `s` onto a translated string.

🤷‍♂️

**Comment by AlexSCorey** [comment]
Tested it out again in our dev environment and I too can't reproduce this issue.  Not sure what changed but thanks for looking into it.
