### ISSUE TITLE
Expandable - Allow for any React node to be passed as toggleText

### ISSUE THREAD

**Issue by jeffpuzzo** [patternfly/patternfly-react#7120]
**Is this a new component or an extension of an existing one?**
Existing component: Expandable

**Describe the feature**
Allowing any React node to be passed as toggleText instead of just a string.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
https://marvelapp.com/prototype/2c7hh33g/screen/83354433
The OCM team's existing ROSA wizard design requires elements to appear conditionally alongside the title of the Expandable:
![image](https://user-images.githubusercontent.com/96431149/160140130-52868ad2-0ef9-4ba4-a692-d6b9d3662be7.png)

**Current prop:** `toggleText: string`
**Expected prop:** `toggleText: React.ReactNode`

**Comment by nicolethoen** [comment]
This request is similar to the following two issues:
https://github.com/patternfly/patternfly-react/issues/6967
https://github.com/patternfly/patternfly-react/issues/6996

so hopefully they can all be addressed together.

**Comment by mcarrano** [comment]
@jeffpuzzo we reviewed this and looks like we already have a similar request in our backlog (https://github.com/patternfly/patternfly-react/issues/6996) Closing as a duplicate.
