### ISSUE TITLE
[Wizard] - Update description field to allow a <div>

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#7122]
Want to update the description field of the wizard to allow a `<div>` as well as a `<p>` tag, Core PR: https://github.com/patternfly/patternfly/pull/4708

@mcoker anything to add?

**Comment by mcoker** [comment]
Just that it should be enabled via a `component` prop, then in a breaking change we should make it a `<div>` by default and could remove the `component` prop if we wanted, since the user can then put whatever they want in the `<div>`
