### ISSUE TITLE
[Calendar month] - add disabled dates

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#7124]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
Calendar Month 

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
The Calendar month is missing the feature to disable a date.  

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.
See this core example 
https://www.patternfly.org/v4/components/calendar-month/html#range-start-date-selected-end-date-hovered

**Any other information?**

**Comment by thatblindgeye** [comment]
Per this commment https://github.com/patternfly/patternfly-react/pull/7082#issuecomment-1084628267, it looks like the functionality to disable dates is present in the component (via the `validators` prop).

Also noted in the comment mentioned above, could this issue instead be changed to adding an example showing disabled dates?
