### ISSUE TITLE
Bug - DatePicker - Can't change months or years

### ISSUE THREAD

**Issue by angoybu** [patternfly/patternfly-react#7126]
**Describe the problem**
`DatePicker` component won't let you change months or years using the interface. If you write date manually, calendar shows correct date.

**How do you reproduce the problem?**
Create a fresh react app using `create-react-app`, install `@patternfly/react-core` and add `DatePicker` to `App`.

**Expected behavior**
When left/right arrows are clicked, calendar should navigate between months.

**Is this issue blocking you?**
Yes. It works again using prerelease version 4.202.5

**What is your environment?**
 - OS: macOS
 - Browser: Chrome and Firefox
 - Version: Chrome 99.0.4844.83, Firefox 98.0.1

**Comment by nicolethoen** [comment]
I believe this will be fixed with the upcoming release this week! Once the update is published, I'll loop back around to this and we can double check

**Comment by nicolethoen** [comment]
was fixed in PR: https://github.com/patternfly/patternfly-react/pull/7077
