### ISSUE TITLE
Bug - Date and time picker - A difference in formatting between: placeholder text vs selected value.

### ISSUE THREAD

**Issue by cfullam1** [patternfly/patternfly-react#7127]
The placeholder text for the date is in a YYYY-MM-DD format. When I use the calendar to select a date it appears in a DD-MM-YYYY format e.g. 03-08-2022

I would have expected that the format shown in the placeholder text would be the same as the format that appears upon selection. 

**Screenshots**
<img width="358" alt="Screenshot 2022-03-28 at 12 48 37" src="https://user-images.githubusercontent.com/89915947/160391704-2b80dd17-96de-4d9b-995b-9a0743008836.png">
<img width="338" alt="Screenshot 2022-03-28 at 12 48 56" src="https://user-images.githubusercontent.com/89915947/160391753-bb5f6586-560b-4c8f-9fb3-b271f5e64c21.png">

**What is your environment?**
 - OS: [iOS]
 - Browser [chrome]

**Comment by nicolethoen** [comment]
@cfullam1 
We definitely need to update [the demo](https://www.patternfly.org/v4/demos/date-and-time-picker) - thank you for noticing that bug!
You can absolutely update the placeholder text to match to returned date format. 
Alternatively, you can update the following line:
`const dateFormat = date => date.toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' }).replace(/\//g,'-');` 
to read `const dateFormat = date => yyyyMMddFormat(date);` and import the `yyyyMMddFormat` helper function from react-core.

Either approach would align the placeholder text with the selected date format.

**Comment by cfullam1** [comment]
No worries, that's great. Thank you @nicolethoen for your help and quick response!
