### ISSUE TITLE
Bug - DatePicker - Can't navigate from current month

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#7136]
**Describe the problem**
Using the DataPicker, I cannot move to the next month, select a month, or change current year.

**How do you reproduce the problem?**
Open up the date picker and attempt to navigate

**Expected behavior**
DatePicker show the month/year being navigated to

**Is this issue blocking you?**
Yes

**Screenshots**
![datepicker-no-nav](https://user-images.githubusercontent.com/11633780/160630330-894d6d13-d06d-45d4-830c-31cdb1aa7a67.gif)

**Comment by nicolethoen** [comment]
Was fixed in this PR: https://github.com/patternfly/patternfly-react/pull/7077
