### ISSUE TITLE
[React-Code-Editor] - [README webpack plugin instructions]

### ISSUE THREAD

**Issue by upalatucci** [patternfly/patternfly-react#7141]
**Is this a new component or an extension of an existing one?**
Only a README change

**Describe the feature**
I think would be great to remember the developers that to use properly the code editor, the `monaco-editor-webpack-plugin` should be not only installed but also added in the webpack configuration

**Any other information?**
I spent several hours figuring out why the syntax highlighting was not working in the editor. I've forgotten to change my webpack configuration!! :smile:

**Comment by nicolethoen** [comment]
Will be addressed in this PR https://github.com/patternfly/patternfly-react/pull/7077

**Comment by upalatucci** [comment]
Great thanks :-)
