### ISSUE TITLE
Core - Add support for React 18

### ISSUE THREAD

**Issue by jonkoops** [patternfly/patternfly-react#7142]
React 18 has been [released](https://reactjs.org/blog/2022/03/29/react-v18.html), code will have to be adjusted to that it is officially supported.

### Checklist
- [x] https://github.com/patternfly/patternfly-react/issues/6919
- [x] Update `@types/react` and `@types/react-dom` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210).
- [x] #7195
- [x] #7216
- [x] #7217
- [x] #7218
- [x] #7282
- [x] #7363
- [x] #7402
- [x] Add `PropsWithChildren` types to components with children
- [ ] Apply migrations from [upgrade guide](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html).
  - [x] #8027
  - [ ] https://github.com/patternfly/patternfly-org/pull/3203
- [ ]  Check for incompatible dependencies and upgrade if necessary.
  - [x] #7706
  - [x] #7826
  - [x] #8577
- [x] #7303
- [x] #7821
- [x] #7827

**Comment by tlabaj** [comment]
@jonkoops Thanks for opening this issue.  We are in the process of investigating impact of supporting  React 18 available in PF.  Our initial investigation found that enzyme adapter does not support React 18. Here is the PRhttps://github.com/patternfly/patternfly-react/pull/6899
We are currently moving our testing to react-testng-library to remove that dependency.  We have several PR already in the works to do so.  
When is your team looking to upgrade?

**Comment by jonkoops** [comment]
We're looking to update as soon as possible, but we also have dependencies that are not yet ready for React 18.

I'd like to help out  with the upgrade so I've opened up a PR #7146 to do some ground work. It's open to collaborators so everyone can push commits to it. If you'd like we can coordinate our efforts there.

**Comment by tlabaj** [comment]
@jonkoops that is great that you would to collaborate.  I am going to copy the "to do" list from your PR to the issue for tracking.

**Comment by mohd-akram** [comment]
Any update on this?

**Comment by jonkoops** [comment]
@nicolethoen could you re-open this issue? Looks like a closing keyword was used in #7706 so this was closed accidentally.

**Comment by siwinski** [comment]
Is there an ETA for React 18 support?

**Comment by nicolethoen** [comment]
React 18 will be supported officially with the next major release of PF, which is tentatively planned to be the first release of 2023.

I believe that this PR: https://github.com/patternfly/patternfly-react/pull/7146 made patternfly React 18 compatible, but I imagine there would still be hiccups fully incorporating it into a React 18 app until we can drop support for React 16 official with that next major release

**Comment by jonkoops** [comment]
Hmmm, I don't think this is stale. There is still some work to be done for proper React 18 support that I haven't gotten to (mostly dependencies).

**Comment by jonkoops** [comment]
Thanks @tlabaj!

**Comment by jonkoops** [comment]
React 18 support has landed a while ago, closing.
