### ISSUE TITLE
[Filters] - create new Filters demo page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#7153]
**Describe the feature**
Create a new Filters demo page where we can start to aggregate demos and design documentation that relate to filtering. Start by moving (or copying?) the following demos from their current location onto this page:

* Attribute-value filtering - /text-input-group/react-demos#attribute-value-filtering
* Auto-complete search with type-ahead - /text-input-group/react-demos#auto-complete-search-with-typeahead
* Composable advance search - /search-input/react-demos#composable-advanced-search

**Comment by mcarrano** [comment]
@mmenestr I've opened this issue to start building out a Filters demo page. If there are other things that you think can be added here in a first iteration, feel free to update.

**Comment by mmenestr** [comment]
We should also have the basic filter variations that we talk about in the filter guidelines. Here is a list with the associated mock:
- Basic search using Search input component [[mock](https://marvelapp.com/prototype/7i0dj2d/section/1222618)]
- Single select [[mock](https://marvelapp.com/prototype/7i0dj2d/section/1222619)]
- Checkbox select [[mock](https://marvelapp.com/prototype/7i0dj2d/section/1222614)]
- Attribute filter [[mock](https://marvelapp.com/prototype/7i0dj2d/section/1222613)]
- Filter group - all checkbox selects [[mock](https://marvelapp.com/prototype/7i0dj2d/section/1222616)]
- Filter group - mix of checkbox and single select [[mock](https://marvelapp.com/prototype/7i0dj2d/section/1222617)]
- Faceted filter [[mock](https://marvelapp.com/prototype/7i0dj2d/section/1222615)]

To make these I also looked at current demos we have that we could "repurpose" and edit to create these new demos. For example, some of the table demos. I also don't have any objection to adding the simple table examples to a full page layout, to truly make it a full page demo.

Can also make mocks for the filters you listed above @mcarrano but I think that we could arguably just add them to existing full page table demos as well? let me know what you think

**Comment by mcarrano** [comment]
Looks like this is a duplicate of #6710. Will close.
