### ISSUE TITLE
Chip - allow customizable max-width

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#7167]
Currently, the max width of a chip's text is set via a css variable `--pf-c-chip__text--MaxWidth` to be 16ch. If the text is wider than that, it is truncated and the chip is wrapped in a tooltip. 

We should create a react prop to override the value of the max-width so that it can be wider or never truncate as the consumer desires.

**Comment by bartoval** [comment]
I noticed this component is implemented using classes. 
Perhaps we can make a refactor and transform it into a functional component, like most of the other components. (or at least open an issue to keep track of it)

Is it worth it?
