### ISSUE TITLE
Bug - Table - collums has toggle button in header

### ISSUE THREAD

**Issue by Andrei-Stepanov** [patternfly/patternfly-react#7177]
Table header heas a toggle button.

Rows are expandable.

```
            <Table 
...
                cells={columns}
...
            >
```

What is wrong: Table automatically adds to header a button with toggle icon.

Please check screenshot:

![Screenshot from 2022-04-05 11-45-42](https://user-images.githubusercontent.com/12443962/161727984-a3d897b1-73d0-49a0-9ea2-cbac26c218f4.png)

This button in header is useless, it is necessary to remove it.

    "@patternfly/react-table": "^4.26.7", <--doesn't have this behaviour
    "@patternfly/react-table": "^4.67.5", <-- has this behavioud

I need to remove this button/toggle icon in the table header in the 1 column.

Example in "^4.26.7":

![no toggle button](https://user-images.githubusercontent.com/12443962/161728924-703d535c-8494-450d-85bc-18808f5e1901.png)

**Comment by nicolethoen** [comment]
Hi @Andrei-Stepanov
Thank you for reporting this issue!
I actually merged a fix for this just a couple weeks ago in this PR: https://github.com/patternfly/patternfly-react/pull/7071
And the fix is about to be released this week!

**Comment by Andrei-Stepanov** [comment]
This is cool! Thank you for the fix :-)

**Comment by nicolethoen** [comment]
closed by https://github.com/patternfly/patternfly-react/pull/7071
