### ISSUE TITLE
ouiaSafe property missing from the Docs and not changing?

### ISSUE THREAD

**Issue by Fewwy** [patternfly/patternfly-react#7185]
**Describe the problem**
1)Table component has a property ouiaSafe(default value true) but it's not in the docs (https://www.patternfly.org/v4/components/table) 
2)The ouiaSafe is not represented in the DOM 
3)When I try to change it to false I don't see any changes in the DOM element everything stays the same

**How do you reproduce the problem?**
Create a table and add ouiaSafe property to it, change it to false and try to find in the DOM

**Expected behavior**
The ouiaSafe property is represented in the DOM

**Is this issue blocking you?**
No but this need a clarification

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
 - Fedora 33: [e.g. iOS]
 - Chrome 
 - Version 99.0.4844.51 (Official Build) (64-bit)

**OCP Insights Advisor**

**Comment by gkarat** [comment]
Hm, the `ouiaSafe` attribute worked correctly to me (was able to set it to false or true => and it was reflected in the `data-ouia-safe` attribute accordingly). 
```  
"node_modules/@patternfly/react-core": {
      "version": "4.198.19",
```

**Comment by Fewwy** [comment]
Ok I will recheck it again after next week

**Comment by tlabaj** [comment]
@Fewwy are not documented in our components.  You can see more info about open UI automation here. https://www.patternfly.org/v4/developer-resources/open-ui-automation

**Comment by Fewwy** [comment]
@tlabaj Hello! Sorry but that's just a page with basic information, I already read through it a couple of times.
To write better tests it's important to understand the behavior of "ouiaSafe" and how it changes.

If you know who could add that information tag them here and let's improve the docs.

**Comment by mcarrano** [comment]
@Fewwy we've added this to an upcoming milestone to improve our documentation approach.
