### ISSUE TITLE
Bug - Label - isCompact doesn't make a label compact

### ISSUE THREAD

**Issue by gkarat** [patternfly/patternfly-react#7196]
**Describe the problem**
The `Label` component, once given an `isCompact=true` property doesn't make the label [compact](https://www.patternfly.org/v4/components/label/#compact). However, if one uses `dist` import, the style is applied. The version `"@patternfly/react-core": 4.162.16"` was used.

**How do you reproduce the problem?**
```
import { Label } from '@patternfly/react-core';

<Label isCompact>Test</Label>
```
results in a label without compact style applied:
![Screenshot 2022-04-08 at 14-46-36 advisor console redhat com](https://user-images.githubusercontent.com/31385370/162438604-4b2b7be4-3e1b-4370-ae35-83859d1049d9.png)

However,
```
import { Label } from '@patternfly/react-core/dist/js/components/Label';

<Label isCompact>Test</Label>
```
results in a compact label as expected:
 ![Screenshot 2022-04-08 at 14-47-35 advisor console redhat com](https://user-images.githubusercontent.com/31385370/162438727-5be69b98-51ca-4f56-92fe-aeeb2b48c849.png)

**Expected behavior**
The compact style is applied to all types of imports.

**Is this issue blocking you?**
Yes. However, this can be resolved if I add extra class name `pf-m-compact` to the Label component.

**What is your environment?**
 - OS: Fedora 33
 - Browser: Firefox
 - Version 94.0

**Comment by mcarrano** [comment]
@tlabaj will verify this issue. Can we reproduce?

**Comment by tlabaj** [comment]
@gkarat I was unable to reproduce this issue in our demo-app or in a code sandbox.  Are you still seeing this issue?

**Comment by gkarat** [comment]
@tlabaj, hi, I couldn't reproduce this again; the parameter works as expected in the latest releases. Thus, there is no action needed. Thank you :)
