### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#72]
t.b.d. cc: @jtomasek

**Comment by sharvit** [comment]
https://github.com/yahoo/react-intl
But why patternfly need to be worried about it?

Supporting right-to-left writing direction can be a nightmare, this can help:
https://github.com/vkalinichev/postcss-rtl

**Comment by waldenraines** [comment]
> https://github.com/yahoo/react-intl
> But why patternfly need to be worried about it?

It's a good questio.  I don't see any strings that need translating in patternfly-react nor can I think of any instance where patternfly-react would include text that isn't overridable by the consumer.

**Comment by priley86** [comment]
Please reference the December 2017 Community meeting where @jtomasek and @vojtechszocs presented on this topic.
https://bluejeans.com/s/vsHaD

Examples can also be found in the following apps:
https://github.com/oVirt/ovirt-engine-dashboard
https://github.com/openstack/tripleo-ui

Closing this issue since it will be an application specific concern. We should keep all language strings overridable (via props or children) in PF-React to support this.
