### ISSUE TITLE
react-docs: Handle PropTypes.oneOfType when displaying the type in the props table

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#720]
For example, if a prop type is:
`PropTypes.oneOfType([PropTypes.string, PropTypes.node, PropTypes.func])`
For the displayed type, instead of `union: , ,`
would expect to see something like 
`string | node | object`

**Comment by amarie401** [comment]
This fix has been merged see: #721 

Will go ahead and close this issue.
