### ISSUE TITLE
[Jumplinks] - [Add demos to match core]

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#7243]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
Jumplinks

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
React does not have demo for 

- [ ] Vertical jump links expanded on mobile
- [ ] Vertical jump links toggle text on mobile

**Comment by mcarrano** [comment]
React demo does have all the same views, but they are combined into a single demo.
