### ISSUE TITLE
Bug - Button - Adding unnecessary CSS class

### ISSUE THREAD

**Issue by ppareekh** [patternfly/patternfly-react#7254]
**Describe the problem**
The button component adding `pf-m-progress` even if `isLoading` prop is false

**How do you reproduce the problem?**
[Sandbox link](https://codesandbox.io/s/beautiful-frog-t31tzm?file=/index.tsx)

**Expected behavior**
`pf-m-progress` CSS class only get added when `isLoading` is true

**Is this issue blocking you?**
No

**Screenshots**
<img width="1534" alt="Screenshot 2022-04-14 at 11 31 07 AM" src="https://user-images.githubusercontent.com/99713013/163755830-7bc72fa9-9390-47d8-8012-10121c417c59.png">

**Comment by nicolethoen** [comment]
Hello @ppareekh! Thank you for opening this issue!

I do believe the Button component is working here as intended.
Essentially, a Button needs special formatting if it is a progress button that _could_ have a loading state. This makes sure that there is enough space for the spinner icon when it's in a loading state. 

By passing a boolean to the `isLoading` prop, you are telling the button that it is a progress button, even if it's not currently in a loading state. If you don't want to have the `pf-m-progress` modifier class applied, you should leave off the `isLoading` prop or possibly pass `undefined` as the value.

**Comment by ppareekh** [comment]
Hello, @nicolethoen Thank you for the clarification
