### ISSUE TITLE
Yarn test: test fails

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-react#726]
I updated master and half of **tests fails**.

I tried to delete `node_modules`, `yarn.lock` and run `yarn install`, but nothing helps.

![screenshot from 2018-10-09 13-37-49](https://user-images.githubusercontent.com/32869456/46667091-ce4f4780-cbc8-11e8-8374-0ef7770ddd5a.png)

I know about https://github.com/patternfly/patternfly-react/pull/719 but I don't want to re-clone the repo as I have open work there.

**Comment by jeff-phillips-18** [comment]
I believe a `yarn build` will solve the issue.

**Comment by rvsia** [comment]
@jeff-phillips-18 

It didn't help. :cry:

**Comment by rvsia** [comment]
Solved by updating **YARN to 1.12.0**
