### ISSUE TITLE
PF4 Switch Component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#728]
Add PF4 Switch Component: https://pf-next.com/components/Switch/examples/
In addition to a React review, this issue should be reviewed by the core contributors of this demo:
visuals: @maryshak1996

**Comment by guillaumevincent** [comment]
We need to discuss about the API for the switch component.
In my first draft (#761) I used the following props `oneLabel`, `noLabel`, `labelOff`, `labelOn`.

Can someone tell me if it's good?

**Comment by guillaumevincent** [comment]
After a discussion on slack, here the new api:

```
<Switch labelLeft="Data Sync" labelRight={<CheckCircleIcon />} />
<Switch labelLeft="Off" labelRight="On" />
<Switch labelRight={checked ? "On" : "Off"} />
<Switch labelLeft={checked ? "On" : "Off"} />
```

Thanks @dmiller9911
