### ISSUE TITLE
Set up Dependabot, Renovate, or something else to automatically keep dependencies up to date in patternfly-react

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#7315]

**Comment by adithyaakrishna** [comment]
@nicolethoen I would like to work on this 👀 

I feel Renovate bot should do the task for us but dependabot also has package vulnerability checking which IMO can be a great addition

**Comment by nicolethoen** [comment]
I think we already have one or both of those bots partly configured. But we have a lot of outdated dependencies, so they could be doing a lot more work.
Definitely let me know if you need any more information
@tlabaj is that okay with you?

**Comment by nicolethoen** [comment]
Closed by https://github.com/patternfly/patternfly-react/pull/9034 & https://github.com/patternfly/patternfly-react/pull/9019
