### ISSUE TITLE
Build simple ComposableDropdown, move current Dropdown examples to Legacy tab

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#7322]
To be determined:
 - how many of the current Dropdown examples/variants needs to built into the ComposableDropdown?
 - will this new page include composable 'demos' to demonstrate how to build out the more complex Dropdown examples?

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj I think that we should support basic variations described in the design guidelines here: https://www.patternfly.org/v4/components/dropdown/design-guidelines#dropdown-variations. These would include a simple dropdown, a dropdown with button styling (primary or secondary) a dropdown with plain styling, a dropdown attached to an icon toggle (kabob or other icon), and split button variants. Menus should support groups and descriptions for items.

It also may be that the thing we currently call an Options menu is really just a dropdown that supports multi-select.

Let me know if this gives you enough to work with and I'll get this into a future milestone.

**Comment by tlabaj** [comment]
@mcarrano I think this is a good starting point for the dropdown.  
Yes.  I wonder if we need the options menu going forward.  I actually think it is closer in functionality to the select.  The dropdown is intended as an action menu and does not have a selected state (does not show the check). The toggle however looks more like the dropdown.

Do you think we should just include a variant to the dropdown that makes it selectable (single and multi)?  The only issue I see is that the the options menu has less variant than the dropdown (e.g. it does  not have split button or primary variants)

**Comment by mcarrano** [comment]
@tlabaj Good questions about what to do with the Options menu. It seems more like a Select that does to propagate the selection to the toggle. But neither does the checkbox select.  After more thought, maybe this belongs more as a type of select than a type of dropdown for the reasons you state. What do you think?
