### ISSUE TITLE
Bug - Menu - Menu requires MenuList and MenuItem

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#7365]
**Describe the problem**
https://github.com/patternfly/patternfly-react/blob/b08f176b3d55fd3feb719db6c02ea0d593405d6b/packages/react-core/src/components/Menu/Menu.tsx#L152-L154 requires that `Menu` contain a `MenuList` with one `MenuItem`.  In https://github.com/openshift/console/pull/11424, I have created a composable menu dropdown that includes a `Switch`.  There is a use case where the composable menu includes no `MenuList` with `MenuItem` (only a `Switch`) and a run time error occurs when using the `Switch` to toggle an optional `MenuList` on (which adds a `MenuList` to the `Menu`) and then off (which removes the `MenuLis`t from the `Menu`) using the `Switch`.

**How do you reproduce the problem?**
See https://codesandbox.io/s/happy-hofstadter-ujv4n3.
1. Click the rendered dropdown
2. Click the switch to turn it on
3. Click the switch to turn it off
4. Note the error

Change line 9 of https://codesandbox.io/s/happy-hofstadter-ujv4n3?file=/DropdownWithSwitchGroups.tsx to `true` and note the bug does not occur.

**Expected behavior**
Should be able to use `Menu` without a `MenuList`.

**Is this issue blocking you?**
No as I developed a workaround included in the above CodeSandbox.

**Screenshots**

https://user-images.githubusercontent.com/895728/166931969-28f53102-2b96-4d9c-99e1-6fc137c7c3a9.mov

**What is your environment?**
 - OS: MacOS
 - Browser: Chrome
 - Version: 100

**What is your product and what release date are you targeting?**
OpenShift 4.11

**Comment by nicolethoen** [comment]
Hi @rhamilto,
The Menu is a component intended to house MenuLists and MenuItems.
I think if you'd like to place more than MenuLists and MenuItems in a Menu - I might suggest using a Panel and placing a menu as well as other controls before the menu within the Panel.
I know the Panel is new, but it was built for cases such as this - I can play with it some to demo for you

**Comment by rhamilto** [comment]
Thanks for the information, @nicolethoen.  My suggestion is to improve the documented examples then.  Knowing about all the various components and how they can and should be used together can be a bit burdensome.

**Comment by nicolethoen** [comment]
absolutely! hopefully in the next few updates we will begin to develop the documentation more and more. We have been adding many new components quickly and sometimes the docs are soon to follow once we have more firmly established their definitions and intended uses.
