### ISSUE TITLE
Charts: Deprecate themeVariant prop for light / dark themes

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#7369]
The charts have a `themeVariant` property, which was intended for light and dark themes. However, PatternFly's dark theme will be enabled by adding `class="pf-theme-dark"` to the `<html>` element.

Since the chart variables will automatically pick up this change, there is no need for `themeVariant` and it should be deprecated.

Note: `themeVariant` was never supported, it always defaulted to the light theme.

**Comment by dlabrecq** [comment]
Merged https://github.com/patternfly/patternfly-react/pull/7372

**Comment by karelhala** [comment]
This PR broke our applications. Can we in the future instead of removing exports adding `deprecate` warning and then removing it?
