### ISSUE TITLE
OverflowMenu - Breakpoint relative to parent/container width

### ISSUE THREAD

**Issue by jmsansan** [patternfly/patternfly-react#7376]
**Is this a new component or an extension of an existing one?**
An extension

What is the existing component, if any?
OverflowMenu

**Describe the feature**
Exactly the same as it is now but relative to container width. When I resize the container, overflowing elements are sent to the overflow menu.

Quick mockup here: [https://wireframe.cc/dv1DhR](https://wireframe.cc/dv1DhR)

**Comment by thatblindgeye** [comment]
@jmsansan in case you missed it, there is some conversation in a PR I opened for this issue (starting at this comment https://github.com/patternfly/patternfly-react/pull/7913#pullrequestreview-1099967147 ). Could you take a look and let us know whether the PR satisfies your use case, or whether you were looking for something else than what the PR does (there are some other ideas mentioned in the PR comments).
