### ISSUE TITLE
Patternfly-react doc returns 404

### ISSUE THREAD

**Issue by paoloantinori** [patternfly/patternfly-react#740]
Hi, I was trying to browse the doc for Patternfly-React here: https://www.patternfly.org/patternfly-react/patternfly-4/

but each link of the menu on the left returns a 404.

This is a sample link url:

`https://www.patternfly.org/patternfly-4/components/brand`
while it seems they should have this structure:

`https://www.patternfly.org/patternfly-react/patternfly-4/components/brand/`

notice the missing `patternfly-react/` prefix.

cc: @seanforyou23 @riccardo-forina

**Comment by dgutride** [comment]
PatternFly 4 documentation lives at patternfly.org/v4 - that link above should not be used anymore
