### ISSUE TITLE
Bug - Drawer - Uncaught TypeError on resize

### ISSUE THREAD

**Issue by KevinFCormier** [patternfly/patternfly-react#7421]
**Describe the problem**
Error appears in the console when resizing a Drawer

**How do you reproduce the problem?**
git clone git@github.com:KevinFCormier/ui-components.git
cd ui-components
npm ci && npm start

1. Navigate to http://localhost:9000/?path=/story/drawer--drawer&args=isResizable:true in browser
1. Click "Open drawer" button
1. Open developer tools
1. Resize the drawer

Observe in console: Uncaught TypeError: Cannot read properties of undefined (reading 'current')

drawerContentRef is undefined in DrawerPanelContent

**Expected behavior**
No console errors.

**Is this issue blocking you?**
No.

**Screenshots**
![image](https://user-images.githubusercontent.com/42188127/168391050-25e4f1cf-a0b4-43b7-81a5-ea992f290de5.png)

**What is your environment?**
 - OS: macOS
 - Browser: Chrome 101.0.4951.54, Firefox 100.0

**What is your product and what release date are you targeting?**
Red Hat Advanced Cluster Management; not yet determined

**Any other information?**
This problem started with @patternfly/react-core 4.202

**Comment by mcarrano** [comment]
Regression from previous release
