### ISSUE TITLE
Bug - [Context Selector] - [screenshots wrong or implementation incomplete]

### ISSUE THREAD

**Issue by jowenn** [patternfly/patternfly-react#7422]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?
[Design guidelines](https://www.patternfly.org/v4/components/context-selector/design-guidelines)
Shows in the "Application-wide impact" and "Navigation-level impact" sections a Context Selector with just two items and no search textbox.

I have this exact use case, my context selector has only to elements, therefor it does not make sense to have  search box. Of course I could just use a regular Dropdown, but semantically it is a context selection.

**How do you reproduce the problem?**
Design guide does not match implementation

**Expected behavior**
Either make search box optional or correct screenshots in design guide

**Is this issue blocking you?**
Workaround with regular dropdown possible

**What is your environment?**
 - Version 2022.05

**Comment by mcarrano** [comment]
We admit that the current way this is presented can be confusing, but in your use case just using a standard [simple Select menu](https://www.patternfly.org/v4/demos/composable-menu#composable-simple-select) should be the best option. Let me know if you have further questions about this.
