### ISSUE TITLE
Popper - remove ToggleMenuBaseProps

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#7438]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
Extends #6985 

**Describe the feature**
Remove deprecated prop interface ToggleMenuBaseProps from Popper and from the components which extend this interface.

**Comment by jenny-s51** [comment]
Picking this up again for the upcoming breaking change release! I had initially worked on this issue and put up the PR for a non-breaking workaround earlier this year

**Comment by nicolethoen** [comment]
Closed by #8235
