### ISSUE TITLE
Bug - ContextSelector - toggleText prop should allow for JSX

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#7457]
Right now the type is set to string, there is a use case to pass in text with an icon, so the type should be set to something like `ReactNode` instead.
https://github.com/patternfly/patternfly-react/blob/5bbf5776f7146b03c36382aa0e8de32781ded672/packages/react-core/src/components/ContextSelector/ContextSelector.tsx#L37

This issue came up in https://github.com/theforeman/foreman/pull/9222

**Comment by adithyaakrishna** [comment]
@mcarrano @jschuler I would like to work on this 👀

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj ^^^

**Comment by nicolethoen** [comment]
@adithyaakrishna I'm happy to assign you! It's scheduled to be included in the 2022.10 release which will have code freeze around August 1st. Let me know if you have any questions or concerns about that deadline :)

**Comment by adithyaakrishna** [comment]
@nicolethoen Thanks for assigning it to me :)

I have made the changes and I wanted to know if the type should only be React.ReactNode or something like toggleText: React.ReactNode | string; 
And if it's only React.ReactNode, how about we rename the param to toggleComponent instead of toggleText?

**Comment by nicolethoen** [comment]
@adithyaakrishna I responded to your questions in the draft PR :)
