### ISSUE TITLE
Table - add/update expandable examples/demos to set column widths

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#7460]
re: https://github.com/patternfly/patternfly/pull/4852

The column widths in expandable tables may shift a bit as expandable rows are toggled open/closed, since the expandable rows are part of the table and the table columns adapt to the content in the table cells. To keep the column widths static when toggling, we've added an example that shows adding set width variations to the expandable table header cells.

For this update in react, I guess it's a question of whether we want to update all of the expandable examples (or at least the ones whose content shifts), or add a new example/demo with the column widths set? @mcarrano wdyt?

**Comment by mcarrano** [comment]
Good question @mcoker I'm not sure. Is there any reason you would not want this behavior? @mmenestr any thoughts?

**Comment by mmenestr** [comment]
I don't think I've ever seen that happen so I'm having a hard time picturing it, but I want to say that we should add it to all tables because it seems like a behavior that would always be wanted?

**Comment by mcoker** [comment]
@mmenestr you can see it by toggling the "parent 2" row here with lorem ipsum in it https://codesandbox.io/s/sleepy-wozniak-el258b
