### ISSUE TITLE
Bug: Data list/Table - selectable variants should only be single select

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#7491]
**Describe the problem**
Per the conversation below, the [Data list selectable rows](https://www.patternfly.org/v4/components/data-list#selectable-rows) variant and the [Table row click handler, hoverable & selected rows](https://www.patternfly.org/v4/components/table#composable-row-click-handler-hoverable--selected-rows) variant should only be single-select (similar to radio buttons).

As mentioned in my original comment below, there was some functionality added to the Data List that would allow either single or multi selectable rows, though currently only single select works (which is the intention). 

**Expected behavior**
The data list component should not have a prop for multi-select rows, and the Table variant linked above should only allow single select rather than multi-select.

### Original comment

PR #7474 adds some new props and improves a11y for selectable data list items, including the ability to pass in whether only a single item or multiple items can be selected (via hidden inputs). Multiple selection does not currently work as intended (can only select one item).

- [x] #7688
- [x] #7689

**Comment by mcarrano** [comment]
@thatblindgeye Selectable rows in the data list component were always intended to be single select. This was introduced to support a use case like in the primary-detail demo here: https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-full-page/  For multi-select use cases, we should be using rows with checkbox selection. Is there a change we need to make to clarify that? Sounds like the current implementation makes this ambiguous.

**Comment by thatblindgeye** [comment]
@mcarrano Ah gotcha. For that use case it does make sense, though I think some confusion may have lied within the Table component example [Row click handler, hoverable & selected rows](https://www.patternfly.org/v4/components/table#composable-row-click-handler-hoverable--selected-rows) having a similar use case, but having that multi-select functionality. This behavior on that example looks to go back several releases (checking the 2022.04 release this behavior is there). 

It sounds like maybe this linked Table example would also need to be updated then to be single select?

**Comment by mcarrano** [comment]
@thatblindgeye Yes, that's a good catch. Seems like this should also be constrained to single-select.

**Comment by thatblindgeye** [comment]
@mcarrano I've updated this issue to reflect the intentions you mentioned and added the bug label.

**Comment by nicolethoen** [comment]
Both the table and data list selectable component examples have been updated! :)
