### ISSUE TITLE
Bug - Log Viewer - logs do not stream in Chrome

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-react#7498]
**Describe the problem**

In Chrome 102.0.5005.61, when the logs update, the logs do not continue to stream even though the user has not interacted with them.  With each log update, the logs pause streaming and the `Resume stream and show X new lines` banner appears at the bottom of `LogViewer`.

https://user-images.githubusercontent.com/895728/171642312-a6a697e1-06ff-4b07-8d74-af27a231d0d7.mov

**How do you reproduce the problem?**

Using an OpenShift 4.10 cluster, view a `cluster-version-operator-*` pod's logs.  Note the behavior.

**Expected behavior**

The logs should continue to stream as they do in Firefox or Safari.

**Is this issue blocking you?**

Yes.  The workaround is to use Firefox or Safari (any non-Chromium-based browser).

**Screenshots**

See above.

**What is your environment?**
 - OS: Mac
 - Browser: Chrome
 - Version 102.0.5005.61

**What is your product and what release date are you targeting?**

OpenShift 4.10+

**Any other information?**

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=2091901

**Comment by DaoDaoNoCode** [comment]
This issue has been fixed in https://github.com/openshift/console/pull/11646, we can close it.
