### ISSUE TITLE
Introduce typescript build support for PF4

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-react#752]
PF4 components need to provide typings for consumption.  We'd like to build the components natively in typescript instead of writing typings that could get out of sync.

This issue is to introduce just build support and convert the propTypes for a single component to illustrate how it should be done.

**Comment by tconn89** [comment]
@dgutride Upon inspection, I already see that components have a `{{component}}.d.ts` file.  For instance, `AboutModal.d.ts` looks like this:
```
import { SFC, HTMLProps, ReactNode } from 'react';

export interface AboutModalProps extends HTMLProps<HTMLDivElement> {
  children: ReactNode;
  isOpen?: boolean;
  onClose?: Function;
  productName: string;
  trademark: string;
  brandImageSrc: string;
  brandImageAlt: string;
  logoImageSrc: string;
  logoImageAlt: string;
  heroImageSrc: string;
  heroImageAlt?: string;
}

declare const AboutModal: SFC<AboutModalProps>;

export default AboutModal;
```

Is this what you meant by supporting PropTypes natively?  I did have to overcome a bug with importing `react-styles` and had to declare new module, but that is a different issue.

**Comment by rachael-phillips** [comment]
Closing this issue
