### ISSUE TITLE
Add a styled system component

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#753]
Expose [PF core css globals](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/_variables.scss) for setting spacers such as padding, margin, font size, font family, line height, colors etc through a `<Box>` component that can be used like this:
`<Box m={2} />`
Looking at utilizing [styled-system](https://github.com/jxnblk/styled-system/blob/master/docs/api.md)

**Comment by LHinson** [comment]
Closing this issue for now since #836 has merged
