### ISSUE TITLE
Charts: Update Victory dependencies

### ISSUE THREAD

**Issue by mgrabovsky** [patternfly/patternfly-react#7614]
Please update the Victory dependencies to at least 36.5.1 as it fixes an annoying bug in build, see FormidableLabs/victory#2307.

Currently, I get a million warnings messages like the following when trying to build a Patternfly app:

    Failed to parse source map from '/www/node_modules/victory-area/es/area.js.map' file: Error: ENOENT: no such file or directory, open '/www/node_modules/victory-area/es/area.js.map'

**Comment by nicolethoen** [comment]
@dlabrecq do you see any issues with this?

**Comment by dlabrecq** [comment]
Should be ok, but I'd like to test this with Cost Management. I had some trouble updating to the latest packages recently.

**Comment by dlabrecq** [comment]
There appears to be a lot of TypeScript changes between v36.5.1 and v36.5.3. This may require a bit of effort to update.

I also encountered a type error with Victory itself, which prevents me from building PatternFly. I had to edit `victory-core/lib/index.d.ts` directly to get any further.

I'll create an issue with Victory to get this one fixed.
![Screen Shot 2022-07-06 at 12 57 26 PM](https://user-images.githubusercontent.com/17481322/177603962-6ce66aca-2e98-45b9-befd-e91674931fd3.png)

**Comment by dlabrecq** [comment]
I was able to resolve the error above, but it requires PatternFly to update to TypeScript "4.7.3".

**Comment by dlabrecq** [comment]
I've updated our dependencies via PR https://github.com/patternfly/patternfly-react/pull/7674.

However, waiting for Victory to fix a TypeScript error in the latest victory-core package.

**Comment by mgrabovsky** [comment]
@dlabrecq What is the current status here, please? It looks like #7674 was closed without merging with no follow-up.

**Comment by dlabrecq** [comment]
We were waiting for a type error fix from Victory -- need to retest the latest packages to see where we are.

**Comment by dlabrecq** [comment]
Unfortunately, I encountered a new Type error that must be fixed in the Victory upstream.

![Screen Shot 2022-09-12 at 1 20 32 PM](https://user-images.githubusercontent.com/17481322/189716919-a21c0419-af27-48e9-a681-5c354674cbe2.png)

**Comment by dlabrecq** [comment]
Pushed a fix to the Victory upstream `https://github.com/FormidableLabs/victory/pull/2464`.
Waiting for the package update now.

**Comment by dlabrecq** [comment]
I pushed a fix to the Victory upstream `https://github.com/FormidableLabs/victory/pull/2464`.
Although, the commit message was changed and merged as a "chore", not a "fix". 
That means a new package was not created automatically. 
Must wait for the next package update.

**Comment by dlabrecq** [comment]
This PR updates Victory dependencies to v36.6.7

https://github.com/patternfly/patternfly-react/pull/7986
