### ISSUE TITLE
Bug - [Flex] - [Flex component loses className]

### ISSUE THREAD

**Issue by Fewwy** [patternfly/patternfly-react#7647]
**Describe the problem**
I have a couple of questions about the Patternfly Flex
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/layouts/Flex/examples/Flex.md

My colleague added the component to the frontend-cloud-components that uses the <Flex> patternfly component as part of it
For some reason, it's losing the className ins-c-rule-details and when I open the page it's nowhere to be found
This is our "component" that has this problem https://github.com/RedHatInsights/frontend-components/blob/master/packages/advisor-components/src/RuleDetails/RuleDetails.tsx#L75

**How do you reproduce the problem?**
Check the production and try to find the ins-c-rule-details through console
https://console.redhat.com/openshift/insights/advisor/recommendations

**Expected behavior**
The added className should be present

**Is this issue blocking you?**
No, but nobody knows why it's happening

**Comment by mcoker** [comment]
@Fewwy I reduced this down to a small example to try and reproduce the issue and it seems to be rendering the `className` value OK - https://codesandbox.io/s/dreamy-cherry-zcffoz?file=/index.js

Are you able to reproduce the issue outside of that page?

**Comment by Fewwy** [comment]
@mcoker Yep, It is working indeed. The bug was fixed on the frontend cloud components side
