### ISSUE TITLE
Topology - Pipeline node icons

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#7648]
**Adding icon decorators to pipeline task nodes**

The basic pipeline task node may require an additional icon to identify specific commit types.  When this feature is enabled there should be two separate tooltips on the node. 

1. hover over the decorator icon identifies its type.
2. hover on the task name writes the full task name (Accomodating truncation)

Designs for this feature can be found at [marvelapp.com/prototype/iadc037/screen/87580727](https://marvelapp.com/prototype/iadc037/screen/87580727)

**Comment by andrew-ronaldson** [comment]
@jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
Fixed by https://github.com/patternfly/patternfly-react/pull/7697
