### ISSUE TITLE
Topology - Adding space for labels/badges in a pipeline task node.

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#7649]
In the new pipelines design we removed the dashed underline that acted as a subtask indicator in pipeline runs. The new version uses a badge to show the count of subtasks and when clicked it shows a popover with information on the subtasks.

<img width="695" alt="Screen Shot 2022-07-04 at 3 43 32 PM" src="https://user-images.githubusercontent.com/28658548/177205221-e17d81f4-c976-426e-895f-c5ff31ddd92a.png">

Another use case is for labels the indicate different statuses on a task. For example a task can be marked outdated if it is no longer in sync or no not needed.

<img width="766" alt="Screen Shot 2022-07-04 at 3 45 42 PM" src="https://user-images.githubusercontent.com/28658548/177205412-5adbd88e-b4a0-4f9c-9da1-0e010322ea9f.png">

Designs are found at [marvelapp.com/prototype/iadc037/screen/87580725](https://marvelapp.com/prototype/iadc037/screen/87580725)

**Comment by nicolethoen** [comment]
@jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
@andrew-ronaldson This has been implemented. If there are any issues with the current version please file issues for them.
