### ISSUE TITLE
Topology - Aggregating edges between node groups

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#7650]
When edges are displayed in larger environments the topology view can be difficult to understand. To help remove clutter on the screen we can aggregate the edges from individual nodes within a group to a single line between node groups layer.
<img width="1285" alt="Screen Shot 2022-07-04 at 4 20 46 PM" src="https://user-images.githubusercontent.com/28658548/177208315-52d80231-0e7c-4492-868b-dc17ce558158.png">

**Comment by andrew-ronaldson** [comment]
@jeff-phillips-18

**Comment by nicolethoen** [comment]
@jeff-phillips-18 - just nudging you again so you're aware this issue is still here

**Comment by jeff-phillips-18** [comment]
Closing in favor of https://github.com/patternfly/react-topology/issues/17
