### ISSUE TITLE
Bug - Number Input - cannot type negative values

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#7659]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?
User cannot type negative values into the number input component. At the moment the "$" example of "With Unit" is the only number input that supports typing negative values - this example works consistently among the staging website and the live docs.

Staging:
https://patternfly-react-main.surge.sh/components/number-input/

Current:
https://www.patternfly.org/v4/components/number-input

**How do you reproduce the problem?**
Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.

1. Go to the staging website
2. Type a negative value into default, it should work.
3. Update any of the other number input demos with any value. 
4. Try to type another negative value into default; it no longer supports typing a `-`.
5. Go to the current pf4 docs website
6. Try typing a negative value into default, it does not work.

**Expected behavior**
A clear and concise description of the expected behavior.
Typing negative values should be supported. Currently it is only possible to have negative numbers by clicking the `-` button on the left of the input field.  

cc @tlabaj

**Comment by MrVSiK** [comment]
If I understand it correctly, the issue exists with the `keyDownHandler` in https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/NumberInput/NumberInput.tsx. I'd like to work on it, assuming it has not been fixed already?

**Comment by CodeDuchess** [comment]
@nicolethoen I can work this ticket. Thanks.

**Comment by tlabaj** [comment]
@MrVSiK are you still interested on working on this?

**Comment by MrVSiK** [comment]
@tlabaj yep

**Comment by MrVSiK** [comment]
NumberInput does seem to handle negative values just fine. The cursor needs to be placed at the beginning of the number in order for negative numbers to be typed.

[Video to clarify what I mean](https://imgur.com/a/KcytuE8)

**Comment by jenny-s51** [comment]
Thank you investigating this @MrVSiK , you are correct that negative values are indeed supported, however that is not the expected behavior here! A consumer should be able to type in a negative value starting with the `-` character. 

Good news though, looks like @kmcfaul 's PR #8304 will resolve this issue once it's merged!
