### ISSUE TITLE
Bug - [Pipeline Topology] - Task node name is not getting updated when element label is changed

### ISSUE THREAD

**Issue by karthikjeeyar** [patternfly/patternfly-react#7719]
**Describe the problem**

Pipeline topology node label is not getting updated when the element's label is changed on the fly.

**How do you reproduce the problem?**
Always

**Expected behavior**
Task name should be changed with element label is changed.

**Screenshots**

Tooltip has the updated label but the task name is not updated.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/9964343/179822101-83b93caf-9bd9-4ede-a3d4-fdac55e92cb1.png">

**What is your product and what release date are you targeting?**
HAC build service

cc: @christianvogt @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar How are you updating the node label?

**Comment by jeff-phillips-18** [comment]
This was fixed by https://github.com/patternfly/patternfly-react/pull/7697
