### ISSUE TITLE
Bug - Select - Dynamic options do not populate on first render when using 'checkbox' variant with hasInlineFilter

### ISSUE THREAD

**Issue by dvail** [patternfly/patternfly-react#7722]
**Describe the problem**

When using a Select component with `variant={SelectVariant.checkbox}` and `hasInlineFilter`, and SelectOptions loaded dynamically (i.e. via network request), the component options are not visible the first time the dropdown is opened. Closing and re-opening the dropdown correctly displays the options.

**How do you reproduce the problem?**

Minimal reproduction in [codesandbox](https://codesandbox.io/s/smoosh-wildflower-u03ph8?file=/src/App.js).

1. Visit codesandbox and open the sandbox console
2. View that the original empty options array is logged during render, followed by the options array containing real values.
3. Open the Select component - you should only see the inline filter.
4. Close the Select component.
5. Open the Select component again. You should now see three options.

**Expected behavior**

The current values of the Select component's options are rendered when the dropdown is opened.

**Is this issue blocking you?**

No known workarounds yet. This is not a product blocker, but blocks updating to the latest PF dependencies.

**What is your environment?**

 - OS: Mac OS
 - Browser: Chrome/Firefox at least
 - Version: Chrome 103 / FF 91

**What is your product and what release date are you targeting?**

Red Hat Advanced Cluster Security (release date N/A)

**Any other information?**

This appears to be an issue only on `@patternfly/react-core` versions `>= 4.224.1`.

[4.224.0 -> 4.224.1 diff](https://github.com/patternfly/patternfly-react/compare/%40patternfly/react-core%404.224.0...%40patternfly/react-core%404.224.1)

**Comment by mkholjuraev** [comment]
We have the same issue, it would be great if this gets attention soon.
