### ISSUE TITLE
Number input - add new Status variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#7730]
Add a new variant of the Number input component to support inserting a status icon into the field (potentially used to warn users about exceeding threshold limits, etc).

Core PR: https://github.com/patternfly/patternfly/pull/4983

**Comment by andyyvo** [comment]
Should the new Status variant be based on the value of the number input? For example, it will only be success or warning (I didn't see a danger rendered) if the number input exceeds or falls below a certain value. I assume that it would to flow with the user experience.

Following up with that, should we allow for the use of two statuses? For example, if it meets a certain number input, then the user gets the success status, but in other cases, it may be a warning status. Having two might become an issue in cases where having no status at all might not mean anything but that is up to discussion. Just some thoughts :D

**Comment by mcarrano** [comment]
@andyyvo while what you are saying makes sense, I wasn't expecting us to code in the logic that decides what Icon to display. I think we would provide the mechanism to pass an icon, but the logic of what icon to display and when would be left to the consumer. This is consistent with the way we've handled similar things, I think. @nicolethoen @tlabaj do you agree with that?

**Comment by nicolethoen** [comment]
@mcarrano we could definitely do it as you describe, but we do have a precedent of showing the inputs with validation on some other examples. I am thinking specifically of the [validated form example](https://www.patternfly.org/v4/components/form#validated).

**Comment by mcarrano** [comment]
Yes, that's true. But in that case, who specifies the validation criteria? I guess this is a similar use case.

**Comment by nicolethoen** [comment]
I would imagine it was arbitrarily chosen by the dev who built that example in the case of the form.

**Comment by gitdallas** [comment]
Currently this only works with `pf-m-status` on the component and `pf-m-warning` on the input. Trying error or info won't add any styles. Should this be the case (warning only) or should it work similar to text-input where they can use error and info as well?

https://www.patternfly.org/v4/components/text-input#invalid 
in the above example you can change the `validation` from error to warning or info and get styling

As far as implementation, I was working to get number-input to work similarly, setting `pf-m-status` on the component if a non-default `validation` existed and then setting `pf-m-[whatever]` based on that value.. however, only `pf-m-warning` would work right now as mentioned.

As only `pf-m-status` exists as a modifier in the number input component styles - I think I'd at least need a modifier for warning... error and info if we want to add them.

@nicolethoen @mcoker
