### ISSUE TITLE
Bug - [Pagination] - [The start index is bigger than the end when switching the perPgae number at the last page.]

### ISSUE THREAD

**Issue by yportfolio** [patternfly/patternfly-react#7734]
**Describe the problem**
The start index is bigger than the end index when you switch perPage number from a smaller number(e.g 10) to bigger(e.g 100) and when you are on the last page already.

**How do you reproduce the problem?**
![Screen Recording 2022-07-25 at 15 28 27](https://user-images.githubusercontent.com/65852944/180723361-b679145f-b2ea-41b1-8d3d-916525c8cef5.gif)

**Expected behavior**
The start index is smaller than the end.

**Is this issue blocking you?**
No, I can set the page number to 1 every time I switch the perPage number. However, it seems better to keep this behavior default or compute the right index.

**Screenshots**
The wrong index is 5201 - 523 of 523:
<img width="890" alt="Screen Shot 2022-07-25 at 15 23 11" src="https://user-images.githubusercontent.com/65852944/180723437-457aac7a-1e6f-4b0b-91a2-845d2de2b413.png">
It should be 501-523 of 523:
<img width="905" alt="Screen Shot 2022-07-25 at 15 42 48" src="https://user-images.githubusercontent.com/65852944/180724485-7f93a54b-23bf-410e-afb8-2d15d4aa7e18.png">

**Comment by michpetrov** [comment]
This looks like a problem with the demo. The `onPerPageSelect` handler should be updating the page number as well:

```
this.onPerPageSelect = (_event, perPage, page) => {
  this.setState({
    perPage, page
  });
};
```
