### ISSUE TITLE
[Popper] - [ investigate enable flip behavior for diagonal positioning]

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#7762]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
Popper.  

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
Investigate enabling flip behavior for diagonal positioning by updating "fallbackPlacements"
https://popper.js.org/docs/v2/modifiers/flip/#fallbackplacements

**Comment by blfetche** [comment]
Hello @tlabaj per todays discussing linking in the below issue as this issue may offer a better solution. 

Original Issue:[ patternfly/patternfly#4754](https://github.com/patternfly/patternfly/issues/4754)

@mcoker
