### ISSUE TITLE
[enhancement] - [add ouiaId properties to WizardNav, WizardNavITem, ClipboardCopy and the Modal close icon]

### ISSUE THREAD

**Issue by gashcrumb** [patternfly/patternfly-react#7767]
There's a few elements that we would like add tags to for user tracking and automation, however there's a few React components that don't appear to offer properties to set a customized ID.  It'd be great if these 3 components offered a `ouiaId` property:

* WizardNav
* WizardNavItem
* ClipboardCopy

Additionally while the Modal component does accept a custom automation ID however the close icon uses a generated ID.  It'd be nice if there was a way to either specify the OUIA ID for the Modal close icon or if the Modal component could perhaps use value built off of the `ouiaId` property it receives.

**Comment by mcarrano** [comment]
@tlabaj can you take a look at this one?

**Comment by tlabaj** [comment]
Hi @gashcrumb traditionally the QE team has added the ouiaId they need for automation.  Would your team be able to add the IDs you need.

**Comment by gashcrumb** [comment]
Yep, one option is I could come up with some generic IDs that are always set on these components, that'd probably work.  I was looking more to update the interface for these components so that we could control the values used at the application layer as the plan is also to use this facility for user tracking as well.  I'll have to investigate if I can come up with a convention using static ids that would satisfy that need.

**Comment by jschuler** [comment]
I think @tlabaj meant that the QE team would update the code to enable OUIA IDs. If you have team members that would like to contribute those changes to PatternFly that would be a way to go about it, or we can open up the issue to the wider team/community.

**Comment by tlabaj** [comment]
Thank you at @jschuler.  Yes that is what I meant.
