### ISSUE TITLE
PF4: TextContent TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#778]
Attempted to pull the latest from PF4 react-core (v1.23.0), pf-next (1.0.57 and 1.0.58) and encountered the following build error. This prevents koku-ui from rendering.

![screen shot 2018-10-16 at 10 35 06 am](https://user-images.githubusercontent.com/17481322/47024414-a06d8400-d12f-11e8-9238-2b4efd880207.png)

I believe this is associated with the following line?
https://github.com/patternfly/patternfly-react/blob/67b0cf1d83470c13bc4b56aeb10746996ea519cd/packages/patternfly-4/react-core/src/components/Text/TextContent.js#L20

**Comment by amarie401** [comment]
@jschuler can you look into this?

**Comment by jschuler** [comment]
This is dependent on a change recently made in react-styles
https://github.com/patternfly/patternfly-react/blob/9cc0092fd876ee251b5b5425ee9191cf6df7bfef/packages/patternfly-4/react-styles/src/StyleSheet.js#L51
Do you have this change?

**Comment by jschuler** [comment]
Should be included in react-styles@2.3.0 from what I can see

**Comment by dlabrecq** [comment]
I retested and see the same errors. Here are my package versions

node_modules/@patternfly/react-core/package.json:  "version": "1.23.1",
node_modules/@patternfly/react-icons/package.json:  "version": "2.5.1",
node_modules/@patternfly/react-styles/package.json:  "version": "2.3.0",
node_modules/@patternfly/react-tokens/package.json:  "version": "1.5.2",

**Comment by jschuler** [comment]
Can you try and see if updating react-core to 1.24.3 resolves this issue?

**Comment by dlabrecq** [comment]
Yes, v1.24.3 is working now -- closing. Thank you!
