### ISSUE TITLE
Investigation(Table): mock REST API for updated table data

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#7795]
Per our discussion @tlabaj @mcarrano - we decided we need to find an online mock REST API that will allow us to paginate all the new table data: https://docs.google.com/spreadsheets/d/1-sqIbCpmFfmID0fByWZSOBpn99ocGyT2KoUZ5B_s3zo/edit#gid=0

The mock API we currently use ([my-json-server.typicode.com](url)) poses some development limitations - it comes with a character limit to the amount of data in the JSON file, and it only lets us make 5 table columns, whereas we need 7 columns to align with the new table data. 

This is an investigation to find a different online REST API that supports fetching all this new data.

**Comment by tlabaj** [comment]
Thank you for investigating.
