### ISSUE TITLE
Search input - advanced search invalid markup

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#7796]
Just a small thing - this element should be a `<div>` since a `<span>` can only accept [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content)

https://github.com/patternfly/patternfly-react/blob/ef241e66080a90616f7eb557b713e39889f1313d/packages/react-core/src/components/SearchInput/SearchInput.tsx#L289

**Comment by nate-j5** [comment]
Heya @mcoker may I be assigned this?

**Comment by mcoker** [comment]
@nate-j5 for sure, thanks!!

**Comment by mcoker** [comment]
@nate-j5 just wanted to check in and see how it's going and if you have any questions. Also we're hoping to get this one in in our current sprint which starts today 🚀 with code freeze in a couple of weeks - end of day September 8th. Do you think you'll be able to submit a PR with this change before then, leaving enough time to work through any sorts of additional updates or feedback?

**Comment by nate-j5** [comment]
@mcoker apologies - I got a new job a few days within making this request and haven't had time to look at it. If things change will circle back and all the best either way.

**Comment by mcoker** [comment]
@nate-j5 - we're 1 week out from code freeze, so just wanted to check in again and see if you think you'll be able to work on this one. Totally fine if not, though I'll probably re-assign it since we're trying to get it in this release if we can. If you'd like a write up on what needs to be done or want to pair up and work through it, just let me know - I'm happy to help if I can!
