### ISSUE TITLE
npm@5 warnings, package-lock.json not tracked in git?

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react#78]
Hey guys,

Is there a reason we don't have a `package-lock.json` file either tracked in git or in the .gitignore?  Are most people not yet on npm@5 for whatever reason?  Ideally we should check this file in.  Every time I run `npm install` it generates one, and it comes up in `git status` as an untracked file.

Also, I'm seeing some other warnings related to npm 4-to-5 migration:

```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

Assuming we all want to use the latest npm, we should address these.

**Comment by priley86** [comment]
+1 ... noticed the same. One of the previous PRs missed this somehow. Hoping to fix in #74 ...

**Comment by priley86** [comment]
can you possibly confirm if we can close this now @mturley ?

**Comment by mturley** [comment]
Yep, this is all fixed now.  Thanks @priley86

**Comment by mturley** [comment]
Oh, well actually I closed this after just reading the title.. I forgot about the prepublish warning.  @priley86 do you think that is worth opening a separate issue for?

**Comment by priley86** [comment]
@mturley it seems that spawn-sync (dep of commitizen) still has a prepublish script causing that warning...  (see `npm ls spawn-sync` output)
https://github.com/ForbesLindesay/spawn-sync/blob/master/package.json#L16

I think we are OK to ignore it for now. I am planning to enable greenkeeper.io soon and we can continue tracking all dependency updates. Hopefully that warning is addressed upstream...
