### ISSUE TITLE
PF4: BackgroundImage TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#781]
Attempted to pull the latest from PF4 react-core (v1.23.0), pf-next (1.0.57 and 1.0.58) and encountered the following build error. This prevents koku-ui from rendering.

![screen shot 2018-10-16 at 10 57 05 am](https://user-images.githubusercontent.com/17481322/47026532-a82f2780-d133-11e8-8b5b-85f2fac64b4d.png)

I believe this may be related to the following change?

https://github.com/patternfly/patternfly-react/commit/44edab1c12b233774686852889653f85cc40e88c

**Comment by amarie401** [comment]
Can either of you look into this issue? @karelhala @jschuler

**Comment by karelhala** [comment]
This issue is caused by missmatch of @patternfly/react-tokens dependency. The code chabge you linked should have fixed it. I'll review it and keep you updated, for now you can fix it by forcing installing @patternfly/react-tokens in version ^1.5.0

**Comment by dlabrecq** [comment]
I'm using the latest version for all PF4 packages

**Comment by dlabrecq** [comment]
I'm only seeing the TypeError with TextContent using v1.23.1 now. Hopefully, that will be resolved soon and I can retest?

Note that I was able to comment-out TextContent from node_modules/@patternfly/react-core/dist/esm/components/index.js. That resolved a lot of other errors in the browser console, but not a good workaround.

I suspect TextContent is the underlying cause for this issue; thus, I'm closing.
