### ISSUE TITLE
Button - add variant that includes count

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#7831]
Want to add a new variant of the Button component that adds a count to the right of the button label in form of a badge.

Core PR: https://github.com/patternfly/patternfly/pull/5029

**Comment by mcarrano** [comment]
Yes, I think so.

**Comment by andyyvo** [comment]
@srambach I saw you worked on the core PR and wanted to know if you were hoping to have react show an example where clicking on the button would result in the badge changing state from unread to read. If so, @nicolethoen I feel like we would want the Button component to handle that?

**Comment by mcarrano** [comment]
@andyyvo @nicolethoen I would not build this functionality into the button as consumers may manage the read/unread states in different ways. What I would expect is just a prop that controls the badge state with the logic left to the consumer. Having an example that shows how to toggle this state is probably OK.
