### ISSUE TITLE
PF4 Progress Bar: Need a unique property for percentage label

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#784]
The Progress component uses the same `value` property for both the progress bar and label shown in the upper right corner. The Koku UI needs to use a custom label as shown below.

![screen shot 2018-10-16 at 12 49 51 pm](https://user-images.githubusercontent.com/17481322/47033469-e4b64f80-d142-11e8-9ee0-1d6d4ada19aa.png)

Ideally, the percent value and percent label should be two properties. Providing another property would allow me to customize the text shown in the Koku dashboard, while providing a more precise percent value (e.g., 82.94345491971737) if needed for the bar.

Note that I attempted to use the valueText property, but that appears to be used for aria-valuetext. IMO, that property name should also be prefixed with "aria", similar to alert's aria-label, to avoid confusion.

**Comment by tlabaj** [comment]
closed by #822
