### ISSUE TITLE
Bug - [Page] - [update onPageResize prop default value]

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#7861]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?
Update the default value for  `onPageResize`
**How do you reproduce the problem?**
Resize observe get created even when there is not sidebar and consumer does not define `onPageResize`
See issue https://github.com/patternfly/patternfly-react/issues/7810 for more details

**Is this issue blocking you?**
List the workaround if there is one.
work around implemented in PR #7811

**Comment by andyyvo** [comment]
@tlabaj @wise-king-sullyman from reading #7811 are we looking to remove `onPageResize: (): void => null,` under `PageProps` on line 104?

**Comment by nicolethoen** [comment]
Closed by #8203
