### ISSUE TITLE
Bug - LoginPage: backgroundImgAlt prop does not do what is intended

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#7867]
**Describe the problem**
Followup based on https://github.com/patternfly/patternfly-react/pull/7793#issuecomment-1218231920

cc @jessiehuff

Two options: 

- Remove the backgroundImgAlt prop from LoginPage (breaking, though not urgent so waiting for a breaking change release should be okay) (probably preferable)
- If we intend for consumers to use the BackgroundImage component in a way that "alt text" should be exposed for assistive technologies, adding role="img" to BackgroundImage and using aria-label instead of the alt attribute for the alt text in LoginPage (possibly breaking, depending if consumers are utilizing this alt attribute?)

**Comment by jessiehuff** [comment]
If I understand the situation correctly, it sounds like the question is whether users will ever have something in the background image that will be more than just decorative. I'm not sure of all use cases for a background image. Is it ever important for a user to know what the image is? 
@mcarrano Do you have any insight into expected use cases of background image and if the user ever really needs to know what the image is?

**Comment by mcarrano** [comment]
I think this was purely decorative. So no, I'm not aware of a scenario where that image is actually used to convey information. Do you agree @mceledonia ?

**Comment by tlabaj** [comment]
@mcarrano this issue my depend on https://github.com/patternfly/patternfly-react/issues/5815

**Comment by tlabaj** [comment]
closed by #8931
