### ISSUE TITLE
Bug - Popper's not maintaining proper stacking z-index order

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#7869]
Placeholder for the work from https://github.com/patternfly/patternfly/issues/4973

I think we're going to need to look at:
* Should popper things be added/removed from the DOM as they're triggered? Or should they create a ref on the page, and re-use that ref where it is in the DOM (doesn't move) to show/hide popper thing? Or both? 
  * Currently the modal creates a ref, but tooltips don't, s
* Updating popper to use more intentional `z-index`es, instead of `9999` for everything - _probably..._ It kinda works well the way it is now except for the bullet above. It's probably still a good to use a smarter z-index order for popper anyways.

**Comment by nicolethoen** [comment]
Given pending recommendations from core, relevant components should expose the z-index so it can be overridden by a consumer.
