### ISSUE TITLE
Accessibility updates for Dropdown component

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#787]
Several changes were made to the Dropdown component in core (https://github.com/patternfly/patternfly-next/pull/750) that should be reflected here:

- For all instances of this component:
  - remove `aria-haspopup` - After further review of this attribute, it causes issues in JAWS. 
  - Update the `id` attribute to match core. Currently the react component has `id` assigned to `pf-c-dropdown` but it should be assigned to `pf-c-dropdown__toggle`
- **basic Dropdown** - We now have a basic generic Dropdown structure that can accept anything in the menu `.pf-c-dropdown__menu` 
  - remove `aria-labelledby` on the menu `<div>` (for this variation only)
- **Dropdown with links and actions** - This is the version of the Dropdown that's currently implemented. This component is specific to the use case of providing a set of actions/links in a dropdown.
  - remove `aria-haspopup`, as noted above
  - the menu `<div>` is now a `<ul>` with `<li>` elements that wrap each `<a>` or `<button>`. The `aria-labelledby` that was on the `<div>` is now on the `<ul>`

**Comment by amarie401** [comment]
The associated PR for this issue has been merged so I will close this. See https://github.com/patternfly/patternfly-react/pull/788
