### ISSUE TITLE
Bug - Topology Pipelines - Visualisation connectors shows curved line for horizontally aligned nodes

### ISSUE THREAD

**Issue by karthikjeeyar** [patternfly/patternfly-react#7902]
**Describe the problem**

Two nodes on the same axis should have straight line instead of integral shape. This issue is caused in integral edge [algorithm](https://github.com/openshift/console/blob/master/frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/draw-utils.ts#L67-L74) due to 1px difference in `startPoint` (y-axis) and `endpoint` (y-axis) of an edge.

**How do you reproduce the problem?**

Create three parallel tasks as a children to a parallel task to form a tree like structure

**Expected behavior**
 
 The center task should align horizontally with its parent task.

**Screenshots**
If applicable, add screenshots to help explain the issue.
![image](https://user-images.githubusercontent.com/9964343/187351540-acd7d0fa-e1fb-4b5c-a257-2e940955c656.png)

![image](https://user-images.githubusercontent.com/9964343/187350776-8d7c71b6-4565-4c00-88b9-6dcd84ecfc61.png)

**What is your product and what release date are you targeting?**

HAC Build service.

**Comment by karthikjeeyar** [comment]
cc:  @jeff-phillips-18 @christianvogt

**Comment by christianvogt** [comment]
bump
