### ISSUE TITLE
PF4: react-core v1.24.1 is broken

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#791]
I took the latest react-core v1.24.1 package and get this error when building koku-ui. I have to drop back to v1.23.1 in order to compile.

![screen shot 2018-10-16 at 2 59 51 pm](https://user-images.githubusercontent.com/17481322/47040531-71b5d480-d154-11e8-89ef-ede49687be49.png)

**Comment by dmiller9911** [comment]
Looks like the index files are gone along with a few others.....https://unpkg.com/@patternfly/react-core@1.24.1/dist/esm/

**Comment by dmiller9911** [comment]
Not sure why but travis should have bailed since this failed: https://travis-ci.org/patternfly/patternfly-react/builds/442388072#L1003 lerna seemed to ignore the failed exit code.

**Comment by dlabrecq** [comment]
v1.24.3 is working now. Thanks!
