### ISSUE TITLE
feat(Wizard - next): WizardReview common component

### ISSUE THREAD

**Issue by jpuzz0** [patternfly/patternfly-react#7916]
**Is this a new component or an extension of an existing one?**
New component, which would be complimentary to the "next" Wizard

**Describe the feature**
Create template component that roughly captures the structure of the screenshot below. In summary, the template would comprise of a title, expandable sections, links to take users back to steps (Edit step), and description lists within those sections for metadata.

This details are still being discussed and planned to be shared with PF design: https://docs.google.com/document/d/1sZDSHsC5LZM1-7EvoYF4idji83TcZ7FargqRuifai_8/edit?pli=1#heading=h.nz2a58j5x0ww

<img width="830" alt="image" src="https://user-images.githubusercontent.com/96431149/187940894-d8de6c3d-5394-430a-9c7a-9db121dded18.png">

**Comment by mcarrano** [comment]
@jeffpuzzo this looks good. The only ask is that this can be implemented so that the collapsible sections are optional. They are not needed if there are only a few items to show.

**Comment by jeffpuzzo** [comment]
Just an update on this: Waiting on styles which were used to produce the screenshot included in the description before proceeding: https://github.com/patternfly/patternfly/pull/5235
