### ISSUE TITLE
PF3: CardGrid doesn't render correctly on window resize

### ISSUE THREAD

**Issue by jotak** [patternfly/patternfly-react#793]
The CardGrid component behaves differently than the one described, for instance, on https://github.com/patternfly/patternfly-tutorial : while resizing the window, cards to the right may appear overflowing their container.

See pictures from the issue reported in Kiali: https://issues.jboss.org/browse/KIALI-1741

By playing with CSS I've found out that `CardGrid` seems to use a `container` class which has a fixed width, causing this problem.
If I override with `width: inherit` then the problem disappears:

![css](https://i.imgur.com/RaezKZ1.png)

**Comment by tlabaj** [comment]
Closing this since there is a work around.
