### ISSUE TITLE
Bug - MenuGroup - High heading level and missing documentation.

### ISSUE THREAD

**Issue by OndrejZobal** [patternfly/patternfly-react#7982]
**Describe the problem**
1. MenuGroup renders its label as a level 1 heading, this is too high for such a label.
2. Documentation for MenuGroup is missing.

**How do you reproduce the problem?**
1. MenuGroup label issue visible here: https://codesandbox.io/s/adoring-maria-c62pcg
2. MenuGroup documentation missing from here: https://www.patternfly.org/v4/components/menu

**Expected behavior**
1. MenuGroup label would have a lover default level (like h3) and would let you specify a custom level via a prop.
2. MenuGroup should be documented on the same page as Menu.

**What is your environment?**
 - OS: Fedora 36
 - Browser: Firefox
 - Version 104.0.1

**Comment by nicolethoen** [comment]
Hello @OndrejZobal 
Thank you so much for reporting this issue! We actually have merged a change already to add the MenuGroup documentation to the Menu component page docs, so as soon as the next release is published, you should see that update on the website :)

The other good news, is that there is a prop on MenuGroup for controlling the menu group heading level. You can already see that prop being used in the [Grouped menu example on the site](https://www.patternfly.org/v4/components/menu/#with-titled-groups). And if you'd like, you can see the MenuGroup docs slated for publication with the next release on [this staging link ](http://patternfly-react-main.surge.sh/components/menu#menugroup).

I'm going to close this issue for now, but if you have any other concerns, feel free to reopen or ask! :)
