### ISSUE TITLE
Bug - [DatePicker] - [TS type bodyContent required in popoverProps]

### ISSUE THREAD

**Issue by akhilmhdh** [patternfly/patternfly-react#8001]
**Describe the problem**
When you add additional props for popover in `popoverProps` inside `DatePicker` the bodyContent prop is required due to the popover default type

**How do you reproduce the problem?**
Add additional attributes in `popoverProps` in Date Picker component.

![image](https://user-images.githubusercontent.com/31166322/190970233-ff26ec29-df38-4bb9-963c-8c653cb9ec10.png)

**Expected behavior**
bodyContent is optional as datepicker has a bodyContent

**Is this issue blocking you?**
No

**Screenshots**
If applicable, add screenshots to help explain the issue.

Kindly refer above

**What is your environment?**
 - OS: MacOS
 - Browser: NA
 - Version: NA

**Comment by akhilmhdh** [comment]
I'll attach a PR for the type fix.

**Comment by tlabaj** [comment]
closed by #8002
