### ISSUE TITLE
Table:  Deprecate the legacy table

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8005]
Deprecate the legacy table.  The following task must be completed 

Move the legacy table code to the deprecated directory.  The documentation would show up under a "React deprecated" tab on the website. 

- [x] #8360
- [x] #8742
- [ ]  `TableComposable` should be renamed to `Table`
- [x] #8749
- [ ]  Rename "React composable" tab to just "React"

**Comment by jenny-s51** [comment]
Update 3/30/23: While reviewing #8843 with @nicolethoen we came to the conclusion that, since ComposableTable was built on the older Table, we cannot deprecate Table entirely as there are certain legacy files that are used by the newer table. #8892 begins to address this
