### ISSUE TITLE
Bug - Alert - crashes with unclear message when `variant` prop is not one of expected strings

### ISSUE THREAD

**Issue by cben** [patternfly/patternfly-react#8015]
**Describe the problem**
I wrote `variant="error"` instead of `variant="danger"` by mistake.  The resulting crash (up to nearest react error boundary) had a very unclear message.

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
>
> Check the render method of `AlertIcon`.

That part about "exports/import" was a red herring but it's what all googling about "expected a string" errors led me to.  
The hint about `AlertIcon` would have saved me a _lot_ of time, except it only shows up in a debug build of React; the project I'm now on is sadly set up with prod builds of React which only gave me this URL: 
https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=
showing only the first sentence :-(

**How do you reproduce the problem?**
https://codesandbox.io/s/strange-darkness-5hwm9f

**Expected behavior**
One of:
1. Give a clearer error message explicitly mentioning `Alert` and the `variant` prop?
2. Ignore the unknown variant, fall back to variant="default" rendering?

* :point_up: I'm happy to send a PR, but tell me which behavior is preferred — error of ignore?

**Is this issue blocking you?**
Not now, but it took me several hours to narrow down the problem (partly because I was on a prod build of React

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**
 - OS: Linux (Fedora 36)
 - Browser chrome
 - Version 105.0.5195.102 (Official Build) (64-bit)

**Comment by nicolethoen** [comment]
@cben I believe in this case it'd be best to implement your first solution: Give a clearer error message explicitly mentioning Alert and the variant prop.

That way if someone thinks they are implementing an 'error' alert and keep seeing the 'default' alert, they don't sit scratching your head looking for more information or an error message like you did. :)

I'd be happy to assign this to you! Let me know if you have anything come up to prevent you from contributing
