### ISSUE TITLE
[Dropdown next] - [Add OUIA support]

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8046]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
Dropdown Next

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
Since the current version of the dropdown has OUIA support we should add it to the Next version of the dropdown.

**Comment by gefgu** [comment]
I would like to work on this issue :)
