### ISSUE TITLE
Menu- add optional danger state for menu items

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#8058]
Want to allow for applying "danger' styling to menu items.

Core PR: https://github.com/patternfly/patternfly/pull/5102

**Comment by gefgu** [comment]
I would like to work on this issue :)

**Comment by mcarrano** [comment]
@nicolethoen @tlabaj ^^^

**Comment by tlabaj** [comment]
@gefgu I have assigned you.  Thank you for picking up the issue.  The target code freeze date for this feature is October 19th.
