### ISSUE TITLE
Modal: Deprecate modal

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8078]
Deprecate the modal

- Move the Modal code to the deprecated directory (`react-core\src\deprecated\`). The documentation would show up under a "React deprecated" tab on the Modal page  of the website.
- Promote the "next Modal" to our default Modal component by moving it to `react-core\src\components\`.  

related to https://github.com/patternfly/patternfly-react/issues/8076

**Comment by thatblindgeye** [comment]
Closed by #10358
