### ISSUE TITLE
Table: Column Management (draggable) demo data

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#8079]
This issue is blocked/on hold until the Drag and Drop refactor is complete. 

- Update draggable column management demo with new data.

- Pull in full-screen conversion updates from #7446

**Comment by tlabaj** [comment]
@jenny-s51 is this different form issue #7357?

**Comment by jenny-s51** [comment]
Yes @tlabaj , this issue is part of the epic to update all the table demos with the new data -> #7384

When this issue is completed, it will close #7357 by default since this is going to be a fullscreen demo.
