### ISSUE TITLE
[DataList] - [remove deprecated props ]

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8086]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

Remove the following deprecated props and any associated logic from DataList

- `onDragFinish`
- `onDragStart`
- `onDragMove`
- `onDragCancel`
- `itemOrder`

**Comment by KhanShaheb34** [comment]
Can I work on this one?

**Comment by tlabaj** [comment]
Sure.  Make sure your work is agains the `v5` branch.

**Comment by nicolethoen** [comment]
@KhanShaheb34 Let me know if you still were planning on working on this, but I've unassigned you for now in case other people want to take a peek

**Comment by nicolethoen** [comment]
Closed by #8388
