### ISSUE TITLE
Bug - Select List/ Dropdown - Disabled selection no longer seems to be keyboard accessible

### ISSUE THREAD

**Issue by maudem** [patternfly/patternfly-react#8095]
**Describe the problem**
When a selection in the Select List is disabled, you can no longer access it by keyboard.
See https://issues.redhat.com/browse/HAC-1377

**Is this issue blocking you?**
No.

**What is your environment?**
 - OS: iOS
 - Browser: Chrome
 - Version: Latest

**What is your product and what release date are you targeting?**
OpenShift ROSA

**Comment by tlabaj** [comment]
Hi @maudem Are you seeing the issue with the PF Select or the PF Dropdown?

**Comment by maudem** [comment]
The PF Select

**Comment by tlabaj** [comment]
Do you now what version you are running and what you upgraded from?
