### ISSUE TITLE
Bug - Pipelines Topology - Multiple popovers are shown at the same time

### ISSUE THREAD

**Issue by karthikjeeyar** [patternfly/patternfly-react#8100]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

Clicking on `Task` badge opens popover but fails to close the previously opened popover.

**How do you reproduce the problem?**

1. Visit  and click on `Layout` option in https://topology-pipeline-zoom2.surge.sh/
2. click on multiple Task badge icon

**Expected behavior**

Previously opened popover should be closed on clicking a task badge.

**Screenshots**
If applicable, add screenshots to help explain the issue.

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/9964343/192481015-1ca20a79-de89-4ec3-9e05-1ae1bcfda90d.png">

**What is your product and what release date are you targeting?**
Openshift Developer Console.

**Comment by karthikjeeyar** [comment]
cc: @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar This one will take some thought. Not sure it can be fixed without somehow maintaining state and controlling the popovers via the VisualizationSurface state.

**Comment by karthikjeeyar** [comment]
The earlier version (before zoom levels) had the expected behaviour https://topology-pipeline-styles-2.surge.sh though 🤔

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar ah, I see it now. It will require a small change on the application's part. If the application has followed the demo's `DemoTaskNode` it will need to update to use the change being made for this fix (passing the ref for the node, rather than wrapping the node in `<g>` for the ref.
