### ISSUE TITLE
Tabs - change border bottom API

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-react#8104]
**Is this a new component or an extension of an existing one?**
Refactoring of an existing component's API and change of default behavior.

**Describe the feature**
Currently primary tabs have a full width bottom border by default (and consumers can opt out of that behavior by setting the `hasBorderBottom` prop to false), but secondary tabs have to opt into that behavior using the `hasSecondaryBorderBottom` prop.

This API could be made more intuitive by both primary and secondary tabs having the same default behavior. This would allow the `hasSecondaryBorderBottom` to be removed and `hasBorderBottom` to control the bottom border behavior regardless of whether the tabs are primary or secondary.

Comment where this breaking change was suggested: https://github.com/patternfly/patternfly-react/pull/7311#discussion_r864958670

dependent on core issue [#5128](https://github.com/patternfly/patternfly/issues/5128)

**Comment by jenny-s51** [comment]
Update: Following #5128 and #8286, **can remove `isSecondary` from the `Tabs` component wherever it's set as a prop, because following the core PR, the secondary variant will have border by default.**

**Comment by nicolethoen** [comment]
https://github.com/patternfly/patternfly-react/pull/8469 commented out related Tabs tests commented out. They need to be fixed/re-enabled.
