### ISSUE TITLE
Bug - [TimePicker] - [The invalid error message is displayed for a second and then is removed when typing and selecting from dropdown]

### ISSUE THREAD

**Issue by Marc19** [patternfly/patternfly-react#8118]
**Describe the problem**
When typing a value like "10:" and then selecting the value from the dropdown, the invalid error message is displayed for a second and then is removed which is not an optimal user experience

**How do you reproduce the problem?**
1. Type a value that is temporarily invalid like "10:"
2. Select from dropdown "10:30" for example
3. The error message is added and then is removed instantly

**Expected behavior**
The error message is not added at all in this case

**Is this issue blocking you?**
It is causing a non optimal user experience

**What is your environment?**
- OS: Windows
- Browser: Chrome
- Version: 105.0.5195.102

**Comment by CodeDuchess** [comment]
@nicolethoen I would be happy to work this ticket. Thanks!

**Comment by CodeDuchess** [comment]
I think I have identified the event associated with this bug. The onBlur event fires at the time of the error message that flashes. If you comment out the this.setState statement, the error does not occur.
![timepicker_culprit](https://user-images.githubusercontent.com/29104113/200420519-20db72fd-a409-4159-8d72-c8aafa071830.png)
