### ISSUE TITLE
[Pagination] - [Rename ToggleTemplateProps]

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8122]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?

rename `ToggleTemplateProps` to `PaginationToggleTemplateProps`. to matche naming practices

**Comment by KhanShaheb34** [comment]
Can you assign me please?

**Comment by KhanShaheb34** [comment]
Ok.

**Comment by nicolethoen** [comment]
Closed by #8134
