### ISSUE TITLE
Breaking change: update hasCheck to hasCheckbox

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#8126]
In various menu/menu option components where a checkbox can be optionally included, it may make more sense to call this property `hasCheckbox` instead of `hasCheck`.

**Comment by bonjo7** [comment]
As this is marked `good first issue` I decided to attempt it.

[PR](https://github.com/patternfly/patternfly-react/pull/8200)

**Comment by thatblindgeye** [comment]
Closed by #8403
