### ISSUE TITLE
Bug - Topology Pipelines - Update status icon and color to match the new design.

### ISSUE THREAD

**Issue by karthikjeeyar** [patternfly/patternfly-react#8147]
**Describe the problem**

Topology pipelines staus icons, colors should be matching the latest design spec

![image](https://user-images.githubusercontent.com/9964343/193826561-0a17ed8b-01da-416c-95c5-042b0535a4f0.png)

1.  Running/Pending status colors needs to be matched with above design.
2.  zoomed out nodes (low details) should contain icons. 
3.  configuration options to show/hide the icons on the zoom nodes.

**How do you reproduce the problem?**
Visit https://topology-pipeline-zoom2.surge.sh/

**Expected behavior**

1. Running task should be blue in color.
2. Pending task should be light blue in color.
3. Should be able to show/hide the icons on zoomed state.

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your product and what release date are you targeting?**
Openshift Devconsole, HACBS.

cc: @serenamarie125 @jeff-phillips-18

**Comment by andrew-ronaldson** [comment]
Brain dump starting:
1. For the pending tasks I was thinking it could be light blue if it was the next task (or group of tasks) in the run rather than all pending tasks. If you are starting a pipelineRun almost all the nodes would be light blue and not necessarily useful.
2. On the other hand the light blue pending style would separate pending from cancelled or skipped tasks.

Curious what you think about those options @serenamarie125

**Comment by jeff-phillips-18** [comment]
> * For the pending tasks I was thinking it could be light blue if it was the next task (or group of tasks) in the run rather than all pending tasks. If you are starting a pipelineRun almost all the nodes would be light blue and not necessarily useful.

Are you suggesting another status?

**Comment by andrew-ronaldson** [comment]
> This would then be the same as selected

That is true for nodes with no associated status. The running icon helps with that but only if it is included. Would the running tasks work better as the light blue and all pending tasks are grey? 
<img width="940" alt="Screen Shot 2022-10-06 at 12 16 32 PM" src="https://user-images.githubusercontent.com/28658548/194351627-ee77d80c-0761-4e9f-aef6-fa8fc5a224f9.png">

**Comment by andrew-ronaldson** [comment]
Option 2 in my screenshot above should be the running task styling so it stands out from the default selected states.

**Comment by andrew-ronaldson** [comment]
As per my earlier suggestions about pending tasks I will leave that out for the time being in favour of getting this out in product.

**Comment by jeff-phillips-18** [comment]
@andrew-ronaldson Can we confirm Option 2 above is the way we want to go?

**Comment by jeff-phillips-18** [comment]
Closing in favor of https://github.com/patternfly/react-topology/issues/12
