### ISSUE TITLE
Bug - Topology Pipelines - Fit to screen as default view in pipelines topology

### ISSUE THREAD

**Issue by karthikjeeyar** [patternfly/patternfly-react#8149]
**Describe the problem**

The graph should contain an option to start it with `fit to screen` mode to be able to see all the pipeline nodes at a glance. 

**How do you reproduce the problem?**

 This issue can be observed when having a large pipeline layout with limited height.

**Expected behavior**

Should be able to set a prop eg: `fit=true` to make the graph default view as fit to screen.

**Screenshots**

Some of the task are going off the graph area.

![image](https://user-images.githubusercontent.com/9964343/193828440-b31fcb4e-50b1-46ba-b327-949029109380.png)

**What is your product and what release date are you targeting?**
Openshift, HACBS

cc: @serenamarie125 @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
Adding an option should be considered an enhancement / feature request
