### ISSUE TITLE
Setting Focus to Input Field per Code

### ISSUE THREAD

**Issue by TimoSta** [patternfly/patternfly-react#816]
I would like to focus an input field represented by a PF4 `TextInput` per code. As far as I can see, this is currently not supported (at least not without major hacks).

The same likely also applies to other input components, e.g. `Checkbox`, `Select`, `Radio`...

---

Two potential solutions:

- **Add a `.focus()` method to the API of `TextInput`** which uses an internal ref to the underlying `input` to focus it; similar to [this example](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-class-component).

- **[Forward refs](https://reactjs.org/docs/forwarding-refs.html) to the `TextInput` to the underlying `input`**, which allows the user to interact directly with the latter.

---

With either approach, the user of `TextInput` can obtain a ref to the instance and focus the underlying input without relying on the component's implementation details.

**Comment by redallen** [comment]
Closing in favor of #1954.
