### ISSUE TITLE
CodeBlock - empty header/actions elements if no actions are passed

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8197]
<img width="684" alt="Screen Shot 2022-10-10 at 2 39 21 PM" src="https://user-images.githubusercontent.com/35148959/194941283-0a798816-d3f0-4184-927e-314954486887.png">

The border comes from the presence of the header.

@mmenestr @mcarrano according to the [design guidelines](https://www.patternfly.org/v4/components/code-block/design-guidelines):

> Code blocks can include multiple actions. By default, the copy action is always present and any other actions are optional and customizable.

It isn't built in to the react component - it has to be defined by the user. Does the design doc blurb imply the copy button is required?  Or can it be optional? I would lean toward it being optional, in case it does something like show a code example/format that isn't meant to be copied/pasted. If so, I don't think we should render the header/actions block unless something is passed.

https://github.com/patternfly/patternfly-react/blob/44af73002bdeb1048be9b326abf7ffd4fcd474be/packages/react-core/src/components/CodeBlock/CodeBlock.tsx#L21-L23

We may also consider adding a `__header-main` element that is adjacent to the actions block for a user to place other items in the header. Currently it's only setup to accept the actions block. This code language toggle group is a good use case for that? https://codesandbox.io/s/code-editor-language-toggle-group-jcmqlb?file=/toggle.js

<img width="811" alt="Screen Shot 2022-10-10 at 2 56 54 PM" src="https://user-images.githubusercontent.com/35148959/194942944-8f9a2112-bfb0-4f33-9f4e-97e923627e09.png">

**Comment by mcarrano** [comment]
> t isn't built in to the react component - it has to be defined by the user. Does the design doc blurb imply the copy button is required? Or can it be optional?

I guess the Copy button could be optional. I think the feeling was that for a Code block you'd always want to be able to copy the contents to the clipboard. Can you think of reasons why we may not want that @mcoker ?

**Comment by mcoker** [comment]
@mcarrano if you want to show a sample block of code that is for demonstration, not for copy/paste. There are code block components with no copy button on our dev guidelines like that - https://www.patternfly.org/v4/developer-resources/global-css-variables

Or if you want to show the source code for something, similar to how I would reference these docs about the `type` prop for the `<TextInput>` https://github.com/patternfly/patternfly-react/blob/44af73002bdeb1048be9b326abf7ffd4fcd474be/packages/react-core/src/components/TextInput/TextInput.tsx#L48-L59

I would also make the case that there should be an inline code block (though it wouldn't be a "block"). Pretty much the "inline compact" copy to clipboard, which already matches the code block component exactly, even with the "play" button. https://www.patternfly.org/v4/components/clipboard-copy/html#inline-compact-in-sentence A use case for that without a copy button would be all the inline code on the [css var guidelines page](https://www.patternfly.org/v4/developer-resources/global-css-variables) that has a white background and light grey border.

**Comment by mcarrano** [comment]
@mmenestr thoughts? ^^^

**Comment by mmenestr** [comment]
@mcarrano @mcoker  I think it's fine to make it optional, and we can update the design guidelines to match that!

**Comment by nicolethoen** [comment]
Closed by #8622
