### ISSUE TITLE
Component - Empty State Pattern

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#82]
Provide implementation for the empty state as documented here:
http://www.patternfly.org/pattern-library/communication/empty-state/#/design

Note : Ang PF implementation can be found here for reference: http://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfEmptyState

Associated JIRA Story: 
https://patternfly.atlassian.net/browse/OSUX-304

**Comment by sharvit** [comment]
@amirfefer - introduced it here https://github.com/theforeman/foreman/pull/5024
