### ISSUE TITLE
Banner - update variant names to reference colors instead of status names

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8204]
https://github.com/patternfly/patternfly/issues/5162

| old | new |
|-|-|
| info | blue |
| danger | red |
| success | green |
| warning | gold |

note - we're just replacing the variant names. We want to keep the status examples, which show how to include an icon and screen reader text.

**Comment by gitdallas** [comment]
would it make sense to have a non-breaking change where we just add the colors without removing the old variants?

note: error exists in some places too
