### ISSUE TITLE
[Dropdown next, Select next] - [add MenuToggle to props table]

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8211]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
MenuToggle is used in the examples.  Add it to the prop tables so consumers can easily find the documentation.

**Comment by CodeDuchess** [comment]
@nicolethoen I would be happy to work this ticket. Thanks.

**Comment by CodeDuchess** [comment]
Is this correct file path for the edits?  patternfly-docs > components > dropdown > react-next.js   It does not exactly match the table here:
<img width="1728" alt="Screen Shot 2022-11-17 at 7 19 37 PM" src="https://user-images.githubusercontent.com/29104113/202588011-ef99d451-e7fb-485b-9c49-d2f45bfd66bc.png">

**Comment by nicolethoen** [comment]
the propComponents array is at the top of each component's example markdown file: 
for next/dropdown: https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/next/components/Dropdown/examples/Dropdown.md
for next/select: https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/next/components/Select/examples/Select.md

**Comment by CodeDuchess** [comment]
Thanks, Nicole.

**Comment by CodeDuchess** [comment]
@nicolethoen I have made the edits to the files. I was looking for directions about how to open a PR. I typically work with GitLab and we open a MR using the following: `git status` `git add -A` `git commit -m "message"` `git push` I was looking for something similar to that in the PatternFly reference doc, but I did not find it. Please advise. Thanks.

**Comment by nicolethoen** [comment]
I believe all those commands should work the same to open a PR in github, as well! After you push, your should be able to go to your fork in github and see a notification that says something like "x branch has new commits." along with a button to open a PR.

**Comment by nicolethoen** [comment]
This issue is currently blocked by https://github.com/patternfly/patternfly-react/pull/8410

**Comment by nicolethoen** [comment]
This issue is being addressed in the v5 branch in the following PRs:
https://github.com/patternfly/patternfly-react/pull/8825
https://github.com/patternfly/patternfly-react/pull/8835
