### ISSUE TITLE
Breaking change: In some components innerRef prop is not hidden

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8233]
**Describe the problem**
Related to issue  #8180

In some components passing innerRef accidentally works when it probably should not. Fixing this could be a breaking change:

BackToTop
MenuToggle
TextInputGroupMain (passing innerRef works while passing ref doesn't)

Expected behavior
innerRef prop should be hidden.

**Comment by nicolethoen** [comment]
closed by #8648
