### ISSUE TITLE
Support for component animations

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8252]
Placeholder for the core work in https://github.com/patternfly/patternfly/issues/4979

If the animations can be handled all in CSS, there may be no react work needed, but we may need to introduce things like event handlers to watch, for example, `transitionend` before removing an element from the DOM or adding/removing a class.

**Comment by tlabaj** [comment]
Closing. This will be tracked by https://github.com/patternfly/patternfly-react/issues/10253
