### ISSUE TITLE
React-icons - support for PF icon sizes

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8263]
Placeholder for the core work in https://github.com/patternfly/patternfly/issues/5265

Ideally if react-icons allows for size variations, they would support the PF icon sizes. Though I believe core is not a dependency for react-icons currently (aside from the JSON file from core with pficons SVG defs), so there may be a case for allowing core/PF components to handle the icon size - particularly since we have an [icon component](https://www.patternfly.org/v4/components/icon) now. Assuming that is the case, should react-icons have a `size` prop that is different from the core sizes?

**Comment by mcoker** [comment]
This is no longer necessary and should be resolved by the change outlined from https://github.com/patternfly/patternfly-react/pull/5275#pullrequestreview-1281925750, including the core PR https://github.com/patternfly/patternfly/pull/5388

**Comment by nicolethoen** [comment]
@mcoker do you mean we can close this issue? Or is it addressed by #5275?

**Comment by mcoker** [comment]
@nicolethoen we can close it. It's no longer relevant since we're removing the size prop.
