### ISSUE TITLE
Accordion - scrollable region must have keyboard access

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8276]
A follow up to the core work here - https://github.com/patternfly/patternfly/pull/5130

As noted in the PR:

* Ideally we would only want the tabindex when a scrollbar is present, which may not always be the case when the accordion content `isFixed`
*Wwe should apply a `role="region"` attribute to the accordion content when `isFixed` is true, unless the accordion is a definition list, in which case I don't think we want the region role applied since the content would have the semantics of a `<dd>` element already. @thatblindgeye - just to double check, this should also only be present when there is scrollable content - not just when`isFixed` is true?
* The accordion content needs an accessible label when it is scrollable/keyboard-focusable. Seems like we might set `aria-labelledby="[id of toggle button]"` by default (like in the core examples), and that could be overridden by a user's `aria-label` and/or `aria-labelledby`?

**Comment by thatblindgeye** [comment]
> just to double check, this should also only be present when there is scrollable content - not just whenisFixed is true?

Based on the isFixed prop description, yeah ideally that would be better. Otherwise it could cause some confusion over one AccordionContent being focusable and others not.
