### ISSUE TITLE
Component - Fixed Accordion

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#83]
Provide implementation for the fixed accordion which is used in the Notification Drawer (http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design)

Note : Ang PF implementation can be found here for reference: http://www.patternfly.org/angular-patternfly/#/api/patternfly.utils:pfFixedAccordion

Associated JIRA Issue: https://patternfly.atlassian.net/browse/OSUX-302

**Comment by Laviro** [comment]
[Check the NotificationDrawer PR #262 made by Gilad](https://rawgit.com/gilad215/patternfly-react/storybook/feature/notif-drawer/index.html?knob-Expanded%20Drawer=false&selectedKind=NotificationDrawer&selectedStory=Stateful%20Drawer%20Wrapper&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
