### ISSUE TITLE
Bug - JumpLinksItem - href does not work properly

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#8309]
**Describe the problem**
A clear and concise description of the problem. Which components are affected?
If a JumpLinksItem is clicked, the url does not update as expected when clicked.

**How do you reproduce the problem?**
Provide steps to reproduce. A [codesandbox](https://codesandbox.io/s/serverless-cherry-q9t3f ) demonstrating the problem is appreciated.
https://www.patternfly.org/v4/components/jump-links/react-demos/scrollspy-with-subsections/

1. *Right* click on a jumplink.
2. Click "Open in new tab"
3. See that the anchor tag is appended to the URL for the jump link.
4. Go back to the same demo in the other tab.
5. Now *Left* click on any of the jump links.
6. Notice that the anchor is never appended to the URL.

**Expected behavior**
A clear and concise description of the expected behavior.
We expect the URL to always append the anchor tag through the `href` attribute in the same window/tab.

**Is this issue blocking you?**
Cannot implement this feature in org until this bug is fixed.
See https://github.com/patternfly/patternfly-org/issues/3120

**Screenshots**

**Current:** 
<img width="699" alt="Screen Shot 2022-10-31 at 11 06 54 AM" src="https://user-images.githubusercontent.com/32821331/199040888-86ecb6ac-8c21-455c-9874-be3e813aaac9.png">

**Expected:**
<img width="771" alt="Screen Shot 2022-10-31 at 11 07 44 AM" src="https://user-images.githubusercontent.com/32821331/199040992-31a2b110-9152-466b-8c3d-8aa8e34455f1.png">

**What is your environment?**
 - Chrome

**Comment by jenny-s51** [comment]
💡: This behavior is due to the [`ev.preventDefault` in the scroll logic of JumpLinks.tsx](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/JumpLinks/JumpLinks.tsx#L197). When it's removed we see the anchor tag get appended to the url, but this causes some other issues with scroll tracking.

**Comment by nicolethoen** [comment]
closed by #9307
