### ISSUE TITLE
Wrong Type for ThExpandType.expand.collapseAllAriaLabel

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#8330]
**Describe the problem**
The `expand` prop of `ThExpandType` requires `collapseAllAriaLabel` and currently has a type of `''` instead of `string`.

**How do you reproduce the problem?**
The HCS UI uses a `Th` for sticky column support; however, it also needs to support expandable rows. We're using `ThExpandType`, but the `expand` props; `areAllExpanded` and `collapseAllAriaLabel` are misleading. We use this functionality to collapse the current row, but there is no "collapse all" feature here.

**Expected behavior**
The `collapseAllAriaLabel` prop should be typed as `string`.

I'd also like to suggest that `areAllExpanded` and `collapseAllAriaLabel` be renamed. Alternatively, `Td` could support sticky columns.

**Is this issue blocking you?**
We have to workaround the issue by casting our valid `string` as `''`

**Screenshots**
![Screen Shot 2022-11-04 at 10 29 08 AM](https://user-images.githubusercontent.com/17481322/200001901-7b8243a3-ecc3-4252-99bf-611941819ca5.png)

**Comment by mcarrano** [comment]
@mcarrano we will plan to fix this in the PatternFly 5 release.

**Comment by nicolethoen** [comment]
Closed by #8634
