### ISSUE TITLE
Bug - Card - set default component to "div" to match core

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#8336]
**Describe the problem**
All the core examples apply the `pf-c-card` class to divs., however in react `<Card>` renders as `<article>` by default, so we have to explicitly set the `component` prop to "div" in order to match the core examples.

Eric noted this discrepancy in PR -  posted by @thatblindgeye in https://github.com/patternfly/patternfly-react/pull/8286#discussion_r1014421268:
> Is there a particular reason for using `div` as the component on the Cards?

**Comment by nicolethoen** [comment]
Closed by #8601
