### ISSUE TITLE
Spinner - remove legacy variant

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8349]
Remove support for the non-SVG spinner.

re: this core issue, though this shouldn't need to wait for core - https://github.com/patternfly/patternfly/issues/3827

**Comment by nicolethoen** [comment]
If someone was using the non-svg, now by default they would be using the svg.
we can remove the isSvg prop. and the code mod can remove the prop.

**Comment by nicolethoen** [comment]
Closed by #8616
