### ISSUE TITLE
Bug - Chip - Chip component does not accept user given attributes

### ISSUE THREAD

**Issue by depatil-redhat** [patternfly/patternfly-react#8353]
**Describe the problem**
I'm trying to give a role attribute to the chip component but it is not applying to the element

**Expected behavior**
It should take addition attributes and apply to the element

**Is this issue blocking you?**
It's not a blocker

**What is your environment?**
 - OS: RHEL
 - Browser: Chrome
 - Version 106.0.5249.119

**What is your product and what release date are you targeting?**
Red Hat Customer Dashboard

**Comment by erkanercan** [comment]
I would like to get an assignment on this issue if possible, I'll be providing a PR to resolve the issue. @nicolethoen

**Comment by nicolethoen** [comment]
@erkanercan I assigned you! Thank you!

**Comment by erkanercan** [comment]
Hi, @nicolethoen can you please take a look at #8383?
