### ISSUE TITLE
Toolbar - support for vertical alignment variations

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8364]
core PR: https://github.com/patternfly/patternfly/pull/5201

**Comment by gitdallas** [comment]
looks like we are still waiting for the core pr to go in.

after that happens, i think we need to give the users the ability to add...

`.pf-m-align-items-center` to `ToolbarContent` and `ToolbarGroup`
`.pf-m-align-self-center` to `ToolbarGroup` and `ToolbarItem`
`.pf-m-align-self-baseline` to `ToolbarGroup` and `ToolbarItem`

What should we call these and what should they be under though? Would they be in addition to (outside of) the `alignment` prop like on `ToolbarContent`?
<img width="315" alt="image" src="https://user-images.githubusercontent.com/5322142/212160082-e947914c-646f-4435-b4b8-83b9e09c21c2.png">

@mcoker @mattnolting 

i may also need a demo or example of exactly what is happening with this, screenshots in story/pr seem to show cramming some text in under a dropdown menu?

**Comment by mcoker** [comment]
@gitdallas good question - looks like `alignment` on `<ToolbarContent>` (`.pf-c-toolbar__content`) can be removed, I only see support for it on `.pf-c-toobar_item` and `.pf-c-toolbar__group`. https://github.com/patternfly/patternfly/blob/86be0974e7544bcc9d0119f85720277dff8290f0/src/patternfly/components/Toolbar/toolbar.scss#L477-L495

If possible, I think it would be good to match the property name where possible (`align-items`, or an `alignItems` prop in this case) so as not to run into naming conflicts in the future. Though sometimes that can be unintuitive, since this vertical alignment of the children would be `align-items` and horizontal alignment (if we added that) would be `justify-content`, which aren't as clear as `verticalAlignItems` and `horizontalAlignItems`. And just to abstract things a bit further, if there were a vertical toolbar, the `align-items` property in CSS would refer to horizontal alignment of the children, and `justify-content` would refer to vertical alignment.

The toolbar is mostly just an opinionated flex layout. If possible, I think matching the flex layout property names here (and for the existing `alignment`) prop would be my suggestion. 

* `alignment` would change to `align`. This applies to a child of a flex layout, and aligns that child (and any adjacent children on the other side of it) to one side of the main axis.
  * https://github.com/patternfly/patternfly-react/blob/bf9cf833bd7117fcfdb71fc68cab3d2453374336/packages/react-core/src/layouts/Flex/Flex.tsx#L249
* use `alignItems` for this property, which applies to a flex parent and vertically aligns its children
  * https://github.com/patternfly/patternfly-react/blob/bf9cf833bd7117fcfdb71fc68cab3d2453374336/packages/react-core/src/layouts/Flex/Flex.tsx#L176

I also think moving in the direction of "start" and "end" instead of "left" and "right" will move us in the direction of RTL language support (see [logical properties/values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties)), and the flex property values already do that

**Comment by gitdallas** [comment]
@mcoker trying to wrap my head around this to translate it into what props actually need to be added and the resulting styles.

https://github.com/patternfly/patternfly/pull/5201 says it added 3 classes, so i was assuming i just needed to have props that add those 3 classes in the right places.

This is where I'm at now:

**ToolbarContent:**

- remove `alignment`
- add `align` (what classes would this add?)
- add `alignItems` (boolean to add `.pf-m-align-items-center` class as it seems to be the only align-items class in core pr)

**ToolbarGroup**

- remove `alignment` and add `align` here as well?
- add `alignItems` (boolean as the core pr only seems to have the `.pf-m-align-items-center` for align-items?)
- add `alignSelf: 'center' | 'baseline'` (to add either `.pf-m-align-self-center` or `.pf-m-align-self-baseline`?)

**ToolbarItem**

- remove `alignment` and add `align` here as well?
- add `alignSelf: 'center' | 'baseline'` (to add either `.pf-m-align-self-center` or `.pf-m-align-self-baseline`?)

**Comment by mattnolting** [comment]
@mcoker One update, `pf-c-toolbar__item` doesn't need `align-items` as it has no `flex` display value by default.

**ToolbarGroup**

- alignItems: 'center' | 'baseline' | 'default'
- alignSelf: 'center' | 'baseline' | 'default'
- align: 'right' | 'left' | 'default'

**ToolbarItem**

~~alignItems: 'center' | 'baseline' | 'default'~~
- alignSelf: 'center' | 'baseline' | 'default'
- align: 'right' | 'left' | 'default'

**ToolbarContentSection**

- alignItems: 'center' | 'baseline'

> I do think we could update align to be start/end instead of left/right, but it would be a bit inconsistent since our classnames are currently left/right, and other components use left/right, too. I think to support RTL with logical properties, the change to start/end could be a separate effort.

@mcoker I love this idea. I can open a new issue to duplicate `left/right` alignment modifier functionality with `start/end` modifiers. We should be migrating towards logical props anyways 😄

**Comment by mcoker** [comment]
@mattnolting nice catch on `__item` and `align-items`! After re-reading that comment, I think I meant to suggest `<ToolbarContent>`'s prop values be `alignItems: 'center' | 'default'`. Sorry for the confusion @gitdallas. I updated my original comment, but here it is again. The logic is just 1) a prop for each CSS alignment property (eg, align-items, align-self), 2) a prop value for each modifier class we have as an available option, and a "default" value for no modifier.

* ToolbarGroup
  * `alignItems: 'center' | 'baseline' | 'default'`
  * `alignSelf: 'center' | 'baseline' | 'default'`
  * `align: 'right' | 'left' | 'default'`

* ToolbarItem
  * `alignSelf: 'center' | 'baseline' | 'default'`
  * `align: 'right' | 'left' | 'default'`

* ToolbarContent
  * `alignItems: 'center' | 'default'`

**Comment by gitdallas** [comment]
@mcoker @mattnolting - are we still removing `alignment` prop from all 3 components in favor of `align`?

```
  alignment?: {
    default?: 'alignRight' | 'alignLeft';
    md?: 'alignRight' | 'alignLeft';
    lg?: 'alignRight' | 'alignLeft';
    xl?: 'alignRight' | 'alignLeft';
    '2xl'?: 'alignRight' | 'alignLeft';
  };
```
to
```
align?: 'right' | 'left' | 'default';
```

**Comment by mcoker** [comment]
@gitdallas yep, only toolbar items and group have CSS support for the classes that `alignment` applies.

**Comment by gitdallas** [comment]
@mattnolting @mcoker 
mind taking a look at [pr diff](https://github.com/patternfly/patternfly-react/pull/8563/files)? i think i'm supposed to be able to get the styles from the component styles rather than from the flex layout, but not sure.
