### ISSUE TITLE
Raw svg in React repo display differently than font awesome icons in core

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#837]
The raw svg in React repo display differently than font awesome icons in core.  Core and React should match.

Comment from Doug Miller in reference to the issue:
>We are using raw svgs not the font icons. I looked into this before, and it has to do with family adding a top attribute to the icons or something similar. I will need to look again. We will need to do this as well in the react-icons package for the font awesome svgs.

**Comment by mcarrano** [comment]
@dlabaj As far as I can tell, this has been fixed.

**Comment by dlabaj** [comment]
Closing issue based on comment above.
