### ISSUE TITLE
Support for page sidebar custom content

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8386]
Placeholder for the core work in https://github.com/patternfly/patternfly/issues/4982

This will add content/body elements and potentially variants to allow for custom page sidebar content.

**Comment by thatblindgeye** [comment]
Per conversation on Slack, this might also involve renaming the `nav` prop to be `children` and marking it as required, since more than just a nav element/component could be passed in. `isNavOpen` might also require a rename to be less specific to just a nav being open or not. cc @tlabaj @mcoker
