### ISSUE TITLE
Bug - TextArea - Breaks when `autoResize` is added to TextArea

### ISSUE THREAD

**Issue by hybridx** [patternfly/patternfly-react#8389]
**Describe the problem**
- Using TextArea in a Modal Component breaks with `TypeError: Cannot read properties of undefined (reading 'style')`

**How do you reproduce the problem?**
- Use TextArea in Modal component 

**Expected behavior**
- Should not break and auto resize on addition of text

**Is this issue blocking you?**
- No

**Screenshots**
<img width="1680" alt="Screenshot 2022-11-24 at 4 37 06 PM" src="https://user-images.githubusercontent.com/12994292/203769431-93ae1c0a-7cd2-4143-89b7-a82660d5f554.png">

**What is your environment?**
 - OS: MacOS 12.6.1
 - Browser: Google Chrome
 - Version: Version 107.0.5304.110 (Official Build) (x86_64)

**What is your product and what release date are you targeting?**
- SPAship

**Any other information?**
- N/A

**Comment by kmcfaul** [comment]
Closing this issue as I have not been able to reproduce the bug. If you are still experiencing this issue on the latest version of Patternfly please reopen the issue and/or message the team on slack.
