### ISSUE TITLE
Bug - TableComposable/IAction - Variant has no effect

### ISSUE THREAD

**Issue by japhar81** [patternfly/patternfly-react#8390]
**Describe the problem**
When adding a `variant: "danger"` to an IAction that's rendered via `ActionsColumn`, nothing happens.

**How do you reproduce the problem?**
https://codesandbox.io/s/nervous-mirzakhani-tx4egd

**Expected behavior**
The delete action should be highlighted red

**Is this issue blocking you?**
No workaround I can find

**Screenshots**
![image](https://user-images.githubusercontent.com/1619545/204071792-008a447c-a715-49ed-9e4e-4188eb0107d2.png)

**What is your environment?**
 - OS: MacOS Ventura 13.0.1
 - Browser: Verified on Firefox and Chrome
 - Version: Tried multiple, including latest

**Comment by mcarrano** [comment]
The actions menu in a table does not currently support all of the features of Menu. We agree it should and will plan to address this in PatternFly 5.
