### ISSUE TITLE
react-topology - upgrade mobx to the maintained development stream (either 6.x or 7.x)

### ISSUE THREAD

**Issue by vjwilson** [patternfly/patternfly-react#8393]
**Is this a new component or an extension of an existing one?**
react-topology

**Describe the feature**
This extension still uses a 5.x version of its `mobx` dependency. We should update it to either versions 6.x or 7.x

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
_No visuals_

**Any other information?**
Version 5 of `mobx` ceased being maintained in Fall 2020
Reference: [ANNOUNCING MOBX 6](https://michel.codes/blogs/mobx6)

**Comment by mcarrano** [comment]
@jeff-phillips-18 @jessiehuff FYI

**Comment by jenny-s51** [comment]
Following. James Talton brought this issue to the team's attention again today; current topology work is underway, and this is likely something that will be resolved as we restructure the repository. cc @jessiehuff @jeff-phillips-18

**Comment by vjwilson** [comment]
We got around this browser console error by implementing the following setting in our app.

https://github.com/stackrox/stackrox/pull/4556

**Comment by jeff-phillips-18** [comment]
Closing in favor of https://github.com/patternfly/react-topology/issues/16
