### ISSUE TITLE
Bug - Wizard - WizardWithDrawer example does not focus

### ISSUE THREAD

**Issue by XiangyuShen** [patternfly/patternfly-react#8394]
**Describe the problem**
Inside the WizardWithDrawer example for the Wizard component, onExpand is never called because it can only be set on the <Drawer> component to work correctly, and <Drawer> is no longer declared in the examples, since that logic is abstracted via the hasDrawer prop. Because of this, the opened drawer is not given focus.

**Expected behavior**
 When the drawer opens, the drawer (or rather the drawer's close button) should be given focus.

**Any other information?**
See #8287 
_Originally posted by @jenny-s51 in https://github.com/patternfly/patternfly-react/pull/8287#discussion_r1021651773_

**Comment by nicolethoen** [comment]
it looks like the existing drawer examples are placing the focus on the drawer body itself when the drawer opens, not the close button. 
I could update all examples to place focus on the close buttons? Or I could make the wizard with drawer example focus on the drawer body when it is expanded like the existing examples do now.

**Comment by nicolethoen** [comment]
For this issue, I will move browser focus onto the drawer body as is done in the other drawer examples. 
I have opened follow up issues in [core](https://github.com/patternfly/patternfly/issues/5319) and [react](https://github.com/patternfly/patternfly-react/issues/8534) to make the focus handling of the drawer more similar to that of the modal.
