### ISSUE TITLE
Component - Notification Drawer

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-react#84]
Provide implementation for the notification drawer (http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design)

Note : Ang PF implementation can be found here for reference: http://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfNotificationDrawer

Associated JIRA Issue: https://patternfly.atlassian.net/browse/OSUX-303

**Comment by ohadlevy** [comment]
Foreman has already implemented most of this pattern, ideally we can start with that and later on send a pr to foreman to use the new patternfly component instead. for details see https://github.com/theforeman/foreman/tree/develop/webpack/assets/javascripts/react_app/components/notifications/drawer
