### ISSUE TITLE
DataList: Remove unneeded SelectableRowObject

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#8423]
There is only one item in the `SelectableRowObject`.  Previously it also had a `type` that was removed making the need of the object obsolete.  

Suggestion to make this update:

1. Remove the `selectableRow` prop 
https://github.com/patternfly/patternfly-react/blob/0cf2f9366120f27b9f5f10e530fc2be8d74b9221/packages/react-core/src/components/DataList/DataList.tsx#L56
Replace it with a prop called `onSelectableRowChange`

`/** Callback that executes when the screen reader accessible element receives a change event */
onSelectableRowChange?: (event: React.FormEvent<HTMLInputElement>, id: string) => void;`
(Note: the event should be first in parameter)

2.  Remove the SelectableRowObject
https://github.com/patternfly/patternfly-react/blob/0cf2f9366120f27b9f5f10e530fc2be8d74b9221/packages/react-core/src/components/DataList/DataList.tsx#L23-L26

**Comment by CodeDuchess** [comment]
@nicolethoen I would be happy to work this issue. Thanks.

**Comment by tlabaj** [comment]
Hi Dana!  That would be great.  This work is going toward our breaking change release, so please make the changes on the V5 branch.

**Comment by CodeDuchess** [comment]
@tlabaj I am still very new to PatternFly & React, so I do not know how you handle a lot of details. Do you want me to just comment out `selectableRow` everywhere in the code or actually delete it?

**Comment by tlabaj** [comment]
Hi @CodeDuchess.  We want to actually delete the `selectableRow` prop and replace it with the `onChange` prop that is currently defined in `SelectableRowObject`.  WE would then also delete the `SelectableRowObject`. 
We would need to update anywhere in the codebase that is referencing `selectableRow.onChange` to just reference the `onChange` prop. 
Let me know if you need any help.

**Comment by CodeDuchess** [comment]
@tlabaj I use git/repo slightly differently on my team. We always push to main. So, how do I choose the V5 branch? Typically we create and name our own branch and then `git push --upstream - origin issue-branch` So I am not sure how I ensure I am pushing to the V5. I see in the PFly contribution guidelines it says to run `git push origin my-branch.` So, do I just change origin to V5? Please advise. Thanks.

**Comment by nicolethoen** [comment]
I'd make sure you checkout pf-react's v5 branch, and then create a new branch off of that branch. Then you can push as you do normally

**Comment by CodeDuchess** [comment]
@nicolethoen I am working on this issue. It is just a slow process because it has been awhile since I last created a PR, so I have to go back and reread the PatternFly reference and remind myself to use P-Fly's git procedure and naming conventions and not the one I use on my team.

**Comment by CodeDuchess** [comment]
@tlabaj I deleted the `SelectableRowObject` and the `SelectableRow` prop. It seems like that was the initial ask. However, in your second comment you talk about replacing with the `SelectableRow.onChange` to just `OnChange`. However, onChange was deleted in the `SelectableRowObject.` So, looks like I need to pull onChange out and define it elsewhere.. . .but it does not say that in the initial part of the ticket. Please advise.

**Comment by nicolethoen** [comment]
@CodeDuchess you'll want to replace SelectableRowObject with a prop on the `DataList` called `onSelectableRowChange`

the code snippet you'll add to define the new prop will be:
/** Callback that executes when the screen reader accessible element receives a change event */ onSelectableRowChange?: (event: React.FormEvent<HTMLInputElement>, id: string) => void;

then you need to make sure it's passed into the component the same ways the `SelectableRow.onChange` prop was previously passed and used.
