### ISSUE TITLE
Chip/label - update structure elements

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8454]
Placeholder for https://github.com/patternfly/patternfly/issues/5199 and https://github.com/patternfly/patternfly/issues/5335

Just along the lines of adding some sort of container to put the close button in instead of just placing it as a child with no sort of component identifier. Also require `.pf-c-chip-group__main`. Though it may already be required, it looks that from https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/ChipGroup/ChipGroup.tsx, but mentioning it just to confirm it's required since it's now required in core.

**Comment by nicolethoen** [comment]
I had to turn off integration tests to pull in the core updates for this issue. Be sure integration tests are back on and working or updated after this change
