### ISSUE TITLE
Topology - Counter scale labels

### ISSUE THREAD

**Issue by jeswanke** [patternfly/patternfly-react#8476]
**Is this a new component or an extension of an existing one?**
Topology

**Describe the feature**
As a topology gets bigger, it needs to be zoomed out to see all of it, but then the labels become more illegible. 
This feature counter scales the labels so that as the zoom out increases, the labels are zoomed in.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
![CleanShot 2022-12-23 at 09 27 23@2x](https://user-images.githubusercontent.com/60980397/209353226-58efdc87-097a-45fe-a3f5-f4e5e981a7e2.png)
**Any other information?**

**Comment by jessiehuff** [comment]
It looks like the relevant PR was merged so closing this issue. Feel free to reopen it if there is something still missing!
