### ISSUE TITLE
Bug - DropdownNext - throws error when onOpenChange not provided

### ISSUE THREAD

**Issue by Dominik-Petrik** [patternfly/patternfly-react#8479]
**Describe the problem**
It should be possible not to pass onOpenChange prop to Dropdown since it is an optional prop. In contrast with this an error is thrown when onOpenChange is not passed to the Dropdown.

**How do you reproduce the problem?**
[codesandbox](https://codesandbox.io/s/great-burnell-7ocqfg?file=/src/App.tsx ) - Press tab or escape key when dropdown toggle is focused.

**Expected behavior**
No error should be thrown when onOpenChange is not provided

**Comment by tlabaj** [comment]
closed by #8640
