### ISSUE TITLE
SimpleList - missing classes on list and list items

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8482]
We're missing `.pf-c-simple-list__list` on the `<ul>`'s
* https://github.com/patternfly/patternfly-react/blob/a79102e34357dbe6416783830bd4580c934342d2/packages/react-core/src/components/SimpleList/SimpleList.tsx#L77
* https://github.com/patternfly/patternfly-react/blob/a79102e34357dbe6416783830bd4580c934342d2/packages/react-core/src/components/SimpleList/SimpleListGroup.tsx#L30

Missing `.pf-c-simple-list__item` on the `<li>`'s 
* https://github.com/patternfly/patternfly-react/blob/a79102e34357dbe6416783830bd4580c934342d2/packages/react-core/src/components/SimpleList/SimpleListItem.tsx#L79

**Comment by nicolethoen** [comment]
they don't have styles attached, so the classes are not shipped with react-styles. They will need to be hardcoded.

**Comment by Noothan-am** [comment]
hey @mcoker is this issue still open? can i get more info about this issue?

**Comment by mcoker** [comment]
Hey @Noothan-am, yep it's still open but likely will not be addressed until after our major release. Is it blocking you in any way?
