### ISSUE TITLE
Table - document overlap/z-index issues with sticky headers/columns

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#8486]
re: https://github.com/patternfly/patternfly/issues/5238

We are working on a core fix for this, but for now we can mention that there may be z-index conflicts, and include a couple of general workarounds.

**Comment by mcoker** [comment]
@mcarrano it looks like this is already in place - https://www.patternfly.org/v4/components/table#sticky-table-modifiers

The second paragraph outlines the issue and includes 3 approaches to address it. Do you agree it's ok to close this issue?

**Comment by mcarrano** [comment]
Yes, I think so. But will we still pursue a more permanent fix for v5?

**Comment by mcoker** [comment]
@mcarrano yep!
