### ISSUE TITLE
Widgets like Switch should only react to left click

### ISSUE THREAD

**Issue by martinpitt** [patternfly/patternfly-react#851]
Right now, widgets like [Switch](https://patternfly-react.surge.sh/patternfly-3/?knob-Size=normal&knob-On%20Color=primary&knob-Off%20Color=default&knob-animate=true&selectedKind=patternfly-react%2FWidgets%2FSwitch&selectedStory=Switch&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) react to middle and right mouse clicks as well, which is wrong. Particularly, right click also brings up the context menu. This can be demonstrated right at the linked storybook demo.

Their event handlers should only do something if `ev.button == 0`, i. e. left click.

**Comment by jeff-phillips-18** [comment]
The switch component here only wraps the [react-bootstrap-switch](https://github.com/Julusian/react-bootstrap-switch). You might file an issue there. Otherwise we would need to re-write our switch component to handle this.

**Comment by martinpitt** [comment]
Sure, makes sense! I filed it at https://github.com/Julusian/react-bootstrap-switch/issues/53 instead.
