### ISSUE TITLE
Tabs - Option for tabs to look like toggle group (but function as a tabs)

### ISSUE THREAD

**Issue by kdoberst** [patternfly/patternfly-react#8513]
**Is this a new component or an extension of an existing one?**
Modification of the tabs component

**Describe the feature**
For OCM, there is a request for a widget to act and behave like tabs, but actual tabs visually look like single selectable toggle group buttons.  I've put in custom SCSS in OCM to make this work, but if this is a design pattern that will be used moving forward, it makes sense to make this an option in PF.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Example:
https://user-images.githubusercontent.com/82059948/211366481-15c66da3-c28b-4b72-a079-dfffab138ff8.mov

**Any other information?**
I've created the custom SCSS in OCM if it is helpful.

The `associate-roles-drawer__tabs` class is applied on the `<Tab>` component.  GitHub wouldn't let me upload a `.scss` file so  I changed the extension to a `.txt' file.
[accountDrawerTabs.txt](https://github.com/patternfly/patternfly-react/files/10375426/accountDrawerTabs.txt)

**Comment by mcarrano** [comment]
@kdoberst can you say more about the use case and context here. Why can't you just use the existing toggle group?

**Comment by kdoberst** [comment]
It all has to do with functionality and the markup to support that functionality.  The behavior of the buttons in this case behaves as if they were tabs - therefore the markup should match.

We could _create_ our own component that uses the toggle buttons but would need to manually add all the supporting markup (like roles, aria attributes) and custom key events (arrow keys, etc).  That is a whole lot of extra custom code.  On the other hand, we can change the look of the tabs and use the PF tabs component which does have a lot of the markup already provided.

This is a widget that will be used in future designs in OCM.  Since this is going to be used a lot more in the future, I was hoping that this change could be made inside of PatternFly instead of hosting custom components.

**Comment by mcarrano** [comment]
Per discussion on Mar 10,we will create a code sandbox to demonstrate how to do this. We do not intend to modify the tab component as this will lead to confusion about usage of tabs vs toggle buttons.

**Comment by nicolethoen** [comment]
I've created this codesandbox in the Patternfly account for future reference if people want tabs which look like a toggle group: 
https://codesandbox.io/s/tabs-as-toggle-group-fhtvym

**Comment by mcarrano** [comment]
Thanks @nicolethoen . I will close this issue.
