### ISSUE TITLE
PF4 Sequence Component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#855]
Introduce PF4 Sequence component: https://pf-next.com/components/Sequence/examples/
This component is required to build the wizard. See closed core issue for more details. https://github.com/patternfly/patternfly-next/issues/767

In addition to a React review, this issue should be reviewed by the core contributors of this demo:
CSS: @christiemolloy

**Comment by christiemolloy** [comment]
Still working on the Sequence in CSS

**Comment by dlabaj** [comment]
Should be an internal component, and no PF3 version to compare apis with.

**Comment by LHinson** [comment]
@christiemolloy ok, I've marked this as "on hold" in react for now. Keep us posted.

**Comment by LHinson** [comment]
Closing this one for now since Wizard has been kicked back to design.
