### ISSUE TITLE
[react-log-viewer] - [Remove react log viewer in favor of it being placed in it's own repo]

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react#8569]
**Is this a new component or an extension of an existing one?**
 react-log-viewer extension

**Describe the feature**
react-log-viewer extension should be removed from this repo in favor of it living it's own repo found [here](https://github.com/patternfly/react-log-viewer)

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
No

**Any other information?**
Dependent on this issue https://github.com/patternfly/react-log-viewer/issues/8

**Comment by nicolethoen** [comment]
Closed by https://github.com/patternfly/patternfly-react/pull/8571
