### ISSUE TITLE
[Topology] - [withContextMenu support for Promise]

### ISSUE THREAD

**Issue by jshaughn** [patternfly/patternfly-react#8588]
On PF Topology, the `withContextMenu` support allows to supply an array of `ContextMenuItems`.  This is fine if the menu items can be determined immediately given the element, but in some cases determining the menu items may require supplemental information and may require data retrieved asynchronously.

It would be nice if `withContextMenu` could supply both an explicit array (could be an initial set of options) and an optional Promise that could supply the final set of options.  The contextMenu may need to display a `loading...` type message while the Promise is being resolved, not sure.

**Comment by jshaughn** [comment]
I don't think you should have stalebot closing issues that have been created because the PFT team asked for them to be created in a Slack thread, at least not with some justification.

**Comment by jeff-phillips-18** [comment]
Closing in favor of https://github.com/patternfly/react-topology/issues/15
