### ISSUE TITLE
Bug - MenuItem - no easy way to make link open in new tab

### ISSUE THREAD

**Issue by vjwilson** [patternfly/patternfly-react#8593]
**Describe the problem**
The MenuItem component has a `to` prop that turns it into a link. It also has a `isExternal` prop, which causes an "external link" icon to appear on its right-hand side.

However, there is no obvious way to make that link open in a new tab. A new tab makes sense when the link is to further documentation about how to do something on the page with the menu item.

**How do you reproduce the problem?**
```
        <Menu>
            <MenuContent>
                <MenuList>
                    <MenuItem
                        isExternalLink
                        to="https://google.com"
                        target="_blank"
                        rel="noopener noreferrer"
                        itemId={0}
                        description="Cluster installation guides"
                    >
                        View instructions
                    </MenuItem>
                </MenuList>
            </MenuContent>
        </Menu>
```

**Expected behavior**

Options:

- A prop, which automatically adds `target="_blank" rel="noopener noreferrer"` to the generated link when used with `to`
- The ability to pass through those attributes to the link element (see this Slack thread for where current pass-through props go, )
- at least a documented workaround, to make the `<MenuItem>` link open in a new tab

**Is this issue blocking you?**
Because I need to ship this, I changed to a Dropdown component with DropItems, which allows the link to be passed as a child.
```
        <DropdownItem key="link" isExternalLink description="Cluster installation guides">
            <a
                href="https://docs.openshift.com/acs/installing/acs-installation-platforms.html"
                target="_blank"
                rel="noopener noreferrer"
            >
                View instructions
            </a>
        </DropdownItem>,
```

**Screenshots**
n/a

**What is your environment?**
 - OS: Mac OS 12.6 Monterey
 - Browser Chrome
 - Version 109.0.5414.87 (Official Build) (arm64)

**What is your product and what release date are you targeting?**
RHACS, Feb. 1, 2023

**Any other information?**
n/a

**Comment by thatblindgeye** [comment]
Closed via #9294
