### ISSUE TITLE
Tab - default to type="button"

### ISSUE THREAD

**Issue by shaofeng66** [patternfly/patternfly-react#8631]
The Tab is now rendered as HTML <button>, the default behavior of which is submits the whole form when clicked. This is barely the expected behavior when tabs is used.
> From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button: 
> If your buttons are not for submitting form data to a server, be sure to set their type attribute to button. Otherwise they will try to submit form data and to load the (nonexistent) response, possibly destroying the current state of the document.

Current I can use type="button" explicitly to override the default behavior, after one hour of debugging. Is it possible to change the default to not submit, to avoid future debugging effort?

**Comment by nicolethoen** [comment]
Hi @shaofeng66, thank you for opening an issue!

as of right now, [the tab's button is set to `type='button'` by default](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Tabs/TabButton.tsx#L30), unless an `href` is passed to the tab.
Are you using an href in your tab button?

**Comment by shaofeng66** [comment]
@nicolethoen Thanks, I used an old version(4.221.3) and hit exactly the same issue as issue #7887, which was fixed by pr #7892.
