### ISSUE TITLE
Composable table sticky column support

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#8632]
The ROS feature for Cost Management requires additional sticky column support. Specifically, the ability to create multiple sticky columns for the last two table columns. Currently, we can only make the first table column sticky.

For example, there are `hasRightBorder` and `stickyLeftOffset` properties, but don't see anything to help make columns sticky on the right side of the table.

**Cost Explorer Example** - The first table column and last two columns are sticky
![Screen Shot 2023-01-31 at 9 03 18 AM](https://user-images.githubusercontent.com/17481322/215789412-fd441f7b-cf57-46c1-9786-746567d1882c.png)

**Any other information?**
The ROS feature for Cost Management is required for Summit 2023

**Comment by mcarrano** [comment]
@mattnolting can you take a look at the feasibility of this?  

Also, @dlabrecq I see your timeline. This will be a problem as there is not another PF release planned until v5 in June. We can consider a special release, however this will require escalation to identify necessary resources.

**Comment by mattnolting** [comment]
@mcarrano We already have `.pf-m-border-left` in place, so it looks like we'd need only to update PF React to add `hasLeftBorder` and `stickyRightOffset` props (`th/td` already support `stickyMinWidth` and `isStickyColumn` regardless of DOM position). 

https://codesandbox.io/s/quizzical-leakey-0785m2?file=/index.tsx

**Comment by mcarrano** [comment]
@dlabrecq we will pull this into our next milestone with the expectation to do a special v4 release. Date for that is currently TBD. Do you have a code freeze date that we need to keep in mind?

**Comment by dlabrecq** [comment]
It would be ideal to have this ready for March. We need to be code complete by April 1st.

**Comment by nicolethoen** [comment]
Closed by #8714
