### ISSUE TITLE
Topology ColaGroups layout: performance issues

### ISSUE THREAD

**Issue by alwayshooin** [patternfly/patternfly-react#8638]
**Describe the problem**
The `ColaGroups` layout of the library causes severe performance issues to the point where it crashes my browser.

**How do you reproduce the problem?**
* https://topology-demo-latest.surge.sh/ -> `Topology package`
* change `Layout` to `ColaGroups` 
* set `Nodes` to `20`, `Edges` to `40`, `Groups` to `5`
* click `Add Node` a few times
* performance starts to crash after the second node that is added to the point where the rest of the page is unresponsive and I have to close the tab to refresh the page
* if you wait a few more minutes at this state, the browser will crash for you and show the screenshot below

**Expected behavior**
It should not crash my browser tab 

**Is this issue blocking you?**
I ended up using `ColaNoForce` instead 

**Screenshots**
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/10412893/216132524-3723f09e-763d-408b-9df3-955433103878.png">

**What is your environment?**
 - OS: macOS Ventura 13.2
 - Browser: Chrome
 - Version: 109.0.5414.87

**What is your product and what release date are you targeting?**
ACS Network graph, we're releasing using the Topology library as tech preview with an anticipated release date of 3/20/2023.

**Any other information?**
I think at the very least some documentation or warning about the performance impact of this layout would be helpful -- I spent too many hours trying to debug why I had a memory leak in my app before I realized it was the layout :/

**Comment by jeff-phillips-18** [comment]
Closing in favor of https://github.com/patternfly/react-topology/issues/10
