### ISSUE TITLE
Bug - Topology - hover outline lost on top edge of nodes

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#8660]
**Describe the problem**

When you hover a default node, the top outline of the node disappears as the outline shifts to a drop-shadow.

**How do you reproduce the problem?**
View demos on patternfly.org: https://www.patternfly.org/v4/topology/topology-view
Find any node that has the default grey outline and hover it.

**Expected behavior**
Node outline should

**Is this issue blocking you?**
no

**Screenshots**
default:
![image](https://user-images.githubusercontent.com/14068621/217266994-dc228bb1-62d6-42d5-92b2-f75ac13bdf04.png)
hover:
![image](https://user-images.githubusercontent.com/14068621/217267039-d7eca36c-05fd-4046-af6a-ae8e010493e7.png)

**What is your environment?**
 - OS:Mac OS
 - Browser: Chrome
 - Version: 108.0.5359.124

**What is your product and what release date are you targeting?**
none

**Any other information?**

**Comment by jeff-phillips-18** [comment]
Closing in favor of https://github.com/patternfly/react-topology/issues/9
