### ISSUE TITLE
Label - Make labels clickable

### ISSUE THREAD

**Issue by OndrejZobal** [patternfly/patternfly-react#8665]
**Is this a new component or an extension of an existing one?**
Label

**Describe the feature**
Label should have an `onClick` prop and act like a button, currently only links are possible via the `href` prop. 

A button-like functionality for labels is strongly hinted at in the design guidelines but is missing from the implementation: https://www.patternfly.org/v4/components/label/design-guidelines#when-to-use-clickable-labels

**Comment by mcarrano** [comment]
We agree this is a good enhancement and we will get it on our roadmap.
