### ISSUE TITLE
Popper - cleanup props and pipe through popperRef

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-react#8666]
`reference` could be renamed to `triggerRef`.
`popperRef` is not exposed to other components that use `Popper`.

If we want users to utilize the alternate strict mode warning resolution (passing references and avoiding the wrapping div), then we should make sure components that use `Popper` have these props available and support them (as the trigger would have be rendered on the component side rather than passed to Popper).

**Comment by nicolethoen** [comment]
Closing in favor of https://github.com/patternfly/patternfly-react/issues/8481
