### ISSUE TITLE
PF4 Data List 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#867]
Please note, this is issue is for Data List only (even though documents below also reference Table). 

[Requirements documentation](https://docs.google.com/document/d/1gyD2_Boy3gOHNl5KVo86274HTT_aqZMQz3coviJZIt8/edit)

Also see [Lists and Tables documentation](https://docs.google.com/document/d/1jYKhaFKvMKH1h2VJEDS4dtReMUmepDp99C4x4UNHNZk/edit). 

PF-Core example: https://pf-next.com/components/DataList/examples/

In addition to a React review, this issue should be reviewed by the core contributors:
CSS: @mattnolting (CSS) @mcarrano (design)

**Comment by dlabaj** [comment]
Took a look at List View below.  It's made up of a large amount of children components and the api is pretty limited.   Migration shouldn't be an issue for consumers of this component from a list view.

http://patternfly-react.surge.sh/patternfly-3/index.html?selectedKind=patternfly-react%2FContent%20Views%2FList%20View&selectedStory=List%20of%20expandable%20items&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
