### ISSUE TITLE
Release notes need to be improved

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#869]
The release notes for all packages are incorrect right now - shown here: https://github.com/patternfly/patternfly-react/releases.  They should be including the changes built from semantic-release style commit messages and include correct package names.  For instance: patternfly3-react-lerna-root@7.8.0 should never be released or listed here and there are no relevant changes listed for patternfly-react-extensions@2.12.0

**Comment by dgutride** [comment]
The release notes for all packages are incorrect right now - shown here: https://github.com/patternfly/patternfly-react/releases.  They should be including the changes built from semantic-release style commit messages and include correct package names.  For instance: patternfly3-react-lerna-root@7.8.0 should never be released or listed here and there are no relevant changes listed for patternfly-react-extensions@2.12.0

**Comment by dgutride** [comment]
@priley86 and I had started looking into this a while back and held off at the time if you need more information.

**Comment by priley86** [comment]
It would be great to adopt semantic-release style commit messages as opposed to cz-convential-changelog. Hopefully they are well supported in lerna's CHANGELOG.md generation for each package (have not tested this but it seems it would support this).

Regarding the root CHANGELOG.md, my guess is this is easiest to solve upstream in `lerna-changelog` in the short term, but I am not positive on this. I filed an [issue](https://github.com/lerna/lerna-changelog/issues/128) upstream requesting feedback.

**Comment by redallen** [comment]
Fixed in #1348 for now. I would ideally like to roll-up the release notes and separate dependencies enough to stop seeing constant "version bumps."
