### ISSUE TITLE
PF4: Social Icons Component - LoginPage Footer

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-react#871]
Introduce the login footer containing the `Or log in with` and social icons component for the LoginPage. This will need to be integrated with the LoginPage component (#604)  and the example will need to be updated. 

**FYI**: There is a `More...` option in core that will show a different view of the social icons.
See: https://github.com/patternfly/patternfly-next/issues/801

**Comment by rachael-phillips** [comment]
@dlabaj @jschuler to investigate for react implementation

**Comment by tlabaj** [comment]
Closed by PR #1319
