### ISSUE TITLE
Bug - [Date picker] - [Date range picker demo is broken]

### ISSUE THREAD

**Issue by idryzhov** [patternfly/patternfly-react#8730]
**Describe the problem**
[Date range picker demo](https://www.patternfly.org/v4/components/date-picker/react-demos/#date-range-picker) is broken.

**How do you reproduce the problem?**
There are two different errors I can reproduce, but I think they are related.

1. Choose dates in both fields and you'll see the following error:
  ```
  TypeError: null is not an object (evaluating 'e.split')
  ```
2. Choose date in the first field and start entering text in the second. You'll see the following error:
  ```
  TypeError: e.split is not a function. (In 'e.split("-")', 'e.split' is undefined)
  ```

**Expected behavior**
There should be no error.
The demo was definitely working at least on Jan 23 (the last time I checked it).

**Is this issue blocking you?**
I don't know a workaround.

**Screenshots**
I provided easy steps to reproduce the issue. If needed, I can provide screenshots/screenrecords.

**What is your environment?**
 - OS: macOS
 - Browser Safari
 - Version 16.3

**Comment by nicolethoen** [comment]
Closed by #8760
