### ISSUE TITLE
Bug - Tabs - scrolling doesn't work consistently

### ISSUE THREAD

**Issue by edewit** [patternfly/patternfly-react#8769]
**Describe the problem**
When there are a large number of tabs you can scroll them with arrow buttons, but sometimes the scrolling stops even though the end has not been reached.

**How do you reproduce the problem?**
Easiest way might be using the keycloak console, see issue https://github.com/keycloak/keycloak/issues/17677

**Comment by MariaAga** [comment]
Is there a way to reproduce it without installing keycloak? could not reproduce it with https://codesandbox.io/s/many-tabs-7l09cy?file=/index.tsx 
tried resizing the screen/devtools/zooming in

**Comment by edewit** [comment]
right @MariaAga seems to be something in combination with what we do with the tabs instead of the component

**Comment by javac9** [comment]
You may find a useful clue by taking a look at the tabs under "User details" (version is 21.1.1). I don't see the error there (tried couple of times), while the tabs under "Realm settings" are still showing the same erroneous behaviour).

**Comment by edewit** [comment]
They are exactly the same:
```
<RoutableTabs
          isBox
          mountOnEnter
          defaultLocation={toRealmSettings({
            realm: realmName,
            tab: "general",
          })}
        >
```
```
        <RoutableTabs
          data-testid="user-tabs"
          defaultLocation={toUsers({
            realm: realmName,
            tab: "list",
          })}
          isBox
          mountOnEnter
        >
```

**Comment by edewit** [comment]
Can we re-open this issue, because this is still something that we see happening and it's reproducible on all tab pages when you make the window really small
