### ISSUE TITLE
BreadcrumbItem - allow the breadcrumb item separator to be customized

### ISSUE THREAD

**Issue by vjwilson** [patternfly/patternfly-react#8781]
**Is this a new component or an extension of an existing one?**
Existing component: BreadcrumbItem, a sub-component of [BreadcrumbItem](https://www.patternfly.org/v4/components/breadcrumb)

**Describe the feature**
Currently, the separator in a list of breadcrumbs is hard-coded as a <AngleRightIcon /> component.
([Link to current code](https://github.com/patternfly/patternfly-react/blob/83c54ab517dd329d924d69ade0430c389aaff5b1/packages/react-core/src/components/Breadcrumb/BreadcrumbItem.tsx#L47-L52))

Our RH product has a design which calls for a "breadcrumb" look to display a hierarchy of cluster / namespaces / deployments, with selectors. (see screenshot below)
UX has spec'ed the separator as a forward-slash (/).

<img width="452" alt="Screen Shot 2023-03-06 at 11 57 12 AM" src="https://user-images.githubusercontent.com/715729/223178976-3526f80b-5a51-4874-a355-8de772af1ff8.png">

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
See screenshot in section above.

**Any other information?**

1. Can this separator be made configurable, so that we can most efficiently implement this design? (We already have a tech preview of this built and released in version 3.74.0 of our installed product, with the right-angle bracket icon for now.)
2. If there is a comparable component in PatternFly, that does not require any custom coding and can mimic the functionality of the breadcrumbs, please reply with that option.
3. If the forward-slash has already been considered by the greater UX and PatternFly team's and rejected for some reason, please reply with those reasons.

**Comment by mcarrano** [comment]
@vjwilson I reached out to UXD folks supporting ACS from a design perspective to better understand the use case here. Based I that we concluded that you should not be using a breadcrumb here as breadcrumb are primarily for navigation and it seems like this is really a filtering mechanism for the content on the page. I'm including an alternate design below which just uses 3 plain select menus with dividers in between. This can be constructed using existing components.



![Image](https://user-images.githubusercontent.com/6619860/227293064-13154c7d-1e6f-4b96-9bd7-1103c79630ee.png)

Will this work? Let me know if you have any questions about how you could implement this.
