### ISSUE TITLE
Bug - TableComposable - "<output> cannot appear as a child of <tbody>" error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#8807]
When I add `isSelectable` to the table's `Tr` component, an `<output>` tag is added as a sibling of the HTML `<tr>` tag.
As a result, we see an "<output> cannot appear as a child of <tbody>" error in the browser console.

**Error**
![Screenshot 2023-03-14 at 10 18 37 AM](https://user-images.githubusercontent.com/17481322/225033811-053c32da-4edf-46ce-822f-4b000a653e1c.png)

**HTML**
![Screenshot 2023-03-14 at 10 19 55 AM](https://user-images.githubusercontent.com/17481322/225033870-2dc5a560-9b1c-441c-ab57-74a85f775601.png)

**Table**
![Screenshot 2023-03-14 at 10 20 16 AM](https://user-images.githubusercontent.com/17481322/225033984-0139ea7e-d7ab-4aa4-ac5d-73aa0e5b680a.png)

**Comment by dlabrecq** [comment]
FYI, @mattnolting

**Comment by mattnolting** [comment]
@dlabrecq `<output>` isn't valid as a child of `table, thead, tbody, or tr`. Looks like there are several options to update. 

- Add a dynamic element to caption: https://www.w3.org/WAI/tutorials/tables/caption-summary/#nesting-summary-inside-the-caption-element
- Use a dynamic element outside of the table, as described here: https://www.w3.org/WAI/tutorials/tables/caption-summary/#using-aria-describedby-to-provide-a-table-summary
- Add a dynamic `aria-label` to a clickable row's `th`

**Comment by dlabrecq** [comment]
@mattnolting Are you suggesting to replace the first `Td` cell of each row with a `Th`? I no longer see the error message; however, we also define the `Th` in `Thead` for sorting.

Adding a `caption` also removes the error, but we end up with a visible description in the table's toolbar, which we don't want.

**Comment by mattnolting** [comment]
> @mattnolting Are you suggesting to replace the first Td cell of each row with a Th? Adding aria labels to Tr, Td, Th, etc. has no effect -- React still generates a validateDOMNesting error.

@dlabrecq I'm suggesting that we make informative cell in the row a `th` as an option. We already do that in several other places, so the functionality is already there, then add `aria-describedby` to the parent `tr`. 

See: 
- https://www.patternfly.org/v4/components/table/html#checkboxes-and-actions-example
- https://www.patternfly.org/v4/components/table/html#single-select-radio-example
- https://www.patternfly.org/v4/components/table/html#expandable-example

and many more... 

Also, `output` appears to be a redundancy. When I select a row, the `aria-label` for the selected row is dynamically updated,  then `VO` announced `Row selected`. I _think_ it's safe to remove the `<output>` element altogether. 

@nicolethoen @wise-king-sullyman @thatblindgeye  Looks like this would be a fairly easy and straightforward update. WDTY?

**Comment by dlabrecq** [comment]
I'm fine using a `th` as an "informative cell in the row". I just want to be clear that does not resolve the React `validateDOMNesting` error. If the proposed solution includes removing the `<output>` element, then that sounds good to me.

**Comment by thatblindgeye** [comment]
I believe we originally added the output to provide a way to announce when a row was selected immediately without having to put something on each table cell, and other attempts at the time didn't work as well. The `aria-label` on the `tr` also doesn't seem to announce the selected state even with aria-live added in (at least for my VO; if it works for others then it's a matter of some setting which may not be as big a deal).

Maybe an output (or similar hidden live region) could work better as a part of the caption similar to how we're rendering visually hidden content in the caption in React, but for now removing the output sounds fine to me to at least remove this error ASAP.
