### ISSUE TITLE
Enhance checkbox select to include search in input field

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-react#8813]
Currently, the checkbox select component only supports having a search input INSIDE the menu.

We would like to request having the search inside the input itself, like a type-ahead kind of functionality. Console dot already implements this in various places, but the solution is a bit messy/hacky, so we'd like to have it available in PF.

Can see an example here (ignore the fact that the height of the input changes - that is not desired).

https://user-images.githubusercontent.com/51165119/225373652-ef7f6fa8-7a73-4871-a659-86254eee3ed5.mov

**Comment by Fewwy** [comment]
You can find the code that is implementing the tags filter here 
https://github.com/RedHatInsights/frontend-components/tree/bf78f005040669a4b33ad11e09314afcc5dab61a/packages/components/src/FilterHooks

and here 
https://github.com/RedHatInsights/insights-inventory-frontend/blob/cf8da9d10b92fce503b8af8216ded14bc35c427e/src/components/InventoryTable/EntityTableToolbar.js#L129

**Comment by nicolethoen** [comment]
@Fewwy and @mmenestr 

There are a few ways you could implement this with Select. 
I'd recommend using the Select-next component (which will be promoted to the recommended Select solution in v5). I have a codesandbox I'd already wired up for another product with a very similar use case: https://codesandbox.io/s/custom-checkbox-multi-typeahead-select-x83wbc?file=/index.tsx

The Select-next component allows you to pair any MenuToggle design with any of the basic select menu designs.

If you need a MenuToggle to ever be paired with something more complex Menu design, you can wire up any MenuToggle to work with any Menu design in any combination. [A bunch of demos have been created on this page](https://www.patternfly.org/v4/demos/composable-menu) to show many of the ways you can wire up MenuToggles and Menus.
