### ISSUE TITLE
test dark theme in the react workspace

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#8815]
Some of the details here may need to be filled out once the dark theme work in core is further along.

- [x] Once dark theme has been added to core's v5 alpha, pull in that version and get the build working - likely put up a PR so that a preview builds and can be shared with core/design
- [ ] audit the dark theme in the react workspace and note anything that is styled oddly in dark theme. Make special note of how components change during interactions and as states update.
- [ ] Work with @mcoker and the core team to open follow up issues in core to address issues discovered

**Comment by mcarrano** [comment]
Opening and documenting issues found during this testing here: https://docs.google.com/document/d/1cvhnDIN2e93dwZvXDxrHNtFvSVPz-Hu-YgzI3XMO5kM/edit?usp=sharing

**Comment by nicolethoen** [comment]
This has been completed
