### ISSUE TITLE
Bug - [All] - [react core esm packages should explicitely import the .mjs files from react-styles]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#8871]
**Describe the problem**
In cockpit we are importing files like import "@patternfly/react-core/dist/esm/components/Button/index.js";

I was recently analyzing the bundled output and noticed that the files that are imported from react-styles are not the .mjs ones but the plain CommonJS. This results in the use of 'require' instead of 'import'.

![Screenshot from 2023-03-27 23-44-34](https://user-images.githubusercontent.com/14921356/228075266-b5c66419-9d6e-43ed-9bb1-6eb3a517cb87.png)

**Expected behavior**
I expect that the esm/ directory imports directly from the .mjs files from react-styles.

**Is this issue blocking you?**
No

**Comment by mcarrano** [comment]
@dgutride thoughts? cc @nicolethoen
