### ISSUE TITLE
PF4 progress bar shows 10% as min value

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#888]
The Koku UI currently uses the latest PF4 progress bar and in some cases, shows zero as the percentage value. However, the progress bar itself still shows zero as 10%.

Similar to how 100% shows a full bar, I expect zero to show an empty bar.

Zero percent
![progressbar zero percent](https://user-images.githubusercontent.com/17481322/48086099-034fb980-e1ca-11e8-9037-09b253213ed3.png)

10 percent
![progressbar 10 percent](https://user-images.githubusercontent.com/17481322/48086220-4c077280-e1ca-11e8-8ac3-57e1b9c2a381.png)

**Comment by ibolton336** [comment]
c_progress__indicator_MinWidth is set to "2rem". Not sure where to change this but setting the min width to 0 should fix it.

**Comment by ibolton336** [comment]
This is a PF-next issue. Closing & reopening in patternfly-next.

**Comment by dlabrecq** [comment]
Won't the react-core package need to be updated in order to receive the fix from pf-next? At a min, the pf-next new issue could be added here, before closing, so we can track progress.

**Comment by ibolton336** [comment]
[link to pf-next issue](https://github.com/patternfly/patternfly-next/issues/913)
