### ISSUE TITLE
Dropdowns w/ Icons and custom Buttons

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#889]
I attempted adding an Icon/Button to our Dropdown toggle and it seems the spacing is slightly off. This appears to be due to the fact that `<Button>` will apply a default class of `pf-c-button pf-m-plain` adding the space. If I add `pf-c-dropdown__toggle` to the Button's `className` prop, I will receive `pf-c-button pf-m-plain pf-c-dropdown__toggle` classes (still adding the space). For now, the easy workaround is to just use a jsx `button`.  Maybe we should add a prop specifying type to `Button`, so we can say type "dropdown" only applies `pf-c-dropdown__toggle`? Please advise on the desired effect here for icon dropdown's.

Tried code:
```
      <Toolbar>
        <ToolbarGroup>
          <ToolbarItem className={classNames('pf-u-sr-only', 'pf-u-visible-on-md')}>
            <Dropdown
              isPlain
              direction="top"
              onSelect={this._onSettingsDropdownSelect}
              toggle={
                <Button onClick={this._onSettingsDropdownSelect} id="settings-button" aria-label="Settings actions" className="pf-c-dropdown__toggle">
                  <CogIcon />
                </Button>
              }
              isOpen={isSettingsDropdownOpen}
            >
              <DropdownItem>About</DropdownItem>
            </Dropdown>
          </ToolbarItem>
```

Workaround code:

```
      <Toolbar>
        <ToolbarGroup>
          <ToolbarItem className={classNames('pf-u-sr-only', 'pf-u-visible-on-md')}>
            <Dropdown
              isPlain
              direction="top"
              onSelect={this._onSettingsDropdownSelect}
              toggle={
                <button onClick={this._onSettingsDropdownSelect} id="settings-button" aria-label="Settings actions" className="pf-c-dropdown__toggle">
                  <CogIcon />
                </button>
              }
              isOpen={isSettingsDropdownOpen}
            >
              <DropdownItem>About</DropdownItem>
            </Dropdown>
          </ToolbarItem>
```

**Comment by jschuler** [comment]
Hi @priley86 , I think using DropdownToggle and having the option of hiding the caret solves your needs right? I am closing this issue, but if there's still an open question around this please let me know, thanks!
