### ISSUE TITLE
Bug - DatePicker - Error stays when resetting the date

### ISSUE THREAD

**Issue by kmalyjur** [patternfly/patternfly-react#8905]
The error does not disappear when resetting the invalid value of the DatePicker to a blank one by not manually deleting it.

**Steps to reproduce:**
https://codesandbox.io/s/determined-banzai-h2876p?file=/index.tsx
1) Write some invalid date into the text input of the DateTime component (e.g. "a")
2) Click the "Clear date" button
=> The error message and the error icon do not disappear as they should

I am using @patternfly/react-core@4.271.2.

**Comment by nicolethoen** [comment]
Problem is within dateParse. If you override it making empty string a valid date, you should be good to go.


![Image](https://user-images.githubusercontent.com/26305082/229897379-59469757-07a6-4104-898a-5bab9783e031.png)
