### ISSUE TITLE
Update the patternfly-icons FilterIcon to use the fa-filter rather than pf-filter-icon

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#8917]
Seems that the Filters demo uses the incorrect filter icon: 
![228327924-af5acee9-23ad-4d3f-9923-e775aabb0a55](https://user-images.githubusercontent.com/26305082/229816679-e0cfa924-caef-497f-b5d8-ba8aec6b270e.png)

It should look like: 
![228327638-9e0e16ff-a491-47d7-843a-e3bb99e5880c](https://user-images.githubusercontent.com/26305082/229816751-f9e9e6cc-4ab0-44bb-8d80-c8da0d1957a9.png)

And the icon docs explain the following about filter icons:
![229525530-3a5b1cdf-5fb6-4bd5-9748-8ab373d965c3](https://user-images.githubusercontent.com/26305082/229816813-10bd7e1f-307a-4a2e-b099-401927d1c019.png)

**Comment by evwilkin** [comment]
FYI V4 does show both the old custom PF filter icon as well as the correct FA filter icon:
https://patternfly-react.surge.sh/icons/

V5 only shows the old custom PF filter icon - the FA filter icon is missing:
http://patternfly-react-v5.surge.sh/icons
