### ISSUE TITLE
Bug - [EmptyState] - [EmptyStateIcon is enormous no matter the EmptyState components variant]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#8947]
**Describe the problem**
Follows a screenshot of the PF5 docs I build locally.

**Expected behavior**
EmptyStateIcon should follow the Icon sizing and derive from the EmptyState component variant it's sizing.

**Is this issue blocking you?**
Custom CSS can be applied I guess as an override.

**Screenshots**
![Screenshot from 2023-04-13 12-23-45](https://user-images.githubusercontent.com/14921356/231731313-3e4cd1b8-7fc3-46ca-92c3-71c2e3153141.png)

**What is your product and what release date are you targeting?**
Cockpit

**Comment by tlabaj** [comment]
Thanks @KKoukiou we are seeing this elsewhere as well (e.g. Card demos).
