### ISSUE TITLE
Bug - Tooltip - Tooltip can no longer be used in SVG components

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-react#8966]
**Describe the problem**
Using the `Tooltip` component within an SVG element (`<g>`) creates a `<div>` element and hence does not show the elements wrapped by the `Tooltip`.

**How do you reproduce the problem?**
Create an SVG (eg. Topology) and add a tooltip on the text of an element.

**Expected behavior**
The subelement show correctly and hovering on them shows the tooltip

**Is this issue blocking you?**
Yes.

**Screenshots**
![image](https://user-images.githubusercontent.com/11633780/232596955-6d5e6d1c-46c0-4bc7-b6fb-188995027e32.png)

**What is your product and what release date are you targeting?**
Patternfly react-topology v5

**Any other information?**
This worked fine in v4:

![image](https://user-images.githubusercontent.com/11633780/232597306-4d4bdc0a-0c00-4e20-b3fc-4d538fa96289.png)

**Comment by nicolethoen** [comment]
@kmcfaul do we have a workaround for this already?

**Comment by wise-king-sullyman** [comment]
I'm poking around at this, passing something for the triggerRef gets the node to work properly, but nothing I've tried passing to it yet has actually made the tooltip show up.

**Comment by nicolethoen** [comment]
I remember discussing adding an ability to define the element type that wraps the tooltip so that it could be configured by the consumer to be something else like a 'span'. would that help here?

**Comment by wise-king-sullyman** [comment]
I've _maybe_ got something that is working

**Comment by kmcfaul** [comment]
The `triggerRef` / `popperRef` update is the largest update to Tooltip recently from what I recall, @wise-king-sullyman is your solution something to do with the wrapping div messing with something?

**Comment by wise-king-sullyman** [comment]
@kmcfaul Yeah I'd seen that in your triggerRef PR you mentioned triggerRef being required on Tooltips now to prevent the wrapping divs, which did work to get the node to properly render.

Getting the tooltip to render right was pretty much just a matter of finding the right element to pass, which I've done for one usage of it in topology so far.

**Comment by wise-king-sullyman** [comment]
Closing per above discussion.
