### ISSUE TITLE
Bug - Wizard - The `appendTo` property is ignored by the wizard

### ISSUE THREAD

**Issue by shaded-enmity** [patternfly/patternfly-react#8972]
**Describe the problem**
`appendTo` and possibly other props are not properly delegated:
(https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Wizard/Wizard.tsx#L576)

**How do you reproduce the problem?**
Use Wizard with `appendTo` other then document.body

**Expected behavior**
`appendTo` being properly delegated

**Is this issue blocking you?**
Yes

**What is your product and what release date are you targeting?**
ASAP/Summit

**Any other information?**

Discovered by @Hyperkid123

**Comment by nicolethoen** [comment]
Closing per comment: https://github.com/patternfly/patternfly-react/pull/9008#issuecomment-1536357285
