### ISSUE TITLE
DataList - implement full page Basic demo to match HTML

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#8982]
Add a demo to the DataList React demos tab which matches the [Basic demo under the HTML Demos tab](https://www.patternfly.org/v4/components/data-list/html-demos#basic).

- It does not need to implement working pagination or filtering - the toolbar at the top of the DataList is for context, so it does not need to be fully functional 
- The Page layout and scaffolding is extremely similar to that of the [Card View React demo](https://www.patternfly.org/v4/demos/card-view#card-view) (code found [here](https://github.com/patternfly/patternfly-react/blob/v5/packages/react-core/src/demos/Card/Card.md)). The primary difference is the presence of Cards in the card view demo and DataList in the DataList demo.
- The DataList items should match as closely as possible to the corresponding HTML Demo
- The source branch for the issue work should be patternfly-react's V5 branch, and that is also the branch your code should merge back into. 
- It will likely be necessary to move the [DataListDemo.md file](https://github.com/patternfly/patternfly-react/blob/v5/packages/react-core/src/demos/DataListDemo.md) into a directory much like the CardView demo is in a Card directory under demos.

**Comment by Kells512** [comment]
Hello, I think I had to comment here about taking on the task
