### ISSUE TITLE
Bug - [*Icon] - [Icons from react-icon (not the Icon component)] do not match any of the sizeo options from Icon

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#8990]
**Describe the problem**
['size' property was removed from createIcon](https://github.com/patternfly/patternfly-react/pull/5275#discussion_r1154800887). The default size now is supposed to be "sm" according to [this comment](https://github.com/patternfly/patternfly-react/pull/5275#discussion_r1154800887). However, this "sm" is not matching the "sm" from the Icon component. But it' not matching "md" either, it's something between these two.

 Can you please make it clear how the mapping is between the old sizes and the new way of resizing the icons? 

**How do you reproduce the problem?**
![Screenshot from 2023-04-24 12-35-47](https://user-images.githubusercontent.com/14921356/233981178-2687695e-77a8-4374-aa48-e89bcc236c44.png)

**Expected behavior**
The *icons created with createIcon should have size="md" matching the dimensions of the`  <Icon size="md" `...

**What is your product and what release date are you targeting?**
Cockpit

**Comment by nicolethoen** [comment]
This is intended. We should clarify this in the docs.

When you don't determine the size, it simply defaults the icon to 1em so that it matches the font size.

**Comment by KKoukiou** [comment]
@nicolethoen and the way to determine size is to pass `<Icon size..>`  around the desired icon? If so that's a bit too verbose and from consumer and code readability perspective worse than before. Why did we decide on this change?

**Comment by nicolethoen** [comment]
The default font size is 14, react-icons (not wrapped in an `Icon` component) will have a size of 1em and match the font size. 

react-icons wrapped in an `Icon` component and using the `isInline` prop will also have a size of 1em and match the font size.

So in this case, you don't need to use an Icon component. Someone would use an inline `Icon` component when they want to swap out two icons dynamically and want them both to take up the same amount of space.

There is not a size variant of the `Icon` component which makes the size 1em. I don't think this is a change?
