### ISSUE TITLE
[TextList vs List] - [Please clarify the difference between these two components]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#9007]
What the difference between https://patternfly-react-v5.surge.sh/components/text/#unordered-list and https://patternfly-react-v5.surge.sh/components/list/#basic ? Seems like exactly the same use case to me.

**Comment by nicolethoen** [comment]
I'm happy to update the Text component's summary at the top of our docs to try to make this clearer. For now I think my best answer to this is as follows:

`Text` components are all intended to be used ONLY within `TextContent` as part of the readable static text content of a page. `Text` is much more lightweight.
 
`List` components can be used anywhere else. `List` also gives you more features, even for static stuff like icons.
