### ISSUE TITLE
Bug - [Icon] - [Icon resets color to --pf-v5-c-icon__content--Color which is not always wanted]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-react#9099]
**Describe the problem**
it's a use case (at least in cockpit) to define icon buttons. When these needed to be resized we need to use the Icon wrapper around the icon, since Patternfly 5 removed the size property on the different icons from react-icons.
When this is used the color is reset to black.

**How do you reproduce the problem?** 
``` jsx
<Button variant="plain" aria-label="Action">
      <Icon size="xl"><TimesIcon /></Icon>
</Button>
```

**Expected behavior**
The Icon color should inherit the 'plain' button variant color.

**Is this issue blocking you?**
CSS workaround, setting color: inherit.

**Screenshots**
Problematic screenshot:
![Screen Shot 2023-05-10 at 13 13 39](https://github.com/patternfly/patternfly-react/assets/14921356/d196eca9-65f4-45cc-accb-63ac4375805d)

Expected:
![Screen Shot 2023-05-10 at 13 13 56](https://github.com/patternfly/patternfly-react/assets/14921356/0a71fabd-e437-4000-8eec-73e01f4a0aad)

**What is your product and what release date are you targeting?**
Cockpit

**Comment by mcoker** [comment]
Hey @KKoukiou! This should be fixed now via https://github.com/patternfly/patternfly/pull/5525. I updated the icon component to inherit `color` and `font-size` by default - though you could do that before using the `isInline` prop, it's the default behavior now. https://codesandbox.io/s/cocky-leaf-d3y4ti?file=/index.tsx
