### ISSUE TITLE
Component - Tooltip

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#91]
Implement a component that provides the following UI element:

- [PatternFly Tooltip](http://www.patternfly.org/pattern-library/widgets/#tooltip)

**Comment by priley86** [comment]
@jgiardino @mcarrano I've merged the base functionality for Tooltip in #79 . Let's follow up here on any remaining issues.

**Comment by jgiardino** [comment]
This looks good to me. I'm closing this issue.
