### ISSUE TITLE
Bug - Pagination - Shrinking the pagination control has odd results

### ISSUE THREAD

**Issue by gitdallas** [patternfly/patternfly-react#9109]
When viewed in a small area, some of the pagination examples are showing odd or duplicate data such as. Can be seen here https://patternfly-react-v5.surge.sh/components/pagination - for example:
![image](https://github.com/patternfly/patternfly-react/assets/5322142/0aebb40a-1205-4193-82b8-b5826070bb17)

**Comment by MariaAga** [comment]
Working on a fix for this

**Comment by gitdallas** [comment]
after latest core bump, this is looking fine. example:

![image](https://github.com/patternfly/patternfly-react/assets/5322142/53e4d5a8-26ae-4d9d-be59-cd665e6a52a5)
