### ISSUE TITLE
Bug - Calendar - misaligned button when validation text appears

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-react#9136]
**Describe the problem**
If an invalid date is entered, the reset/toggle calendar button is misaligned. This happens on the Controlled example and the Controlling the date picker calendar state example.

**How do you reproduce the problem?**
Go to https://www.patternfly.org/v4/components/date-picker#controlled and enter an invalid date

**Expected behavior**
The primary button on the left should maintain alignment with the input.

**Screenshots**
<img width="380" alt="image" src="https://github.com/patternfly/patternfly-react/assets/19825616/f3f82888-95d0-4ae6-b47d-de42ae7fdb7e">

**Comment by tlabaj** [comment]
@srambach this also seems to be broken on the v4 branch https://www.patternfly.org/v4/components/date-picker

**Comment by nicolethoen** [comment]
I think it may be improved by simply placing the button above the datepicker on a separate line.
