### ISSUE TITLE
Bug - some new imports broken when trying to update to v5

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#9161]
bumping versions to:
```
"@patternfly/patternfly": "5.0.0-alpha.64",
"@patternfly/react-charts": "7.0.0-alpha.31",
"@patternfly/react-code-editor": "5.0.0-alpha.116",
"@patternfly/react-core": "5.0.0-alpha.115",
"@patternfly/react-icons": "5.0.0-alpha.19",
"@patternfly/react-styles": "5.0.0-alpha.16",
"@patternfly/react-table": "5.0.0-alpha.117",
"@patternfly/react-tokens": "5.0.0-alpha.14",
```
and running code mods (version 1.76.0), the following errors are being reported:
```
Most issues seem to be relates to module imports, which I cannot seem to fix.
export 'Select' (imported as 'SelectDeprecated') was not found in '@patternfly/react-core/deprecated' (module has no exports)...
TS2305: Module '"@patternfly/react-core/deprecated"' has no exported member 'Select'...
TS2724: '"@patternfly/react-core"' has no exported member named 'InputGroupItem'...
TS2305: Module '"@patternfly/react-core"' has no exported member 'EmptyStateHeader'...
```

we need to figure out if there's a change we need to direct products to make ahead of running codemods so that this works seamlessly, or if there's a problem on our end.

**Comment by gitdallas** [comment]
It seems that in this case the pf versions weren't actually installed, @nicolethoen . i believe this can be closed

https://patternfly.slack.com/archives/C03LQ25DDLN/p1684521701290119?thread_ts=1684517229.497629&cid=C03LQ25DDLN

**Comment by gitdallas** [comment]
the reason they weren't installed is that `npm install` was being used and there were conflicts between the alpha pf versions (updated package.json) and the versions of pf used in redhat-cloud-services/frontend-components. it seems that we can get around this by using the `--force` flag on `npm install`

**Comment by tlabaj** [comment]
Thanks Dallas

**Comment by gitdallas** [comment]
This sounds like something we should just be aware of and not really something we can do about on the PF end.

Older versions of npm would ignore more types of conflicts. We can use flags to replicate the older behavior. Using `--force` will install both versions which should work fine although will cause a bigger project size.

Best solution is to make sure we don't have conflicts which may require other projects to update. In the examples of HCS and Cost Management we'd need `redhat-cloud-services/frontend-components` to update their version of PF.
