### ISSUE TITLE
Bug - Pagination - Default `page` renders negative first index

### ISSUE THREAD

**Issue by josemigallas** [patternfly/patternfly-react#9165]
**Describe the problem**
When omitting prop `page` (default value is 0) the first index is `(0 - 1) * perPage + 1;` -> `1 - perPage` a negative number.

**How do you reproduce the problem?**
```jsx
<Pagination itemCount={25} />
```

**Expected behavior**
First index should be 0.

**Is this issue blocking you?**
Set `page={1}´.

**Screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/11672286/0e74252a-199e-41b4-8a3f-278d00eafc6d)

**What is your environment?**
`@patternfly/react-core@4.276.8`

**Any other information?**
The existing Pagination snapshots already confirm this bug:
https://github.com/patternfly/patternfly-react/blob/ff94267709508525b7fe8dd1da0b7ea6a33854aa/packages/react-core/src/components/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap#L2081

**Comment by MariaAga** [comment]
This is also a bug in v5, I'll take a look
