### ISSUE TITLE
Bug - v5 alpha testing - nested v5 selectors in v4

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9182]
The HCS UI's test environment contains a mix of pf4 and pf5 CSS in the page. Consoledot's Chrome currently wraps the HCS UI with a masthead and sidebar nav, and includes PatternFly's pf4 base CSS. For testing, the HCS UI also includes PatternFly's patternfly.css and patternfly-addons.css from pf5.

Although pf5 shouldn't conflict with pf4, the HCS UI has lost some styling. In particular, it's page padding as shown below.

![Screenshot 2023-05-24 at 11 19 13 PM](https://github.com/patternfly/patternfly-react/assets/17481322/36af2f29-d22c-4cb7-9deb-36319b906c5b)

For the `Grid` component; for example, the inspector shows vars are defined for `--pf-v5-l-grid--m-gutter--GridGap`, `--pf-v5-global--gutter`, etc.

![Screenshot 2023-05-24 at 11 36 38 PM](https://github.com/patternfly/patternfly-react/assets/17481322/1f347f77-b077-4ca8-bbf3-4a28b1fadd37)

However, for the `PageSection` component, the inspector shows undefined vars like -`-pf-v5-c-page__main-section-PaddingLeft`, `--pf-v5-c-page__main-section-PaddingTop`, etc.

![Screenshot 2023-05-24 at 11 30 19 PM](https://github.com/patternfly/patternfly-react/assets/17481322/db385b21-a102-41ed-8166-449a176c8c96)

I suspect `PageSection` needs to be nested within `pf-v5-c-page__main`? However, since the HCS UI is wrapped by Consoledot's Chrome, only `pf-c-page__main` is available.

This is just one of many missing vars. Therefore, I don't believe it's possible to truly support both pf4 and pf5 in the same page without additional modifications.

The HCS UI basically starts where the HTML is highlighted below. Note all the `pf-c-*` selectors in the page before that point.

![Screenshot 2023-05-24 at 11 54 49 PM](https://github.com/patternfly/patternfly-react/assets/17481322/882a23a4-c9cb-4a6a-8caa-326b9bdb5c1a)

That said, I don't see a migration path for Cost Management and the HCS UI, unless all of Consoledot updates to pf5 at the same time. However, if the selectors had not been renamed as `pf-v5-c-*`, I believe pf5 would have been compatible.

**Comment by srambach** [comment]
@dlabrecq you are correct, that the v5 variables scoped to page are not defined since the v5 page section is within the old `pf-c-page` instead of the new `pf-v5-c-page`. The simplest solution to this is to wrap your whole app in a div with `class="pf-v5-c-page" style="display:contents"`. This will provide the v5 variables without rendering another box for the page. We'll investigate a cleaner solution for this use case for a future release.

**Comment by dlabrecq** [comment]
The problem with adding `class="pf-v5-c-page" style="display:contents"` to a `div` is some dialogs are outside this scope, located elsewhere in the document body.

For example, this confirmation dialog
![Screenshot 2023-06-02 at 8 58 39 PM](https://github.com/patternfly/patternfly-react/assets/17481322/0be29ff7-9003-43b0-a966-f418e5a3d48e)

Even though we added `class="pf-v5-c-page" style="display:contents"` as suggested, you can see in the HTML below that id="pf-modal-part-56" is outside this scope.
![Screenshot 2023-06-02 at 8 58 30 PM](https://github.com/patternfly/patternfly-react/assets/17481322/82238899-33a4-493d-ad8f-635fd8580e3b)

**Comment by dlabrecq** [comment]
Since the `pf-v5-c-page selector` is no longer required, the UI looks fine now.
