### ISSUE TITLE
Bug - Navigation - Drill down navigation is broken

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#9183]
**Describe the problem**
If you click on the drill down item in the navigation menu, next level menus do not display. you get this:

<img width="330" alt="Screenshot 2023-05-25 at 9 49 23 AM" src="https://github.com/patternfly/patternfly-react/assets/6619860/b8836218-8da3-4b2d-8c6f-b46fa58eb5a6">

**Comment by wise-king-sullyman** [comment]
Git bisect is pointing me at https://github.com/patternfly/patternfly-react/pull/7683 for where this bug was introduced.
