### ISSUE TITLE
Bug - Number input - Number inputs now show spin buttons

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#9184]
**Describe the problem**
The number input fields now have spin buttons which leads to truncation and spacing problems. This was not the case for PatternFly 4

<img width="309" alt="Screenshot 2023-05-25 at 9 55 01 AM" src="https://github.com/patternfly/patternfly-react/assets/6619860/b15b68b9-ccce-4aa9-9dd8-c9b26ed97745">

**Comment by thatblindgeye** [comment]
This may be resolved in Core by https://github.com/patternfly/patternfly/pull/5609

**Comment by thatblindgeye** [comment]
Confirmed that the linked Core PR above resolved the issue in React: [number input in current React surge](https://patternfly-react-v5.surge.sh/components/number-input)

**Comment by tlabaj** [comment]
Thanks @thatblindgeye 
This issue has been closed by https://github.com/patternfly/patternfly/pull/5609
