### ISSUE TITLE
Convert toolbar layout to a component 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#919]
Convert toolbar layout to a component. Come up with the API. For now, we have to leave out the filtering as this is still being designed/developed in core. We will follow up with another issue. 

If any tests are required then include those.

**Comment by priley86** [comment]
This issues causes a problem for me when upgrading to `@patternfly/patternfly` version `1.0.210` and `@patternfly/react-core` version `2.2.9`. As I noted in #1333, the current nav items no longer hide on mobile with the usage here:
https://github.com/openshift/console/blob/master/frontend/public/components/masthead-toolbar.jsx#L242

As a workaround in my local code with the existing `pf-l-toolbar` usage:
```
@media screen and (max-width: 767px) {
  .pf-u-visible-on-md {
    display: none;
  }
}
```
So the use case problem presented is, the profile dropdown items should hide when the kebab is present. Currently that is not the case:
<img width="673" alt="screen shot 2019-02-27 at 4 41 48 pm" src="https://user-images.githubusercontent.com/4237045/53524979-ca0bc400-3aae-11e9-8b51-1d55f11f26fc.png">


We will need to upgrade the toolbar examples or the intention for consumers appropriately.

**Comment by priley86** [comment]
This issue I noted above can be resolved without override by using the `pf-u-screen-reader` class:
https://github.com/openshift/console/pull/1238/files#diff-ad1a22990eba749c0aeabdc5a78fe485

It would still be nice to revisit kebab usage in our PF React demos in this toolbar issue in the future if possible. Currently, OpenShift does not put the App Launcher or Help dropdowns into the kebab on `md` breakpoint. It would be nice to clarify in our examples if this is the intended usage of those in the future alongside the new toolbar component.

<img width="1011" alt="screen shot 2019-03-01 at 9 57 41 am" src="https://user-images.githubusercontent.com/4237045/53646425-27b42380-3c09-11e9-82cd-733652df691f.png">
