### ISSUE TITLE
Bug - Password strength demo - demo is broken in v5

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#9192]
**Describe the problem**
In testing v5, I found that the password strength demo no longer works. http://patternfly-react-v5.surge.sh/components/password-strength  When I enter text into the password field, I get [object Object]

<img width="843" alt="Screenshot 2023-05-25 at 3 21 58 PM" src="https://github.com/patternfly/patternfly-react/assets/6619860/1d62e5df-98cf-4a70-9117-ecefe0d1b6b8">

**Comment by MariaAga** [comment]
I'll take a look at this

**Comment by KKoukiou** [comment]
> I'll take a look at this

@MariaAga I opened yesterday a PR about it.
