### ISSUE TITLE
Bug - Pagination - spin buttons on number input

### ISSUE THREAD

**Issue by adamviktora** [patternfly/patternfly-react#9218]
Pagination: spin buttons should not be displayed (they are not shown in core), it is causing spacing issues. Also the input field seems small.

![Screenshot 2023-06-01 at 11 19 28 (2)](https://github.com/patternfly/patternfly-react/assets/84135613/7cb778c7-6022-4807-a943-99ecbfbca359)

**Expected behavior**
It should look like in the core implementation:
![Screenshot 2023-06-01 at 11 48 26 (2)](https://github.com/patternfly/patternfly-react/assets/84135613/d1d647d5-76e6-4747-b49d-9d2c78a38118)

**Comment by tlabaj** [comment]
duplicate of #9184
