### ISSUE TITLE
Bug - v5 alpha testing - hasSelectableRowCaption

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9228]
While testing the Cost management UI, I encountered the following error after applying the latest codemods. Ideally, the codemods would remove the `hasSelectableRowCaption` prop from Table

![Screenshot 2023-06-02 at 10 46 18 AM](https://github.com/patternfly/patternfly-react/assets/17481322/ccedc99c-cbef-4c9d-9d88-a8ef25069ed2)

**Comment by adamviktora** [comment]
@dlabrecq What is the name of the component which has the `hasSelectableRowCaption` prop? Is it `Table`?

**Comment by adamviktora** [comment]
oh, I see this issue has already been solved by Eric in this commit: https://github.com/patternfly/pf-codemods/commit/983880f0e3dda0a8f62385add774155666bb8d60

**Comment by thatblindgeye** [comment]
@dlabrecq can you confirm what component this error is being thrown for? Like Adam mentioned above a PR in our codemods should resolve this as I assume the component name is just "Table" (and not TableComposable), but just wanted to double check.

**Comment by thatblindgeye** [comment]
Yep, we have a codemod that will update TableComposable to just Table. If that codemod fix runs before the removal of hasSelectableRowCaption, then the prop wasn't previously removed. The latest update should resolve that so it removes the prop on either TableComposable or Table (after TableComosable is renamed).

**Comment by tlabaj** [comment]
Can we close this one @dlabrecq
