### ISSUE TITLE
Bug - v5 alpha testing - test failures due to Select imports

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9229]
While testing the Cost management UI, I encountered the following import error after applying the latest codemods. Currently, we have 66 test failures, all due to `Select*` component imports.

![Screenshot 2023-06-02 at 11 32 38 AM](https://github.com/patternfly/patternfly-react/assets/17481322/ea709b19-61a1-42a7-93e7-5fc02c583762)

**Comment by gitdallas** [comment]
@wise-king-sullyman - this feels familiar and like something i thought you fixed... something about esm. i searched our slack chat and found we began the convo and went to a call ( so i can't see the conclusion ) 😢

**Comment by kmcfaul** [comment]
@dlabrecq confirmed this is still an ongoing issue. It does look like potentially some babel configuration that may address it? Unless your call came to a different conclusion.

**Comment by wise-king-sullyman** [comment]
I think it's something that's off in my script that re-exports everything in the higher level deprecated path. Doing some testing now.
