### ISSUE TITLE
Attribute value (text box) Filter Demo

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react#923]
This is a follow up to https://github.com/patternfly/patternfly-next/issues/2218

For intended design behaviors see the Marvel prototpye: https://marvelapp.com/1i69c6ig

**Comment by mcarrano** [comment]
@LHinson @tlabaj Not sure if we still need this component. Do we have what we need to build filters today on React? I think there is still work on Filters pending, correct? I think we could make a TextBox filter from an input group.

Maybe we should just close this and open new issues if needed. Thoughts?

**Comment by tlabaj** [comment]
closed by #3127
