### ISSUE TITLE
Bug - v5 alpha testing - build failures

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9230]
While testing the Cost management UI, we encountered the following build errors when attempting to create PRs. The build appears to error because it cannot resolve the numerous dependency conflicts.

Note that we're only able to test locally using `npm install --force`.

See https://app.travis-ci.com/github/RedHatInsights/hybrid-committed-spend-ui/jobs/603454135 for the full log.

![Screenshot 2023-06-02 at 11 38 28 AM](https://github.com/patternfly/patternfly-react/assets/17481322/fcc6fdef-248c-4fe7-97d3-a4bf5ffdcfb4)

**Comment by gitdallas** [comment]
related to this https://github.com/patternfly/patternfly-react/issues/9161#issuecomment-1561683319

**Comment by dlabrecq** [comment]
Cost Management has 3 unresolved dependencies (below) with @redhat-cloud-services/frontend-components. 
However, we can add an override via the package.json file.

@patternfly/react-core
@patternfly/react-icons
@patternfly/react-table
