### ISSUE TITLE
Bug - v5 alpha testing - InputGroupItem layout

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9234]
While testing the Cost management UI, we encountered the `InputGroupItem` layout / padding. 

**Before**
![Screenshot 2023-06-02 at 3 46 17 PM](https://github.com/patternfly/patternfly-react/assets/17481322/f1bd7d8d-fb3e-4705-8107-95bae5a33edd)

**After**
![Screenshot 2023-06-02 at 3 47 45 PM](https://github.com/patternfly/patternfly-react/assets/17481322/ebe74d12-a8e2-4cf4-99be-ed780dd65b6f)

**Code**
![Screenshot 2023-06-02 at 3 48 21 PM](https://github.com/patternfly/patternfly-react/assets/17481322/11d315ee-1d01-425a-ada5-ee14f45d8543)

**HTML**
![Screenshot 2023-06-02 at 3 53 26 PM](https://github.com/patternfly/patternfly-react/assets/17481322/d2789f05-d477-4f8d-89a1-76b206d970b5)

**Comment by dlabrecq** [comment]
More examples

Before
![Screenshot 2023-06-02 at 4 11 42 PM](https://github.com/patternfly/patternfly-react/assets/17481322/2869952c-9e5e-4748-bb3c-bb1c89099666)



After
![Screenshot 2023-06-02 at 4 11 24 PM](https://github.com/patternfly/patternfly-react/assets/17481322/48d4d2e6-c195-4c67-8b44-46a04c96a9f3)

**Comment by dlabrecq** [comment]
Apparently, the codemods replaced `InputGroupText` with `InputGroupItem isBox`. I suspect this may not be correct?

![Screenshot 2023-06-02 at 9 51 47 PM](https://github.com/patternfly/patternfly-react/assets/17481322/096d51a2-c9ca-4f47-8f87-17143d4bdcc6)

**Comment by tlabaj** [comment]
@thatblindgeye do you know if the code mod was updated after the last updated to inputGroup?

**Comment by thatblindgeye** [comment]
The codemod should be up to date with the latest updates made to InputGroup.

Our test file for the codemod shows that InputGroupText doesn't get wrapped in InputGroupItem anymore, and running the --fix flag on our `test.tsx` file ends up with InputGroupText not being wrapped as well for me. The only way I'm able to get the Item wrapper around the Text is if I omit the InputGroupText import, but even then the `isBox` prop isn't applied.

@gitdallas are you able to reproduce the above issue where InputGroupText is wrapped inside of `<InputGroupItem isBox>`?

**Comment by gitdallas** [comment]
@thatblindgeye - it appears that dan was using an old version of codemods - likely the npx cached in the ide. 

codemods as of about 6 days ago should not have this issue, and i didn't when running it on koku a few days ago with `@latest`
