### ISSUE TITLE
Bug - [Popover.tsx] - minWidth doesn't set and defaults to revert.

### ISSUE THREAD

**Issue by shubhit7** [patternfly/patternfly-react#9279]
**Describe the problem**
https://github.com/patternfly/patternfly-react/blob/6b44876bfb15c8335fc6e263d63f41f55ae8636b/packages/react-core/src/components/Popover/Popover.tsx#L468

Why is `revert` hardcoded here/ I am trying to set the minWidth props but it always gets set to `revert`.

**Comment by kmcfaul** [comment]
The hardcoded value was added when the `Popper` `minWidth` prop was updated to have a new default, to prevent that change from propagating up through components that use it. Between that change and another change to `Popper` which removed the wrapping <div> elements though, `Popper` is now overriding the `Popover` `minWidth` prop that is being set directly on the style field. The line should be removed and made into a default value for the `Popover` prop instead.
