### ISSUE TITLE
Bug - Wizard - Can't build using parcel

### ISSUE THREAD

**Issue by cyyfyy** [patternfly/patternfly-react#9309]
When I try and use parcel to build the package, I get an error:

@parcel/transformer-css: Ambiguous
url('../../assets/images/status-icon-sprite.svg#success')
 in custom property. Relative paths are
 resolved from the location the var()
is used, not where the custom property
is defined. Use an absolute URL instead
 
**How do you reproduce the problem?**
install patternfly package, attempt parcel build of code with wizard component

**Expected behavior**
Should build

**Is this issue blocking you?**
The workaround is finding all the string references in the packages to the assets folder
much like the reference here: https://github.com/patternfly/patternfly/issues/4930
but also by manually removing references to /c/node_modules

**Comment by tlabaj** [comment]
Hello @cyyfyy  ver what version of PF are you running?

**Comment by cyyfyy** [comment]
"@patternfly/react-core": "^4.276.8"

**Comment by nicolethoen** [comment]
This should be addressed when v5 goes live! We can circle back around to verify.
Until then, there is a possible workaround in [this comment](https://github.com/patternfly/patternfly/issues/4930#issuecomment-1285445590) in the referenced issue.

**Comment by cyyfyy** [comment]
Thanks!

**Comment by wise-king-sullyman** [comment]
PatternFly v5 has gone live! Once you migrate to it we would be interested in hearing if the issue is resolved.
