### ISSUE TITLE
Bug - v5 preview testing - black modal footer

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9315]
While testing Cost management with pf-v5, I noticed the modal has a large, black footer. However, the wizard does not.

**Example 1**
![Screenshot 2023-06-28 at 2 17 39 PM](https://github.com/patternfly/patternfly-react/assets/17481322/00900a73-4369-423f-9e04-fff798ba2fbf)

**Example 2**
![Screenshot 2023-06-28 at 2 19 44 PM](https://github.com/patternfly/patternfly-react/assets/17481322/4a967dd7-98c3-4346-976b-acf4dc685552)

**Comment by tlabaj** [comment]
@dlabrecq I am not seeing this in our workspace.   Do you have any specific configurations or css overrides that could help use debug.  
Could you please provide a screenshot of the DOM.
