### ISSUE TITLE
Bug - Dropdown - When dropdown opens and outer page gets overflow, scrolling down is stuck

### ISSUE THREAD

**Issue by avivtur** [patternfly/patternfly-react#9326]
**Describe the problem**
Using the Dropdown component in a table row, causes sometimes the page to get overflow and the dropdown is getting focused on every scroll down. This happens only on firefox (installed version 113.0.1). 
adding screencast below

**How do you reproduce the problem?**
Please note that on sandbox this works as expected and only firefox is not
https://codesandbox.io/s/xenodochial-brook-ljcmvg?file=/index.js

**Expected behavior**
In case the dropdown is causing the page to overflow we should be able to see the bottom of the menu (as the chrome example I posted does)

**Is this issue blocking you?**
Not blocking me. My workaround is using Chrome for now 

**Screenshots**
firefox (note that I can't scroll to the bottom of the dropdown menu):

https://github.com/patternfly/patternfly-react/assets/67270715/154995b2-8ca7-4d8f-b6f4-9a1efc78f9bd

chrome (here everything works as expected):

https://github.com/patternfly/patternfly-react/assets/67270715/f1ee3eb1-2671-41b7-8cb6-ee8dea8c3237

**What is your environment?**
 - OS: fedora 36
 - Browser firefox
 - Version 103.0.1

**What is your product and what release date are you targeting?**

**Any other information?**
when the zoom is at 90% or lower this issue wasn't reproduceable for me, it was easier to reproduce on higher zoom like 110% and above

**Comment by tlabaj** [comment]
@avivtur What version of PF are you using?

**Comment by nicolethoen** [comment]
It looks like the codesandbox is using the latest v4 version. 
Is this something we could address in v5?

**Comment by avivtur** [comment]
@nicolethoen @tlabaj Hi thanks for your reply :) 
I'm using 4.122.2 version

**Comment by avivtur** [comment]
@nicolethoen @tlabaj Hi thanks for your reply :) 
Im using PF version 4.122.2 which seems quite old

**Comment by nicolethoen** [comment]
@tlabaj we should double check that this was indeed resolved in v5

**Comment by wise-king-sullyman** [comment]
For whoever takes on this issue: first step should be to check if this issue is resolved for the non-deprecated dropdown. If so this issue can be closed.

**Comment by avivtur** [comment]
@wise-king-sullyman Hi no worries :) 
We moved our project to v5 and it doesn't reproduce there AFAIK
