### ISSUE TITLE
PF4: react-core build warnings

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#934]
Seeing a bunch of react-core warnings while building the Koku UI. It appears to be related to BackgroundImage importing variables from react-tokens below.

![screen shot 2018-11-16 at 8 00 24 pm](https://user-images.githubusercontent.com/17481322/48654387-54d22280-e9da-11e8-9c64-5aa7a6817fe8.png)

Build warnings
![screen shot 2018-11-16 at 7 48 31 pm](https://user-images.githubusercontent.com/17481322/48654246-33bd0200-e9d9-11e8-8d76-ebd5eb2900da.png)

**Comment by redallen** [comment]
These don't happen after the BackgroundImage conversion.
