### ISSUE TITLE
Demos - clean up logo assets in demos

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9346]
**Describe the enhancement or change**
A clear and concise description of the request. What is the expected outcome?
There are a lot of duplicate images in the demos space.  Can we add an assets directory and get the image from one place in all demos.

**Comment by MariaAga** [comment]
Can I be assigned on this? I think it will be good to just move any image assets to `react-core/src/components/assets/` or `react-core/src/demos/assets/` depending on were the import happens

**Comment by tlabaj** [comment]
@MariaAga Yes, thanks for picking this one up.
