### ISSUE TITLE
Code improvement: Support React-Router Link in DropdownItem

### ISSUE THREAD

**Issue by ligangty** [patternfly/patternfly-react#940]
Hi, I'm a new guy for patternfly-react, and when I'm using Dropdown component, I found it is not supported to wrap a react-router Link component in DropdownItem. If doing that, a warning of "<a> should not wrapped in a <a>" or something similar will be reported in browser and finally the route will not work. As a work around, the declarative way of router context should be used inside. So I just wonder if this can be supported in the future as an improvement like below snippet?
```
<DropdownItem> 
     <Link to={to}>link</Link> 
</DropdownItem>
```

**Comment by kmcfaul** [comment]
Merged with #991
