### ISSUE TITLE
Bug - Select - Inline filter doesn't allow left/right arrows moving caret within entered filter text

### ISSUE THREAD

**Issue by jeswanke** [patternfly/patternfly-react#9404]
**Describe the problem**
The Select component has an hasInlineFilter option that opens a search field. The up and down arrows are used to navigate down to the available selections. However the left/right arrow keys are captured even when the input field still has focus preventing a user from pressing the left arrow back in the entered text.

**How do you reproduce the problem?**
There's a section in Select.tsx that captures left/right--even when the focus is on input and not on the menu:

<img width="395" alt="CleanShot 2023-07-26 at 10 36 20@2x" src="https://github.com/patternfly/patternfly-react/assets/60980397/a6776575-0630-4a8e-a141-4d4547c729b4">

**Expected behavior**
User should be able to click left/right arrow keys in text field.

**Is this issue blocking you?**
Not pretty but you can open a div under the Select and grab key down events and call stopPropagation on them to prevent them bubbling up to the Select and having those events being killed with preventDefault

**Screenshots**
![CleanShot 2023-07-25 at 14 37 49](https://github.com/patternfly/patternfly-react/assets/60980397/74904fe6-3564-48d6-88d8-afef006d823a)

**What is your environment?**
n/a

**What is your product and what release date are you targeting?**
    "@patternfly/react-core": "^4.276.8",

**Any other information?**

**Comment by adamviktora** [comment]
@wise-king-sullyman Can we close this issue as it is related only to the deprecated Select? Problem with caret moving in V5 is related to Menu component and is now tracked by this issue: https://github.com/patternfly/patternfly-react/issues/9750

**Comment by wise-king-sullyman** [comment]
@adamviktora yes since the v5 work is being tracked in that new issue I think this one can be closed.
