### ISSUE TITLE
Update all instance of old PF logo in examples and demos to new logo

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9443]
**Describe the enhancement or change**
Update all instance of old PF logo in examples and demos to new logo

component examples:
~~- About Modal~~
~~- Background image~~
~~- Brand~~
~~- Card~~
- Login Page

Demos:

~~-  Card~~
- Custom menus Application launcher demo
- Application launcher demo
- ~~notification drawer~~
- ~~wizard demo~~

**Comment by mcoker** [comment]
[PF logos.zip](https://github.com/patternfly/patternfly-react/files/13044800/PF.logos.zip)

**Comment by jenny-s51** [comment]
Waiting on https://github.com/patternfly/patternfly/issues/5724 cc @srambach @mcoker 

I've updated most of the components/demos with the new v5 logos. However the background logo needs the Penta updates in Core so the changes can be pulled in here. 

The background logo lives exclusively in the Core repo and is referenced via URL in a couple of places in addition to (https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/BackgroundImage/examples/BackgroundImageBasic.tsx#L5):
- [About Modal](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/AboutModal/examples/AboutModalBasic.tsx#L23)
-  [Login Page](https://github.com/patternfly/patternfly-react/blob/9b96292a79852b0cd6b119aff97b69b650e121c1/packages/react-core/src/components/LoginPage/examples/LoginPageBasic.tsx#L138)...

Link to the v4 background logo SVG which needs this Core update:
https://github.com/patternfly/patternfly/blob/b67d08e80065f9be206fae571f988ac4ff59e1ba/src/patternfly/assets/images/pfbg-icon.svg?plain=1
