### ISSUE TITLE
Bug - Form - isHorizontal property is not working in pf5

### ISSUE THREAD

**Issue by aljesusg** [patternfly/patternfly-react#9465]
**Describe the problem**
The forms with isHorizontal to tru are not working

**How do you reproduce the problem?**
```ts
<Form style={{ float: 'left' }} isHorizontal={true}>
{Items}
</Form>
```

**Expected behavior**

**Is this issue blocking you?**
yes is blocking

**Screenshots**

## Before
![image](https://github.com/patternfly/patternfly-react/assets/3019213/00b12ade-5203-47a5-8aa5-a6775f7b915f)

## Now

![image](https://github.com/patternfly/patternfly-react/assets/3019213/1b5f3a58-f6c1-46f3-929c-607c74da6ce8)

**What is your environment?**
"@patternfly/patternfly": "5.0.0",
    "@patternfly/react-charts": "7.0.0",
    "@patternfly/react-core": "5.0.0",
    "@patternfly/react-table": "5.0.0",
    "@patternfly/react-tokens": "5.0.0",
    "@patternfly/react-topology": "5.0.0",

**What is your product and what release date are you targeting?**
Kiali

**Comment by mcoker** [comment]
@aljesusg the [horizontal form example](https://www.patternfly.org/components/forms/form#horizontal) in our documentation looks OK to me. Would you mind updating this codesandbox with something minimal that matches your layout and reproduces the problem from your screenshot? https://codesandbox.io/s/compassionate-silence-hpt7dv?file=/index.tsx

**Comment by aljesusg** [comment]
I migrated all my component and worked thanks
