### ISSUE TITLE
port Cluster Upgrade wizard to patternfly-react

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-react#947]
As part of oVirt 4.3, we developed a Cluster Upgrade wizard. This wizard should be reused by ManageIQ and potentially other projects, so it should live in patternfly-react.

oVirt patch: https://gerrit.ovirt.org/#/c/93639/

cc @sjd78

**Comment by dgutride** [comment]
Moving to closed due to lack of activity
