### ISSUE TITLE
Bug - [NavItem] - [invalid TS type for the `component` prop]

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/patternfly-react#9492]
**Describe the problem**
The `NavItem` component has the `component` prop defined as a `ReactNode` but then uses it in the code as `React.ComponentType`

**How do you reproduce the problem?**
Use the NavItem `component` prop in any TS project with a custom react component (not `a` or a `div`).

**Expected behavior**
The `component` prop type should be `React.ComponentType`

**Is this issue blocking you?**
Many workarounds:
- typecastring
- ignoring the type check error
- redefining the module

**What is your product and what release date are you targeting?**
HCC, pf5 adoption starting Aug 21st, not blocking

**Comment by wise-king-sullyman** [comment]
The first part of this issue should be determining if this would be a breaking change. If so we will need to delay this fix until the next major release.

**Comment by Hyperkid123** [comment]
I don't think so, I think we just want to fix the type. Because the `component` prop is already used as `React.ComponentType`. You can't pass `ReactNode` to the prop. You will hit a runtime error.
