### ISSUE TITLE
Bug - "Start from scratch" link is confusing on read-only editors with actions

### ISSUE THREAD

**Issue by jgyselov** [patternfly/patternfly-react#9537]
**Describe the problem**

A code editor that is read-only but allows file uploads shows the "Start from scratch" link when it's empty. This is confusing, especially when you click it - because the editor is read-only, you cannot actually start from scratch.

**Expected behavior**

The "Start from scratch" link should not appear, when the code editor is read-only. 

"Browse" should be the only option.

**Screenshots**

![image](https://github.com/patternfly/patternfly-org/assets/87187179/8a83c13f-7c05-4782-8131-9e182e40395a)

**Comment by tlabaj** [comment]
After talking to design, we agree that the link and the button should both be removed.
