### ISSUE TITLE
Convert DashboardHeader and DashboardWrapper to TS

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#9544]
**Describe the enhancement or change**
There are build issues caused by these jsx files when using them with TS demos. 

The DashboardWrapper import is currently causing the build to fail in #9359 if the filetype is declared as `ts` and build issues were also seen in https://github.com/patternfly/patternfly-react/pull/9487 when trying to declare the demo as a `ts` file.

**Any other information?**
This was discovered through work on the #9367 epic

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/9553
- [ ] https://github.com/patternfly/patternfly-react/issues/9617
```

**Comment by wise-king-sullyman** [comment]
Closing as all tasks are complete.
