### ISSUE TITLE
Bug - @patternfly/react-tokens - some colors do not have the correct values

### ISSUE THREAD

**Issue by rh-gvincent** [patternfly/patternfly-react#9545]
**Describe the problem**
Dark theme in pf5 contains a number of additions and overrides to pf color palettes.
Those changes has not be ported to react-tokens.

Changes are listed here: https://www.patternfly.org/developer-resources/dark-theme-handbook/#whats-changed

For example

`--pf-v5-global--palette--black-800` value is `#1f1d21`
`global_palette_black_800` in `@patternfly/react-tokens` is `#3c3f42`

**Comment by mcoker** [comment]
It looks like we're ignoring anything within a `.pf-v5-theme-dark` selector:
https://github.com/patternfly/patternfly-react/blob/1e1305e5f7450e087ff8d1690d2be28b00dac0a1/packages/react-tokens/scripts/generateTokens.js#L26

I wonder if we could return those in a new object (eg, `dark`) in the existing token? Something like `global_palette_black_800.dark.value`, which would return `#1f1d21`.

```
global_palette_black_800.value  // #3c3f42
global_palette_black_800.dark.value  // #1f1d21
```
