### ISSUE TITLE
[Filter study] - Create working prototypes for filter study

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-react#9560]
**Is this a new component or an extension of an existing one?**
This is not for a component, but for a filtering study I am trying to conduct where I would like to test our existing attribute filter against a [new filter design](https://marvelapp.com/prototype/5ic41fd/screen/75659692) I came up with.

**Describe the feature**
I need two prototypes made for testing, one for each filter type that would include a toolbar with the filters attached to a table with dummy data. **Details are outlined in** [this document](https://docs.google.com/document/d/1ajNS-J6guAV3gzIU2jwTrr5XkNSRiGYTBbb8zfNfDZU/edit?usp=sharing).

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Yes, I had started making a mocked up prototype, and these are [the mocks](https://sketch.com/s/4f9b7534-e6cd-4082-ab71-a1c1b384b350) for that.

**Any other information?**
Looking to have this within the next week if possible (September 8th ish)

**Comment by jenny-s51** [comment]
Done. Closing with confirmation from @mmenestr 

Final demos as requested by @mmenestr can be accessed here:

- Out of the box, no initial filter states: https://halting-test.surge.sh/
- With preset filter states: https://gratis-thunder.surge.sh/
