### ISSUE TITLE
Bug - Dropdown Next - Unable to specify an appendTo target for the menu bug 

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-react#9564]
**Describe the problem**
Currently we can't customize what the menu appends to in Dropdown next.

**How do you reproduce the problem?**
Attempt to have the dropdown menu append anywhere in the DOM other than the default location.

**Expected behavior**
A clear and concise description of the expected behavior.
We should be able to have the menu append elsewhere in the DOM.

This issue is for the "Next" implementation of Dropdown in PF4

**Comment by adamviktora** [comment]
closing the issue manually, as https://github.com/patternfly/patternfly-react/pull/9652 was merged, and it somehow did not link
