### ISSUE TITLE
Popper - investigate whether logical properties can be used

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#9576]
**Is this a new component or an extension of an existing one?**
Popper

**Describe the feature**
Related to https://github.com/patternfly/patternfly/issues/5886

Before going further with the above issue, we should look into whether Popper can support using logical properties instead of directional, e.g. "block-start" instead of "top", in some fashion.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by wise-king-sullyman** [comment]
Moved to parking lot and removing from Q3 milestone since we want to wait on this until we move to floating-ui (assuming we do in the near future).

**Comment by srambach** [comment]
Close this to create an epic
