### ISSUE TITLE
PF4-PageLayoutDemo: Dropdown should only have a border on the hover state (like in Core)

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#959]
Same as the kebab/menu icon (used on mobile view)

Parent issue:
https://github.com/patternfly/patternfly-react/issues/955

**Comment by jschuler** [comment]
Probably needs https://github.com/patternfly/patternfly-react/pull/954/files and then need to update the pagelayoutdemo to use the isPlain prop on the dropdown toggle

**Comment by matthewcarleton** [comment]
This is being fixed in this PR https://github.com/patternfly/patternfly-next/pull/971 there should be no border at all for the plain dropdowns.

**Comment by jschuler** [comment]
Fixed with #954
