### ISSUE TITLE
Pagination - RTL support

### ISSUE THREAD

**Issue by mfrances17** [patternfly/patternfly-react#9599]
With RTL enabled, the language is still LTR for the current page and total pages, which seems odd. Examples:

LTR: 
`1-20 of 523  << <  1 of 27  > >>`

RTL: 
`<<  <  of 27 [ 1 ]  >  >>  of 523 20-1`

**Comment by mcoker** [comment]
That's one of the quirks of using an LTR language in an RTL doc. If I update the example to use an RTL langauge for the word "of", it displays as expected



<img width="479" alt="Screenshot 2023-09-11 at 3 50 17 PM" src="https://github.com/patternfly/patternfly-react/assets/35148959/537b9fd0-48e4-4296-9f12-44cef21f4683">
