### ISSUE TITLE
[JumpLinks] - support scroll container node reference for spy

### ISSUE THREAD

**Issue by christianvogt** [patternfly/patternfly-react#9636]
**Is this a new component or an extension of an existing one?**
What is the existing component, if any?
[JumpLinks](https://www.patternfly.org/components/jump-links)

**Describe the feature**
A clear and concise description of the new feature. What is the expected behavior?
`JumpLinks` has a prop called `scrollSelector` of type `string` whose purpose is: `Selector for the scrollable element to spy on. Not passing a selector disables spying.`

It should be possible to supply a direct node reference or call back function instead of only supporting a selector string. 

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

None

**Any other information?**

**Comment by christianvogt** [comment]
Bump waiting on response.

**Comment by tlabaj** [comment]
We will address this issue in a future sprint.
