### ISSUE TITLE
Toolbar - render expand-all icon internally

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#9647]
**Describe the enhancement or change**
Currently we have a ToolbarExpandIconWrapper component that has to be passed an icon manually. We should render an icon internally. Most likely just the AngleRightIcon, which is how a lot of our other components with expandable icons are setup; they don't allow passing a custom icon in, and we currently have CSS that rotates the icon based on the `pf-m-expanded` class being applied.

Related to https://github.com/patternfly/patternfly-react/pull/9605

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

**Comment by mcoker** [comment]
@thatblindgeye is this a dupe of https://github.com/patternfly/patternfly-react/issues/9641? If so feel free to close mine if you'd prefer keep this one open.

**Comment by thatblindgeye** [comment]
Oop, you're right! I'll close this out since yours was put up first
