### ISSUE TITLE
Badge Component Audit

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-react#966]
Discrepancies between Core and React:

Badges in React have a margin applied to them. The component shouldn't have margins, its parent should handle its layout, so I'm curious as to what this was used for?
Can we remove this margin from the badge:

`.css-1v6g7pq > span {
    margin: 0.5rem;
}`

**Comment by kmcfaul** [comment]
This span is added to the live preview wrapper and is not a part of the Badge component. Should I still remove this padding to better match the core?
