### ISSUE TITLE
Bug - Docs - Release highlight point to wrong form url

### ISSUE THREAD

**Issue by lordrip** [patternfly/patternfly-react#9663]
**Describe the problem**
At [the docs](https://www.patternfly.org/get-started/release-highlights), there's a text that reads like:
```
To add helper text to a form group in place of these properties you should use the FormHelperText, HelperText, and HelperTextItem components directly as part of the FormGroup’s children. This implementation is shown in PatternFly's [invalid form example.](https://www.patternfly.org/get-started/release-highlights/components/forms/form#invalid)
```

Notice how the URL points to the same page. Instead, it should point to https://www.patternfly.org/components/forms/form/#invalid

**Is this issue blocking you?**
No, it's not a blocker, the workaround is to navigate to the Form component's docs directly

**Screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/16512618/2ec5c08d-890a-4c15-bb61-00ddbfb96dc3)

**What is your environment?**
 - OS: [Fedora CSB]
 - Browser [Firefox]

**What is your product and what release date are you targeting?**
@kaoto-next

**Comment by nicolethoen** [comment]
Thank you for reporting this!
This URL has been fixed in [this commit](https://github.com/patternfly/patternfly-org/commit/b071d23ec5ac791da7b6bd60c9935585b4c15772) and will go live on the site next time the website is re-published

**Comment by lordrip** [comment]
Awesome, thanks a lot @nicolethoen 🎉
