### ISSUE TITLE
Consume core updates: Toolbar and Action List

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react#9677]
Follow up to Core [Toolbar](https://github.com/patternfly/patternfly/issues/5713) issue

in core bump PR #10022  he following was done:
- removed application of pf-m-chip-container modifier on toolbar group in ToolbarExpandableContent.tsx
- removed application of pf-m-buttonGroup modifier on toolbar group in
- removed import of @patternfly/react-tokens/dist/esm/c_toolbar__item_Width since it no longer exists. also comment out widths prop application since it depends on the token.
- Removed bulkSelect, overflowMenu, searchFilter modifier applications on toolbar item

**Comment by thatblindgeye** [comment]
Closed by #10041 and #10042
