### ISSUE TITLE
Page - add documentation for mainTabIndex

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9693]
Add documentation for mainTabIndex.  The consumer should update the value so it is not -1 when there is no skip to content.
We will change the default value in the next major release(https://github.com/patternfly/patternfly-react/issues/5920).

**Comment by deepchauhan2002** [comment]
Can you explain this issue @tlabaj

**Comment by tlabaj** [comment]
@deepchauhan2002 the default value for `mainTabIndex` is -1.  When you add a `SkipToContent` to the page you should change the default value otherwise the page will not function correctly as reported in this issue https://github.com/patternfly/patternfly-react/issues/5920.
We will update the default in a future breaking change release.  In the interim, we will update the example to demonstrate how to work around the issue.
