### ISSUE TITLE
Immutability in PF React

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react#97]
It seems that there are a lot of Immutability helpers in the wild with React. I would like to determine if we are OK w/ introducing any of these in PF React, or if we should just prefer simple state modification, i.e. `Object.assign` or direct array modification in our examples (fully recognizing that the state is typically not mutable).

Here is a list of some common ones I am seeing:
https://gist.github.com/jlongster/bce43d9be633da55053f

Can we mention any pros/cons we are seeing there?

**Comment by jtomasek** [comment]
TripleO UI uses immutable.js but we mostly use it on reducer -> selectors part. Do you have an example of when immutable data would be useful in patternfly-react?

If I was to choose lib for immutable data, I'd consider Ramda as it seems to have same functionality as immutable.js with POJO. https://github.com/este/este/issues/626

**Comment by sharvit** [comment]
I am personally not a big fan of Immutable libraries.
You can achieve an immutability by using ES2015 syntax + some babel transpilers.

https://wecodetheweb.com/2016/02/12/immutable-javascript-using-es6-and-beyond/

**Comment by sharvit** [comment]
We use `seamless-immutable` in foreman

**Comment by priley86** [comment]
After chatting in slack... it seems that we are OK w/ simple state modification and `Object.assign` in the simple Storybook examples. Appreciate all the feedback here. I'm going to close this for now.

**Comment by priley86** [comment]
It seems that another one has started trending quite recently...
https://github.com/mweststrate/immer
