### ISSUE TITLE
Bug - Chart - legendAllowWrap function generates an error

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-react#9718]
When using the `Chart.legendAllowWrap` function, I encounter a "Cannot read properties of null (reading 'props')" error. 

It's not an issue with the examples, I only encounter this in Cost Management. Believe this is related to the `useEffect` hook that wraps legend properties.

**Error**
![Screenshot 2023-10-07 at 1 08 39 PM](https://github.com/patternfly/patternfly-react/assets/17481322/1fa90352-00fe-4af0-878d-108ada7b6a98)

**Comment by tlabaj** [comment]
closed by #9719
