### ISSUE TITLE
Bug - Droppable - Empty Droppables do not receive Draggables

### ISSUE THREAD

**Issue by bostrick** [patternfly/patternfly-react#9749]
**Describe the problem**
When a "Droppable", as found in the "Multilist Example", is empty, it does not receive a Draggable.

https://www.patternfly.org/components/drag-and-drop/react/multiple-lists

**How do you reproduce the problem?**
Open the above link, move all items from right hand list to left hand list, and then attempt to move an item back.

**Expected behavior**
A empty destination Droppable, if given a min-height, should receive a Draggable, but doesn't.

**Is this issue blocking you?**
I've implemented an ugly workaround by adding a placeholder if a list is empty, and stripping it if it is not.

**Screenshots**
![image](https://github.com/patternfly/patternfly-react/assets/2624756/c1ebaa20-9125-49a5-b49d-984b4f6c9e16)

**What is your environment?**
 - OS: recent fedora (F38)
 - Browser: chrome
 - Version: google-chrome-stable-117.0.5938.149-1.x86_64

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by tlabaj** [comment]
@bostrick we recommend that you use the flex layout instead of the split layout.  I have pushed a PR to update our example code. you cna see that here https://github.com/patternfly/patternfly-react/pull/10692

**Comment by bostrick** [comment]
Thanks all!
