### ISSUE TITLE
Nav - add wrapper to Nav link item text by default

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9755]
**Describe the enhancement or change**
A clear and concise description of the request. What is the expected outcome?

Update `NavItem` to add the Nav link text wrapper (`.pf-v5-c-nav__link-text`) by default instead of as an opt-in.    Remove the `hasNavLinkWrapper` opt-in prop.

**Comment by thatblindgeye** [comment]
In addition to the above, as part of the work from https://github.com/patternfly/patternfly/pull/6704#pullrequestreview-2086095202 we will need to add a prop for an `icon` that must be rendered before the link text.

**Comment by mcoker** [comment]
This should be ready to work on now, work was done in https://github.com/patternfly/patternfly/pull/6704. And as @thatblindgeye mentioned in https://github.com/patternfly/patternfly-react/issues/9755#issuecomment-2138000772, there is a separate enhancement (that depends on the nav text wrapper) to add icon support to nav items. Not sure if we want a separate issue for that, or just include it as part of this update @tlabaj?
