### ISSUE TITLE
Chip 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-react#976]
Related Core Issue: https://github.com/patternfly/patternfly-next/issues/177 

In addition to a React review, this issue should be reviewed by the core contributors:
CSS: @christiemolloy and @mcarrano 

React Interaction: 
- Close button should remove chip. 
- Overflow button should show and hide chips
- Overflow button should count how many chips have overflown

**Comment by tconn89** [comment]
I do not see a Chip component in the code.  Are you referring to a Badge?

If not are you referring to a tag?  If so, would this issue be dependent on PR #351 Introduce Tagging React component? 
https://github.com/patternfly/patternfly-react/pull/351

**Comment by christiemolloy** [comment]
@tconn89 https://pf-next.com/components/Chip/examples/ and https://pf-next.com/components/ChipGroup/examples/

**Comment by LHinson** [comment]
@ibolton336 will you be providing the api review/recommendations only are do you also plan to implement the component?

**Comment by ibolton336** [comment]
@LHinson Ah I thought this issue only involved the API review recommendations.

**Comment by LHinson** [comment]
@ibolton336 the issue covers both. the standard initial API review/recommendations and then moves on to component implementation. I just wasn't sure if you were assigned to complete one or both.

**Comment by ibolton336** [comment]
@LHinson @rachael-phillips I can take a crack at implementing the react component for this.

**Comment by rachael-phillips** [comment]
Ok great! Thank you @ibolton336 !
