### ISSUE TITLE
Context selector menu - use instant filtering and sticky search bar

### ISSUE THREAD

**Issue by adamviktora** [patternfly/patternfly-react#9801]
Context selector menu examples should be updated in [context selector](https://www.patternfly.org/components/menus/context-selector) and in the [custom menus](https://www.patternfly.org/components/menus/custom-menus#context-selector-menu) too. Right now, it has these problems:

1. does not use instant filtering, you have to click on the search button instead (even enter key does not work)
2. when scrolling down, search bar will not stick at place

https://github.com/patternfly/patternfly-react/assets/84135613/ccb61cbd-8cca-4c00-8d6f-db80a632d052

**Expected behavior**
Similar to this [With inline search filter example](https://patternfly-react-pr-9687.surge.sh/components/menus/custom-menus/#with-inline-search-filter)

After merging https://github.com/patternfly/patternfly-react/pull/9687, and fixing this issue, we would have both _With inline search filter_ and _Context selector menu_ examples in [Custom menus page](https://www.patternfly.org/components/menus/custom-menus), both with the exact same behavior. So we should probably keep only one of these examples and delete the other one, it's questionable whether name it _With inline search filter_ or _Context selector menu_

**Comment by wise-king-sullyman** [comment]
Thanks for taking the time to write this issue up, but it sounds like this is the intended behavior of the context selector and the leads don't think it needs to be changed.
