### ISSUE TITLE
(Alert): Consume Penta tokens

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9810]
Follow up to core https://github.com/patternfly/patternfly/issues/5996

**Comment by srambach** [comment]
Just checking - @andrew-ronaldson in core, we don't show a "default" alert without any status styling, and it's not in Figma. Is this use here ok? https://patternfly-react-v6.surge.sh/components/alert/react-demos/alert-group-toast-with-notification-drawer/

**Comment by andrew-ronaldson** [comment]
We don't have a plain alerts except for the overflow version which I see in the demo already.
![image](https://github.com/patternfly/patternfly-react/assets/28658548/d60b1d4a-a900-4dca-b455-d036eb6162ad)

**Comment by andrew-ronaldson** [comment]
This is good to go!
