### ISSUE TITLE
Clean up react hooks with missing dependencies

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-react#9812]
**Describe the enhancement or change**
A clear and concise description of the request. What is the expected outcome?
There are several instances in our codebase that raise ESLint warnings where react hooks are missing dependencies from their dependency array. 

**Any other information?**
In https://github.com/patternfly/patternfly-react/pull/9484, see warnings in DatePicker.tsx and scroll down to "Unchanged files with check annotations"

**Comment by tlabaj** [comment]
Lets ignore the lines of code where this is intentional.
