### ISSUE TITLE
CodeEditor - support Mac and PC shortcuts in example

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-react#9821]
**Describe the enhancement or change**
Followup to updates made to a11y docs and conversation at https://github.com/patternfly/patternfly-org/pull/3799#discussion_r1383460463

The [with shortcut menu and main header content example](https://www.patternfly.org/components/code-editor#with-shortcut-menu-and-main-header-content) is setup to only render a list of keys as `A + B + C + n...`. It'd be beneficial to have the example show the shortcuts menu supporting both Mac and PC shortcuts.

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

**Comment by tlabaj** [comment]
Lets add a checkbox to toggle between Mac and PC shortcuts.
