### ISSUE TITLE
Bug - Table -> React demos -> Sortable-responsive - incorrect pagination in readme demo

### ISSUE THREAD

**Issue by keckrich** [patternfly/patternfly-react#9834]
**Describe the problem**
In the readme under Tables -> React demos -> [Sortable - responsive ](https://www.patternfly.org/components/table/react-demos/#sortable---responsive) in the React.useEffect 
```setSortedRows(sortedData.slice((page - 1) * perPage, page * perPage - 1));``` should be ```setSortedRows(sortedData.slice((page - 1) * perPage, page * perPage));``` because slice end is exclusive. The demo code says the pagination is pages 1-10 but only shows nine results. 

**Expected behavior**
The example code should be changed to
```typescript
React.useEffect(() => { 
    setSortedRows(sortedData.slice((page - 1) * perPage, page * perPage));
}, [sortedData, page, perPage]);
``` 

**What is your environment?**
 - Readme: Release 5.1.0

**Comment by wise-king-sullyman** [comment]
Thanks for reporting this issue! The team will address when able.
