### ISSUE TITLE
Consume core updates: Skip to content

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9857]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6088

**Comment by wise-king-sullyman** [comment]
React staging link: https://patternfly-react-v6.surge.sh/components/skip-to-content/react/basic/

This looks good to me and I don't think any changes are needed, can someone else confirm?

**Comment by srambach** [comment]
LGTM ⛷️

**Comment by lboehling** [comment]
lgtm!

**Comment by wise-king-sullyman** [comment]
Closing as it seems no changes are needed.
