### ISSUE TITLE
Consume core updates: Back to top

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9859]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6084

**Comment by wise-king-sullyman** [comment]
I think this looks good to me and it doesn't need changes, can someone else give this a look to confirm?

Staging link: https://patternfly-react-v6.surge.sh/components/back-to-top

**Comment by srambach** [comment]
🔼 LGTM! 🔝

**Comment by lboehling** [comment]
very nice! lgtm!

**Comment by wise-king-sullyman** [comment]
Closing as it seems no changes are needed.
