### ISSUE TITLE
Consume core updates: Tooltip

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9861]
Follow up to core PR https://github.com/patternfly/patternfly/pull/6064

**Comment by thatblindgeye** [comment]
Comparing alpha 34 release to core v6 staging, it doesn't look like any updates are needed. React Tooltip is using the maxwidth var value in code, but that wasn't update in Core. cc @mcoker @andrew-ronaldson @lboehling for confirmation whether the following React screenshots look good to you compared to [core's v6 tooltip](https://pf6.patternfly.org/components/tooltip)

![Basic v6 React tooltip](https://github.com/patternfly/patternfly-react/assets/70952936/8708962d-8109-4a7b-aa90-71b8bcb77726)

![v6 React Tooltip aligned left of trigger](https://github.com/patternfly/patternfly-react/assets/70952936/5870cb99-a32a-4898-a011-b10449743c4a)

![v6 React Tooltip aligned bottom-start](https://github.com/patternfly/patternfly-react/assets/70952936/16612d65-93e5-40d1-853c-708e3a57292f)

![v6 React Tooltip in dark mode](https://github.com/patternfly/patternfly-react/assets/70952936/5f3f708f-6916-4182-9765-10314727540c)

**Comment by andrew-ronaldson** [comment]
I think this is good to go. Happy to close this out if you feel good @thatblindgeye

**Comment by thatblindgeye** [comment]
Closing per above comments/agreements
