### ISSUE TITLE
Consume core updates: Popover

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9862]

**Comment by thatblindgeye** [comment]
Doesn't look like any updates needed. React's Popover uses the maxwidth and minwidth var values, but neither of those were touched in Core. cc @mcoker @andrew-ronaldson @lboehling for confirmation that the following screenshots of React v6 popover from alpha 34 release looks good compared to [core v6 popover](https://pf6.patternfly.org/components/popover#custom-alert-popover); I can also do a side by side comparison during a happy hour if it's easier

![Basic v6 React Popover](https://github.com/patternfly/patternfly-react/assets/70952936/093fdffb-d613-4b52-986d-7e8331a08639)

![v6 React Popover without padding](https://github.com/patternfly/patternfly-react/assets/70952936/48148343-2eb1-434a-91a2-5c48b8965495)

![v6 React Popover aligned at bottom start](https://github.com/patternfly/patternfly-react/assets/70952936/75144c7b-c8e8-4885-9b6e-44ad7d489912)

![v6 React Popover with danger icon](https://github.com/patternfly/patternfly-react/assets/70952936/13105138-0c55-468b-9c9a-74663d85c9a4)

**Comment by andrew-ronaldson** [comment]
Seems good to me.

**Comment by thatblindgeye** [comment]
Closing as no updates needed in React (@mcoker left a thumbs up and commented during a Penta meet)
