### ISSUE TITLE
Reselecting items in Horizontal Nav shifts spacing

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#990]
In reviewing this demo: http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/examples/page-layout-horizontal-nav/#nav-link5  I observed that when menu items are selected, there is a small movement in position/spacing of items. I think this is an artifact of the text style changing from regular to bold on mouse-down for the item which slightly changes the horizontal width of the item.

**Comment by mcarrano** [comment]
I'm still seeing this issue and think it's something we should addressed. How can we get this looked at? @rachael-phillips @LHinson

**Comment by rachael-phillips** [comment]
We should raise the priority if we want this addressed

**Comment by tlabaj** [comment]
Issue moved to [patternfly/patternfly-next #2027](https://github.com/patternfly/patternfly-next/issues/2027) via [**ZenHub**](https://www.zenhub.com/)
