### ISSUE TITLE
[Switch] - [add hasCheckIcon implementation to switch with no label]

### ISSUE THREAD

**Issue by yamalameyooooo** [patternfly/patternfly-react#9905]
**Is this a new component or an extension of an existing one?**
Switch

**Describe the feature**
add hasCheckIcon implementation to Switch with no label to hide the CheckIcon based on user input

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
No

**Any other information?**
https://github.com/patternfly/patternfly-react/pull/9904

**Comment by wise-king-sullyman** [comment]
cc @andrew-ronaldson
