### ISSUE TITLE
(Button): Consume Penta tokens

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-react#9907]
The core PR - https://github.com/patternfly/patternfly/pull/6127

* New additions are the stateful buttons. They get `.pf-m-stateful` if they are stateful, and have 3 states - `.pf-m-[read/unread/attention]`
* Stateful states should not be combined with other button variants
* `isActive` (`.pf-m-active`) is no longer used. The "clicked" (`.pf-m-clicked`) has replaced it.

**Comment by adamviktora** [comment]
Closing as this was resolved in PR https://github.com/patternfly/patternfly-react/pull/9934
