### ISSUE TITLE
Consume core Penta updates: Skeleton

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9912]
Follow up to core PR https://github.com/patternfly/patternfly/pull/6158

**Comment by thatblindgeye** [comment]
Shouldn't require any React updates. React uses the height and width CSS vars which are both still intact in Core. Since the component examples use animations it may be easier to show a side by side of alpha 51 locally vs core v6 staging in a screenshare.

**Comment by srambach** [comment]
LGTM 🦴

**Comment by thatblindgeye** [comment]
Closing per comments above + agreement from @andrew-ronaldson
