### ISSUE TITLE
Consume core Penta updates: Slider

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9913]
Follow up top core PR https://github.com/patternfly/patternfly/pull/6157

**Comment by thatblindgeye** [comment]
Shouldn't require any updates in React for Slider. There are some things related to the input groups used for examples with a value input, but those issues should be resolved by the Core issue for input group. React components use the `__value--c-form-control--width-chars`, `__value`, and `__step--Left` CSS vars, all of which are still intact in Core.

Some screenshots below of alpha 51 locally compare to the [Core v6 staging](https://pf6.patternfly.org/components/slider) cc @mcoker @andrew-ronaldson 


![Discrete slider in dark mode](https://github.com/patternfly/patternfly-react/assets/70952936/c242f068-038a-402b-91c7-35973ef30ab5)
![Discrete slider in light mode](https://github.com/patternfly/patternfly-react/assets/70952936/752423e7-18a3-4bbe-8b03-fe1af36fb4a0)

![Actions and disabled sliders in dark mode](https://github.com/patternfly/patternfly-react/assets/70952936/00209a54-5d10-4d22-9f09-a4793b1f0bc2)
![Actions and disabled sliders in light mode](https://github.com/patternfly/patternfly-react/assets/70952936/eb5fcdaa-30ad-4672-87b2-cec5e3cac75d)

Following is a slider with RTL enabled to show styling works correctly
![Slider in RTL](https://github.com/patternfly/patternfly-react/assets/70952936/ecf1a1e7-e97b-47a3-8c80-ebe4f052e204)

**Comment by srambach** [comment]
Looks good - input group should fix the inputs that don't look quite right. 🎚️

**Comment by thatblindgeye** [comment]
Closing per comments above + agreement from @andrew-ronaldson
