### ISSUE TITLE
Consume core Penta updates: Switch

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9916]

**Comment by thatblindgeye** [comment]
Doesn't look like Switch needs any updates. Screenshots of Switch using alpha 51 locally compared to the [Core v6 staging](https://pf6.patternfly.org/components/switch) cc @mcoker @andrew-ronaldson :

![Toggled off, toggled on, and with icon Switch in dark mode](https://github.com/patternfly/patternfly-react/assets/70952936/19419f83-546b-4304-a5dd-67705e56b902)
![Disabled switch in dark mode](https://github.com/patternfly/patternfly-react/assets/70952936/1d3a29d1-5b10-45a4-a02f-0c56185e83d6)

![Toggled off, toggled on, and with icon Switch in light mode](https://github.com/patternfly/patternfly-react/assets/70952936/a5b96c51-7255-40e8-b6bb-63e6e6e4e839)
![Disabled switch in light mode](https://github.com/patternfly/patternfly-react/assets/70952936/7949cb59-2a51-4a14-9ace-bf4cd113683c)

**Comment by mcoker** [comment]
@thatblindgeye LGTM

**Comment by thatblindgeye** [comment]
Closing per comments above + agreement from Andrew during group review sessions
