### ISSUE TITLE
Consume core Penta updates: Progress ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9917]
Follow up to core issue https://github.com/patternfly/patternfly/issues/5737

**Comment by tlabaj** [comment]
@andrew-ronaldson @srambach We should be able to close this one. No changes are needed in react. You can verify this looks correct here.
https://patternfly-react-v6.surge.sh/components/progress

**Comment by srambach** [comment]
LGTM thank you! 🤓

**Comment by lboehling** [comment]
lgtm!
