### ISSUE TITLE
Consume core Penta updates: Truncate

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9918]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6143

**Comment by tlabaj** [comment]
@andrew-ronaldson @srambach We should be able to close this one. No changes are needed in react. You can verify this looks correct here https://patternfly-react-v6.surge.sh/components/truncate

**Comment by srambach** [comment]
Looks good to me! 😀

**Comment by lboehling** [comment]
lgtm!
