### ISSUE TITLE
Consume core Penta updates: Divider

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9919]
follow up to core issue https://github.com/patternfly/patternfly/issues/6136

**Comment by kmcfaul** [comment]
Horizontal divider needs no changes. 
Vertical divider needs a core fix (not displaying in a flex layout on react examples and [core examples](https://pf6.patternfly.org/components/card/html-demos/#aggregate-status-card)).

Keeping issue open for now until core update with the fix goes in.

**Comment by mcoker** [comment]
@kmcfaul @tlabaj this should be fixed in core, we added an example of the divider in a flex layout here - https://pf6.patternfly.org/components/divider#in-flex-layout
