### ISSUE TITLE
Consume core Penta updates: Backdrop

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9920]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6137

**Comment by tlabaj** [comment]
@andrew-ronaldson @srambach We should be able to close this one.  No changes are needed in react.  You can verify this looks correct here.
https://patternfly-react-v6.surge.sh/components/backdrop

**Comment by srambach** [comment]
LGTM! 🥇

**Comment by andrew-ronaldson** [comment]
Agreed, thanks!
