### ISSUE TITLE
Consume core updates: Notification Drawer ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9923]
Follow up to core issue https://github.com/patternfly/patternfly/issues/5714
Also depend on core issue https://github.com/patternfly/patternfly/issues/6162 for menu styling

**Comment by andrew-ronaldson** [comment]
I don't see any react follow up based on the Core examples

**Comment by tlabaj** [comment]
@mcoker @srambach Can one of you verify this looks god in React.

**Comment by mcoker** [comment]
LGTM! 👍
