### ISSUE TITLE
Consume core Penta updates: Data list

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9925]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6106

**Comment by kmcfaul** [comment]
DataList itself looks like no updates are required. The only discrepancy between v6 react and core is that the menu toggles are different. Core is using a `pf-v5-c-dropdown__toggle pf-m-plain` toggle while react uses `pf-v5-c-menu-toggle pf-m-plain` which has a rounded border.

**Comment by kmcfaul** [comment]
menu toggle style updates are in and look good, react changes are still unneeded. The issue with the core side using dropdown-toggle is tracked https://github.com/patternfly/patternfly/issues/6207

**Comment by kmcfaul** [comment]
@patternfly/design-reviewers 
@patternfly/core-in-react-reviewers 

Could we get design+core eyes to ensure DataList looks good on the react side?

**Comment by andrew-ronaldson** [comment]
looks good as is!
Thanks for checking

**Comment by kmcfaul** [comment]
Just need core once-over @patternfly/core-in-react-reviewers

**Comment by mcoker** [comment]
LGTM! I noted one small update we'll want to make in a separate issue - https://github.com/patternfly/patternfly-react/issues/10119
