### ISSUE TITLE
Consume core updates: Breadcrumb ( Follow up to issue)

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9927]
Follow up to core issue https://github.com/patternfly/patternfly/issues/5731

Also depend on core issue https://github.com/patternfly/patternfly/issues/6162 for menu styling

**Comment by andrew-ronaldson** [comment]
![Screenshot 2024-02-20 at 2 36 48 PM](https://github.com/patternfly/patternfly-react/assets/28658548/4d1a6d38-f232-499c-8e70-07626df9bb58)
The only thing I noticed was the hover state on this dropdown that doesn't appear in Core. Is that waiting for a menu toggle update? @srambach @mcoker

**Comment by srambach** [comment]
Core is still using a dropdown there; https://github.com/patternfly/patternfly/issues/6207 should change that over to a menu-toggle.

**Comment by mcoker** [comment]
In chatting with @lboehling about it yesterday, she said that ideally there would be no background color applied to that toggle. We have a button variation that does that, but not a menu toggle variation. For now I was thinking we can just push a CSS update that removes the background for that toggle so no update would need to be made in react. Maybe later we can see if there is a good case for adding that variation as a menu toggle?

**Comment by mcoker** [comment]
Breadcrumb lgtm otherwise!
