### ISSUE TITLE
Remove lodash dependency from charts + table

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#9942]
Lodash is no longer a supported library. (no new releases since 2016)

Some of these might be replaceable with built-in APIs depending on the browser support target. For example lodash/cloneDeep could be replaced with [structuredClone()](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone).

It's only a dependency in charts + table right now.

**Comment by dlabrecq** [comment]
Note that lodash will still be installed via Victory. And since lodash is already installed, we have been using it throughout the charts package. I would recommend leaving the charts package as is, considering Victory's dependency.
