### ISSUE TITLE
Update workspace to use latest version of yarn (not yarn v1)

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react#9959]
New features in Yarn (or PNPM for that matter) is the workspace: protocol, which allows us to refer to workspace dependencies without needing to specify an exact version. This reduces the chances of merge conficts when these versions are bumped.

See:

- https://yarnpkg.com/features/workspaces#cross-references
- https://pnpm.io/workspaces#workspace-protocol-workspace
- https://lerna.js.org/docs/recipes/using-pnpm-with-lerna
- https://yarnpkg.com/getting-started/install#updating-yarn

(reported/suggested by @jonkoops who has offered to be a resource)

**Comment by jonkoops** [comment]
@nicolethoen could you pin this issue so the stale bot doesn't keep tagging this?
