### ISSUE TITLE
Bug -ClipboardCopy - Regression in 5.2.0 prerelease

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-react#9962]
**Describe the problem**
While the ClipboardCopy is expanded, any changes to its content made are not reflected in the main section (and copy action)

**How do you reproduce the problem?**
https://codesandbox.io/p/sandbox/epic-danilo-t9lft3?file=%2Findex.tsx%3A17%2C7

**Expected behavior**
While the component is expanded, I would expect changes made to its content to reflect both in the expanded as well as the main portion of the component.

**Is this issue blocking you?**
No, we can make our component not expandable for the time being as a workaround

**What is your environment?**
 - OS: MacOS
 - Browser Saw both in FF and Chrome

**What is your product and what release date are you targeting?**
OCM: Now

**Any other information?**
It's cold today

**Comment by tlabaj** [comment]
I put up a PR so it behaves as it did before and does not break your use case.
