### ISSUE TITLE
Consume core Penta updates: Drawer

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9979]
follow up to core https://github.com/patternfly/patternfly/pull/6183

The following was done with core bump PR #10017 

- Removed light color variant form DrawerColorVariant
- disabled out color variant unit test
- removed color variant from drawer integration demo
- disabled drawer background variant integration test
- Removed light variant from Modal with drawer Wizard Demos and In page with drawer wizard Demos
- Removed light variant from drawer panel wizard test
- Removed light variant from WizardWithDrawer example
- disabled failing integration test

**Comment by thatblindgeye** [comment]
Closed by #10036
