### ISSUE TITLE
Consume Penta tokens: Menu toggle

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9986]
Follow up to core PR https://github.com/patternfly/patternfly/pull/6177

**Comment by thatblindgeye** [comment]
Shouldn't need any React updates to MenuToggle when comparing v6 core Menu Toggle to v6 React Menu Toggle. cc @mattnolting @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
@thatblindgeye i think this looks good as is. Thanks!

**Comment by thatblindgeye** [comment]
Going to use this issue to go towards updates being made in https://github.com/patternfly/patternfly/pull/6321

**Comment by tlabaj** [comment]
closed by #10097
