### ISSUE TITLE
Consume core Penta updates: Tile

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-react#9992]
Follow up to core issue https://github.com/patternfly/patternfly/issues/6197

**Comment by wise-king-sullyman** [comment]
React staging link: https://patternfly-react-v6.surge.sh/components/tile

This looks good to me and I don't think any changes are needed, can someone else confirm?

**Comment by srambach** [comment]
This is pre-existing, but can there be space between tiles in the basic examples and also in the demos? I don't think we really want them touching anymore, do we? @andrew-ronaldson @lboehling 

Otherwise it looks fine to me.

**Comment by wise-king-sullyman** [comment]
@srambach do you just mean by adding some example specific CSS like what's in the core repo?

**Comment by andrew-ronaldson** [comment]
Agreed with the spacer comment.

**Comment by wise-king-sullyman** [comment]
Closed by #10040
